### ISSUE TITLE
cli needs a command that outputs nicely formatted environment information for debugging

### ISSUE THREAD

**Issue by stephenfeather** [NativeScript/nativescript-cli#1001]
### Summary
Having just posted an issue and realized just how ugly the output from --log trace is and how difficult it is to read that in an issue (yet important information for debugging), believe that a cli command that would show environments, 3rd party tooling version information, nativescript versions, etc in a way that is compact and easy enough to cut/paste into issues and be readable.

It be nice to get the system information portion of --log trace 

```
System information:
{ procInfo: 'nativescript/1.4.0-non-ci',
  platform: 'darwin',
  os: 'Darwin Stephens-iMac.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.6',
  npmVer: '2.13.2',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.0.1\nBuild version 7A1001\n',
  itunesInstalled: true,
  cocoapodVer: '0.38.2\n',
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: '4.2.0',
  gitVer: '2.6.0',
  gradleVer: '2.7',
  javacVersion: '1.8.0_51' }
```
without sifting through the entire console.

**Comment by ligaz** [comment]
Merging this issue into https://github.com/NativeScript/nativescript-cli/issues/54
