### ISSUE TITLE
Removing a plugin should remove frameworks copied into {project}/lib

### ISSUE THREAD

**Issue by stephenfeather** [NativeScript/nativescript-cli#1003]
### Summary

If a plugin is removed, frameworks and libraries copied into the project lib folder should be removed. The average nativescript user is not going to know they need to be manually cleaning all this up.
### System information

```
{ procInfo: 'nativescript/1.4.0-non-ci',
  platform: 'darwin',
  os: 'Darwin Stephens-iMac.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.6',
  npmVer: '2.13.2',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.0.1\nBuild version 7A1001\n',
  itunesInstalled: true,
  cocoapodVer: '0.38.2\n',
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: '4.2.0',
  gitVer: '2.6.0',
  gradleVer: '2.7',
  javacVersion: '1.8.0_51' }
```

**Comment by teobugslayer** [comment]
Hi @sfeather,

You are correct that a cleanup is needed. That said, things like un-merging application  info.plist and Androidmanifest.xml are not easy to be done manually. We have brainstormed some solutions and will implement them gradually.

**Comment by dtopuzov** [comment]
Still valid in {N} 2.0.1.
Steps to reproduce:
tns create TestApp
tns plugin add nativescript-iqkeyboardmanager
tns build ios -> pods are copied to /platforms/ios
tns plugin remove nativescript-iqkeyboardmanager
tns build ios -> pods are still in /platforms/ios (expected: no pods in /platforms/ios)

**Comment by pkoleva** [comment]
Not relevant anymore as we do not have lib folder anymore (v 2.5.0)
