### ISSUE TITLE
Suggest an 'update' command for plugins

### ISSUE THREAD

**Issue by sfeather** [NativeScript/nativescript-cli#1004]
### Summary

Removing/Adding an already installed plugin is tedious just to pick up changes from an npm repo (or local directory) and being sure we aren't leaving any vestigial parts floating around in the project is tedious.

Should be able to update a single plugin or possibly all plugins previously installed in a project.

**Comment by Fatme** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/526
