### ISSUE TITLE
Cannot install with node 4.1.1

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1014]
_From @kononenko-a-m on October 5, 2015 19:4_

Hi! Cannot install NativeScript with node 4.1.1 in Windows.

_Copied from original issue: NativeScript/NativeScript#887_

**Comment by rosen-vladimirov** [comment]
Hi  @kononenko-a-m,
We are working on this issue, hopefully we'll be ready to provide support for Node 4.1.x+ versions very soon.
You can follow the progress of the issue [here](https://github.com/NativeScript/nativescript-cli/issues/958).
