### ISSUE TITLE
tns build android --compileSdk 17 returns bad error message

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1021]
```
tns build android --compileSdk 17 
```
returns bad error message:

```
[31;1mYou need to have the latest Android Support Repository installed on your system.[0m
```
This error can not be solved by installing latest Android Support Repository, here is the full log:
```
Versions found in /Users/topuzov/Tools/adt-bundle/sdk/build-tools are 19.1.0, 21.1.2, 22.0.1, 23.0.0
Selected targetSdk is: 17
Versions found in /Users/topuzov/Tools/adt-bundle/sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0
Selected AppCompat version is: null
[31;1mYou need to have the latest Android Support Repository installed on your system.[0m
```

**Comment by dtopuzov** [comment]
Not fixed. Current master:

Directories found in /Users/topuzov/Tools/adt-bundle/sdk/build-tools are 19.1.0, 21.1.2, 22.0.1, 23.0.0, android-4.4W
Versions found in /Users/topuzov/Tools/adt-bundle/sdk/build-tools are 19.1.0, 21.1.2, 22.0.1, 23.0.0
Selected targetSdk is: 17
Directories found in /Users/topuzov/Tools/adt-bundle/sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in /Users/topuzov/Tools/adt-bundle/sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0
Selected AppCompat version is: undefined
Error: You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
    at Object.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/lib/nativescript-cli.js:7:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

It looks SDK 17 is not available in support repository, so we should return some appropriate error massage, may be something like "You selected compile idk 17, but it is not available on your system."

**Comment by Plamen5kov** [comment]
The message in CLI 1.6.1 is: 
```
You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
```
Which is fine because:
* it's in the changelog: https://docs.nativescript.org/releases/CLI#140-2015-october-07
* it's in the docs here: https://github.com/NativeScript/nativescript-cli
