### ISSUE TITLE
Plugin add ./myPlugin --path <path to application> add plugin relative to the location where the command was executed instead of relative to the location of the package.json.

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#1023]
Due to issue in npm `tns plugin add ./myPlugin --path <path to application>` does not save the plugin in package.json with local path.

The produced package.json is:
```
{
   dependnecies: {
         "myPlugin": "<version>"
   }
}
```

The expected package.json is:
```
{
   dependnecies: {
         "myPlugin": "file:./myPlugin"
   }
}
```
Tested on Windows with `npm 2.11.3`, `npm 2.14.4` and `npm 3.3.5`
Tested on OSX with `npm 2.14.4`

**Comment by PanayotCankov** [comment]
On my mac it currently saves the path as relative to the location where the command was executed instead of relative to the location of the package.json.

**Comment by dtopuzov** [comment]
Known issue
