### ISSUE TITLE
tns platform add android - Error: spawn REG ENOENT

### ISSUE THREAD

**Issue by FabioThe1** [NativeScript/nativescript-cli#1029]
Windows 10 Pro
Nodejs 0.10.40
Java jdk1.8.0_45
Android SDK all required installed
Gradle 2.3
Paths all set and check 100 times

tns doctor: no error shown
tns create AppName: works greate

tns plattform add android:
Error: spawn REG ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
at child_process.js:1144:20
ar process._tickCallback (node.js:355:11)

I already searched for this error but havent found any solution. Im asking you for Help.

**Comment by rosen-vladimirov** [comment]
Hi @FabioThe1,
May I ask you to try cleaning your npm cache and see if it helps:
```
npm cache clean
```
If you still have the problem, can you do the following:
* Locate the installation folder of nativescript-cli (`which tns` should help you)
* Locate config directory inside nativescript-cli installation directory.
* Edit `config.json` inside config directory and set DEBUG to true
* Try your steps again, but for platform add use:
```
tns platform add android --log trace > out.txt 
```
And send us the out.txt file.

I'm looking forward to hearing from you.

**Comment by teobugslayer** [comment]
In addition to @rosen-vladimirov's suggestions, please check your PATH environment variable. Make sure that Windows system directory and Windows directory are the **first** entries in there.

**Comment by FabioThe1** [comment]
@rosen-vladimirov Thanks for your fast answer. I tryed your suggestion and it still doesn't work. THe Problem is when I run "tns platform add android --log trace > out.txt" the textfile is created but the file is empty.
@teobugslayer Which directoried do you mean? Does the order of the Path entries matter?

**Comment by FabioThe1** [comment]
@rosen-vladimirov Since debug mode is on the "tns doctor" command has longer output. Maybe you can help me finding the error.
tns doctor output:

Exec npm -v
stdout: 2.11.3 
 
stderr: 
spawn: java -version

Exec ant -version
stdout:
stderr: 'ant' is not recognized as an internal or external command,
operable program or batch file.


Exec node-gyp -v 
 
stdout:  
 
stderr: 'node-gyp' is not recognized as an internal or external command,
operable program or batch file.


Exec adb version 
 
stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

stderr: 

Exec android -h 
 
stdout:
    	Usage:
       
	android [global options] action [action options]

       	Global options:
  
  -s --silent     : Silent mode, shows errors only.
  
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     
     --clear-cache: Clear the SDK Manager repository manifest cache.
 
  -h --help       : Help on a specific command.

                                                                    
Valid
 actions
 are
 composed
 of a verb
 and an
 optional
 direct
 object:

-    sdk              : Displays the SDK Manager window.

-    avd              : Displays the AVD Manager window.

-   list              : Lists existing targets or virtual devices.

-   list avd          : Lists existing Android Virtual Devices.

-   list target       : Lists existing targets.

-   list device       : Lists existing devices.

-   list sdk          : Lists remote SDK repository.

- create avd          : Creates a new Android Virtual Device.

-   move avd          : Moves or renames an Android Virtual Device.

- delete avd          : Deletes an Android Virtual Device.

- update avd          : Updates an Android Virtual Device to match the folders
 of a new SDK.

- create project      : Creates a new Android project.

- update project      : Updates an Android project (must already have an
 AndroidManifest.xml).

- create test-project : Creates a new Android project for a test package.

- update test-project : Updates the Android project for a test package (must
 already have an AndroidManifest.xml).

- create lib-project  : Creates a new Android library project.

- update lib-project  : Updates an Android library project (must already have
 an AndroidManifest.xml).

- create uitest-project: Creates a new UI test project.

- update adb          : Updates adb to support the USB devices declared in the
 SDK add-ons.

- update sdk          : Updates the SDK by suggesting new platforms to install
 if available.
 
 

stderr: 'xcopy' is not recognized as an internal or external command,
operable program or batch file.


Exec mono --version 
 
stdout:  
 
stderr: 'mono' is not recognized as an internal or external command,
operable program or batch file.


Exec git --version 
 
stdout: git version 2.6.1.windows.1
 
 
stderr: 
Exec gradle -v 
 
stdout: 

------------------------------------------------------------

Gradle 2.3

------------------------------------------------------------



Build time:   2015-02-16 05:09:33 UTC

Build number: none

Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274



Groovy:       2.3.9

Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013

JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)

OS:           Windows 10 10.0 amd64

 
 stderr: 

Exec javac -version 
 
stdout:  
 
stderr: javac 1.8.0_60


System information:

{ procInfo: 'nativescript/1.3.0',

  platform: 'win32',

  os: 'Windows 10 Pro 6.3.10240',

  shell: 'C:\\WINDOWS\\system32\\cmd.exe',

  dotNetVer: '4.6.00079',

  procArch: 'x64',

  nodeVer: 'v0.12.7',

  npmVer: '2.11.3',

  javaVer: '1.8.0',

  antVer: null,

  nodeGypVer: null,

  xcodeVer: null,

  itunesInstalled: false,

  adbVer: 'Android Debug Bridge version 1.0.32',

  androidInstalled: true,

  monoVer: null,

  gitVer: '2.6.1.windows.1',

  gradleVer: '2.3',

  javacVersion: '1.8.0_60' }

Starting watch on killswitch C:\Users\Fabio\AppData\Local\Temp\Fabio\KillSwitches\cli

Initializing analytics statuses.


Analytics statuses: 

{ TrackFeatureUsage: 1, TrackExceptions: 0 }

Trying to track feature 'Non-interactive' with value 'doctor'.

BeforeHookName for command doctor is before-doctor

AfterHookName for command doctor is after-doctor

Looking for project in 'C:\WINDOWS\system32'

Looking for project in 'C:\WINDOWS'

Looking for project in 'C:\'

No project found at or above 
'C:\WINDOWS\system32'.


WARNING: Apache Ant is not installed or is not configured properly.
You will not be able to build your projects for Android.
To be able to build for Android, download and install Apache Ant and
its dependencies as described in http://ant.apache.org/manual/index.html


TIP: To avoid setting up the necessary environment variables, you can use the chocolatey package manager to install the Android SDK and its dependencies.


WARNING: You can work with iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.


Exec android list targets 
 
stdout: Available Android targets:

----------

id: 1 or "android-17"

     Name: Android 4.2.2

     Type: Platform

     API level: 17

     Revision: 3

     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 
 Tag/ABIs : default/armeabi-v7a, default/mips, default/x86

----------

id: 2 or "android-22"
 
    Name: Android 5.1.1

     Type: Platform

     API level: 22

     Revision: 2

     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in

 Tag/ABIs : default/armeabi-v7a, default/x86, default/x86_64

----------

id: 3 or "android-23"

     Name: Android 6.0

     Type: Platform

     API level: 23

     Revision: 1

     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in

 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, default/armeabi-v7a, default/x86, default/x86_64

----------
id: 4 or "Google Inc.:Google APIs:17"

     Name: Google APIs

     Type: Add-On

     Vendor: Google Inc.

     Revision: 4

     Description: Android + Google APIs

     Based on Android 4.2.2 (API level 17)

     Libraries:

      * com.android.future.usb.accessory (usb.jar)

          API for USB Accessories

      * com.google.android.media.effects (effects.jar)

          Collection of video effects

      * com.google.android.maps (maps.jar)

          API for Google Maps

     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in

 Tag/ABIs : default/armeabi-v7a

----------
id: 5 or "Google Inc.:Google APIs:22"

     Name: Google APIs

     Type: Add-On

     Vendor: Google Inc.

     Revision: 1

     Description: Android + Google APIs

     Based on Android 5.1.1 (API level 22)

     Libraries:

      * com.android.future.usb.accessory (usb.jar)

          API for USB Accessories

      * com.google.android.media.effects (effects.jar)

          Collection of video effects

      * com.google.android.maps (maps.jar)

          API for Google Maps

     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in

 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64

----------
id: 6 or "Google Inc.:Google APIs:23"

     Name: Google APIs

     Type: Add-On

     Vendor: Google Inc.

     Revision: 1

     Description: Android + Google APIs

     Based on Android 6.0 (API level 23)

     Libraries:

      * com.android.future.usb.accessory (usb.jar)

          API for USB Accessories

      * com.google.android.media.effects (effects.jar)

          Collection of video effects

      * com.google.android.maps (maps.jar)

          API for Google Maps

     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in

 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64


 
 stderr: 'xcopy' is not recognized as an internal or external command,
operable program or batch file.

Versions found in C:\Users\Fabio\AppData\Local\Android\android-sdk\build-tools are 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1
Selected targetSdk is: 22
Versions found in C:\Users\Fabio\AppData\Local\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1
Selected AppCompat version is: 22.2.1
These warnings are just used to help the NativeScript maintainers with debugging if you file an issue.
Please ignore them if everything you use NativeScript for is working fine.

**Comment by teobugslayer** [comment]
Hello @FabioThe1,

the log says that bot reg.exe and xcopy.exe are missing. Please verify that your windows and windows system directories are correctly set in PATH environment variable as **first** entries

**Comment by FabioThe1** [comment]
@teobugslayer Solved Thanks!

**Comment by d4rkd0s** [comment]
> Hello @FabioThe1,
> 
> the log says that both reg.exe and xcopy.exe are missing. Please verify that your windows and windows system directories are correctly set in PATH environment variable as **first** entries

Can you explain how this would look? and what the "windows" and "windows system directories" paths actually are?

**Comment by d4rkd0s** [comment]
> @teobugslayer Solved Thanks!

What did you do to solve this? I'm on Windows using android and struggling.
