### ISSUE TITLE
tns platform add android faile with java path not found and It's impossible

### ISSUE THREAD

**Issue by NelsonRock** [NativeScript/nativescript-cli#1040]
I have a issue:

When I do tns platform add android -> reponse java is not set to your path

All android support and library installed, 22, 23, android sdk builds tools 22, 23 as well

I'have installed node by nvm package manager , i have used node version 10.30, 10.35, 12.07 and reinstalled nativescript client in every version of node

Following path config in .bashrc

gradle path

GRADLE_HOME=/usr/share/gradle-2.3
PATH=$PATH:$GRADLE_HOME/bin
export GRADLE_HOME
export PATH

android path

ANDROID_HOME=/usr/share/android-sdk-linux
PATH=$PATH:$ANDROID_HOME/tools:ANDROID_HOME/platform-tools
export ANDROID_HOME
export PATH

java path

JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
export JAVA_HOME
export JRE_HOME 
export PATH

I paste the resultat from tns platform add android --log trace

nelson@developpeur:~/github/node/tes1$ tns platform add android --log trace
Exec uname -a 
stdout: Linux developpeur 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

stderr: 
Exec npm -v 
stdout: 1.4.28

stderr: 
spawn: java -version
Exec ant -version 
stdout:

stderr: /bin/sh: 1: ant: Permission denied

Exec node-gyp -v 
stdout: v0.12.2

stderr: 
Exec adb version 
stdout:

stderr: /bin/sh: 1: adb: not found

Exec android -h 
stdout: 
Usage:
android [global options] action [action options]
Global options:
-s --silent : Silent mode, shows errors only.
-v --verbose : Verbose mode, shows errors, warnings and all messages.
--clear-cache: Clear the SDK Manager repository manifest cache.
-h --help : Help on a specific command.

                                                                Valid
                                                                actions
                                                                are
                                                                composed
                                                                of a verb
                                                                and an
                                                                optional
                                                                direct
                                                                object:
sdk : Displays the SDK Manager window.
avd : Displays the AVD Manager window.
list : Lists existing targets or virtual devices.
list avd : Lists existing Android Virtual Devices.
list target : Lists existing targets.
list device : Lists existing devices.
list sdk : Lists remote SDK repository.
create avd : Creates a new Android Virtual Device.
move avd : Moves or renames an Android Virtual Device.
delete avd : Deletes an Android Virtual Device.
update avd : Updates an Android Virtual Device to match the folders of a new SDK.
create project : Creates a new Android project.
update project : Updates an Android project (must already have an AndroidManifest.xml).
create test-project : Creates a new Android project for a test package.
update test-project : Updates the Android project for a test package (must already have an AndroidManifest.xml).
create lib-project : Creates a new Android library project.
update lib-project : Updates an Android library project (must already have an AndroidManifest.xml).
create uitest-project: Creates a new UI test project.
update adb : Updates adb to support the USB devices declared in the SDK add-ons.
update sdk : Updates the SDK by suggesting new platforms to install
if available.

stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar

Exec mono --version 
stdout:

stderr: /bin/sh: 1: mono: not found

Exec git --version 
stdout: git version 2.1.4

stderr: 
Exec gradle -v

stdout:

Gradle 2.3

Build time: 2015-02-16 05:09:33 UTC
Build number: none
Revision: 586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy: 2.3.9
Ant: Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM: 1.8.0_45-internal (Oracle Corporation 25.45-b02)
OS: Linux 3.19.0-30-generic amd64

stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar

Exec javac -version 
stdout:

stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
javac 1.8.0_60

TypeError: Cannot read property '1' of null
at FiberFuture.Future.wait (/home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
at /home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/lib/nativescript-cli.js:17:45
- - - - -
at SysInfo.getSysInfo (/home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/lib/common/sysinfo.js:63:75)
at /home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/lib/common/dispatchers.js:21:46
at Function.settle (/home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
at FiberFuture.Future.wait (/home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
at /home/nelson/.nvm/v0.10.35/lib/node_modules/nativescript/lib/nativescript-cli.js:17:45

**Comment by teobugslayer** [comment]
Hello @NelsonRock,
We had an issue in which we did not detect correctly Java version. It should be fixed in the upcoming 1.4.0 release (see https://github.com/NativeScript/nativescript-cli/issues/936). If you cannot wait until it is out, you can just manually change the faulty regexp'es in the code - just see the fixed code.

Incidentally, I saw that you are missing adb as well. Can you verify that tools and platform-tools directories of Android SDK are added to the PATH?

**Comment by NelsonRock** [comment]
Thank so much; 

With this manually change is work perfect!

I had an error in my path, an $ dolar sing missing in ANDROI_HOME variable

I have installed ant and without making any variable system it just work great.

You are great! Keep working.

**Comment by Fatme** [comment]
Glad to hear that it works! I'm going to close this issue, if you have any problems feel free to open an another issue.
