### ISSUE TITLE
Not able to install in OS X El Capitan

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/nativescript-cli#1043]
Trying to complete the installation and i get a lot of errors after typing npm i -g native script. I followed the setup guide.

**Comment by Fatme** [comment]
Can you send us the installation log?

**Comment by alexrainman** [comment]
Downgraded node to version 0.12.* and that solved the problem. Thanks

**Comment by teobugslayer** [comment]
Great that you find the solution! We already support node.js 4.1.1 in the master branch and one of our next releases will include this change.

**Comment by alexrainman** [comment]
I have a question for you. Is this the right place to do it? Its related to the http module and the way it is implemented. I want to have some details about it. Thanks

**Comment by alexrainman** [comment]
I got the answer myself. I see that in iOS you use NSUrlSession and that you are planning to implement OkHttp for Android. Awesome, OkHttp is way faster.
