### ISSUE TITLE
Bad error message when try to build not existing app

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1056]
Bad error message when try to build not existing app

Steps to reproduce:
Make sure you have no {N} app in current folder and run:
node_modules/.bin/tns build ios --release

Result:
Cannot read property 'split' of undefined

**Comment by Fatme** [comment]
This happens when the folder contains corrupted package.json 
```
{
	"nativescript": {
		
	}
}
```
