### ISSUE TITLE
Is a custom Android library still supported in plugins?

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/nativescript-cli#1059]
Hi all,

With {N} 1.2 I was able to add an Android library (zxing) like this: https://github.com/EddyVerbruggen/nativescript-barcodescanner/tree/master/platforms/android/LibraryProject

`tns plugin add nativescript-barcodescanner` correctly added the lib to the project.

With 1.3 (and 1.4.1) the library no longer seems to be resolved. With the exact same plugin code, resolving a class in the zxing library fails (https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/4).

Has this broken due to the build system moving to Gradle in 1.3.0? If so, I'm guessing I need to transform the LibraryProject into an .aar file. If that's the case: can someone provide me with the required steps to do so perhaps?

Thanks a bunch,
Eddy

**Comment by Fatme** [comment]
Hi @EddyVerbruggen,

{N} CLI 1.3+ version doesn't support ant projects (libraries with project.properties) from plugin. You need to add the library as .jar or .aar.

**Comment by Mararesliu** [comment]
build system did moving to Gradle from 1.3,  I generate apk success by maually complie LibraryProject to jar and add to platform/android/libs, but the other error happen.
java.lang.RuntimeException: Unable to start activity
ComponentInfo(org.nativescript.barcode/com/google.zxing.client.android.CaptureActivity);
android.content.res.Resources$NotFoundException: Resource ID #0x0

**Comment by EddyVerbruggen** [comment]
@Fatme That's great, progress! I guess I'll have to find out how to upgrade the LibraryProject to an .aar then..

**Comment by Mararesliu** [comment]
Hi all,
plugin jar will auto include from plugin's below directory, and auto merge android AndroidManifest.xml, But what about the plugin's resource?

**Comment by Mararesliu** [comment]
ok, i know i need .aar

**Comment by EddyVerbruggen** [comment]
@Mararesliu Today I created the [barcodescanner aar](https://github.com/EddyVerbruggen/barcodescanner-lib-aar), and I've just released version 1.1.0 of the [nativescript-barcodescanner plugin](https://www.npmjs.com/package/nativescript-barcodescanner) which is no compatible with NativeScript 1.3+ on Android.

**Comment by rolandorocha** [comment]
Hi @EddyVerbruggen. 
Do you have some ideas to solve this issue? I think this is a great plugin and will be great if it would be supported in next versions of nativescript.
