### ISSUE TITLE
No error message when deploy failed due to no space available

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1060]
No error message when deploy failed due to no space available

CLI Output:
This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Project successfully built
Using  /Users/topuzov/Git/PushNotificationApp/platforms/android/build/outputs/apk/PushNotificationApp-debug.apk
Successfully deployed on device with identifier 'emulator-5554'

Actual result: App is not deployed, because there is no free space on emulator

Adb:
TOPUZOVMAC:PushNotificationApp topuzov$ adb install /Users/topuzov/Git/PushNotificationApp/platforms/android/build/outputs/apk/PushNotificationApp-debug.apk
1111 KB/s (15404924 bytes in 13.530s)
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
	pkg: /data/local/tmp/PushNotificationApp-debug.apk
Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]

**Comment by NickIliev** [comment]
I have reproduced this exact problem with version 1.7.0

**Comment by surdu** [comment]
This is somewhat happening again with version 4.0. There is a text output indicating there is a problem, but it's not triggering an error and out CI environment just hangs:

The following are the last log lines when running `tns test android --justlaunch --log trace`
```
spawn: /usr/local/share/android-sdk/platform-tools/adb "-s" "emulator-5554" "install" "-r" "/Users/distiller/ourApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk"
Result when throw error is false:
{ stdout: '',
  stderr: 'adb: failed to install /Users/distiller/ourApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]\n',
  exitCode: 1 }
Error name: INSTALL_FAILED_INSUFFICIENT_STORAGE result code: -4
The package manager service found that the device didn't have enough storage space to install the app.
Unable to apply changes on device: emulator-5554. Error is: The package manager service found that the device didn't have enough storage space to install the app..
Project dir from hooksArgs is: /Users/distiller/ourApp.
Hooks directories: [ '/Users/distiller/ourApp/node_modules/nativescript/lib/hooks',
  '/Users/distiller/ourApp/node_modules/nativescript/lib/common/hooks',
  '/Users/distiller/ourApp/hooks' ]
AfterHookName for command watch is after-watch
Project dir from hooksArgs is: /Users/distiller/ourApp.
Hooks directories: [ '/Users/distiller/ourApp/node_modules/nativescript/lib/hooks',
  '/Users/distiller/ourApp/node_modules/nativescript/lib/common/hooks',
  '/Users/distiller/ourApp/hooks' ]
AfterHookName for command liveSync is after-liveSync
Too long with no output (exceeded 10m0s)
```
