### ISSUE TITLE
CSS not applied with NativeScript 1.4.1

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-cli#1062]
When I create a project from scratch using NativeScript 1.4.1 and run it on Samsung Edge+ (Android 5.1.1) app.css doesn't seem to be applied.

I have not tested it on any other device.

However when I build and run my older projects that were created with {N} 1.3 the css seems to be working fine.

**Comment by vchimev** [comment]
This issue was moved to NativeScript/NativeScript#939
