### ISSUE TITLE
bind.node is missing. try reinstalling prebuilt

### ISSUE THREAD

**Issue by nraboy** [NativeScript/nativescript-cli#1077]
I am experiencing the following:

```
$ tns platform add ios
`/usr/local/lib/node_modules/nativescript/node_modules/ref-struct/node_modules/ref/bin/darwin-x64-v8-3.28/binding.node` is missing. Try reinstalling `prebuilt`?
```

This happens when I try to add either the iOS or Android platforms.  Information about my setup is as follows:

Node: 0.12.4
TNS: 1.4.2
Mac OS: 10.11
Xcode: 7

I saw this issue as resolved in the issue tracker, but it doesn't seem to be resolved.

Any insight appreciated.

Thanks,

**Comment by Fatme** [comment]
Hi @nraboy,

It seems that you've installed {N} CLI with node version different from 0.12.4 but you're trying to use it with node 0.12.4. 

I suggest you to remove the old {N} CLI and install it again.

**Comment by nraboy** [comment]
Not true.  I had 0.12.4 before I tried to install the NativeScript CLI and I had 0.12.4 after I tried to install the NativeScript CLI.  In other words, my Node version is the same it has always been.

I have tried to remove NativeScript and install again, but this has happened without luck.

Best,

**Comment by Fatme** [comment]
@nraboy sorry to hear that.

Unfortunately, I wasn't able to reproduce the problem. Can you execute `tns platform add ios --log trace` and send us the log file? Also can you zip `/usr/local/lib/node_modules/nativescript/` and send us the archive?

**Comment by nraboy** [comment]
After speaking with various NativeScript developers they recommended I make use of NVM to manage multiple versions of Node.

I did this and installed 0.12.7.  I no longer receive issues when adding the iOS platform, but I get issues when trying to add the Android platform.

Since this is a different issue, I've created a new ticket at https://github.com/NativeScript/nativescript-cli/issues/1097

You can close this ticket if you want since the bind issue appears to be isolated to only me.
