### ISSUE TITLE
Can no longer debug on iOS after upgrading to 1.4.2

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/nativescript-cli#1078]
Debugging no longer works on the iOS emulator or an iPhone device after upgrading to 1.4.2

Here are the last few lines of output.

```
Setting up debugger proxy...
Press Ctrl + C to terminate, or disconnect.

Frontend client connected.
Backend socket created.
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:749:11)
    at Socket.Readable.resume (_stream_readable.js:734:3)
    at /usr/local/lib/node_modules/nativescript/lib/services/ios-debug-service.js:304:28
    at Socket.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios-debug-service.js:58:13)
    at Socket.emit (events.js:92:17)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/ios-device.js:272:62
    at process._tickCallback (node.js:442:13)
```

Additionally, when debugging on device, this message appears:

<img width="532" alt="screen shot 2015-10-16 at 8 14 24 pm" src="https://cloud.githubusercontent.com/assets/1638579/10555782/a066a556-7442-11e5-893d-74178218bd49.png">

**Comment by teobugslayer** [comment]
Hi @alexziskind1,

I am sorry for the late reply. Please tell us the versions of your Mac OS and Xcode.

**Comment by alexziskind1** [comment]
Hi @teobugslayer,

Here are my specs:
 
Mac OS - El Capitan v. 10.11
XCode - v. 7.0.1 (7A1001)

**Comment by alexziskind1** [comment]
After upgrade to 
OSX 10.11.1 and XCode to 7.1 (7B91b)
Debugging started working again.
