### ISSUE TITLE
--key-store-path option to look for the keystore file path relative to the app root

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1086]
Currently the `<File Path>` value of `--key-store-path` option used with `tns build/run android` needs to be relative to the *platforms/android* folder. It would be more convenient to be relative to the app root folder.

Actual: `$ tns run android --keyStorePath ../../../../keystore/Telerik.keystore`
Expected: `$ tns run android --keyStorePath ../keystore/Telerik.keystore`

```
vchimev@VCHIMEV /c/Work/release
$ tns --help run android
# run android
┌─────────────────────────────────┬─────────────────────────────────────────────────
│ Usage                           │ Synopsis
│ Run on all connected devices    │ $ tns run android [--key-store-path <File Path> ...
```

**Comment by rosen-vladimirov** [comment]
It should be relative to the directory where the command is executed, definitely a bug.
