### ISSUE TITLE
Allow Info.plist and AndroidManifest.xml files to be placed in App_Resources

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1089]
To customize my iOS apps I frequently need to alter my Info.plist the file. If I place an `appName-Info.plist` file in `App_Resources/iOS`, the file gets copied to `platforms/ios/appName/Resources`, but it needs to be copied to `platforms/ios/appName`.

Can this be supported?

**Comment by tjvantoll** [comment]
Actually I believe `AndroidManifest.xml` has the same problem.

**Comment by jlooper** [comment]
+1, this would be extremely helpful for both iOS and Android

**Comment by sitefinitysteve** [comment]
+1 it's painful to maintain important files in a volatile folder

**Comment by dapriett** [comment]
Support for custom Android build.gradle and iOS Podfiles would be nice too.

**Comment by toddanglin** [comment]
+1

I used XCode today to set a number of project settings (supported orientations, iOS devices, etc), so it would be great if these settings were more "durable" and easier to persist in source control (since the "platforms" folder is usually ignored). Especially when so many debugging/troubleshooting steps include "Delete your platforms ios/android directories." :)

**Comment by fritzvd** [comment]
I actually found a way to do this for the Android part. The AndroidManifest.xml file can be filled with permissions if you define the AndroidManifest.xml file in 
app/App_Resources/Android/res/AndroidManifest.xml

I added one like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

</manifest>
```

And the permission got appended to the AndroidManifest.xml in the platforms/ folder.

Cheers,

Fritz

**Comment by fritzvd** [comment]
It's interesting that it does work when a plugin uses permissions such as @dapriett's https://github.com/dapriett/nativescript-google-maps-sdk

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/platforms/android/AndroidManifest.xml

These permissions do get added. Is there way to incorporate that same mechanism for the regular App_Resources files?

The merge of an xml (for android) is being handled in the plugin service.. 
https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/plugins-service.ts#L293

**Comment by ligaz** [comment]
The support for Android has landed in 1.5. This means that if you have an `AndroidManifest.xml` in `App_Resources/Android` it will get merged. The same goes for any resources in the `App_Resources/Android/res`.

**Comment by sitefinitysteve** [comment]
+10 for iOS support

**Comment by jlooper** [comment]
When can we expect this for iOS, please?

**Comment by sect2k** [comment]
Android support seems to be broken as well in 1.5.0. Adding AndroidManifest.xml to App_Resources, brakes the build step.

**Comment by ligaz** [comment]
@sect2k Maybe https://github.com/NativeScript/android-runtime/pull/294 is the issue you have hit?

**Comment by sect2k** [comment]
@ligaz it seems the problem was this issue here https://github.com/NativeScript/android-runtime/commit/cd51a5179cbeebfa9475e6baed2f5f912fccc6c3. After fixing the comma problem the build step runs fine, and seems to work.

**Comment by PanayotCankov** [comment]
The #1369 just landed. With the next version of the CLI release an Info.plist will be created upon build or upon creating a new project in `app/App_Resources/iOS/Info.plist` and it will be merged with the `Info.plist` of the installed plugins. You can keep there build numbers and configure launch images, icons etc.

**Comment by speigg** [comment]
Great. Is the Info.plist in `app/App_Resources/iOS` guaranteed to be merged last (after the info.plist of the installed plugins)? This is important for overriding settings that are provided by plugins (e.g., the `nativescript-geolocation` plugin).

**Comment by dragGH102** [comment]
+1 for plist merging for iOS

**Comment by PanayotCankov** [comment]
@speigg: Yes, except for the bundle identifier that comes from the package.json.

**Comment by Daxito** [comment]
+1 for iOS support
