### ISSUE TITLE
CocoaPods /platforms/ios/Podfile generation

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#1096]
_From @NathanaelA on October 22, 2015 14:51_

This generated Podfile (tns command builds it) is built it can get lots of duplicates.   Each time you do something that internally does a **tns prepare ios** or if you manually do a **tns prepare ios** you will get a duplicate begin, pod and end lines into this file.   
Maybe this file should be truncated before adding them back.   As when I was fixing my pod file; I ended up getting several of the same pods in the file, but all with different :path variables which then caused it to choke...

_Copied from original issue: NativeScript/ios-runtime#382_

**Comment by NathanaelA** [comment]
Woo Hoo!   I'm glad this is almost done; I've ran into another issue as I had to add a post install step to my podfile and because it keeps getting inserted into the file; I start getting warnings about needing to manually fix the podfile due to multiple post install steps.

**Comment by rosen-vladimirov** [comment]
@NathanaelA Have you tried our latest build from release branch. We'll be glad for any assist that could confirm it works as expected now?

**Comment by NathanaelA** [comment]
Nope, but I will attempt to try this out...

**Comment by dtopuzov** [comment]
Steps to reproduce:
1. $ tns create myApp
2. $ cd myApp
2. $ tns plugin add nativescript-iqkeyboardmanager
3. $ tns prepare ios
4. $ cat platforms/ios/myApp/Podfile -> there is something like this:
# Begin Podfile 
pod 'IQKeyboardManager', '~> 4.0.0'
# End podfile
5. $ tns prepare ios
6. $ cat platforms/ios/myApp/Podfile -> lines above are repeated 2 times

**Comment by pkoleva** [comment]
Could not reproduce following the steps above in {N} 2.0.1
