### ISSUE TITLE
Add ability to use http(s) urls in --frameworkPath on tns platform add ios|android

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1098]
Right now this is the missing link in the ability to easily use other runtimes.   
For example I can currently do npm install <any url> to install both the nativescript cli and the nativescript common core library from anywhere including my nightlies on http://nativescript.rocks.    

However, for the platform files; I have to manually download them, put them into a folder then type 
tns platform add --frameworkPath=\<whereever I stuck it\>

This could be made so much more simple if --frameworkPath supported doing a download from the internet...

**Comment by teobugslayer** [comment]
Hi @NathanaelA,

This is great suggestion but we won't be able to implement it soon by ourselves. Can you help with a pull request :)

**Comment by NathanaelA** [comment]
@teobugslayer - I might; but it is also low on my priority list...  :)

**Comment by enchev** [comment]
Hey @NathanaelA @teobugslayer 

I'm closing this due to low interest from both sides. If you still think that this is important please reopen the issue or even submit pull request.

**Comment by NathanaelA** [comment]
I think the report is still valid; and not sure I would close it just because it is low on everyone's priority list.  Maybe instead of closing it you should label it as a needs help or another label expressing third party dev is needed on this one.

**Comment by enchev** [comment]
Hey @NathanaelA feel free to reopen when needed! :)

**Comment by NathanaelA** [comment]
@enchev I don't have the ability to re-open issues on any of of Telerik's repos.  ;-)    So I just have to hope I can get you to reopen.  :grinning:
