### ISSUE TITLE
Support node.js API

### ISSUE THREAD

**Issue by RangerMauve** [NativeScript/nativescript-cli#110]
Hello, I think it would be nice if you supported Node.js apis out of the box so that you could easily share all the modules that exist in the npm ecosystem.

**Comment by rosen-vladimirov** [comment]
Hi @RangerMauve 
Thanks for the suggestion. We've logged our idea how to implement this, so I'll close this issue. You can write your ideas in the other thread - https://github.com/NativeScript/nativescript-cli/issues/362
