### ISSUE TITLE
tns livesync ios always installing pods when change something in tns-core-modules

### ISSUE THREAD

**Issue by x4080** [NativeScript/nativescript-cli#1101]
And downloading from internet every time, so it kinda slow. Cant we installing pods only on tns run ios only ?

Edit : I try again and it is not downloading from pods, wil investigate further, 

Edit 2 : OK it is downloading pods when the file in the tns_modules is changes. I dont know if this the intended procedure or not

**Comment by Fatme** [comment]
Hi @x4080,

Sorry for the late reply.
NativeScript CLI will call `pod install` command only if a plugin that contains `podFile` is changed. If some other dependency in node_modules is changed, NativeScript CLI should not execute `pod install`.

**Comment by x4080** [comment]
So it will be fix in 1.5 then , cool

**Comment by x4080** [comment]
Hi i just upgraded to 1.5 and it still installing pods if file in the tns_modules is changed

**Comment by dtopuzov** [comment]
Current (2.0.1) behavior:
Change in tns-core-modules cause "tns livesync ios" to call pod install.
Change in your app (not in modules) does not call pod install.

**Comment by pkoleva** [comment]
Not relevant anymore due to changes in livesync behavior.
