### ISSUE TITLE
After upgrading to nativescript 1.4, ios build failed

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1103]
_From @eforth on October 22, 2015 14:34_

cocoapods (0.39.0)
nativescript@1.4.2

Steps

1. tns create testapp
2. cd testapp
3. tns platform add ios
4. tns build ios

Output from tns buid ios
========================

Project successfully prepared
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator
    SDKROOT = iphonesimulator9.0
    SHARED_PRECOMPS_DIR = /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/sharedpch
    VALID_ARCHS = "i386"

=== BUILD TARGET testapp2 OF PROJECT testapp2 WITH CONFIGURATION Debug ===

Check dependencies
build-debug.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods/Pods.debug.xcconfig"

PhaseScriptExecution NativeScript\ PreBuild build/testapp2.build/Debug-iphonesimulator/testapp2.build/Script-C97FD7AC1ADE5369004DB2A4.sh
    cd /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios
    /bin/sh -c /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/testapp2.build/Debug-iphonesimulator/testapp2.build/Script-C97FD7AC1ADE5369004DB2A4.sh
~/Projects/nativescript-apps/testapp2/platforms/ios/internal/metadata-generator/bin ~/Projects/nativescript-apps/testapp2/platforms/ios
Generating metadata for i386

~/Projects/nativescript-apps/testapp2/platforms/ios

Ld build/emulator/testapp2.app/testapp2 normal i386
    cd /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ervinforth/ApacheAnt/bin:/Users/ervinforth/android-sdk/tools:/Users/ervinforth/android-sdk/platform-tools:/Users/ervinforth/android-sdk/build-tools:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS/"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator -F/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator -F/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/../../lib/iOS -filelist /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/testapp2.build/Debug-iphonesimulator/testapp2.build/Objects-normal/i386/testapp2.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -sectcreate __DATA __TNSMetadata /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/metadata-i386.bin -lNativeScript -L/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/internal/NativeScript/lib -licucore -lz -lc++ -framework Foundation -framework UIKit -framework CoreGraphics -framework MobileCoreServices -fobjc-arc -fobjc-link-runtime -Xlinker -dependency_info -Xlinker /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/testapp2.build/Debug-iphonesimulator/testapp2.build/Objects-normal/i386/testapp2_dependency_info.dat -o /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/testapp2.app/testapp2
ld: warning: directory not found for option '-F/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/../../lib/iOS'
ld: can't open -sectcreate file: /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/metadata-i386.bin
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/testapp2.app/testapp2 normal i386
(1 failure)
Command xcodebuild failed with exit code 65

I noticed this all happened when I upgraded to version 1.4 of nativescript.

build-debug.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods/Pods.debug.xcconfig"

Anybody have a similar issue?

_Copied from original issue: NativeScript/NativeScript#978_

**Comment by enchev** [comment]
_From @fealebenpae on October 22, 2015 15:2_

Hi @eforth,

The `Unable to find included file "Pods/Target Support Files/Pods/Pods.debug.xcconfig"` warning is benign and you can safely ignore it. The real issue here is that for some reason the metadata generation has failed: `ld: can't open -sectcreate file: /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/metadata-i386.bin`.

I just performed these steps on my machine, running OS X 10.11.1, Xcode 7.1 from the App Store, nativescript@1.4.2 and CocoaPods 0.39.0, and it built fine. What's your environment like?

**Comment by enchev** [comment]
_From @eforth on October 22, 2015 15:32_

Xcode 7.0.1
Build version 7A1001

OS X El Captain
Version 10.11.1

**Comment by enchev** [comment]
_From @manijak on October 22, 2015 19:52_

I had the similar (if not the same) error right after I moved to El Capitan and XCode 7. 
Try giving your user more permissions to the platforms and/or ios folder (and sub-content). I gave my user read & write permission, plus added myself as the 'owner'. 
Then rebuild.

**Comment by enchev** [comment]
_From @eforth on October 22, 2015 21:57_

That didn't work but I'm going to upgrade my Xcode.

**Comment by enchev** [comment]
_From @x4080 on October 22, 2015 22:15_

Hello, i also can confirm that i don't have this issue, im using nvm for node versioning

**Comment by enchev** [comment]
_From @TobiasHennig on October 23, 2015 6:42_

I have exactly the same problem with the last Xcode.

**Comment by enchev** [comment]
_From @ivanbuhov on October 23, 2015 8:32_

Hi @eforth, try building your project with the CLI and the standart error stream of metadata generator will be dumped in `{YourAppFolder}/platforms/ios/build/emulator/metadata-generation-stderr-i386.txt` (if you build the app from Xcode you can find the dumped output in your `DeriveData` folder). Can you share the contents of the file?

**Comment by enchev** [comment]
_From @x4080 on October 23, 2015 9:11_

Oh maybe I should add I don't have cocoapod installed .maybe that is the issue ?

**Comment by enchev** [comment]
_From @TobiasHennig on October 23, 2015 9:14_

I have the problem with and without cocoapod installed. (I have installed it to solve the problem.)

**Comment by enchev** [comment]
_From @eforth on October 23, 2015 16:21_

Hi @ivanbuhov, the {YourAppFolder}/platforms/ios/build/emulator/metadata-generation-stderr-i386.txt file is empty.

**Comment by enchev** [comment]
_From @eforth on October 23, 2015 16:57_

Upgraded to Xcode 7.1 and also completely removed node, npm and all node modules (I know it's a bit drastic but I wanted to see if node or node modules might have caused the error).

##### system config:

OS X El Captain (version 10.11.1)
Xcode 7.1 (Build version 7B91b)
nvm (version 0.29.0)
node (version v0.12.7)
npm (version 2.11.3)
nativescript (version 1.4.3)```

I didn't install cocoapods however I will install later once the issue is fixed

The same error still occurs:

```ld: can't open -sectcreate file: /Users/ervinforth/Desktop/doula/platforms/ios/build/emulator/metadata-i386.bin```

Also a warning:

```ld: warning: directory not found for option '-F/Users/ervinforth/Desktop/doula/platforms/ios/../../lib/iOS'```

**Comment by enchev** [comment]
_From @TobiasHennig on October 25, 2015 15:0_

I've made a clean OSX install, but i'm still unable to build an ios project.

My system:
* OSX El Capitan 10.11
* Xcode 7.0.1
* node 0.12.7
* npm 2.11.3
* nativescript 1.4.3

And after ...
```
tns run ios --emulator
```
... i get these errors:
```
...
ld: warning: directory not found for option '-F/Users/tobiashennig/Sites/tns-example/platforms/ios/../../lib/iOS'
ld: can't open -sectcreate file: /Users/tobiashennig/Sites/tns-example/platforms/ios/build/emulator/metadata-i386.bin
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/tnsexample.app/tnsexample normal i386
(1 failure)
Command xcodebuild failed with exit code 65
```

**Comment by ivanbuhov** [comment]
We hardly tried to reporoduce the issue, but without success. I guess in your case the metadata generator is never called or it is called but crashes too early to produce any output. Try to run metadata generator manually. Depending on the result we can say if it is called at all or it just crashes too early. To run the generator manually:
1. Create a folder where the generator output will be stored
 2. Open a terminal in `{AppFolder}/platforms/ios/metadata-generator/bin/` and run the following command:
```
./objc-metadata-generator -output-bin "{OutputFolder}/metadata-i386.bin" -output-umbrella "{OutputFolder}/umbrella-i386.h" -output-yaml "{OutputFolder}" Xclang -isysroot "{SimulatorSdkFolder}" -arch i386 -miphoneos-version-min=7.0 -target arm-apple-darwin -std=gnu99 "-I{AppFolder}/platforms/ios/build/emulator/include" "-I{AppFolder}/platforms/ios/internal" "-I{AppFolder}/platforms/ios/internal/NativeScript/include" "-F{AppFolder}/platforms/ios/build/emulator" "-F{AppFolder}/platforms/ios/../../lib/iOS" -DDEBUG=1
```
Replace {OutputFolder} with the absolute path to previoslly created folder.
Replace {AppFolder} with the absolute path to your app folder.
Replace {SimulatorSdkFolder} with the absolute path to simulator sdk fodler.

On my machine I set the output folder to be `/Users/buhov/Desktop/metadata` and run the following command:
```
./objc-metadata-generator -output-bin "/Users/buhov/Desktop/metadata/metadata-i386.bin" -output-umbrella "/Users/buhov/Desktop/metadata/umbrella-i386.h" -output-yaml "/Users/buhov/Desktop/metadata" Xclang -isysroot "/Applications/Xcode7.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk" -arch i386 -miphoneos-version-min=7.0 -target arm-apple-darwin -std=gnu99 "-I/Users/buhov/Desktop/NSTestApp/platforms/ios/build/emulator/include" "-I/Users/buhov/Desktop/NSTestApp/platforms/ios/internal" "-I/Users/buhov/Desktop/NSTestApp/platforms/ios/internal/NativeScript/include" "-F/Users/buhov/Desktop/NSTestApp/platforms/ios/build/emulator" "-F/Users/buhov/Desktop/NSTestApp/platforms/ios/../../lib/iOS" -DDEBUG=1
```
If everything goes well your output folder should be populated with `metadata-i386.bin`, `umbrella-i386.h` and nearly 90 more YAML files (one yaml file per clang module).
Please share the output of the command dumped in the console, too.

**Comment by z0nekill** [comment]
Hey Ivan,

Thanks for moving my issue to the correct thread.

I'm trying to follow your steps but have ran into a snag.
```
tns platform add ios 
```
doesn't create the directory you outlined above in step 2.

However, I searched through the platforms directory and found the folder at the following location:

```
{AppFolder}/platforms/ios/internal/metadata-generator/bin/
```

I may just be highlighting a typo, but if I'm not then could this possibly be the reason the metadata isn't being generated?

Cheers,
David.

**Comment by ivanbuhov** [comment]
Ops, my fault. As @z0nekill noticed the folder is `{AppFolder}/platforms/ios/internal/metadata-generator/bin/`. I edited the original answer.

**Comment by eforth** [comment]
HI @ivanbuhov, when I ran the code below:

```./objc-metadata-generator -output-bin "output/metadata-i386.bin" -output-umbrella "output/umbrella-i386.h" -output-yaml "output" Xclang -isysroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk" -arch i386 -miphoneos-version-min=7.0 -target arm-apple-darwin -std=gnu99 "-I/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/build/emulator/include" "-I/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/internal" "-I/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/internal/NativeScript/include" "-F/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/build/emulator" "-F/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/../../lib/iOS" -DDEBUG=1```

or 

```./objc-metadata-generator -output-bin output/metadata-i386.bin -output-umbrella output/umbrella-i386.h -output-yaml output Xclang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk -arch i386 -miphoneos-version-min=7.0 -target arm-apple-darwin -std=gnu99 -I/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/build/emulator/include -I/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/internal -I/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/internal/NativeScript/include -F/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/build/emulator" "-F/Users/ervinforth/Projects/nativescript-apps/testa/platforms/ios/../../lib/iOS -DDEBUG=1```

I got the following response:

```Illegal instruction: 4```

**Comment by Fatme** [comment]
This issue was moved to NativeScript/ios-runtime#388
