### ISSUE TITLE
Fix livesync double restarts for TS projects

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1106]
The infamous double app restart issue when livesyncing TypeScript projects.

The first time you save a .ts file it gets synced to the device (completely unnecessarily), then you need another sync after you run your compiler. The fix involves ignoring `.ts` files on livesync. We sync the transpiled js files on the second pass.

**Comment by ligaz** [comment]
Once LiveSync and debugging play nicely we should revisit this because if you try to debug the `ts` files via source maps the files will not be updated.

**Comment by hdeshev** [comment]
> Once LiveSync and debugging play nicely we should revisit this because if you try to debug the ts files via source maps the files will not be updated.

Fully agree here. I meant this as a temporary (he-he) fix.

**Comment by vchimev** [comment]
A related issue: https://github.com/NativeScript/nativescript-cli/issues/1212.
