### ISSUE TITLE
TNS debug platform broken when offline

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1109]
From the tests I've done, it appears that when you run **tns debug android** or **tns debug ios** you are required to have an active internet connection. 

I must have tried this a dozen different ways this morning and I could not get it to work.  This is on a brand new v1.4 install I did, so I hadn't ran the debugger before under 1.4..  (So maybe their is a one time internet requirement?)   Once I connected to an internet connection both started working.

Debugging should not require an internet connection...

**Comment by teobugslayer** [comment]
Currently debugging builds the project, which indeed requires internet connection. We can think of alleviating this issue, though.

**Comment by NathanaelA** [comment]
Building the project doesn't require internet...  So what is needed that can't be put offline or downloaded the first time?

**Comment by NathanaelA** [comment]
Actually I was testing it tonight; and it appears that the Android side CAN be used offline -- I disconnected from the wifi and it seemed to work.   .  @teobugslayer  do you know of what the iOS side needs that requires it to have a internet connection; or did it just need to download some one-time resources?

**Comment by dtopuzov** [comment]
{N} 2.0.1 state:

Build iOS -> works offline
Build Android -> works offline
Run iOS  -> works offline
Run Android -> works offline
Debug iOS -> works offline
Debug Android -> works offline

@NathanaelA iOS debug require tns-ios-inspector, with is now outside tns-ios package (outside ios runtime). If you have it installed then debug works offline, but if it is not available in you npm cache may be tns try to download it and that is why you fail to debug offline.
