### ISSUE TITLE
unable to add android platform tns -v 1.4

### ISSUE THREAD

**Issue by NelsonRock** [NativeScript/nativescript-cli#1112]
Sorry by english!

I use nvm manager for node version, before upgrating from tns 1.3 and node 10.35 eveything were working fine

Hello I've upgrade to tns -v 1.4 and it's impossible runnin, adding platform, nothing.

I've create another project from sample-Groceries, git clone way!

My log trace when adding tns platform add android or running is the same.

Tns doctodr does not shows anything weird, just a flags for ios projects

Another issue i've force npm install packages because  tns install is not working

xec uname -a 
 stdout: Linux developpeur 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 
 stderr: 
Exec npm -v 
 stdout: 2.11.3
 
 stderr: 
spawn: java -version
Exec node-gyp -v 
 stdout: v0.12.2
 
 stderr: 
Exec adb version 
 stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
 
 stderr: 
Exec android -h 
 stdout: 
       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.
 
 stderr: 
Exec mono --version 
 stdout:  
 stderr: /bin/sh: 1: mono: not found

Exec git --version 
 stdout: git version 2.1.4
 
 stderr: 
Exec gradle -v 
 stdout: 
------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45-internal (Oracle Corporation 25.45-b02)
OS:           Linux 3.19.0-30-generic amd64

 
 stderr: 
Exec javac -version 
 stdout:  
 stderr: javac 1.8.0_66

System information:
{ procInfo: 'nativescript/1.4.3',
  platform: 'linux',
  os: 'Linux developpeur 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.7',
  npmVer: '2.11.3',
  javaVer: '1.8.0',
  nodeGypVer: 'v0.12.2\n',
  xcodeVer: null,
  itunesInstalled: false,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.1.4',
  gradleVer: '2.3',
  javacVersion: '1.8.0_66' }
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'platform'.
BeforeHookName for command platform-add is before-platform-add
AfterHookName for command platform-add is after-platform-add
Looking for project in '/home/nelson/github/node/sample-Groceries'
Project directory is '/home/nelson/github/node/sample-Groceries'.
`/usr/local/lib/node_modules/nativescript/node_modules/ref/bin/linux-x64-v8-3.28/binding.node` is missing. Try reinstalling `prebuilt`?
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, init, install, library, library|add, livesync, platform, platform|*list, platform|add, platform|remove, platform|update, plugin, plugin|add, plugin|remove, prepare, run, run|android, run|ios, usage-reporting
Reading help for command 'platform|add'. FileName is 'platform-add.md'.
# platform add
┌───────────────┬─────────────────────────────────────────────────┐
│ Usage         │ Synopsis                                        │
│ Android       │ $ tns platform add android [--frameworkPath     │
│ latest        │ <File Path>] [--symlink] [--sdk <API Level>]    │
│ runtime       │                                                 │
│ Android       │ $ tns platform add android[@<Version>] [-       │
│ selected      │ -frameworkPath <File Path>] [--symlink] [--sdk  │
│ runtime       │ <API Level>]                                    │
└───────────────┴─────────────────────────────────────────────────┘

Configures the current project to target the selected platform.  

### Options

    * --frameworkPath - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package. 
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
    * --sdk - Sets the target Android SDK for the project.

### Attributes

    * <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Version> is any available version of the respective platform runtime published in npm.

**Comment by rosen-vladimirov** [comment]
Hi @NelsonRock ,

Thank you for the detailed log. It looks like you have installed NativeScript CLI with node 0.10.x and later you have switched to node 0.12.x. In this case you have to reinstall NativeScript CLI.
Can you try executing `npm install -g nativescript` in the same terminal and execute `tns platform add android --log trace` after that.
I'm looking forward to hearing from you.

**Comment by NelsonRock** [comment]
Hi guys;

You were right! I've reinstalled nativescript with npm way in node v0.12.7 version and it's works great like before with tns 1.3 even tns install has worked as well

I've reinstalled before in the same way, i guess maybe changing from terminal to terminal with diferents node version and managing nvm manager have caused the problem.

One more again you are greats guys and keep working!!

I will show my next mobile app sooner! it's nothing amazing but it will be my firts with nativescript

Thanks a lot!

**Comment by rosen-vladimirov** [comment]
Hey @NelsonRock ,
I'm glad you were able to resolve the issue. We'll be waiting for more information on your application, hopefully you enjoy working with nativescript :) 
I'm closing this issue now, feel free to contact us in case you have any problems or concerns.
