### ISSUE TITLE
Install via npm install failed

### ISSUE THREAD

**Issue by GerjanOnline** [NativeScript/nativescript-cli#1115]
When i do `npm install -g nativescript` I get errors:

<pre>
C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ios-sim-portable\node_modules\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project " C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
</pre>

Full log:

<pre>
npm install -g nativescript
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Versions\Current -> A
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.0","npm":"3.3.8"})
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Versions\Current -> A
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
C:\Program Files (x86)\nodejs\tns -> C:\Program Files (x86)\nodejs\node_modules\nativescript\bin\nativescript.js
C:\Program Files (x86)\nodejs\nativescript -> C:\Program Files (x86)\nodejs\node_modules\nativescript\bin\nativescript.js

> fibers@1.0.6 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\fibers
> node build.js || nodejs build.js

C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props " was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\fibers
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN install:fibers@1.0.6 fibers@1.0.6 install: `node build.js || nodejs build.js`
npm WARN install:fibers@1.0.6 Exit status 1

> fibers@1.0.6 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ios-sim-portable\node_modules\fibers
> node build.js || nodejs build.js

C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ios-sim-portable\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ios-sim-portable\node_modules\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project " C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ios-sim-portable\node_modules\fibers
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN install:fibers@1.0.6 fibers@1.0.6 install: `node build.js || nodejs build.js`
npm WARN install:fibers@1.0.6 Exit status 1

> bufferutil@1.0.1 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\bufferutil
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting

> ref@1.1.3 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ref
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting

> ffi@2.0.0 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\ffi
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting

> ws@0.4.32 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\node-inspector\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

> utf-8-validate@1.0.1 install C:\Program Files (x86)\nodejs\node_modules\nativescript\node_modules\utf-8-validate
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting
C:\Program Files (x86)\nodejs
+-- (empty)

npm ERR! code 1
</pre>

**Comment by teobugslayer** [comment]
Due to bug in V8, we cannot support node v4.2.0. Please update to 4.2.1 and try installing NativeScript CLi again.

Let me know if this worked for you

**Comment by GerjanOnline** [comment]
Yes, updating to node v4.2.1 solves this issue! Thanks for your help.
 
But now I'm curious: which bug in V8? Do you have a link?

**Comment by rosen-vladimirov** [comment]
Hi @GerjanOnline ,
There are two major bugs in Node 4.2.0 that are breaking almost everything. As pointed in [their CHANGELOG](https://github.com/nodejs/node/blob/master/CHANGELOG.md):
```
Includes fixes for two regressions
Assertion error in WeakCallback - see #3329
Undefined timeout regression - see #3331
```

We think the problem that you've hit is the first on - `Assertion error in WeakCallback`.

Hope this helps :)

**Comment by GerjanOnline** [comment]
Awesome, thank you guys

**Comment by unaor** [comment]
Im also getting this error im on node v5.0.0 should i downgrade to 4.2.1 p.s on another machine i had issues as well but running npm i -g node-gyp resolved them

**Comment by unaor** [comment]
just uninstalled node 5.0 and reinstalled v 4.2.2 and nativescript instalation passed on perfectly without issues.

**Comment by rosen-vladimirov** [comment]
@unaor , as you have found, NativeScript CLI cannot work with node 5.0.0 due to known bug in the node itself. For the moment I recommend you to use Node's LTS version (4.2.x).

**Comment by VishalSubramanyam** [comment]
I have the same problem on Node 6.1.0. Does this bug exit on that version?

**Comment by rosen-vladimirov** [comment]
@VishalSubramanyam 
Node 6.1.0 is still not supported, I suggest you to install latest LTS Version (4.4.4) or latest 5.x version of node :)

**Comment by VishalSubramanyam** [comment]
How am I supposed to run two versions parallel in the same environment @rosen-vladimirov

**Comment by rosen-vladimirov** [comment]
@VishalSubramanyam you can use **nvm** in such cases:
https://github.com/creationix/nvm

**Comment by ravi005e** [comment]
still happening in node v9.4.0

> fibers@2.0.0 install /node_modules/fibers
> node build.js || nodejs build.js

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line toolsinstance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line toolsinstance

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:318:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter);
                ^~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
Installed in `/node_modules/fibers/bin/darwin-x64-59/fibers.node`
