### ISSUE TITLE
tns platform add ios Bus error: 10

### ISSUE THREAD

**Issue by jwoods1** [NativeScript/nativescript-cli#1119]
After following the getting started, Step 1.2 Add target development platforms in terminal get the following errors on Mac OSX El Capitan 10.11.1 (15B42).  

Bus error: 10 
Segmentation fault: 11

**Comment by jwoods1** [comment]
After completely deleting node off of the system, and reinstallation of node with home brew. It fixed this issue.

**Comment by rosen-vladimirov** [comment]
@jwoods1  I'm glad you've resolved the issue. I'm closing this thread, but feel free to contact us in case you have any other problems or concerns :)

**Comment by cenobyte321** [comment]
I'm getting a "Segmentation Fault" error when doing "tns platfom add ios" and "tns platfom add android", I'm using npm version 3.3.12. Also using Mac OS X El Capitan 10.11.1. npm was installed alongside with Nodejs.

**Comment by jwoods1** [comment]
I had a similar issue. The fix for me was to complete delete node from my system. Some permission stuff changed when I did the update to el captain. After I completely deleted node and all modules I installed it with homebrew. Hope this help.

Jason

Sent from my iPhone

On Nov 9, 2015, at 9:08 AM, cenobyte321 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm getting a "Segmentation Fault" error when doing "tns platfom add ios" and "tns platfom add android", I'm using npm version 3.3.12. Also using Mac OS X El Capitan 10.11.1. npm was installed alongside with Nodejs.

-

**Comment by cenobyte321** [comment]
I already uninstalled Node using this guide: https://gist.github.com/TonyMtz/d75101d9bdf764c890ef and re-installed it with Homebrew. I'm still getting the same error.

**Comment by jwoods1** [comment]
When I deleted following that guide I for some reason had node still installed. I ran the node command in terminal and was checking if it was deleted. You might want to try that once it is fully deleted. I then had to do a full search and delete the remaining node files. Then I reinstalled. Hope this helps I'm just shooting in the dark now.

Sent from my iPhone

On Nov 9, 2015, at 11:32 AM, cenobyte321 <notifications@github.com<mailto:notifications@github.com>> wrote:


I already uninstalled Node using this guide: https://gist.github.com/TonyMtz/d75101d9bdf764c890ef and re-installed it with Homebrew. I'm still getting the same error.

-

**Comment by cenobyte321** [comment]
Thanks, that seems to have resolved the error, but now I get:
FATAL ERROR: v8::ArrayBuffer::Neuter Only externalized ArrayBuffers can be neutered
Abort trap: 6
Which according to this: https://github.com/NativeScript/nativescript-cli/issues/1129
Should either be resolved in a future Node version or by downgrading Node

**Comment by rosen-vladimirov** [comment]
Hi @cenobyte321 ,
Please install node 0.10.40 or node 0.12.7 or node 4.2.1/4.2.2
These are the supported versions, so any other could cause unexpected behavior.
After that execute `npm i -g nativescript`

Hope this helps.

**Comment by cenobyte321** [comment]
@rosen-vladimirov, yes thank you, downgrading Node to a version prior to 5.0.0 solved the problem.

**Comment by rosen-vladimirov** [comment]
@cenobyte321, I'm glad it worked for you. In fact we've discovered an issue in node 5.0.0, it should be fixed in the incoming node 5.1.0, but we'll double check it once it is released. This issue is causing the segmentation fault when using node 5.0.0 :)

**Comment by EddyVerbruggen** [comment]
Just fyi - `nvm install 4.2.2` fixed the `Segmentation fault: 11` error for me when I did `tns platform add ios/android`.
