### ISSUE TITLE
Wrong error messages

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#112]
Case 1:
This command:
"tns deploy android --device fakeDevice --path TNS_Javascript"
returns following error:
Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'appbuilder device'.

'appbuilder device' is wrong, it should be replaced with 'tns list-devices'

Case 2:
When all Android devices are disconnected and you call "tns list-devices android" then you see:
Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again

Then message does not end with '.'.

**Comment by rosen-vladimirov** [comment]
First issue is resolved. The second one is part of html help changes.
