### ISSUE TITLE
[Unit Testing] Add meaningful unit test examples for the tests directory

### ISSUE THREAD

**Issue by ikoevska** [NativeScript/nativescript-cli#1124]
It would be great if `example.js` actually contains a meaningful, executable test and not the generic example carried by the framework documentation.

This example.js could verify the message text on first run or the value of the counter. It could check what happens after a few iterations of tapAction and verify whether the counter keeps going below zero.

**Comment by tailsu** [comment]
It rather makes sense to ship the project templates with tests.

**Comment by dtopuzov** [comment]
Will be included in default template.
