### ISSUE TITLE
[Linux] No execute permissions on node_modules/nativescript/resources/platform-tools/android/linux/adb

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#113]
When install Nativescript CLI on Linux user has no execute permissions on node_modules/nativescript/resources/platform-tools/android/linux/adb
This leads to issues with some of the Nativescript CLI commands.

Workaround:
After Nativescript CLI installation run this command:
chmod u+x node_modules/nativescript/resources/platform-tools/android/linux/adb

**Comment by stevelacy** [comment]
This issue still persists and is not fixed.
