### ISSUE TITLE
Livesync with console.log

### ISSUE THREAD

**Issue by N3ll** [NativeScript/nativescript-cli#1130]
_From @prijindal on November 1, 2015 18:26_

Currently you can't log anything with livesync
Any plans on upgrading livesync to show log output?

_Copied from original issue: NativeScript/NativeScript#1009_

**Comment by N3ll** [comment]
_From @x4080 on November 2, 2015 2:18_

+1

**Comment by N3ll** [comment]
_From @manijak on November 2, 2015 9:58_

+1

**Comment by emiloberg** [comment]
One way of solving it would be to make it easier for the developer to start view the log files, as described in this issue https://github.com/NativeScript/NativeScript/issues/1009#issuecomment-152999397

**Comment by x4080** [comment]
I found that livesync ios don't update changed .ios the Android side works though

**Comment by vchimev** [comment]
@x4080,

I tried what you reported with the latest {N} CLI 1.5 Release Candidate and experienced only this issue: https://github.com/NativeScript/nativescript-cli/issues/1234.

Please, give a try to {N} 1.5 when released and let us know if you still experience such problem by opening a separate issue.

**Comment by vchimev** [comment]
There is an issue using `console.log` during LiveSync that on Android after making a change to a *.js* file (respectively the app restarts) than the `console.log` messages duplicate. /CC: @Fatme

**Comment by vchimev** [comment]
Sum up:
- `consoloe.log()` will be supported with LiveSync in {N} CLI 1.5.0 for Android device/emulator and iOS device
- `consoloe.log()` support with LiveSync for iOS simulators implementation could be followed here: https://github.com/NativeScript/nativescript-cli/issues/1262
- the issue described above for duplicate `console.log` messages during LiveSync on Android will be resolved in {N} CLI 1.5.1
