### ISSUE TITLE
Expose Android package name as global variable

### ISSUE THREAD

**Issue by tsvetko** [NativeScript/nativescript-cli#1139]
It would be really nice if Android package name is exposed as global variable and it is accessible from 3rd party plugins.

For example if I want to create a {N} plugin that instruments Android app I have to insert this section into AndroidManifest.xml

<< instrumentation android:targetPackage="PACKAGE_NAME" android:name="com.telerik.testingextension.MobileTestingInstrumentation" />

At the moment there is no way to do this because package name is generated by {N} depending on how user has set up his project.

**Comment by valentinstoychev** [comment]
HI @tsvetko - are you looking for something like this - http://stackoverflow.com/questions/21109019/android-gradle-replace-package-name-for-a-value-in-manifest

**Comment by tsvetko** [comment]
Yes - I need a way to reuse package name when merging manifest files. 
Noticed that my previous message is not well formatted and fixed it.

**Comment by enchev** [comment]
I believe that now you have full control using AndroidManifest.xml
