### ISSUE TITLE
Add search box in cli docs

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1146]
As title says it. 

Usage: search by command and search by command parameter or search by keyword in general

**Comment by NathanaelA** [comment]
Uhm, maybe I am missing the point but almost every browser has a ctrl-f (find) function; and some of us actually have find on type enabled in our browsers.  :grinning:     Why duplicate the functionality of the browser?

**Comment by blagoev** [comment]
The idea is to search in multiple files either by providing a combined single file for all the help pages or to some JS logic to do this.

**Comment by ligaz** [comment]
We plan to include the CLI documentation in the docs.nativescirpt.org: https://github.com/NativeScript/docs/issues/157

There we have a unified search.
