### ISSUE TITLE
Running custom builds (or nightlies) breaks with new TNS CLI Master

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1147]
I upgraded to v1.5 nightly of everything 2015/11/04; but I ran into a issue with it that required me to disable some code inside the tns command line tool. 

Here is the problem:
When you do a tns prepare (or anything internally does a tns prepare) it runs a function called  NpmInstallationManager.prototype.isShasumOfPackageCorrect
Well, this function attempts to do a **npm view tns-android@1.5.0**  (or whatever version the built runtime is labeled).  Of course since this is a compiled master installed using --frameworkPath; this sha will not be in the npm log.  So npm fails to be to get a sha hash.  If you label the custom runtime 1.4 (i.e. whatever is current) then of course the sha hash won't match.   

I haven't had these problems ever before; so I am "assuming" this code is new in the master branch of the CLI; or their is some other bug that is causing a prepare to force a sha check of the runtimes which will for sure fail.

**Comment by teobugslayer** [comment]
@NathanaelA,

we introduced this change in 1.4.3 to fix [1054](https://github.com/NativeScript/nativescript-cli/issues/1054). I will fix the SHA check though to not fail in your case.

**Comment by teobugslayer** [comment]
Hi @NathanaelA, which version of CLI are you using? I cannot reproduce this behavior with CLI from master.

**Comment by NathanaelA** [comment]
I was using the CLI from master as of 11/4.   I hadn't seen this issue before switching to master; prior to that I was running v1.4 release.   I need to run master to test out the new **npm test** stuff. I am not sure when the **isShasumOfPackageCorrect** gets called (or why it was called).  But if it somehow gets triggered to be called; it will break if you are running a master of the runtimes also.  The Android runtimes from master will be tagged v1.50 but the latest published on npm will be 1.4, and so the **npm view tns-android@1.5.0** that the **isShasumOfPackageCorrect** runs will fail and bring back an undefined value; which will then crash that check (with dist.shasum of undefined error).  Which then leaves you really in a broken state. Which is ultimately what gave me the #1148 issue.

Just to make sure I'm clear; you must be running master of the CLI and master of the android runtimes.  I do not know if this will occur on iOS (but I don't see any reason why it wouldn't since it is trying to do a npm view on an non-existent release...

**Comment by NathanaelA** [comment]
Here this causes it to fail for me (make sure you are also the master android runtime and the master cli) :
1. Delete your /platforms/android/src/main/assets/app to force a full resync of the application
2. tns prepare android

**Comment by NathanaelA** [comment]
Ok, I figured out how to duplicate this
- tns create test_150
- cd test_150
- tns platform add android --frameworkPath=../tns-android-master.tgz
- tns plugin add nativescript-vibrate
- tns prepare android

Please note this MUST be the nativescript-vibrate plugin (I'm using v1.10 -- the latest as of this message); other plugins might cause this behavior but this appears to be the guilty party in this case.)

When you run the tns prepare; it will do a addToCache with tns-android@1.5.0, which then calls the isShaSum with those values and dies.   This will ALSO leave you with the #1148 issue.  If you check your test_150\platforms\android\src\main\assets\app\tns_modules you will see it has a broken vibrate plugin install (files un-renamed has both ios & android) but it is missing the rest of the tns-core modules... Making the app totally un-runable.  Another tns prepare won't fix it...

**Comment by teobugslayer** [comment]
Thanks for the repro case, I'll have a look at the issue
