### ISSUE TITLE
Bad **tns prepare android** can leave project unusable

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1148]
A bad **tns prepare android** can leave the /platform/android/src/main/assets/app folder in a bad state (i.e. without the /tns_modules) which you can't recover from without deleting the assets/app folder.  A second (or any number) **tns prepare android*, returns that it succeeded; but the missing files aren't copied into the app folder leaving the app unable to run on a device.

I ran into this because of bug #1147 
Please note this is tns cli Master as of 2015/11/04

**Comment by teobugslayer** [comment]
@NathanaelA,

can you give me exact repro case? We have [try / catch'ed](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/platform-service.ts#L79) the attempt to add platform and the directory should be deleted on error.

On the top of my head, there's one possible scenario where we can fail - deep inside the npm, there's an actual 'assert', which tears down the process. I will have a look at the issue but I need stable way to reproduce it.

**Comment by NathanaelA** [comment]
The exact case is what causes #1147; when it failed it leaves me in this case.
See the addition notes on 1147.
