### ISSUE TITLE
[Unit Testing] tns test android - doesn't actually run (Master as of 2015/11/04)

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1149]
This sets up the environment; transfers all the files and once I get the status of "NativeScript deployment completed with code 0" 

I have to manually launch the application on the device.   The app should be automatically launched.

**Comment by dtopuzov** [comment]
It is OK now, please note that "tns test android" require sdcard.

**Comment by NathanaelA** [comment]
@dtopuzov, what about devices that don't have a sdcard?   The new Samsung S6 I believe does not have SD card capability....
