### ISSUE TITLE
CLI Android Full Sync issues / Unit Testing bad interaction

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1150]
I'm not sure which party is at fault; but this is broken badly for unit testing / running.  

When you do a **tns test run android** it does the full sync (which btw is incredibly slow); then the user currently launches the test version of the application (because the package.json file points to the test frameworks app.js) and this works.   

However, if you try to launch the application a second time; it is totally corrupt.  

The new syncing code syncs everything each time to the /data/local/tmp/app.nam/ folder; and then when the application is launched it (I believe) it moves the files to the actual application folder. (either that or it deletes them, one way or the other the tns_modules folder is cleared out)

The issue is that it LEAVES the files in the main /tmp/app.name/ directory like the package.json file.    Now I don't believe this is a bad issue normally; BUT when you are doing running a test this file is changed to point to the test framework app file.  But this file no longer exists in the tmp folder because it was cleared out...  So the app crashes.

**Comment by teobugslayer** [comment]
Thanks for noticing this! We will fix it for 1.5.0
