### ISSUE TITLE
[Unit Testing] Test failures on Android may bring up the error box; rather than exiting app.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1158]
Some failures of tests;  if they fail because of a bug (not because of an assert) instead of the app quitting with a test failure; it crashes to an error dialog. If your lucky to the call stack dialog.

Any way while in test mode; we can just quit the application rather than the callstack or worse the stupid crash dialog.

**Comment by tailsu** [comment]
Yes, this is a problem in the runtime. Things like syntax errors are right now impossible to capture and bring the runtime down. Hence it's impossible to report them and you have to dig through logcat.

**Comment by tailsu** [comment]
This is one of the pertaining issues: https://github.com/NativeScript/android-runtime/issues/221.

**Comment by tailsu** [comment]
Bug is reportedly fixed in 1.5.1. Can you give it a try?
