### ISSUE TITLE
android support design library

### ISSUE THREAD

**Issue by x4080** [NativeScript/nativescript-cli#1160]
Hi, how to add android support design library to nativescript ? Ive tried :

1. add in the gradle (compile "com.android.support:design:$suppotVer") -> android.support.design is still undefined

2. try to copy android-support-design.jar to lib and run tns build android but build failed with UNEXPECTED TOP-LEVEL EXCEPTION (trying to build the metadata)

What is the correct way to add android library (especially from google android)

Thanks

**Comment by x4080** [comment]
And now it works, I dont know what happened, so the gradle actually was already downloaded the aar of the android support design

Sorry for the false alarm

**Comment by ssimpo** [comment]
@x4080  Wow, there should be a note in the install documentation, spent ages trying to debug this.  Thanks , that fixed it for me.
