### ISSUE TITLE
tns run/emulate/deploy does not check if device is available before build

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1167]
Steps to reproduce:
run/emulate/deploy on not existing device/emulator/simulator

Result:
tns execute prepare and build and after that check if device is available.

Suggestion:
When execute un/emulate/deploy check if device/emulator/simulator before prepare and build.

**Comment by vchimev** [comment]
Done for the `run` and `deploy` commands in 1.5.0 - it still needs validation for the `emulate` command.
