### ISSUE TITLE
nativescript not installing

### ISSUE THREAD

**Issue by romessido** [NativeScript/nativescript-cli#1187]
Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.

C:\Windows\System32>npm install nativescript -g
/
> nativescript@1.4.3 preuninstall C:\Users\S Rajesh kumar\AppData\Roaming\npm\no
de_modules\nativescript
> node preuninstall.js

Failed to complete all pre-uninstall steps.
{ [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node bin/nativescri
pt.js dev-preuninstall"
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\S Rajesh kumar\AppData\Roaming\npm\node_modu
les\nativescript\lib\common\bootstrap.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "node bin/nativescript.js dev-preun
install"' }
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.2","npm":"2.7.4"})
|

> fibers@1.0.6 install C:\Users\S Rajesh kumar\AppData\Roaming\npm\node_modules\
nativescript\node_modules\fibers
> node build.js || nodejs build.js

`win32-ia32-v8-3.28` exists; testing
Binary is fine; exiting
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/
highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Versions\Current -> A
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/
highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Versions\Current -> A
\

> ws@0.4.32 install C:\Users\S Rajesh kumar\AppData\Roaming\npm\node_modules\nat
ivescript\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Users\S Rajesh kumar\AppData\Roaming\npm\node_modules\nativescript\node_modul
es\node-inspector\node_modules\ws>if not defined npm_config_node_gyp (node "C:\P
rogram Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nativescript" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nativescript" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by rosen-vladimirov** [comment]
Hi @romessido 
Can you try executing:
```
npm i -g node-gyp
npm i -g nativescript
```
If the installation fails again, can you try upgrading your node to 0.12.7 for example and try again?

**Comment by rosen-vladimirov** [comment]
Hi @romessido 
As we have not heard back from you for a week, I'm closing this issue. Feel free to contact us in case you have any problems or concerns.

**Comment by romessido** [comment]
hi @rosen-vladimirov 
C:\WINDOWS\system32>npm i -g node-gyp
C:\Users\S Rajesh kumar\AppData\Roaming\npm\node-gyp -> C:\Users\S Rajesh kumar\
AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
node-gyp@3.2.1 C:\Users\S Rajesh kumar\AppData\Roaming\npm\node_modules\node-gyp

├── graceful-fs@4.1.2
├── semver@5.1.0
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── nopt@3.0.6 (abbrev@1.0.7)
├── fstream@1.0.8 (inherits@2.0.1)
├── which@1.2.1 (is-absolute@0.1.7)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── path-array@1.0.0 (array-index@0.1.1)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── rimraf@2.5.0 (glob@6.0.3)
├── npmlog@1.2.1 (ansi@0.3.0, gauge@1.2.2, are-we-there-yet@1.0.5)
└── request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, c
aseless@0.11.0, stringstream@0.0.5, oauth-sign@0.8.0, tunnel-agent@0.4.2, json-s
tringify-safe@5.0.1, isstream@0.1.2, extend@3.0.0, node-uuid@1.4.7, qs@5.2.0, to
ugh-cookie@2.2.1, combined-stream@1.0.5, form-data@1.0.0-rc3, bl@1.0.0, hawk@3.1
.2, mime-types@2.1.8, har-validator@2.0.3, http-signature@1.1.0)

C:\WINDOWS\system32>

**Comment by romessido** [comment]
Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
