### ISSUE TITLE
Cannot add platform android (Assertion Failed)

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1192]
_From @ArsalanDotMe on November 14, 2015 13:27_

When executing `tns platform add android` I get the following error:

`Assertion failed: (object)->IsUint8Array(), file src\node_buffer.cc, line 151`

Running tns doctor gives the following output.

```
WARNING: You can work with iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

WARNING: CocoaPod is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPod.
These warnings are just used to help the NativeScript maintainers with debugging if you file an issue.
Please ignore them if everything you use NativeScript for is working fine.
```

What could be wrong?

_Copied from original issue: NativeScript/NativeScript#1101_

**Comment by rosen-vladimirov** [comment]
Hi @ArsalanDotMe ,
It looks like you are using node 4.2 which has known issue about this error. Please upgrade your node to 4.2.1 or 4.2.2 and try again. 
Note that NativeScript CLI can work with node 0.10.40, 0.12.7 and node 4.2.1, 4.2.2
Can you give it a try and inform us if it works for you?
