### ISSUE TITLE
Forbid creating projects with names starting with number

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-cli#1203]
Currently, I can create a project with name starting with number, but cannot run it:
```
d:\>tns create 123
Project 123 was successfully created

d:>cd 123
d:\123>tns run adnroid
Project name must not begin with a number
```
Better fail on the create step.

**Comment by vchimev** [comment]
@TsvetanMilanov @rosen-vladimirov 

There was a similar case (https://github.com/NativeScript/nativescript-cli/issues/1439) where a project with name *app* cannot build for iOS.

Could you make both cases behave in the same way?

Currently, if I run `tns create app` it will warn me
```
You cannot build applications named 'app' in Xcode. Consider creating a project with different name.
```
and will create the project. If I run `tns create 123` it will warn me
```
The project name does not start with letter and will fail to build for Android.
```
and prompt me
```
Do you want to create the project with this name?
```

**Comment by TsvetanMilanov** [comment]
@vchimev 
Nice idea we will implement it.
