### ISSUE TITLE
tns build --release should use a release version of the runtimes.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1221]
I think the system need to be building and distributing both the debug and release versions of the Runtimes.  By default as far as I can tell it always uses the debug versions.   When you use the --release command it should use the release versions of the runtimes.   (Yes, I realize the runtimes download will double in size; but a release app should be running the fastest we can make it...)

From my experience the release versions appears to be faster than the debug versions.

**Comment by x4080** [comment]
Will the release version remove all trace and console log ? Or we must remove it manually ?

**Comment by NathanaelA** [comment]
It does remove some of the internal logging, but the main issue is that it is compiled for speed, not debugging.  Any console.log's you currently have to remove.

**Comment by x4080** [comment]
Alright that's clears it

**Comment by rosen-vladimirov** [comment]
Hi @NathanaelA , 
In fact we ship only one version of the runtimes and its the "release" one. So I'm closing this issues, but feel free to reopen it in case you think the provided solution is not enough or I've misunderstood your idea.

**Comment by NathanaelA** [comment]
@rosen-vladimirov Awesome.  Was maybe v1.0/1.1 still debug built?    I could have sworn when I originally checked it; it was built with debug options.

**Comment by rosen-vladimirov** [comment]
@NathanaelA , not sure about this, but I've asked the guys from Android and iOS Runtime and they assured me that we provide only release version now.
