### ISSUE TITLE
Do we need the prepare command? Why don't we just leave the build command?

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#123]

**Comment by leecrossley** [comment]
The `prepare` command is useful, as you may wish to build independently from the copied files. This matches the "Cordova way".

What I feel is wrong, is the fact that the `build` command does not encompass the `prepare` command. i.e. `tns build ios` does not automatically run `tns prepare ios` first. This has caught me out and does not match the "Cordova way".

I'd like to know someone else's thoughts, I'm happy to PR.
