### ISSUE TITLE
the cli should have an option to list out the plugins used

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/nativescript-cli#1231]
the cli should have an option to list out the plugins used. It can be read from package.json when typing
```
tns plugin list
```

**Comment by amjd** [comment]
`tns plugin` command should list the plugins according to the usage instructions of plugin command for CLI as seen below, but for some reason it doesn't seem to have been implemented:

```
$ tns plugin list
The input is not valid sub-command for 'plugin' command
# plugin 
┌────────────────┬────────────────────────┐
│ Usage          │ Synopsis               │
│ List plugins   │ $ tns plugin           │
│ Manage plugins │ $ tns plugin <Command> │
└────────────────┴────────────────────────┘

Lets you manage the plugins for your project.

### Attributes
<Command> extends the plugin command. You can set the following values for this attribute.


    * add - Installs the specified plugin and its dependencies.
    * remove - Uninstalls the specified plugin and its dependencies.
```

**Comment by gaurav-chandra** [comment]
in the latest cli also tns plugin is not listing the plugins.

**Comment by pavel-blagodov** [comment]
Any updates here, how can I sее a list of available plugins?

**Comment by rosen-vladimirov** [comment]
@pavel-blagodov 
The easiest way is to check your package.json (the one at the root of your application). Just take a look at dependencies section - all packages described there will be included in your app.

**Comment by pavel-blagodov** [comment]
@rosen-vladimirov 
I want to see list of available plugins for nativescript not for my project. 
`tns plugin` command should list the plugins according to its usage instructions, but this does not happen!

**Comment by rosen-vladimirov** [comment]
Ok, it's bug in the documentation then. This is not implemented at all

**Comment by dtopuzov** [comment]
Now tns plugin will list all used plugins.
