### ISSUE TITLE
livesync and App_Resources

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-cli#1235]
Is livesync meant to add images that I add to App_resources?
For some reason those don’t seem to be picked up when I add them, however the app keeps refreshing each time I add a new image.

Sometimes I have to run tns build android and then tns run android to see the see the images.

**Comment by Fatme** [comment]
LiveSync command doesn't build your application so you're not able to sync **resources** using `livesync` command. You can move your images to `app` folder and load them with local file system paths. This way `livesync` command will sync your images.

**Comment by Fatme** [comment]
I'm going to close this issue for now, feel free to open another issue if you have additional questions.
