### ISSUE TITLE
On build time the pod included in the plugin can't be installed (sandbox problem)

### ISSUE THREAD

**Issue by nikolay-diyanov** [NativeScript/nativescript-cli#1249]
Hey guys,

I have a project which is working with a plugin that has a cocoapod inside it. So, on build time, I get: 

Installing pods...
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1 Error output: 
 [!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.2`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-search-0.1.0`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-0.5.1`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.1`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.0`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-0.4.5`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-0.4.4`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface/error_report.rb:77:in ``': Operation not permitted - git (Errno::EPERM)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface/error_report.rb:77:in ``'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface/error_report.rb:125:in `git_information'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface/error_report.rb:38:in `report'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:61:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:374:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:315:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<main>'

I know the workaround, it is to go to: /Users/[USER NAME]/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/config/config.json 
and set "USE_POD_SANDBOX": false

But still, it is interesting why this happens at all.

**Comment by jlooper** [comment]
I just encountered the same, using the Firebase plugin. :(

**Comment by teobugslayer** [comment]
The `sandbox-pods` executable uses Mac OS sandboxing to voluntarily relinquish some of its permissions. On the other hand, `pods` has unrestricted access to the machine. We are defaulting to sandboxing, so that users have consistent experience in AppBuilder and {N} CLI.

**Comment by teobugslayer** [comment]
This is documented in https://github.com/NativeScript/docs/pull/259, will close this issue.

**Comment by zb0t** [comment]
@jlooper Thanks this helped me greatly

**Comment by AhsanAyaz** [comment]
@jlooper thanks.. you're a life saver 👍

**Comment by jonathan-casarrubias** [comment]
@jlooper +1

**Comment by thomasjosephgreco** [comment]
@nikolay-diyanov that seems to have worked for me. I had to navigate to `/Users/thomasgreco/.nvm/versions/node/v4.2.6/lib/node_modules/nativescript`

**Comment by nabito** [comment]
Thanks @jlooper
