### ISSUE TITLE
iOS Emulator Livesync problems, not updating instantly

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1256]
- tns livesync ios --emulator --watch
- <Simulator starts>
- <App Loads>
- <Click button to nav to screen I want to work with>
- <Update Xml\Css>
- ...nothing happens, but I see it doing something in the terminal
- Nav back home, then back to screen, changes are visible

Android is instant

**Comment by Fatme** [comment]
Can you execute the command with --log trace and send us the output?

**Comment by DeLI-medportal** [comment]
Okay, here's the output... just uncommented out a button, on android it changes\shows fine

Steves-MBP:native steve$ tns livesync ios --emulator --watch --log trace
execFile: /usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.4.1/tools/android "--help"

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.

Exec uname -a 
 stdout: Darwin Steves-MBP 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 2.14.7
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 7.1.1
Build version 7B1005
 
 stderr: 
Exec pod --version 
 stdout: 0.39.0
 
 stderr: 
Exec '/usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
 
 stderr: 
spawn: /usr/local/Cellar/android-sdk/24.4.1/tools/android "-h"
Exec mono --version 
 stdout:  
 stderr: /bin/sh: mono: command not found

Exec git --version 
 stdout: git version 2.4.9 (Apple Git-60)
 
 stderr: 
Exec gradle -v 
 stdout: 
------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Mac OS X 10.11.1 x86_64

 
 stderr: 
Exec "javac" -version 
 stdout:  
 stderr: javac 1.8.0_65

System information:
{ procInfo: 'nativescript/1.5.0',
  platform: 'darwin',
  os: 'Darwin Steves-MBP 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v4.2.2',
  npmVer: '2.14.7',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.1.1\nBuild version 7B1005\n',
  itunesInstalled: true,
  cocoapodVer: '0.39.0',
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.4.9 (Apple Git-60)',
  gradleVer: '2.8',
  javacVersion: '1.8.0_65' }
execFile: /usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb "start-server"
Looking for project in '/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native'
Project directory is '/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native'.
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'livesync'.
AnalyticsInstallationID: daccb8fc-2cd2-4de8-9a67-3c90b994e1a1
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native/hooks' ]
BeforeHookName for command prepare is before-prepare
Statistics was sent successfully (xhr).
Statistics was sent successfully (xhr).
Images from Xcode project
[ 'Default-568h@2x.png',
  'Default-667h.png',
  'Default-736h.png',
  'Default-Landscape-667h.png',
  'Default-Landscape-736h.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'ic_add_white.png',
  'ic_add_white_2x.png',
  'ic_add_white_3x.png',
  'ic_arrow_back_white.png',
  'ic_arrow_back_white_2x.png',
  'ic_arrow_back_white_3x.png',
  'ic_email_white.png',
  'ic_email_white_2x.png',
  'ic_email_white_3x.png',
  'ic_remove_white.png',
  'ic_remove_white_2x.png',
  'ic_remove_white_3x.png',
  'ic_search_white.png',
  'ic_search_white_2x.png',
  'ic_search_white_3x.png',
  'ic_search_white_48pt.png',
  'ic_search_white_48pt_2x.png',
  'ic_search_white_48pt_3x.png',
  'ic_share_white.png',
  'ic_share_white_2x.png',
  'ic_share_white_3x.png',
  'ic_star_border_white.png',
  'ic_star_border_white_2x.png',
  'ic_star_border_white_3x.png',
  'ic_star_white.png',
  'ic_star_white_2x.png',
  'ic_star_white_3x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-40@3x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-60@3x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'watch-172x172.png',
  'watch-196x196.png',
  'watch-48x48.png',
  'watch-55x55.png',
  'watch-58x58.png',
  'watch-80x80.png',
  'watch-87x87.png',
  'watch-88x88.png' ]
Current images from App_Resources
[ 'Default-568h@2x.png',
  'Default-667h.png',
  'Default-736h.png',
  'Default-Landscape-667h.png',
  'Default-Landscape-736h.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'ic_add_white.png',
  'ic_add_white_2x.png',
  'ic_add_white_3x.png',
  'ic_arrow_back_white.png',
  'ic_arrow_back_white_2x.png',
  'ic_arrow_back_white_3x.png',
  'ic_email_white.png',
  'ic_email_white_2x.png',
  'ic_email_white_3x.png',
  'ic_remove_white.png',
  'ic_remove_white_2x.png',
  'ic_remove_white_3x.png',
  'ic_search_white.png',
  'ic_search_white_2x.png',
  'ic_search_white_3x.png',
  'ic_search_white_48pt.png',
  'ic_search_white_48pt_2x.png',
  'ic_search_white_48pt_3x.png',
  'ic_share_white.png',
  'ic_share_white_2x.png',
  'ic_share_white_3x.png',
  'ic_star_border_white.png',
  'ic_star_border_white_2x.png',
  'ic_star_border_white_3x.png',
  'ic_star_white.png',
  'ic_star_white_2x.png',
  'ic_star_white_3x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-40@3x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-60@3x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'watch-172x172.png',
  'watch-196x196.png',
  'watch-48x48.png',
  'watch-55x55.png',
  'watch-58x58.png',
  'watch-80x80.png',
  'watch-87x87.png',
  'watch-88x88.png' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Project successfully prepared
AfterHookName for command prepare is after-prepare
Exec ps cax | grep launchd_sim 
 stdout:   401   ??  S      0:00.72 launchd_sim
 
 stderr: 
Exec killall Native 
 stdout:  
 stderr: 
BeforeHookName for command watch is before-watch
Exec xcrun simctl launch 3607EE15-7B8D-46AE-9DE4-2526D5E91E1F org.nativescript.OutbreakHelp 
 stdout: org.nativescript.OutbreakHelp: 1279
 
 stderr: 
BeforeHookName for command prepare is before-prepare
Images from Xcode project
[ 'Default-568h@2x.png',
  'Default-667h.png',
  'Default-736h.png',
  'Default-Landscape-667h.png',
  'Default-Landscape-736h.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'ic_add_white.png',
  'ic_add_white_2x.png',
  'ic_add_white_3x.png',
  'ic_arrow_back_white.png',
  'ic_arrow_back_white_2x.png',
  'ic_arrow_back_white_3x.png',
  'ic_email_white.png',
  'ic_email_white_2x.png',
  'ic_email_white_3x.png',
  'ic_remove_white.png',
  'ic_remove_white_2x.png',
  'ic_remove_white_3x.png',
  'ic_search_white.png',
  'ic_search_white_2x.png',
  'ic_search_white_3x.png',
  'ic_search_white_48pt.png',
  'ic_search_white_48pt_2x.png',
  'ic_search_white_48pt_3x.png',
  'ic_share_white.png',
  'ic_share_white_2x.png',
  'ic_share_white_3x.png',
  'ic_star_border_white.png',
  'ic_star_border_white_2x.png',
  'ic_star_border_white_3x.png',
  'ic_star_white.png',
  'ic_star_white_2x.png',
  'ic_star_white_3x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-40@3x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-60@3x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'watch-172x172.png',
  'watch-196x196.png',
  'watch-48x48.png',
  'watch-55x55.png',
  'watch-58x58.png',
  'watch-80x80.png',
  'watch-87x87.png',
  'watch-88x88.png' ]
Current images from App_Resources
[ 'Default-568h@2x.png',
  'Default-667h.png',
  'Default-736h.png',
  'Default-Landscape-667h.png',
  'Default-Landscape-736h.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'ic_add_white.png',
  'ic_add_white_2x.png',
  'ic_add_white_3x.png',
  'ic_arrow_back_white.png',
  'ic_arrow_back_white_2x.png',
  'ic_arrow_back_white_3x.png',
  'ic_email_white.png',
  'ic_email_white_2x.png',
  'ic_email_white_3x.png',
  'ic_remove_white.png',
  'ic_remove_white_2x.png',
  'ic_remove_white_3x.png',
  'ic_search_white.png',
  'ic_search_white_2x.png',
  'ic_search_white_3x.png',
  'ic_search_white_48pt.png',
  'ic_search_white_48pt_2x.png',
  'ic_search_white_48pt_3x.png',
  'ic_share_white.png',
  'ic_share_white_2x.png',
  'ic_share_white_3x.png',
  'ic_star_border_white.png',
  'ic_star_border_white_2x.png',
  'ic_star_border_white_3x.png',
  'ic_star_white.png',
  'ic_star_white_2x.png',
  'ic_star_white_3x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-40@3x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-60@3x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'watch-172x172.png',
  'watch-196x196.png',
  'watch-48x48.png',
  'watch-55x55.png',
  'watch-58x58.png',
  'watch-80x80.png',
  'watch-87x87.png',
  'watch-88x88.png' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Project successfully prepared
AfterHookName for command prepare is after-prepare
Transfering /Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native/app/views/home/home.xml to /Users/steve/Library/Developer/CoreSimulator/Devices/3607EE15-7B8D-46AE-9DE4-2526D5E91E1F/data/Containers/Bundle/Application/9DA7C7D8-A6B0-4A17-A10B-22AEFB5DFC27/Native.app/app/views/home
Exec /usr/local/bin/node /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js notify-post org.nativescript.OutbreakHelp:NativeScript.Debug.AttachRequest 
 stdout:  
 stderr: 
Successfully synced application org.nativescript.OutbreakHelp.

**Comment by sitefinitysteve** [comment]
Okay, here's the output... just uncommented out a button, on android it changes\shows fine

Steves-MBP:native steve$ tns livesync ios --emulator --watch --log trace
execFile: /usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.4.1/tools/android "--help"

   Usage:
   android [global options] action [action options]
   Global options:
-s --silent : Silent mode, shows errors only.
-v --verbose : Verbose mode, shows errors, warnings and all messages.
--clear-cache: Clear the SDK Manager repository manifest cache.
-h --help : Help on a specific command.

                                                                Valid
                                                                actions
                                                                are
                                                                composed
                                                                of a verb
                                                                and an
                                                                optional
                                                                direct
                                                                object:
sdk : Displays the SDK Manager window.
avd : Displays the AVD Manager window.
list : Lists existing targets or virtual devices.
list avd : Lists existing Android Virtual Devices.
list target : Lists existing targets.
list device : Lists existing devices.
list sdk : Lists remote SDK repository.
create avd : Creates a new Android Virtual Device.
move avd : Moves or renames an Android Virtual Device.
delete avd : Deletes an Android Virtual Device.
update avd : Updates an Android Virtual Device to match the folders of a new SDK.
create project : Creates a new Android project.
update project : Updates an Android project (must already have an AndroidManifest.xml).
create test-project : Creates a new Android project for a test package.
update test-project : Updates the Android project for a test package (must already have an AndroidManifest.xml).
create lib-project : Creates a new Android library project.
update lib-project : Updates an Android library project (must already have an AndroidManifest.xml).
create uitest-project: Creates a new UI test project.
update adb : Updates adb to support the USB devices declared in the SDK add-ons.
update sdk : Updates the SDK by suggesting new platforms to install if available.
Exec uname -a 
stdout: Darwin Steves-MBP 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

stderr: 
Exec npm -v 
stdout: 2.14.7

stderr: 
spawn: java "-version"
Exec node-gyp -v 
stdout:

stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
stdout: Xcode 7.1.1
Build version 7B1005

stderr: 
Exec pod --version 
stdout: 0.39.0

stderr: 
Exec '/usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb' version 
stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

stderr: 
spawn: /usr/local/Cellar/android-sdk/24.4.1/tools/android "-h"
Exec mono --version 
stdout:

stderr: /bin/sh: mono: command not found

Exec git --version 
stdout: git version 2.4.9 (Apple Git-60)

stderr: 
Exec gradle -v

stdout:

Gradle 2.8

Build time: 2015-10-20 03:46:36 UTC
Build number: none
Revision: b463d7980c40d44c4657dc80025275b84a29e31f

Groovy: 2.4.4
Ant: Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM: 1.8.0_65 (Oracle Corporation 25.65-b01)
OS: Mac OS X 10.11.1 x86_64

stderr: 
Exec "javac" -version 
stdout:

stderr: javac 1.8.0_65

System information:
{ procInfo: 'nativescript/1.5.0',
platform: 'darwin',
os: 'Darwin Steves-MBP 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64\n',
shell: '/bin/bash',
dotNetVer: null,
procArch: 'x64',
nodeVer: 'v4.2.2',
npmVer: '2.14.7',
javaVer: '1.8.0',
nodeGypVer: null,
xcodeVer: 'Xcode 7.1.1\nBuild version 7B1005\n',
itunesInstalled: true,
cocoapodVer: '0.39.0',
adbVer: 'Android Debug Bridge version 1.0.32',
androidInstalled: true,
monoVer: null,
gitVer: '2.4.9 (Apple Git-60)',
gradleVer: '2.8',
javacVersion: '1.8.0_65' }
execFile: /usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.4.1/platform-tools/adb "start-server"
Looking for project in '/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native'
Project directory is '/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native'.
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'livesync'.
AnalyticsInstallationID: daccb8fc-2cd2-4de8-9a67-3c90b994e1a1
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
'/usr/local/lib/node_modules/nativescript/lib/common/hooks',
'/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native/hooks' ]
BeforeHookName for command prepare is before-prepare
Statistics was sent successfully (xhr).
Statistics was sent successfully (xhr).
Images from Xcode project
[ 'Default-568h@2x.png',
'Default-667h.png',
'Default-736h.png',
'Default-Landscape-667h.png',
'Default-Landscape-736h.png',
'Default-Landscape.png',
'Default-Landscape@2x.png',
'Default-Portrait.png',
'Default-Portrait@2x.png',
'Default.png',
'Default@2x.png',
'Icon-Small-50.png',
'Icon-Small-50@2x.png',
'Icon-Small.png',
'Icon-Small@2x.png',
'ic_add_white.png',
'ic_add_white_2x.png',
'ic_add_white_3x.png',
'ic_arrow_back_white.png',
'ic_arrow_back_white_2x.png',
'ic_arrow_back_white_3x.png',
'ic_email_white.png',
'ic_email_white_2x.png',
'ic_email_white_3x.png',
'ic_remove_white.png',
'ic_remove_white_2x.png',
'ic_remove_white_3x.png',
'ic_search_white.png',
'ic_search_white_2x.png',
'ic_search_white_3x.png',
'ic_search_white_48pt.png',
'ic_search_white_48pt_2x.png',
'ic_search_white_48pt_3x.png',
'ic_share_white.png',
'ic_share_white_2x.png',
'ic_share_white_3x.png',
'ic_star_border_white.png',
'ic_star_border_white_2x.png',
'ic_star_border_white_3x.png',
'ic_star_white.png',
'ic_star_white_2x.png',
'ic_star_white_3x.png',
'icon-40.png',
'icon-40@2x.png',
'icon-40@3x.png',
'icon-60.png',
'icon-60@2x.png',
'icon-60@3x.png',
'icon-72.png',
'icon-72@2x.png',
'icon-76.png',
'icon-76@2x.png',
'icon.png',
'icon@2x.png',
'watch-172x172.png',
'watch-196x196.png',
'watch-48x48.png',
'watch-55x55.png',
'watch-58x58.png',
'watch-80x80.png',
'watch-87x87.png',
'watch-88x88.png' ]
Current images from App_Resources
[ 'Default-568h@2x.png',
'Default-667h.png',
'Default-736h.png',
'Default-Landscape-667h.png',
'Default-Landscape-736h.png',
'Default-Landscape.png',
'Default-Landscape@2x.png',
'Default-Portrait.png',
'Default-Portrait@2x.png',
'Default.png',
'Default@2x.png',
'Icon-Small-50.png',
'Icon-Small-50@2x.png',
'Icon-Small.png',
'Icon-Small@2x.png',
'ic_add_white.png',
'ic_add_white_2x.png',
'ic_add_white_3x.png',
'ic_arrow_back_white.png',
'ic_arrow_back_white_2x.png',
'ic_arrow_back_white_3x.png',
'ic_email_white.png',
'ic_email_white_2x.png',
'ic_email_white_3x.png',
'ic_remove_white.png',
'ic_remove_white_2x.png',
'ic_remove_white_3x.png',
'ic_search_white.png',
'ic_search_white_2x.png',
'ic_search_white_3x.png',
'ic_search_white_48pt.png',
'ic_search_white_48pt_2x.png',
'ic_search_white_48pt_3x.png',
'ic_share_white.png',
'ic_share_white_2x.png',
'ic_share_white_3x.png',
'ic_star_border_white.png',
'ic_star_border_white_2x.png',
'ic_star_border_white_3x.png',
'ic_star_white.png',
'ic_star_white_2x.png',
'ic_star_white_3x.png',
'icon-40.png',
'icon-40@2x.png',
'icon-40@3x.png',
'icon-60.png',
'icon-60@2x.png',
'icon-60@3x.png',
'icon-72.png',
'icon-72@2x.png',
'icon-76.png',
'icon-76@2x.png',
'icon.png',
'icon@2x.png',
'watch-172x172.png',
'watch-196x196.png',
'watch-48x48.png',
'watch-55x55.png',
'watch-58x58.png',
'watch-80x80.png',
'watch-87x87.png',
'watch-88x88.png' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Project successfully prepared
AfterHookName for command prepare is after-prepare
Exec ps cax | grep launchd_sim 
stdout: 401 ?? S 0:00.72 launchd_sim

stderr: 
Exec killall Native 
stdout:

stderr: 
BeforeHookName for command watch is before-watch
Exec xcrun simctl launch 3607EE15-7B8D-46AE-9DE4-2526D5E91E1F org.nativescript.OutbreakHelp 
stdout: org.nativescript.OutbreakHelp: 1279

stderr: 
BeforeHookName for command prepare is before-prepare
Images from Xcode project
[ 'Default-568h@2x.png',
'Default-667h.png',
'Default-736h.png',
'Default-Landscape-667h.png',
'Default-Landscape-736h.png',
'Default-Landscape.png',
'Default-Landscape@2x.png',
'Default-Portrait.png',
'Default-Portrait@2x.png',
'Default.png',
'Default@2x.png',
'Icon-Small-50.png',
'Icon-Small-50@2x.png',
'Icon-Small.png',
'Icon-Small@2x.png',
'ic_add_white.png',
'ic_add_white_2x.png',
'ic_add_white_3x.png',
'ic_arrow_back_white.png',
'ic_arrow_back_white_2x.png',
'ic_arrow_back_white_3x.png',
'ic_email_white.png',
'ic_email_white_2x.png',
'ic_email_white_3x.png',
'ic_remove_white.png',
'ic_remove_white_2x.png',
'ic_remove_white_3x.png',
'ic_search_white.png',
'ic_search_white_2x.png',
'ic_search_white_3x.png',
'ic_search_white_48pt.png',
'ic_search_white_48pt_2x.png',
'ic_search_white_48pt_3x.png',
'ic_share_white.png',
'ic_share_white_2x.png',
'ic_share_white_3x.png',
'ic_star_border_white.png',
'ic_star_border_white_2x.png',
'ic_star_border_white_3x.png',
'ic_star_white.png',
'ic_star_white_2x.png',
'ic_star_white_3x.png',
'icon-40.png',
'icon-40@2x.png',
'icon-40@3x.png',
'icon-60.png',
'icon-60@2x.png',
'icon-60@3x.png',
'icon-72.png',
'icon-72@2x.png',
'icon-76.png',
'icon-76@2x.png',
'icon.png',
'icon@2x.png',
'watch-172x172.png',
'watch-196x196.png',
'watch-48x48.png',
'watch-55x55.png',
'watch-58x58.png',
'watch-80x80.png',
'watch-87x87.png',
'watch-88x88.png' ]
Current images from App_Resources
[ 'Default-568h@2x.png',
'Default-667h.png',
'Default-736h.png',
'Default-Landscape-667h.png',
'Default-Landscape-736h.png',
'Default-Landscape.png',
'Default-Landscape@2x.png',
'Default-Portrait.png',
'Default-Portrait@2x.png',
'Default.png',
'Default@2x.png',
'Icon-Small-50.png',
'Icon-Small-50@2x.png',
'Icon-Small.png',
'Icon-Small@2x.png',
'ic_add_white.png',
'ic_add_white_2x.png',
'ic_add_white_3x.png',
'ic_arrow_back_white.png',
'ic_arrow_back_white_2x.png',
'ic_arrow_back_white_3x.png',
'ic_email_white.png',
'ic_email_white_2x.png',
'ic_email_white_3x.png',
'ic_remove_white.png',
'ic_remove_white_2x.png',
'ic_remove_white_3x.png',
'ic_search_white.png',
'ic_search_white_2x.png',
'ic_search_white_3x.png',
'ic_search_white_48pt.png',
'ic_search_white_48pt_2x.png',
'ic_search_white_48pt_3x.png',
'ic_share_white.png',
'ic_share_white_2x.png',
'ic_share_white_3x.png',
'ic_star_border_white.png',
'ic_star_border_white_2x.png',
'ic_star_border_white_3x.png',
'ic_star_white.png',
'ic_star_white_2x.png',
'ic_star_white_3x.png',
'icon-40.png',
'icon-40@2x.png',
'icon-40@3x.png',
'icon-60.png',
'icon-60@2x.png',
'icon-60@3x.png',
'icon-72.png',
'icon-72@2x.png',
'icon-76.png',
'icon-76@2x.png',
'icon.png',
'icon@2x.png',
'watch-172x172.png',
'watch-196x196.png',
'watch-48x48.png',
'watch-55x55.png',
'watch-58x58.png',
'watch-80x80.png',
'watch-87x87.png',
'watch-88x88.png' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Project successfully prepared
AfterHookName for command prepare is after-prepare
Transfering /Users/steve/Dropbox/Projects/Apps/OutbreakHelp/Native/app/views/home/home.xml to /Users/steve/Library/Developer/CoreSimulator/Devices/3607EE15-7B8D-46AE-9DE4-2526D5E91E1F/data/Containers/Bundle/Application/9DA7C7D8-A6B0-4A17-A10B-22AEFB5DFC27/Native.app/app/views/home
Exec /usr/local/bin/node /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js notify-post org.nativescript.OutbreakHelp:NativeScript.Debug.AttachRequest 
stdout:

stderr: 
Successfully synced application org.nativescript.OutbreakHelp.

**Comment by rosen-vladimirov** [comment]
Hi @sitefinitysteve ,
I've just tried this with latest CLI from npm and latest CLI from master and everything works as expected. Is it possible to send us a sample project reproducing the issue?

**Comment by sitefinitysteve** [comment]
Hmm, okay I'll try and get back to you, doesn't seem to work here
http://www.screencast.com/t/2neKhhhEY6

**Comment by sitefinitysteve** [comment]
No sample needed, bug found...1.6 shows the error
Unable to sync file /Users/steve/Dropbox/Projects/Apps/Temp/modal-test/modal-test/app/modal/modal.ios.css. Error is: ENOENT: no such file or directory, stat '/Users/steve/Dropbox/Projects/Apps/Temp/modal-test/modal-test/platforms/ios/modaltest/app/modal/modal.ios.css'

The .ios gets removed under the platform folder, livesync is not up to speed on that

**Comment by rosen-vladimirov** [comment]
Ok, we already have this one logged https://github.com/NativeScript/nativescript-cli/issues/1313
Can you confirm it is duplicate, so we can close this one.

**Comment by sitefinitysteve** [comment]
Yep duplicate, close whatever you need

**Comment by rosen-vladimirov** [comment]
Thanks for your investigation and report
