### ISSUE TITLE
tns run ios --emulator --device "iPhone 6" cannot start the app on 2nd call

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#1258]
If I call the above command twice - the first time the app is deployed to simulator and runs but the second time the CLI stop on 'Starting iOS Simulator'. Probably a check if simulator is already started is needed.

**Comment by Fatme** [comment]
The problem happens with `sample-TelerikNext`. The sample had incorrect `Info.plist` file. After fixing the `Info.plist` file the problem was resolved.
