### ISSUE TITLE
LiveSync with console.log support for iOS simulators

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1262]
Starting with {N} CLI 1.5.0, `consoloe.log()` messages is supported with LiveSync on Android device/emulator and iOS device (https://github.com/NativeScript/nativescript-cli/issues/1130) - support for iOS simulators to be implemented.

**Comment by tjvantoll** [comment]
Did this make it into the 1.6 release? It doesn’t seem to be working for me.

**Comment by rosen-vladimirov** [comment]
Yep, I've tested it and it worked. What's your XCode version, simulator and the command that you are executing?

**Comment by tjvantoll** [comment]
@rosen-vladimirov: I’m using Xcode 7.2.1 with a iOS 9.2 simulator and using `tns livesync ios --emulator --watch`.

I see console logs the first time I run the app, but as soon as I make a single change I no longer see console logs or stack traces.

**Comment by sitefinitysteve** [comment]
Same as TJ, tns 1.6.1

Looks like if I update the XML, I get my console log dumps, but any JS change just isn't shown

**Comment by rosen-vladimirov** [comment]
Guys, can you try `tns livesync ios --watch` when the simulator is already started and see if your console.logs are there?

**Comment by tjvantoll** [comment]
@rosen-vladimirov: I’ve tried this several times on several different apps and I consistently don’t see the console logs 🙁

**Comment by rosen-vladimirov** [comment]
@tjvantoll Thank you for testing it. I'll give it a try in the next couple of days and see what's going on there.

**Comment by dtopuzov** [comment]
Still not working with {N} 1.7.0 RC.

**Comment by aaweb** [comment]
+1

**Comment by stefalda** [comment]
I confirm that it still doesn't work (1.7.0), I think it is a MUST for any serious development!
Thanks

**Comment by axalon** [comment]
Confirm that it still doesn't work in 1.7.0. Definitely a huge issue that needs to be fixed.

**Comment by vchimev** [comment]
Fixed in 2.0.0.
