### ISSUE TITLE
LiveSync clears navigation history

### ISSUE THREAD

**Issue by mikebranstein** [NativeScript/nativescript-cli#1273]
After LiveSync refreshes a page, the current navigation history is cleared. Attempts at navigating back  after a LyneSync refresh do nothing, i.e., `topmost.goBack();` does nothing. Additionally, the "< Back" navigation link is missing.

I feel LiveSync should maintain your navigation history to move about your app. 

I'm running NativeScript 1.5.0.

**Comment by ligaz** [comment]
@hshristov can you elaborate on the current implementation and what we can improve in order to not clear the history?

**Comment by Fatme** [comment]
This issue was moved to NativeScript/NativeScript#1417
