### ISSUE TITLE
Colored output for console.log

### ISSUE THREAD

**Issue by amjd** [NativeScript/nativescript-cli#1274]
This is a suggestion for `console.log`ing during LiveSync or the usual way or running the apps.
At present, the logged text looks like this:
```
JS: Text goes here
```

It's easy for the messages to get lost in the stream of output. It would be great if the log messages could be colored partially or completely so they are hard to miss. Also, this could be implemented in combination with a timestamp, which would address #1263.
```
[console.log | 12:34:56 PM] Text goes here
```
or
```
[12:34:56 PM] Text goes here
```
where the text inside the square brackets would be colored and/or bold.

I think this would greatly improve the debugging experience. Please look into whether it's feasible to add this.

**Comment by stephenfeather** [comment]
Colorization should be optional/configurable.
Not everyone uses the same terminal backgrounds colors.
Not everyone has eyes that work the same as everyone else (color blindness, etc)

**Comment by TheBrousse** [comment]
I would be for enabling it by default and have a cli option allowing users to modify or deactivate it altogether.

**Comment by rosen-vladimirov** [comment]
Hi, 

At the moment, we are filtering device logs, so it is harder to miss the console.log messages

**Comment by ligaz** [comment]
Merging this into https://github.com/NativeScript/nativescript-cli/issues/719

**Comment by sylwesterdigital** [comment]
2021, still missing typical for shell ANSI coloring.
