### ISSUE TITLE
Populating list view calls Object.defineProperty 3 times {N} 1.5

### ISSUE THREAD

**Issue by GitCharm** [NativeScript/nativescript-cli#1276]
I have this problem in my own project, and have also replicated in the Friends apps when populating the initial activies list.  

I have added an alert dialogue which displays 3 times when loading the activities in the Friends app:

 Object.defineProperty(ActivitiesViewModel.prototype, "activities", {
        get: function () {
            this.isLoading = true;
            var that = this;

            var expandExp = {
               "UserId":{
                  "ReturnAs":"User",
                  "TargetTypeName":"Users",
                  "Expand":{
                     "Picture":{
                        "TargetTypeName":"System.Files"
                     }
                  }
               },
               "Picture":{
                  "ReturnAs":"Picture",
                  "SingleField":"Uri",
                  "TargetTypeName":"System.Files"
               }
            };

            var data = EVERLIVE.data('Activities');
            var query = new Everlive.Query();
            query.orderDesc('CreatedAt');
            
            data.expand(expandExp).get(query)
            .then(function(data) {
                for(var i = 0; i < data.result.length; i++){
                    data.result[i].dateConverter = dateConverter;
                    var activityItem = new activityItemViewModel.ActivityItemViewModel(data.result[i]);

                    data.result[i] = activityItem;
                }

               alert('There are ' + data.result.length.toString() + ' activities: ' + JSON.stringify(data.result));
                that._activities.push(data.result); 

                that.isLoading = false;
            }, function(error) {
                that.isLoading = false;
                alert("Activities can't be retrieved");
            });      

            return this._activities;        
        },
            enumerable: true,
            configurable: true
    });

NOTE:  I have replicated this in CLI, Appbuilder CLI and also Windows Appbuilder.

**Comment by GitCharm** [comment]
Additionally - this means 3 calls to the backend database service, and also the number of records displayed is tripled.

**Comment by ligaz** [comment]
This issue was moved to NativeScript/NativeScript#1216
