### ISSUE TITLE
Build iOS project fails because of missing icons 

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#128]
Log:

The following build commands failed:
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default-Landscape.png UnitTestApp/Resources/icons/Default-Landscape.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default-568h@2x.png UnitTestApp/Resources/icons/Default-568h@2x.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default-Landscape@2x.png UnitTestApp/Resources/icons/Default-Landscape@2x.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default-Portrait.png UnitTestApp/Resources/icons/Default-Portrait.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default-Portrait@2x.png UnitTestApp/Resources/icons/Default-Portrait@2x.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default.png UnitTestApp/Resources/icons/Default.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/Default@2x.png UnitTestApp/Resources/icons/Default@2x.png
    CopyPNGFile /private/var/lib/jenkins/workspace/tns-modules-stable-build-unittests-ipa/UnitTestApp/platforms/ios/build/device/UnitTestApp.app/icon-40.png UnitTestApp/Resources/icons/icon-40.png

**Comment by Agnostic** [comment]
I have the same problem, I'm using `nativescript` v1.0.0.

I did this:
```bash
$ tns create MyApp --copy-from "~/NativeScript/apps/TelerikNEXT"
$ cd MyApp
$ tns platform add ios
```
But then, when I try to run the app I got this:

```
...
** BUILD FAILED **

The following build commands failed:
	CpResource MyApp/Resources/icons/Default-Portrait.png build/emulator/SocialBusv2.app/Default-Portrait.png
	CpResource MyApp/Resources/icons/Default-Landscape@2x.png build/emulator/MyApp.app/Default-Landscape@2x.png
	CpResource MyApp/Resources/icons/Default-Landscape.png build/emulator/MyApp.app/Default-Landscape.png
	CpResource MyApp/Resources/icons/Default-568h@2x.png build/emulator/MyApp.app/Default-568h@2x.png
	CpResource MyApp/Resources/icons/Default-Portrait@2x.png build/emulator/MyApp.app/Default-Portrait@2x.png
	CpResource MyApp/Resources/icons/Default.png build/emulator/MyApp.app/Default.png
	CpResource MyApp/Resources/icons/Default@2x.png build/emulator/MyApp.app/Default@2x.png
(7 failures)
Command xcodebuild failed with exit code 65
```

Any idea?

**Comment by Fatme** [comment]
Hi @Agnostic,

It seems that these images are missing from 'MyApp/app/App_Resources/iOS' folder. 
Can you send us the application for further investigation?

Thanks in advance.

**Comment by Fatme** [comment]
I suggest that you're using `https://github.com/NativeScript/sample-TelerikNEXT`. If this is the case notice that `https://github.com/NativeScript/sample-TelerikNEXT` is already an application created with NativeScript CLI. In this situation I can suggest you to do the followings:
1. tns create <appName> --copy-from **`<path-to-sample-app>/app`**
2. tns platform add ios
3. Notice that this is TypeScript sample and you need to transpile it to JavaScript. I suggest you to execute the followings:
*  `dir *.ts /b /s > ts-files.txt` if you're working on Windows or `find . -iname "*.ts" > ts-files.txt` if you are on Mac.
*  `tsc --module commonjs --target ES5 @ts-files.txt`
4. This application is using the drawer component from Telerik UI [for iOS](http://www.telerik.com/ios-ui/sidedrawer) and [Android](http://www.telerik.com/android-ui/sidedrawer). You can add drawer libraries to NativeScript app using our CLI library add command - `tns library add <platform> <path to library>`.

Let me know if this helps.
