### ISSUE TITLE
Problem building with cocoapod

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1280]
pod 'ZendeskSDK'

ld: warning: directory not found for option '-F/Users/steve/Dropbox/Projects/Apps/hello-world/platforms/ios/../../lib/iOS'
ld: warning: could not create compact unwind for .LFB3: non-standard register 5 being saved in prolog
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CABasicAnimation", referenced from:
      objc-class-ref in ZendeskSDK(ZDKUIActivityView.o)
  "_OBJC_CLASS_$_CAShapeLayer", referenced from:
      objc-class-ref in ZendeskSDK(ZDKRMAFeedbackView.o)
  "_OBJC_CLASS_$_MFMailComposeViewController", referenced from:
      objc-class-ref in ZendeskSDK(ZDKArticleViewController.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

**Comment by jasssonpet** [comment]
Hello, @sitefinitysteve,

The ZendeskSDK seems to depend on the QuartzCore and MessageUI frameworks. You can link with them by adding a `build.xcconfig` file in `platforms/ios` with the following contents:

```
OTHER_LDFLAGS = $(inherited) -framework "QuartzCore" -framework "MessageUI"
```

It's very similar to the [nativescript-google-mobile-ads-sdk](https://github.com/nikolay-diyanov/nativescript-google-mobile-ads-sdk/blob/master/platforms/ios/).

**Comment by sitefinitysteve** [comment]
@jasssonpet Thanks!  ...how on earth does one determine that is the issue btw?

**Comment by jasssonpet** [comment]
I'm glad that it worked for you. Looking at the error message `CABasicAnimation` and `CAShapeLayer` are undefined symbols. According to the Apple docs are defined in QuartzCore. Similarly for `MFMailComposeViewController`.
