### ISSUE TITLE
Karma + Babel won't run tests

### ISSUE THREAD

**Issue by N3ll** [NativeScript/nativescript-cli#1286]
_From @stevetayloruk on November 30, 2015 12:7_

When using Babel/ES6 and unit tests (mocha or jasmine - tried both) I'm getting an error when the tests run.  The error i think is down to the the babel after-prepare as disabling this gets rid of the error but then the app doesn't run. I'm using "tns test ios --emulator" command.

The error I'm getting is: 

```
30 11 2015 11:46:42.230:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
30 11 2015 11:46:42.236:INFO [launcher]: Starting browser NativeScript Unit Test Runner
Successfully prepared plugin nativescript-unit-test-runner for ios.
Project successfully prepared
Executing after-prepare hook from /Users/stevetaylor/Projects/raise/raise-app/raise/hooks/after-prepare/nativescript-dev-babel.js
Cannot read property 'appDestinationDirectoryPath' of undefined
# test ios
```

and the tests do not run.

Any ideas?

Thanks

Steve

_Copied from original issue: NativeScript/NativeScript#1182_

**Comment by tailsu** [comment]
It's was bug in the Babel hook. Try updating the `nativescript-dev-babel` to 0.1.4 and see if the problem goes away.

**Comment by stevetayloruk** [comment]
Yes, thats fixed the error.  Still can't get them to run though.  App is saying No reachable hosts now.  Must be a config issue i guess.

**Comment by tailsu** [comment]
The app runs in the simulator and says "No reachable hosts"? I can't see how this could be possible, as the simulator shares the network interfaces of the host. Can you paste in the contents of `node_modules/nativescript-unit-test-runner/config.js`, please?

**Comment by stevetayloruk** [comment]
module.exports = {"port":9876,"ips":["192.168.1.68"],"options":{"debugTransport":false,"debugBrk":false}}

**Comment by tjvantoll** [comment]
I’m hitting the same issue. I have the same `config.js`, and `tns test ios --emulator` gives me a screen that says “no reachable hosts”.

**Comment by jasssonpet** [comment]
Hello, @tjvantoll,

I know this is a long shot, but can you open you `platforms/ios/build/emulator/APP_NAME.app/Info.plist` and check if there is the key for [`NSAppTransportSecurity`](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33). This might be blocking the requests to the server.

If this is the case, you should run `tns emulate ios` first, and then your second `tns test ios` command should succeed.

**Comment by tjvantoll** [comment]
Hey @jasssonpet,

The {N} CLI seems to automatically add `NSAppTransportSecurity` to my Info.plist every time I exectute `tns test ios`. I’m assuming that flag needs to be set for the tests to run successfully?

**Comment by tailsu** [comment]
Yes, it does, because the unit test client connects to the Karma server over plain HTTP. Is what you're saying that the flag is set, but the emulator still shows "no reachable hosts"? Have you tried deleting the `platforms/ios/` folder and rebuilding?

**Comment by tailsu** [comment]
Same issue: https://groups.google.com/forum/#!topic/nativescript/YyxwmWOKmH0

**Comment by tjvantoll** [comment]
> Is what you're saying that the flag is set, but the emulator still shows "no reachable hosts"?

Correct. I have the code below in my `Info.plist`, and I still see “no reachable hosts” when I run `tns test ios`.

```xml
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
```

> Have you tried deleting the platforms/ios/ folder and rebuilding?

I just tried that and I have the same problem. Here’s exactly what I’m running:

```
git clone https://github.com/NativeScript/sample-Groceries.git
cd sample-Groceries
tns init
tns emulate ios
tns test ios --emulator
```

**Comment by ligaz** [comment]
It looks like the issue is caused by a newly release version of the socket.io client library referenced by karma. If you manually revert to the old version of the library (change the contents of `node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/socket.io.js` to `https://raw.githubusercontent.com/socketio/socket.io-client/1.3.7/socket.io.js`) the tests are executed. Unfortunately Karma is referencing socket.io with `^` which causes this incorrect behavior.

We will continue the investigation on our side.

**Comment by ligaz** [comment]
Pull Request issued against socket.io that handles the issue: https://github.com/socketio/socket.io-client/pull/932

**Comment by ligaz** [comment]
Another one: https://github.com/socketio/engine.io-client/pull/453

**Comment by ligaz** [comment]
:tada: Good news everyone. Socket.io has a [new version](http://socket.io/blog/socket-io-1-4-5) that has the fix included. Just nuke your `node_modules` and `npm install` again.
