### ISSUE TITLE
tns build breaks permanately if you have drawable-invalid name

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1296]
I created a drawable-xdpi & drawable-xxxdpi  (notice the missing H)
Well tns aborted the build and reported the first one was bad, and I realized I missed the h in both of them.  So I added the missing h to both folder..   Tried to build again, still fails with the same bad folder name.  But my copy isn't bad.   However, tns still has the BAD folder names in the platform folder
platforms/android/src/main/res/ that you have to go manually delete before you can build again.

**Comment by dtopuzov** [comment]
Still valid in {N} 2.0.1.
Workaround: Delete your platform folder.

**Comment by enchev** [comment]
Hey @NathanaelA,

What we can do in case of gradle build error is to suggest `platform remove/add`. Will this work for you? I've made pull request with this implemented.

**Comment by enchev** [comment]
I've made second attempt to fix this. We will validate App_Resources drawable resources and we will stop the build in case of invalid.

**Comment by NathanaelA** [comment]
I know about **platforms remove/add** -- however, I think this is something that maybe should be handled by the new **tns clean** command (not sure the status but I thought it was coming in the next version), and if a gradle image error occurs, maybe a clean is auto-ran and then the rebuild is restarted, so the end user actually is not impacted..

One note:  I personally feel remove/add really shouldn't be needed for normal things, tns is in control of the platforms folder, it should maintain it properly.  :grinning:

**Comment by enchev** [comment]
Hey @NathanaelA,

In my opinion it will be better if we prevent the error at first place by validating resources. `tns clean` is another story and we will do our best to deliver it asap.

**Comment by NathanaelA** [comment]
@enchev I TOTALLY agree; eliminating any errors a end user sees is the BEST policy.  :grinning:   

I just was trying to throw out suggestions in case verifying the images turned into a problem...

**Comment by enchev** [comment]
Hey @NathanaelA,

Unfortunately we found that cannot handle this problem easily and I've removed the code that validates drawables. The other option will be to use our new clean command in such cases:
`tns platform clean android`

**Comment by NathanaelA** [comment]
Bummer on the validation.   As long as the clean works that is acceptable to me.   To me their needs to be a easy way to recover from this...

In the event any error occurs during building; can we make sure that the "tns platform clean" command is displayed as part of the suggestions for how to recover?
