### ISSUE TITLE
tns test --watch syncs running slowly

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1300]
I'm playing with the `tns test` command and noticed that `tns test --watch` always does a full sync, which is very slow.

Comparing a "no live sync" test run:

```
~/w/test-hello (master) $ time -p tns test android --emulator
03 12 2015 13:34:18.461:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
03 12 2015 13:34:18.466:INFO [launcher]: Starting browser NativeScript Unit Test Runner
Successfully prepared plugin nativescript-unit-test-runner for android.
Project successfully prepared
Transferring project files...
Successfully transferred all project files.
Applying changes...
Successfully synced application org.nativescript.testhello.
03 12 2015 13:34:33.451:INFO [NativeScript / 22 (5.1; api22)]: Connected on socket v5usYHC0KX3BiN2WAAAA with id NativeScriptUnit-8437
NativeScript / 22 (5.1; api22): Executed 1 of 1 SUCCESS (0.068 secs / 0.001 secs)
real 16.99
user 1.24
sys 0.04

```

And a live sync one:

```
03 12 2015 13:36:07.504:INFO [watcher]: Changed file "/home/local/TELERIK/hdeshev/w/test-hello/app/tests/example.js".
03 12 2015 13:36:07.755:WARN [karma]: No captured browser, open http://localhost:9876/
03 12 2015 13:36:07.756:INFO [launcher]: Deploying NativeScript unit tests...
Successfully prepared plugin nativescript-unit-test-runner for android.
Project successfully prepared
Transferring project files...
Successfully transferred all project files.
Applying changes...
Successfully synced application org.nativescript.testhello.
03 12 2015 13:36:22.938:INFO [NativeScript / 22 (5.1; api22)]: Connected on socket yGau5T5b3yoOFyLeAAAC with id NativeScriptUnit-9988
NativeScript / 22 (5.1; api22): Executed 1 of 1 SUCCESS (0.028 secs / 0 secs)
03 12 2015 13:36:23.740:WARN [NativeScript / 22 (5.1; api22)]: Disconnected (1 times)
```

Total time: 13:36:22 - 13:36:07 = 15 seconds.

So, we have 17 seconds without live sync vs. 15 seconds with live sync. In addition both commands seem to do the same thing: preparing and transferring files.

So, am I doing something wrong here? Does this happen on android or emulators only? And, most importantly, can we make live synced test runs start instantly?

**Comment by tailsu** [comment]
Yes, it's an Android thing. Yes, it can be made to start in about 3-4 seconds. @Fatme has a prototype in the works, but hasn't had the time to complete it.

**Comment by ligaz** [comment]
Hey @hdeshev,

We have done some performance optimizations for Android's LiveSync in `1.6.0`. Also some improvements to the unit testing support will land in `1.6.2`. 

Can you share your experience using them?

**Comment by hdeshev** [comment]
It's been great. Testing is a lot faster and usable in day-to-day activities.
