### ISSUE TITLE
"Session ended without errors" in log when iOS application crashes with segmentation fault

### ISSUE THREAD

**Issue by tailsu** [NativeScript/nativescript-cli#1301]
The message in the system log is something along the lines of 

```
DF75F7A293C9.launchd_sim[41185] (UIKitApplication:org.nativescript.foo[0x6f85][41233]): Service exited due to signal: Segmentation fault: 11
```

Can be simulated by adding `*(int*)0 = 0;` into `main.m`.

**Comment by fealebenpae** [comment]
This is printed by Xcode's CoreSimulator framework which `ios-sim-portable` uses internally to launch Simulator applications and it happens on every launch, irrespective of whether or not the simulated app has exited gracefully or at all. I agree that it is confusing, but I'm not sure there's a way to suppress it without losing all of `ios-sim-portable`'s output, which also includes the `stdout` and `stderr` of the simulated application.

**Comment by enchev** [comment]
Outdated issue closed.
