### ISSUE TITLE
`--nobrowser` option for the `tns help` command (command to generate html help)

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#1302]
Introduce an option for the tns help command, so that it prepares the documentation, but does not launch a browser. This way the documentation will get collectible by other tools.

**Comment by rosen-vladimirov** [comment]
What's the use-case here?
Currently we are showing browser help in case you use
`tns help <command name>`
But in case you need command line help you can use `tns <command name> -h `

**Comment by teobugslayer** [comment]
This is needed to generate CLI documentation for publishing on docs.nativescript.org.
I think, a dev- command is more appropriate here.

**Comment by teobugslayer** [comment]
Actually, I've implemented the `dev-generate-help` command. As any dev- command it lacks help.

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by dtopuzov** [comment]
Html is generated at node_modules\nativescript\docs\html
