### ISSUE TITLE
TNS 1.5 Android build error

### ISSUE THREAD

**Issue by gverschuur** [NativeScript/nativescript-cli#1303]
When I try to build/run my app on a Android device, the process quits with the following error:

```
:processDebugResources
Unknown source file :       Unable to add '/Volumes/Development/apps/nativescript-demo/platforms/android/build/intermediates/assets/debug/app/tns_modules/semver/semver.browser.js.gz': file already in archive (try '-u'?)
Unknown source file : ERROR: unable to process assets while packaging '/Volumes/Development/apps/nativescript-demo/platforms/android/build/intermediates/res/resources-debug.ap_'

:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/opt/android-sdk/build-tools/23.0.1/aapt'' finished with non-zero exit value 1
```
I tried the following solutions and none of them worked:

* reinstall the android platform
* use a different SDK (23, 22, etc)
* clean the NPM cache
* clean the build folder

OSX 10.10.5, TNS 1.5

**Comment by Hyra** [comment]
Looks like an issue with Gradle looking through all the folders, including the `node_modules`.

I had the same error, but after (re)moving the node_modules folder somewhere else the build process finishes with:

```BUILD SUCCESSFUL

Total time: 33.272 secs```

**Comment by teobugslayer** [comment]
Can you please clean up your project, by removing the node_modules and platforms directories and update to the latest version of semver? It removed the offending .gz file.

**Comment by teobugslayer** [comment]
I am closing this issue as there is nothing else we can do.
