### ISSUE TITLE
Allow use of icon font codes in the TabView

### ISSUE THREAD

**Issue by jlooper** [NativeScript/nativescript-cli#1306]
Currently, we can add an icon code to an element that has a 'text' property (like Label or Button). I'd like to use icons within a TabView and currently have to use an image because we have access only to the properties "iconSource" and "title". The Title should be the text, but maybe we can add a separate "iconCode" that would allow us to use an icon code.

Right now my tab bar looks like this on iOS:

![o6bcke0at30ugxta8jsiuamd3npw61uwekleq5as1ku](https://cloud.githubusercontent.com/assets/1450004/11565320/6d6413f8-99ab-11e5-9198-341878fb0432.png)

Using icon codes will allow me to avoid more image scaling battles. Thanks!

**Comment by ligaz** [comment]
This issue was moved to NativeScript/NativeScript#1217
