### ISSUE TITLE
Strange case of XML linting

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#1307]
I'm testing the just released XML error reporting (https://github.com/NativeScript/nativescript-cli/issues/1272) and it looks really nice, but I stumbled on an edge case with a malformed XML file:

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
  </StackLayout>
</Page
```
Here the closing `>` at the end is missing.

When I execute a `tns prepare ios` command, the CLI just hangs in what seems to be an infinite loop and there is no way to stop it (`CTRL`+`C` not doing it).

Every other kind of error got reported just fine, but this was the first thing I tried to do and it was a bit confusing :smile_cat:

After a couple of minutes the following appears:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    52930 abort      tns prepare ios
```

**Environment:**
OS X: 10.10
CLI: 1.5.1
Node: 0.12.7
NPM: 2.11.3
Xcode: 7.0

**Comment by teobugslayer** [comment]
Confirmed. Logged as https://github.com/jindw/xmldom/issues/139 and https://github.com/jindw/xmldom/issues/142 upstream.

**Comment by jindw** [comment]
fixed!

thanks

**Comment by jasssonpet** [comment]
:+1:
