### ISSUE TITLE
Live sync endless loop

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1308]
Running `tns livesync android --watch --log trace` on the angular todomvc project ends up with an endles file change -> prepare -> compile -> file change -> prepare ... loop.

To reproduce, clone the project, add a platform, and run the command above:
https://github.com/NativeScript/sample-ng-todomvc

**Comment by Fatme** [comment]
The problem is in `https://github.com/NativeScript/sample-ng-todomvc/blob/master/hooks/before-prepare/10-fix-zone-typings.js` hook. 

The code that fixes the problem is:
```
if (!$usbLiveSyncService.isInitialized) {
        var zoneDts = path.join('node_modules', 'angular2', 'typings', 'zone', 'zone.d.ts');
        shelljs.sed('-i', /.*reference.*path.*es6-shim.*\n/g, '', zoneDts);
}
```
