### ISSUE TITLE
tns debug android - doesn't is not using the latest code

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-cli#1312]
When I run [tns debug android], then make some changes to the code and run [tns debug android] again, the debugger doesn't seem to be picking up the changes.
I noticed this behaviour since I started using 1.5 with TypeScript.
Changes to ts files are not picked up, even though the js files do get updated.
The same happens when I try to add font or image files.

At the moment I have to run [tns build android] and then back again [tns debug android].

**Comment by Fatme** [comment]
It's a really strange. `tns debug` should always build the project at first step. Can you execute `tns debug android --log trace` and send us the output?

**Comment by rosen-vladimirov** [comment]
Hi @sebawita 
Do you still reproduce the issue? We have fixed several similar cases, so can you try it once again and see if it works ?

**Comment by ligaz** [comment]
Hey @sebawita,

I'm going to close this issue for now. If you are still able to reproduce it please reopen it. Thanks.

**Comment by sebawita** [comment]
Hi @ligaz, I can still reproduce it on my machine.
I am using Windows 10. NativeScript 1.6

**Comment by rosen-vladimirov** [comment]
@sebawita can you try the following:
```Shell
$ tns create app1 --template tsc
$ cd app1
$ tns debug android --justlaunch
$ // apply some change in the source code in projectDir/app/
$ tns debug android
```
Do you reproduce the issue this way?
