### ISSUE TITLE
tns livesync <platform> --watch is not working for changed platform specific files

### ISSUE THREAD

**Issue by x4080** [NativeScript/nativescript-cli#1313]
Hi,

When I change the content of .ios.js, the changes not reflected in the simulator (don't know about device), if I re run ins live sync iOS --watch again or without --watch, it changes (but not in the --watch state)

**Comment by Fatme** [comment]
https://github.com/telerik/mobile-cli-lib/pull/562

**Comment by dtopuzov** [comment]
*.ios.js files fail to sync in iOS simulator:

Unable to sync files. Error is: ENOENT: no such file or directory, stat '/Users/topuzov/Git/test/TestApp/platforms/ios/TestApp/app/details.ios.js'

**Comment by m-abs** [comment]
I see a similar error as @dtopuzov with Android modules from a Linux PC:

"""
Unable to sync files. Error is: ENOENT: no such file or directory, stat '/home/m_abs/project/playerdemo/platforms/android/src/main/assets/app/shared/sound.android.js'
"""

NativeScript 1.6.1

**Comment by rosen-vladimirov** [comment]
Yep, the livesync is not working when `--watch` option is used and platform specific file is modified, for example `main-page.android.js`. I've just merged a fix for this in the release branch :)
