### ISSUE TITLE
Unable to not --debug-brk

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1314]
Okay so I don't know why we have a --debug-brk option.  

tns debug <platform> --emulator
Says that or start not specified, loads with debug-brk by default

tns debug <platform> --emulator --debug-brk
Loads with debug-brk

tns debug <platform> --emulator --start
Wont load unless the emulator is currently running

As far as I can tell there's no way to start a debug without it pausing on app load.  WHICH IS A GREAT FEATURE don't get me wrong, I just only need it like 10% of the time.

Sidenote:
IMO it would make more sense to rename it to --break-on-load as debug is the command it's a double debug.

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/nativescript-cli/issues/1376
