### ISSUE TITLE
LiveSync does not respect deleted files on some android devices

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1315]
If I delete a .xml/.css file it is not removed from the app on the device. Then if I delete a .js file (supposed to trigger a full livesync) it is removed from the app on the device, but the previous deleted files still stay on it.

**Comment by Fatme** [comment]
This issue happens on some android devices. The runtime does not handle files from /data/local/tmp/<appIdentifier>/removedsync.
