### ISSUE TITLE
Can't livesync Android app : "spawn ENAMETOOLONG"

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/nativescript-cli#1317]
Hello,

Since i updated to NS 1.5.0, i can't livesync my app.
Here is the error details :

>C:\Users\XX\Documents\Perso\Dev\XX>tns livesync android --watch
>Executing before-prepare hook from C:\Users\XX\Documents\Perso\Dev\XX\hooks\before-prepare\nativescript-dev-typescript.js
>Found peer TypeScript 1.7.3
>Project successfully prepared
>Transferring project files...
>spawn ENAMETOOLONG

- Windows 10 Pro
- NodeJs 4.2.2
- NS 1.5.0
- Typescript 1.7.3

EDIT : tns doctor :
> No issues were detected.

Regards,
Guillaume

**Comment by vchimev** [comment]
Hi @guillaume-roy,

This issue has already been fixed in {N} CLI 1.5.1 - https://github.com/NativeScript/nativescript-cli/issues/1246.

**Comment by guillaume-roy** [comment]
Hi @vchimev,

Thanks for your reply. Do you have a release date for NS CLI 1.5.1 ?

**Comment by vchimev** [comment]
@guillaume-roy,

{N} CLI 1.5.1 was released last week.
