### ISSUE TITLE
Livesync not generating metadata after a native plugin is added

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#1318]
At the moment if you add a plugin with a native iOS dependency and then try to run livesync, CocoaPods are getting installed, but no metadata is being generated so the APIs are unavailable.

**Example:**
```bash
$ tns create TestApp
# Do some work
$ tns plugin add TestPlugin
$ tns livesync ios # Livesync doesn't have metadata for new APIs
```

**Workaround:**
```bash
$ tns create TestApp
# Do some work
$ tns plugin add TestPlugin
$ tns run ios # Call build explicitly generating new metadata
$ tns livesync ios # Livesync can use new APIs from now on
```

**P.S.** I believe that the situation with Android is similar, but I haven't tested it.

**P.P.S.** I think that the same thing is happening if I create an app and try to livesync immediately after that:

```bash
$ tns create TestApp
$ tns livesync ios
shell.js: internal error
TypeError: Path must be a string. Received null
IosEmulatorServices.prototype.syncCore
```

**Comment by Fatme** [comment]
The described behavior is expected, we need to provide some documentation with all restrictions from livesync.

**Comment by enchev** [comment]
In my opinion we should enable by default `livesync --watch` similar to AppBuilder CLI. In this way the app will be updated automagically after every change in XML, JS, CSS, etc. Rebuilding plugins can be time consuming and we should be extra careful, still we can show at least warning that plugin is added and the app should be rebuilt.

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/nativescript-cli/issues/1366
