### ISSUE TITLE
When using iOS shared frameworks, the CLI should respect the current iOS deployment target

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#1320]
If the Xcode project has an iOS deployment target greater than 8.0, the CLI should keep it when adding shared frameworks or using CocoaPods. The upgrade of the deployment target should happen if it's less than 8.0 only.

**Comment by jasssonpet** [comment]
This issue should be no longer relevant after we remove the iOS 7 support.

**Comment by enchev** [comment]
We no longer support iOS7
