### ISSUE TITLE
Android 1.5.0 : LogCat trace disabled and no way to enable it

### ISSUE THREAD

**Issue by karaahmed** [NativeScript/nativescript-cli#1323]
I think it would be useful for experienced mobile developers to see the LogCat trace on run time.
Currently it is removed for v1.5.x and there is no way to enable it. Maybe adding an option 
like "--showFullTrace" or similar deserves.

**Comment by NathanaelA** [comment]
@karaahmed - Uhm, you do know that you can open another terminal and type **adb logcat** and you will see the logcat...

**Comment by rosen-vladimirov** [comment]
The idea is to have filtered log when executing `tns run android` for example. In case you need the full log, with version 1.6.0 you'll be able to call `tns device log` and this will show the full output.
@karaahmed  do you think this is fine, or you would like a flag on `tns run` command?
