### ISSUE TITLE
Unpaired but connected Android device does not return any devices info on tns device

### ISSUE THREAD

**Issue by nikolay-diyanov** [NativeScript/nativescript-cli#1329]
If you connect an Android device to a Mac, but you do no tap the Authorize button, adb devices returns an unauthorized device, while tns device returns a record for the device in the table, but there is no device identifier, nor you are told that the device is unauthorized. It will be better, if we return that info.

Here is the log of that situation:

execFile: /usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.3.2/tools/android "--help"

       Usage:
       android [global options] action [action options]
       Global options:
  -h --help       : Help on a specific command.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -s --silent     : Silent mode, shows errors only.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.

Exec uname -a 
 stdout: Darwin diyanovmac.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 2.11.3
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 7.1
Build version 7B91b
 
 stderr: 
Exec pod --version 
 stdout: 0.39.0
 
 stderr: 
Exec '/usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
 
 stderr: 
spawn: /usr/local/Cellar/android-sdk/24.3.2/tools/android "-h"
Exec mono --version 
 stdout: Mono JIT compiler version 4.0.4 ((detached/d481017 Mon Sep 28 17:32:19 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
 
 stderr: 
Exec git --version 
 stdout: git version 1.8.4
 
 stderr: 
Exec gradle -v 
 stdout: 
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_71 (Oracle Corporation 24.71-b01)
OS:           Mac OS X 10.10.5 x86_64

 
 stderr: 
Exec "javac" -version 
 stdout:  
 stderr: javac 1.7.0_71

System information:
{ procInfo: 'nativescript/1.5.1',
  platform: 'darwin',
  os: 'Darwin diyanovmac.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.7',
  npmVer: '2.11.3',
  javaVer: '1.7.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.1\nBuild version 7B91b\n',
  itunesInstalled: true,
  cocoapodVer: '0.39.0',
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: '4.0.4',
  gitVer: '1.8.4',
  gradleVer: '2.7',
  javacVersion: '1.7.0_71' }
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'device'.
AnalyticsInstallationID: dec7f90a-1750-4b18-a220-28f0bfb9a318
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
execFile: /usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb "help"
spawn: /usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb "start-server"
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'device|*list'.
startLookingForDevices; platform is undefined
spawn: /usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb "devices"
Statistics was sent successfully (xhr).
spawn: /usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb "-s" "undefined" "shell" "getprop"
{}
spawn: /usr/local/Cellar/android-sdk/24.3.2/platform-tools/adb "-s" "undefined" "shell" "cat" "/system/build.prop"
{}
Found device with identifier 'undefined'
┌───┬─────────────┬──────────┬───────────────────┐
│ # │ Device Name │ Platform │ Device Identifier │
│ 1 │             │ Android  │                   │
└───┴─────────────┴──────────┴───────────────────┘
Statistics was sent successfully (xhr).

machinemac:~ machine$ tns device
┌───┬─────────────┬──────────┬───────────────────┐
│ # │ Device Name │ Platform │ Device Identifier │
│ 1 │             │ Android  │                   │
└───┴─────────────┴──────────┴───────────────────┘
machinemac:~ machine$

**Comment by rosen-vladimirov** [comment]
With 1.6.0 release, we'll show another column with header "Status"
The values in it will be "Connected" when the device is reachable and "Unreachable" in case it is locked, not trusted, etc.
