### ISSUE TITLE
Workaround for static library required architecture?

### ISSUE THREAD

**Issue by speigg** [NativeScript/nativescript-cli#1345]
When I try to wrap a third-party static library as a nativescript plugin, I receive the following error: 

```
Processing node_modules failed. Exception: The static library at {plugin-path}/platforms/ios/libX.a is not built for one or more of the following required architectures: armv7, arm64, i386. The static library must be built for all required architectures.
```
The [hard-coded requirement](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts#L477) for static libraries to support armv7, arm64, and i386 makes it impossible to use this third-party static library. The third-party static library I am trying to use (for iOS) only supports: `armv7 armv7s arm64` (it does not support the iOS Simulator).  

Can an option be introduced to change the required architectures, or to workaround this restriction somehow?

**Comment by rosen-vladimirov** [comment]
Hi @speigg ,
You are correct - currently the validation is hard-coded and we'll have to find a way to make it a warning. The problem I see here is that if we skip the validation and the static library is not built for simulator, we'll still try to build the app for simulator by default. But in case you are building for device, we should not validate against i386 (used for simulator). 
We'll try to find the best solution, but meanwhile I suggest you to remove the i386 from nativescript-cli validation on your side (just find the `ios-project-service.js` file in the installation dir of nativescript-cli and remove the "i386" from the array used for validation.

Thanks for reporting this :)

**Comment by speigg** [comment]
Thanks @rosen-vladimirov. Ideally I would like to build for both the simulator and device, and simply not use the library in the simulator. Is that possible?

**Comment by jasssonpet** [comment]
Hello @speigg,

I would like to suggest a workaround.

Instead of using the support from the NativeScript CLI for static libraries, you can use a [xcconfig file](https://pewpewthespells.com/blog/xcconfig_guide.html) to optionally link with it.

Something like:

```
FOO[sdk=iphoneos*] = -l"X" -L"$(SRCROOT)/../../node_modules/X-plugin/platforms/ios"
```

**Comment by speigg** [comment]
Thanks for the suggestion @jasssonpet! I actually tried that too :) 

I'm not sure if it worked though... I'm still unsure about how to access the library from javascript. Is there a step I am missing in order to generate the interface to the static library in javascript? It's a C++ library / headers, if that makes a difference...

I'm also unable to run `tns run ios` (even in a new project, see https://github.com/NativeScript/nativescript-cli/issues/1343). I have tried installing the plugin and running `tns prepare ios`, and then I open up the Xcode project and try building via the GUI (hopefully this does the same thing as `tns run ios` should do). 

I have also tried uncommenting the `TNS_TYPESCRIPT_DECLARATIONS_PATH` option in `internal/nativescript-build.xcconfig` but it doesn't seem to generate anything.

**Comment by speigg** [comment]
Hmm, based on conversation at https://groups.google.com/forum/#!topic/nativescript/JvUVr6yauCg, it seems I can't use a C++ library directly. Assuming I am able to wrap the library somehow, I think the workaround that @jasssonpet suggested is acceptable. Feel free to close this.
