### ISSUE TITLE
Livesync does not sync when package.json is changed

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1347]
Expected: install a new plugin and restart the app, currently the new plugin is not installed and new code may be written that depend on it leading to crash always mode.

**Comment by mriccia** [comment]
+1 when installing a new npm module, if tns livesync --watch is running, the module doesn't get included and the application crashes when it tries to require() the new module

**Comment by enchev** [comment]
Hey folks,

We want to keep livesync as fast as possible and that's why we are excluding changes in App_Resources, node_modules, package.json, etc.

You need to perform full rebuild in such cases.
