### ISSUE TITLE
Livesync both Android and iOS at the same time, only android updates

### ISSUE THREAD

**Issue by N3ll** [NativeScript/nativescript-cli#1354]
_From @sitefinitysteve on December 15, 2015 18:39_

http://www.screencast.com/t/jIgl2WZ4

When I just had iOS going by itself it seemed fine, when I added android on a new terminal window to sync as well, it just doesn't update iOS, android syncs just fine.

So from the video:
tns livesync ios --emulator --watch
tns livesync android --watch    (<-- Geny emulator)

_Copied from original issue: NativeScript/NativeScript#1258_

**Comment by Plamen5kov** [comment]
Hi,  @sitefinitysteve
Do you still have the same issue?

**Comment by sitefinitysteve** [comment]
@Plamen5kov I have not tried recently... I will today though

**Comment by Lampei** [comment]
I tried today and am experiencing the same issue.

**Comment by Lampei** [comment]
OK, I gave this another try today and it does not appear to be working for me.  I started an iOS instance and was successfully getting it to update.  I then started an android --watch and it started to sync correctly, but the iOS instance then stopped updating.  The terminal window states that it is applying changes and successfully synced application, but does not show in the emulator

**Comment by ejsuncy** [comment]
I'm encountering this error...
`EEXIST: file already exists, open '/Users/[username]/.local/share/.nativescript-cli/.lock`

I believe it is due to the race condition when both livesync processes attempt to create the `.lock` file...but the android livesync wins everytime, and the ios livesync quits watching after the error.

Is multiple livesync without race conditions on the roadmap?

**Comment by fbrcdx** [comment]
Same error here.
iOS watch failed after a few compilations with multiple livesync (iOS / Android).

`Error: EEXIST: file already exists, open '/Users/fabrice.caudoux/.local/share/.nativescript-cli/.lock'
    at Object.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/tools/broccoli/builder.js:35:48
    at /usr/local/lib/node_modules/nativescript/lib/common/fiber-bootstrap.js:10:13
    - - - - -
    at Error (native)`

**Comment by PedroAnibarro1** [comment]
Is this fix out? I saw that they merge it to the master but I'm still having this problem

**Comment by enchev** [comment]
The fix is our master branch only. Here is how to build your CLI from master:
https://github.com/NativeScript/nativescript-cli/#how-to-build
