### ISSUE TITLE
Question: "The project file is corrupted" error

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/nativescript-cli#1368]
When I type:
```
$ tns run android
```
I get the following error:
```
The project file is corrupted. Additional technical information: SyntaxError: Unexpected token /
```
This is happening when I am developing on Windows and move to Mac.

What is the project file? Is it package.json?

**Comment by Fatme** [comment]
Hi @gaurav-chandra,

Yes, the project file is `package.json`.
