### ISSUE TITLE
Consider removing --debug-brk parameter

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1376]
Neither --debug-brk nor --start option was specified. Defaulting to --debug-brk.

Since the android debug command is defaulting always to --debug-brk why do we have this parameter at all. Lets just remove this and have one thing less to worry about and show warning of.

**Comment by sitefinitysteve** [comment]
Agree
https://github.com/NativeScript/nativescript-cli/issues/1314

**Comment by teobugslayer** [comment]
I started implementing this but I am blocked by a bug in the Karma launcher and cannot verify that my change does not break the unit testing. Once this is resolved, I'll create a PR with the fix.

**Comment by blagoev** [comment]
On the other hand if we want the functionality to be able to run an app in debug without braking lets leave the parameter but remove the default setting. 
ie tns debug android will run the app in debug without braking on the first available statement.
