### ISSUE TITLE
Show a progress indicator when downloading platforms

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1382]
The first time you run `tns platform add`, the {N} CLI downloads the necessary files for the platform. That download can potentially take some time, especially on slow connections, and especially for the iOS platform.

As a feature request, we should show the download progress on the CLI so users don’t think the CLI has froze up. Even the simple thing where you append dots would help—i.e. Downloading files...............

**Comment by teobugslayer** [comment]
Good idea!
