### ISSUE TITLE
Tests crash on android emulator

### ISSUE THREAD

**Issue by losttime** [NativeScript/nativescript-cli#1386]
Developing on Windows 10 for Android (6.0) with the x86_64 emulator provided with Android Studio.

I have a one-page app that runs fine on the emulator. I'm attempting to start writing some tests for it. After setting up testing with jasmine (`tns test init --framework jasmine`) I run `tns test android`. The app launches briefly, then displays a java stack trace with a NativeScriptException.

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication:
com.tns.NativeScriptException: Failed to find module: "./", relative to: /
...
```

The only test I have is the unaltered `example.js`

**Comment by teobugslayer** [comment]
Hi @losttime, 

we are actively tracking and fixing issues in our dependencies which prevents running the unit tests correctly. Please check the [GitHub issue](https://github.com/NativeScript/NativeScript-cli/issues/1286) for details.

At the moment, we are waiting for the upstream to merge the fixes. I am sorry for the inconvenience caused but I can assure you that this is a high priority task for us.

**Comment by rosen-vladimirov** [comment]
Hi @losttime  ,
The issue in socket.io had been resolved. Just delete your node_modules and platforms directories and run `tns test android` again.
Also I believe you have faced another issue - https://github.com/NativeScript/nativescript-cli/issues/1332
So please run `tns run android` before executing `tns test android`
