### ISSUE TITLE
install errors (windows 10)

### ISSUE THREAD

**Issue by dryandsolid** [NativeScript/nativescript-cli#1389]
I keep getting the same error window when I try to do:
npm install nativescript -g

need to know how to fix this ...

see attached image
![nativescripterror](https://cloud.githubusercontent.com/assets/16564527/12285260/181283ee-b96d-11e5-8771-ba0e0ea84aec.png)

**Comment by rosen-vladimirov** [comment]
Hi @dryandsolid ,
You can find some more information for this error in these threads:
https://github.com/NativeScript/nativescript-cli/issues/1348
https://github.com/laverdet/node-fibers/issues/262

I'll try to prepare a custom build for you in the next few days, that includes laverdet's fix. Can you give me information which nodejs version are you using?

**Comment by dryandsolid** [comment]
No need yet. 
I'll do some research over the weekend. I think it's because I re-installed node on my d: drive - but npm is still (through scripts, etc) still pointing at my c: drive. Some premliminary tests last night indicated that might be the real issue. 

Steven Archibald
E-Mail: steven.archibald@sa-consult.com
Mobile: 510.684.4588
 
“Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”D Antoine de Saint-Exupéry, Airman's Odyssey
 
 
Date: Thu, 14 Jan 2016 08:06:02 -0800
