### ISSUE TITLE
Livesync not syncing assets

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1390]
_From @dragGH102 on January 12, 2016 21:32_

I am working on an Nativescript project on Android.

I noticed that when using **livesync** new assets in **App_Resources** (e.g. an image used by res://image) are not loaded.

In fact I don't see anything in particular in the terminal but most important I even need to

- uninstall the app (otherwise it just skips installation)
- delete 'build' folder (otherwise nothing new is actually uploaded)
- re-build / livesync

to make it recognize the new assets.

_Copied from original issue: NativeScript/NativeScript#1364_

**Comment by enchev** [comment]
_From @NathanaelA on January 12, 2016 22:12_

Any actual assets the app has to be rebuilt.  You should not have to delete the build folder nor uninstall the app.  If I recall correctly, the built in LiveSync doesn't typically rebuild the app; so you can use.    **tns run android** or **tns deploy android** and then after it deploys switch back to livesync mode.   Their maybe a faster way than this (using stock tools); but since I don't actually use the limited built in LiveSync stuff, I can't really tell you.  

I do know in my free LiveEdit product; I also have the same limitation for compiled resources; the app _must_ be rebuilt for any actual app_resources; these can't be synced to the device since they are compiled into the actual application.   So in my case if I change a resource; I leave my LiveEdit watcher running, and then do a simple **tns run android --emulator** and let tns rebuild the app and redeploy it, and then just continue editing any of the source code and then my LiveEdit keeps everything else in sync on the device.

**Comment by Fatme** [comment]
Hi @dragGH102,

LiveSync doesn't rebuild your application so you're not able to sync **resources** using `livesync` command. As  @NathanaelA pointed you can use `tns run android` or `tns deploy android` command. The another option is to uninstall the application from your device and run `tns livesync command`. {N} CLI will notice that the application is not installed on device and will build and install it. 

I can suggest you to move your images to `app` folder and load them from local file system - for example `<Image src="~/logo.png" / >`. More information can be found here https://docs.nativescript.org/ui/ui-images. This way you will be able to sync your images using `livesync` command.

**Comment by dragGH102** [comment]
@Fatme thank you for your answer.
I was in fact considering loading the images directly from filesystem at least while in development environment.
However my doubt is: **how to make different assets load for different screen dpi in this case?** (according to the DOCS this is not yet implemented and apparently no milestore for this has been defined)

**Comment by ligaz** [comment]
Indeed this feature has not been triaged. Please comment on the [issue](https://github.com/NativeScript/NativeScript/issues/276) that you are interested in it and we can continue the discussion there. I'm going to close this issue for now.

**Comment by johnnyzen** [comment]
This issue is still in 2.5 ??

I have tried everything to get new resources to show after adding to Android resource folder.

The only thing that works is following enchev instructions at the top.

Is this how it is?
