### ISSUE TITLE
Unit testing: `tns test android` command hangs

### ISSUE THREAD

**Issue by unlight** [NativeScript/nativescript-cli#1401]
Executing `tns test android` hangs and does not end.
I have example unit test, generated by `tns test init` (jasmine), according to this https://docs.nativescript.org/core-concepts/testing
```js
describe("Hello World Sample Test:", function() {
  it("Check counter.", function() {
    expect(42).toEqual(42);
  });
});
```
When I execute command, after preparing and syncing, I see blue screen with message
##### Found karma at 10.11.11.156 #####
And that's it. Nothing happens.
Console output:
```
Successfully transferred all project files.                                               
Applying changes...                                                                       
Successfully synced application org.nativescript.yesorno at Jan 18, 2016 5:51:27 PM.
```
Environment:
nativescript: 1.5.2
emulator: genymotion
node: 5.3.0
OS: Win64

**Comment by teobugslayer** [comment]
Hi @unlight,

we are actively tracking and fixing issues in our dependencies which prevents running the unit tests correctly. Please check the [GitHub issue](https://github.com/NativeScript/NativeScript-cli/issues/1286) for details.

At the moment, we are waiting for the upstream to merge the fixes. I am sorry for the inconvenience caused but I can assure you that this is a high priority task for us.

**Comment by rosen-vladimirov** [comment]
Hi @unlight ,
The issue in socket.io had been resolved. Just delete your node_modules and platforms directories and run `tns test android` again.
