### ISSUE TITLE
Livesync does not work when /data/local/tmp/<app-identifier> file exists on Android device

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1416]
Steps to reproduce:
tns run android --path TNS_App --justlaunch
<edit some xml file>
tns livesync android --path TNS_App --justlaunch
=> Still see old app on the phone.

**Comment by Fatme** [comment]
This happens when a file with name `app-identifier` exists in `/data/local/tmp` directory on device. In this case CLI is not able to create directory.

**Comment by teobugslayer** [comment]
Is this related to https://github.com/NativeScript/nativescript-cli/issues/1081 ?

**Comment by Fatme** [comment]
Yep

**Comment by teobugslayer** [comment]
`ls -l` -> `rm - rf`

**Comment by dtopuzov** [comment]
Duplicates #1081
