### ISSUE TITLE
No .apk found in /test/platforms/android/build/outputs/apk directory

### ISSUE THREAD

**Issue by do-web** [NativeScript/nativescript-cli#1417]
Creating a empty project with android. After i run tns run android --device 1 i get an error No .apk found in /test/platforms/android/build/outputs/apk directory. But there is an apk.

OS: OSX 10.11.02
CLI Version: 1.5.2

**Comment by raefa** [comment]
Hi Do-web. Can I asked why you closed this? What did you do to resolve the issue?

**Comment by humbss** [comment]
+1

**Comment by ignaciolarranaga** [comment]
Guys, seems there is some problem when the nativescript.is is not in the form: org.nativescript.XXX.
When named differently the project name in settings.gradle says __PROJECT_NAME__

**Comment by jwuliger** [comment]
I have been trying to build an app for hours now lol. Having the same problem. I a new to NativeScript (Coming Crapdova... oh I mean Cordova!).

So all I need to do is change my project name in "/platforms/android/settings.gradle"?

**Comment by blaur** [comment]
This is still an issue for me on iOS. Any suggestions??

**Comment by nmandyam** [comment]
Had the same problem, so I removed the platform (tns platform remove android), added it again, all OK now. Of course, I have my assets in app/App-Resources, so blowing away the platform is OK in my case - may not be in yours!

**Comment by kamlekar** [comment]
Though the above solution might work, it doesn't actually fix this issue. I request the author to reopen this issue. Thanks.

**Comment by ole1986** [comment]
Honestly, this really su*.
An initial part of a project cause to fail when doing a simple `tns run android` only because of this error

**Comment by Fatme** [comment]
@ole1986,

Can you give us the following information:
* The version of {N} CLI
* The content of your package.json file

**Comment by ole1986** [comment]
Any specific version?
