### ISSUE TITLE
CocoaPod verification makes CLI installation slower

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1418]
CocoaPod verification installs iOS runtime, creates a project and build it, this have two negative impacts:
- Slower CI builds (~30sec per build)
- Slower getting started

**Comment by x4080** [comment]
This usually happens when tns modules is changed

**Comment by teobugslayer** [comment]
There's workaround -> `npm i -g nativescript --ignore-scripts`
