### ISSUE TITLE
Show warning on OS X when installation is started with SUDO

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#1425]
On OS X when installation is started with `sudo npm i -g nativescript`, the post-install script might not be executed correctly. The reason is that the script is trying to write to user's profiles (`.bash_profile`, `.bashrc`, `.zshrc`) and to verify users setup. When using `sudo`, npm runs the post-install script with another user - `nobody` in order to prevent malicious scripts running on your machine. So the verification of user setup is not against the current user's environment and some incorrect warnings might be shown.

> NOTE: The workaround is to install the package with sudo and `--unsafe-perm` flag: `sudo npm i -g nativescript --unsafe-perm` This way the installation will use the current user for all scripts.

We should print warning that sudo is not required on OS X as the global installations work correctly without it. This way the post-install script will be executed with current user and the environment verification will be correct.

**Comment by dtopuzov** [comment]
Still valid in {N} 2.0.1

**Comment by tolerious** [comment]
not work for me, there  are . still many warnings.
<img width="1438" alt="2017-11-12 12 09 09" src="https://user-images.githubusercontent.com/2922120/32695827-52f5ad02-c7a2-11e7-84d6-f5691131b662.png">

**Comment by rosen-vladimirov** [comment]
Hey @tolerious ,
Please excuse us for the late reply. Can you please share more details about your issue?

**Comment by rosen-vladimirov** [comment]
We are no longer executing environment checks on post install and also our [post install actions](https://github.com/NativeScript/nativescript-cli/blob/74e50743dc9ef26fda5e50fa91ded7145d7d9148/lib/commands/post-install.ts#L18-L42) already check if the current command is run with `sudo`, so I do not think we need such a warning anymore, so I'm closing this thread.
