### ISSUE TITLE
[iOS] XCode v7.2+ Fails with Cocoapods on emulator

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1428]
This issue has cropped up multiple times in the NS community; and so far my advice has been to downgrade to 7.1.     This effects other communities (not just NS).   But since 7.2 and the new 7.3 beta has this issue this is something that we probably need to solve before v1.6 is released.  

This issue from everything I've read only appears in NativeScript when a cocoapod is added to the project; so fortunately it doesn't affect the majority of people.    But that means their might be something not being passed via the command line when it is building the cocoapod.

See: https://github.com/NativeScript/ios-runtime/issues/488

**Comment by Daxito** [comment]
Seems like one option is to downgrade to 7.1  AND  the other one is to run the app using:

tns livesync ios --emulator --watch

The last worked for me....for now.

**Comment by raefa** [comment]
+1

**Comment by alg** [comment]
+1

**Comment by AntonioCuevaUrraco** [comment]
Another workaround for now it is https://github.com/CocoaPods/cocoapods-deintegrate that solves the problem of the corrupted pods by clearing the dependencies so they are freshly installed again.

**Comment by NathanaelA** [comment]
Here is another datapoint from the forums (copy & pasted): 

**Antonio Cueva** said:
Yes, with Xcode 7.2 the pods get corrupted if you make a change on then, like adding a new one.
I was manually removing the ios platform and adding it again because only the first installation of the pods go through.
I also tested https://github.com/CocoaPods/cocoapods-deintegrate yesterday and it is solving the problem of the corrupted pods by clearing the dependencies so they are freshly installed again

**Comment by NathanaelA** [comment]
One thing to note; if you upgrade your iDevice to iOS 9.2; you are required to use XCode 7.2 or later of XCode to be able to deploy to the iDevice as 7.1 doesn't have the disk image information for iOS 9.2...

**Comment by NathanaelA** [comment]
This has been fixed by @ivanbuhov  & @Mitko-Kerezov and is tagged to show up in v1.6!    However, in the meantime I wrote up a blog post using Ivan's solution so that you can easily fix it now on your own projects.  http://fluentreports.com/blog/?p=214

**Comment by Daxito** [comment]
Not clear to me yet, is this fixed in {N} v1.6? do we have to still apply this workaround in {N}v1.6? 
I add and remove the platforms very often, you know, when weird stuff happens, so I prefer to not have to go back into this folder and modify that file every time, I already have to remember to add the NSAllowsArbitraryLoads everytime.

**Comment by NathanaelA** [comment]
@Daxito if you deinstall the platform and reinstall the platform (v1.6 and higher) it will then contain the fix.   It appears the @Mitko-Kerezov pushed a fix to the CLI (which I haven't tested) and might also fix it without @ivanbuhov fix.   But Ivan's fix from what I can tell is the actually root of the issue (which should be deployed in the v1.6 runtimes).

**Comment by Daxito** [comment]
Got it. I was trying to install the toast plugin today and just because of this error I had to uninstall it, I cannot wait for the new version come out!
