### ISSUE TITLE
Setup script issues

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1429]
- [x] the script installs *nodejs* version 5.1.0. It would be the best to install *nodejs* LTS version.
- [x] the script fails to install android build tools.
Output: `Error: Ignoring unknown package filter 'build-tools-23.0.2'`
- [x] the command `npm install -g nativescript` fails due to *npm* not found.

**Comment by vchimev** [comment]
https://gist.github.com/vchimev/e90a0f9a3ab1f7aa54a4

**Comment by vchimev** [comment]
![nodejs](https://cloud.githubusercontent.com/assets/12251337/12647634/c80cb0da-c5de-11e5-933e-e62767dbba83.png)

**Comment by vchimev** [comment]
If I have already installed jdk and android sdk they are not detected. The script install them again.

Log: https://gist.github.com/vchimev/c3381a754fb059596e1c

Screenshot:
![jdk](https://cloud.githubusercontent.com/assets/12251337/12648956/1595cb10-c5e5-11e5-8969-bffc60d329b2.png)

**Comment by vchimev** [comment]
The NPM warnings of the NativeScript CLI installation are colored in red, they can be mistaken for errors and make harder to see the real errors if any.

![tns](https://cloud.githubusercontent.com/assets/12251337/12649292/a5ba2d7a-c5e6-11e5-93e3-1ca78f3c05e9.png)

**Comment by teobugslayer** [comment]
About the red text, it is beyond my control.
About failing re-installations, I'll fix them.
About the first reported fail, I cannot reproduce it. I'll try couple more times.

**Comment by dtopuzov** [comment]
The script does not install "Local Maven repository for Support Libraries" which is required by tns (and doctor report it)

**Comment by enchev** [comment]
Already done.
