### ISSUE TITLE
Document the --log option

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1451]
For debugging I find the `--log` option to be quite handy, but it doesn’t appear to be documented in the CLI itself. For instance `tns build android --help` doesn’t mention it.

One side note: when an Android build fails, Gradle spits out the following warning:

```
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
```

I didn’t know it was Gradle issuing this warning—I thought it was `tns`. So I tried running `tns build android --stacktrace info`, which obviously didn’t work. Not sure whether we can do anything about this, but I thought I’d at least you know.

Thanks.

**Comment by rosen-vladimirov** [comment]
Hey @tjvantoll , 
In fact `--log trace` option is documented as global option. You can find information about it when executing `tns -h` or `tns help` - it's the last option at the bottom of the table. Maybe we should find a way to include it on a more visible place

**Comment by tjvantoll** [comment]
@rosen-vladimirov Hmmm... ok that makes sense. I think I was mostly thrown off by the Gradle error message. Ideally we could replace the Gradle error with one of our own that points people at the global `--log trace` option.

**Comment by rosen-vladimirov** [comment]
I'll check if there's option to replace the gradle output.

**Comment by enchev** [comment]
Already implemented
