### ISSUE TITLE
When a offline device is present the CLI can't debug on the other working device

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1463]
When there is a device/emulator in offline state the CLI can't work stating an error

"Cannot debug on multiple devices. Select device with --device option."

Expected: it should skipt this device/emulator an continue working with the available one

**Comment by rosen-vladimirov** [comment]
We should modify devicesService execute method to disregard Unauthorized devices.
Also in debug command filter only the devices that can be accessed :)

**Comment by pkoleva** [comment]
Still reproduced in {N} 2.0.1

**Comment by enchev** [comment]
Not relevant anymore since the CLI will start emulator in case of multiple devices not matter trusted or not
