### ISSUE TITLE
Remove confusing message when attaching a debugger

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1476]
This message is warning for something that may not happen depending on the actual command being used. For example the Attach debugger command (--start) will not deploy anything to the device. Now it is more visible when you try to attach since we are handling the issue that the app is not running. If we show an error message for that case it will be confusing since we stated early we will deploy something on the device which is actually not correct.

https://github.com/telerik/mobile-cli-lib/blob/36ddbba5326ad3ab09ae3378e1c8f911d01fa55b/mobile/mobile-core/devices-service.ts#L282

Action: Either remove this message or take into account the command executed.

**Comment by enchev** [comment]
Hey @blagoev,

What if we change the message to `Your application will work only on the device specified by the provided index or identifier.`? 

Hey @rosen-vladimirov what do you think?

**Comment by blagoev** [comment]
I am for just removing this message. It even does not show the selected device identifier ((we have the selected device in this._device)). It is not  useful imo.

This message tries to anticipate a user confusion about something which I think is not the case.

It is even too long - nobody will read it. 
A better message will be 
**Target device: emulator-5554** or something like that.

**Comment by enchev** [comment]
Thanks @blagoev, I like that as well! Hey @rosen-vladimirov, what do you think?

**Comment by enchev** [comment]
This issue was moved to telerik/mobile-cli-lib#767
