### ISSUE TITLE
LiveSync doesn't show any changes to a modal page

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1481]
If I open a view as modal, then make a change, I see the CLI detecting changes, but nothing is reflected in the actual view without a manual restart.

**Comment by enchev** [comment]
Hey @sitefinitysteve,

I believe that we can at least close the modal page when restarting the app. Will this work for you?

**Comment by sitefinitysteve** [comment]
Anythings better than nothing :)
