### ISSUE TITLE
Android will not build after adding iOS as platform

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/nativescript-cli#1483]
After adding iOS as a platform I can no longer Build, Run or LiveSync my app on Android. I receive the following error message:

```
Processing node_modules failed. Error: Command failed: C:\Windows\system32\cmd.e
xe /s /c "ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('C:\Dropbox\Native
Script\nextra-workplan2\platforms\ios\plugins-debug.xcconfig').merge(Xcodeproj::
Config.new('C:\Dropbox\NativeScript\nextra-workplan2\node_modules\nativescript-s
qlite\platforms\ios\build.xcconfig')).save_as(Pathname.new('C:\Dropbox\NativeScr
ipt\nextra-workplan2\platforms\ios\plugins-debug.xcconfig'))""
'ruby' is not recognized as an internal or external command,
operable program or batch file.
```

Also, when trying to ```tns prepare android``` the above error message appears .

**Edit 1**
Running ```tns platform remove ios``` and then ```tns prepare android``` appears to fix the issue.

**Comment by rosen-vladimirov** [comment]
Hi @mikeres0 ,
This issue has been already fixed and the fix will be included in our incoming 1.6.0 release.

**Comment by mikeres0** [comment]
@rosen-vladimirov  do you have any idea when this will be released? My fix seemed to work earlier but it is not anymore...

**Comment by rosen-vladimirov** [comment]
Hi @mikeres0 , 
We are planning the release for later this week or the next one. As a workaround I suggest you to find the `<your app>\node_modules\nativescript-sqlite\platforms\ios` dir and rename it, for example to `old_ios`. This way CLI will not try to prepare the iOS part of the plugin
