### ISSUE TITLE
How to use livesync with genymotion

### ISSUE THREAD

**Issue by abhisekgithub** [NativeScript/nativescript-cli#1488]
Hello,
      
        I succeeded to run the groceries app in genymotion emulator. But I want to execute the app in livesync mode, But I am unable to find the command to execute livesync along with genymotion emulator
I have tried
tns emulate android --geny "mydevice name" 
this is working perfectly

But when I am using 

tns emulate android --geny "mydevice name"  livesync android --emulator --watch
it is not working.
And can't find in the documentation how to make it work

**Comment by rosen-vladimirov** [comment]
Hi @abhisekgithub ,
You have to execute two separate commands:
```
tns emulate android --geny "mydevice name" --juslaunch
```
This will install the app on your device and will start it.
After that you have to start the livesync command:
```
tns livesync android --watch
```
Now you can make changes in your code and they'll be synced on the device :)

**Comment by abhisekgithub** [comment]
Resolved. Thanks

On Tue, Feb 16, 2016 at 1:39 PM, Rosen Vladimirov <notifications@github.com>
wrote:

> Hi @abhisekgithub <https://github.com/abhisekgithub> ,
> You have to execute two separate commands:
>
> tns emulate android --geny "mydevice name" --juslaunch
>
> This will install the app on your device and will start it.
> After that you have to start the livesync command:
>
> tns livesync android --watch
>
> Now you can make changes in your code and they'll be synced on the device
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NativeScript/nativescript-cli/issues/1488#issuecomment-184568861>
> .
>



-- 
*Abhisek Malakar*

**Comment by gabouh** [comment]
Hi @abhisekgithub , like an alternative I try: 
tns run android --geny "Custom Phone"livesync --watch
and it worked.

**Comment by yadinesh** [comment]
Hi,
I used the following one simple command to emulate on Geny and it worked smoothly:
tns livesync android --geny "my device name" --watch
Hope it helped :)

**Comment by ishandutta2007** [comment]
do you mean livesync on a new terminal ?
beacuse  `tns emulate android --geny Google_Nexus_5X_6_API23_1080x1920` doesnt terminate .

**Comment by Pip3r4o** [comment]
@ishandutta2007 you seem to have omitted the `--justlaunch` flag which will terminate the CLI process .

Alternatively you could start a genymotion emulator manually and execute `tns run android`, which will automatically livesync to the running device/emulator.
