### ISSUE TITLE
hello-world app should be submittable at the AppStore

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#1490]
Currently submission to the AppStore throws the following errors:
```
ERROR ITMS-90022: Missing required icon file. The bundle does not contain an app icon for iPhone / iPad Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."
ERROR ITMS-90023: Missing required icon file. The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format for iOS versions .+ 7.0.
ERROR ITMS-90023: Missing required icon file. The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 7.0.
ERROR ITMS-90023: Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format.
ERROR ITMS-90476: Invalid Bundle. iPad Multitasking support requires launch story board file 'LaunchScreen' in bundle 'org.nativescript.TNSAppTests'.
```
The icons may need to be listed in the Info.plist or carefully stored in xcasset (#683), there is a similar issue (#888).
The LaunchScreen was not added to my app's target.

**Comment by rosen-vladimirov** [comment]
I believe the missing icons should be added in the default App_Resources (tns-template-hellow-world). CLI cannot do anything in case you just delete some of them.

**Comment by rosen-vladimirov** [comment]
Maybe I'm wrong, but as far as I remember, the LaunchScreen should be added in the default Info.plist. So this is again part of the tns-template-hello-world and in case the user modifies it, CLI has nothing to do about it. 
@PanayotCankov  why do you consider this as bug in CLI, maybe I'm missing something here?

**Comment by fealebenpae** [comment]
@PanayotCankov @rosen-vladimirov the default Info.plist should explicitly disable iPad multitasking which will obviate the need for a LaunchScreen. iPad multitasking relies on AutoLayout and size classes so it's likely not to work for apps using NativeScript layouts anyway.

**Comment by PanayotCankov** [comment]
We will have to update the Info.plist in the hello world templates:

List all icons from the template in the Info.plist
`CFBundleIconFiles`
https://github.com/NativeScript/nativescript-marketplace-demo/blob/production/app/App_Resources/iOS/Info.plist#L43

Switch off iPad multitasking requiring
`UIRequiresFullScreen`
https://github.com/NativeScript/nativescript-marketplace-demo/blob/production/app/App_Resources/iOS/Info.plist#L31

We may also switch off the `LaunchScreen` storyboard and add all variants of the launch images. I think we currently miss some for iPhone6, 6+ etc.

**Comment by PanayotCankov** [comment]
We can also use *Images.xcassets*.

The CLI will add `app/App_Resources/iOS/Images.xcassets` as resource to the Xcode project.
In the `app/App_Resources/iOS/build.xcconfig` the following two flags can set icon and launch image from the *Images.xcassets*:
```
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = Brand Assets;
```

**Comment by fealebenpae** [comment]
iPad Pro will only support launch storyboards, not images: https://openradar.appspot.com/22915712

**Comment by PanayotCankov** [comment]
@fealebenpae Launch Storybards are better than images. But then it is hard to provide a decent editor outside the Xcode project. IMO we should have used a full Xcode project in the template (~app/platform) and inserted the resources and run-times similar to the way cocoa pods adds dependencies.

The best thing I can imagine for a launch storyboard, that is editable by a non-Xcode user, would be a 9-patch-like image, displayed by our default launch storyboard.

How would you address this issue?

**Comment by fealebenpae** [comment]
@PanayotCankov Place a simple storyboard in App_Resources with a single image view that loads the LaunchImage asset. This will work for 99% of users, IMO, the rest would need to edit the storyboard.

**Comment by jumenta1960** [comment]
Buenos dias. Por favor tengo el error 90023 icons. Que debo hacer en Info.plist? Gracias @AppColombiaNet
![unspecified](https://cloud.githubusercontent.com/assets/22826691/21294942/83a7b1fe-c517-11e6-8e9e-ab6da4ede9af.png) Lo anterior para poder subir el archivo a Tunes. Gracias
