### ISSUE TITLE
Having a .gitignore reference the platforms/ folder will break that cocoapod

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1495]
Ok, a friend of mine was working on creating a plugin today.  He created the JS, and platforms/ios/Podfile totally correct.    But he either copied a .gitignore from his app or accidentally put in his .gitignore file to ignore the platforms folder (as that is what you would do with normal {N} apps). 

So once he realized his mistake he just manually added the Podfile and commited it.   So when pulling down the plugin from github everything looked great!      
```
.gitignore
package.json
plugin.ios.js
platforms/ios/Podfile.
```
So trying to help him figure out why it isn't building -- I create a brand new app; and do a 
**tns plugin add \<path to plugin\>**  - It spins a little while, and then says everything is great.  
**tns prepare ios** & **tns build ios**, everything is great.  No errors (I should have really got the Signing error on the new app!); however the cocoapod is never installed and no xcworkspace (and all its related files) are never created.  So it basically is acting like the ns plugin has no cocoapod Podfile in the platforms/ios folder.   The node_modules looks fine, the package.json looks fine.   Just no Cocoapod installed.

He finally fixed his .gitignore file to eliminate the platforms/ folder reference and commited it and tried one more time to re-add his plugin and it actually worked.   I'm like, their is no way a .gitignore should cause this issue.    So I take my local copy; delete the .gitignore reference to "platforms/" and then reinstall the plugin, do a **tns prepare ios** and low and behold it shows that I have a cocoapod that it is installing, and now has all the proper xcworkspace and other support files needed for Cocoapod support...    

I'm not sure what part of the CLI tooling is at fault; but .gitignore is for GIT, not {N}, a faulty .gitignore should not factor into tns being able to actually use a cocoapod.

**Comment by dtopuzov** [comment]
@NathanaelA what exactly is content of .gitignore. Can you please verify the issue is still valid and provide exact steps to reproduce.

**Comment by NathanaelA** [comment]
Based on my description I wrote 4 months ago - above; it looks like the .gitignore file was just:
*platforms/* 
I will attempt to test this tomorrow, unless you beat me to it.

**Comment by NathanaelA** [comment]
I re-tested this, and it appears that it is now fixed.
