### ISSUE TITLE
[Babel] tns livesync android --watch is very slow

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1506]
Steps:

Git clone https://github.com/teobugslayer/hardcoreaww
Update everything in pacakge.json to latest versions.
Start android emulator and wait to boot
tns livesync android --watch

=> Livesync works but it is very very slow.

**Comment by jgeewax** [comment]
I'm still seeing about 15 seconds from save time (when livesync picks up the change) to deployment. Is this what's expected?

Comparing this to React Native it's quite a bit slower...
