### ISSUE TITLE
tns build iOS overwrites .plist changes

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/nativescript-cli#1507]
When building my app using ```tns build iOS``` all changes that I've made to my app.plist file are overwritten with the standard file. 

It is necessary for me to change the .plist file to allow arbitrary downloads, and it's pretty annoying having to manually edit the file **EACH** and **EVERY** time I wish to run my project.

**Comment by rosen-vladimirov** [comment]
Hi @mikeres0 ,
Which file are you modifying? With 1.6.0 release we've introduced Info.plist in app/App_Resources/iOS - you should modify it and prepare your app after that.

**Comment by mikeres0** [comment]
Hi @rosen-vladimirov,

I was editing the .plist file within ```Platforms/iOS/app_name/app_name.plist```. I'll try it with the file located within ```app/App_Resources/iOS``` and report back if there are any issues. 

Thanks for your help!

**Comment by rosen-vladimirov** [comment]
Hi @mikeres0 ,
Did you resolve your issue?

**Comment by mikeres0** [comment]
Apologies for not getting back sooner. Yes it did, thanks for your help! :+1:

**Comment by rosen-vladimirov** [comment]
I'm glad it worked for you. Our idea is to keep `platforms` dir out of source control, so there will be no need to modify anything inside it :)

**Comment by mikeres0** [comment]
It's a good idea! Awesome
