### ISSUE TITLE
iOS Emulator crashes when building NativeScipt application

### ISSUE THREAD

**Issue by gheron** [NativeScript/nativescript-cli#1511]
The process runs and return a successful message, but the emulator crashes after opening the application.

** BUILD SUCCEEDED **

Project successfully built.
Using  /Users/george/AndroidStudioProjects/iOSApps/NativeScript/PantonApp/platforms/ios/build/emulator/PantonApp.app
Starting iOS Simulator
Feb 18 17:30:32 MacBook PantonApp[28311]: 1   0xaf4b8 -[TNSRuntime executeModule:]
Feb 18 17:30:32 MacBook PantonApp[28311]: 2   0x5c183 main
Feb 18 17:30:32 MacBook PantonApp[28311]: 3   0x3f65a21 start
Feb 18 17:30:32 MacBook PantonApp[28311]: file:///app/tns_modules/ui/text-base/text-base.js:7:18: JS ERROR Error: Could not find module 'ui/text-base/text-base-styler'. Computed path '/Users/george/Library/Developer/CoreSimulator/Devices/605C75A1-A256-4874-BD6C-2E5AC0DE12E0/data/Containers/Bundle/Application/BF32F773-3389-41BB-BAF3-06F36FCF89CE/PantonApp.app/app/tns_modules/ui/text-base/text-base-styler'.
Feb 18 17:30:34 MacBook com.apple.CoreSimulator.SimDevice.605C75A1-A256-4874-BD6C-2E5AC0DE12E0.launchd_sim[28244] (UIKitApplication:com.pantoninc.piV1[0xf463][28311]): Service exited due to signal: Segmentation fault: 11

**Comment by mikeres0** [comment]
The emulator crashes due to the app not being able to find the following module:

`JS ERROR Error: Could not find module 'ui/text-base/text-base-styler'`

**Comment by gheron** [comment]
I was unable to find the cause of the problem, but I was able to resolve it by creating a new project and transferring all the data from the broken project. Then it runs fine.
