### ISSUE TITLE
Issue when Android SDK emulator prints an error

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#1515]
Consider this scenario: the user runs `tns run android` using Android SDK emulator. But, the emulator finds and error and prints it on the screen:

```
C:\ng-sample>emulator.exe @api29

C:\ng-sample>emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Intel HAXM is properly installed and usable.
CPU acceleration status: HAX kernel module is not installed!

C:\ng-sample>
```

In this case, emulator exe waits for the user press to press ENTER (although it does not indicate it in no way).

Because tns hides the console input/output of emulator.exe, the user is unaware of the issue. Finally, tns exists with an error message which suggest for the user to re-run the command specifying bigger --timeout value, which won't fix the underlying issue.

**Comment by rosen-vladimirov** [comment]
Just to add, that we are spawning the emulator.exe, but for some reason it raises close event before even starting, so we cannot detect if it's really started or crashed or whatever.

**Comment by dtopuzov** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/1515
