### ISSUE TITLE
Allow for apps to disable page reload livesyncs

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1517]
### Why

Page reload syncs are completely unsupported in Angular apps, and realoading a page completely breaks the app.

### What

We need a way to disable page reload syncs for Angular apps, and always restart the app.

### How

Certainly not like [this](https://github.com/NativeScript/sample-Groceries/commit/4404716490b74b7d703158dc287654c21d1519fe). Funny hacks aside, here's what comes to mind:

* We can check `package.json` for an `angular2` dependency.
* We can introduce a CLI option like `--no-page-reloads`
* We can expose additional hooks in some module that the `nativescript-angular` code overrides and disables page reloads.

**Comment by rosen-vladimirov** [comment]
I would suggest an option in package.json (of course under nativescript key), so you can just define that you always want restart for the current project.

**Comment by atanasovg** [comment]
Ping @rosen-vladimirov @ligaz This is critical for our Angular integration.

**Comment by rosen-vladimirov** [comment]
@atanasovg , @hdeshev 
Do you like the idea for having separate key in project's package.json, for example:
```JSON
"nativescript": { 
    "reloadOnSync": false
    "tns-android": "1.7.0"
}
```
We can add it by default in our Angular template and I'll make sure CLI will copy it to project's package.json when this template is used.
This way user's will not have to pass additional option to `tns livesync` command.
What do you think?

**Comment by hdeshev** [comment]
I like it. Do we need to copy it in the CLI if it's present in the template already?

**Comment by rosen-vladimirov** [comment]
@hdeshev yes, I've not been very creative with the name :smile_cat: 
Maybe we can name it `disableFastSync` or `refreshOnSync`?

As per the copying from template to project's package.json - yes, CLI works with the project, not with the template's package.json. The only case where we check the template's package.json is on `tns create` - CLI reads it and copies information from it to the project.

**Comment by ligaz** [comment]
Isn't this responsibility of the `nativescript-angular` package? Imagine that in a bright future we enable fast LiveSync for Angular apps. This will require every project's `package.json` to be updated in order to take advantage of it, instead of just updating the `nativescript-angular` dependency.

I'm imagining we provide the right hook (similar to the way we want transpilers to define which files to ignore for sync) so that the `nativescript-angular` disables the fast LiveSync.

**Comment by hdeshev** [comment]
:+1: I like the idea of calling a callback which we can override in a plugin. That would probably require a change to tns-core-modules (which is probably OK).

**Comment by TsvetanMilanov** [comment]
Livesync hook and a way to force full livesync are added. [This](https://github.com/TsvetanMilanov/nativescript-restart-on-sync-plugin) plugin shows how to do it. With this hook when changing any type of file full sync will be executed.

**Comment by enchev** [comment]
Already done.
