### ISSUE TITLE
EACCES, unlink *

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/nativescript-cli#1518]
I am trying to build for android on mac and I receive the following error:

`EACCES, unlink
'/Users/johnt/Dropbox/NativeScript/workplan2/platforms/android/src/main/assets/app/Images/logo.jpg'`

Any idea on what may cause this? My `ANDROID_HOME` variable is set correctly.

**Comment by mikeres0** [comment]
Okay, so using `sudo tns build android` worked, however it's now telling me that my `ANDROID_HOME` is incorrectly set. I've navigated to the SDK path through Finder and it's there. I've ran `android` from the command line which works correctly. I am at a bit of a loss.....

**Comment by Emadello** [comment]
Solution is simple: remove the "sudo"

Just: tns build android

I ran into this and this is how it worked :)

**Comment by mikeres0** [comment]
The only reason I used `sudo` was to get it to work in the first place....

**Comment by Emadello** [comment]
I know, i have been there and used sudo to get things work, but in this exact stage you don't need sudo, just try it and post how it goes

**Comment by mikeres0** [comment]
I have got no idea why, but it's suddenly decided to work... Seems like you know a thing or two about black magic ;) Cheers!

**Comment by Emadello** [comment]
Its just android_home is not set at root level, it's set to user.

So whenever u try using sudo with tns build android or anything related to android, u'll get this error.

Glad I helped :)
