### ISSUE TITLE
Trial message doesn't remove when you install dev plugin

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#1519]
1. clone NativeScript UI examples: https://github.com/telerik/nativescript-ui-samples and add trial plugin. 
2. Then add Dev plugin and you will see that the trial message exists. 
3. You should remove lib and platform folders and message will hide

**Comment by Daxito** [comment]
Question, how did you get the Dev Plugin?

**Comment by enchev** [comment]
Irrelevant old issue closed
