### ISSUE TITLE
Cannot specify emulator device while debugging

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/nativescript-cli#1522]
As of 1.6.1, it appears there is a CLI bug that causes problems if you try to specific a device while debugging on an emulator.

**Command:**
`$ tns debug ios --emulator --device "iPad Air 2"`

**Result:**
Error Message in CLI:
`Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.`

**Expected:**
App to load in iOS Simulator running as iPad Air 2 with debugger attached

This is a CLI command that worked as expected before 1.6.

**Comment by Daxito** [comment]
+1
Not working here either

**Comment by rosen-vladimirov** [comment]
Thanks for reporting this. As a workaround you can use:
```
$ tns emulate ios --device "iPad Air 2" --justlaunch
$ tns debug ios
```

**Comment by nguyenbn** [comment]
I am also have the same issue on 1.6.2.  I tried doing the workaround, but had no luck.

tns emulate ios --device "iPhone 6" --justlaunch
tns debug ios

The simulator opens after the first command, but the second command doesn't launch the debugger window.

**Comment by dtopuzov** [comment]
Still valid in {N} 2.0.1
