### ISSUE TITLE
Unable to create application

### ISSUE THREAD

**Issue by sharnupatil3535** [NativeScript/nativescript-cli#1523]
error image

![image](https://cloud.githubusercontent.com/assets/15356426/13212297/0fe74dee-d966-11e5-8ee7-94a3589e341e.png)

please give feedback

thank you

**Comment by rosen-vladimirov** [comment]
Hi @sharnupatil3535 ,
Is this an old application or a new one? It seems similar to this issue - https://github.com/NativeScript/NativeScript/issues/1577 but it shouldn't be reproducible with newly created application. Can you give more details on the command you are executing, is this just a sample project, etc.
