### ISSUE TITLE
tns livesync doesn't stop if TypeScript compilation fails

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1524]
Running `tns livesync android` (no --watch!) doesn't stop the process if TypeScript compilation fails, and transfers app files to the device, which is followed by a crash.

What makes the situation even worse is that the console gets spammed with too much output, and you can't easily figure out that you got a compile error in your code.

**Comment by enchev** [comment]
Tested with latest (2.0.1) and worked as expected.
![untitled](https://cloud.githubusercontent.com/assets/5804953/16010388/a503c94a-3189-11e6-9f58-9fa4c4762432.png)
