### ISSUE TITLE
Recursive/Dependent Packages

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1528]
If I have a plugin called say "sqlite" and I want to depend on another plugin say "node-process"; is their an easy way to do this.  My understanding is that TNS doesn't not yet support plugins with a another plugin dependency.   

If it does support it, can you point to some docs on how to do it.   
If not, can we get a feature request for this.

**Comment by rosen-vladimirov** [comment]
Hi @NathanaelA ,
This is supported in the way npm support dependencies. In your `sqlite` plugin dir, just execute:
```
npm install --save `node-process`
```
In case your `node-process` is a nativescript plugin as well (I mean it has platforms dir and nativescript key in package.json), when CLI process node_modules of your application, it will detect this and process it in the same way as other nativescript plugins.

Is this what you are looking for or I've misunderstood your question?

**Comment by NathanaelA** [comment]
@rosen-vladimirov, I'm actually looking for a way to simplifies this for end users. 

 If my plugin requires another one of my plugins; it would be nice if they could just install one plugin and have the second come along for the ride just like NPM does already.    Is their a way to do this yet, if not; this is something that does need to get fixed to allow more modular plugin support.

**Comment by rosen-vladimirov** [comment]
`tns plugin add sqlite` will install both plugins
In fact CLI spawns `npm install` so all of your plugins dependencies will be installed and processed to the native application. CLI flattens them, so in case you check the `tns_modules` dir inside platforms, you'll notice that the `node-process` is there - at the root level, even if it is dependency of your `sqlite` plugin.
So yes - your users will receive both plugins in case they just add the `sqlite`.

**Comment by NathanaelA** [comment]
Sweet, I was under the impression that sub-modules wouldn't be flattened or supported  But if that not the case; that is awesome..   I'm off to try it out...

**Comment by rosen-vladimirov** [comment]
@NathanaelA , can we close this issue ?
