### ISSUE TITLE
Warn when replacing invalid AndroidManifest.xml with the default one

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1529]
My `app/App_Recources/AndroidManifest.xml` get replaced by the default one from the *hello-world* template because it is not valid. I would prefer to be warned that the file is not valid in order to be able to fix it.

**Comment by MHunterNZ** [comment]
This issue also happens with the iOS plist.

**Comment by rosen-vladimirov** [comment]
@MHunterNZ , before 1.6.0 NS CLI did not support `Info.plist` in `app/App_Resources/iOS`, that's why when we place a new file there, we do not show warning.

**Comment by stefalda** [comment]
I've spent half an hour trying to understand why my AndroidManifest.xml got replaced, until I've found this thread and understood the problem...

**Comment by enchev** [comment]
Already done
