### ISSUE TITLE
Livesync Not Copying SourceMaps

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1531]
_From @burkeholland on February 23, 2016 13:47_

It looks to me like in 1.6, `livesync` is not copying source maps over.

````
Unable to sync files. Error is: ENOENT: no such file or directory, stat '/Users/burkeholland/dev/burkeholland/nativescript-devdays/platforms/ios/nativescriptdevdays/app/models/Speaker.js.map'
````

Even though that file exists in my project, but it does not exist at the location specified in the error.

Note that this is resolved by adding `inlineSourceMaps: true` to the `tsconfig` file.

_Copied from original issue: NativeScript/NativeScript#1617_

**Comment by rosen-vladimirov** [comment]
Hi @burkeholland , 

The issue is already resolved. Just update your CLI to 1.6.1. Also please update your nativescript-dev-typescript version to 0.3.0

https://github.com/NativeScript/nativescript-cli/issues/1499
