### ISSUE TITLE
build.gradle errors with twitter sdk gradle settings

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-cli#1535]
I was starting to work on a Twitter SDK plugin for the framework when I ran into a bunch of issues with the **build.gradle** file. On the  [Twitter Kit Repo](https://github.com/twitter/twitter-kit-android) in the **Download** section, the README suggests the following gradle file settings...

      buildscript {
         repositories {
             mavenCentral()
             maven { url 'https://maven.fabric.io/public' }
      }
         dependencies {
           classpath 'io.fabric.tools:gradle:1.+'
        }
    }

    apply plugin: 'io.fabric'

     repositories {
         mavenCentral()
         maven { url 'https://maven.fabric.io/public' }
     }

     dependencies {
         compile('com.twitter.sdk.android:twitter:1.12.1@aar') {
         transitive = true
        }
    }

 If I don't add the `apply plugin: 'io.fabric'` line then the app will build but I can't access the twitter sdks. Runtime errors occur when calling the methods within the SDK. I have no idea what would need to be included or modified to the build.gradle file to allow something like the twitter sdk to be pulled and packaged in android apps. I made the correct changes to the current `build.gradle` file that ships with 1.6.1 and no luck getting it to work.

**Comment by Plamen5kov** [comment]
Hi @bradmartin,
Can you post exactly what is the runtime error you are refering to?

**Comment by enchev** [comment]
Hey @bradmartin,

Do you still have issues with this?

**Comment by bradmartin** [comment]
I never got back around to it. I'll close it and if I get back to it I'll reopen. Thanks.
