### ISSUE TITLE
tns run android not working fine

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1536]
_From @SivaJonnala on February 24, 2016 6:56_

I am practicing the nativescript sample examples. While I doing I successfully run with the sample groceries app. And then I have restarted my computer. executing the file is not working. even tns build android also not working. 
I am using windows 7 Operating System.
I think problem is at setting the environmental variable is not set correctly. But it is having the environmental variable also.
I have attached my screen shots
![image](https://cloud.githubusercontent.com/assets/10843991/13277811/a1ef9476-daf1-11e5-88f2-9f08645c33dc.png)
![image](https://cloud.githubusercontent.com/assets/10843991/13277842/d4ae3ef8-daf1-11e5-8422-b41fe8bb5608.png)

please let me know the solution for this issue.

_Copied from original issue: NativeScript/NativeScript#1623_

**Comment by Plamen5kov** [comment]
Hi, @SivaJonnala
I think this can help: http://stackoverflow.com/questions/26217055/adb-server-didnt-ack
In short open task manager and kill adb.exe
If that doesn't work try to run commands:
```bash
adb kill-server
adb devices
```

**Comment by SivaJonnala** [comment]
@Plamen5kov Thank you for your response. yeah yesterday itself I saw that Url which you have mentioned. No problem, I will look into that more deeply hopefully will get a good output.

**Comment by rosen-vladimirov** [comment]
@SivaJonnala as we have not heard back from you for a while, I'm closing this thread. Feel free to reopen it in case you still have any problems or concerns.
