### ISSUE TITLE
NativeScript 1.6 Problem 2, please take a look :)

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1538]
_From @wisonye on February 25, 2016 3:8_

In 1.5, for "get round" the splash screen( black screen, App Name, App Icon ) and network issue( e.g. "NSAppTransportSecurity" ) in IOS app, I can modify the "plist" file in XCode project:

```javascript
// "XXXX" is the project name
./platforms/ios/XXXX/XXXX-Info.plist
```

But 1.6, "run" and "livesync" will rebuild the plist file EVERY TIME, my modify gone, .....how to stop it re-write the file or where I can put the content I want to save in plist file ?????

_Copied from original issue: NativeScript/NativeScript#1642_

**Comment by rosen-vladimirov** [comment]
Hi @wisonye,
With version 1.6.0 we have introduced Info.plist in `app/App_Resources/iOS` - you should edit it instead of the one in platforms dir. Can you try it and see if it works for you?

**Comment by wisonye** [comment]
@rosen-vladimirov Yep, I got it, and it works, THANKS !!!!! :)
