### ISSUE TITLE
CLI can easily fail and blow project up on windows when you have multiple plugins.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1546]
Windows only supports 255 character length paths...      This is VERY IMPORTANT to this issue!

For some reason the CLI is creating a really long path for merging stuff using the names of each installed plugin.      So for example when using 8 plugins if each of them are an average of 22 characters (nativescript = 12 by itself, almost every plugin is prefixed with those 12 characters).  = 176 characters.

So If I have D:\projects\nativescript\projname = 35
Then you add in \platforms\android\build\intermediates\res\merged = 59
(176 in Plugin name characters) = 172
Then you add the image part of the path \debug\drawable-xxhdpi\someimage.png = 49

= 315 Characters.   Guess what happens.   No Worky :grinning: and now your platform folder is totally screwed up. 

THIS IS A BAD ISSUE!   It leaves the project effectively dead.  
 Plugins I was using:
		"nativescript-barcodescanner": "^1.2.0",
		"nativescript-cardview": "^0.1.1",
		"nativescript-dom": "^1.0.0",
		"nativescript-drop-down": "^1.2.1",
		"nativescript-grid-view": "^1.3.0",
		"nativescript-liveedit": "file:..\\repos\\nativescript-liveedit",
		"nativescript-sqlite": "file:..\\repos\\nativescript-sqlite",
		"nativescript-telerik-ui": "file:..\\nativescript-ui-debug-dev.tgz",
		"tns-core-modules": "^1.6.2"

Then I attempted to add: nativescript-floatingactionbutton

This is a BLOCKING issue for most people when they hit this.   I have some ways I think I can work around this.

**Comment by NathanaelA** [comment]
Ok; for anyone who runs into this -- this is a gradle issue, not a TNS specific issue.  
However, the issue is still the same.  Gradle / aapt apparently has a couple bugs already in for this:
https://code.google.com/p/android/issues/detail?id=187430
https://code.google.com/p/android/issues/detail?id=160994

Who knows when they will be fixed; but their is a way to mitigate the primary issue I ran into.  The include.gradle files internal names can be shortened.  

Inside the include.gradle files are a section that (example nativescript-cardview) looks like this
```
android {
    productFlavors {
        "nativescriptcardview" {
            dimension "nativescriptcardview"
        }
    }
}
```

Edit and make it look like this:
```
android {
    productFlavors {
        "nscv" {
            dimension "nscv"
        }
    }
}
```
Now the plugin only uses 4 characters rather than 20 characters.  By doing this to all the existing include.gradle files the size was reduced to considerably under the 255 length.

A couple notes, this could be done via the CLI automatically; We would make the CLI when it copies over the include.gradle files automatically shorten the name...   When it generates a new default include.gradle it uses a shortened name.

**Comment by Daxito** [comment]
Is there a way to know when we run into this issue? Any error message or something?

**Comment by NathanaelA** [comment]
In my case it threw lots of error messages about aapt not being able to process some of the png files.  At the end it just says gradlew failed.

Here is one of the many errors:

```
AAPT out(1144172198) : No Delegate set : lost message:  Output file: D:\projects\nativescript\test1\platforms\android\build\intermediates\res\merged\nativescript-barcodescannernativescriptcardviewnativescriptfloatingactionbuttonnativescriptfloatingactionbuttonnativescript-liveeditnativescript-telerik-ui\debug\drawable\flip_camera.png
APT out(1144172198) : No Delegate set : lost message:Error
APT out(1144172198) : No Delegate set : lost message:Done
```

And then finally tns reports:
```
Command D:\projects\nativescript\test1\platforms\android\gradlew.bat failed with exit code 1
```

**Comment by teobugslayer** [comment]
This issue was moved to NativeScript/android-runtime#369
