### ISSUE TITLE
Unhandled exception when trying to run app in emulator

### ISSUE THREAD

**Issue by jalal** [NativeScript/nativescript-cli#1549]
I've been developing an app and all has been working fine until this morning when I get this in the terminal:

`Project successfully built
Successfully deployed on device with identifier '192.168.59.101:5555'.
E/VdcInflateDelegate( 2391):    at com.tns.Platform.callJSMethodNative(Native Method)
E/VdcInflateDelegate( 2391):    at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
E/VdcInflateDelegate( 2391):    at com.tns.Platform.callJSMethod(Platform.java:711)
E/VdcInflateDelegate( 2391):    at com.tns.Platform.callJSMethod(Platform.java:690)
E/VdcInflateDelegate( 2391):    at com.tns.Platform.callJSMethod(Platform.java:680)
`
and in the emulator (Genymotion) is an Unhandled Exception.

From `adb logcat`:

`E/VdcInflateDelegate( 2391): Exception while inflating <vector>
E/VdcInflateDelegate( 2391): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> ta
g requires viewportWidth > 0
E/VdcInflateDelegate( 2391):    at android.support.graphics.drawable.VectorDrawableCompat.updateStateFr
omTypedArray(VectorDrawableCompat.java:535)
etc etc etc
`

The only thing that has changed is a small update in the Android SDK (`Local Mavern Repo` and `Android Support Library`) which I can't manage to roll back AFAICT.

**Comment by hamorphis** [comment]
https://github.com/NativeScript/nativescript-marketplace-demo/issues/108

**Comment by hamorphis** [comment]
http://android-developers.blogspot.bg/2016/02/android-support-library-232.html

1. Create a file `/app/App_Resources/Android/app.gradle` and paste this:
```
android {  
    defaultConfig {  
        generatedDensities = []
    }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }
}
```

2. Open `/platforms/android/build.gradle` and update the version of `com.android.tools.build:gradle:1.x.x` to `1.5.0` if needed.

**Comment by jalal** [comment]
You, sir, are a saviour!

I had already tried the first part of that, but the second step is key to getting it working. Thanks.

**Comment by aditya-kanekar** [comment]
I couldn't get it working on my Redmi 2 after making all the suggested changes.
