### ISSUE TITLE
can not run demo in android

### ISSUE THREAD

**Issue by xuezier** [NativeScript/nativescript-cli#1557]
version 1.6.1  on windows10
tns run android
Successfully deployed on device with identifier 'ddcb5e0d'.
W/dalvikvm( 6286):              in Lcom/tns/Platform;.callJSMethodNative:(ILjava/lang/String;IZ[Ljava/lang/Object;)Ljava/lang/Object; (CallVoidMethodA)
I/dalvikvm( 6286):   at com.tns.Platform.callJSMethodNative(Native Method)
I/dalvikvm( 6286):   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
I/dalvikvm( 6286):   at com.tns.Platform.callJSMethod(Platform.java:711)
I/dalvikvm( 6286):   at com.tns.Platform.callJSMethod(Platform.java:690)
I/dalvikvm( 6286):   at com.tns.Platform.callJSMethod(Platform.java:680)

@vchimev

**Comment by vchimev** [comment]
Hi @xuezier.

This issue is caused by the latest version (23.2) of Android Support Library called Local Maven repository for Support Libraries. You could find a workaround [here] (https://github.com/NativeScript/nativescript-cli/issues/1549#issuecomment-189268709).
