### ISSUE TITLE
"tns platform add android" throwing error

### ISSUE THREAD

**Issue by DeepakDonde** [NativeScript/nativescript-cli#1564]
I am getting so
[log.txt](https://github.com/NativeScript/nativescript-cli/files/156274/log.txt)
me issue while running "tns platform add android" command.
Every time when I run above command on cmd, I get following error -
"Unable to find "android.bat" executable file. Make sure you have set ANDROID_HOME environment variable correctly.(this is in red color on cmd).
Sending exception report (press Ctrl+C to stop)....... "
Can you please help me resolving this ?
I have attached log trace for your reference. 
Please help.

**Comment by rosen-vladimirov** [comment]
Hi @DeepakDonde ,
It looks like something's wrong with your Android SDK installation. May I ask you to uninstall the SDK and install it again as it looks like your `tools` directory is missing some of the required executables. Also make sure you've set your JAVA_HOME correctly as pointed in [our help](https://github.com/NativeScript/nativescript-cli#system-requirements)

**Comment by DeepakDonde** [comment]
Hello @rosen-vladimirov ,
Thanks for the reply.

I have already tried installing new SDK and run it again but still its not working.

Please can you check following are my system configurations.
Android SDK : API 22 (Android 5.1.1)
Android SDK Build-tools : 23.0.2
Android Support Library : 23.2
JDK : jdk1.7.0_71 (JDK 7) 
node.js : version 4.3.1

Following are my Environmental Variables -
JAVA_HOME : C:\Program Files\Java\jdk1.7.0_71
ANDROID_HOME : E:\ANDROID\sdk
path : %PATH%;C:\Program Files\Java\jdk1.7.0_71\bin;C:\Program Files\Java\jdk1.6.0_45\bin;C:\Program Files\nodejs\;E:\ANDROID\sdk\tools;E:\ANDROID\sdk\platform-tools; 

Also, when I run android.bat file on cmd, the sdk manager open as it should be. So I am wondering why it is not able to fine that "android.bat" file .. :|
Do I need to install JDK 8 ? is it compulsory? I read it somewhere JDK 7 will also do.
Am I missing something ? Please help. Its bit Urgent.

Thanks..

**Comment by rosen-vladimirov** [comment]
Hi @DeepakDonde 
It's recommended to install JDK 1.8.x.
Calling `android` directly from your terminal is working because you have added the `tools` directory to your PATH environment variable. Try calling `%ANDROID_HOME%\tools\android` from your terminal and see if it works - that's what CLI is trying to do.
I've checked for similar errors and it seems there were some issues in the `android.bat` file with JDK 1.7 (more info [here](http://stackoverflow.com/questions/11023179/android-sdk-and-avd-manager-will-not-run)), so please update your Java and try again.
The other configurations seems correct :)

**Comment by DeepakDonde** [comment]
Hi @rosen-vladimirov 
I have installed JDK 1.8.0_74 as per your recommendation. Also I have updated JAVA_HOME and path accordingly.
Still the error persists..  :|
I am stuck since 5 days on same error.

I also tried calling %ANDROID_HOME%\tools\android from my terminal as per your suggestion, It works perfectly fine !!

As per the documentation, I have run "tns doctor" on cmd, I am getting following :
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or
 later.
No issues were detected.

Any other command that I can run and know where am I making mistake ?

**Comment by DeepakDonde** [comment]
Hello @rosen-vladimirov ,
After so much hassle, it turn out to be a very basic and surprising error. 
My working directory was containing the symbol "&", which was according to log file generated,was not acceptable .. :/
Log says : \r\nError: The working directory does not seem to be valid: \'E:\\Android R\n',exitCode: 0 }

Now I have changed my directory name and it does not give that damn error anymore and platform android gets created properly. :)

Thanks for all your time and help ..!! 
I really appreciate .. !!

**Comment by rosen-vladimirov** [comment]
@DeepakDonde , thanks for sharing the problem and the fix you've found. Really weird behavior of android.bat file.
Anyway, I'm glad you resolved it.

**Comment by DocGreenRob** [comment]
I am having the same issue.  Here is a screenshot of my environment variables. (see below)

![env_vars](https://cloud.githubusercontent.com/assets/7489324/16401330/0e81150e-3ca1-11e6-935f-594b81d40b22.PNG)

The error message is:

Unable to find "android.bat" executable file. Make sure you have set ANDROID_HOME environment variable correctly.
WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the native emulator.
To be able to build for Android and run apps in the native emulator, verify that you have
installed the latest Android SDK and its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the chocolatey package manager to install the Android SDK and its dependencies.

NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.
