### ISSUE TITLE
On Windows Error executing command 'javac'. Make sure you have installed The Java Developme nt Kit (JDK) and set JAVA_HOME environment variable.

### ISSUE THREAD

**Issue by mabelanski** [NativeScript/nativescript-cli#1570]
Hi,

I installed all requirements nodejs, jdk, android and JAVA_HOME and ANDROID_HOME variables, i follow this tuto https://github.com/NativeScript/nativescript-cli#system-requirements

but when i launch tns run android --emulator or tns doctor, i have this error 

Error executing command 'javac'. Make sure you have installed The Java Developme nt Kit (JDK) and set JAVA_HOME environment variable.

I'm on window 8.1

JAVA_HOME is set on 
C:\Program Files (x86)\Java\jre1.8.0_66\bin

Please help me 
Thanks

**Comment by rosen-vladimirov** [comment]
@mabelanski 
You have set your JAVA_HOME to point to your JRE bin folder. NativeScript CLI requires JDK, not JRE. Also when setting JAVA_HOME, it should point to the root of the JAVA installation, not to the `bin` directory. For example: `JAVA_HOME=C:\Program Files\Java\jdk1.8.0_66`
You can download latest JDK from [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Comment by urko-b** [comment]
> @mabelanski
> You have set your JAVA_HOME to point to your JRE bin folder. NativeScript CLI requires JDK, not JRE. Also when setting JAVA_HOME, it should point to the root of the JAVA installation, not to the `bin` directory. For example: `JAVA_HOME=C:\Program Files\Java\jdk1.8.0_66`
> You can download latest JDK from [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

This solve my problem. Thanks so much
