### ISSUE TITLE
Livesync ios is not working when dependency has executable

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#1571]
`tns livesync ios` fails when one of the dependency has executables created in `node_modules/.bin` directory.

Some of npm packages may have executables, that are created in `node_modules/.bin` directory after calling `npm install`. These executables are used for calling the module directly, not via require. For example such module is `mkdirp`. You can use it in code, but you can also call it directly from `node_modules/.bin/mkdirp`.
When we have such module as dependency, CLI is unable to process the resources when `tns livesync ios` or `tns test ios` is called. The calls pass only the first time, every consecutive call is failing. 
CLI should not try copying any `.bin` directory to platforms dir - it has no valid point to have these executables on device.

Steps to reproduce
1) `tns create myApp`
2) `cd myApp`
3) `tns plugin add nativescript-unit-test-runner@0.3.0`
4) `tns livesync ios --justlaunch`
5) `tns livesync ios`
The last call will fail with EEXIST error.

**Comment by pkoleva** [comment]
Not reproduced in {N} 2.0.1
