### ISSUE TITLE
nativescript-unit-test-runner is included in release build

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#1572]
In case the application has dependency on `nativescript-unit-test-runner`, calling `tns build <platform> --release` will include the unit-test runner in the prepared package. It is not expected to have it there in release build.

Some options to resolve the issue:
* Implement special logic in CLI to exclude the `nativescript-unit-test-runner` when in release build. The problem here is that if the same issue occurs with other modules, we'll have to hard-code them in CLI as well.
* Install `nativescript-unit-test-runner` as devDependency and add logic in it to be copied to `<platforms>` directory on `after-prepare`. This way the plugin will have the logic when to be copied to the project and when not. The same approach can be used for other packages.

**Comment by dtopuzov** [comment]
Still valid in {N} 2.0.1

**Comment by enchev** [comment]
In my opinion it will be better if we implement the logic in the plugin itself (second option). I'm moving this issue to the `nativescript-unit-test-runner` repo.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-unit-test-runner#11
