### ISSUE TITLE
The test command does not execute tests

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1578]
The reason is that the hook is not executed.

Steps to reproduce:
```
tns create appTest
cd appTest
tns test init
tns test <platform>
```

package.json:
```
mcsofvchimev:appTest vchimev$ cat package.json 
{
	"nativescript": {
		"id": "org.nativescript.appTest",
		"tns-ios": {
			"version": "1.6.0"
		}
	},
	"dependencies": {
		"nativescript-unit-test-runner": "^0.3.1",
		"tns-core-modules": "1.6.2"
	},
	"devDependencies": {
		"jasmine-core": "^2.4.1",
		"karma": "^0.13.21",
		"karma-jasmine": "^0.3.7",
		"karma-nativescript-launcher": "^0.4.0"
	}
```

**Comment by BenElliottBV** [comment]
I'm having issues with running tests - is this linked?


Following the guide here - https://docs.nativescript.org/core-concepts/testing 
I get to the "Run the Tests" section and run the command "tns test android" and get this in the console:

> Successfully prepared plugin nativescript-unit-test-runner for android.
> Project successfully prepared
> 08 03 2016 09:28:01.548:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
> 08 03 2016 09:28:01.556:INFO [launcher]: Starting browser NativeScript Unit Test Runner
> Transferring project files...
> Successfully transferred all project files.
> Applying changes...
> Successfully synced application org.nativescript.nativescriptUnitTest on device BH90VVBD1L.


And then nothing happens

**Comment by vchimev** [comment]
Issue fixed in nativescript-unit-test-runner version 0.3.3. Related: https://github.com/NativeScript/nativescript-cli/issues/1581
