### ISSUE TITLE
Add clean commands to tns

### ISSUE THREAD

**Issue by donaldking** [NativeScript/nativescript-cli#1580]
At the moment, there is no command to simply clean a platform. The way to accomplish this currently it to remove the platform folder and add it again. I think there should be a clean command that could simply automate the removing and adding of the specified platform folder. 

e.g: ```tns platform clean android```

or ```tns platform clean ios```

Cheers

**Comment by sitefinitysteve** [comment]
:+1: Oh yeah great idea...  tns platform remove ios, tns platform add ios gets old fast

**Comment by BenElliottBV** [comment]
+1 from me, this would be really useful!

**Comment by jvzanatta** [comment]
for now i'm using (on linux) `alias tnsclean="tns platform remove android && tns platform add android"` (since i'm doing android only for now)
