### ISSUE TITLE
Test runner doesn't work

### ISSUE THREAD

**Issue by BenElliottBV** [NativeScript/nativescript-cli#1581]
I've set up new projects on both PC and Mac and have run the command "tns test" through Genymotion (on both) and a physical Android device on the PC, and the iOS simulator on the Mac and the test runner never seems to kick in,

vladimirov has been trying to help with this on the Slack channel but so far to no avail. He suggested I raise this as an issue.

I've attached the output of an attempt to run it on the android device. 
[log.txt](https://github.com/NativeScript/nativescript-cli/files/163477/log.txt)

**Comment by rosen-vladimirov** [comment]
Can you please check that in your `<project_dir>/node_modules/nativescript-unit-test-runner` the version in package.json is 0.3.2 and also there's a `postinstall.js` in `<project_dir>/node_modules/nativescript-unit-test-runner`

**Comment by rosen-vladimirov** [comment]
@BenElliottBV 
Also have you configured your environment to disable package scripts, what's the output of 
```
$ npm config get ignore-scripts
```

**Comment by BenElliottBV** [comment]
npm config get ignore-scripts comes back false
It's definitely 0.3.2 and ther eis a `postinstall.js`

**Comment by rosen-vladimirov** [comment]
@BenElliottBV 
We've just released new version of `nativescript-unit-test-runner` - 0.3.3 Please update your projects and see if it works on your side :)

**Comment by rosen-vladimirov** [comment]
Just for information - somehow the package in npm was missing it's scripts. The `nativescript-unit-test-runner` package has postinstall script, which is mandatory in order to make it work :)

**Comment by BenElliottBV** [comment]
Thanks! Just trying it now

**Comment by BenElliottBV** [comment]
As confirmed via Slack - Looks good on PC via Genymotion and android device and on Mac via iOS simulator and Genymotion!

**Comment by rosen-vladimirov** [comment]
@BenElliottBV  thanks very much for testing this!

**Comment by BenElliottBV** [comment]
@rosen-vladimirov No problem, let me know if I can help with anything else
