### ISSUE TITLE
Add text-transform property to Android

### ISSUE THREAD

**Issue by donaldking** [NativeScript/nativescript-cli#1582]
Currently, on Android version 6.0+ button titles are all CAPS by default. setting css property:

``` .buttonClass { text-transform: none; }``` does nothing. 
You'd need to override this in code:
``` page.getViewById("buttonId").android.setTransformationMethod(null); ```

It would be more helpful if we could use css text-transform property for this.

Cheers

**Comment by bradmartin** [comment]
This should be moved to the NativeScript repo.

Also, a temporary workaround is to set `textWrap` on the `<button>` and this will case your text as defined in the `text` property.

**Comment by bradmartin** [comment]
@TelerikAdminTeam - can someone move this to the main repo? So it doesn't get lost.

**Comment by rosen-vladimirov** [comment]
This issue was moved to NativeScript/NativeScript#1734
