### ISSUE TITLE
Analytics for SDK and tools versions

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#1583]
Add Analytics tracking the version of Android SDK and Xcode used. This will give us insight how to develop the CLI. A good place to report these metrics is `platform add`

**Comment by valentinstoychev** [comment]
can I request one more tracking - I want to know how many people have development environment ready to use ({N} dependenciess installed) when they install the CLI. This can be done at the moment we execute tns doctor (AFAIK on first run of CLI). Optionally I want to know what part of the customers have successfully installed the dependencies (if they were not OK after the first run of tns doctor).

**Comment by rosen-vladimirov** [comment]
@valentinstoychev  your requirement is already in production :)

**Comment by rosen-vladimirov** [comment]
@enchev why is this issue closed? The initial feature that @teobugslayer had logged is not implemented. Have you decided to drop this feature request?

**Comment by enchev** [comment]
My mistake, issue reopened.

**Comment by dtopuzov** [comment]
@teobugslayer @valentinstoychev Do you still think we need to track Xcode and Android Build Tools versions?

**Comment by dtopuzov** [comment]
{N} team do not need to know version of Xcode or Android build tools.
