### ISSUE TITLE
Provide a shorthand for starting Angular 2 apps

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1595]
Related to https://github.com/NativeScript/nativescript-cli/issues/1498.

As we talk about Angular 2 more I think it’s important that we optimize the getting started experience as much as possible. With that in mind I’d like to propose that we create a `--ng` flag for `tns create` that acts as a shorthand for `tns create my-app-name --template https://github.com/NativeScript/template-hello-world-ng`.

So `tns create my-next-great-angular-project --ng`. Thoughts?

**Comment by rosen-vladimirov** [comment]
@tjvantoll Is it expected to have `tns-core-modules` from angular tag?
Also we may add a shortcut for the template, as we've created for typescript:
```
tns create my-next-great-angular-project --template ng
tns create my-next-great-angular-project --template angular
```
Both will use the angular template.

In case we provide --ng option, I believe the new app should install modules from angular tag, but maybe I'm not correct.

**Comment by ligaz** [comment]
@hdeshev Do we plan to maintain the `@angular` in the long term?

**Comment by hdeshev** [comment]
We need `@angular` for out of band releases, so that we can release the angular renderer with unofficial `tns-core-modules` features/fixes. I expect that need to diminish greatly over the next couple of months, and I hope it is temporary.

I don't expect it to disappear completely, but we'll probably use it very rarely. I think it's perfectly fine to pick a version of `nativescript-angular` that works with the official `tns-core-modules` release and use that when starting a project with the `--ng` option. (Actually picking the right version is a thing we need to agree upon too :wink:)

**Comment by tjvantoll** [comment]
@rosen-vladimirov I would expect `tns create my-next-great-project --ng` to simply clone https://github.com/NativeScript/template-hello-world-ng. If that template needs a special version of tns-core-modules its `package.json` can just take care of that for me.

I like the idea of having `tns create my-next-great-angular-project --template ng`, but personally I’m in favor of (additionally?) having `tns create my-next-great-angular-project --ng` as a even shorter shorthand :smile:

**Comment by rosen-vladimirov** [comment]
@tjvantoll I agree we can have both options ;)

**Comment by NathanWalker** [comment]
love this. :+1:

**Comment by vchimev** [comment]
With the shorthand implementation of:
```
tns create my-next-great-angular-project --template angular
```
and 
```
tns create my-next-great-angular-project --ng
```
I think it makes sense to support also
```
tns create my-next-great-typescript-project --tsc
```
for
```
tns create my-next-great-typescript-project --template typescript
```
This will keep the NativeScript commands consistent as well.

What do you think?

**Comment by vchimev** [comment]
My suggestion moved to a separate issue: https://github.com/NativeScript/nativescript-cli/issues/1650.
