### ISSUE TITLE
Provide a cleaner platform-upgrade-failure message

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#160]
When trying to upgrade I get:
```
me@myMachine:~/projects/MyApp% tns platform update ios --frameworkPath=../tns-ios-0.4.1-2014.11.27.1.tgz
Current and new version are the same.
Usage:
    $ tns platform update <Platform>
    $ nativescript platform update <Platform>

Update the version of NativeScript runtime used for a specific platform.
```
The version of the package I specified in the frameworkPath (0.4.1) is bigger than the one the project currently has (0.4.0), but I still get the error message. It would really help if I can specify a verbose mode, where I will get informed where does the package version get checked.

**Comment by enchev** [comment]
To old and irrelevant.
