### ISSUE TITLE
Sample app waiting seemingly forever for emulator device initialization on ubuntu

### ISSUE THREAD

**Issue by formula1** [NativeScript/nativescript-cli#1600]
The output isn't very descriptive
```
Starting Android emulator with image and23
Waiting for emulator device initialization...
Waiting for emulator device initialization...
```

What happens on the screen when the second 'waiting' happens is it opens some sort of menu quickly then exits (I don't have an android so I have no idea what is going on tbh). From there it just sits and does nothing.

Versions
- tns - 1.6.2
- node - 5.7.0
- npm - 3.6.0
- ubuntu - 14.04

Steps to reproduce
- Followed this to get it all setup - http://docs.nativescript.org/start/ns-setup-linux
- Followed this guide to adding an AVD - http://developer.telerik.com/featured/using-android-emulator-hybrid-mobile-apps-telerik-appbuilder/#managing-avds
  - greated a nexus 4 named and23
  - using api 23
  - targeting intel x86
  - 100 mb ram, 200 storage, using host gpu
- using android version 23 (and tried 22)
- `sudo ANDROID_HOME=/home/sam/android-sdk-linux JAVA_HOME=/usr/lib/jvm/java-8-oracle tns platform add android`
- `sudo ANDROID_HOME=/home/sam/android-sdk-linux JAVA_HOME=/usr/lib/jvm/java-8-oracle tns run android --emulator=and23`

btw, what did I do wrong that I have to sudo everything?

**Comment by rosen-vladimirov** [comment]
This issue is already fixed and the fix will be included in the next official release. Meanwhile you can start the emulator manually and call `tns run android` after that.
