### ISSUE TITLE
Demo app build error

### ISSUE THREAD

**Issue by zverbeta** [NativeScript/nativescript-cli#1603]
Run `tns build android`

My result
`Execution failed for task ':dexDebug'. > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_66\bin\java.exe'' finished with non-zero exit value 2`

**Comment by rosen-vladimirov** [comment]
@zverbeta we'll need more details, steps to reproduce, etc.
The error could be caused by thousands of reasons, so please share the steps that lead you to this error. If you can provide a sample project, please share it with us.

**Comment by zverbeta** [comment]
hmm, now it's working. But yesterday desn't. I'm sorry.

**Comment by rosen-vladimirov** [comment]
No problem, glad it works on your side ;)
