### ISSUE TITLE
nativescript install error

### ISSUE THREAD

**Issue by mahmoudHosny** [NativeScript/nativescript-cli#1604]
I can't install natvescript and I receive bad JSON file

I attached npm-log
[npm-debug.txt](https://github.com/NativeScript/nativescript-cli/files/173609/npm-debug.txt)

**Comment by rosen-vladimirov** [comment]
@mahmoudHosny can you try cleaning your cache (`npm cache clean`) and install nativescript again.
Also can you send the output of the command `npm i -g nativescript-cli` (not the detailed log - just what's printed on the console

**Comment by mahmoudHosny** [comment]
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm ERR! registry error parsing json
