### ISSUE TITLE
Build for iOS Simulator fails with XCode 7.2 when Cocoapod has Swift code

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#1606]
Build for iOS Simulator fails with XCode 7.2 when Cocoapod has Swift code. This is bug in XCode 7.2 when ARCHS are passed:
`http://www.openradar.me/23857648`

In fact CLI can pass `-destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'` instead of ARCHS and VALID_ARCHS parameters and the build succeeds.
Steps to reproduce:
1) `tns create app1`
2) `cd app1`
3) `tns plugin add nativescript-dialog`
4) `tns emulate ios`

**Comment by rosen-vladimirov** [comment]
For `name` we should pass the device that will be used, not sure if OS parameter is mandatory.

**Comment by Mitko-Kerezov** [comment]
OS parameter seems to be optional so I'll go ahead and skip passing it

**Comment by rosen-vladimirov** [comment]
Marking this as Known Issue. Please install XCode 7.3 in order to fix the issue :)
