### ISSUE TITLE
How to use .java files in {N} app

### ISSUE THREAD

**Issue by DeepakDonde** [NativeScript/nativescript-cli#1608]
Hello @hdeshev ,

Can I dump all java files as it is like my native android and just build UI using nativescript/javascript ?
Is it possible to design application UI using Angular JS and business logic using android with nativescript ?
It will be great if you would able to provide some sample app and code for same.

Thanks.

**Comment by hdeshev** [comment]
I think it is possible, but you'd have to use a plugin that builds an aar from your Java code. Then you'd be able to call that code from JavaScript running in a vanilla NativeScript or a NativeScript+Angular app. It doesn't look like the easiest job in the world, but if you really have to share Java code with other apps, this seems like the way to go.

One such plugin is our [tns-core-modules-widgets](https://github.com/NativeScript/android-widgets) package, which contains the Android layout system, and its codebase is 100% Java.
