### ISSUE TITLE
Read NPM registry from NPM package

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#161]
Right now the registry is hardcoded. We have an embedded npm package, which should allow something, analogous to `npm config get registry` to be called to retrieve the current systems' npm registry

**Comment by Fatme** [comment]
The hardcoded npm registry url was replaced with `npm view command` which internally respects `npm config registry` - https://github.com/npm/npm/blob/master/lib/view.js#L26
