### ISSUE TITLE
tns debug android - chrome caches older version of files

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/nativescript-cli#1615]
Ok, this happens a lot. Could be a Chrome thing, but I doubt it. For a while 'tns debug android' is working. Then at some point it all goes wrong (some or all of these at once):

1. I have opened a page in my app, still the associated file (think .js) are not shown in the sources.
2. Some of the files that are present are shown as empty when opened.
3. Sometimes the old version of a file is being shown, even though when I test with livesync for example I can see that my changes have been applied.
4. Custom plugin that I have created locally and that is being called for sure (console.log) is not shown in node_module sources.

I know this all sound weird and probably hard to reproduce, but it keeps happening :(

**Comment by enchev** [comment]
Hey @MiroValchev,

I believe that this was Chrome issue which is already fixed in newer versions.
