### ISSUE TITLE
Provide a way to update native project

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#162]
Right now, when updating the platform of a project (`tns platform update [platform]`), only the runtime gets updated. It would be useful to provide a way for the user to get the native project updated too (assuming customers will mainly use cross-platform code instead of xCode/Eclipse projects)

**Comment by ligaz** [comment]
This has been addressed in `1.3.0` with this commit: https://github.com/NativeScript/nativescript-cli/commit/69a5c058dbbcb7f8132554c46d8ee80cd3bc3a54
