### ISSUE TITLE
Unable to debug on iOS using the --device option

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1620]
I am unable to execute the `tns debug ios` command with `--device` option.
I get [`Timeout waiting for response from NativeScript runtime`] (https://gist.github.com/vchimev/ec3984db321b7a5ae8b1).

**Comment by sushruth** [comment]
Experiencing the same problem here without the `--device` option too.

**Comment by dtopuzov** [comment]
Still valid in {N} master and Xcode 7.3.1. iOS devices with iOS 9.3.2
tns debug ios --path TestApp
-> Successfully deployed on device with identifier 'ccd596fa85d0c0c78c9b5a95147c1ba49c9dcd67'.
-> Inspector app started
tns debug ios --device ccd596fa85d0c0c78c9b5a95147c1ba49c9dcd67 --path TestApp
-> fails with multiple error, different each time

Error 1:
````
Status: InspectingPackage PercentComplete: 20

Error: PackageInspectionFailed 
ErrorDescription: Failed to load Info.plist from bundle at path /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.eNYmMw/extracted/Payload/TestApp.app 
```

Error 2:
```
Results at '/Users/topuzov/TestApp/platforms/ios/build/device/TestApp.ipa' 
Project successfully built
Status: BrowsingApplications
Status: Complete
Status: BrowsingApplications
Status: Complete
Status: CreatingStagingDirectory PercentComplete: 5
Status: ExtractingPackage PercentComplete: 15

Error: PackageExtractionFailed 
ErrorDescription: Could not extract archive 
```

**Comment by enchev** [comment]
It seems that `tns run|debug --device [DEVICE-ID|INDEX]` will work on emulators but not on real devices. In my opinion the problem is with the app deployment not with debug service.

**Comment by mattpcaswell** [comment]
Hey this is still happening for me. I tried debugging on device from the vs code native script plugin and got the same error, `[31;1mTimeout waiting for response from NativeScript runtime.`

**Comment by spstratis** [comment]
I'm still getting this issue today. What's the actual work around for this?

**Comment by demetrio812** [comment]
Still happening for me too (2.5.1)
