### ISSUE TITLE
Livesync --watch no longer working for CSS and XML Changes on iOS

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-cli#1621]
### Overview of the issue

After the upgrade to 1.7, `livesync ios --watch` no longer syncs XML and CSS changes to iOS. TypeScript changes still cause the application to close and re-open.

### Telerik NativeScript version(s): 

1.7.0

Considered a regression. It was working in 1.6.2.

### System configuration

* OS X El Capitan
* iOS 9.2
* Xcode 7.2.1

### Steps to reproduce

````bash
tns create my-application && cd my-application
tns platform add ios
tns deploy ios --emulator
tns livesync ios --emulator --watch 
````

Change any of the CSS or XML. Changes are not synced to the application.

[log-trace.txt](https://github.com/NativeScript/nativescript-cli/files/179867/log-trace.txt)

**Comment by dtopuzov** [comment]
Just testing with:
```
tns create MyApp
cd MyApp
tns run ios --emulator
tns livesync ios --emulator --watch 
```

- OS
- X El Capitan
- iOS 9.2
- Xcode 7.2
- iOS 9.1 Simulator 

It works like a charm.

**Comment by burkeholland** [comment]
Fixed it by removing and re-installing NativeScript...

````
npm remove -g nativescript
npm install -g nativescript
````
