### ISSUE TITLE
Request: make tns run <platform> more "intelligent"?

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1624]
I would LOOOVE to stop typing --emulator :)

Could we not do like
On iOS if no physical device is attached,  **_assume_** --emulator because it'll fail otherwise?  So if a physical device is attached, tns run ios will go to the device and you can OPTIONALLY add --emulator to send it over to the simulator.

**Comment by rosen-vladimirov** [comment]
@sitefinitysteve 
CLI is already working this way. For example try calling `tns run ios` when there's no device attached - the command will automatically start iOS Simulator on your machine and run the app in it.
Can you try some commands without passing `--emulator` and tell us in case you encounter any issues :)

**Comment by sitefinitysteve** [comment]
omg I cant believe I've been --emulatoring this entire time

The only other "want" is "tns livesync ios" to --watch by default, but thats in another thread

**Comment by rosen-vladimirov** [comment]
@sitefinitysteve , We've made this change in 1.6.0, but looks like we've not promoted it very well. Also this introduced some issues with options like `--emulator`, `--device`, etc. as some of them have different context for devices and for emulators/ios simulator. We are still working to fix these issues, so in case you find anything strange, please contact us.

**Comment by sitefinitysteve** [comment]
Oh yeah, got one
tns debug ios doesn't work, needs --emulator
