### ISSUE TITLE
Full LiveSync issue with the marketplace demo app

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1637]
It seems that the full LiveSync on iOS simulator does not work for this app.

Steps to reproduce:
1. Run the marketplace demo app on iOS Simulator: https://github.com/NativeScript/nativescript-marketplace-demo
2. Make a change
3. `tns livesync ios --emulator --log trace`

Output: https://gist.github.com/vchimev/844afab372cad834b298

**Comment by rosen-vladimirov** [comment]
Hm, this sounds like duplicate of https://github.com/NativeScript/nativescript-cli/issues/1532
@vchimev  can you try changing the id of the marketplace demo in your local copy and see if it works on your side?

**Comment by vchimev** [comment]
Thanks @rosen-vladimirov, that was the case. It worked!
