### ISSUE TITLE
I am unable to update the tns

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1645]
_From @aderbas on March 25, 2016 14:32_

I do according to the documentation, my current version is 1.5.2, before update version continues 1.5.2. I'm restart the system but don't update. I'm use Linux Mint 17.2
```
$ sudo npm install nativescript -g
```
```
$ tns doctor
$ No issues were detected.
```
When installing it warns that ANDROID_HOME is not set, but if I try:
```
$ echo $ANDROID_HOME
/media/aderbal/DATA/android/Sdk/
```
During and at the end of the installation has no error message unless the notice of ANDROID_HOME. Any helpe?

_Copied from original issue: NativeScript/NativeScript#1850_

**Comment by aderbas** [comment]
How I do complete uninstall nativescript?
```
$ npm uninstall nativescript -g 
$ tns --version
1.5.2
```

**Comment by aderbas** [comment]
Ok, I completely removed the NativeScript and re-install ¬¬

**Comment by bfattori** [comment]
I tried to remove nativescript and re-install, but I'm getting:
```
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
To be able to perform Android build-related operations, set the ANDROID_HOME variable to point to the root of your Android SDK installation directory.
```
So I checked:
```
> echo $ANDROID_HOME
/usr/local/Cellar/android-sdk/24.4.1_1/
```
Seems okay to me. Then it fails for CocoaPods:
```
Verifying CocoaPods. This may take more than a minute, please be patient.
WARNING: There was a problem with CocoaPods
Verify that CocoaPods are configured properly.
```
And finally, we get to the sudo after running as sudo:
```
There seem to be issues with your configuration.
? Do you want to visit the official documentation? Yes
? Do you want to run the setup script? (Y/n) 1
? Do you want to run the setup script? (Y/n) 1Z
? Do you want to run the setup script? (Y/n) 1ZZ547
? Do you want to run the setup script? No
EACCES: permission denied, mkdir '/Users/fat624/.local/share/.nativescript-cli'
Error: EACCES: permission denied, mkdir '/Users/fat624/.local/share/.nativescript-cli'
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:21:45
    - - - - -
    at Error (native)
```
That's me trying to type in my password because it was prompting me for that AND for the "Do you want me to run the setup script? [Y/n]"!

If it's already being run as `sudo`, why does it need sudo access again?
