### ISSUE TITLE
Livesync not working on android connected wirelessly

### ISSUE THREAD

**Issue by sfabriece** [NativeScript/nativescript-cli#1646]
I'm just getting started with nativescript. 
I've setup my device to connect to adb wirelessly. I can't get livesync to work.
The console indicates that it has successfully synced, but no changes on the phones screen.

**Comment by enchev** [comment]
Hey @sfabriece,

Do you still have problems with this?

**Comment by sfabriece** [comment]
Sorry, I haven't with nativescript for a while. I'll let you know when i do.
