### ISSUE TITLE
Analytics for OS X version

### ISSUE THREAD

**Issue by Mitko-Kerezov** [NativeScript/nativescript-cli#1652]
Currently we track the `Windows` version, but not the `OS X` one. OS version is crucial information and could give insight on easier ways to further develop the CLI.

**Comment by rosen-vladimirov** [comment]
We should have tracked this, I consider it as bug :)

**Comment by enchev** [comment]
I don't believe that OSX version is valuable statistic. Usually more than 90% are using the latest version .
