### ISSUE TITLE
Add command for searching nativescript plugins

### ISSUE THREAD

**Issue by TsvetanMilanov** [NativeScript/nativescript-cli#1665]
The command should have flags to specify the count of the displayed plugins.
For example --count 10 should list 10 plugins per page, --all should list all plugins.

**Comment by dtopuzov** [comment]
Not working, move back in progress.

**Comment by rosen-vladimirov** [comment]
What's not working, currently I found only one issue - when there are no results, we print table with headers only.
Please note that the first time when the command is executed, it may take a while to build the local index. On my  Linux it took around 40 seconds, but based on your setup, machine, internet connection, etc. it may last even longer.
Please clarify what's "not working". @dtopuzov

**Comment by dtopuzov** [comment]
I tough it will return search results immediately (as fast as search in npm website). Closing this issues since the feature works, however it is much slower compared to search in npm website.
