### ISSUE TITLE
Changes to info.plist not applied with tns livesync and tns build 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#1666]
When changes are made to **info.plist** file the changes are applied 
after **tns run** or **tns deploy** but are not applied after **tns livesync** or **tns build**
For example reffer to [#1881](https://github.com/NativeScript/NativeScript/issues/1881)

**Comment by vchittar** [comment]
Is this fixed yet, I still cannot seem to display pictures with http links on my app. Thanks!
