### ISSUE TITLE
gfs.gracefulify is not a function

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1675]
_From @alamgird on April 11, 2016 14:6_

After running the installation script, tns doctor shows the following error:

gfs.gracefulify is not a function

_Copied from original issue: NativeScript/NativeScript#1933_

**Comment by Mitko-Kerezov** [comment]
@alamgird
This is most probably related to a quirk/bug in npm 3.x.

I can suggest upgrading to the latest stable node 5.10.1 or downgrading to the latest LTS node 4.4.2. Both of these approaches should resolve the issue.

Note however that **before** attempting an upgrade or a downgrade respectively, you should make sure to uninstall the nativescript package (by running **$ npm uninstall nativescript -g**) and clear npm's cache (by running **$ npm cache clean**)

**Comment by nikolal** [comment]
I confirm that solution above works. Thanx.
