### ISSUE TITLE
Feature Request: Additional TNS Doctor Check

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1695]
I've had a couple people who I have helped with the 1.7.x runtime upgrade run into this issue; and the TNS DOCTOR command would be a great place for tns to detect this issue, although during build might not be a bad place also...

Several people upgraded from v1.5 and 1.6 to 1.7.  The TNS-Core-Modules MUST be in sync to use the newest runtime.  However, these people updated the platform files (either purposefully or when trying to see if the platforms folder was corrupt) and they got the v1.7 android runtimes.    When they went to run their program the next time it crashed with a error message that left them scratching there heads as to what is wrong.

I am proposing that TNS DOCTOR if ran inside a app folder; will look at the package.json file read both the tns-core-modules key and the runtime key and verify they are both the same major.minor version.  So 1.7.x = 1.7.x.   If they are not the same versions -- then throw a warning saying That the core modules does not appear to match the runtime and this could potentially cause the app to crash and that they should fix this issue with a "npm install tns-core-modules@latest" or a "tns platform remove android/ios" & "tns platform add android/ios".

**Comment by rosen-vladimirov** [comment]
@NathanaelA , interesting idea. With our next release `tns doctor` command will check for available updates of the modules, runtimes and CLI and if some of them could be updated, we show a table with information:
![updatesavailable](https://cloud.githubusercontent.com/assets/8351653/14714195/bb32ee2e-07ec-11e6-946f-55c1bd896996.png)

Also we've added new command: `tns info` and when you execute it inside your project, it will give you information for your current versions of modules, runtimes and CLI and the latest available version.

Does this fulfill your requirement?

**Comment by NathanaelA** [comment]
Sweet, yeah that is exactly what is needed -- does it also list itself in the table (i.e. the nativescript command).

**Comment by rosen-vladimirov** [comment]
@NathanaelA,
The `tns info` command will check the versions of:
* `tns-android`
* `tns-ios`
* `tns-core-modules`
* `nativescript-cli`

It will show the current versions and latest versions.

`tns doctor` command will check the same items and will show the table only in case any of them could be updated (and of course will show only the items that can be updated).

I'm closing this issue now, but feel free to reopen it in case you have any concerns.
