### ISSUE TITLE
LiveSync does not work on iOS

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1696]
_From @tjvantoll on April 11, 2016 14:13_

I think this is a known issue, but I thought I’d log it here so it could be tracked. In ng2 {N} apps LiveSync does not work for on iOS—with or without the `--watch` flag.

The command executes successfully, but the app itself never updates. `tns livesync android --watch` works great.

Thanks.

_Copied from original issue: NativeScript/nativescript-angular#167_

**Comment by hdeshev** [comment]
_From @rosen-vladimirov on April 19, 2016 15:24_

@tjvantoll Can you give me a sample project reproducing the issue.
I've tried (with latest CLI from release branch of course) to reproduce the issue, but it works fine on my side. My steps are:
* `$ tns create myAngularApp --ng`
* `$ cd myAngularApp`
* `$ tns run ios`
* `$ tns livesync ios --watch`

@burkeholland in case you have any idea how to reproduce it, can you share it.

**Comment by hdeshev** [comment]
_From @tjvantoll on April 19, 2016 15:48_

@rosen-vladimirov Using the released version of the CLI I’m unable to livesync any changes in Groceries. Here’s what I’m doing:

* `git clone https://github.com/NativeScript/sample-Groceries.git`
* `cd sample-Groceries`
* `git checkout angular-end`
* `tns install`
* `tns run ios --emulator`
* `tns livesync ios --emulator --watch`
* Change any file. The livesync watcher will detect the change, but the app won’t update.

This might something specific to the configuration in Groceries, because when I try a new app I can only recreate the problem with CSS changes (TypeScript changes livesync as expected). Here are the steps:

* `tns create myAngularApp --template tns-template-hello-world-ng`
* `cd myAngularApp`
* `tns run ios --emulator`
* `tns livesync ios --emulator --watch`
* Change anything in `app.css`. The livesync watcher will again detect the change, but the app again won’t update.

I’ll give the release branch a shot to see if I have better luck with it.

**Comment by hdeshev** [comment]
_From @tjvantoll on April 19, 2016 16:15_

Ok good news and bad news.

**Good news**: I installed the {N} CLI from the release branch and I’m no longer having the same issue with Groceries. TypeScript changes livesync as expected 🎉

**Bad news**: I am still not seeing changes I make to CSS files, even in the release branch. I can recreate this in Groceries and in new apps using the steps above.

**Comment by hdeshev** [comment]
_From @tjvantoll on April 19, 2016 16:16_

So it appears that, with the updated CLI, the problem is limited to CSS changes on iOS.

**Comment by rosen-vladimirov** [comment]
@hdeshev ok, thanks, I'll check it immediately

**Comment by rosen-vladimirov** [comment]
Hi @hdeshev ,

It looks like the problem with `.css` files is that the app is not restarted. However we've added new functionality for the 2.0.0 release of NativeScript CLI, that allows the plugins to define if the livesync should restart the application. You can find a sample plugin here:
https://github.com/TsvetanMilanov/nativescript-restart-on-sync-plugin

The idea is to add `before-livesync` hook and set `$usbLiveSyncService.forceExecuteFullSync = true;`
I've added such hook and after changing the `.css`, my application was restarted and everything worked as expected.

**Comment by tjvantoll** [comment]
@hdeshev @rosen-vladimirov Is the next step for making sure that all new ng2 apps get that hook by default adding the nativescript-restart-on-sync-plugin plugin to https://github.com/NativeScript/template-hello-world-ng?

**Comment by rosen-vladimirov** [comment]
@tjvantoll we should add it to `nativescript-angular` plugin instead.
We'll talk with @hdeshev and we'll add it very soon :)

**Comment by hdeshev** [comment]
Just published it as nativescript-angular@0.0.43.
