### ISSUE TITLE
tns livesync ios does not work with CLI 1.7.1. 

### ISSUE THREAD

**Issue by stefanaerts** [NativeScript/nativescript-cli#1698]
tns livesync ios does not work with CLI 1.7.1.
Th error message: 
"Error Command failed: /bin/sh -c killall sampleGroceries.app
No matching processes belonging to you were found
 while executing killall sampleGroceries.app "

When i kill sampleGroceries myself it works,but kill sampleGroceries.app doesn't work
because thats not the name of the process,its sampleGroceries.

killall "nameofapp".app  shoud be killall "nameofapp"

I use mac os x 10.9.5 when running it.

**Comment by snailbites** [comment]
+1 

Running `/bin/sh -c killall sampleGroceries` seems to run with no errors, but I can't seem to find where this command is being run from. Is no one else having this problem? It's one of the first steps in the tutorial!

**Comment by vchimev** [comment]
Hi,

are you able to reproduce this issue with NativeScript 2.0.0? If yes, what is your Xcode version?

**Comment by snailbites** [comment]
@vchimev I am on 6.4 (6E35b) and NativeScript 2.0. I just pulled the latest from the angular-start branch so I should be up to date. Also I am on Node v4.2.6.

I don't really have much in the way of a good repro as I'm only on the first page of the angular tutorial. But this is what I am doing, if it helps:

1) Complete all of the steps on the angular tutorial up to 1.4, Running your app. I run `tns run ios --emulator` and ios simulator pops up with the hello world screen.
2) Ctrl + C out of that as specified in 1.5. The simulator is still running. Then I run `tns run ios --emulator
`.
3) I get this message and the changes I make are not automatically updated on the app.
`Error Command failed: /bin/sh -c killall sampleGroceries.app
No matching processes belonging to you were found
 while executing killall sampleGroceries.app.`

**Comment by dtopuzov** [comment]
Can not reproduce with {N} 2.0.1 and Xcode 7.3.
Is there a reason to use such old Xcode? 
Closing the issue, please reopen if you still reproduce with {N} 2.0.1 and Xcode 7.*
