### ISSUE TITLE
Angular hot reloading / replacement

### ISSUE THREAD

**Issue by mardo** [NativeScript/nativescript-cli#1713]
Hello!

I'd like to know if hot reloading is coming for nativescript-angular apps. I know livesync is working, but it refreshes the whole app and doesn’t keep the state; I just want to know if we can go even further.

Let's say we make a change on the editor and the whole angular component gets replaced without refreshing the app, and you will be able to test that component with the app's current state (i.e. you are on a subpage where you already navigated, I'd love not to login/navigate/etc again just to test the component).

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-angular#268
