### ISSUE TITLE
tns does not work when only Android SDK 21 is installed

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#173]
I verified that I have installed Android SDK 21. When I tries adding a platform, got this error:

```Please install Android target 17 the Android newest SDK). Make sure you have the latest Android tools installed as well. Run "android" from your command-line to install/update any missing SDKs or tools.```

Also, note the spelling mistake ;)

**Comment by ErjanGavalji** [comment]
In the original message (I verified that I have installed Android SDK 21.), did you ONLY have Android SDK 21, but not SDK Android SDK 17?

**Comment by fourpixels** [comment]
Unfortunately this keeps happening, despite "Android SDK 19 or later" info in system requirements. Just just fresh install following step by step instructions (from http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-win.html), and ended up here:

```
Please install Android target 17. Make sure you have the latest Android tools in
stalled as well. Run "android" from your command-line to install/update any miss
ing SDKs or tools.
```

Had to play around (in)installing different SDKs from Android SDK Manager, and hit the spot at Android 4.4.2 (API 19).

Win 7, fresh install of everything that's in the instructions (choco, ant, geny, everything).

**Comment by Alber70g** [comment]
@fourpixels I can confirm this.

**Comment by teobugslayer** [comment]
Hi @fourpixels , @Alber70g,

We have a list of verified SDKs which we should be able to use to build {N} projects. The list is [here](https://github.com/NativeScript/nativescript-cli/blob/release/lib/services/android-project-service.ts#L15). Can you verify that you have fully installed one of the supported SDKs?
I have just tried building with MNC SDK and it worked (this code will land in master later).

**Comment by fourpixels** [comment]
Hm, I have tried installing BOTH MNC and standard API22 (Android 5.1.1) - with those two together I wasn't able to make it work. I'm not sure if this is kind of my fault, but I finally did it with API 19 (4.4.2).

The bad thing is that the error says 'Use Android 17', which is from 2013, and it seems like different from the docs - 19 (requirements)..

**Comment by toddanglin** [comment]
Just experienced this, too, with NS 1.1.0 running on Mac. Is this a regression?

**Comment by rosen-vladimirov** [comment]
Hi @toddanglin, 
I believe the problem on your side is because you have only API Level 22 installed, am I right? Currently this version is not added to "supported versions" in CLI. I'm working on adding support for API Level 22, you can check this issue https://github.com/NativeScript/nativescript-cli/issues/551

**Comment by fourpixels** [comment]
The error received is wrong - `Please install Android target 17`. And I get no clue how to solve it. More important is that **requirements are wrong**, as they state `Android SDK 19 or later`. If the platform does **not** support  API 22, then you should clearly state it. As far as I can see in the code, lvl 20 is not supported either?

My point here is that as a new customer of your product, I would love to try it, but I get misguiding requirements and error messages, which, as you all know, is very frustrating to fight with.

**Comment by rosen-vladimirov** [comment]
Hi @fourpixels ,
You are correct, that the message is not clear. I've already replaced it in my [PR here] (https://github.com/NativeScript/nativescript-cli/pull/554/files#diff-b64860922c31aeed973aef6663b2a536R366), so it should give you more information which are the supported versions.
Also we'll make sure to sync our code and the system requirements. Thanks for spotting this and please excuse us for the caused inconvenience.

**Comment by Anilinfo2015** [comment]
I have faced this issue whole week, now i am regret to choose nativescript.
