### ISSUE TITLE
TNS 2.00 & Macintosh without Java/Android configured

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1732]
This is a annoying regression in the CLI on macs.

TNS run **ios**, tns debug **ios**, tns deploy **ios**, tns emulate **ios**, and tns prepare **ios** 
See the commonality.  ;-)

I do all my Android development on my PC, and so my mac is not configured for even java or Android.

Now when ever a plugin is updated, installed or manually changed the TNS command will now spit out the following:

The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
To be able to perform Android build-related operations, set the ANDROID_HOME variable to point to the root of your Android SDK installation directory.

Ok, so that is just annoyingly pointless verbage since I asked for a iOS build.   But the real regression is that it checks the Java version.  Does anyone remember what happens when you don't have Java installed on a Mac osx box.  You get one of these:
![java-missing-osx](https://cloud.githubusercontent.com/assets/850871/14902559/676b9834-0d61-11e6-9ca2-d2491f6a5ec7.png)

Do you have ANY idea how frustrating that is to have popup frequently...  Argh....

**Comment by enchev** [comment]
Hey @NathanaelA,

I've just tried this on my Mac where ANDROID_HOME is not configured at all however all commands worked as expected. I'm using CLI 2.0.1.

**Comment by NathanaelA** [comment]
Do you have Java installed?   The error message is about Java not being installed. 

For some reason even when I try and do any command stuff; say like "tns debug ios --emulator" or "tns emulate ios" on a mac, it still attempts to check the "java" version; which is what brings up that dialog if you do NOT have java installed...   This is a NEW issue with v2.00 of the CLI.    Prior versions were apparently smart enough to realize I asked for an iOS build and didn't need to check any of the android values...   The ANDROID_HOME warning is just garbage, it just wastes space on the screen.  The stupid Java popup is what is REALLY annoying.

**Comment by enchev** [comment]
No. I've tested this on Mac with no Java installed.

**Comment by NathanaelA** [comment]
So when you type "java" at a command prompt you see  that error dialog show up?

**Comment by rosen-vladimirov** [comment]
I believe @vakrilov had faced the same issue, so we'll investigate it further. Not sure what's causing this behavior.

**Comment by vakrilov** [comment]
I confirm. On a Mac with no Java -> I get the popup every time i build.

**Comment by enchev** [comment]
Ok. We've found [what's causing the problem](https://github.com/telerik/mobile-cli-lib/blob/052500b761c8582616a52c24a2b25b73d9882939/sys-info-base.ts#L19). This code was intended initially to be called only from `tns doctor` (post install) however now is used in various services during build/prepare. The class should be split in two platform independent classes to avoid further problems.
