### ISSUE TITLE
[node.js 6.x support] Native module sources is not supported

### ISSUE THREAD

**Issue by mehfuzh** [NativeScript/nativescript-cli#1733]
After updating to nativescript 2.0 when I try to install a plugin I am getting the following error:

(node:9070) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by NickIliev** [comment]
Hello @mehfuzh 

Which version of **node.js** are you using?
This error is caused by some packages not supporting **version 6** so if that is the case
you can try going back to **5.x**

**Comment by NickIliev** [comment]
I have installed the latest nodejs v.6.0.0 and the issue is confirmed.
Installing any plugin via **tns plugin add xxx** will return 
`Support for node.js 6.0.0 is not verified. This CLI might not install or run properly.`

@mehfuzh As a solution I recommend to use the recommended Node.js version (4.4.x) or any version lower then 6 (I have tested successfully with 5.9.x) - you can use [NVM](https://github.com/creationix/nvm) to easily switch within Node.js versions

**Comment by hekigan** [comment]
I can confirm that.
I had to rollback to v5.11.1
Do we know specifically which plugin is causing that?

In my package.json I only have the following:
```
...
"nativescript-drop-down": "^1.2.5",
"nativescript-telerik-ui": "^1.1.0",
"tns-core-modules": "2.0.0"
...
```

**Comment by enchev** [comment]
Hey folks,

Right now node.js 6.x is still not supported and we will do our best to add support in the next release. 

Hey @rosen-vladimirov, 

Can you list here everything that needs to be precompiled with node.js 6 here?

Thanks

**Comment by geminiyellow** [comment]
👍

**Comment by rosen-vladimirov** [comment]
Ooops, @enchev , sorry, I've somehow missed your comment. 
When we want to support new Node.js version, there are a couple of C++ dependencies that we have to rebuild (and get the latest changes from their upstreams in case there are such changes). We've forked the C++ dependencies and modified them to use our own module called `prebuilt`. This allows us to distribute prebuilt binaries, so the end users will not need any tools when installing NativeScript CLI (rebuilding C++ dependencies requires Python, node-gyp, G++ or Visual Studio, based on the OS, etc.).
The dependencies that we have to rebuild are:
* bufferutil
* ffi
* fibers
* ref
* utf-8-validate

Also we have to update our dependencies that depend on any of these packages, which are:
* ios-sim-portable
* NodObjC
* ref-struct
