### ISSUE TITLE
'tns' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by DocGreenRob** [NativeScript/nativescript-cli#1738]
I am new to NativeScript and am currently going through the installation steps described here (http://docs.nativescript.org/angular/tutorial/ng-chapter-1) and I just completed executing the PowerShell script 

`@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/NativeScript/nativescript-cli/production/setup/native-script.ps1'))"`

and then I run

`tns doctor`

and I get

`C:\>tns doctor
'tns' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by NickIliev** [comment]
Hello @DocGreenRob 

This script will install all the additional requirements but before you run it you have to already passed step two in the tutorial as follows : 
`npm install -g nativescript`

To install npm packages you must have installed [Node.js](https://nodejs.org/en/) (versions 0.10, 0.12, 4.x or 5.x)  - do not install version 6 as it is not supported by many nopm packages at this moment.

After you install nativescript you will have all the NativeScript CLI commands in your shell/prompt
including **tns doctor** and **tns help**

I hope that will be helpful - let me know if you ned further assistance

**Comment by obendesmond** [comment]
You might want to use "sudo" for ubuntu
>sudo npm install -g nativescript

**Comment by PixsaOJ** [comment]
> You might want to use "sudo" for ubuntu
> 
> > sudo npm install -g nativescript

Never use `sudo` with npm

**Comment by angelrepublic24** [comment]
I don't know why,
But i've installed global nativescript, also i check the path and doesn't work.
But tns was working before to install node 8.

But now i check and tns is working but in cmd, if a use the visual studio terminal or git bash doesnt work
i don't know why
