### ISSUE TITLE
TNS issues with ANDROID_HOME path

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1742]
I was helping someone get going on mac, and TNS kept saying they didn't have ANDROID_HOME set properly or that the folder didn't exist.  I manually walked through each of the steps, and everything looked fine from the disk perspective and even ls $ANDROID_HOME/<path> worked great.

The issue:
ANDROID_HOME=/SOME/PATH**/**
See that little trailing backslash?   Yep, TNS gets totally confuse by having a trailing slash as part of the ANDROID_HOME variable; so TNS should add some code to detect if their is a back slash at a minimum and ask them to fix it; or in best case; just use it as is, ie.  home= home.substring(0,home.length-1)...

**Comment by enchev** [comment]
Hey @NathanaelA,

Are you using [our setup scripts](https://github.com/NativeScript/nativescript-cli/blob/master/setup/native-script.rb) by chance? Or you've got this after the installation when you try to run some command?

**Comment by NathanaelA** [comment]
@enchev actually it was someone else's machine that I was helping on slack.    I do NOT know if they used your setup scripts.  

However what I do know is that if you add:
ANDROID_HOME=/some/path**/** vs ANDROID_HOME=/some/path  The TNS command has major issues and will insist that Android software is NOT installed if you have a trailing "/" on the end of the ANDROID_HOME path.

**Comment by enchev** [comment]
I've tried this today both on Mac and Windows and everything worked normally, that's why I'm asking do you get problems during installation or when running commands.

**Comment by NathanaelA** [comment]
The issue was when running any "tns" commands.   Even TNS doctor was stating that android was not installed.

**Comment by NathanaelA** [comment]
Hmm, I can't duplicate this on Linux or Windows either.     Not sure why removing the / helped two different people on Slack when v2.0 was just released.    Since neither of us can duplicate this; this should just be closed as un-duplicatable.
