### ISSUE TITLE
Cordova error compiling for android cause "-" char in package name id

### ISSUE THREAD

**Issue by ktemo** [NativeScript/nativescript-cli#1758]
I am using last version of meteor and I am getting this error, if I remove the "-" everything works as expected.

=> Errors executing Cordova commands:

   While adding platform Android to Cordova project:
   Error validating package name. Package name must look like: com.company.Name
   at validatePackageName (/Users/temo/.cordova/lib/npm_cache/cordova-android/5.1.1/package/bin/lib/create.js:164:25)
   at Object.exports.create (/Users/temo/.cordova/lib/npm_cache/cordova-android/5.1.1/package/bin/lib/create.js:237:12)
   at Api.createPlatform (/Users/temo/.cordova/lib/npm_cache/cordova-android/5.1.1/package/bin/templates/cordova/Api.js:95:6)
   at
   /Users/temo/.meteor/packages/meteor-tool/.1.3.2_4.1e55l81++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js:191:24
   at _fulfilled
   (/Users/temo/.meteor/packages/meteor-tool/.1.3.2_4.1e55l81++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/temo/.meteor/packages/meteor-tool/.1.3.2_4.1e55l81++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/temo/.meteor/packages/meteor-tool/.1.3.2_4.1e55l81++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/temo/.meteor/packages/meteor-tool/.1.3.2_4.1e55l81++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:557:44
   at flush
   (/Users/temo/.meteor/packages/meteor-tool/.1.3.2_4.1e55l81++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:458:13)

**Comment by enchev** [comment]
Hey @ktemo,

Can you post more info how this is related to NativeScript CLI?
