### ISSUE TITLE
CLI not directing the commands correctly to the correct device/emulator

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1765]
Currently some emulators are not recongnized as emulators and CLI is not working correctly with them

The problem manifests itself in VS Code where there are two options for debug "Launch on Android Device" and "Launch on Android Emulator". In other words there is no way for the user to use plain commands like "tns debug android" and is always specifying --emulator or --device. 

The problem is the user is required to use "Launch on Android Device" for some emulators (Visual Studio Android Emulator is one) in order to get the debug session working. 

For every command the CLI receives it issues multiple adb commands to the device. The correct way to work is to respect the "--emulator" given to the tns command and use "adb -e" for every adb command send to the device. This way all Android emulators will work correctly and the user will be happy selecting "Launch on Android Emulator" as expected.

this is somewhat related to #1763 since this will fix it.

**Comment by blagoev** [comment]
We already received some issues regarding this incorrect behavior outlining the expectations of the users

https://github.com/NativeScript/nativescript-vscode-extension/issues/38
https://github.com/NativeScript/nativescript-vscode-extension/issues/23

**Comment by rosen-vladimirov** [comment]
@blagoev 
May I ask you for some clarification, which are these emulators that are not recognized as emulators?

**Comment by blagoev** [comment]
>  (Visual Studio Android Emulator is one) 
> maybe Genymotion

**Comment by blagoev** [comment]
@rosen-vladimirov The best way of targeting the emulator is by not "recognizing it" but by redirecting communication to it. Similar how adb does it.

https://github.com/android/platform_system_core/blob/master/adb/commandline.cpp#L1480
https://github.com/android/platform_system_core/blob/master/adb/commandline.cpp#L1715-L1716

In our case this "targeting" means passing "-e"  to all adb commands that correlate to the executed "tns xyz" command

**Comment by rosen-vladimirov** [comment]
Using `-e` flag will work for debug command, but not for other commands as it requires only single emulator to be used. However many commands are designed to work with multiple devices. So we should check carefully and make sure other commands will work as expected.

**Comment by enchev** [comment]
Not valid with the latest VS Code run options
