### ISSUE TITLE
"tns livesync ios --watch" doesn't sync changes if pacakgeId and folder name does not match

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/nativescript-cli#1770]
tns livesync ios --emulator --watch  doesn't sync xml and css files but js.

**Comment by rosen-vladimirov** [comment]
@SvetoslavTsenov  is this issue reproducible?

**Comment by SvetoslavTsenov** [comment]
Hi @rosen-vladimirov, it is my mistake everything works perfectly fine.
