### ISSUE TITLE
Show warning when livesync cannot reflect a change

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1773]
This is some feedback we got from our call with Martin Keiblinger. Suppose you have a `livesync` watcher running and you change some file in `App_Resources`—let’s say `AndroidManifest.xml`. You’ll see something like this:

```
Transferring project files...
Unable to sync file /Users/tj/dev/nativescript/sample-Groceries/app/App_Resources/Android/AndroidManifest.xml. Error is: ENOENT: no such file or directory, stat '/Users/tj/dev/nativescript/sample-Groceries/platforms/android/src/main/res/AndroidManifest.xml'
Try saving it again or restart the livesync operation.
```

This can be confusing as following the output’s instructions—aka saving the file again or restarting the livesync operation—isn’t going to help. Instead we should be smarter about knowing when the CLI can’t reflect a change, and print out a big error.

> ERROR: We detected a change to the `App_Resources/Android/AndroidManifest.xml` file. This change requires a full Android build to update your application. Would you like to stop the `livesync` command and perform that build now? (y/n)

Something like that that at least points the user in the right direction. And we should try to include this warning for any change that we’re unable to livesync—`package.json` changes, etc.

**Comment by enchev** [comment]
Hey folks,

Interrupting livesync to perform full rebuild in case of major changes like files in the `App_Resources` folder is very good idea and we definitely need to research carefully how to implement it properly. 

In the meantime I think that it will be easier to simply exclude files in the `App_Resources` folder during livesync and warn the user in case of changes in these files:
![untitled](https://cloud.githubusercontent.com/assets/5804953/15643803/f801b964-2657-11e6-9641-f58fa95cd868.png)

**Comment by tjvantoll** [comment]
@enchev Looks great! 😀
