### ISSUE TITLE
sample-Groceries w/Telerik UI crash when using Nativescript 2.0

### ISSUE THREAD

**Issue by 3logy** [NativeScript/nativescript-cli#1775]
Groceries worked fine with Nativescript 1.7 but update to 2.0 i can't build an Android Platform anymore. I need to remove the Telerik UI and XML using it, to be able to build again.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#86

**Comment by johnsunam** [comment]
![13735185_1114318365302277_2086309563_n](https://cloud.githubusercontent.com/assets/10027298/16896560/6b626d16-4bb7-11e6-9579-dc1e77cb4839.png)
I got such type of the sideDrawer when i used telerik-ui sidedrawer please help me how do i get the actual sidedrawer shown on the demo
