### ISSUE TITLE
tns plugin add fails with error when a private github repo is used

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1784]
It should ask for credentials as normal "git clone" does

currently fails with message
remote: Invalid username or password.

**Comment by dtopuzov** [comment]
For plugin add we spawn `npm install <plugin> --save` which will fail for private repos.

However you can do it via npm:
http://stackoverflow.com/questions/28728665/how-to-use-private-github-repo-as-npm-dependency
