### ISSUE TITLE
"Last message repeated 133 times"

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1787]
_From @enchev on May 30, 2016 12:15_

_From @manijak on May 4, 2016 11:10_

I was trying to debug my app and added several console.log lines in different parts of code (functions where I fetch data). And watched the osx terminal for clues. 

I noticed the following line appear either before or after my console.log lines:
```May  4 12:26:15 --- last message repeated 133 times ---```

I was freaking out right about now. Looks like my service was called 133 times after tapping once on the refresh button! But no. 

Opened the Debug > System log console via the iOS simulator to see all the lines. And it happens that this line has nothing to do with my app.

```
May  4 12:25:45 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:26:15 --- last message repeated 133 times ---
May  4 12:26:16 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:26:16 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:26:27 --- last message repeated 26 times ---
May  4 12:26:27 MacBook-Pro routined[46342]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
May  4 12:26:29 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:26:48 --- last message repeated 57 times ---
May  4 12:26:48 MacBook-Pro fkzeljoapp[50283]: CONSOLE LOG file:///app/partial-views/fixtures/fixtures.js:134:20: fetch Fixtures - Done
May  4 12:26:48 MacBook-Pro fkzeljoapp[50283]: CONSOLE LOG file:///app/partial-views/fixtures/fixtures.js:112:20: fetch Results - Done
May  4 12:26:48 MacBook-Pro fkzeljoapp[50283]: CONSOLE LOG file:///app/partial-views/videos/videos.js:29:18: fetch Videos - Done
May  4 12:26:49 MacBook-Pro fkzeljoapp[50283]: CONSOLE LOG file:///app/partial-views/teams/first-team.js:116:24: fetch FirstTeam - Done
May  4 12:26:49 MacBook-Pro fkzeljoapp[50283]: CONSOLE LOG file:///app/partial-views/articles/articles.js:25:18: fetch Articles - Done
May  4 12:26:49 MacBook-Pro fkzeljoapp[50283]: CONSOLE LOG file:///app/partial-views/teams/first-team.js:129:24: fetch TeamBench - Done
May  4 12:26:52 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:27:22 --- last message repeated 49 times ---
May  4 12:27:46 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:27:46 MacBook-Pro assertiond[46357]: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
May  4 12:28:16 --- last message repeated 6 times ---
```

So it looks like the CLI console is showing some irrelevant information that can give people heart attacks :)
It ignores the "assertion failed:" comments but prints out the "last message repeated x times", this can easily lead to confusion when running the app via osx terminal. 

_Copied from original issue: NativeScript/nativescript-cli#1737_

_Copied from original issue: NativeScript/ios-runtime#570_

**Comment by enchev** [comment]
This is actually the console implementation in ios/JavaScriptCore :)

**Comment by enchev** [comment]
_From @fealebenpae on May 30, 2016 13:10_

@enchev this actually the syslog implementation in the [Apple System Log](http://stackoverflow.com/questions/17230451/stop-squashing-syslog-debug-messages-on-os-x) :)

@jasssonpet is right - this is an issue of the CLI trying (and failing) to filter the syslog output. [Many moons ago](https://github.com/telerik/mobile-cli-lib/pull/250) @jasssonpet and I worked to reliably forward the output streams only of the current app the same way the Xcode debugger does which is supposed to prevent exactly issues such as this one from occuring, but this functionality has sadly been lost to the mists of time after one of the many sweeping architectural changes in the CLI and has never been restored.

**Comment by enchev** [comment]
Ok. I'm moving the issue back to the CLI :(.

**Comment by enchev** [comment]
I'm almost sure that the same can be reproduced in Chrome/WebKit console and that's why I believe that JavaScriptCore is responsible for this and unfortunately I'm not sure what we can do in the CLI itself to improve this. In my opinion this is the expected behavior when you print multiple times the same message. 

Hey @manijak do you expect something different?

**Comment by manijak** [comment]
Well the thing is that it's not mine Console.log lines that are repeated, but something else that we not see in the console... something system based.

I am just saying, it confused me a lot, because by seeing this, i thought that my code was bad, and that my functions where called 133 times! When in fact they were not, the message was connected to some other lines, that we do not see.

**Comment by enchev** [comment]
Hey @manijak {N} CLI is not responsible for the combining nor messages as well and that's why I don't believe that we can do much on this topic. I'm closing this for now.
