### ISSUE TITLE
tns publish ios fails with cocoapods

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#1790]
Trying the `tns publish` command with the QSF fails with:

```
Code Sign error: Provisioning profile does not match bundle identifier: The provisioning
profile specified in your build settings ("OrgNativeScriptDistribution") has an AppID of
"org.nativescript.*" which does not match your bundle identifier
"org.cocoapods.IQKeyboardManager".
```

I don't think we should try to sign any of the cocoapod targets using the App's provisioning profile.

**Comment by PanayotCankov** [comment]
The following can produce `.xcarchive`:
``` bash
xcodebuild archive \
    -workspace nativescriptmarketplacedemo.xcworkspace \
    -scheme nativescriptmarketplacedemo \
    -archivePath nativescriptmarketplacedemo.xcarchive
```

And this can export a properly signed `.ipa`, ready for upload using `Application Loader`:
``` bash
xcodebuild
    -exportArchive
    -archivePath nativescriptmarketplacedemo.xcarchive
    -exportPath nativescriptmarketplacedemo.ipa
    -exportOptionsPlist export.plist
```
In combination with the `export.plist` (this is pretty much the options you have when exporting from Xcode UI):
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
	<key>uploadBitcode</key>
	<false/>
	<key>uploadSymbols</key>
	<false/>
</dict>
</plist>
```

**Comment by PanayotCankov** [comment]
The `tns publish ios <itunesuser> <itunespass>` will now create Xcode archive and export ipa successfully with pods.

**Comment by vbresults** [comment]
@PanayotCankov @enchev @rosen-vladimirov This is happening again for me in 2.4.0, can anyone reproduce?  publish seems to be selecting the cocoapod scheme (in my case IQKeyboardManager) instead of the NS scheme.

**Comment by vincentpalita** [comment]
@vbresults : did you specify an "ipa" path in your build command? If yes, remove it and keep the default folder.
As specified in the code at line https://github.com/NativeScript/nativescript-cli/blob/master/lib/commands/appstore-upload.ts#L54 if you specify an ipa path it will not create an archive.
Be careful also to not include arguments about provisioningProfile & codeSigningIdentify.
It should be only in your build.xconfig file.
Hope it helps even if it's a reply 2 months later...
