### ISSUE TITLE
The test init command to add a sample test in TypeScript for TypeScript/Angular projects

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1798]
The `tns test init` command configures a project for unit testing, creates a _tests_ folder in the _app_ directory and adds an **example.js** file in it with a sample test.

It would be great the sample test to be in TypeScript (example.ts) for TypeScript/Angular projects.

**Comment by tjvantoll** [comment]
This came up as a limitation while writing a guide on unit testing today, so I’ll toss in my vote for this feature.

**Comment by nraboy** [comment]
+1

**Comment by stefalda** [comment]
+1

**Comment by kalanaw** [comment]
+1

**Comment by JuanDelgadillo** [comment]
+1

**Comment by vstuen** [comment]
+1

**Comment by scottjmchugh** [comment]
+1

**Comment by harrinsonmb** [comment]
+1

**Comment by stefanmeschke** [comment]
+1

**Comment by jacobbundren** [comment]
+1

**Comment by Jai-Krish** [comment]
+1

**Comment by Roar1827** [comment]
+1

**Comment by simonox** [comment]
+1

**Comment by ludcila** [comment]
+1

**Comment by agra1992** [comment]
+1

**Comment by AresDev** [comment]
+1

**Comment by anorthwolf** [comment]
+1

**Comment by frapaa** [comment]
+1

**Comment by Belax8** [comment]
@vchimev or @tjvantoll, can we get an update on this issue? With this be worked on any time soon? Thanks!

**Comment by AresDev** [comment]
+1

**Comment by frapaa** [comment]
For now, here's an template/example of a `.spec.ts` file that works. It tests a component that requires a REST service, but that is mocked by mockito.

```
import {mock} from 'ts-mockito';
import * as utils from 'utils/utils';
import {ContactDetailsNSComponent} from '../contact-details/contact-details.component';
import {GtDirectoryService, ContactViewModel} from '@private/library';

describe('Contact details test', function () {
  let contactDetailsComponent;

  beforeEach(function () {

    const directoryService = mock(GtDirectoryService);
    contactDetailsComponent = new ContactDetailsNSComponent(new ContactViewModel('4799999999'), directoryService);
  });

  it('should create tel-uri when tapping call', function () {

    const spy = spyOn(utils, 'openUrl');
    contactDetailsComponent.onTapCall();
    expect(spy.calls.count()).toBe(1);
    expect(spy.calls.first().args[0]).toBe('tel:+4799999999');
  });

  it('should create sms-uri when tapping sms', function () {

    const spy = spyOn(utils, 'openUrl');
    contactDetailsComponent.onTapMessage();
    expect(spy.calls.count()).toBe(1);
    expect(spy.calls.first().args[0]).toBe('sms:+4799999999');
  });
});
```

**Comment by cvietor** [comment]
+2 :)

**Comment by Fedelaus** [comment]
In a project of entirely typescript files, it seems backwards to write JavaScript tests.
Is there any update to this, or is anyone aware of how to get my tests compiled along with `tns test <platform>`?

**Comment by nkalscheuer** [comment]
+2

**Comment by Fatme** [comment]
Currently you should be able to achieve this using the following steps:
1. Replace `example.js` file with `example.ts` inside `tests` folder 
2. Change the files property in `karma.conf.js`
```
files: [
      'app/tests/**/*.ts'
],
```
3.  Install the required definitions for the selected testing framework
When mocha is selected:  `npm i --save-dev @types/chai && npm i --save-dev @types/mocha && npm i --save-dev @types/karma-chai`

We're working on improving our unit testing story and planned this issue for one of our next releases.

**Comment by cowboyd** [comment]
This worked, but the `test init` command put the files in `src/tests/`, so we made this line in the [`karma.conf.js`][1] `src/tests/**/*.ts`

[1]: https://github.com/resideo-platform/exemplar/blob/cl%2Fbigtesting/karma.conf.js#L15
