### ISSUE TITLE
Livesync --watch fails every few changes for TypeScript projects with sourceMaps disabled

### ISSUE THREAD

**Issue by ibnzbssrckr** [NativeScript/nativescript-cli#1808]
Every few changes when running **tns livesync android --watch** the cli spits this back at me:

> Unable to sync files. Error is: ENOENT: no such file or directory, stat '/home/mike/WebstormProjects/NativeScript/sample-Groceries/platforms/android/src/main/assets/app/pages/list/list.html___jb_tmp___

I am working with the sample Groceries Typescript/Angular app from https://github.com/nativescript/sample-Groceries.git. I have not made any configuration changes beyond typing to disable sourceMap in tsconfig per another issue. I am using the Webstorm editor and think that it may be creating these temporary files.

**Comment by enchev** [comment]
Hey @ibnzbssrckr,

I don't have Webstorm however I've tested with Visual Studio Code and everything worked as expected. Since Visual Studio Code is where we want to invest the only option I can suggest you for now is to use instead Webstorm.

**Comment by enchev** [comment]
Most probably related to https://github.com/NativeScript/nativescript-cli/issues/1810

**Comment by adamansky** [comment]
You can use fork https://github.com/Softmotions/nativescript-cli with minor change https://github.com/Softmotions/nativescript-cli/commit/0bdaba69a853583ea704b9d20996f8d113956e2c
