### ISSUE TITLE
Fibers problem in npm install

### ISSUE THREAD

**Issue by Coolranch** [NativeScript/nativescript-cli#1811]
I'm experiencing the same issue found in https://github.com/NativeScript/nativescript-cli/issues/1348.  I applied the patch as specified here https://github.com/meteor/node-fibers/commit/d519f0c5971c33d99c902dad346b817e84bab001.  When I make the change and run node build -f I get the following output:

![image](https://cloud.githubusercontent.com/assets/1944174/15861443/63043c58-2c9a-11e6-9e00-7611f2257b99.png)

**Comment by enchev** [comment]
Hey @Coolranch,

Are you trying to build the CLI or you get this error during install? Can you try to call `npm cache clean` and try the install again?

**Comment by dtopuzov** [comment]
@Coolranch can you give some more details about your environment. 
Node version
OS Version

**Comment by dtopuzov** [comment]
@Coolranch closing because we can not reproduce, if you still encounter this issue, please provide exact steps, logs and info for your environment.
