### ISSUE TITLE
tns doctor can't find android.bat

### ISSUE THREAD

**Issue by psmak4** [NativeScript/nativescript-cli#1812]
When running tns doctor I get the following output.

`C:\>tns doctor
Unable to find "android.bat" executable file. Make sure you have set ANDROID_HOM
E environment variable correctly.
WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the nati
ve emulator.
To be able to build for Android and run apps in the native emulator, verify that
 you have
installed the latest Android SDK and its dependencies as described in http://dev
eloper.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the ch
ocolatey package manager to install the Android SDK and its dependencies.

NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or
 later.

Unable to find "android.bat" executable file. Make sure you have set ANDROID_HOM
E environment variable correctly.
Unable to find "android.bat" executable file. Make sure you have set ANDROID_HOM
E environment variable correctly.
Unable to find "android.bat" executable file. Make sure you have set ANDROID_HOM
E environment variable correctly.
Cannot find a compatible Android SDK for compilation. To be able to build for An
droid, install Android SDK 22 or later.
Run $ android to manage your Android SDK versions.

You need to have Android SDK 22 or later and the latest Local Maven repository f
or Support Libraries installed on your system.
Run $ android  to manage the Local Maven repository for Support Libraries.

There seem to be issues with your configuration.
? Do you want to visit the official documentation? No
? Do you want to run the setup script? No
Your components are up-to-date.

These warnings are just used to help the NativeScript maintainers with debugging
 if you file an issue.
Please ignore them if everything you use NativeScript for is working fine.`

I've confirmed that my ANDROID_HOME environment variable is pointed appropriately, as well as my JAVA_HOME environment variable.  I also have Android SDK 22 and 23 installed.  Any help would be appreciated.

**Comment by enchev** [comment]
Hey @psmak4,

What's your Java version? We need 1.8 since 1.7 is deprecated.

**Comment by dtopuzov** [comment]
You need:
Android SDK 22 or a later stable official release
Android SDK Build-tools 23.0.0 or a later stable official release
Local Maven repository for Support Libraries

**Comment by psmak4** [comment]
I have Java version 1.8.0_91, Android SDK Tools 25.1.7, Android SDK Platform-tools 23.1, and Android SDK Build-tools 22.0.1, 23.0.1, 23.0.2, and 23.1 all installed.

**Comment by psmak4** [comment]
Is there some diagnostic log I can produce to document this information?  Forgive my ignorance on this, I'm new to NativeScript.

**Comment by rosen-vladimirov** [comment]
Hi @psmak4 , can you execute:
$ tns doctor --log trace > out.txt
And send us the out.txt file?

**Comment by psmak4** [comment]
Here you go.
[out.txt](https://github.com/NativeScript/nativescript-cli/files/307836/out.txt)

**Comment by rosen-vladimirov** [comment]
@psmak4 , 
It looks like there's a problem with your Java. When CLI tries to execute
`C:\Users\pjones\AppData\Local\Android\android-sdk\tools\android.bat --help` it receives an error:
`'Usage: java [-options] class [args...]\n           (to execute a class)\n...`
Can you try executing the command `android.bat --help` directly in your cmd and see if it works?
Also please verify your JAVA_HOME environment is set correctly?
You can use `echo %JAVA_HOME%` and also `where javac` to determine the path to your Java executable.

**Comment by psmak4** [comment]
`C:\>android.bat --help
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument

    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for m
ore details.`

`C:\>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_92`

`C:\>where javac
C:\Program Files\Java\jdk1.8.0_92\bin\javac.exe`

**Comment by rosen-vladimirov** [comment]
@psmak4 ,
Definitely something's not correct here, but I'm not really sure what.
The output of `android.bat --help` should be something like:
```

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
...
```

I've googled the error and I have two suggestions (the first one sounds really weird, but I'll be glad if you can try it):
1) Try executing `android.bat --help` from a directory that is not in your root of the drive, for example make new dir:
```
$ mkdir test
$ cd test
$ android.bat --help
```

2) If this does not work, you can try the following: http://stackoverflow.com/questions/21914704/android-sdk-manager-refusing-to-open

**Comment by psmak4** [comment]
`C:\>mkdir test

C:\>cd test

C:\test>android.bat --help

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.
`

**Comment by psmak4** [comment]
I don't know why that gave a different output.

**Comment by rosen-vladimirov** [comment]
@psmak4 that's the correct output. Can you try running `tns doctor` inside test directory and see if the output will be correct this time.
By the way I've taken the idea for new directory from [here](https://groups.google.com/forum/#!topic/android-platform/UjY92-9CX48).
I'm totally confused what could cause such strange behavior.

**Comment by psmak4** [comment]
I just ran tns doctor from the same test directory and it gave a slightly different output as well.
`C:\test>tns doctor
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or
 later.

You need to have Android SDK 22 or later and the latest Local Maven repository f
or Support Libraries installed on your system.
Run $ android  to manage the Local Maven repository for Support Libraries.

There seem to be issues with your configuration.
? Do you want to visit the official documentation? No
? Do you want to run the setup script? No
Your components are up-to-date.

These warnings are just used to help the NativeScript maintainers with debugging
 if you file an issue.
Please ignore them if everything you use NativeScript for is working fine.`

**Comment by rosen-vladimirov** [comment]
@psmak4 
It looks like you do not have `Local Maven repository for Support Libraries` installed. Just run `$ android.bat`, navigate to the bottom of the page, select the `Local Maven repository for Support Libraries` and click install :)

**Comment by psmak4** [comment]
That doesn't appear in the list.
![android](https://cloud.githubusercontent.com/assets/847301/15945812/5be2d66a-2e51-11e6-87fd-2ec4f7dc40ed.jpg)

**Comment by rosen-vladimirov** [comment]
Ok, sorry, they've changed it's name again :(
It's `Android Support Repository`, I'll add separate issue to change the name in our code and docs.

**Comment by psmak4** [comment]
That was it.  Thanks for the help.  Still a little weird that it won't work from C: but will work from any sub directory.

**Comment by rosen-vladimirov** [comment]
@psmak4 
I've reproduced the same weird behavior, but not sure what's causing it. I'll mark this thread as KnonwIssue for anyone else who has the same problem.
Just a summary: `android.bat` file throws java error when executed from the root of a drive (C:\, D:\, etc.) and `tns doctor` is unable to detect if `android.bat` really works.

**Comment by jmoleiro** [comment]
I get a simillar error on OSX and the cli version 2.1.1

``
Directories found in /Users/jmoleiro/Library/Android/sdk/build-tools are 21.1.2, 22.0.1
Versions found in /Users/jmoleiro/Library/Android/sdk/build-tools are 21.1.2, 22.0.1
Selected version is:  undefined
Selected targetSdk is: 22
Directories found in /Users/jmoleiro/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0-alpha1, 24.0.0-alpha2, 24.0.0-beta1, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in /Users/jmoleiro/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0, 24.0.0, 24.0.0
Selected version is:  22.2.1
Selected AppCompat version is: 22.2.1
You need to have the Android SDK Build-tools installed on your system. You have to install version 23.
Run android from your command-line to install required Android Build Tools.
``

Any idea?

**Comment by rosen-vladimirov** [comment]
@jmoleiro the error on your side is:
```
You need to have the Android SDK Build-tools installed on your system. You have to install version 23.
```
You do not have Android SDK Build-tools 23 installed, please update your tools and try again.

**Comment by jmoleiro** [comment]
Yes, i read the thread before posting. There's no SDK v23. There's a 23.0.1, 23.0.2, 23.0.3, and i have those installed. But no 23

![screen shot 2016-07-11 at 6 18 38 pm](https://cloud.githubusercontent.com/assets/247449/16746848/b85b819e-4792-11e6-893a-a2356f0cf16f.png)
![screen shot 2016-07-11 at 6 18 22 pm](https://cloud.githubusercontent.com/assets/247449/16746849/b8789b08-4792-11e6-92f7-d3d338076089.png)

Again, any idea?

**Comment by rosen-vladimirov** [comment]
@jmoleiro from the log you've sent I see:
```
Directories found in /Users/jmoleiro/Library/Android/sdk/build-tools are 21.1.2, 22.0.1
Versions found in /Users/jmoleiro/Library/Android/sdk/build-tools are 21.1.2, 22.0.1
```

Can you verify your ANDROID_HOME environment variable points to the directory from your last screenshot?

**Comment by jmoleiro** [comment]
Ouch! The "android" utility runs from a completelly different folder to ANDROID_HOME. Now im looking why.

I executed the android utility from the ANDROID_HOME folder and yes, i didn't have the v23 version installed. Now is solved!

Thanks!
