### ISSUE TITLE
CLI does not respect the whole project template structure

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1819]
CLI tries to be smart for what to copy from the project template. It should copy the template as it it with the whole project structure. This magic logic brakes future enhancements of the project template.

**Comment by Plamen5kov** [comment]
related to: https://github.com/NativeScript/android-runtime/issues/561

**Comment by etabakov** [comment]
Closed in favor of https://github.com/NativeScript/android-runtime/issues/561
