### ISSUE TITLE
tns doctor stuck on Verifying CocoaPods

### ISSUE THREAD

**Issue by yogeshwar607** [NativeScript/nativescript-cli#1835]
<img width="1280" alt="screen shot 2016-06-12 at 4 22 03 am" src="https://cloud.githubusercontent.com/assets/10059011/15987840/858ca52a-3056-11e6-8dd2-330e82fb7834.png">

**Comment by enchev** [comment]
Hey @yogeshwar607,

What's your OSX and XCode version? Have you tried to run the same command with `--log trace`?

**Comment by yogeshwar607** [comment]
OSX version - 10.11.5
XCODE - 7.2
still struck there
screenshot with --log trace

<img width="1280" alt="screen shot 2016-06-14 at 3 39 38 am" src="https://cloud.githubusercontent.com/assets/10059011/16024874/b7471712-31e1-11e6-9ce8-3468d728d00e.png">

**Comment by PBartrina** [comment]
Same issue here, same OS and same xCode
![image](https://cloud.githubusercontent.com/assets/14554908/16046036/49b1d0e2-324b-11e6-9b65-d137d2b9bdf1.png)

**Comment by enchev** [comment]
Hey folks,

NativeScript CLI will simply call `pod --version`. Can you verify what will happen if you call the same directly?

**Comment by enchev** [comment]
Hey @vchimev @dtopuzov @SvetoslavTsenov can you help me to verify this?

**Comment by dtopuzov** [comment]
Can not reproduce with 
OSX 10.11.5
XCODE 7.3.1
{N} 2.1.0 Release candidate (it will be officially available by the end of the month)

@yogeshwar607 if you still encounter the problem, feel free to reopen the issue.

**Comment by yogeshwar607** [comment]
Waiting for {N} 2.1.0 ,
still gettting issue .

**Comment by enchev** [comment]
There are no changes related to this issue in the upcoming version. Have you tried to call manually `pod --version`?

**Comment by dtopuzov** [comment]
It might happen when /var/folders is too big. Can you try to clean up all folders inside /var/folder (do not delete /var/folder itself because it might damage your OS) and run "tns doctor" again.

**Comment by dtopuzov** [comment]
Issue is valid, we have just reproduced it.

**Comment by yogeshwar607** [comment]
solved the issue by cleaning /var/folders.
Thanks for efforts

**Comment by dtopuzov** [comment]
Another thing that might cause the same problem is cocoa pod installations. 
If cleanup /var/folders does not help you can try:
```
` $ sudo rm -fr ~/.cocoapods/repos/master`
`  $ pod setup`
```

**Comment by tolerious** [comment]
@dtopuzov  how to clean up the folders , just run `sudo rm -f * ` ? but I got operation not permitted.
