### ISSUE TITLE
Error in tns build android: 'spawn gradle.bat ENOENT'

### ISSUE THREAD

**Issue by ali-hooshmand** [NativeScript/nativescript-cli#1836]
I'm able to run NativeScript simple example. However, I am getting 'spawn gradle.bat ENOENT' when I'm trying to build a project where multidex is enabled. Here is my build log:
http://pastebin.com/mf6ZHVA0

Thanks,

**Comment by enchev** [comment]
Hey @Plamen5kov,

Do you know what can cause this?

**Comment by Plamen5kov** [comment]
Hi @ali-hooshmand 
> spawn gradle.bat ENOENT

What this message means is, cli can't find the `platforms/android/gradle.bat` file and run it. Make sure the file exists.

Could you provide us with some additional information. As I understand you had a working project and you tried to enable multidex support, so you probably did some changes. It would be helpful, if you could describe the steps you made from the start to finish. 
What command did you try to run, and what version of cli are you using. You can check by running `tns --version`

Also this problem may have something to do with Analytics.
>Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track exception with message 'spawn gradle.bat ENOENT'.

@ivanbuhov, @rosen-vladimirov

**Comment by ali-hooshmand** [comment]
Hi @Plamen5kov,
Thanks for the reply. FIrst, I check platforms/android and as you guessed I don't have the gradle.bat. How can I create this file?

Also, here are the steps I made:
This happened after I added nativescript-plugin-firebase to the project. All I did was:
"tns plugin add nativescript-plugin-firebase"
and then I added "GoogleService-Info.plist" file to platforms/android.
Then I added following lines to platforms/android/build.gradle:
in dependencies, added: "com.google.gms:google-services:3.0.0" and at the end of file "apply plugin: "com.google.gms.google-services""
Finally enabled Multidex by adding "multiDexEnabled true" in app.gradle.

Thanks..

**Comment by Plamen5kov** [comment]
Hi @ali-hooshmand 

>Then I added following lines to platforms/android/build.gradle

The place where you should add gradle dependencies is in `app/App_Resources/Android/app.gradle` instead of `platforms/android/build.gradle`. 

----
> and then I added "GoogleService-Info.plist" file to platforms/android.

`GoogleService-Info.plist` and `.plist` as an extension is used in iOS projects. The Android equivalent of the `.plist` is the `AndroidManifest.xml`. 

----
> Finally enabled Multidex by adding "multiDexEnabled true" in app.gradle.

If you want to enable multidex support you can see an example [here](https://github.com/NativeScript/sample-Android-Multidex). You need to do more than enabling it in the gradle configuration. Read more [here](https://developer.android.com/studio/build/multidex.html).

**Comment by flamoedo** [comment]
Run this:
`tns platform remove android
then:
`tns platform add android`

**Comment by tons613** [comment]
Am still having problem with this. I tried all the solutions suggested here, none worked. Any help please?

**Comment by tons613** [comment]
I got this sorted out. I think it is a permission issue. I moved my project folder to desktop and it worked perfectly well...

**Comment by KannaCoding** [comment]
> Run this:
> `tns platform remove android`
> 
> then:
> 
> `tns platform add android`

this worked for me..

**Comment by cristiaan3003** [comment]
`tns install` worked for me

**Comment by justintoth** [comment]
For me, I ran into this error when executing "tns update" to upgrade from NativeScript 7 to NativeScript 8. The first step of this process is to "clean old project artifacts", which must wipe out most of platforms/android. However, at the end of the upgrade it never restores these files. I would consider this a bug in the NativeScript upgrade process...

**Comment by NathanaelA** [comment]
@justintoth  - The `platforms/*` files are all artifacts of building.   So the next time you do a `tns run android` or `tns build android` it will automatically repopulate the `platforms/android` folder.

**Comment by justintoth** [comment]
@NathanaelA Unfortunately, that's not what happened when executing tns run android. Instead, it gave the spawn gradle.bat ENOENT error. I had to use the tns platform remove android / tns platform add android trick to get it to generate again.

**Comment by NathanaelA** [comment]
1. Was anything left in `platforms/` after it upgraded as you said "which must wipe out most of platforms/android" 
2. What ide are you using?
3. Did you have any shells active in the platform/android folder
4. was perhaps a `tns run` or `tns debug` still running when you tried to upgrade?

**Comment by justintoth** [comment]
Excellent questions...

1. Yes, the platforms/android folder existed. It had one file in it, I don't recall exactly which file it was.
2. WebStorm.
3 & 4. I definitely did, I had a tns run android active within WebStorm.

I guess that explains it! Thanks for the follow-up.
