### ISSUE TITLE
tns livesync android --watch hangs in Visual Studio Code integrated Terminal

### ISSUE THREAD

**Issue by harlankoehn** [NativeScript/nativescript-cli#1844]
I'm using the latest version of Visual Studio Code on Windows 7 64bit with tns version 2.0.1. When I attempt to run my project using the Code Integrated Terminal, tns hangs on "Transferring project files...". I've tried running Code as Administrator and it doesn't make any difference.

The same command works fine for me from the Windows command line.

One issue is that this seems to create multiple adb.exe processes with one of them bound to port 5037 and then you have to kill all instances of adb.exe in order to be able to even use the Windows Command Line.

Is this a VS Code issue? Is there some way I can create/view tns log files to further troubleshoot this issue?

**Comment by harlankoehn** [comment]
OK, not sure what's going on here. I think I posted a little too soon. I killed all the adb.exe processes and my terminal window created two and started working properly. I'll investigate a little further to see if I can duplicate the issue.

**Comment by kumanan12** [comment]
I am also getting the same issue.  I am running tns version 2.1.1.  Also updated Geny motion to 2.7.2. Killed the adb process.  Still no luck.  Any ideas.


![nativescript-issue](https://cloud.githubusercontent.com/assets/1306800/16740386/e1daa660-476c-11e6-9908-a7f80701e0a1.JPG)
