### ISSUE TITLE
Publish with Enterprise Apple Dev Account

### ISSUE THREAD

**Issue by bfattori** [NativeScript/nativescript-cli#1850]
I didn't know where else to put this, but when I'm working with an application that _i don't plan to deploy to the AppStore_, how do I go about doing that? I'm trying to release an internal mobile application, so I'm building it with an Enterprise account to be able to wildcard the provisioning profile.

Does TNS-cli support this? It really seems to be targeted at the AppStore and iTunes Connect.

**Comment by enchev** [comment]
Hey @bfattori,

When you prepare your app for ios (`tns prepare ios`) NativeScript CLI will create XCode project in the `platforms\ios` folder. You can open this project in XCode and archive/export like normal native app.
