### ISSUE TITLE
Why an application created with Angular template needs 2 package.json files?

### ISSUE THREAD

**Issue by fabioperrella** [NativeScript/nativescript-cli#1851]
When creating an application with `tns create AppName --ng` it is generated 2 package.json files: `package.json` and `app/package.json`

Is it really necessary the file `app/package.json`?

In Nativescript tutorial project "Sample-Groceries" the file app/package.json has only the key "main" but this file generated by `tns create --ng` has a lot of keys.

**Comment by enchev** [comment]
Hey @fabioperrella,

I believe that we have `package.json` both in the root folder of the project and in the `app` folder no matter if this is Angular app or not. The content of the `app` folder is separate NPM module downloaded as dependency and that is why we have the inner `package.json`.

**Comment by fabioperrella** [comment]
But when installing a npm module, like "email-validator", the dependency is added to root package.json

I made it when I was doing the tutorial, in chapter 5: http://docs.nativescript.org/angular/tutorial/ng-chapter-5

So I did not understand what will be added to app package.json, and if this file is really necessary

**Comment by enchev** [comment]
Hey @fabioperrella,

At the moment when you build the project this file will be simply copied to the native app (`platforms` folder). If we remove it we will need to introduce special logic in both NativeScript CLI and iOS/Android runtimes to handle it.
