### ISSUE TITLE
Flag when Android devices are out of storage

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1853]
This was originally reported in https://github.com/NativeScript/sample-Groceries/issues/97.

If you try to deploy to an Android device with insufficient storage, we show the “Successfully deployed on device with identifier 'LGXXXXX'” confirmation message, when the app hasn’t actually deployed. 

If you turn on trace logs during the build you’ll see the error below, but that’s hidden by default so users as left confused as to why their app doesn’t show up.

```
Result when throw error is false:
{ stdout: '\tpkg: /data/local/tmp/groceries-debug.apk\r\nFailure [INSTALL_FAILED_INSUFFI
CIENT_STORAGE]\r\n',
  stderr: '1482 KB/s (22105844 bytes in 14.565s)\n',
  exitCode: 0 }
Successfully deployed on device with identifier 'LGXXXXX'.
```

**Comment by rosen-vladimirov** [comment]
Hey @tjvantoll , 
This is already addressed and should be working fine in the next official release - the error is detected and shown to the user. I'll mark it as bug and set it to Ready for Test, so it will be included in the release notes.

**Comment by dtopuzov** [comment]
I can confirm it works in {N} CLI master
