### ISSUE TITLE
Android Typescript Template - AppLabel with Whitespace

### ISSUE THREAD

**Issue by SjurWarEagle** [NativeScript/nativescript-cli#1860]
Hi,

at the moment the name in package.json must not have any whitespaces and it has to match the app_name from strings.xml.
This results in the app_name not having whitespaces.
The label title_activity_kimera may have whitespaces but when it is different from the app_name this results in a bad unstallation dialog on Android.
![uninstallwrong](https://cloud.githubusercontent.com/assets/7311103/16177528/b5d8cbf2-3630-11e6-803b-5495d7d3ccd6.JPG)

A solution would be to change the default AndroidManifest.xml:

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/title_activity_kimera" <------ change this
		android:theme="@style/AppTheme" >
		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera" <------ remove this
			android:configChanges="keyboardHidden|orientation|screenSize">

after this, everything looks fine.

![uninstallok](https://cloud.githubusercontent.com/assets/7311103/16177530/b9e52394-3630-11e6-8805-2340f3126f83.JPG)

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#490
