### ISSUE TITLE
TNS doctor redirects OSX user to download JRE instead of JDK

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#1863]
_From @rbreaves on June 20, 2016 4:56_

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
2.0.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
N/A
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
N/A
- Plugin(s): (look for the version number in the `package.json` file of your
project)
N/A

### Please tell us how to recreate the issue in as much detail as possible.
Install nativescript on OSX 10.11 and run tns doctor without java installed and then follow the More Info link when the download java prompt appears. Can you not have the prompt prompt for the JDK instead?

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No.

_Copied from original issue: NativeScript/NativeScript#2338_

**Comment by enchev** [comment]
Hey @vchimev @dtopuzov can you verify this?

**Comment by dtopuzov** [comment]
With 2.1.0 RC if JAVA_HOME points to wrong location error is:
```
  ◠ Verifying CocoaPods. This may take some time, please be patient..
Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.
You will not be able to build your projects for Android.
To be able to build for Android, verify that you have installed The Java Development Kit (JDK) and configured it according to system requirements as
 described in https://github.com/NativeScript/nativescript-cli#system-requirements.
```

**Comment by rbreaves** [comment]
Ah, it may be something on the OS level then. The prompt I am referring too is a prompt given by OSX outside the terminal window. Not sure if there is a way to suppress that completely, but it would probably avoid the confusion. I followed the UI prompt that occurs outside of the terminal window vs what the text said in the terminal.

**Comment by vchimev** [comment]
I confirm that `tns doctor` throws an error if no JDK/JAVA_HOME available:

My guess is that we execute a `java` command in the [doctor service] (https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/doctor-service.ts) which results in the prompt below.

![os_x_jdk](https://cloud.githubusercontent.com/assets/12251337/16796287/8f53b6b4-48ea-11e6-9c2e-fa86eef888d4.png)

The "More info" button leads to *http://www.java.com/en/download/mac_download.jsp* which provides a download of JRE, but not JDK required by NativeScript.

I logged a separate issue here: https://github.com/NativeScript/nativescript-cli/issues/1922

**Comment by fdjean** [comment]
Same problem following http://docs.nativescript.org/start/ns-setup-os-x

El Capitan 10.11.6 
tns 2.2.1 

```bash
sudo npm i -g nativescript
```
```bash
Cannot read property 'match' of null
Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:9:16)
    at Module._compile (module.js:556:32)
Sending exception report (press Ctrl+C to stop).../usr/local/lib
└─┬ nativescript@2.2.1 
  └─┬ glob@7.0.6
    └── once@1.4.0 
```
