### ISSUE TITLE
CLI list plugins command

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#1880]
Currently there is "no way" to know which plugins are installed. (correct me if I am wrong)

We need tns plugins list command especially since tns plugin remove needs a plugin name

**Comment by rosen-vladimirov** [comment]
You can use `tns plugin` command which prints the following output:
![nativescriptplugins](https://cloud.githubusercontent.com/assets/8351653/16372975/53e5ecda-3c58-11e6-874a-0f42bad4a738.png)

**Comment by blagoev** [comment]
thats not how most CLI work.. ie is not very obvious. still thanks.

**Comment by blagoev** [comment]
I still think we should have "tns plugin list" in order to be more on par with all other cli envrionments

**Comment by blagoev** [comment]
in my view "tns plugin" should do nothing just list the available options 

tns plugin

list - info
add - info
remove - info

**Comment by enchev** [comment]
Already implemented
![untitled](https://cloud.githubusercontent.com/assets/5804953/17211646/5e11bfa2-54d3-11e6-8ab7-bec5de4350b8.png)
