### ISSUE TITLE
Uninstalled Node 6.2.2 but still can't get NativeScript working

### ISSUE THREAD

**Issue by a22munir** [NativeScript/nativescript-cli#1885]
Hi all, I'm trying to get started with NativeScript but I keep on running into errors. I originally had the unsupported version of Node on my computer but I uninstalled it and installed a supported version. This let me install chocolatey, Java, Android SDK and whatever else it installs when you run it. 

When I do node -v it gives me back v 4.4.6 and I can't find any reference of the later version on my computer.

However when I do tns in powershell it is giving me the following:

```

Support for node.js 6.2.2 is not verified. This CLI might not install or run properly.

C:\Users\Aazir\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
        ^

Error: `C:\Users\Aazir\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\bin\win32-x64-v8-5.0\fibers.nod
e` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (C:\Users\Aazir\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\fibers.js:16
:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Aazir\AppData\Roaming\npm\node_modules\nativescript\lib\common\helpers.js:3:13)
    at Module._compile (module.js:541:32)
 PS C:\Users\Aazir>
```

**Comment by a22munir** [comment]
Anybody?

**Comment by NickIliev** [comment]
Hey @a22munir 

From your log error, it seems that your app is still referring to Node.js 6.2.2.
So to ensure you have completly unistalled your Node.js follow this steps:

1.) Uninstall Node.js and restart
2.) Look for this folders and remove them,
 - C:\Program Files (x86)\Nodejs
 - C:\Program Files\Nodejs
 - C:\Users\{User}\AppData\Roaming\npm (or %appdata%\npm)
 - C:\Users\{User}\AppData\Roaming\npm-cache (or %appdata%\npm-cache)

After folders are gone you can run `where node` to check if other references are present.

3.) In your shell/cmd run %PATH% and make sure no references to Node.js are still present
4.) Restart and install wanted version of Node.js

As an alternative for this steps, you can use Node manager like this one [https://github.com/coreybutler/nvm-windows](https://github.com/coreybutler/nvm-windows) and install multiple versions which then can be easily changed with one command.

p.p. Keep in mind that our next release (2.1 will be announced in a matter of days) will come with a support for Node.js version 6.x

**Comment by a22munir** [comment]
Hello, thanks for your help! So, if the new version will come out in a couple days would it not be easier to just wait for that and then I would just have to install the new version of NativeScript. I am in no particular rush.

**Comment by NickIliev** [comment]
@a22munir  NaativeScript 2.1 is now released and the support for Node.js 6.2.2 is here.
