### ISSUE TITLE
BUILD SUCCESSFUL but nothing happens

### ISSUE THREAD

**Issue by joanlopez** [NativeScript/nativescript-cli#1893]
[out.txt](https://github.com/NativeScript/nativescript-cli/files/342919/out.txt)
[out2.txt](https://github.com/NativeScript/nativescript-cli/files/342918/out2.txt)

I'm trying to run the hello world app with Typescript but I can't..

I've tried with the hello-world without Typescript and with Groceries and both works.

What are happening? Thanks :)

**Comment by enchev** [comment]
Hey @joanlopez,

Can you post more info about the NativeScript and TypeScript versions?

**Comment by joanlopez** [comment]
Nativescript@latest: 2.0.1
Typescript: 1.8.10

I'm getting started with Nativescript so I think that all version are the most recent.

Thanks!

**Comment by Alexisvt** [comment]
Did you initialized your project to use typescript?
This is an example of how you can do it, `projectname` part will be the name of your project
```sh
tns create projectname --template typescript
```
that will install all the needed packages to run nativescript using typescript
If you did it, please run `tns doctor` to check any missing part. I noticed that you are using an old version of nativescript, try to update it using:
```sh
npm i -g nativescript
```

**Comment by thakurarun** [comment]
i got same issue and notice few things while testing on device
1. after successful build my device go offline.
2. my device has android 5.1 version which is compatible with max. sdk 22.
3. i notice in my AndroidManifest.xml file it is android:targetSdkVersion="23" which may be incompatible.

also all issues comes up after node upgrade to 5.1.0 and nativescript to 2.1.0

**Comment by dtopuzov** [comment]
@thakurarun can you post package.json of your app. We have some known issues if you combine {N} CLI 2.1.* with tns-android@2.0.* and tns-core-modules@2.0.*

**Comment by thakurarun** [comment]
here is my current json package:
```
{
  "name": "listit",
  "version": "1.0.0",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.listit",
    "tns-android": {
      "version": "2.1.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/platform-server": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "nativescript-angular": "0.2.0",
    "tns-core-modules": "^2.1.0"
  },
  "devDependencies": {
    "babel-traverse": "6.10.4",
    "babel-types": "6.11.1",
    "babylon": "6.8.3",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
}


```

**Comment by harlankoehn** [comment]
I'm having the same issue. I'm using the standard Android-SDK Emulator on Windows 7 with Android version 5.1.1. This issue just started for me in the last day and I'm not aware that I updated by NativeScript version, but maybe it got updated automatically after cloning a new project?

In looking into the issue, I can see that the .apk file actually gets pushed to my Emulator/Virtual Device. But the app never gets ran. The connection between the Emulator and the Command Window is still good as the Emulator still outputs errors to the Command Window.

My package.json is:

	{
	  "name": "MobileDir",
	  "version": "0.1.0",
	  "description": "NativeScript Application",
	  "license": "SEE LICENSE IN <your-license-filename>",
	  "readme": "NativeScript Application",
	  "repository": "<fill-your-repository-here>",
	  "nativescript": {
		"id": "co.villagemedia.mobiledir",
		"tns-android": {
		  "version": "2.1.1"
		}
	  },
	  "dependencies": {
		"@angular/common": "2.0.0-rc.3",
		"@angular/compiler": "2.0.0-rc.3",
		"@angular/core": "2.0.0-rc.3",
		"@angular/http": "2.0.0-rc.3",
		"@angular/platform-browser": "2.0.0-rc.3",
		"@angular/platform-browser-dynamic": "2.0.0-rc.3",
		"@angular/platform-server": "2.0.0-rc.3",
		"@angular/router-deprecated": "2.0.0-rc.2",
		"nativescript-angular": "0.2.0",
		"tns-core-modules": "^2.1.0"
	  },
	  "devDependencies": {
		"babel-traverse": "6.10.4",
		"babel-types": "6.11.1",
		"babylon": "6.8.2",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.3.2",
		"typescript": "^1.8.10"
	  }
	}

**Comment by joanlopez** [comment]
The `tns doctor` only shows the Nativscript update, nothing else.

I've updated nativescript to the latest version but anything happens.

I've tried creating a project with `tns create projectname --template typescript` and it works.

The project that doesn't work was created with the `tns create projectname --ng` as explained in the docs.

Which is the right command to create an empty project with the Angular 2 & Typescript?

Many thanks! =)

**Comment by Alexisvt** [comment]
According with [nativescript blog](https://www.nativescript.org/nativescript-is-how-you-build-native-mobile-apps-with-angular) is 
```sh
tns create my-angular-app --ng 
```

**Comment by joanlopez** [comment]
When I create with this command `tns create my-angular-app --ng`, it doesn't work.

Everything is fine with the other creation commands.

Thanks!

**Comment by enchev** [comment]
Hey @vakrilov,

Do you know what can cause such issue with Angular projects?

**Comment by vakrilov** [comment]
One possible reason could be that the NG template pushes more files to the device/emulator, because of all the angular dependencies.

**Comment by joanlopez** [comment]
@vakrilov Why pushing all of these files produces the app does not work? It don't seems reliable..

**Comment by enchev** [comment]
Hey @joanlopez,

We unable to replicate such behavior locally so far. Do you still have the same problem?
