### ISSUE TITLE
tns run ios --emulator fails with "Class.getClass cannot identify the unidentified class:  <Buffer@0x0 >  pointer: 0"

### ISSUE THREAD

**Issue by pep108** [NativeScript/nativescript-cli#1894]
This error seems to be undocumented. I've tried uninstalling NativeScript and reinstalling, updating config and still having the same problem. Running the ios emulator was working fine until I upgraded tns-core-modules.

Running:
OSX 10.10.2
xcode v6.3.1
node v5.6.0
nativescript @2.1.0
tns-core-modules @2.1.1
tns-ios @2.1.0

Any help is greatly appreciated. The best I am able to trace this down right now is to the definition of getClass in tns-core-modules/utils/types.d.ts

**Comment by enchev** [comment]
Hey @jasssonpet,

Do you know if this is something related to the iOS runtime?

**Comment by pep108** [comment]
I'm not sure, but it is very possible. The problem surfaced sometime after I came across the ios-runtime package and installed cmake31, automake and libtool because the iOS emulator was booting up, but was failing with livesync. 

The ios-runtime requirements do indicate that my OS and Xcode versions are not supported. I'm in the middle a back up before updating to El Capitan and Xcode 7.3.1. Will report back whether this fixes the issue or not.

**Comment by pep108** [comment]
UPDATE -
Upgraded to El Capitan, installed Xcode 7.3.1 and everything is back to working, including livesync

**Comment by mrac** [comment]
Is there any change this bug will be fixed for X 10.9 and Xcode 6.2 ?

The docs for ```tns emulate ios`` says:

> The version of Xcode must be compatible with the ios-sim-portable npm package on which the NativeScript CLI depends. For more information, visit https://www.npmjs.org/package/ios-sim-portable.

ios-sim-portable docs says:
> System Requirements:
OS X 10.9.4 or later
Xcode 5.0 or later
