### ISSUE TITLE
Move verifying CocoaPods step from npm install to tns plugin install

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#1897]
There is no need to wait for this step if you don't have pods in your project.
Also the check could probably be improved - now it downloads the latest official runtime and try to build it. I think there should be faster check.

**Comment by dtopuzov** [comment]
Not sure where you will move it, but after installation we should run doctor and doctor should run Cocoa Pod verification (if OS is OSX).

**Comment by hshristov** [comment]
@dtopuzov `tns plugin install` sounds way more appropriate to me. I don't want to wait for checks that are not needed in my project. If `tns doctor` is fast enough - OK if it does the same slow check for `Verifying CocoaPods` I don't want it after `npm install -g nativescript`.

**Comment by dtopuzov** [comment]
We agreed `tns install` is the right place to verify cocoa pods.
