### ISSUE TITLE
console.log(); not working when using over USB (Windows 10 | Android)

### ISSUE THREAD

**Issue by Voakie** [NativeScript/nativescript-cli#1898]
Hello,

it seems like when I'm testing an app over USB on my Android device, the log statements won't show up. Plus my computer doesn't support the emulator (yay) so I'm stuck to the USB method.

I looked everywhere but didn't seem to find a solution. Thanks in advance!
(Tried both `tns run android` and `tns livesync android --watch`)

**Comment by NickIliev** [comment]
Hi @Voakie is your app deploying on your device!? If you have the sample project that you can share it will help us investigate your issue and give you instructions on how to handle it.
If you app is running on your USB connected device can you try logging a message before any other code is executed (for example in app.js before **_start_**)

As for you emulator issue - Are you trying to use the 'state' emulator or Genymotion?(I recommend the second option) .If you are using Genymotion, then you should have your emulator image started before deploying your app .Also, you can see if you have connected devices with
```
tns device
```

**Comment by Voakie** [comment]
Right, my fault. I included the console.log command inside a function taht i didnt even call...

Thanks!
