### ISSUE TITLE
Invalid APK / NativeScriptActivity does not exist.

### ISSUE THREAD

**Issue by moraskillermo** [NativeScript/nativescript-cli#1899]
`/data/local/tmp/testapp-debug.apk\r\r\nFailure [INSTALL_FAILED_INVALID_APK]\r\r\n',
  stderr: '',
  exitCode: 0 }
Successfully deployed on device with identifier '1514b4ce'.
spawn: C:\Users\Guillermo\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb "-s" "1514b4ce" "shell" "am" "start" "-a" "android.intent.action.MAIN" "-n" "org.nativescript.testapp/com.tns.NativeScriptActivity" "-c" "android.intent.category.LAUNCHER"
Result when throw error is false:
{ stdout: 'Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.nativescript.testapp/com.tns.NativeScriptActivity } \r\r\nError type 3\r\r\nError: Activity class {org.nativescript.testapp/com.tns.NativeScriptActivity} does not exist.\r\r\n',
  stderr: '',
  exitCode: 0 }
spawn: C:\Users\Guillermo\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb "-s" "1514b4ce" "logcat" "-c"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: C:\Users\Guillermo\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb "-s" "1514b4ce" "logcat"`

So far, this has happened with every NativeScript project I've created, without modifying any files at all. My android version is 4.4.4 and I'm able to see the NativeScriptActivity.java file on \platforms\android\src\main\java\com\tns, so I don't understand where the issue is. Any clue? Thanks in advance.

**Comment by dtopuzov** [comment]
@moraskillermo please provide more details.
{N} CLI version
Android platform version
tns-core-modules version
App type -> js, ts, angular
Exact steps to reproduce

**Comment by moraskillermo** [comment]
NativeScript version: 2.0.1
Android platform version: 19

Steps to reproduce:
tns create testapp
tns run android

**Comment by theluk** [comment]
same here 

{N} cli 2.0.1
Android Api 19
tns-core-modules version: 2.1.0

steps.
tns create my-app-name --ng
tns run android --log trace

/data/local/tmp/client-debug.apk\r\n[100%] /data/local/tmp/client-debug.apk\r\nWARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.\r\r\n\tpkg: /data/local/tmp/client-debug.apk\r\r\nFailure [INSTALL_FAILED_INVALID_APK]\r\r\n',
  stderr: '',
  exitCode: 0 }
Successfully deployed on device with identifier 'emulator-5554'.
spawn: C:\Users\Lukas\AppData\Local\Android\android-sdk\platform-tools\adb "-s" "emulator-5554" "shell" "am" "start" "-a" "android.intent.action.MAIN" "-n" "org.nativescript.client/com.tns.NativeScriptActivity" "-c" "android.intent.category.LAUNCHER"
Result when throw error is false:
{ stdout: 'WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.\r\r\nStarting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.nativescript.client/com.tns.NativeScriptActivity }\r\r\nError type 3\r\r\nError: Activity class {org.nativescript.client/com.tns.NativeScriptActivity} does not exist.\r\r\n',
  stderr: '',
  exitCode: 0 }

**Comment by theluk** [comment]
an update from {N} cli 2.0.1 to 2.1.0 AND a complete new `tns create ...` fixed the issue for me

**Comment by dtopuzov** [comment]
Yes, we have some significant changes that might cause such issues if you use tns-core-modules@2.1.0 with tns-android@2.0.0 and nativescript@2.0.0.
We can confirm it is ok if everything is 2.0.* or everything is 2.1.*
