### ISSUE TITLE
Enhancement: TNS Doctor Android tools detection

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1906]
Apparently TNS Doctor is unaware that you need Build tools v23.0.3 when doing Android projects.  If you upgrade from 2.0 (or earlier) you may not already have the 23.0.3 build tools and so TNS will fail to build application with some really weird errors...

Can we make sure that tns doctor tests to verify all the components for android that are needed are present?

**Comment by Daxito** [comment]
+1
