### ISSUE TITLE
Livesync .xml .css and .js files not reloading

### ISSUE THREAD

**Issue by caleb0** [NativeScript/nativescript-cli#1907]
Hello,

I'm having some trouble getting Livesync to work consistently.
It will only update on the device the first time it is saved/changed, and the following changes are not updated. **Not even if javascript is saved and the app is reloaded, does the xml changes display.**

However, I know that it's actually saving because if I stop livesync and just "_tns run android_", all the changes are there.

I have tried running it in
1. Android AVD emulator (Intel image) 6.0
2. Physical device (Nexus 5X) 6.0
3. Genymotion (Nexus 5X) 6.0

**Config**
Ubuntu 16.04 LTS
tns --version: 2.1.1
Atom code editor

Also reinstalling Nativescript as was suggested [here](https://github.com/NativeScript/nativescript-cli/issues/1621) did not work.

This issue aside, Nativescript is a truly awesome framework and the devs are doing a great job :+1: 

Thanks.

**Comment by NickIliev** [comment]
Issue confirmed under Android with N 2.1.1
Steps to reproduce
```
tns create myApp
tns livesync --watch android
```

Then make some changes in **xml** or **css** file. 
The app will reload with success message but
will not load changes occasionally.

```
Executing before-prepare hook from D:\issues\NativeScript-CLI\issue_1907\hooks\before-prepare\nativescript-dev-typescript.js
Project successfully prepared
Transferring project files...
Successfully transferred main-page.xml.
Applying changes...
Successfully synced application org.nativescript.issue1907 on device 192.168.206.101:5555.
```

sample project here : [https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript-CLI/issue_1907](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript-CLI/issue_1907)

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/nativescript-cli/issues/1872
