### ISSUE TITLE
Debugging on iOS cannot find application

### ISSUE THREAD

**Issue by vanka78bg** [NativeScript/nativescript-cli#1908]
Steps to reproduce:
```
tns create Test
cd Test
tns platform add ios
tns debug ios
```
With the last command CLI builds, deploys, starts the app on the device and tries to attach the debugger. The problem is that it cannot find a debuggable app on the device, even though the app is up and running. Here is the error message that occurs in the output:
```
The application org.nativescript.Test does not appear to be running on
<device name> or is not built with debugging enabled.
```
However the following commands work:
```
tns deploy ios
tns debug ios --start
```
It seems that deploying manually and attaching the debugger works just fine. The problem is it is not possible to debug code that have already been executed on application startup.

**Comment by NickIliev** [comment]
Hi @vanka78bg 

I have followed your exact steps but was **not** able to reproduce this behaviour.(tne NativeScript inspector is up and running, the app is up and running, you can debug it)
Can you give us more details on your environment settings. (version of NativeScript)

**Comment by vanka78bg** [comment]
@NickIliev Glad you have closed this without even contacting me. :smile: Please, test on a real device, not just in the emulator. Tested with iOS 8.1 tablet - reproducible 100% of the time. Here is a short video, demonstrating what happens: https://drive.google.com/file/d/0B1k8WYiUfYQ8V3FJc2FKem0zazg/view?usp=sharing
