### ISSUE TITLE
Improve diagnostics

### ISSUE THREAD

**Issue by slavchev** [NativeScript/nativescript-cli#1913]
To debug Android builds it is required to set different `gradle` flags. Currently the `tns` command does not support parameter forwarding. We can provide a general `tns` option for that purpose. For example

```
tns build android --gradle="--debug --no-rebuild -Pmyprop=myvalue"
```

**Comment by rosen-vladimirov** [comment]
Closing this in favor of https://github.com/NativeScript/nativescript-cli/issues/19
