### ISSUE TITLE
NativeScript debugger encountered Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use".

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/nativescript-cli#1916]
I get this error when trying to start debugging using the iOS emulator:

NativeScript debugger encountered Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use".

Versions:
El Capitan 10.11.5
XCode 7.3.1
NativeScript 2.1.1

What else can I get you?
Thanks,
Alex

**Comment by enchev** [comment]
Hey @alexziskind1,

Do you get this error every time when you run the debugger?

Hey @vchimev @dtopuzov @SvetoslavTsenov can you confirm this?

**Comment by alexziskind1** [comment]
@enchev - I got this error EVERY time I ran debug and whether I started the app in debugging or attached to it. This also happens on two of my Macs- a MacBookPro and an iMac. After I restarted the machine, the problem went away.

**Comment by enchev** [comment]
Hey @alexziskind1,

We believe that this was caused by the fact the both iOS and Android debuggers were using the same port. We resolved this recently here:
https://github.com/NativeScript/nativescript-cli/pull/1902

**Comment by alexziskind1** [comment]
@enchev I hope that fixes it. However, I want to add that when I get this error, I am not running the android emulator, just the iOS simulator alone. Also, I haven't restarted my other machine (iMac) and still getting the error on that one. Let me know if there is some kind of trace or something I can do that can help diagnose.

**Comment by enchev** [comment]
Can you pull our master branch, use it instead the official CLI and let us know if you still have the same problems?

**Comment by alexziskind1** [comment]
Sure. Can you point me to a set of instructions on how to do that?

**Comment by enchev** [comment]
Here is it: https://github.com/NativeScript/nativescript-cli#how-to-build

**Comment by alexziskind1** [comment]
Can of worms :)
I get stuck at this step with an error:

```
$ git submodule update --init
Submodule 'lib/common' (git@github.com:telerik/mobile-cli-lib.git) registered for path 'lib/common'
Cloning into 'lib/common'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:telerik/mobile-cli-lib.git' into submodule path 'lib/common' failed
```

I also tried using ```sudo``` with the same results

**Comment by ErjanGavalji** [comment]
@alexziskind1
Alex, this error is typical when you don't have an [SSH key setup](https://github.com/settings/keys) and the submodule is added via the [smart git protocol](https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols#The-Smart-Protocol)

Can you try setting one up?

Cheers,
Erjan

**Comment by alexziskind1** [comment]
Thanks @ErjanGavalji 
I've successfully built v2.2.0 from the master repo
The first run of the debug command resulted in the same error.
Then I reset content and settings of the simulator and quit the program. I deleted the platforms folder. I executed the ```../nativescript-cli/bin/tns debug ios --emulator``` command again, but I get the same error.

**Comment by alexziskind1** [comment]
```
Frontend client connected.
Backend socket created.
Jul 13 10:10:15 --- last message repeated 1 time ---
Jul 13 10:10:15 Alexander-Mac testdebug[75521]: NativeScript debugger encountered Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use".
Jul 13 10:10:16 Alexander-Mac backboardd[75471]: SecTaskCopyDebugDescription: testdebug[75521]
Jul 13 10:10:16 Alexander-Mac backboardd[75471]: SecTaskCopyDebugDescription: testdebug[75521]
Jul 13 10:10:16 Alexander-Mac backboardd[75471]: SecTaskCopyDebugDescription: testdebug[75521]
Jul 13 10:10:16 Alexander-Mac backboardd[75471]: SecTaskCopyDebugDescription: testdebug[75521]
Jul 13 10:10:16 Alexander-Mac backboardd[75471]: SecTaskCopyDebugDescription: testdebug[75521]
Jul 13 10:10:16 Alexander-Mac testdebug[75521]: assertion failed: 15F34 13B137: libxpc.dylib + 71730 [D938B614-A290-3D25-8032-8DEF8A01913A]: 0x7d
Frontend socket closed!
```

**Comment by enchev** [comment]
Hey @SvetoslavTsenov @vchimev can you check this?

**Comment by dtopuzov** [comment]
Still can not reproduce.

@alexziskind1 can you try "tns debug ios --emulator --log trace" and post the log (may be part after *** BUILD SUCCEEDED *** will be enough).
--log trace will show the port used by debugger and you can check if something else also try to use this port. 
--log trace will also give us info for tns-ios-inspector package which is important part for debugging. It might happen that you use latest {N} CLI, runtime and modules, but inspector is old. If that is the case clean npm cache might solve the problem.

**Comment by alexziskind1** [comment]
Unfortunately my machine restarted due to a power outage so I lost the ability to reproduce.
