### ISSUE TITLE
"tns platform add android"  command is not working

### ISSUE THREAD

**Issue by subhamdas88** [NativeScript/nativescript-cli#1917]
$ tns platform add android
Copying template files...
ENOENT: no such file or directory, scandir 'D:\Projects\nativejs\demo1\platforms\android\src\main\res'

**Comment by Anilinfo2015** [comment]
Can you please try running  $ tns doctor
I faced same or more dangerous issue like this with nativescript and these commands were very slow.
It took me two week to do the same.

Try to delete platforms/ folder from project root and try again if tns doctor said no issue.
