### ISSUE TITLE
project build successfully, but nothing happen

### ISSUE THREAD

**Issue by Anilinfo2015** [NativeScript/nativescript-cli#1919]
I am trying to run 

$tns run android --emulator

Project build successfully. but nothing happen.

It successfully started emulator also but then i get this message

```
:config phase:  createDefaultIncludeFiles

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: C:\1Projects\NS Web\workstation\ns-mobile\platforms\
android\libs\aar\widgets-release.aar
:deleteMetadata
:deleteFlavors
:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 23.072 secs
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)
```

**Comment by enchev** [comment]
Hey @Anilinfo2015,

Any more info about your environment will be helpful.

**Comment by NickIliev** [comment]
Issue resolved after updating npm and NativeScript. (as logged [here](http://stackoverflow.com/questions/38303969/nativescript-project-build-successfully-but-nothing-happen?noredirect=1#comment64026428_38303969))

**Comment by Anilinfo2015** [comment]
Thanks guys.
