### ISSUE TITLE
API Notifications

### ISSUE THREAD

**Issue by unlight** [NativeScript/nativescript-cli#192]
Not sure, that is right place for issue.
But I found nothing about notifications [ApiReference][1].
Will it be available in future version of NativeScript?

[1]: https://github.com/NativeScript/docs/tree/master/ApiReference

**Comment by ligaz** [comment]
Hi unlight,

Can you please elaborate what kind of Notification API you are expecting? I guess you are talking about Push Notifications and Local Notifications.

**Comment by unlight** [comment]
I mean something like this
![example](http://www.vogella.com/tutorials/AndroidNotifications/images/xnotification10.png.pagespeed.ic.fmc6zyoaDS.png)
http://www.vogella.com/tutorials/AndroidNotifications/article.html

**Comment by ligaz** [comment]
This issue was moved to NativeScript/cross-platform-modules#260
