### ISSUE TITLE
Please, improve cli, we (developers) are using it!

### ISSUE THREAD

**Issue by lordgreg** [NativeScript/nativescript-cli#1930]
Hi NS team!

I really love the effort you put into the NS. Even better, to include the ng2 into it and stay up-to-date with latest ng2 rc4 improvements (including new router!), however, starting the project, here is one big big issue I'm having:

Until today, I've never ever saw transpiler/cli/compiler for OOP to generate files and put them in the same folder structure as the sources. 

Its really, really bad and I don't even know why aren't you (if you're using babel or typescript transpiler itself) just putting everything in `/dest/` folder of some kind? Please, don't make us rely on editor, which should ignore or hide specific files from project folders.  Just create webpack/browserify/gulp system with watchers of src folder to watch any other files that aren't *.ts and copy them to /dist. As for the ts, transpile them on the same location and you're done. 

Please, don't make a workspace mess with "compiled" js files being in the same folder as the "source" files. 

Do something about that, don't make the mistake on user having to rely on IDE's.

Thank you.

:+1:

**Comment by enchev** [comment]
Hey @lordgreg,

TS files are needed for debug and when you build your project with `--release` you will not have these files.

**Comment by lordgreg** [comment]
@enchev thank you for your reply. However, you totally missed the point of my opened issue. Seeing that kind of replies without any other additional info just points to the status of Nativescript itself. Yep, it's young, its good for hello world, but you can forget about enterprise solutions. 

Thank you again for replying.
