### ISSUE TITLE
"Too many files open on system" error during iOS build

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/nativescript-cli#1931]
Since upgrading to NativeScript 2.1, I am intermittently (but frequently) getting errors late in the iOS build process that cause the build to fail. The final error code is usually this:

```
The following build commands failed:
	CpResource invisiblecontrollernative/app build/emulator/invisiblecontrollernative.app/app
(1 failure)
Command xcodebuild failed with exit code 65
```

BUT, inspecting the build output, it _seems_ this error is occurring when "Too many files open on system"  appears in the XCode build. Example:
```
xcodebuild[5273:35213102] unable to create temporary file at /Users/toddanglin/Documents/git/invisiblecontroller-native/platforms/ios/build/invisiblecontrollernative.build/Debug-iphonesimulator/invisiblecontrollernative.build/dgph-vSRO73IR: Too many open files in system
```
I never encountered these build errors prior to 2.1. Given the late stage of the build process, I do wonder if the new AssetCatalog (and related files) is somehow contributing.

As I said, this is intermittent, so it can usually be resolved by just retrying a build. Unfortunately, that makes it harder to debug. :/ Flagging here in case others have begun to hit this problem so we can triangulate a root cause.

**Comment by enchev** [comment]
Hey @PanayotCankov @tzraikov  do you know what can cause this?

**Comment by tzraikov** [comment]
Hmm, we haven't observed this one. I will try to reproduce it. @toddanglin, can you specify the exact cli command that you are executing when the issue occurs? Are you using angular or typescript in your project?

**Comment by tzraikov** [comment]
As @rosen-vladimirov pointed out, this could be related to some settings on your local machine. If you have for example too many projects open, or if you changed the default maximum number of open files. The issue is discussed here:

http://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

The default limit is 10,240 per process. You can increase the limits (at your own risk) with:

sysctl -w kern.maxfiles=20480 (or whatever number you choose)
sysctl -w kern.maxfilesperproc=18000 (or whatever number you choose)

**Comment by tzraikov** [comment]
I will check whether {N} opens a large number of files somewhere. I shouldn't happen.

**Comment by toddanglin** [comment]
@tzraikov Thanks for the input.

My setup is pretty vanilla. Using OS X (10.11.5 El Capitan) on a Mac Pro 12GB RAM -- all default system settings (as far as `maxFiles` goes).

To ensure it's not something related to crazy multi-tasking, I have tried to ensure only the current active {N} project is open in VS Code -- minimum number of other apps/files open. It is a TypeScript project, FWIW.

My two biggest hunches:
- It's related to the AssetCatalog step (since that's the last thing I see in the build output before the "Too Many Files Open" error)
- It's related to one or more NativeScript CocoaPod plugins, that are loading a bunch of files for XCode to build (maybe too many native plugins in the build process?)

Either way, as I said, it's intermittent. If it fails once with this error, immediately re-running `$ tns emulate ios` or `$ tns deploy ios` will often fix it. Sometimes. :) If you find any possible fixes, let me know. I will update this issue if I can narrow down the root cause, too.

**Comment by jlooper** [comment]
I had about a day and a half of horror with my emulator failing dreadfully. I think it has to do with the need to free up space. I did that, and rebooted, and am back to building again. :( no fun while it lasts.

**Comment by dtopuzov** [comment]
@toddanglin is it a public project or something you can send us for testing. 
I hit this problem once, but can not reproduce it now.

**Comment by toddanglin** [comment]
@dtopuzov Unfortunately, it's not (yet) a public repo, but I'll see if I can create a new test project that more consistently reproduces the issue.
