### ISSUE TITLE
Enhancement: TNS create <project> --template <xyz> has issues...

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#1932]
Since I make a bazillion plugins, I created a really cool template that automates a lot of the grunt work, however when you do a `tns create --template <pluginTemplate>` - TNS totally messes up my all new tns plugin project and really destroys it's usability.    

Can we make it so that if I have a flag in the template package.json like {"cleanTemplate": "true"} that the tns will not start messing with things it doesn't understand.  ;-)   Or if you MUST install all that crap; please put it into the "demo" folder (if the demo folder exists in the template); as that is where the actual demo project will resides.   I have no problem automating the install of the demo folder; but man it is a serious pita to work around tns's attempt to destroy my cool new plugin...

**Comment by enchev** [comment]
Hey @NathanaelA,

Can you clarify how exactly {N} CLI destroys your plugin?

**Comment by NathanaelA** [comment]
Ok, so here is what my tns-template-plugin looks like:
> package.json
> .npmignore
> README.md
> LICENSE
> index.js
> postinstall.js

When I run it; this is what happens:

> app/
> app/App_Resources/*
> app/**.npmignore**
> app/**index.js**
> app/**LICENSE**
> app/**package.json**
> app/**postinstall.js**
> app/**README.md**
> node_modules/tns-core-modules/*
> node_modules/tns-core-modues-widgets/*
> platforms/
> package.json

Now my expectations would be that template installs AS-IS no additional files, and my plugin files wouldn't get stuck inside and app folder.     That is what I mean by it destroys my plugin, the output of the template is totally unusable for plugin development...

Also because of the way tns works; my post-install scripts runs BEFORE your changes; so it makes it really difficult for me to actually "undo" all the damage that it does.   It would be really awesome if tns could have a "post-tns" script step so that I can run some final cleanup after the plugin is installed in the final location.

**Comment by NathanaelA** [comment]
I'm closing this because I think #1945 is a better way to state what I need and why I need it.   I wrote this one right after discovering how tns destroyed my cool plugin template.  So it is a bit more snarky.  :-)
