### ISSUE TITLE
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by stephenfeather** [NativeScript/nativescript-cli#1948]
├─┬ nativescript@2.1.1
│ ├─┬ gaze@1.0.0
│ │ └─┬ globule@0.2.0
│ │   ├─┬ glob@3.2.11
│ │   │ └── minimatch@0.3.0
│ │   └── minimatch@0.2.14

This is a flaw inherited from dependancies. gaze was updated to 1.1.0 on Apr 27th, globule updated a month ago (Jun 22) to upgrade minimatch

**Comment by rosen-vladimirov** [comment]
Hi @stephenfeather , 
Thanks for reporting this. I've submitted a PR for updating some of the dependencies, including gaze. However the warning for minimatch version is still in the output as there's no new version of broccoli dependency. Also at the moment we can use only a specific version of node-inspector, which depends on old version of minimatch.
