### ISSUE TITLE
Xcode8/iOS10 support

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#1959]
tns build i386 when deploy on simulator, we must build 64-bit architecture in this case.

Current result:
App works, but you see warning in Simulator that this app is not optimized (only first time you start the app).

Notes: When build via Xcode8-Beta there are no issues with architectures.

**Comment by jasssonpet** [comment]
@dtopuzov What application are you testing with. Does  https://github.com/NativeScript/NativeScript/issues/2456 reproduce?

**Comment by dtopuzov** [comment]
https://github.com/NativeScript/template-hello-world
