### ISSUE TITLE
Nativescript - Livesync - When XML file is modified - Android emulator does not reload

### ISSUE THREAD

**Issue by tonyawad88** [NativeScript/nativescript-cli#1962]
Hello,

Sorry I am new to nativescript but I noticed that when I make a change in my IDE to any of the xml files it doesn't reload the new modified version of the app.

1. Running TNS Doctor shows me that "No issues were detected."
2. I ran the ```tns livesync android --emulator --watch``` to start the emulator and it still running
3. When a change occurs I get:
```
"Applying Changes...."
Successfully synced applicatoin..... on device emulator...
```
However no changes happens in the emulator.

The emulator settings are: 
* Android 7.0
* Platform 7.0
* API Level 24
* CPU Intel Atom x86

I have tns version 2.1.1. 

I tried removing it with npm remove -g nativescript, cleared cache npm cache clean and reinstalled and still having this problem.

Any suggestions ? Sorry I opened a new issue cause I couldn't find a solution in the other ones.

Thank you !!

**Comment by m-abs** [comment]
It's a bug in nativescript-cli, you can try this quickfix: https://github.com/NativeScript/nativescript-cli/issues/1872#issuecomment-234461196
