### ISSUE TITLE
Unable to deploy NativeScript demo app to android emulator by "tns run android --emulator"

### ISSUE THREAD

**Issue by MaxySpark** [NativeScript/nativescript-cli#1967]
I cloned the **sample-Groceries** repo
and when I try to run the project by `tns run android --emulator`

I always get this error and app does not deploy to the emulator 
![issue](https://cloud.githubusercontent.com/assets/8802860/17270998/4edecf8c-568d-11e6-9dfc-6180f5f3d7cf.jpg)

In Emulator
![issue2](https://cloud.githubusercontent.com/assets/8802860/17271000/4ee49be2-568d-11e6-8ed8-6c2de126e7d2.JPG)

**Comment by donangel** [comment]
Have you tried to increase the timeout, as it suggests?

There's quite high probability the emulator startup to be too slow and the script to timeout, while waiting?

I'd also suggest trying Genymotion, in case this does not work.

**Comment by donangel** [comment]
Also, bear in mind that the support channel has moved to StackExchange: http://stackoverflow.com/questions/tagged/nativescript

Maybe you'll get better and quicker answer there?

**Comment by MaxySpark** [comment]
I installed genymotion emualtor and delete node_modules folder and run it by `tns emulate android --geny <geny device name>` and it is working
