### ISSUE TITLE
Calling method onSingleTapUp failed

### ISSUE THREAD

**Issue by usanyo** [NativeScript/nativescript-cli#1979]
Hi,
I'm new at native script development. I'm working on an android application, and I got an error message. It occured several times. I don't know how can I reproduce, sometimes when I click in the app, it happens. I think, it is a native script issue.

I tried only on android emulator.

![bug0](https://cloud.githubusercontent.com/assets/11265863/17402372/e7527f58-5a8d-11e6-97ad-ecec42770cdf.png)
![bug1](https://cloud.githubusercontent.com/assets/11265863/17402373/e757a7d0-5a8d-11e6-9a68-5d02561bf56c.png)

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#525
