### ISSUE TITLE
Npm Error when running `tns prepare ios` with github package dependency

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#1990]
_From @speigg on August 10, 2016 4:28_
### Tell us about the problem

After (successfully) installing a dependency directly from github via npm, `tns prepare ios` emits errors like this: 

```
npm ERR! install trying to install 1.0.1 to /Users/gspeiginer/<nativescript-app>/node_modules/nativescript-screen-orientation
npm ERR! install but already installed versions [ '1.0.1', '1.0.1' ]
nativescript-screen-orientation@1.0.1 node_modules/nativescript-screen-orientation
npm ERR! install trying to install 1.0.1 to /Users/gspeiginer/<nativescript-app>/node_modules/nativescript-screen-orientation
npm ERR! install but already installed versions [ '1.0.1', '1.0.1', '1.0.1' ]
nativescript-screen-orientation@1.0.1 node_modules/nativescript-screen-orientation
npm ERR! install trying to install 1.0.1 to /Users/gspeiginer/Code/<nativescript-app>/node_modules/nativescript-screen-orientation
npm ERR! install but already installed versions [ '1.0.1', '1.0.1', '1.0.1', '1.0.1' ]
```
### Which platform(s) does your issue occur on?

iOS , but probably not relevant
### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.1
- Cross-platform modules: 1.7.1
- Runtime(s): 2.1.1
### Please tell us how to recreate the issue in as much detail as possible.

You can try installing the same dependency I am using:
`npm install bionictk/nativescript-screen-orientation --save`

_Copied from original issue: NativeScript/NativeScript#2563_

**Comment by tsonevn** [comment]
Hi @speigg,

I reviewed the given scenario with latest modules and it seems to work as expected. In my opinion this issue is related to the old modules. You could try to upgrade you nativescritp using the described instruction [here ](http://docs.nativescript.org/releases/upgrade-instructions) and try to remove the plugin and add it again in your project. In regard to that you could also use `tns plugin remove <plugin_name>` and `tns plugin add <plugin_name>` to uninstall and install plugin in your project.

Let me know whether this helps.

**Comment by tsonevn** [comment]
_From @speigg on August 10, 2016 6:21_

I just tried updating `tns_core_modules` as you suggested, but that didn't affect the npm errors I am getting (as described above). It's definitely a CLI issue. My guess is that the problem has something to do with the way the nativescript CLI is using `npm` internally (I have npm v3 and node v6 installed).

**Comment by tsonevn** [comment]
Hi @speigg,

I tried to recreate the problem while using above described steps and node 6.3.1 and npm v3.10.3, however I was unable to reproduce such an issue. Could you try  to create new project `tns create <project_name> --template typescript` and to install the plugin with  `npm install bionictk/nativescript-screen-orientation --save`. Then try again to run `tns prepare ios`. If that doesn't help you could try to reinstall NativeScript  `npm uninstall nativescript -g` `npm install nativescript -g`.

I hope this will help

**Comment by speigg** [comment]
I followed your instructions and everything worked as it should in a brand new project. Nevertheless, it continues to generate errors with my original project. Even reinstalling nativescript as you suggested didn't fix the problem. Not sure what else the problem could be. 
--- HOLD ON --- 
I just tried one last ditch thing and I was able to reproduce the problem in the new project!

I have no explanation for this, but I can definitively say now that the errors I am seeing are caused the following two dependencies together:
```
npm install bionictk/nativescript-screen-orientation --save
npm install @types/openpgp --save 
```

Either of these, alone, does not cause errors to appear. Wow, that was hard to catch. I hope you can reproduce this now.

**Comment by speigg** [comment]
Btw, the biggest negative effect of this bug is that it causes `tns prepare ios` to reevaluate, prepare, and install plugins every time, drastically slowing down the development cycle. In other words, I see the following every time I run `tns prepare ios`, even if nothing has changed. 

```
Executing before-prepare hook from /Users/gspeiginer/Code/argon-project/argon-app/hooks/before-prepare/nativescript-dev-typescript.js
Successfully prepared plugin argon-web-view for ios.
Successfully prepared plugin nativescript-screen-orientation for ios.
Successfully prepared plugin nativescript-vuforia for ios.
Successfully prepared plugin speigg-nativescript-geolocation for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
Fetching podspec for `Vuforia` from `../../node_modules/nativescript-vuforia/platforms/ios/Vuforia`
Downloading dependencies
Using Vuforia (5.5.9)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

And if I remove either of the two specific dependencies which are causing the problem from my `package.json`:
```
"@types/openpgp": "0.0.27",
"nativescript-screen-orientation": "github:bionictk/nativescript-screen-orientation",
```

Then `tns prepare ios` is able to finish quickly again (when nothing has changed since the last prepare)

**Comment by speigg** [comment]
My workaround for now is:
1) remove `"@types/openpgp": "0.0.27"` from my dependencies
2) add a postinstall script `"postinstall": "npm install @types/openpgp"`

Hopefully that might help someone else until this is fixed.

**Comment by tsonevn** [comment]
Hi @speigg,
I followed the above described steps, however I was unable to reproduce such a problem. In my opinion this issue could be caused due some issues with `openpgp` plugin. Further more `openpgp` plugin  is  not officially supported in NativeScript . I could suggested you to use `nativescript-toolbox` plugin , which provides encrypting functionality. The better way to install plugin in your project is via `tns plugin add <plugin_name>`, which will download the right version of the  selected plugin and will notify you, whether this plugin has been supported in NativeScript.  Sample example:

`main-page.xml`

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Sample app" class="title"/>
  </StackLayout>
</Page>
```

`main-page.ts`

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import {sha256} from "nativescript-toolbox"


export function navigatingTo(args: EventData) {
    var page = <Page>args.object;
    console.log("encrypt test--------------------------------------------------");
    console.log(sha256("sample text"));
    console.log("encrypt test--------------------------------------------------");
}
```

About the other question, you could use `tns run ios`, which will make the prepare step automaticly, however this will rebuild the whole app. To save time you could also use `tns livesync ios` to start your project. You could read more about the command [here](https://docs.nativescript.org/tutorial/chapter-1#15-development-workflow).

Let me know whether this helps.

**Comment by speigg** [comment]
I'm not actually installing openpgp via npm.  Note that this problem appears when installing the scoped `@types` package for openpgp, not the openpgp package itself.  I am using openpgp for decryption and I have it installed via a global UMD script.

**Comment by speigg** [comment]
Okay, you should be able to reproduce the problem with `tns create <project_name> --template typescript` and the following `package.json`:

```
{
  "description": "NativeScript Application",
  "readme": "NativeScript Application",
  "nativescript": {
    "id": "org.nativescript.nativescriptnpmtest",
    "tns-ios": {
      "version": "2.2.0"
    }
  },
  "dependencies": {
    "@types/openpgp": "0.0.27",
    "nativescript-screen-orientation": "github:bionictk/nativescript-screen-orientation",
    "tns-core-modules": "2.2.0"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }
}
```

**Comment by speigg** [comment]
Just to prove that openpgp itself has nothing to do with the problem, it looks like I am able to reproduce the error with any `@types/X` package:

```
{
  "description": "NativeScript Application",
  "readme": "NativeScript Application",
  "nativescript": {
    "id": "org.nativescript.nativescriptnpmtest",
    "tns-ios": {
      "version": "2.2.0"
    }
  },
  "dependencies": {
    "@types/urijs": "^1.15.27",
    "nativescript-screen-orientation": "github:bionictk/nativescript-screen-orientation",
    "tns-core-modules": "2.2.0"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }
}
```

**Comment by tzraikov** [comment]
@speigg I was able to reproduce the issue. We are still not sure what causes it and that is why I can't offer a workaround.

**Comment by speigg** [comment]
Great. Glad you are at least able to reproduce the issue.

**Comment by Plamen5kov** [comment]
Hi @speigg,
I can't seem to reproduce your problem with the latest bits. Could you please try again an tell me if the issue still persists.

**Comment by pkoleva** [comment]
Closing this due to lack of response. We'll reopen it if necessary.
