### ISSUE TITLE
Cannot run tests in new app

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/nativescript-cli#2001]
Run these commands:

```
tns create appX2 --ng
cd appX2
tns test init # Select jasmine here
tns test android
```

Result:

![screen shot 2016-08-14 at 6 32 38 pm](https://cloud.githubusercontent.com/assets/5921642/17650117/9db97190-624d-11e6-85fb-b0959e7e51f5.png)

Environment:
- tns: 2.2.0
- OS: OSX El Capitain
- Emulator: Genymotion

**Comment by dtopuzov** [comment]
Already report: https://github.com/NativeScript/nativescript-cli/issues/1636
