### ISSUE TITLE
after updating to nativescript 2.1.1 (from 2.0) debug ios stopped working

### ISSUE THREAD

**Issue by huehnerhose** [NativeScript/nativescript-cli#2008]
Hi,

i updated my installed nativescript version to 2.1.1 via npm. I followed the instructions regarding upgrading my project in the documentation.
Now I am not able to run the ios debugger anymore. It transfers and starts the app in the emulator, shows the start-splashscreen, starts the debugger and stops there. No spinning loader in the debugger, app keeps showing the splashscreen. 
iOS run starts the app, debug/run with android emulator works fine. 
CLI output ends on:

    ** BUILD SUCCEEDED **

    Project successfully built.
    Starting iOS Simulator

    Setting up proxy...
    Press Ctrl + C to terminate, or disconnect.

    Frontend client connected.

I run tns 2.1.1, macOS Sierra Beta, CLI for XCode 8.0 beta6.

Any hints what I can to do get a clue why this doesn't work?

**Comment by dtopuzov** [comment]
Hi @huehnerhose we still do not officially support XCode 8.0 beta6. 
Current {N} release was tested against beta3. 
We will support beta6 (or new betas if such are available before end of the month) with our next release.

However you can try following:
Uninstall your current version of {N}, clean npm cache (npm cache clean) and then install {N} again.

**Comment by mnahkies** [comment]
@dtopuzov I'm getting the same issue as @huehnerhose only my system is running XCode 7.3.1

Downgrading to nativescript@2.1.0 fixes it for me.
