### ISSUE TITLE
ANDROID_HOME not found

### ISSUE THREAD

**Issue by kenanchristian** [NativeScript/nativescript-cli#2014]
Hi guys, I'm really new in nativescript, just tried to install it.
But everytime i do `tns platform add android`, i got this error :

> "The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android."

I can do `android` and `adb` command from any directory just fine. This is my tns doctor log:

[tns-doctor-trace.txt](https://github.com/NativeScript/nativescript-cli/files/438809/tns-doctor-trace.txt)

**Comment by dtopuzov** [comment]
You should setup ANDROID_HOME environment variable.
If everything is ok when you run ```echo %ANDROID_HOME%``` it should print the path to your home.

Alternative: When you run ```tns doctor``` and it fails you are prompted to run setup script. This scruipt should set ANDROID_HOME for you.

**Comment by kenanchristian** [comment]
@dtopuzov yes, it prints the right path to my ANDROID_HOME env var.
I also have done the setup script, here's the log.
[setup-script.txt](https://github.com/NativeScript/nativescript-cli/files/439253/setup-script.txt)

after that, i restarted my laptop, and tried to do `tns platform add android` but still got the same error :(

**Comment by dtopuzov** [comment]
hm, is it possible that somehow you set android home only for current shell.
Can you please try to call ```%ANDROID_HOME%\tools\adb``` just before ```tns platform add android```

**Comment by kenanchristian** [comment]
@dtopuzov this is what i got

`C:\Users\Christian Dimas\Desktop\hybrid-test\sample-Groceries>echo %ANDROID_HOME%\tools\adb
C:\Program Files(x86)\Android\android-sdk\tools\adb

C:\Users\Christian Dimas\Desktop\hybrid-test\sample-Groceries>tns platform add android
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
Sending exception report (press Ctrl+C to stop).....`

**Comment by kenanchristian** [comment]
fixed by installing android studio, and cleaning all the path on the environtment variable

**Comment by PhillipMwaniki** [comment]
I already have android studio installed and running but this issue still persists
Error is 
`The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.`

**Comment by dtopuzov** [comment]
Hi @PhillipMwaniki 

Can you run `echo %ANDROID_HOME%` if you are on Windows or `echo $ANDROID_HOME` if you are on Linux/macOS and paste the output.

Any additional info how you installed your environment is also welcome (via installer script or manually following some docs/tutorial).

**Comment by PhillipMwaniki** [comment]
![android_home](https://user-images.githubusercontent.com/2037708/36600728-21152e7a-18c4-11e8-84fe-3ce5d83eb5e7.PNG)
@dtopuzov There is the screenshot. I used the android studio installer and then set up the environment variables manually.
