### ISSUE TITLE
Lots of adb instances make my machine slow and use lots of resources

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/nativescript-cli#2015]
I've noticed that upon the first sync on android, `tns` will spawn an `adb` process for every file in the project (see the screenshot). Even though I'm running on a pretty powerful machine (quad core 3.8 GHz, 8 GB RAM, SSD), while those processes are running, my machine is unusable, even the mouse lags.

Would it be possible to transfer the files in batches, rather than all at once?

I'm using `tns` 2.2.1 on Win 10.

![untitled](https://cloud.githubusercontent.com/assets/5921642/18005580/a27d0146-6b4f-11e6-9609-1d3bf8fe2026.png)

Later edit: 

- the app is angular & typescript.
- Also the memory usage while those processes are running is ridiculos. It jumps from 130 MB to 4 GB:

![untitled](https://cloud.githubusercontent.com/assets/5921642/18005695/6d9ad52e-6b50-11e6-931c-8333e53942af.png)

**Comment by victorhurdugaci** [comment]
I'm also hitting the issue on OSX. Basically while the adb processes are running, the os reaches the max limit of processes it can run and you hit the issue described here: https://access.redhat.com/solutions/543503

While the adb processes are running, no new process can be created.

**Comment by rosen-vladimirov** [comment]
Hi @victorhurdugaci ,
All of these processes are in fact uploading of files on the device. There are two ways to upload files on Android device with `adb` - call `adb push <filename>` or `adb push directory <dirname>`. NativeScript CLI is trying to utilize both of the methods based on different cases. 
Basically we have an optimization to keep the shasums of all livesynced files on device. So when you have the application installed and you execute `tns livesync android`, NS CLI checks the current files in the project and the shasum file on the device. In case there's shasum file on the device (it's saved per application in the `/data/local/tmp` directory) the shasums of local files against the shasums persisted in the file on the device and uploads only the changed ones by calling simultaneously `adb push <file>`. In case there's no shasum file, NS CLI will call `adb push <directory>` which will be a single operation.
So what's causing the issue that you have faced - it looks like you had an application with the same id installed on the device and calling `tns livesync android` finds the mentioned shasum file on the device. As it's from different application (but with the same identifier), it contains files that are not part of your project. So NS CLI detects all angular files as new for the project and decides to upload them one by one (simultaneously). This instantiates a lot of adb processes.
One way to see this behavior is to do:
1) `$ tns create app1` (this will create application with identifier `org.nativescript.app1`)
2) `$ cd app1`
3) `$ tns run app1 --justlaunch`
4) `$ tns livesync app1 --justlaunch`
At this point remove the app1 from device (uninstall it) and create new project in different place on your machine, but use the same name:
1) `$ tns create app1 --template ng` (this will create application with identifier `org.nativescript.app1`)
2) `$ cd app1`
4) `$ tns livesync app1 --justlaunch` - this should reproduce the issue.

Can you confirm these are the steps with which you reproduce the problem? In case not, can you point the exact steps that lead to this behavior?

**Comment by XiaLeon** [comment]
> Basically

Hi Can I ask you a question by the way ? Do you know how many adb processes can be exist simultaneously on an OS like Windows ? I'm using Windows 7. Thanks a lot !

**Comment by XiaLeon** [comment]
Hi @rosen-vladimirov 
Can I ask you a question by the way ? Do you know how many adb processes can be exist simultaneously on an OS like Windows ? I'm using Windows 7. Thanks a lot !
