### ISSUE TITLE
tns test not ending process

### ISSUE THREAD

**Issue by hypery2k** [NativeScript/nativescript-cli#2017]
When running the following command:
```
tns test ios --emulator
```
the process is only ended within test failures, but if there are no errors, the process is never ended. In older docs the --single arg was mentioned, but within 2.2 this is not working.

Any suggestions?

Currently hack around with this:
```
 ( (sleep 120; ps -ef | grep emulator | grep -v grep | awk '{print $2}' | xargs kill -9) & exec tns test ios --emulator )
```

**Comment by rosen-vladimirov** [comment]
@hypery2k  have you tried using `--justlaunch` flag on your side?
By default all device related commands of NativeScript CLI will hold the console and print device logs. Passing `--justlaunch` will stop device logs printing and the process should exit.
Can you try it and see if it works?

**Comment by hypery2k** [comment]
just this works, thanks ;)

**Comment by rosen-vladimirov** [comment]
@hypery2k I'm glad it worked. I'm closing this issue now.
