### ISSUE TITLE
Android miss path image

### ISSUE THREAD

**Issue by eppisapia** [NativeScript/nativescript-cli#2023]
Hello

I'm doing a simple app just to show Images and working with a local images folder in the app folder.

Testing it on iOS haven't any trouble but on Android (Device using tns run android --device ID) it build the app but not show any image

This is how I declare the Image component and src

`<image src="~/images/1_Icons/recursos-04" height="30">`

Any clue what is happening?

**Comment by enchev** [comment]
Hey @eppisapia,

What's the image format? Is it PNG? Can you verify also if the the image is copied to the platforms/android folder?

**Comment by eppisapia** [comment]
hello @enchev 

It's PNG format.
Isn't copied at platforms. Im working with a local folder located at " MyProject/app/images/ " 

When use <image src="res://recursos-04" height="30"> to load from platform it working in both platform.

**Comment by eppisapia** [comment]
I solve it using "PNG" extension on source. ... with this I must say that Always the simple answer is the right one.

Thanks anyways for your support

regards

`<image src="~/images/1_Icons/recursos-04.png" height="30">`
