### ISSUE TITLE
Add support for Node.js 6.5

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#2025]
NativeScript CLI cannot be used with Node.js 6.5 without rebuilding its C++ dependencies. On most Linux and Mac OS X machines, the users have the required tools, so calling `npm install -g nativescript` will rebuild the binaries in case Node.js 6.5 is used. However rebuilding the dependencies on Windows requires Visual Studio. So NativeScript CLI's C++ dependencies have prebuilt binaries for all operating systems (for Linux and Mac OS X this will speed up the process of installation). The binaries are versioned based on the version of v8 included in Node.js. In Node.js 6.4, the version of v8 is 5.0.x, while in Node.js 6.5 the version is 5.1.x. 
So we need prebuilt binaries for the new v8 that's used.

**Comment by born2net** [comment]
As of current npm release still getting same error as of:
https://github.com/NativeScript/nativescript-cli/issues/2036
