### ISSUE TITLE
Create tns update command

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#2027]
Right now to do an upgrade we need to visit the docs to remember all the commands :)

Would be fantastic to just roll everything up into 
"tns update" and it'll do the platform remove\add, and update core modules all with one command

**Comment by firescript** [comment]
+1

**Comment by dtopuzov** [comment]
This command should actually do those steps:
````
rm -rf hooks
rm -rf platforms
rm -rf node_modules
tns platform remove (for all installed platforms)
tns platform add (for all installed platforms)
tns plugin remove tns-core-modules
tns plugin add tns-core-modules
```
Not sure what to do with 3rd party plugins, should we also update to latest version?

**Comment by SvetoslavTsenov** [comment]
Hey @tzraikov,
What about to add a check also for the package.json and if the version is lower than the released one to update project no matter if the platform is installed. So far as it is working fine but only if the platforms are already installed.
