### ISSUE TITLE
CocoaPods - env: ruby: Operation not permitted

### ISSUE THREAD

**Issue by KevinF813** [NativeScript/nativescript-cli#2029]
when I run tns doctor, I get a warning that there was a problem with CocoaPods.  I'm new to nativescript and was able to get my windows machine set up to run android, but I'm struggling to get my mac set up for ios.  Any help would be greatly appreciated.

this is what happens when I run **tns doctor**:

Installing iOS runtime.tns-ios@2.2.1 ../../var/folders/xt/dxd5rpt50psg7c3q23wcmnrm0000gn/T/nativescript-check-cocoapods11682-44457-2jcgpu/node_modules/tns-ios
  ◠ Verifying CocoaPods. This may take some time, please be patient..
 env: ruby: Operation not permitted

WARNING: There was a problem with CocoaPods
Verify that CocoaPods are configured properly.
There seem to be issues with your configuration

-----------------------------
My environment:
* OS X El Capitan v 10.11.6
* Xcode: v 7.3.1

**Comment by enchev** [comment]
Hey @KevinF813,

You may need to install ruby using homebrew like described here:
http://stackoverflow.com/questions/33015875/operation-not-permitted-usr-bin-update-rubygems
