### ISSUE TITLE
nativescript-google-maps-sdk Sandbox-exec error

### ISSUE THREAD

**Issue by eppisapia** [NativeScript/nativescript-cli#2039]
Hello,

After installing the library "native script-google-maps-sdk" (Follow the configuration guide) I get this error:

'Processing node_modules failed. Error: Command sandbox-pod failed with exit code 71 Error output: 
 sandbox-exec: /Users/synergyqa/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod: Operation not permitted'

I found out some old issues like this so I tried to solve this is:

- Change sandbox's permission but get same issue
- I read about change Ruby version to 2.1.1 or bellow but if I do im not able to use Cocoapods thats require 2.2.2 or further

How can I solve this or there is another way to use API GoogleMaps?

**Comment by wdulin** [comment]
I solved this problem by changing NativeScript to avoid using sandbox_exec. Find the config.json file in
and change "USE_POD_SANDBOX"  value to 'false'. Mine was in '/Users/$USER/.npm-packages/lib/node_modules/nativescript/config' but I have my npm global packages installed under my home directory.

**Comment by eppisapia** [comment]
@wdulin i'm not sure of this but isn't sandbox needed to use Api Key Authentication?

**Comment by wdulin** [comment]
My understanding is that the sandbox is used to protect against malicious Pod code. But then I am certainly no expert on building with CocoaPods. There is another thread here about this [1249](https://github.com/NativeScript/nativescript-cli/issues/1249).

**Comment by eppisapia** [comment]
Hey @wdulin

I did what you say, putting "USE_POD_SANDBOX=false" solve this issue.

Thanks you
