### ISSUE TITLE
"tns livesync android --watch" is dead slow

### ISSUE THREAD

**Issue by niranjan-reddy** [NativeScript/nativescript-cli#2042]
I am using tns 2.2.0 on my Windows 7 (intel i3, 4G RAM) machine and this command (or be the "tns run" command) takes like not less than 30 minutes to complete. It is too frustrating to work. On the other hand, my MacBook Air completes it in a few seconds to 1-2 mins (i7, 8G RAM). Note that I need to work on the Windows machine as it is my company supplied one.

I have tried almost all the options to boost the performance but in vain.

Supplied below is the command line trace...

Any suggestion?

======================================================
D:\NativeScript\sample-Groceries>tns --version
2.2.1

D:\NativeScript\sample-Groceries>tns livesync android --watch
Executing before-prepare hook from D:\NativeScript\sample-Groceries\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Project successfully prepared (android)
Executing before-livesync hook from D:\NativeScript\sample-Groceries\hooks\before-livesync\nativescript-angular-sync .js
Transferring project files...

======================================
I did not have any more patience to hold on to it and hence I killed the process (It took more than 30 mins at this point).

**Comment by dtopuzov** [comment]
Please run ```tns livesync android --watch --log trace``` and post logs.
