### ISSUE TITLE
[iOS] LiveSync suddenly stopped working ("Unable to kill the application")

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#2043]
_From @NordlingArt on September 8, 2016 11:22_

LiveSync (TNS 2.2.1) worked well earlier today. Went for a walk outside, came back and it now throws me this error:

```
Project successfully prepared (ios)
Transferring project files...
Successfully transferred all files.
Applying changes...
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.naSlideShow on device 7C3FA351-6853-469E-B51C-05098DFB430F.
Unable to kill the application.
```

It does launch the app but the terminal process closes after the error, so I cannot check any further logs. I have tried doing `tns platform remove ios` but still the same. I even tried "Reset Content and Settings..." in the iOS Simulator.

_Copied from original issue: NativeScript/NativeScript#2690_

**Comment by tsonevn** [comment]
Hi @NordlingArt,

Did you try to restart the terminal and then to start `tns livesync ios ` again. I case this doesn't help you could try the following steps:

1. remove platform `tns platform remove ios`
1. `tns plugin remove tns-core-modules`
3. `tns plugin add tns-core-modules`
4. delete the app from the Simulator or Device, where you have been tested the app .
5. run `tns livesync ios`

**Comment by NordlingArt** [comment]
@tsonevn - Thanks, this fixed it!

**Comment by NordlingArt** [comment]
@tsonevn - Actually that didn't solve the issue. Today the error reappeared and the solution you gave me doesn't fix it anymore. Any other ideas?
