### ISSUE TITLE
Getting an error with the CLI installation

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-cli#2046]
![image](https://cloud.githubusercontent.com/assets/10844009/18375622/983bd000-7675-11e6-8c5d-9c1289e81dc2.png)

**Comment by JaganJonnala** [comment]
Please anyone let me know what to do next with that

**Comment by NickIliev** [comment]
Hey @JaganJonnala 

Have you restarted your shell as pointed in the log message. The environment settings have been changed and in order for the setup to complete you need to restart your command prompt.

**Comment by JaganJonnala** [comment]
Thank you so much... I resolved issue
On Sep 9, 2016 7:56 PM, Nick Iliev <notifications@github.com> wrote:Hey @JaganJonnala 

Have you restarted your shell as pointed in the log message. The environment settings have been changed and in order for the setup to complete you need to restart your command prompt.
