### ISSUE TITLE
Cannot add platform to project

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#2047]
_From @TheLox95 on September 8, 2016 20:56_

## Problem
I have troubles running the `tns platform add android` command.
`Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-5404-6ee83dd8\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   48c6eda4b8a6b075a2b9f8a2eb59acd98dd57822
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz
`

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.1
- Cross-platform modules:   `2.2.1`
- Runtime(s): There is not any of these properties
- Plugin(s): `"dependencies": {
    "tns-core-modules": "2.2.1"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }
`

## Question
I just want to know if there is some error with my configuration or if it is an error with the server. Yesterday I update Nativescript so I do not know what is wrong.

_Copied from original issue: NativeScript/NativeScript#2694_

**Comment by tsonevn** [comment]
Hi @TheLox93,

I reviewed the problem and found that you could try to clear the npm cache using the following command `npm cache clean`. Then try again to add the platform for your project - `tns platform add android`.

In regard to the problem in case that above given suggestion doesn't help, could you run `tns platform add android --log trace` and sent us the output from console. It also would help if you give us info about the node and npm versions.

I hope this helps

**Comment by TheLox95** [comment]
Hello! I runned `npm cache clean` and then `tns platform add android` but had the same error.
`Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-2812-69f4f7ba\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   a5b11d6491ad301c8792646616a7e3d7687a6ac9
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz
`$ tns platform add android --log trace
execFile: C:\Users\Leonardo\AppData\Local\Android\android-sdk\platform-tools\adb "help"
execFile: C:\Users\Leonardo\AppData\Local\Android\android-sdk\platform-tools\adb "help"
spawn: C:\Users\Leonardo\AppData\Local\Android\android-sdk\platform-tools\adb "--help"
Socket {
  _connecting: false,
  _hadError: false,
  _handle:
   Pipe {
     _externalStream: {},
     fd: -1,
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread],
     reading: true },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events:
   { end: { [Function: g] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     close: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false },
  writable: false,
  allowHalfOpen: false,
  destroyed: false,
  bytesRead: 0,
  _bytesDispatched: 0,
  _sockname: null,
  _writev: null,
  _pendingData: null,
  _pendingEncoding: '' }
Exec npm -v
 stdout: 2.14.12

 stderr:
spawn: java "-version"
Exec node-gyp -v
 stdout:
 stderr: "node-gyp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Exec "C:\Users\Leonardo\AppData\Local\Android\android-sdk\platform-tools\adb" version
 stdout: Android Debug Bridge version 1.0.32
Revision 09a0d98bebce-android

 stderr:
spawn: C:\Users\Leonardo\AppData\Local\Android\android-sdk\tools\android.bat "-h"
Result when throw error is false:
{ stdout: '\n       Usage:\n       android [global options] action [action options]\n       Global options:\n  -s --silent     : Silent mode, shows errors only.\n  -v --verbose    : Verbose mode, shows errors, warnings and all messages.\n     --clear-cache: Clear the SDK Manager repository manifest cache.\n  -h --help       : Help on a specific command.\n\n                                                                    Valid\n                                                                    actions\n                                                                    are\n                                                                    composed\n                                                                    of a verb\n                                                                    and an\n                                                                    optional\n                                                                    direct\n                                                                    object:\n-    sdk              : Displays the SDK Manager window.\n-    avd              : Displays the AVD Manager window.\n-   list              : Lists existing targets or virtual devices.\n-   list avd          : Lists existing Android Virtual Devices.\n-   list target       : Lists existing targets.\n-   list device       : Lists existing devices.\n-   list sdk          : Lists remote SDK repository.\n- create avd          : Creates a new Android Virtual Device.\n-   move avd          : Moves or renames an Android Virtual Device.\n- delete avd          : Deletes an Android Virtual Device.\n- update avd          : Updates an Android Virtual Device to match the folders\n                        of a new SDK.\n- create project      : Creates a new Android project.\n- update project      : Updates an Android project (must already have an\n                        AndroidManifest.xml).\n- create test-project : Creates a new Android project for a test package.\n- update test-project : Updates the Android project for a test package (must\n                        already have an AndroidManifest.xml).\n- create lib-project  : Creates a new Android library project.\n- update lib-project  : Updates an Android library project (must already have\n                        an AndroidManifest.xml).\n- create uitest-project: Creates a new UI test project.\n- update adb          : Updates adb to support the USB devices declared in the\n                        SDK add-ons.\n- update sdk          : Updates the SDK by suggesting new platforms to install\n                        if available.\n',
  stderr: '',
  exitCode: 0 }
Exec mono --version
 stdout:
 stderr: "mono" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Exec git --version
 stdout: git version 2.8.4.windows.1

 stderr:
Exec gradle -v
 stdout:
 stderr: "gradle" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Exec "C:\Program Files\Java\jdk1.8.0_92\bin\javac" -version
 stdout:
 stderr: javac 1.8.0_92

System information:
{ procInfo: 'nativescript/2.2.1',
  platform: 'win32',
  os: 'Windows 7 Ultimate 6.1.7600',
  shell: 'C:\\Windows\\system32\\cmd.exe',
  dotNetVer: '4.5.50938',
  procArch: 'ia32',
  nodeVer: 'v4.3.2',
  npmVer: '2.14.12',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: null,
  xcodeprojGemLocation: null,
  itunesInstalled: false,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.8.4.windows.1',
  gradleVer: null,
  javacVersion: '1.8.0_92' }
Starting watch on killswitch C:\Users\Leonardo\AppData\Local\Temp\Leonardo\KillSwitches\cli
Initializing analytics statuses.
Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'Non-interactive' with value 'platform'.
AnalyticsInstallationID: c388e1ad-a44d-4d68-aa65-6c734664083d
monitor not started
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'NodeJSVersion' with value '4_3_2'.
Waiting for analytics to send information. Will check in a 1000ms.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 28000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 27000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 26000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 25000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 24000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 23000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 22000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 21000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 20000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 19000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 18000
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 17000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 16000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 15000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 14000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 13000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 12000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 11000
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 10000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 28000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 27000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 26000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 25000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 24000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 23000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 22000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 21000
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 20000
Looking for project in 'C:\xampp2\htdocs\NeoBux Forum Reader'
Project directory is 'C:\xampp2\htdocs\NeoBux Forum Reader'.
Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'Non-interactive' with value 'platform|add'.
Waiting for analytics to send information. Will check in a 1000ms.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 28000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 27000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 26000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 25000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 24000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 23000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 22000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 21000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 20000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 19000
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 18000
Creating NativeScript project for the android platform
Path: C:\xampp2\htdocs\NeoBux Forum Reader\platforms\android
Package: org.nativescript.NeoBuxForumReader
Name: NeoBuxForumReader
Copying template files...
  - Installing tns-androidUsing version 2.2.0.
  - Installing tns-android[Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-4968-ab8e73d4\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   321ef4e4ae6eaabeb4bada0fbe16ea717d51daed
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz]
Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-4968-ab8e73d4\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
    at FiberFuture.Future.wait (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:566:15)
    at C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\npm-installation-manager.js:85:81
    at Function.settle (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:565:10)
    at C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\services\platform-service.js:84:113
    at Function.settle (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:565:10)
    at C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\services\platform-service.js:49:59
    at arrayEach (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\lodash\lodash.js:451:11)
    at Function.forEach (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\lodash\lodash.js:8634:14)
    at C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\services\platform-service.js:48:15
    at Function.settle (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:565:10)
    at C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\commands\add-platform.js:11:55
    at Function.settle (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:565:10)
    - - - - -
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   321ef4e4ae6eaabeb4bada0fbe16ea717d51daed
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz
    at C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\npm\node_modules\sha\index.js:25:8
    at ReadStream.<anonymous> (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\node_modules\npm\node_modules\sha\index.js:72:7)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
%s. Error: %s
Error: Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-4968-ab8e73d4\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   321ef4e4ae6eaabeb4bada0fbe16ea717d51daed
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz
    at Object.<anonymous> (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:7:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Leonardo\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:9:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'Non-interactive' with value 'help'.
Waiting for analytics to send information. Will check in a 1000ms.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 28000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 27000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 26000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 25000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 24000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 23000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 22000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 21000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 20000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 19000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 18000
Statistics was sent successfully (xhr).
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, info, init, install, livesync, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|find, plugin|install, plugin|remove, plugin|search, plugin|update, prepare, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, usage-reporting
Reading help for command 'platform|add'. FileName is 'platform-add.md'.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 17000
# platform add
┌──────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                    │ Synopsis                                                                                                                                        │
│ Android latest runtime   │ $ tns platform add android [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>]             │
│ Android selected runtime │ $ tns platform add android[@<Version>] [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>] │
└──────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Configures the current project to target the selected platform.

### Options

    * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package.
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
    * --sdk - Sets the target Android SDK for the project.
    * --platform-template - Sets the platform template that will be used for the native application.

### Attributes

    * <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.
    * <Version> is any available version of the respective platform runtime published in npm.

Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track exception with message 'Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-4968-ab8e73d4\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   321ef4e4ae6eaabeb4bada0fbe16ea717d51daed
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz'.
Waiting for analytics to send information. Will check in a 1000ms.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 28000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 27000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 26000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 25000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 24000
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 23000
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 22000
`

**Comment by TheLox95** [comment]
## Node Version
v4.3.2

## NPM Version
2.14.12

I restarted my PC. Now, after run `tns platform add android` it get hung in the spinning sign:
`/ Installing tns-android`

**Comment by tsonevn** [comment]
Hi @TheLox95,
Thank you for writing us back.

In my research I found that this problem could be caused due network problems or could be an [issue](https://github.com/npm/npm/issues/13699) related with npm. Make sure that you have good network connection and try again to run 

`npm cache clean`
`tns platform remove android`
`tns platform add android`
`tns run android`

In case this doesn't help try to install latest long-term support nodejs from [here](https://nodejs.org/en/).
1. `npm uninstall nativescript -g`
2. install the new nodejs
3. `npm install nativescript -g`
4. `tns create sampleProject`
5. `tns run android`

**Comment by TheLox95** [comment]
Hi! I installed `node-v4.5.0-x86` and I was able to add the platform without problem

**Comment by cesarbmolina** [comment]
ANDROID_HOME=C:\Users\macespedes\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_151
(node:6180) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
"adb" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
(node:6180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload?
hi! i need help, i dont understand why printed this error, any can hel me please?

**Comment by tsonevn** [comment]
Hi @cesarbmolina.
Please provide some more info about the case and your environment(CLI node npm modules versions).
Also, it would help if you send us project, which could be debugged locally.
