### ISSUE TITLE
tns doctor fails on Verifying CocoaPods due to USE_POD_SANDBOX

### ISSUE THREAD

**Issue by dennistang** [NativeScript/nativescript-cli#2049]
On a fresh OS X El Capitan 10.11.6 installs on two separate machines, `tns doctor` errors out on `Verifying CocoaPods. This may take some time, please be patient` with the error: `Errno::EPERM - Operation not permitted @ dir_s_rmdir - /Users/<HOME>/Library/Caches/CocoaPods/Pods`.

Looking at the [doctor service](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/doctor-service.ts#L196), it looks like it checks the [config](https://github.com/NativeScript/nativescript-cli/blob/master/config/config.json#L9) to see if it should use the sandbox-pod executable, which it does. 

I know it's been discussed [why `sandbox-pod` is used](https://github.com/NativeScript/nativescript-cli/issues/1249), but is there a reason why we couldn't use `pod` by default in `tns doctor` if we're explicitly calling out the pod plugin in the first place? It's the only error preventing me from seeing the glorious "No issues were detected." message.

I created an empty Xcode project and created a Podfile with the AFNetworking dependency as specified in `doctor-service` and `pod install` works fine, though `sandbox-pod install`, results in the same error.

Maybe it makes sense for `ios-project-service` to use sandbox, but should it be changed for doctor?

Full error log below:

Setting up CocoaPods master repo

CocoaPods 1.1.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.1

Setup completed
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.4)

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a92b9bbdcce3cfdcac2acdfe34490d62731a03e3
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target "__PROJECT_NAME__" do
pod 'AFNetworking', '~> 1.0'
end
```

### Error

```
Errno::EPERM - Operation not permitted @ dir_s_mkdir - /Users/<HOME>/Library/Caches/CocoaPods
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/pathname.rb:576:in `mkpath'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/config.rb:90:in `cache_root'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:33:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:346:in `install_source_of_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:313:in `block (2 levels) in install_pod_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:312:in `block in install_pod_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:304:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:304:in `install_pod_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:160:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:158:in `download_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:115:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Operation+not+permitted+%40+dir_s_mkdir+-+%2FUsers%2F<HOME>%2FLibrary%2FCaches%2FCocoaPods&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

WARNING: There was a problem with CocoaPods
Verify that CocoaPods are configured properly.
There seem to be issues with your configuration.

**Comment by tzraikov** [comment]
@dennistang  Changing the current behavior of tns-doctor will bring inconsistency between this command and ios-project-service. This could result in tns-doctor giving green light while the project is failing to build the app.

**Comment by dennistang** [comment]
Agreed, would there be any objection to changing both to use the regular/non-sandbox `pod` and perhaps updating the documentation to give the option to use the sandbox version? Otherwise the doctor command will give off the wrong impression especially for those unfamiliar to getting {NS} up and running.

If there's no objection, I can submit a PR for it.

**Comment by tzraikov** [comment]
Yes, we will consider that change. That is why I changed the type of this issue to feature. We will appreciate such a pull request.

**Comment by dennistang** [comment]
PR merged! Closing issue.
