### ISSUE TITLE
Incorrect behavior when uncaught exception of type NS Exception is thrown and the phone is connected with cable

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#2053]
_From @vhristov5555 on June 28, 2016 15:9_

1. Create App which throws an uncaught exception of type NS Exception:
var arr = new NSArray();
var o = arr.objectAtIndex(5); 
2. Connect IPhone with cable
3. Deploy the app to the phone:
tns run ios

Actual Result: The App will be stuck and it will remain open. If you disconnect the phone from the cable the App will be closed

Expected Result: The App to be closed because uncaught exception is raised

Note: Reproduce it with IPhone 5S - IOS 8.3

_Copied from original issue: NativeScript/ios-runtime#591_

**Comment by jasssonpet** [comment]
This is because the process is being stopped with `SIGABRT` and the `GDBSignalWatcher` is waiting only for `SIGKILL`.

**Comment by enchev** [comment]
Hey @rosen-vladimirov can you comment this?
