### ISSUE TITLE
tns setup adds PATH variables to .profile when .zshrc is needed.

### ISSUE THREAD

**Issue by lindsaymarkward** [NativeScript/nativescript-cli#2058]
When I ran the setup for NativeScript CLI, and then again running `tns doctor`, the setup script added the PATH variables into my `~/.profile` file, but I'm using zshell, and need these in `~/.zshrc`. 
Is it possible for the setup script to detect the shell or prompt the user to choose which shell, or at least print a message regarding this (what to change if using a different shell)?
Thanks!

tns --version == 2.2.1
Mac, OS 10.10.5
zsh (Ohmyzshell)

**Comment by tzraikov** [comment]
Hi @lindsaymarkward, currently the setup script supports bash shell. Of course, if there is interest we could consider adding support for zsh in future.

**Comment by dtopuzov** [comment]
If `~/.zshrc` exist script will add variables there, see https://github.com/NativeScript/nativescript-cli/blob/master/setup/native-script.rb#L84

**Comment by tranqt1984** [comment]
@dtopuzov that link doesn't work?
