### ISSUE TITLE
"Expected "/*", "//" or "{" but "<" found." reappeared

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-cli#2062]
After a first execution it starts giving the same error.

The same workaround as #1639 still works

**Comment by enchev** [comment]
Hey @ignaciolarranaga,

Please update your app as described here:
https://github.com/NativeScript/NativeScript/issues/2703#issuecomment-247430766

**Comment by ignaciolarranaga** [comment]
Hi @enchev, thanks, but you know I follow those steps and it is still happening.
The first tns run works ok, but after starts with the problem.
