### ISSUE TITLE
Invoke-Expression : you must...

### ISSUE THREAD

**Issue by fredtbx** [NativeScript/nativescript-cli#2063]
Invoke-Expression : you must provide a value expression on the right-hand side of the '/' operator.

At line:1 char:4...

I'm attending the Nativescript Developer Day in Boston but I getting this error when trying to do the @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://www.nativescript.org/setup/win'))" script in Windows

Can you help?

**Comment by dtopuzov** [comment]
Fixed with this commit: 
https://github.com/NativeScript/nativescript-cli/commit/7b9dd3134540757191ffa8a184e11bc71d939208

Please reopen if you encounter this error again.
