### ISSUE TITLE
Entry Point found. always showing this error.

### ISSUE THREAD

**Issue by th3g3ntl3m3n** [NativeScript/nativescript-cli#2065]
Hi..
I am getting this error again and again whenever i am run nativescript angular 2 application.
here what i did for this 
------installation--------
npm install -g nativescript
------create project----------
tns create todos --ng
------adding platform--------
tns platform add android
--------running app-------------
tns run android

--------
---------Error part-------
getting a error as entry point not found. please provide it in package.json.
if using typescript make sure it is trainspiled. etc etc.
please help me.. 
This error only come when i make a angular2 project with nativescript only
when i run---------
tns create todos
it work great..
please help me i want to make it with angular 2

**Comment by dtopuzov** [comment]
Works for me, steps:
```
tns create todos --ng
cd todos
tns run android
```
Can you please clean you npm change (npm cache clean) and try again.

**Comment by tamasfoldi** [comment]
+1 I have the same issue.
