### ISSUE TITLE
build, run, and livesync commands should support the teamid option 

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/nativescript-cli#2067]
Xcode 8 expects a development team to be set when building for device. This can be specified by using the teamid opiton in build, run and livesync commands.

**Comment by roblav96** [comment]
@tzraikov Corrent me if I'm wrong, but can't we define these parameters in our `App_Resources/iOS/build.xcconfig`:
```pascal
CODE_SIGN_IDENTITY = iPhone Developer: Rob Laverty (AG45G4WKF3)
```

**Comment by dtopuzov** [comment]
Yes, you can, but you store this file on source control. 
Some times multiple develelopers with different signing identities can work on this project and then each of them should specify different signing options, that is why we provide CLI command.

**Comment by roblav96** [comment]
@dtopuzov Ah that's a very good point!
