### ISSUE TITLE
Supporting Custom Entitlements files

### ISSUE THREAD

**Issue by SpoonIsBad** [NativeScript/nativescript-cli#2075]
Is it possible to have a custom Entitlements.plist file in App_Resources like it is possible to have a custom Info.plist file? #1089

I tried dropping a Entitlements.plist in my App_Resources file, but when I navigate to platforms/ios/MyApp/ I notice there is no prepended MyApp-Entitlements.plist, and instead it still lives inside of the platforms/ios/MyApp/Resources/ folder. As a result I'm guessing the answer to my question is no.

**EDIT**
Upon messing with this more, I realize the correct file I need is a .entitlements file, not an entitlements.plist, in my case it'd be MyApp.entitlements

**Comment by vbresults** [comment]
@SpoonIsBad @enchev It would also need to add the CODE_SIGN_ENTITLEMENTS variable to the xcconfig

**Comment by vbresults** [comment]
For anyone else who needs to build in CI right now, this is what I use:

`before-prepare/xcode-8-entitlements.js`:
```js
var fs = require('fs-extra');
var path = require('path');

module.exports = function(logger, platformsData, projectData, hookArgs) {
	var platform = hookArgs.platform.toLowerCase(),
		appResourcesDirectoryPath = projectData.appResourcesDirectoryPath,
		platformResourcesDirectory = path.join(appResourcesDirectoryPath, "iOS");

	return new Promise(function(resolve, reject) {
		if (platform == 'ios') {
			var target = path.join(platformResourcesDirectory, "build.xcconfig");

			try {
				fs.writeFileSync(target, "CODE_SIGN_ENTITLEMENTS = " + path.join(projectData.projectName, projectData.projectName + ".entitlements"));
			} catch (error) {
				reject();
			}
		}

		resolve();
	});
};
```

`after-prepare/xcode-8-entitlements.js`:
```js
var fs = require('fs-extra');
var path = require('path');

module.exports = function(logger, platformsData, projectData, hookArgs) {
	var platform = hookArgs.platform.toLowerCase(),
		appResourcesDirectoryPath = projectData.appResourcesDirectoryPath,
		entitlementsFile = path.join(appResourcesDirectoryPath, "iOS", ".entitlements"),
		projectRoot = path.join(projectData.platformsDir, "ios"),
		project = path.join(projectRoot, projectData.projectName);

	return new Promise(function(resolve, reject) {
		if (fs.existsSync(entitlementsFile)) {
			if (platform == 'ios') {
				fs.copy(entitlementsFile, path.join(project, projectData.projectName + ".entitlements"), { clobber: true }, function(e) {
					if (e) {
						console.error(e);
						reject();
					}
				});
			}
		}

		resolve();
	});
};
```

You'll need to have a `.entitlements` file in the App_Resources/iOS folder copied from running Xcode once.

**Comment by spike1292** [comment]
@vbresults tnx for the suggestion, I created a plugin based on your code!

https://github.com/Essent/nativescript-custom-entitlements

**Comment by joaoduartemariucio** [comment]
The script not function in my project. Is there any new solution to the problem?
