### ISSUE TITLE
Building app on NativeScript

### ISSUE THREAD

**Issue by vchittar** [NativeScript/nativescript-cli#2076]
So, I am trying to build my app on XCode and I keep getting this error. How do I remedy this error?

ld: framework not found FLAnimatedImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dennistang** [comment]
Are you using a plugin in your project? Sounds like it may be similar to https://github.com/NativeScript/nativescript-cli/issues/1649

**Comment by NickIliev** [comment]
Hey @vchittar 

Can you provide some more info on your environment  - versions of iOS, version of XCode, version of NativeScript. Also, are you using a specific plugin that requires the FLAnimatedImage!?

**Comment by vchittar** [comment]
Yeah sure. I am using iOS 7, XCode 8, and my nativescript version is 2.3.0. I think the Nativescript version of NYTPhotoviewer uses it and I have removed the pod for it too but I still continue to have this error.

**Comment by NickIliev** [comment]
Hey @vchittar 

I saw that you are aware of the fix suggested in [this thread](https://github.com/NativeScript/nativescript-cli/issues/1649#issuecomment-203891472).

Try to modify your **build.xcconfig** file in your **_app/App_Resources/iOS/_**

**Comment by vchittar** [comment]
@NickIliev What do I add to it? Currently all I have in it is:

```
// You can add custom settings here
// for example you can uncomment the following line to force distribution code signing
// CODE_SIGN_IDENTITY = iPhone Distribution 
// ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
// ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = Brand Assets;

```

**Comment by NickIliev** [comment]
@vchittar  To try the fix to the same file with not comment slashes add
```
EMBEDDED_CONTENT_CONTAINS_SWIFT = YES
```

Save the project, remove the **platforms** file and remove the project.

**Comment by vchittar** [comment]
I did and now I get this error that tells me that my info.plist file is missing from the /platforms/ios folder. And if I may ask what does you mean by removing the project?

**Comment by NickIliev** [comment]
@vchittar my bad - I meant **rebuild** the project! (e.g. tns run ios)

**Comment by vchittar** [comment]
I get an error that says "Cannot read property 'id' of undefined" and I did do the whole removing and adding the project.

**Comment by vchittar** [comment]
I guess I "fixed" that and now I get an error that says myApp/app : No such folder or file exists

**Comment by tzraikov** [comment]
@vchittar I was able to reproduce the issue using the demo project of NYTPhotoviewer. It was created with an old version of NativeScript and needs to be updated. You can address the issue by following those steps:

1. create a new project: `tns create my-test-project`
2. `cd my-test-project`
3. `npm install nativescript-photoviewer`
4. `tns run ios`

You can fix the old project by removing the lib, and platforms folders and removing any reference to  nativescript-photoviewer from your package.json file.
