### ISSUE TITLE
Unable to use plugin with cocoapods

### ISSUE THREAD

**Issue by fleuverouge** [NativeScript/nativescript-cli#2079]
Hi, 
I want to use GLCalendarView in my project, so I created files & folders (https://docs.nativescript.org/angular/plugins/cocoapods.html):
> navitescript-glcalendarview
> -- platforms
> ---- ios
> ------ Podfile
> -- package.json

It's ok when adding the plugin:
```
$ tns plugin add ../nativescript-glcalendarview
nativescript-glcalendarview@0.0.1 node_modules/nativescript-glcalendarview
Successfully installed plugin nativescript-glcalendarview.
```

However, I got error when preparing to build:
```
$ sudo tns prepare ios

nativescript-glcalendarview has Podfile and you don't have Cocoapods installed or it is not configured correctly. Please verify Cocoapods can work on your machine.
```

I've been using Cocoapods perfectly fine in my Xcode projects.

Package.json:
```
{
    "name": "nativescript-glcalendarview",
    "version": "0.0.1",
    "description": "GLCalendarView",
    "main": "index.js",
    "nativescript": {
    "platforms": {
        "ios": "1.3.0"
        }
    }
}
```
Podfile:
`pod 'GLCalendarView'`

XCode version: 8.0
```
$ pod --version
1.0.1
```
```
$ tns --version
2.3.0

```

**Comment by NickIliev** [comment]
Hello @fleuverouge 

I have tried to reproduce your issue but on my side, everything works as expected.
[Here is the sample plugin + NativeScript project ](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript-CLI/issue-2079)that is installing the plugin.
Can you please compare it at your side for any possible differences?

**Comment by fleuverouge** [comment]
Hi @NickIliev,
Thank you for replying!

Your sample project works fine. However, it doesn't contain the podfile (which lead to cocoapods, I guess). When I add files into nativescript-calendarview folder like the files hierarchy above, the problem remains.

Without **sudo** I got:

```
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1 Error output: 
 shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
<blah blah...>
```
So I turn off the **USE_POD_SANDBOX** flag (as suggested in [this thread](https://github.com/NativeScript/nativescript-cli/issues/1249)) and now "Project successfully prepared" :)
 
However this is really a hassle. I wish it had been noted in the docs (like troubleshooting or something). 

Sorry for taking your time.
