### ISSUE TITLE
JS ERROR Error: Could not find module './'.

### ISSUE THREAD

**Issue by tskweres** [NativeScript/nativescript-cli#2080]
When I try to run on a simple helloworld app with routes setup from the docs ( first.component, second.component ):

tns livesync ios --emulator --watch

I get this error:

NativeScript loaded bundle file:///System/Library/Frameworks/UIKit.framework
NativeScript loaded bundle file:///System/Library/Frameworks/Foundation.framework
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x100457d48 -[TNSRuntime executeModule:]
2   0x10005d4b4 main
3   0x180b4e8b8 <redacted>
JavaScript stack trace:
1   @undefined
JavaScript error:
undefined: JS ERROR Error: Could not find module './'.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#471
