### ISSUE TITLE
Livesync not working after update.

### ISSUE THREAD

**Issue by IvRRimum** [NativeScript/nativescript-cli#2084]
i recently updated all my tns deps:

```
karlis@karlis-SATELLITE-L750 ~/Projects/my-instagram/test $ tns info
All NativeScript components versions information

┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.3.0           │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.3.0           │ 2.3.0          │ Up to date  │

```
When i change something in code and save, this shows up in console. However nothing changes in the app( closing and opening the app doesn't help too ):

```
4:42:18 PM - File change detected. Starting incremental compilation...

4:42:22 PM - Compilation complete. Watching for file changes.


Executing before-prepare hook from /home/karlis/Projects/my-instagram/test/hooks/before-prepare/nativescript-dev-typescript.js
Project successfully prepared (android)
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.test on device 3d828389.
```
Each time i run the command `tns livesync android --watch --device=3d828389` i get the full app reinstall and message showing: `The application with id "org.nativescript.test" is not installed on device with identifier 3d828389.` However the app IS installed on the phone.

Tryed removing app, then installing it with tns run.. and again with tuns livesync. No progress.

Whats the problem again?

**Comment by IvRRimum** [comment]
The problem was in my app/App_Resources/android/Manifest and gradle.

I changed them to original ones and it worked.

**Comment by NickIliev** [comment]
When applying changes in the Android Manifest file you will need to rebuild your project.

> WARNING: Not all changes can be livesync’d in a NativeScript app. For instance, livesync cannot patch native configuration file changes (Info.plist, AndroidManifest.xml, and so forth), new plugin installations, and any other change that requires a full compilation of the application. In those cases, you’ll want to use Ctrl+C to stop livesync, and rerun the application using the tns run ios or tns run android commands. Don’t worry though; when situations that require a full compilation come up in this guide, these instructions will be explicitly listed.

source: [https://docs.nativescript.org/tutorial/chapter-1](https://docs.nativescript.org/tutorial/chapter-1)
