### ISSUE TITLE
Keyboard hides when moving to next textfield using "next" key

### ISSUE THREAD

**Issue by dotlens** [NativeScript/nativescript-cli#2085]
The soft keyboard hides when the user tries to move from one textfield to next one with "next" button on the keyboard.

I reproduced this problem on android with and without using angular.

Found in {N} 2.3

To reproduce:
- build and run the sample groceries app using tns 2.3 (https://github.com/NativeScript/sample-Groceries/tree/angular-end)
- select username on the login page (keyboad opens)
- press "next" on the keyboard (password is selected but keyboard is hidden)

Possible workaround (not tested):
- use the (returnPress) event of the TextField to focus the next textfield.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#2809
