### ISSUE TITLE
Feature Request: Custom flags for tns command

### ISSUE THREAD

**Issue by markosko** [NativeScript/nativescript-cli#2091]
Hello,
I would like to ask if there can be added way to add/use custom flags for cli. As i did hook for shrinking (as alternative to webpack) and don't want to run it always after it was added but as optional hook like `nativescript-dev-webpack` module `--bundle` flag but bundle flag is implemented inside cli as part of possible options

Thanks

**Comment by rosen-vladimirov** [comment]
Closing in favor of https://github.com/NativeScript/nativescript-cli/issues/2548
