### ISSUE TITLE
Installed cocoapods and still getting warnings with tns doctor

### ISSUE THREAD

**Issue by davidrhoderick** [NativeScript/nativescript-cli#2096]
So I'm on the following versions:

ruby 2.2.2
node 6.7
cocoapods 2.4.8

When I run `tns doctor` I get:

```
WARNING: There was a problem with CocoaPods
Verify that CocoaPods are configured properly.
There seem to be issues with your configuration.
```

What can I do to get rid of this warning (or should I just ignore it)?

**Comment by davidrhoderick** [comment]
I just downgraded cocoapods to 0.38.2 as per https://docs.nativescript.org/plugins/cocoapods to no avail; problem persists.  This just means I can't use cocoapods modules in ios correct?

**Comment by NickIliev** [comment]
Hey @davidrhoderick 

After you have installed your CocoaPods you should run the following command
```
pod setup
```

Once the setup is ready it should respond with **"Setup completed"**

Also, notice that if you are using XCode 8 you need to install the pods with
```
sudo gem install cocoapods --pre
```

**Comment by davidrhoderick** [comment]
Hey @NickIliev, that was a great tip, but I ran into an issue fixed by https://github.com/CocoaPods/CocoaPods/issues/776 and following that `tns doctor` is still returning:

```
  ◠ Verifying CocoaPods. This may take some time, please be patient..
 sandbox-exec: /Users/davidrhoderick/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-0.38.2/bin/pod: Operation not permitted
```

Any other tips?

**Comment by NickIliev** [comment]
@davidrhoderick 

Can you try the solution described here : [https://github.com/NativeScript/docs/pull/259/files](https://github.com/NativeScript/docs/pull/259/files)

**Comment by Abdenasser** [comment]
Hi there, if anyone is having a hard time with this issue .. I just managed to fix it following the sudo-less installation method from the guides here https://guides.cocoapods.org/using/getting-started.html
