### ISSUE TITLE
App is not starting after deployment

### ISSUE THREAD

**Issue by aplut** [NativeScript/nativescript-cli#2098]
Hi,

after successful building my app is deployed, I see in my console:

> Project successfully built
> The system failed to delete the package for an unspecified reason.
> Successfully deployed on device with identifier 'emulator-5554'.

But the app in not starting, I'm able to go to menu and start the app manually. Additionally after adding --watch option I can see a lot o successful log in the console but nothing happen.

I'm using Ubuntu 16.04 LTS. I have tried with android API 23 and 24.

My NativeScript stack:
 | nativescript           │ 2.3.0                              │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.4.0-2016-09-30-4270 │ 2.3.0          │ Up to date  │
│ tns-android           │ 2.3.0                              │ 2.3.0          │ Up to date  │
│ tns-ios                   │ 2.4.0-2016.9.16.4          | 2.3.0          │ Up to date  │

Thanks,
Adrian

**Comment by aplut** [comment]
I have found a solution.

Here is described what is the problem:
https://github.com/NativeScript/nativescript-cli/issues/2092

But somewhere is a bug because I didn't change my package. After creating app during the wizard I have had:

package.json:
"id": "pl.test.app_name"

app.gradle:
applicationId = "org.nativescript.app_name"

Cheers,
Adrian

**Comment by NickIliev** [comment]
Hey @aplut glad to know you have found the solution.
Closing this as duplicate to [https://github.com/NativeScript/nativescript-cli/issues/2092](https://github.com/NativeScript/nativescript-cli/issues/2092)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#576
