### ISSUE TITLE
tns platform add --framework-path should support urls

### ISSUE THREAD

**Issue by mnahkies** [NativeScript/nativescript-cli#2101]
When using a custom build of the nativescript runtimes across a team, it would be more convenient if `tns platform add --framework-path ...` supported being given a url rather than only local file paths.

Currently if you attempt this using nativescript@next you get this error message:
`
ENOENT: no such file or directory, stat ...
`

**Comment by Plamen5kov** [comment]
Hi @mnahkies,
it will be possible to pass local folders tgz files or URLs with [this PR](https://github.com/NativeScript/nativescript-cli/pull/2209)

**Comment by Plamen5kov** [comment]
@mnahkies if you want to use the platforms with `@next` you can do `tns platform add android@next`
