### ISSUE TITLE
Feature Request: include default gitignore files when creating new app

### ISSUE THREAD

**Issue by dudeofawesome** [NativeScript/nativescript-cli#2102]
It would be nice to have a default gitignore file and editorconfig file included in the default app.

**Comment by stephenfeather** [comment]
A .gitignore file to keep unnecessary file commits at bay, ok. 
But an editorconfig/.jscsrc/.jshintrc is a good bit more personal and opinionated and does not belong (imnsho) in the default app.

Not everyone uses the same style guide.  Just copy your default/preferred config file over into the project.

**Comment by dudeofawesome** [comment]
Yeah, I get that. My thinking behind including it is that you would have to have a matching plugin installed in your editor for it to do anything, and it does improve the code climate by making your code's formatting match that of all the snippets from the documentation and future generated code.

**Comment by stephenfeather** [comment]
Ok, I do understand what you are saying...let me play the other side...

So, will you let me dictate, through an editorconfig file, your indents (7 for perfection), line length (12 chars so you can read it on a small android device), enforce semicolons (because its classy), 3 spaces following a function name and the braces, etc?

I know, total foolishness, but I believe it demonstrates that some things ought not come with the framework.

**Comment by dudeofawesome** [comment]
Haha, yeah, that sounds like a good default config!
```javascript
import {
       Component
} from '@angular/core';
```
Maybe a line length of 24 makes a little more sense, that way you can import Component

But yeah, I get where you're coming from. I got the idea from the Ionic team has included an `.editorconfig` (and `.gitignore`) in their default template. Their CLI has a generate command which will create new components, pages, etc, so perhaps since `tns` doesn't support generation, having a config makes less sense.

We are on the same page about a `.gitignore`, though, correct?

**Comment by stephenfeather** [comment]
a .gitignore for the generated directories that should not be pushed to a repo, yes, great idea

**Comment by rosen-vladimirov** [comment]
This feature is already implemented, just try `tns create myApp` and the newly created project will have .gitignore file.
