### ISSUE TITLE
Unable to create application com.tns.NativeScriptApplication

### ISSUE THREAD

**Issue by uno-de-piera** [NativeScript/nativescript-cli#2103]
Hi,

I have multiple issues executing this project, my last issue is related with nativescript.
```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "parse5/index", relative to: /app/tns_modules/
```
I hope you can help me.

Thanks.

**Comment by NickIliev** [comment]
Hey @uno-de-piera 

Can you please post your project's **package.json**  content.
As a possible solution, make sure you have the latest tns-core-modules

```
rm -rf node_modules
rm -rf platforms
tns plugin remove tns-core-modules
tns plugin add tns-core-modules  // or tns plugin add tns-core-modules@next for the next verison
tns run android // or ios
```

**Comment by johntomcy** [comment]
Thank you @NickIliev the steps mentioned by you helped me...
I was trying to run NativeScript sample project on groceries and i was getting this very exception..
I tried above steps and it started working...
Thanks once again...
