### ISSUE TITLE
Can't run, debug, or anything anymore

### ISSUE THREAD

**Issue by gokuu** [NativeScript/nativescript-cli#2105]
Everything was working fine, and all of a sudden, `tns` commands no longer run the app on either a device or emulator.

Running the app outputs this in the console:

```
BUILD SUCCESSFUL

Total time: 17.182 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
Project successfully built
The system failed to delete the package for an unspecified reason.
Successfully deployed on device with identifier 'emulator-5554'.
```

But both the emulator and the device simply don't do anything.

Has anyone had any similar issues?

**Comment by Daxito** [comment]
+1
Getting this error very often but not always, I just start my app manually and keep going.

**Comment by gokuu** [comment]
...

My bad, I was trying to run this in an old, broken project... Sorry.

Closing the issue...

**Comment by bhandarims12** [comment]
I have the same issue, anyone solved this issue.

Multiple errors were thrown:
The application org.nativescript.TestProject does not appear to be running on ZY222ZHGNL or is not built with debugging enabled.
# debug android
