### ISSUE TITLE
Unable to compile a project that have a symbolic link 

### ISSUE THREAD

**Issue by diegogonzalez** [NativeScript/nativescript-cli#2106]
I create a dummy component and add it in a folder outside the project, then I create a symbolic link to that folder within the project, but I get this error.
```
../test.ts(4,25): error TS2307: Cannot find module '@angular/core'.
```
The code has no errors, if I replace the link with the original folder it works

**Comment by tzraikov** [comment]
This issue is related with the typescript compiler. It uses the physical location of your file and therefore it cannot resolve the module. You will get the same result by executing the `tsc` command when in project root folder.
