### ISSUE TITLE
Feature request: have "tns create" also initialize git repository

### ISSUE THREAD

**Issue by cmermingas** [NativeScript/nativescript-cli#2115]
I think it would be great if `tns create` automatically initialized a git repository with the correct settings for the new project. 

The problem is that after running `tns create` it is not immediately clear which directories and files should be in the repository and which ones should be ignored.

**Comment by stephenfeather** [comment]
There is already an issue where  someone has suggested a default .gitignore in #2102.
That solves your problem.

However, there seems to be an undercurrent to have this particular framework's tooling do all the work devs should, imo, be handling on their own.  

Why create a git repo by default, if the enterprise another user is in doesn't use git but subversion?

**Comment by cmermingas** [comment]
Hi @stephenfeather, 

A .gitignore would do. I searched the issues for "git" and didn't find that, otherwise I wouldn't have opened this one :)

There's no need to create a repository. Not even the .gitignore, although that would be nice. A simple readme that lists which directories should be in version control would be enough for me.

Thank you!
