### ISSUE TITLE
By Using Nativescript-background-http It is showing error as "Net is Not defined".. BY running my emulator

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-cli#2120]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "timers", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:241)
    com.tns.Runtime.run(Runtime.java:235)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:54

**Comment by tzraikov** [comment]
This issue was moved to: [https://github.com/NativeScript/nativescript-background-http/issues/27](https://github.com/NativeScript/nativescript-background-http/issues/27)

**Comment by JaganJonnala** [comment]
Where is the solution  for this why this Should be closed..?

**Comment by JaganJonnala** [comment]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

ReferenceError: net is not defined
File: "/data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-background-http/background-http.js, line: 9, column: 21

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-background-http/background-http.js', line: 9, column: 22
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/app.component.js', line: 4, column: 14
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/main.js', line: 5, column: 23
	Frame: function:'require', file:'', line: 1, column: 266


ReferenceError: net is not defined
File: "<unknown>, line: 1, column: 265

StackTra

**Comment by JaganJonnala** [comment]
Getting above Exception Can Any one Have solution for this

**Comment by tzraikov** [comment]
@JaganJonnala This issue is specific for nativescript-background-http module. That is why I closed this issue and created another another one in nativescript-background-http repository. You can track the issue status there. 

Currently there are some issues related with this module when using our latest version - 2.3.0, we are working on them.

**Comment by JaganJonnala** [comment]
ThnQQ :+1: )

**Comment by kaurag007ph** [comment]
I'm having the same issue while requiring `feathers` module

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "tty", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
    android.app.ActivityThread.access$1300(ActivityThread.java:141)
    android.app.ActivityThread$H.handleMessage(ActivityThread.jav
