### ISSUE TITLE
`tns test` broken with socket-io 1.5.0

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#2122]
The `tns test` command uses socket.io to communicate between the Karma server and the mobile app. The Karma runner code has that dependency set as `"socket.io": "^1.4.5",`, which in turn brings in `socket.io-client` 1.5.0.

Using socket.io 1.5 somehow breaks the connection between the mobile app and the Karma server and the test runner just hangs.

To work around the problem, you need to add an explicit dependency (dev dependencies preferred) to version 1.4.8:

```
"socket.io": "1.4.8",
"socket.io-client": "1.4.8",
```

It seems socket.io-client has changed the way it bundles its code for version 1.5. We need to investigate what's breaking the connection and find a way to fix it.

**Comment by dtopuzov** [comment]
Seems working now with 
```
"socket.io": "1.7.3"
"socket.io-client": "1.7.3"
```
@hdeshev Please reopen if you still experience the issue.
