### ISSUE TITLE
NativeScript setup script fails on Mac

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/nativescript-cli#2125]
[Setup script](http://docs.nativescript.org/start/quick-setup#macos) we promote on [docs.nativescript.org](http://docs.nativescript.org/start/quick-setup#macos) does not work on macOS.

`brew` install Android Tools 25, while we create emulators with old command:
https://github.com/NativeScript/nativescript-cli/blob/master/setup/native-script.rb#L151

**Comment by dtopuzov** [comment]
Brew formula is also changed.
`brew install android-sdk` should be replaced with `brew cask install android-sdk`.
