### ISSUE TITLE
tns platform add android keeps failing

### ISSUE THREAD

**Issue by Nanle21** [NativeScript/nativescript-cli#2132]
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.

**Comment by NickIliev** [comment]
Hey, @Nanle21 in order for NativeScript to work with Android you need to have installed Android SDK, Java JDK and to have set ANDROID_HOME and JAVA_HOME - are all this set at your environment.

If the above steps have been passed, can you provide more information on the environment specifics (e.g.g what is your OS, how have you installed SDK and set the environment paths ). Are you running [the installation script ](https://docs.nativescript.org/start/quick-setup)for the installation article?

**Comment by Nanle21** [comment]
Thanks alot @NickIliev i got everything fixed up
