### ISSUE TITLE
Launch fails for android emulator on genymotion

### ISSUE THREAD

**Issue by agrawal-mohit** [NativeScript/nativescript-cli#2141]
Here's the error trace : 

$ tns livesync android --emulator --watch --stacktrace 
The option 'stacktrace' is not supported. To see command's options, use '$ tns help livesync'. To see all commands use '$ tns help'.
Sending exception report (press Ctrl+C to stop).....

$ tns livesync android --emulator --watch
Executing before-prepare hook from /Users/mohit/work/Mobile/native/Groceries/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Project successfully prepared (android)
Executing before-livesync hook from /Users/mohit/work/Mobile/native/Groceries/hooks/before-livesync/nativescript-angular-sync.js
The application with id "org.nativescript.groceries" is not installed on device with identifier 192.168.56.101:5555.

:config phase:  createDefaultIncludeFiles
	+found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
	 Creating product flavors include.gradle file in /Users/mohit/work/Mobile/native/Groceries/platforms/android/configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/mohit/work/Mobile/native/Groceries/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/mohit/work/Mobile/native/Groceries/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/mohit/work/Mobile/native/Groceries/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:prepareGroceriesRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0DebugDependencies
:compileF0DebugAidl UP-TO-DATE
:compileF0DebugRenderscript UP-TO-DATE
:generateF0DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:mergeF0DebugShaders UP-TO-DATE
:compileF0DebugShaders UP-TO-DATE
:generateF0DebugAssets UP-TO-DATE
:mergeF0DebugAssets UP-TO-DATE
:generateF0DebugResValues UP-TO-DATE
:generateF0DebugResources UP-TO-DATE
:mergeF0DebugResources UP-TO-DATE
:processF0DebugManifest UP-TO-DATE
:processF0DebugResources UP-TO-DATE
:generateF0DebugSources UP-TO-DATE
:incrementalF0DebugJavaCompilationSafeguard UP-TO-DATE
:compileF0DebugJavaWithJavac UP-TO-DATE
:compileF0DebugNdk UP-TO-DATE
:compileF0DebugSources UP-TO-DATE
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.graphics.drawable.animated.BuildConfig conflict: /Users/mohit/work/Mobile/native/Groceries/platforms/android/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.2.1/jars/classes.jar and /Users/mohit/work/Mobile/native/Groceries/platforms/android/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/23.4.0/jars/classes.jar
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:39)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.503 secs
Command /Users/mohit/work/Mobile/native/Groceries/platforms/android/gradlew failed with exit code 1

**Comment by dtopuzov** [comment]
@agrawal-mohit it look the issue is not related with Genymotion, emulator or device type.
The problem is that you can not build your app.
Can you please give us more details:
- Log from "tns build android --log trace"
- Details for app you build (if you can reproduce with simple app it will be great)
- Version of nativescript you use (post your package.json + output of "tns --version")

**Comment by Pip3r4o** [comment]
@agrawal-mohit in addition to what @dtopuzov asked, I'd like to point out that at first sight the issue appears to stem from the fact that one of the android support libraries has been included twice in the build. Could you try completely wiping the `platforms/android` directory before running your app again?
