### ISSUE TITLE
Different folders for compiled files

### ISSUE THREAD

**Issue by FabioAntunes** [NativeScript/nativescript-cli#2142]
I have been searching for some config option and I don't know if it's possible but is there a way of not having the compiled javascript alongside the typescript files? 

![screenshot from 2016-10-17 20 43 01](https://cloud.githubusercontent.com/assets/2544673/19452822/6bcb6708-94aa-11e6-9de5-6f8a98bc92c3.png)

**Comment by tzraikov** [comment]
Yes, that is possible when using Visual Studio Code:
[https://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files](https://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files)
