### ISSUE TITLE
tns run ios error - Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by thowerton** [NativeScript/nativescript-cli#2144]
tns run ios, with or without --emulator, results in this message:

Cannot read property 'id' of undefined 

tns prepare ios and tns build ios both work great.  I can open the project in xcode, and it runs fine.

I see this error on projects checked out from github, as well as after running tns create.

**Comment by matart15** [comment]
Seems like your code trying to access `id` property of  `someobject` which is not assigned yet.
I am not expert but `tns prepare ios` and `tns build ios` both work because they just compile source.

Any source?
what project from github?

**Comment by dtopuzov** [comment]
Can you please run "tns run ios --log trace" also can you try to boot manually simulator before executing build command and see if you reproduce the issue again.

**Comment by thowerton** [comment]
Manually booting simulator seems to be the key.  I booted simulator, then tns run ios --emulator worked.  

After doing this once, and shutting down simulator, tns run ios --emulator boots up simulator and works fine, although it requires a longer timeout than 90 seconds on my old MacBook.

**Comment by tzraikov** [comment]
This could happen on slow machines because the Xcode 8 simulator takes too long to start. You have two options to work around the issue:
1. Like you suggested, you can start the simulator in advance
2. You can edit the Xcode project and change its build schema. Choose Product >> Scheme >> Edit Scheme and change the launch option to "Wait for executable to be launched"

**Comment by dtopuzov** [comment]
This issue might happen on slow macs and only first time when simulators starts (or when you reset simulator settings).
Workaround: Start simulator manually and then run tns commands.
