### ISSUE TITLE
Question : How to compile android sdk 22

### ISSUE THREAD

**Issue by matart15** [NativeScript/nativescript-cli#2145]
My {N} app uses 3rd library. which seems to work with `compileSdkVersion 22` and `targetSdkVersion 22`. 

I tried force fixing buidl.gradle like this
```
def compiteCompileSdkVersion () {
		return 22
}
```

It seems getting 22  value. but now `tns compile android` gives me this error
```
/Users/matar/workplace/NativeScript/matar/platforms/android/build/intermediates/res/merged/F0F1F2/debug/values-v23/values-v23.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
```

which i suspect tns trying to compile with sdk 23. Which happened before on android studio. But android studio editor fixed it automatically. i didn’t understand what happened in background.

**Comment by dtopuzov** [comment]
@matart15 Can you please try
```
tns build android --compileSdk 22
```

**Comment by matart15** [comment]
OK it worked. Thank you
I didn't understand what `project.hasProperty` was in build.gradle. It was command line argument then.
```
       if(project.hasProperty("compileSdk")) {
		return compileSdk
	}
```
