### ISSUE TITLE
TNS run command broken with using --watch

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2150]
According to the docs (and my experience) with the `tns run ios` command -- it rebuilds the app, deploys it and then runs it.   

However, if you add the cool magical `--watch` command the initial build/deploy is skipped and it acts exactly as if you did a `tns livesync ios --watch`.    This is completely different behavior that I don't expect.     When I use the `tns run ios --emulator --watch` I expect it do a full build the app, deploy it, run it and then livesync any changed files after that point.  

Right now because it is broken; you have to a `tns run ios --emulator` ctrl-c after it deploys it, and then start the `--watch` command.

TNS v2.30 - issue is on ios for sure.  No idea on Android as I still use my LiveEdit and never use the --watch command on android.

**Comment by tzraikov** [comment]
Yes, I confirm that currently `tns run ios --watch` is just a shortcut for `tns livesync ios --watch`. Livesync works like this: it checks whether there is an app with the same id installed on the specified emulator/device. If so, it uses the app and transfers application files without rebuilding. If there is no application with the specified id deployed, livesync builds and deploys the app. However, calling build every time when executing `run` will mimimize the benefits of using `livesync`. That is why we will investigate this scenario further and we will try to find the best option.

**Comment by NathanaelA** [comment]
I understand how livesync works.  ;-)     @tzraikov I would totally disagree with you on this

> However, calling build every time when executing run will mimimize the benefits of using livesync

This is incorrect; if I want to do a livesync then I run `tns livesync --watch`.   If I want to do a BUILD & DEPLOY first, then I should do this according to the help & documentation:  `tns run --watch`.

In addition, another issue is that when I do a `tns run ios` I get a TOTALLY different behavior than if I do `tns run ios --watch`.    The first part of this command should act the same.   I.e. build/deploy/run, then it should watch if I included the `--watch` parameter.

And finally; by breaking this command this way, you have given me two commands that do the same thing (i.e. livesync) but you have eliminated the only command that should allow me to do what I actually NEED to do. 

So please fix this command, so it is consistent with itself and the documentation.
