### ISSUE TITLE
Unable to start service com.apple.debugserver. Result code is: 3892314146

### ISSUE THREAD

**Issue by agrawal-mohit** [NativeScript/nativescript-cli#2161]
Hi,

I'm using tns 2.3.0 and trying to build and livesync a project on iPhone 9.3.2

The debug commands builds and mounts successfully but end in this message : 

```
$tns debug ios --device <device id>

Timeout waiting for response from NativeScript runtime.

```

and livesync command responds -

```
$tns livesync ios —device <device id> --watch

Your application will be deployed only on the device specified by the provided index or identifier.
Executing before-prepare hook from /Users/mohit/work/Mobile/native/finly-ng/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.3
Project successfully prepared (ios)
Executing before-livesync hook from /Users/mohit/work/Mobile/native/finly-ng/hooks/before-livesync/nativescript-angular-sync.js
Transferring project files...
Successfully transferred all files.
Applying changes...
Unable to start service com.apple.debugserver. Result code is: 3892314146
```

**Comment by agrawal-mohit** [comment]
`tns device run <application id>  --device <device id>` 
results in the same error.

**Comment by agrawal-mohit** [comment]
Here's the
[device-log.txt](https://github.com/NativeScript/nativescript-cli/files/553958/device-log.txt)

**Comment by tzraikov** [comment]
@agrawal-mohit We are not able to reproduce the issue locally. You could help us by doing the following:
- Check whether the same issue appears when using the same device on different Mac
- Check whether the same issue appears when using a different iPhone device on the same machine
- Run `tns livesync ios` with `--log trace` option and send us the log file

**Comment by cuteredstorm** [comment]
I have the same issue. Unfortunately don't have another Mac or iPhone, so just attached the trace. Note that the app runs on iPhone if I start it manually (tns run ios managed to install it on the iPhone, but no debugging).

[trace.txt](https://github.com/NativeScript/nativescript-cli/files/574737/trace.txt)

**Comment by tkaarrela** [comment]
For me this issue started to occur after updating phone to iOS 10.1.1.

I tried to launch app from xcode directly and got error dialog that iPhone support files are missing(maybe this error message could be reported by cli).


Update xcode to 8.1 fixed my issue.

**Comment by agrawal-mohit** [comment]
I don't have another Mac or an iPhone. But since @cuteredstorm is facing it too, I suppose the problem is at the application level.

**Comment by tzraikov** [comment]
Like @tkaarrela said, this issue could occur when deploying to a phone running with higher version of iOS than the supported by Xcode. Upgrading to the latest version of Xcode should fix the issue. We will think on improving the CLI message in such scenarios.

**Comment by cuteredstorm** [comment]
@tzraikov has completely ignored the fact that I posted the trace of a case where I had the latest iPhone and latest Xcode.

**Comment by tzraikov** [comment]
I missed that, yes. One option then is that there is something wrong with your Xcode configuration. Please, could you try the following: go to the plafroms/ios/ folder in your project and open the .xcodeproj file located there. Try to start it from Xcode.

**Comment by cuteredstorm** [comment]
I have tried and tried but cannot reproduce the issue anymore. I was certainly on latest Xcode and latest iOS but maybe these two were not in sync by Apple. Anyway a better message would benefit as well as instructions to test from Xcode first (in that perspective this issue is very useful).

**Comment by krisloekkegaard** [comment]
This happened to me as well while trying to run livesync. Doing a build with `tns build ios` fixed it. After that I was able to run livesync again.

**Comment by mn-martin** [comment]
Just ran into the same issue. Here's what solved it for me:

```bash
tns platform add ios && tns prepare ios && tns build ios && tns run ios
```

**Comment by burkeholland** [comment]
I have run into this twice now in 2.5.0. When this happens, the only solution I've found is to completely reboot my machine.

**Comment by dxshindeo** [comment]
Just ran into this issue. What fixed it for me was:
1. `tns build ios`
2. And now running on a device works: 'tns run ios --device xxxxx'

NS CLI: 2.5.3
macOS: 10.12.4
OSX on iPhone 5: 10.3
Xcode: 8.2.1

**Comment by hurricane987** [comment]
Perhaps relevant: when building the application in Xcode rather than NS, Xcode cannot assemble the project on the iPhone if the iPhone screen was locked at the time of plugin (even if you unlock the screen after it is has been plugged in. If I start Xcode and try to run the project, it tells me this. If I then unplug my iPhone from the Mac, unlock the screen, and plug it back in, I am able to compile and run the application with the TNS CLI. Very strange.
