### ISSUE TITLE
Service exited due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by zartheman** [NativeScript/nativescript-cli#2162]
Hi there,

I am trying to render a basic map using nativescript + angular2. I followed all of the installation instructions for the google-maps-sdk and at run time, I am getting a segmentation fault 11 error. Any ideas how to resolve this error and render a basic map?

I am running tns-core-modules version 2.3 and xcode 7.2.

page.html

```
<StackLayout>
  <GridLayout>
    <MapView (mapReady)="onMapReady($event)"></MapView>
  </GridLayout>
</StackLayout>
```

page.component.ts

```
import { Component, ViewChild, ElementRef } from '@angular/core';
import { registerElement } from "nativescript-angular/element-registry";

// Important - must register MapView plugin in order to use in Angular templates
registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);


@Component({
  selector: 'page-login',
  templateUrl: './component/pages/page.html'
})
export class LoginComponent {

  @ViewChild("MapView") mapView: ElementRef;

  //Map events
  onMapReady = (event) => {
    console.log("Map Ready");
  };
}

```

To emulate the app I tried both:

```
tns livesync ios --watch --emulator 
```

and 

```
tns run ios --emulator
```

Note, removing the top two registerElement lines from the component (the import and the require lines), resolves the segmentation fault 11 error, however, these lines are required to load the map.

I also tried removing ios as a platform and re-adding it. I tried removing node_modules and then reinstalling all dependencies -- same outcome.

I appreciate any help, thanks in advance!

**Comment by tzraikov** [comment]
@zartheman Note that google maps API requires an API key to be registered. This issue appears when there is no API key in your app. Use the following code to add a keey when using Angular:
<pre>
import * as platform from "platform";

if(platform.isIOS) {
  GMSServices.provideAPIKey("<your-api-key-goes-here>");
}
</pre>

Place this code inside `main.ts` file, just before calling the `bootstrapModule` method. Do not forget to put a correct key inside "&lt;your-api-key-goes-here&gt;".

**Comment by dxshindeo** [comment]
It will still throw an error, that GMSServices cannot be found.In your main.ts file declare it:

```
import * as platform from "platform";
declare var GMSServices: any;

// before calling .boostrap
if( platform.isIOS ) {
    GMSServices.provideAPIKey("YOUR KEY");
}
```

**Comment by locnguyen** [comment]
@dxshindeo Are you able to get past this error yet? I'm running into this same issue trying to get a map to show up.

**Comment by dxshindeo** [comment]
Can't say atm, because all focus right now is on apps android version. The only advice I can give you right now is I suggest you use https://www.npmjs.com/package/npm-check-updates , just to make sure you have all the latest packages. And also use `tns doctor`, it will say if you have outdated nativescript CLI version.

**Comment by jdnichollsc** [comment]
any solution for this issue? 👍
