### ISSUE TITLE
linked-list fails to load _source/linked-list.js

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#2166]
While working on this app: https://github.com/NativeScript/remote-redux-devtools/tree/master/examples/ns-counter
We hit problems with one of its dependencies: https://github.com/wooorm/linked-list
Its `lined-list/_source/linked-list.js` failed to be required.

**Comment by wooorm** [comment]
Whoops. I haven’t touched that code in a while.
Anything I can do to fix?

**Comment by slavchev** [comment]
related to https://github.com/NativeScript/android-runtime/issues/607

**Comment by etabakov** [comment]
This is fixed already.
