### ISSUE TITLE
Livesync doesn't work for TS files (Android)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2167]
_From @bm-software on October 27, 2016 13:25_
### Tell us about the problem

Livesync feature doesn't working anymore for `ts` files. Works fine only for `css` and `html` files.

**Moreover, also running the build command followed by run command my changes to ts files are not deployed to the emulator.**

**NOTE**: I've tried to run livesync with `--log trace` option and when I change a ts file the CLI log the following lines:

```
Shasum of file C:\Code\NativeScriptsProjects\SOSNumbers\app\pages\tabs\tabs.component.ts is f9e0fbd5f5c8cd4e0859ba8c3ade2704caf69ec0
Adding C:\Code\NativeScriptsProjects\SOSNumbers\app\pages\tabs\tabs.component.ts file with f9e0fbd5f5c8cd4e0859ba8c3ade2704caf69ec0 hash.
Syncing filePath C:\Code\NativeScriptsProjects\SOSNumbers\app\pages\tabs\tabs.component.ts, mappedFilePath is C:\Code\NativeScriptsProjects\SOSNumbers\platforms\android\src\main\assets\app\pages\tabs\tabs.component.ts
Syncing C:\Code\NativeScriptsProjects\SOSNumbers\platforms\android\src\main\assets\app\pages\tabs\tabs.component.ts
```

Seems that livesync gets stuck on syncing.
### Which platform(s) does your issue occur on?

Android (not tested on iOS yet)
### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): tns-android: 2.3.0
- Plugin(s): 
  
  "nativescript-cardview": "^1.2.0",
  "nativescript-dom": "^1.0.7",
  "nativescript-floatingactionbutton": "^2.2.5",
  "nativescript-geolocation": "0.0.13",
  "nativescript-google-maps-sdk": "^1.3.14",
  "nativescript-material-icons": "^1.0.1",
  "nativescript-ng2-fonticon": "^1.2.6",
  "nativescript-phone": "^1.2.2",
  "nativescript-snackbar": "^1.1.4",
  "nativescript-social-share": "^1.3.1",
  "nativescript-sqlite": "^1.1.2",
  "nativescript-telerik-ui": "^1.4.1",
  "nativescript-theme-core": "^0.1.3",
  "tns-platform-declarations": "^2.3.0"
### Please tell us how to recreate the issue in as much detail as possible.

Execute `tns livesync android --emulator --watch` command from command prompt

_Copied from original issue: NativeScript/NativeScript#2972_

**Comment by bm-software** [comment]
I've found the problem.
To use `tns-platform-declarations` without errors or warnings I had to configure my `references.d.ts` as follows:

    /// <reference path="./node_modules/tns-core-modules/tns-core-modules.es6.d.ts" /> Needed for autocompletion and compilation.

    /// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/ios/ios.d.ts" />
    /// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/android17.d.ts" />

    declare type FormData = any;
    declare var FormData;
    declare type Blob = any;
    declare var Blob;

And my `tsconfig.json` as follows:

    {
    "compilerOptions": {
        "outDir": "app",
        "module": "commonjs",
        "target": "es6",
        "inlineSourceMap": true,
        "removeComments": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "noLib": false
        "lib": [
             "es2016"
         ]
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
    }

This configuration seems to cause the problem of `ts` syncing with livesync feature. Is that possible? There is any way to fix it?

**Comment by tzraikov** [comment]
@bm-software This seems to be a typescript issue. Executing `tsc` from the project folder with this `tsconfig.json` configuration doesn't produce js files in the app folder. It looks like the `outDir` argument is not working. However, it works when executing typescript from the console: `tsc --outDir app`. A possible work around would be to call typescript compiler manually before running {N} CLI.

**Comment by tzraikov** [comment]
@bm-software Please note that we currently don't support e6 as a target. You should use es5 instead.
