### ISSUE TITLE
CLI should report adb install errors

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#2170]
`tns run android` reach to 

```
Successfully deployed on device with identifier '...'.
```

and then starts the `adb install` command which fails when there is no space left on the device.
But the `adb install` error is not shown. You can only see it if you run with `--log trace` or if you manually call `adb install app.apk`.

**Comment by dtopuzov** [comment]
What is the error exactly.
Related to: https://github.com/NativeScript/nativescript-cli/issues/1060

**Comment by hshristov** [comment]
The error:
```
adb: error: failed to copy 'demo-debug.apk' to '/data/local/tmp/demo-debug.apk': No space left on device
```

**Comment by slavchev** [comment]
That's a good suggestion. We could make the developer experience better if we report `adb` errors. It would eliminate the need to rerun the command with `--log trace`.
