### ISSUE TITLE
Prepare does not flatten scoped dependencies

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2177]
Before we flattened scoped dependencies, now with {N} 2.4 rc we don’t.

Before: 
TNS_App/platforms/android/src/main/assets/app/tns_modules/@angular/core
Now: 
TNS_App/platforms/android/src/main/assets/app/tns_modules/nativescript-angular/node_modules/@angular/core

Possible implications:
File paths too long for Windows OS.

**Comment by Plamen5kov** [comment]
This is expected since cli uses npm installed on machine, if npm 3.x is installed on the user machine, the modules will be flattened if there are no semver exceptions.
