### ISSUE TITLE
Can't install NativeScript

### ISSUE THREAD

**Issue by LorettaNyx** [NativeScript/nativescript-cli#2185]
OS : Win 10 
Node.js v7.0.0
I'm running CMD as administrator 
I'm using this comand : npm install -g nativescript
Getting this output:

`gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:111:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Samsung NP700G7C-S02\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Samsung NP700G7C-S02\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Samsung NP700G7C-S02\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Samsung NP700G7C-S02\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Samsung NP700G7C-S02\npm-debug.log
npm ERR! code 1`

**Comment by NickIliev** [comment]
Hey @LorettaNyx 

At this very moment, NativeScript is not supporting Node.js 7 - keep track [on this thread ](https://github.com/NativeScript/nativescript-cli/pull/2157)where the support will be annouced.
The team is working actively on this issue - meanwhile, you can use NativeScript with LTS or previous version of Node.js (for example 5.x or 6.x). If you need to use several node.js versions you can use node package manager like [nvm](https://github.com/coreybutler/nvm-windows).

Closing this issue as related to [https://github.com/NativeScript/nativescript-cli/pull/2157](https://github.com/NativeScript/nativescript-cli/pull/2157)
