### ISSUE TITLE
Not being able to compile, getting non-descriptive error

### ISSUE THREAD

**Issue by pocesar** [NativeScript/nativescript-cli#2197]
I upgraded the SDK from 19 to 21, and now I'm getting a non-descriptive error and it's failing to build

Windows 10 x64
Nativescript 2.3.0
Android SDK API Level 21
Build Tool 21.1.2
Node 6.9.1
NPM 4.0.1

```
:processF0F1DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'F:\Users\Paulo\AppData\Local\Android\android-sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 46.16 secs
```

already tried to remove and add the android platform, `tns install` everything from scratch, manually deleted `node_modules` and `platforms` folders. always the same outcome

**Comment by Pip3r4o** [comment]
@pocesar We advise NS developers to always use the latest Android SDK tools whenever possible.

To be able to see a more descriptive error run the build with the log trace flag enabled like so: `tns build/run android --log trace` and upload a text document with the console output of the build process so that we may have a better look at the error. Thank you

**Comment by pocesar** [comment]
tried to use build tool 25, it showed:

```
Processing node_modules failed. Exception: You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=23 <=24'.
Sending exception report (press Ctrl+C to stop).....
```

**Comment by Pip3r4o** [comment]
@pocesar in that case using 24 will have to do until the CLI is updated to support android-25. Managed to get the initial error logged with the trace flag enabled?

**Comment by slavchev** [comment]
related to #2203

**Comment by Pip3r4o** [comment]
The issue has been addressed in the latest CLI release and should not limit you to build tools version now.
