### ISSUE TITLE
[Help!] Service exited due to signal: Killed: 9

### ISSUE THREAD

**Issue by fleuverouge** [NativeScript/nativescript-cli#2216]
Hi, my project has been running well until today, without any change, when I run:

`tns emulate ios`

I got:
```
Project successfully built
...
 Service exited due to signal: Killed: 9
```

I tried with freshly pulled the _nativescript-sdk-examples-ng_ project (to make sure that the problem is not in mine only) and got the same error. I can't figure out what's the cause since I hadn't changed anything in neither my code nor {N} before the problem occurred. What I tried to handle it:
- Remove then add platform iOS
- Reinstall {N} (with uninstall & install commands)
- Restart my computer (sometimes it works since this problem has occurred several times before, but not this time)
- Reset the simulator

Other information:
- XCode version: 8.1
- {N} version: 2.3.0
- OS: Sierra

I did some research and found out that this seems to be a popular & persistent problem.

Any suggestion is welcomed.

**Comment by Plamen5kov** [comment]
hi @fleuverouge,
I'm closing this issue in favor of: https://github.com/NativeScript/nativescript-cli/issues/1816
