### ISSUE TITLE
Nothing seems to happen when trying to install

### ISSUE THREAD

**Issue by Jijy** [NativeScript/nativescript-cli#2220]
### Environment
macOSX Sierra
Bash version 3.2.57

### To Reproduce
`$ yarn global add nativescript`
`$ tns`

and then output is
bash: tns: command not found

**Comment by Plamen5kov** [comment]
Hi @Jijy,
Let me star by saying we haven't tried installing the nativescript package through yarn, yet so we can't be absolutely sure it's working.
If we suppose yarn has successfully installed the `nativescript` package, the error you're seing means you need to add the path to the newly installed `nativescript` package in your `$PATH` environment variable.
