### ISSUE TITLE
[Setup Script on OS X] Homebrew as root is no longer supported

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2228]
The [setup script](https://github.com/NativeScript/nativescript-cli/blob/master/setup/native-script.rb#L11) for OS X executes with *root* permissions. However, the homebrew no longer supports installation as *root* and it throws an error. As a result, the setup script quits at this step of the execution.

```
==> Installation successful!
==> Next steps
Run `brew help` to get started
Further documentation: https://git.io/brew-docs
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Homebrew is not installed or not configured properly. Download it from http://brew.sh/, install, set it up and run this script again.
```

**Comment by jasssonpet** [comment]
More on this: https://github.com/Homebrew/brew/commit/eabdbde3f0b7d34de8233e8f886fea10d2922a9e

**Comment by prakashfrancis** [comment]
Still I am facing the same issue. Any solutions or work around is greatly appreciated.

**Comment by aleczadikian** [comment]
I ended up hacking my brew script to just let me run it as sudo.
