### ISSUE TITLE
'Getting up and runnning' not happening

### ISSUE THREAD

**Issue by fossilCreature** [NativeScript/nativescript-cli#2233]
After hours of setting up everything just to run the tutorial app, I don't know what to do. I don't usually waste this much time trying to use new framework if it simple won't work.

This is what happens:

F:\groceries\sample-Groceries>tns run android --emulator
Starting Android emulator with image Nexus4
Waiting for emulator device initialization........
The system failed to delete the package for an unspecified reason.
The package archive file is invalid.

**Comment by NickIliev** [comment]
Hey @fossilCreature 

Can you share with us some more details on your environment setttings and also which branch of the sample-Groceris you are runnning?

We will need your NativeScript versions (`tns --version`), your node,js versions and the branch you are trying to run from the tutorial app (angular-start, master or else)

**Comment by fossilCreature** [comment]
Thanks, I am trying this out at work on a work computer.
I'm using tns version 2.4.0 and I was following the pure JavaScript example for now.
Node.js 6.4.0

I have been playing around with this in my free time and it's just error after error for me. tns doctor reports no issues.

**Comment by NickIliev** [comment]
Hey @fossilCreature I have created a test sample-Groceries from the angular-start branch with content updated up to chapter 4.3. Also, we have released 2.4.3 now - perhaps you can try our with the lastest versions of nativeScritp and Node.js (6.9.2 at this very moment)

**Comment by fossilCreature** [comment]
Thanks. It seems to work now!
