### ISSUE TITLE
High severity vulnerability affecting this repo 

### ISSUE THREAD

**Issue by benmag1** [NativeScript/nativescript-cli#2235]
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [Content & Code Injection (XSS)](https://snyk.io/vuln/npm:marked:20150520?utm_source=gh_issue)
* Affected package: marked<=0.3.5

[Here is the test report for this repo](https://snyk.io/test/github/NativeScript/nativescript-cli?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

**Comment by NickIliev** [comment]
Hey, @benmag1 thank you for reporting this vulnerability.
I noticed that it only covers versions of **_marked_** package below 0.3.5.
Currently, the latest version is 0.3.6 so I guess there is a fix included.

@hdeshev , @Plamen5kov  @jasssonpet  is it safe to update the dependency of **_marked_** to 0.3.6
