### ISSUE TITLE
NPM install fails on Windows

### ISSUE THREAD

**Issue by dax0** [NativeScript/nativescript-cli#224]
I  get a stream of errors like the following whenever I try to build:

`..\src\ffi.cc(55): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\cygwin64\opt\node\node_modules\nativescript\node_modules\ffi\build\ffi_bindings.vcxproj]`

I suspect it has something to do with node-gyp trying to build a native module but I'm not too sure, I've had VS 2012 installed already.

**Comment by Dharun** [comment]
Downgraded to Node v0.10.32 and it fixed the problem

**Comment by ErjanGavalji** [comment]
@Dharun, and which version of NodeJS did you have installed?

**Comment by Dharun** [comment]
v0.12.0 was giving me issues

**Comment by rosen-vladimirov** [comment]
Hi @Dharun,

Thanks for the information. You are correct - currently we have issues with this node version, as some of our dependencies are not buildable with it. We are working on this issue and hopefully we'll be able to support Node 0.12.0 very soon.

Feel free to contact us in case you have any other problems or concerns.

Regards,
Rosen
