### ISSUE TITLE
hooks inside app folder for template-hello-world-ng on tns create

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-cli#2240]
> I was going to open this issue on [template-hello-world-ng](https://github.com/NativeScript/template-hello-world-ng). However, there're no issues on that repo.

After creating a new project using the `template-hello-world-ng`, I've noticed that inside the project comes with a file `./app/hooks/before-livesync/nativescript-angular.sync.js`, however, the same file is on the correct folder `./hooks/before-livesync/nativescript-angular.sync.js`.

I was wondering if that suppose to be there or it's a new setup that I'm not aware.

To reproduce it, just run:

```
tns create myapp --template tns-template-hello-world-ng
```

PS: I've tried to check if other templates come with the hook into app folder, but none of them did, so I thought it would be worth open this issue.

**Comment by NickIliev** [comment]
Hey @leocaseiro 

Thank you for reporting this issue - I ahve tested it on my side and can confirm that the described inconsistency is observed with 
```
tns create myapp --template tns-template-hello-world-ng

// this will create additional hooks folder in app/
```

but is not observed with 
```
tns create myapp --ng

// ok
```

use the shorthand as a workaround - we will investigate and apply a fix for the --template syntax.

**Comment by Plamen5kov** [comment]
fixed in master
