### ISSUE TITLE
LiveSync hangs after exception with XML change

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-cli#2249]
NS 2.4

Crash the app with an exception, change the XML with livesync still running and the CLI just hangs on `Applying changes ...`

**Comment by Pip3r4o** [comment]
@tzraikov do you think they are related? https://github.com/NativeScript/nativescript-cli/pull/2273

**Comment by tzraikov** [comment]
Yes, this is the same issue. It is addressed already and it is included in our @next release. The fix will be included also in our next public release 2.4.1 later this week.
