### ISSUE TITLE
Prepare command with bundle option doesn't copy files

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#2253]
Steps to reproduce:

```shell
tns create TestApp && cd TestApp
tns install webpack
tns run android --bundle
```

Expected `platforms/android/src/main/assets/app/main-view.xml` to be present but the file is missing.

Using NativeScript 2.4 on macOS with Node 6.

**Comment by Plamen5kov** [comment]
There is a new workflow when it comes to bundle. Anyone interested can read about it in the [docs](http://docs.nativescript.org/tooling/bundling-with-webpack), but essentially the new way of doing things is:
```
tns create TestApp && cd TestApp
npm install --save-dev nativescript-dev-webpack
npm run start-android-bundle
```
