### ISSUE TITLE
handlebars?

### ISSUE THREAD

**Issue by code0wl** [NativeScript/nativescript-cli#2255]
Hi all, 

While running my application I get the following error once I have upgraded to nativescript 2.4
This appears when trying to run tests
```
ERROR in ./~/handlebars/lib/index.js
Module not found: Error: Cannot resolve module 'fs' in 
 @ ./~/handlebars/lib/index.js 17:11-24
webpack: bundle is now VALID.
shell.js: internal error
Error: EEXIST: file already exists, symlink '../uglify-js/bin/uglifyjs' -> <localpath>/platforms/android/src/main/assets/app/tns_modules/handlebars/node_modules/.bin/uglifyjs'
```
I was wondering if others were having similar issues?

**Comment by NickIliev** [comment]
Hey @code0wl 

You issue seems to be related to [this one](https://github.com/NativeScript/nativescript-cli/issues/2242).
It is logged as a bug related to the shell.js and we are working on it.
I will close this one as  a duplicate - keep track on the issue above for additional information and fixes.
