### ISSUE TITLE
Deprecate support for Node.js 4.x

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2260]
We consider deprecating support for Node.js 4.x. For this goal, it is needed to update:

- [ ] Doctor Command - UPDATE: Instead of doctor, every single command warns about this.
- [x] Documentation
- [x] Windows Installer

**Comment by rosen-vladimirov** [comment]
Can you explain in more details why do you want to deprecate LTS version of Node.js. It's recommended for users to use Node.js 4 or 6. Also this version will be supported until 2018-04-01 according to Node.js LTS organization: https://github.com/nodejs/LTS

**Comment by stephenfeather** [comment]
Consider that you have competing frameworks whose tooling is stuck at NodeJS 4.x.
If you move up unnecessarily, those users would be required to carry 2 node installs during any transition phase.

**Comment by valentinstoychev** [comment]
@rosen-vladimirov @stephenfeather - we are forced by the Angular requirements. See - https://github.com/angular/angular/blob/master/package.json#L10-L12
