### ISSUE TITLE
Tns cli issue 

### ISSUE THREAD

**Issue by abhishekit29** [NativeScript/nativescript-cli#2262]
I was upload a component from a path. Even after changing the path it is looking at the same path for that component. It seems path is cached.

Nativescript-cli - 2.4.0

**Comment by dtopuzov** [comment]
@abhishekit29 can you give us some more details and exact steps to reproduce.
What you call "component"? May be a plugin? How you exactly change the path?

**Comment by abhishekit29** [comment]
Its now resolved thanks for the reply :) @dtopuzov
