### ISSUE TITLE
Android: apk contains typescript folder

### ISSUE THREAD

**Issue by snekbaev** [NativeScript/nativescript-cli#2269]
Hi,

2.4.0, TS+NG.

```package.json``` file is as following:

```
{
  "description": "Beeper Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "Beeper Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.REDACTED.Beeper",
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "moment": "^2.17.0",
    "nativescript-angular": "1.1.3",
    "nativescript-direct-sms-send": "file:..\\nativescript_modules\\direct-sms-send",
    "nativescript-messenger": "^1.2.0",
    "nativescript-permissions": "^1.2.1",
    "nativescript-ripple": "^1.0.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.3",
    "tns-platform-declarations": "2.4.0",
    "ts-nameof": "^0.7.0",
    "typescript": "^2.1.1",
    "zone.js": "~0.6.21"
  }
} 
```
and apk contains: ```\platforms\android\build\outputs\apk\Beeper-debug.apk\assets\app\tns_modules\typescript``` folder which is 20.9 MB. Is that expected? I was under impression that ```devDependencies``` meant those packages won't end up in the build. For example, ```zone.js``` is not in the apk.

App is quite simple: 2 views, ```App_Resources``` is 2.7MB, yet ```Beeper-debug.apk``` is 23.7MB.
apk contents size:
```
assets - 53MB
lib - 18.4MB
META-INF - 1.4MB
res - 1.1MB
AndroidManifest.xml - 3.8KB
classes.dex - 3.8MB
resources.arsc - 232.4KB
```

Contents of the ```assets``` folder:
```
app - 51.3MB
internal - 3.4KB
metadata - 1.6MB
```
Contents of the ```app\tns_modules```:
```
@angular\
application\
application-settings\
camera\
color\
connectivity\
console\
css\
css-value\
data\
debugger\
fetch\
file-system\
fps-meter\
globals\
http\
image-asset\
image-source\
js-libs\
location\
moment\
nativescript-angular\
nativescript-direct-sms-send\
nativescript-messenger\
nativescript-permissions\
nativescript-ripple\
platform\
reflect-metadata\
rxjs\
text\
timer\
trace\
typescript\
ui\
utils\
xhr\
xml\
bundle-entry-points.js
LICENSE
package.json
```

Thank you!

**Comment by Pip3r4o** [comment]
Hey @snekbaev I wasn't able to replicate this erroneous behavior of the CLI to get it to copy the typescript dev module into my `tns_modules`. Can you confirm that `typescript` isn't a production dependency of the `nativescript-direct-sms-send` plugin?

Running `npm list --prod` will also output a list of all production dependencies used in your project.

**Comment by snekbaev** [comment]
Hi @Pip3r4o,

ok, I should have guessed about external dependencies, in this case my own plugin (I'm new to npm). Indeed it had typescript as dependency, also had tns-modules in both dependencies, probably I missed something when was trying to create my first plugin via https://github.com/NathanWalker/nativescript-plugin-seed. Then I did ```npm update``` in the plugin directory, after that removed the plugin from the main app and re-added it, but ```npm list --prod``` was still giving me an error regarding that plugin. Next step: deleted the app's node_modules directory and ran ```npm install```, however it had installed way more packages than previous folder had, not sure why, skipped that and moved on to ```npm list --prod``` now error was gone and there was no typescript in the list, yet ```tns build android``` was still packaging it. Finally I resolved it by removing and re-adding the android platform via tns.

1) is that ok that I have more packages now? package.json wasn't modified though
2) instead of removing and re-adding the platform was there another way around it?

Thank you!

**Comment by Pip3r4o** [comment]
@snekbaev currently CLI uses `npm 2` internally to install node packages. That results in a different folder structure to what you would see when using `npm install` with `npm 3`. They install the same modules, just differently, hence why you saw "more" modules when you manually npm installed as opposed to tns install. In both cases, `typescript` was referenced as a production dependency, and we include it in the package. As of 2.5 the tns commands will use the npm available on the user's computer. That shouldn't change resulting plugins in APK.

If you don't want the `typescript` included in your final package you should add typescript as a dev-dependency of your module, since you use it only during development time (and that's the main and probably only purpose of 'dev-dependencies'). 

Additionally if your plugin references tns-core-modules I would advice making them a peer dependency of your plugin. That means that the `tns-core-modules` package needs to be present as a dependency in the project that your plugin is being used in order to allow installation of your plugin. Read more here -> https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by snekbaev** [comment]
thank you for clarification!

Regarding the 2) is that something I have to keep in mind in future? I didn't try again but it felt like if plugin production dependency has changed it is not enough to just remove the plugin, re-add it (tns plugin remove/add) and do ```tns build android```, but platform needs to be also removed and re-added. Sort of a reset :)

**Comment by Pip3r4o** [comment]
@snekbaev correct, unless you manually open tns_modules and remove the dependency you removed from node_modules, and clean up the prepared native files, if any, for plugins with native dependencies (.aars and .jars). So yes, cleaning up the platform is the easiest and most painless method of starting fresh with your currently present node_modules. If the plugin stays as a dev-dependency it won't ever copied in tns_modules, so you won't have to worry about it.
