### ISSUE TITLE
App build on beta XCode (with build number) deploying but not starting on device

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2275]
Reproduce steps:

- used real device with iOS 10.1 {*****} where ***** is the build number 
- run `tns run ios` with attached real device

result:
- the application is deployed but not started automatically.
Possible reason - the build number is divided by whitespace from the version number in the path string.

@PanayotCankov  @dtopuzov

**Comment by tzraikov** [comment]
This happens when the app is build with an xcode version lower than the version installed on device.
