### ISSUE TITLE
Do not execute plugin hooks in debug if plugin is used only for release builds

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2300]
Steps to reproduce:
```
tns create TestApp && cd TestApp
tns run android --watch
```
Result:
Snapshot plugin hooks are always executed, while this plugin is applicable only for release builds.

**Comment by pkoleva** [comment]
Rosen Vladimirov: The hook can depend on `$options` and check if `$options.release` is true. So it can immediately return the execution to CLI.

**Comment by dtopuzov** [comment]
Thanks, `$options.release` sounds good enough.
