### ISSUE TITLE
Changes in package.json are not livesynced

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#2303]
If during development you edit the package.json (in the root folder) the change is not applied during a livesync session.

Related to #2153

**Comment by vchimev** [comment]
Let's break down this issue to:
- [ ] 1. change app's id
- [ ] 2. add/remove dependency; update version dependency
- [ ] 3. add/remove dependency; update version of devDependency

These are not going to be supported in 2.5.0. CC: @tzraikov

**Comment by Plamen5kov** [comment]
Because the behavior was unstable, we hid watching the `node_modules` and `package.json` behind a flag `--sync-all-files`, and we'll get back to it as soon as possible.

**Comment by Plamen5kov** [comment]
Closing this until we decide we actually want to have this functionality ready for production.
