### ISSUE TITLE
update used Android Gradle plugin and Gradle

### ISSUE THREAD

**Issue by sunwei415** [NativeScript/nativescript-cli#2307]
When I open project created with tns 2.4.1 and tns-android 2.4.1 in Android Studio 2.2.2, it prompts:

>>> To take advantage of all the latest features (such as Instant Run), improvements and security fixes, we strongly recommend that you update the Android Gradle plugin to version 2.2.2 and Gradle to version 2.14.1.  You can learn more about this version of the plugin from the release notes.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#647
