### ISSUE TITLE
Using nativescript@next brings multiple libraries into node_modules

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2308]
Steps to reproduce:
```
npm uninstall -g nativescript
npm install -g nativescript@next
tns create myProject --tsc
```

result:
![nodemoudlesnext](https://cloud.githubusercontent.com/assets/18008302/20878163/f52fe220-bad5-11e6-8cda-438228214570.png)

On existing project with several plugins, the installed libraries are becoming over 50 
and `tns run android` **hangs out**

Example:
![nodemoudlesnext002](https://cloud.githubusercontent.com/assets/18008302/20878252/8cb2902a-bad6-11e6-915b-2ef121631374.png)

**Comment by Plamen5kov** [comment]
I can't reproduce the problem with the latest, @next build. Can you try again and tell me if the problem still persists when you try it?

**Comment by NickIliev** [comment]
Node,js 6.9.2 (tested also with 6.6.0)
npm 3.10.9 (tested also with 2010.3)

**Comment by Plamen5kov** [comment]
This is expected since if the user has npm 3.x installed, cli will use it to do `npm install` and npm v3.x flattens all dependencies it can on installation.
If the user has npm  v2.x installed the modules won't get flattened on installation.
