### ISSUE TITLE
shell js version

### ISSUE THREAD

**Issue by code0wl** [NativeScript/nativescript-cli#2310]
Hello everyone, 

I had an issue where unit tests were broken as it was giving a symlink issue.
That was luckily solved by updating the cli shelljs version to 0.7.5. 

But now I have an issue that the app resources for iOS are not being copied properly to their build destinations. Anyone else having this issue?

```
Failed to find LaunchScreen.storyboard but it was specified in the Info.plist.
Consider updating the resources in app/App_Resources/iOS/.
A good starting point would be to create a new project and diff the changes with your current one.
Also, the following repo may be helpful: https://github.com/NativeScript/template-hello-world/tree/master/App_Resources/iOS
We will now place an empty obsolete compatibility white screen LauncScreen.xib for you in platforms/ios/edapp/Resources/LaunchScreen.xib so your app may appear as it did in pre v2.1.0 versions of the ios runtime.
Successfully prepared plugin native
```

**Comment by tzraikov** [comment]
@code0wl I confirm the issue. It appears when using the @next version. When using this version the project template doesn't include App_Resources folder. The issue will be addressed in our upcoming 2.5 release. You can work around the issue either by downgrading to 2.4.1 or by copying this folder from an existing project.
