### ISSUE TITLE
tns doctor cocoapods warning

### ISSUE THREAD

**Issue by niyazhussain** [NativeScript/nativescript-cli#2311]
$ tns doctor
Verifying CocoaPods. This may take more than a minute, please be patient.
  ◟ Installing iOS runtime.tns-ios@2.4.0 ../../var/folders/zf/f6yjv3q91_bgcztlcz1rrrtw0000gn/T/nativescript-check-cocoapods116115-3987-1s5en07.ujsp7dgqfr/node_modules/tns-ios
  ◠ Verifying CocoaPods. This may take some time, please be patient..
Analyzing dependencies
[!] Unable to find a specification for `AFNetworking (~> 1.0)`
 
WARNING: There was a problem with CocoaPods
Verify that CocoaPods are configured properly.
There seem to be issues with your configuration.

**Comment by NickIliev** [comment]
@niyazhussain  try to reinstall your pods

```
rm -rf ~/.cocoapods
pod setup
pod install
```

**Comment by niyazhussain** [comment]
when i tried pod install after the pod setup it is throwing 

> [!] No `Podfile' found in the project directory.

**Comment by NickIliev** [comment]
@niyazhussain did you verify you have globally installed Cocoa Pods.

This is the command to install it
```
sudo gem install cocoapods
```

**Comment by Abdenasser** [comment]
Hi there, if anyone is having a hard time with this issue .. I just managed to fix it following the sudo-less installation method from the guides here https://guides.cocoapods.org/using/getting-started.html
