### ISSUE TITLE
port not set when setting USE_PROXY on true

### ISSUE THREAD

**Issue by spike1292** [NativeScript/nativescript-cli#2314]
the unit test runner will try to access karma on http://localhost:9876/context.json.
If you set USE_PROXY to true in `config.json` the path send to the proxy will be http://localhost/context.json

Consider the following fix:
https://github.com/telerik/mobile-cli-lib/compare/master...Essent:feature/proxy-2.5

**Comment by Plamen5kov** [comment]
@spike1292 please do a PR, so the team can validate the inner workings, and the continuous integration is ran.

**Comment by dtopuzov** [comment]
@spike1292 Can you please try with {N} 3.0.0 and `tns proxy set` command.
Help: `tns help proxy set`

Please let us know if you still experience the issue.

**Comment by dtopuzov** [comment]
Related with https://github.com/NativeScript/nativescript-cli/issues/2313

**Comment by spike1292** [comment]
@dtopuzov thank you, now the the port is send to the proxy server
