### ISSUE TITLE
Install issues, windows 7 64 bit

### ISSUE THREAD

**Issue by hsvtarget** [NativeScript/nativescript-cli#2317]
The problem arises during powershell script execution, after apparently successful download and install of android-sdk.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex
 ((new-object net.webclient).DownloadString('https://www.nativescript.org/setup/
win'))"
Allow the script to install Chocolately(It's mandatory for the rest of the scrip
t)?
Tip: Note that if you type a you won't be prompted for subsequent installations
(Y)es/(N)o/(A)ll: a
Installing Chocolately
Getting latest version of the Chocolatey package for download.
Downloading https://chocolatey.org/api/v2/package/chocolatey/0.10.3 to C:\Users
\xj\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
Extracting C:\Users\xj\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
 to C:\Users\xj\AppData\Local\Temp\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName
'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\xj\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Installing Google Chrome (required to debug NativeScript apps)
Chocolatey v0.10.3
Installing the following packages:
googlechrome
By installing you accept licenses for the packages.

GoogleChrome v55.0.2883.75 (forced) [Approved]
googlechrome package files install completed. Performing other installation step
s.
Google Chrome 55.0.2883.75 is already installed.
 The install of googlechrome was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Installing Java Development Kit
Chocolatey v0.10.3
Installing the following packages:
jdk8
By installing you accept licenses for the packages.

jdk8 v8.0.112 (forced) [Approved]
jdk8 package files install completed. Performing other installation steps.
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8
u112-windows-x64.exe
Installing jdk8...
jdk8 has been installed.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of jdk8 was successful.
  Software installed to 'C:\Program Files\Java\jdk1.8.0_112\'

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Installing Android SDK
Chocolatey v0.10.3
Installing the following packages:
android-sdk
By installing you accept licenses for the packages.

android-sdk v24.4.1.3 (forced) [Approved]
android-sdk package files install completed. Performing other installation steps
.
Downloading android-sdk
  from 'https://dl.google.com/android/installer_r24.4.1-windows.exe'
Progress: 100% - Completed download of C:\Users\xj\AppData\Local\Temp\chocolatey
\android-sdk\24.4.1.3\installer_r24.4.1-windows.exe (144.63 MB).
Download of installer_r24.4.1-windows.exe (144.63 MB) completed.
Hashes match.
Installing android-sdk...
android-sdk has been installed.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of android-sdk was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Cannot find an overload for "Combine" and the argument count: "3".
At line:101 char:40
+ $androidExecutable = [io.path]::combine <<<< ($env:ANDROID_HOME, "tools", "an
droid")
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

'update' is not recognized as an internal or external command,
operable program or batch file.
'update' is not recognized as an internal or external command,
operable program or batch file.
'update' is not recognized as an internal or external command,
operable program or batch file.
'update' is not recognized as an internal or external command,
operable program or batch file.
'update' is not recognized as an internal or external command,
operable program or batch file.
Do you want to install Android emulator?: y
Do you want to install HAXM (Hardware accelerated Android emulator)?: y
'update' is not recognized as an internal or external command,
operable program or batch file.
Cannot find an overload for "Combine" and the argument count: "5".
At line:112 char:44
+         $haxmSilentInstaller = [io.path]::combine <<<< ($env:ANDROID_HOME, "e
xtras", "intel", "Hardware_Accelerated_Execution_Manager", "silent_install.bat"
)
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

'update' is not recognized as an internal or external command,
operable program or batch file.
'create' is not recognized as an internal or external command,
operable program or batch file.
This script has modified your environment. You need to log off and log back on f
or the changes to take effect.
Press any key to continue...

C:\Windows\system32>
```
Repeated attempts all have the same result, of course. Any ideas what is fouling up the process? Can I manually set a path, or hand execute what isn't working automatically? Thank you for your time and attention.

**Comment by NickIliev** [comment]
Hey @hsvtarget although the several 'update' warning it seems that the script has done its jobs successfully.

> This script has modified your environment. You need to log off and log back on f
> or the changes to take effect.

Have you tried the log off and then log in in order for your environment changes to be applied.
Also, notice that the script downloads the HAXM but it needs to be installed manually (it also requires restart for its changes to take effect)

Once downloaded you can start it using:
```
%ANDROID_HOME%\extras\intel\Hardware_Accelerated_Execution_Manager\intelhaxm-android.exe
```
or locate manually its download location and install it.

At this point, If have already installed Node.js and NativeScript then you should be able to run 
```
tns doctor
```

else continue with the installation process described [here ](http://docs.nativescript.org/start/quick-setup) or the advanced [step by step process described here](http://docs.nativescript.org/start/ns-setup-win)

**Comment by hsvtarget** [comment]
Have tried relogging several times.
%ANDROID_HOME%\extras\ does exist, but contains only "android" as a subdirectory, so despite my requesting that HAXM be downloaded, it wasn't downloaded where you're saying it should have at the very least. Searching all of my drives for intelhaxm*.* results in no hits

**Comment by hsvtarget** [comment]
Trying to continue with the step by step instructions, although I don't see HAXM mentioned? Which is just to say that it looks as if the processes may differ in ways I don't understand :)

**Comment by hsvtarget** [comment]
And it seems strange, the last step listed in the step by step instructions has already been completed before the powerscript command is ever executed in the normal installation process...

I remain concerned by whatever the commands involving "update" and "create" which could never have been executed given that their executables weren't found (I don't think I would classify them as warnings given that it means that whatever you're trying to do simply fails completely because the command (or executable you rely on to execute the command) doesn't exist)

**Comment by hsvtarget** [comment]
tns doctor indeed indicates success, but in that case what were all those updates and the create? And where's HAXM?

**Comment by NickIliev** [comment]
@hshristov you might face some local system restrictions which are preventing the file to be downloaded. HAXM is hardware accelerator needed to create faster system images (Android emulators).
If the `tns doctor`  is OK then you can download and install HAXM manually from [here](https://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager) (your system may require a restart)

To create and use HAXM enabled emulators you can follow the steps in [this article](http://docs.nativescript.org/tooling/android-virtual-devices)

**Comment by phatakrajan** [comment]
I am facing this issue as well on Win 7 64 bit machine. For last 6 months, when i was using Win 7 32 bit, i did never face this issue.  Here is one of the issues. These issues don't go away even after restart and having full admin permissions while executing the scripts. I also checked that ANDROID_HOME and JAVA_HOME environment variables are registered. Issue description is

Cannot find an overload for "Combine" and the argument count: "5".
At line:18 char:54
+             $haxmSilentInstaller = [io.path]::combine <<<< ($env:ANDROID_HOME
, "extras", "intel", "Hardware_Accelerated_Execution_Manager", "silent_install.
bat")
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

'create' is not recognized as an internal or external command,
operable program or batch file.
ERROR: An error occurred while installing Android emulator. Please, install it manually.
