### ISSUE TITLE
android build fails on windows

### ISSUE THREAD

**Issue by chehabz** [NativeScript/nativescript-cli#233]
[aapt] C:\Users\xxx\Desktop\tns\helloworld\platforms\android\bin\AndroidManifest.xml:14: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

i know that the icon is missing so i edited the AndroidManifest.xml file and build it and it then worked fine. 

However this is the  pre-packaged sample app and it's the default one and this should not have happened.

**Comment by rosen-vladimirov** [comment]
Hi @chehabz 
I assume the problem happened with version 0.4.2 of nativescript-cli. May I ask you to try our latest release and see if the problem is still reproducible on your side?

**Comment by rosen-vladimirov** [comment]
Hi @chehabz 

I'm closing this thread now, but feel free to contact us in case you still have problems.
