### ISSUE TITLE
`tns run` command to watch for changes by default

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/nativescript-cli#2330]
Currently when executing `tns run` command you should pass the `--watch` option in order to start watching for changes. We will change this behavior so that when you execute `tns run` command the watch to be on by default.
If you don't want to watch, we will provide a `--no-watch` option.
If you want to rebuild the application explicitly, we will provide the `--clean` option
> The deploy, prepare and build commands will not be changed. The `livesync` command will be deprecated in 2.5 and removed in 2.6.
We should update the docs accordingly.

**Comment by vchimev** [comment]
Additional:
In order to run the app and release the console/terminal, `--just-launch` option should be used.
