### ISSUE TITLE
Debug with --start option does not return a meaningful result when app is not started on a device/emulator

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2333]
**Steps to reproduce:**
1. Create an app and run it on a device/emulator
2. Stop the app and run `tns debug android/ios --start`

**Expected result**
Info that the app is not started on the device, so --start option cannot work
**Actual result**
On android the cli session is just stopped and on ios we get the message "Frontend client connected"

**Comment by Plamen5kov** [comment]
Currently cli doesn't have functionality where you can check if a process with a specified name (application) is running or not. In the ideal scenario, we'll implement this functionality for iOS and Android.

**Comment by pkoleva** [comment]
With 3.0 we now have a meaningful message "The application org.nativescript.testapp does not appear to be running on TestUser’s iPhone or is not built with debugging enabled."
