### ISSUE TITLE
tns create app1 --frameworkPath ..\tns-android.tgz unexpected behavior

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/nativescript-cli#2350]
Executing `tns create app1 --frameworkPath tns-android.tgz` creates a project with all the wrong files as the tarball is extracted in the new `app` directory.

Not sure if this behavior is intended to work with platform packages (my guess is the ios inspector?) but it's misleading and can cause frustration.

**Comment by tzraikov** [comment]
Interesting, currently we show a message which says that it is wrong to create an app called "app", however we provide an option to create the app. Maybe we should remove that option?

**Comment by Pip3r4o** [comment]
@tzraikov we show no such message. Here's the output with the latest CLI as of the time of this post:
```
$ tns create cc --frameworkPath ../RUNTIME/dist/tns-android-2.5.0.tgz
Installing  D:\work\RUNTIME\dist\tns-android-2.5.0.tgz
D:\work\projects\cc
`-- tns-android@2.5.0

D:\work\projects\cc
`-- tns-core-modules@2.4.4
  `-- tns-core-modules-widgets@2.4.0

Project cc was successfully created.
```

We should remove this option altogether when creating a new project. @KristinaKoeva will this affect the ios runtime? Is the option still used there?

**Comment by KristinaKoeva** [comment]
It seems to me that you are talking about two different things. 
About @tzraikov suggestion - The option to create an application with the name `app` was specifically requested. Take a look here - https://github.com/NativeScript/nativescript-cli/issues/1203#issuecomment-203367786
About @Pip3r4o question - As far as I know the option is not used and I believe that it will not affect the ios runtime. Nevertheless if we decide that we are going to remove it we should throughly test all scenarios :)

**Comment by dtopuzov** [comment]
Now we have validation for `tns create` and passing `--frameworkPath` on create is handled with nice error message.

**Comment by dtopuzov** [comment]
We have no user guide that says we support `--frameworkPath` on create, it is also not listed in `tns create -h`.
