### ISSUE TITLE
Cannot attach on debug port

### ISSUE THREAD

**Issue by rLoka** [NativeScript/nativescript-cli#2353]
Hi, it seems debugger can not connect to android device debug port for some reason .. Tried with both Geny and AVD, but also with physical device .. same result.. I am using Ubuntu 16.10, and android SDK 23.

tns info:
```
All NativeScript components versions information
┌──────────────────┬────────────────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version            │ Latest version │ Information      │
│ nativescript     │ 2.5.0-2016-12-13-7466      │ 2.4.2          │ Up to date       │
│ tns-core-modules │ 2.5.0-2016-12-07-4948      │ 2.4.2          │ Up to date       │
│ tns-android      │ 2.5.0-next-2016-12-14-1505 │ 2.4.1          │ Up to date       │
│ tns-ios          │ 2.3.0                      │ 2.4.0          │ Update available │
└──────────────────┴────────────────────────────┴────────────────┴──────────────────┘
```

Debug output (app starts normally):
```
[NativeScriptCli] execute: tns --version
[NSDebugAdapter] Using tns CLI on path 'tns'
[NSDebugAdapter] Running tns command...
[NSDebugAdapter] Watching the tns CLI output to receive a connection token
[NativeScriptCli] execute: tns debug android --get--port
[NSDebugAdapter] Attaching to application on 40000
```

**Comment by zuran** [comment]
Running into the same issue on OSX when testing on a physical device. iOS debugging works.

Component|Current version|Latest version|Information
---|---|---|---
nativescript|2.3.0|2.4.2|Update available
tns-core-modules|2.4.0-2016-10-19-4474|2.4.3|Update available
tns-android|2.3.0|2.4.1|Update available
tns-ios|2.3.0|2.4.0|Update available

**Comment by rLoka** [comment]
Well, then clearly is something wrong with the version on Linux.

**Comment by pkoleva** [comment]
Hey, guys, @rLoka @zuran 
Is this happening with the chrome devTools debugging released with 2.5.0?

**Comment by Plamen5kov** [comment]
@rLoka `--get-port` is an old flag that will be deprecated for android debugging, please try to use `tns debug android` which will provide you with a link to open in chrome as @pkoleva suggested.

**Comment by etabakov** [comment]
Closing this, due to inactivity.
