### ISSUE TITLE
[@next] --copy-to option is broken

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2357]
Steps to reproduce:
```
tns create TestApp
tns platform add ios@next --path TestApp
tns build ios --path TestApp--copy-to ./
```

Result:
App is build and available at `/Users/nsbuilduser/workspace/CLI-stable-tests-osx-build/TNS_App/platforms/ios/build/emulator/TNSApp.app`
App is not copied to specified location.

Logs:
```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/nsbuilduser/workspace/CLI-stable-tests-osx-build/TNS_App/platforms/ios/build/emulator/TNSApp.app

** BUILD SUCCEEDED **

Project successfully built.
?[31;1mcp: omitting directory '/Users/nsbuilduser/workspace/CLI-stable-tests-osx-build/TNS_App/platforms/ios/build/emulator/TNSApp.app'?[0m
```

Failing since Dec 13, 2016
It was fine on Dec 12, 2016

**Comment by Plamen5kov** [comment]
@dtopuzov the `--copy-to` is not in the docs and in tns help. I suggest we deprecate and remove this functionality.

**Comment by dtopuzov** [comment]
It is in docs! See `tns build ios --help` output :)
