### ISSUE TITLE
tns publish should prune dev dependencies

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-cli#2360]
As the dev dependencies are usually large (at least on the angular context), and there is no reason for send them when releasing the version to the store, I would suggest to prune them when building to the store.

Right now I do this in the following way:
```
npm prune --production
tns publish ios --disable-npm-install
```

**Comment by Pip3r4o** [comment]
@ignaciolarranaga dev-dependencies shouldn't end up in your application package at all, not in debug, nor in release, so pruning dependencies explicitly should be unnecessary. Or is there a specific case that causes your application to contain dependencies that are otherwise declared as dev-deps?

**Comment by ignaciolarranaga** [comment]
Thanks for the clarification. I just double check and you are totally right.

Best
