### ISSUE TITLE
Compling in other path (dist), no in same path (src/app)

### ISSUE THREAD

**Issue by alejonext** [NativeScript/nativescript-cli#2368]
Well, the compiling files for `.ts` is in the same path. The problem is don't clear the project, when you search a line into all the fails compiling is very very hard, with that. 

```
app.component.html
app.component.js // Compling
app.component.js.map // Compling
app.component.ts
app.css
app.module.js // Compling
app.module.js.map // Compling
app.module.ts
main.aot.ts
main.js // ??
main.js.map //??
main.ts
```
Is very clear when use the path `dist`

**Comment by Plamen5kov** [comment]
@alejonext can you provide steps to reproduce?

**Comment by Dashue** [comment]
I think this is an issue as well, having the .ts and .scss compile alongside within the app folder is messy.

How much of an effort would it be to support compiling to a different folder? For example using outDir of typescript?

**Comment by Plamen5kov** [comment]
No reason searching for a solution, until we know the problem.

**Comment by Dashue** [comment]
Right.. apologies for assuming this was understood already.
So the concern is that files are getting compiled alongside the .ts and .scss files inside the app folder. Does that make it clearer?

**Comment by dolanmiu** [comment]
I am finding this annoying too

it's good practice to put compiled files in a `/build` or `/dist` folder

How does one do it?

**Comment by Fatme** [comment]
Hi @dolanmiu, @Dashue,

For typescirpt projects you can specify `outDir` property in `tsconfig.json` file. For example:
```
{
    "compilerOptions": {
          "outDir": "./app/dist"
    }
}
```

**Comment by rosen-vladimirov** [comment]
Hey, when using the `bundle` workflow, the generated files (`bundle.js`, `vendor.js`, etc.) are produced in `<project dir>/platforms/<platform>/.../app` directory and they are never produced next to your source files. As in NativeScript 6.0 the `bundle` workflow will be the only one supported, I'm closing this thread.
