### ISSUE TITLE
[Android] Snapshot w/ livesync --emulator --watch.

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2373]
_From @AntonisHopkins on December 26, 2016 10:56_

Hello, I use an emulator device (the default of android avd) and after I open the snapshot and  try to tns livesync android --emulator --watch ( it tries to re open a new emulator ). By the way the tns device shows the status of device as unreachable and the log trace shows me this repeatedly until timeout.
```
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
execFile: C:\Users\Antony\AppData\Local\Android\android-sdk\platform-tools\adb "devices"
```

_Copied from original issue: NativeScript/NativeScript#3357_

**Comment by NickIliev** [comment]
@AntonisHopkins

There are [some limitations](https://github.com/NativeScript/android-snapshot) when using the snapshot plugin and one of them is regarding live syncing your application

Limitations

- APK file size will be increased with 1.5MB (6MB with Angular).
- The installed application size will be increased with an additional 1.2MB (5MB with Angular).
- It is not possible to step into the embedded script from VS Code. You must use the CLI if you want to debug it.
- **LiveSyncing may work in most cases, but is not officially supported.**
- Snapshots are not compatible with the NativeScript webpack plugin.

**Comment by AntonisHopkins** [comment]
Thank you for your reply
