### ISSUE TITLE
Build ipa for iOS Developement

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2378]
_From @mohitgorakhiya on December 30, 2016 5:37_

Hi,

I want to make archive for iOS Devices using development profile.
I have taken it from platforms-->ios-->build-->device here there is ipa file and now I have added file in iTunes LIbrary and trying to install in iPhone7 Plus.
But it gives iTunes Sync error (-54).
While its working in other devices iPod, iPhone 5S with same way installing.
So can you tell me I am doing anything wrong to make build for development or some issue with iTunes or iPhone7 plus?
iPhone7 Plus UDID also there is in the Development Profile.

Waiting for reply...

_Copied from original issue: NativeScript/nativescript-angular#613_

**Comment by NickIliev** [comment]
Hey  @mohitgorakhiya not sure if this is NativeScript related issue as the reasons are mostly related to trying t sync iPhone 7 with iOS10. Take a look at [this post ](https://www.imobie.com/support/how-to-fix-itunes-sync-iphone-error.htm) where the problem is discussed and a solution is suggested as well.

**Comment by mohitgorakhiya** [comment]
Thanks for your reply.
The Build I have taken from below location 
platforms-->ios-->build-->device
So is it ok?
I want it for development purpose.

**Comment by NickIliev** [comment]
@mohitgorakhiya 

The **ipa** file generated in **_platforms/ios/build/device_** is the one you need. Still keep in mind that you will need to have development team set in your **_app/App_Resources/iOS/build.xcconfig_** file in order to build for real device in iOS10.
Open your **_build.xcconfig_**, uncomment the line with DEVELOPMNET_TEAM and set your development team id as the value.
