### ISSUE TITLE
@next: Next release will be not backward compatbile with old proejcts.

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2379]
`tns build android` result in:
```
sed: no such file or directory: /Users/nsbuilduser/workspace/tns-stable-build-testapps-android-groceries/Groceries/app/App_Resources/Android/app.gradle
```

**Comment by Plamen5kov** [comment]
@dtopuzov cli builds ok with projects with templates >= 1.6.0 which is 7 versions behind the current live version. I wouldn't say cli won't be compatible with old projects. I've already made a PR, which will help the users deal with the problem with old templates: https://github.com/NativeScript/nativescript-cli/pull/2381

**Comment by vchimev** [comment]
TODO: Publish a blog post. Close it when blog post is done.

**Comment by Plamen5kov** [comment]
Keeping old behavior, but showing a warning: https://github.com/NativeScript/nativescript-cli/pull/2381
