### ISSUE TITLE
"tns emulate android" fails with a space in the name of the home directory

### ISSUE THREAD

**Issue by jdah** [NativeScript/nativescript-cli#2380]
The command `tns emulate android` fails when there is a space in the name of the home directory. My version of nativescript-cli is 2.4.2 and I'm on Windows 10.
Output from the command:
```
Command failed: C:\Users\Jonathan Henriksen\AppData\Local\Android\android-sdk\tools\android list avd
'C:\Users\Jonathan' is not recognized as an internal or external command,
operable program or batch file.
```
It then goes on to print the command usage.

**Comment by dtopuzov** [comment]
Thanks for the report.

Workaround: 
Install Android SDK in folder without spaces.
