### ISSUE TITLE
ENV Variable to Disable Email Prompts for Telerik UI

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2384]
_From @vbresults on December 27, 2016 2:45_

For those of us building many apps in a CI environment, please add a variable that we can prepend to npm install so that there is no opt in/email prompt.  It is causing my builds to hang.

Tried using `npm install telerik-nativescript-ui --ignore-scripts` but at random this seems to be ignored by the `npm install` that follows it, and we can't `--ignore scripts` on the latter.

_Copied from original issue: NativeScript/NativeScript#3360_

**Comment by tzraikov** [comment]
This issue was moved to https://github.com/telerik/nativescript-ui/issues/704
