### ISSUE TITLE
[@next][Android] console line breaks in terminal are non existent

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-cli#2385]
## Android console `@next`
![next](http://i.imgur.com/aYiiUZO.png)

## Android console `2.4.4`
![2.4.4](http://i.imgur.com/EAiEP6R.png)

Seems that the console does not recognize line breaks while using `@next`.

**Comment by tzraikov** [comment]
This PR addresses the issue https://github.com/telerik/mobile-cli-lib/pull/864.

**Comment by roblav96** [comment]
@tzraikov ❤️
