### ISSUE TITLE
Cli version format is changed and false update messages are shown in the console

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2386]
See [link](http://www.screencast.com/t/3s10FqJRfK)

We suspect that travis and jenkins create differently formatted versions that's why we have "update needed" message when we actually have a newer version installed locally.

**Comment by dtopuzov** [comment]
This is internal issue caused byu the fact that version format of travis and jenkins are different.
We will handle it by making version of jenkins packages same as travis.
