### ISSUE TITLE
NativeScript CLI should execute hooks only for the specified platform

### ISSUE THREAD

**Issue by galexandrov** [NativeScript/nativescript-cli#2388]
NativeScript CLI should execute hooks only for the specified platform, but from logs it seems that when `tns build ios` command is executed some android hooks invoked as well. 
This hook seems to take significant time to execute.

Please, check the line with `nativescript-dev-android-snapshot.js` in the log bellow

```
mcs:vagrant-sierra-box-fixed user$ tns build ios | gnomon
   9.9536s   Executing before-prepare hook from /Users/vagrant/myapp/hooks/before-prepare/nativescript-dev-android-snapshot.js
   0.0051s   Project successfully prepared (ios)
   1.1895s   Executing after-prepare hook from /Users/vagrant/myapp/hooks/after-prepare/nativescript-dev-android-snapshot.js
   0.0229s   Build settings from command line:
   0.0069s       ARCHS = i386 x86_64
   0.0009s       CODE_SIGN_IDENTITY =
   0.0006s       CONFIGURATION_BUILD_DIR = /Users/vagrant/myapp/platforms/ios/build/emulator
   0.0005s       ONLY_ACTIVE_ARCH = NO
   0.0005s       SDKROOT = iphonesimulator10.0
   0.0005s       SHARED_PRECOMPS_DIR = /Users/vagrant/myapp/platforms/ios/build/sharedpch
   0.0042s       VALID_ARCHS = i386 x86_64
   0.5670s
   0.0012s   === BUILD TARGET myapp OF PROJECT myapp WITH CONFIGURATION Debug ===
   0.0002s
   0.2122s   Check dependencies
   0.0489s
   0.0001s   PhaseScriptExecution NativeScript\ PreBuild build/myapp.build/Debug-iphonesimulator/myapp.build/Script-C97FD7AC1ADE5369004DB2A4.sh
   0.0001s       cd /Users/vagrant/myapp/platforms/ios
   0.0519s       /bin/sh -c /Users/vagrant/myapp/platforms/ios/build/myapp.build/Debug-iphonesimulator/myapp.build/Script-C97FD7AC1ADE5369004DB2A4.sh
   0.1001s   ~/myapp/platforms/ios/internal/metadata-generator/bin ~/myapp/platforms/ios
   0.0011s   Python version: 2.7.10 (default, Jul 30 2016, 18:31:42)
   0.0013s   [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
   0.0074s   Generating metadata for i386
   0.0014s   Metadata Generator Arguments:
   ...
```

**Comment by tzraikov** [comment]
Currently plugins are not platform specific and can't be executed conditionally.

**Comment by rosen-vladimirov** [comment]
@tzraikov the main problem here is that when building for ios, the before-prepare hook of `nativescript-dev-android-snapshot` almost 10 seconds, when it shouldn't do anything. Maybe it's a problem of the plugin, maybe in the hooks service of the CLI, I'm not sure.

**Comment by tzraikov** [comment]
Hmm, that is strange. AFIK it has an internal logic that causes it to execute only when preparing android in release. However, calling the plugin can't be prevented conditionally. That is why I added the feature flag. Maybe @jasssonpet could bring more light on why the plugin could take 10 seconds on before-prepare step.

**Comment by jasssonpet** [comment]
Are those 9.9536s the time it took from the beginning until the `Executing before-prepare hook nativescript-dev-android-snapshot.js` message is printed? Because the actual plugin hook starts executing after this message is printed.

**Comment by tzraikov** [comment]
Just did some tests and the snapshot plugin takes no time (less than 100ms) when executing its before/after prepare stages on ios. I did those tests with our current release branch (2.5.0). So any slow down should come from other tasks (typescript plugin and the prepare task itself). The prepare task for a simple JavaScript project takes ~3 seconds on my machine.

**Comment by rosen-vladimirov** [comment]
Closing this as each plugin can use the platform from hookArgs.platform in before/after-prepare hooks and check if it should do anything.
