### ISSUE TITLE
Could not find an emulator image to run your project.

### ISSUE THREAD

**Issue by Devansh3790** [NativeScript/nativescript-cli#2389]
I followed [setup guid](http://docs.nativescript.org/angular/start/ns-setup-linux) for LINUX. I have Ubuntu 14.04 LTS. I have downloaded and install Android Studio 2.2.3. I created the project by using [Ch-1](http://docs.nativescript.org/angular/tutorial/ng-chapter-1) and when I run 
`tns run android --emulator`
_Could not find an emulator image to run your project._

`$ adb version`
_Android Debug Bridge version 1.0.31_
 
I amn't able to get what actually going wrong within my case. 
Thanks

**Comment by NickIliev** [comment]
You need to manually choose and install Android emulators from Android SDK manager.
For the folder where your Android SDK is installed run **android** in your android tools

```
$ cd /android-sdk-linux/tools
$ ./android
```

And from the pop-up screen that will appear install the proper image you want to run your project on. 
Look [this article](http://www.2daygeek.com/install-sdk-android-emulator-on-ubuntu-centos-debian-fedora-rhel-opensuse-arch-linux-mint/2/) for details

**Comment by NickIliev** [comment]
Hey @Devansh3790 I am closing the issue due to inactivity but do let me know if you need further assistance!
