### ISSUE TITLE
Execution failed for task ':transformClassesWithDexForF0Debug'.

### ISSUE THREAD

**Issue by calacianu** [NativeScript/nativescript-cli#2401]
Every time I run tns build android I get this error

* What went wrong:
Execution failed for task ':transformClassesWithDexForF0Debug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 137

**Comment by Pip3r4o** [comment]
@calacianu please provide more details regarding your project setup.

What versions of the nativescript CLI, nativescript core-modules and the nativescript android runtime are you using? (`tns info`)

Are you using any plugins in your projects?

How can we reproduce that crash?

Meanwhile you could try `tns platform remove android && tns platform add android` before firing up your project the next time and see if that helps.

Thanks!

**Comment by calacianu** [comment]
Hi, thank you for your quick response.
This is my tns info output:
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-core-modules │                 │ 2.4.4          │ Not installed │
│ tns-android      │                 │ 2.4.1          │ Not installed │
│ tns-ios          │                 │ 2.4.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
I tried removing and adding the android platform.
Steps to reproduce:
1. create a simple app
2. and android platform
3. run tns prepare android - build successfully
4. run tns build android - I get this error and another one regarding metadata, but I posted it into another ticket
 
I used no plugins

Thank you!

**Comment by Pip3r4o** [comment]
Closing in favor of https://github.com/NativeScript/nativescript-cli/issues/2402 as the two issues seem identical
