### ISSUE TITLE
Add comments to template-hello-world-ng

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2403]
In 2.5.0, [template-hello-world-ng](https://github.com/NativeScript/template-hello-world-ng) has been rewritten to contains router configuration.

This issue is to add explanation of the template and what it contains in form of comments/README.md/documentation to facilitate users in their getting started.

CC: @valentinstoychev.

**Comment by NickIliev** [comment]
[PR ready for review](https://github.com/NativeScript/template-hello-world-ng/pull/54)

**Comment by dtopuzov** [comment]
PR merged, will be shipped with next release.
