### ISSUE TITLE
Show TypeScript line numbers in stack traces

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#2417]
Currently stack traces show JavaScript line numbers instead of TypeScript line numbers. This makes debugging difficult, and it’s also a tricky thing for beginners to understand. I’m adding a debugging section to the Getting Started Guide, and I’m having a heck of a time trying to explain how this works to new users.

You can recreate this by starting a new project that uses TypeScript.

```
tns create Whatever --ng
cd Whatever
tns run ios --emulator --watch
```

And then doing something silly like this in your TypeScript code.

``` JavaScript
throw Error("Boom!");
```

You‘ll see a stack trace that gives line numbers in the compiled JavaScript code, and not the source TypeScript files.

```
CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: ns-renderer: Error in :0:0 caused by: Boom!

	AppComponent@file:///app/app.component.js:6:20
```

**Comment by stevenspiel** [comment]
This would be very helpful!

**Comment by farfromrefug** [comment]
@dcarrot2 actually ```source-map-support``` works perfectly fine on Android/v8. It is actually made for it.
It won't work however with the iOS runtime.See that issue https://github.com/NativeScript/ios-runtime/issues/1135

Here is an example of reading external source map in android {N} app:
```ts
const currentApp = knownFolders.currentApp();
require('source-map-support').install({
    environment: 'node',
    handleUncaughtExceptions: false,
    retrieveSourceMap(source) {
        const sourceMapPath = source + '.map';
        const sourceMapRelativePath = sourceMapPath.replace('file://', '').replace(currentApp.path + '/', '');

        return {
            url: sourceMapRelativePath + '/',
            map: currentApp.getFile(sourceMapRelativePath).readTextSync()
        };
    }
});
```
