### ISSUE TITLE
[2.5 preview] Initiating debug after a release build crashes the application

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/nativescript-cli#2443]
The new fast run/livesync strategy does not build a debuggable APK after building once for release

```
tns create ts-my-app
cd ts-myapp
tns build/run android --release --key-store- .... ...
tns debug android # <-- app will not be rebuilt, and instead the release apk will be used
```

Executing the above will crash the application when we open the chrome-devtools frontend or debug through the official VSCode extension. 

**Edit**: app rebuilds, but release-specific artifacts remain in the build and pollute the debug output.

**Comment by vchimev** [comment]
This issue seems unpleasant.

A workaround is to delete the `<app/platform/android>` folder and execute `tns debug android` again.
