### ISSUE TITLE
When using tns run <platform> app is built and installed many times without change is made (android only) 

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-cli#2445]
After running sdk examples for android **then** for ios,  **in android only** - the app is built and installed over and over again without making any change in the app or interacting with it.

_NOTE:_ If first ios is run then android - everything's fine.

Here's the app - https://github.com/telerik/nativescript-ui-samples/tree/master

1. Run the app for android - _tns run android_
2. Then **in another terminal** tab run the app for ios - _tns run ios_

**Comment by vchimev** [comment]
This issue comes with NativeScript CLI 2.5.0.

**Comment by vchimev** [comment]
My steps:
```shell
git clone git@github.com:telerik/nativescript-ui-samples.git
cd nativescript-ui-samples/sdk
tns update 2.5.0
tns run android
tns run ios # in another terminal
```
I don't manage to reproduce the issue with the steps above. 

Then, if I execute:
```shell
rm -frv platforms
tns run android
tns run ios # in another terminal
```
I manage to reproduce the issue.

My guess is that platform adding, which happens on the `tns run ios` (installing iOS runtime package to __node_modules__ and removing it), triggers a loop of rebuilds for every file the package contains.


### Workaround:

Execute `tns run <platform> --no-watch|--justlaunch`.

**Comment by Plamen5kov** [comment]
We need to figure out what behavior we want to support before we can do any work in a particular direction.

**Comment by Plamen5kov** [comment]
We should make the run command behave the same way, livesync did: `tns run` should try to livesync all platforms and a `<platform>` parameter should be optional.

**Comment by dtopuzov** [comment]
Closing in flavor of https://github.com/NativeScript/nativescript-cli/issues/2470
