### ISSUE TITLE
tns run--device NonexistentName retunrs different messages for ios and android

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2446]
`tns emulate ios --device NonexistentName`
**Result:** Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.
`tns emulate android --device NonexistentName`
**Result:** Cannot find device with name: NonexistentName

**Related issues** #2131 [#2349](https://github.com/NativeScript/nativescript-cli/issues/2349)

**Comment by dtopuzov** [comment]
Current state with {N} CLI 3.0.0-2017.4.13.3

**iOS:**
```
Searching for devices...
Could not find device by specified identifier 'fake'. To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
```

**Android**
 ```
Searching for devices...
Could not find an emulator image or identifier to run your project. Please run: "tns device <platform> --available-devices"
```

**Comment by yyosifov** [comment]
@dtopuzov Sorry, my bad - I've already fixed this in `mobile-cli-lib` but has forgotten to merge the PR there and update the submodule reference here. I just opened another PR: [https://github.com/NativeScript/nativescript-cli/pull/2760](https://github.com/NativeScript/nativescript-cli/pull/2760)

**Comment by pkoleva** [comment]
Related issue -> https://github.com/NativeScript/nativescript-cli/issues/2728
