### ISSUE TITLE
[iOS][Debug] "tns debug ios --start" is not working if the app is previously started with "tns debug ios"

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-cli#2456]
CLI version: 2.5
iOS Runtime version: 2.5

Steps to reproduce:
1. Run  `tns debug ios` in the app root. This should deploy the app and attach the WebInspector.
2. Close the WebInspector and close/kill the CLI process (`Ctrl+C`/`Ctrl+\`). The app should still be opened in the emulator.
3. Run `tns debug ios --start`.
The expected result is the WebInspector to be started and attached to the already running app without restarting it. The actual behavior is stopping the app without even starting it again.

> Note: if the app is previously started with clicking on the app icon, `tns debug ios --start` works as expected.

**Comment by rosen-vladimirov** [comment]
This issue is resolved with latest CLI and ios-runtime (3.4.1)
