### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by alejonext** [NativeScript/nativescript-cli#246]
I really do not know where to place this issue... Well, the point is that I would like to access the accelerometer sensor. In the docs [android](https://github.com/NativeScript/docs/wiki/Getting-Started-with-NativeScript-for-Android#how-to-inherit-from-class) and [ios](https://github.com/NativeScript/docs/wiki/Getting-started-with-NativeScript-for-iOS#using-the-c-api).  As would be to implement? Do not know if an event ...

**Comment by brianchirls** [comment]
Sensor access (accel, gyro, position, etc.) would definitely be useful.

I believe Android does it through event listeners, and that's probably the best way to do it. There are various settings that describe how often events get triggered, balancing needs of the application with energy consumption. It might make for an easier API to allow querying of sensor values on every frame, but I worry that it might encourage people to ignore those settings.

**Comment by ligaz** [comment]
This issue was moved to NativeScript/NativeScript#209

**Comment by alejonext** [comment]
ok!
