### ISSUE TITLE
tns run fails in 2.5.0

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#2466]
In a typescript project after a project is deployed to emulator/simulator running `tsc && tns run ios` fails with the following error:
```
Transferring project files...
cp: cannot create directory '/Users/.../Library/Developer/CoreSimulator/Devices/1E32CA69-FA23-4E32-8F74-367C293D92D0/data/Containers/Bundle/Application/BC10DB71-B6B0-4E5A-9CC4-5368804A3763/perfmetrics30.app/app': No such file or directory
# run ios
```

**Comment by Plamen5kov** [comment]
@hshristov I can't reproduce the issue. 
What I'm trying is:
```
tns create cliapp --tsc && cd cliapp
tns deploy ios
tsc && tns run ios
```

**Comment by hshristov** [comment]
Maybe something with my project was incorrect. On a new project I can't reproduce it as well. Closing it.
