### ISSUE TITLE
tns run android fails (2.5.0)

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#2467]
tns run android fails to build if there is ios dev dependency in node_modules folder.

Steps to repro:
1. tns create test
2. cd test
3. npm install tns-ios-inspector@2.5.0 --save-dev
4. tns run android

**Comment by pkoleva** [comment]
Related to https://github.com/NativeScript/nativescript-cli/pull/2532

**Comment by Plamen5kov** [comment]
Expectation:
Cli will use the locally installed tns-ios-inspector for debugging.

**Comment by yyosifov** [comment]
This issue was moved to NativeScript/android-runtime#722
