### ISSUE TITLE
Could not update the project!

### ISSUE THREAD

**Issue by modev32** [NativeScript/nativescript-cli#2471]
This what i get after running 'tns update'

```
Platform android successfully removed.
Platform ios successfully removed.
unbuild tns-core-modules@2.5.0
Succsessfully removed plugin tns-core-modules
unbuild tns-core-modules-widgets@2.5.0
Succsessfully removed plugin tns-core-modules-widgets
Could not update the project!
```

**Comment by timh5** [comment]
@modev32 figure this out?

**Comment by timh5** [comment]
might be related:
https://github.com/NativeScript/nativescript-cli/issues/2359

**Comment by rosen-vladimirov** [comment]
Hey @modev32 , @timh5 ,
Have you resolved this issue? In case not, can you give us exact steps to reproduce it? A good starting point will be your package.json file before executing `tns update` command.

**Comment by modev32** [comment]
@timh5 yeah I looked to that before but it's not related, i haven't figure it out yet. i will post more details soon.

**Comment by x00** [comment]
Have the same problem
```
Platform android successfully removed.
Succsessfully removed plugin tns-core-modules
Succsessfully removed plugin tns-core-modules-widgets
Copying template files...
  ◜ Installing tns-androidInstalling  tns-android
  ◜ Installing tns-android/home/zero/aTender2
└── tns-android@2.5.0 


Could not update the project!
```

**Comment by x00** [comment]
running tns update again after changign the rxjs setting resolved this. 

I also had

https://github.com/NativeScript/nativescript-cli/issues/2487
