### ISSUE TITLE
[2.5.0] Livesync watches .DS_Store files

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-cli#2472]
### Steps to reproduce
- `tns livesync ios --watch`
- change a file
- cli applies changes
- ~1 second later transfers `.DS_Store` files rebooting app

### Console
```
Executing before-prepare hook from /Users/roblav96/Projects/app-smile/ghmobile/hooks/before-prepare/nativescript-dev-typescript.js
Preparing project...
Project successfully prepared (ios)
Transferring project files...
Successfully transferred .DS_Store.
Successfully transferred .DS_Store.
Refreshing application...
```

### `tns info`
```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-core-modules │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

A bit of a show stopper since making one file change reboots the app 3 or more times.

#### `v2.4.2` does not have this issue.

# PR
https://github.com/NativeScript/nativescript-cli/pull/2473

**Comment by roblav96** [comment]
@rosen-vladimirov @vchimev how can i help with this? i would ❤️ to contribute.

**Comment by rosen-vladimirov** [comment]
@roblav96 thank you very much. I think your PR was on the right direction. Can you try modifying the pattern, for example `ignored: **/*.DS_Store`  and see if it will work on your side?

**Comment by roblav96** [comment]
@rosen-vladimirov I can confirm that `ignored: '**/*.DS_Store'` does indeed resolve the issue. I'll fix this in the PR. 😄

**Comment by yalva** [comment]
Is this part of latest nativescript-dev-webpack ?

with version 0.14.1 when I use --bundle webpack is watching for .DS_store file.
