### ISSUE TITLE
[2.5.0] prepare skipped so app/ files changes aren't copied

### ISSUE THREAD

**Issue by vbresults** [NativeScript/nativescript-cli#2489]
Since the prepare is skipped in 2.5 if there were no native changes, this also means that changes to files in `app/` are not copied after the first `prepare ios && emulate ios` run.

**Comment by Plamen5kov** [comment]
@vbresults prepare is skipped only if no files are changed.

**Comment by vbresults** [comment]
@Plamen5kov I don't know why, but can no longer reproduce the issue, closing
