### ISSUE TITLE
"nativescript -help" do not work and error message is not appropriate

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#249]
Execute:
nativescript -help
Result:
The option 'e' is not supported. To see command's options, use '$ nativescript help -help'. To see all commands use '$ nativescript help'.

"The option 'e' is not supported." is not a good error message in this case.

**Comment by teobugslayer** [comment]
It is the correct message. You have entered invalid short-hand option and we point out to this. We also give you hints how to see the correct syntax.

**Comment by ligaz** [comment]
Is the message really correct? Shouldn't the option be `elp` not `e` in this case?

**Comment by teobugslayer** [comment]
In this case, we are giving short-hand options to the command line parser - note that it starts with a single `-`. The parser permits all shorthand options to be fused together. Internally, `-help` is treated as `-h -e -l -p`. We stop parsing after the first invalid option, which happens to be `-e`.

**Comment by ligaz** [comment]
:+1:
