### ISSUE TITLE
TNS platform clean android 

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2496]
I ran into a corner case; but one that is annoying if you aren't paying attention.

If you are building a product using a prior version of the runtime; lets say 2.4.1 and you do a 
`tns platform clean android` you will end up with 2.5.0 of the runtime.    When I do a "clean" I expect to maintain the SAME version of the runtimes; I don't expect to have part of my project upgraded...

**Comment by Plamen5kov** [comment]
@NathanaelA you're absolutely right, I'll fix it as soon as possible.
