### ISSUE TITLE
Give 'feedback' while 'node_moudels' are being staged/downloaded

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-cli#2506]
# Setup

- NativeScript 2.5.0
- Running an {N} + Angular application ([this one](https://github.com/telerik/nativescript-ui-samples-angular))

# What is happening

When I run a project that is 'cleaned' meaning there is not platforms and/or node_modules folders via:

`tns run android` or `tns run ios`

The console/terminal is not giving any feedback that the node_modules are being resolved as shown in the screenshot below:
![screen shot 2017-02-08 at 10 28 09](https://cloud.githubusercontent.com/assets/4989411/22728990/532ba4f4-ede9-11e6-8cae-28fc264c2e7c.png)

# What should happens

There should be a message giving the user some feedback on what is being done (npm packages are being resolved). Note that in {N} + Angular those npm packages are many and the CLI is "stuck" on that first time for around 20-30 seconds causing confusion if something is not wrong, after which the build and run continues as expected.

**Comment by dtopuzov** [comment]
Looks OK now, npm3 shows indicator.
