### ISSUE TITLE
NativeScript isn't working. 

### ISSUE THREAD

**Issue by sandeep1k** [NativeScript/nativescript-cli#2507]
I installed NativeScript, there are some issue installation that I can't understand it. when I type TNS DOCTOR it shown : **NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later. 

Your components are up-to-date.
No issues were detected.
** 

how can I fix this problem please let me know. I'm using window 10. 

Thanks

![issue](https://cloud.githubusercontent.com/assets/21118811/22732144/202c77a2-ee13-11e6-9d0b-6fc703ce90b2.jpg)

**Comment by NickIliev** [comment]
Hey @sandeep1k 

From your screenshot, there seem to be no issues at all! 
You can start developing your Android app right away!
To create your first app execute the follwing comands:
```
tns create myApp
tns platform add android
tns run android

```

The warning note is just to inform you that as you are developing on PC with Windows, you will be able to develop only Android apps and you will be able to work only with Android devices. You can not develop for iOS and use iOS devices using Windows (you need Mac with OS X Mavericks or later) or virtual machine (again with OS X Mavericks or later)

**Comment by sandeep1k** [comment]
Thank you so much Sir
