### ISSUE TITLE
XCode build fails after upgrading to MacOSX Sierra, XCode 8.2.1 and tns 2.5.0

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2509]
_From @ickata on February 8, 2017 13:28_

Hi,

After upgrading to Mac OSX Sierra, XCode 8.2.1 and tns 2.5.0 (previous version 2.4.1) (upgrades made in this exact order) XCode build fails because of these:

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/ickata/Library/Developer/Xcode/DerivedData/mobile-hejwrdlgqvwnwqaplqalmdilgkgw/Build/Intermediates/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Release-iphoneos/mobile.build/Script-4DB84042E5969946D8E6C6E9.sh
    cd /Users/ickata/Sites/mobile/platforms/ios
    /bin/sh -c /Users/ickata/Library/Developer/Xcode/DerivedData/mobile-hejwrdlgqvwnwqaplqalmdilgkgw/Build/Intermediates/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Release-iphoneos/mobile.build/Script-4DB84042E5969946D8E6C6E9.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/ickata/Library/Developer/Xcode/DerivedData/mobile-hejwrdlgqvwnwqaplqalmdilgkgw/Build/Intermediates/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Release-iphoneos/mobile.build/Script-4DB84042E5969946D8E6C6E9.sh
    cd /Users/ickata/Sites/mobile/platforms/ios
    /bin/sh -c /Users/ickata/Library/Developer/Xcode/DerivedData/mobile-hejwrdlgqvwnwqaplqalmdilgkgw/Build/Intermediates/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Release-iphoneos/mobile.build/Script-4DB84042E5969946D8E6C6E9.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/ickata/Library/Developer/Xcode/DerivedData/mobile-hejwrdlgqvwnwqaplqalmdilgkgw/Build/Intermediates/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Release-iphoneos/mobile.build/Script-4DB84042E5969946D8E6C6E9.sh
    cd /Users/ickata/Sites/mobile/platforms/ios
    /bin/sh -c /Users/ickata/Library/Developer/Xcode/DerivedData/mobile-hejwrdlgqvwnwqaplqalmdilgkgw/Build/Intermediates/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Release-iphoneos/mobile.build/Script-4DB84042E5969946D8E6C6E9.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

In `platforms/ios/` there is `Podfile.lock` file, but I can't see `Manifest.lock` there.

Build for emulator `tns run ios --emulator` is successful.

I upgraded tns following [these instructions](http://docs.nativescript.org/releases/upgrade-instructions).

My environment:

   - Mac OSX Sierra 10.12.3 (16D32)
   - XCode 8.2.1 (8C1002)
   - tns 2.5.0

_Copied from original issue: NativeScript/NativeScript#3610_

**Comment by NickIliev** [comment]
@ickata  I had the same issue and managed to resolve it by updating the CocoaPods

```
sudo gem install cocoapods
pod setup
```

Now `pod --versions` returns **1.2.0** and my projects are building in XCode.

**Comment by ickata** [comment]
Hi @NickIliev ,

As per your instructions I upgraded CocoaPods, removed and added back iOS platform. Problem still persists.

**Comment by NickIliev** [comment]
@ickata - try resetting your project by removing **node_modules**, **platforms**, **hooks** and **libs** folders and then run `tns upadte`. I've had this issue with an old project and after the update of CocoaPods at first it produced the same error in XCode but after resetting the whole project and rebuilding the issue was resolved.

**Comment by ickata** [comment]
@NickIliev , problem still persists even after following your instructions:

```
tns platform remove ios
tns platform remove android
rm -rf node_modules/ platforms/ hooks/
tns update
tns platform add ios
tns platform add android
tns build ios
```

I didn't have `libs` directory.

**Comment by NickIliev** [comment]
If you have your Xcode Projects' workspace opened during the rebuild the problem might persist as mentioned [here](http://stackoverflow.com/a/38499861/4936697) - try closing XCode, then delete all folders (discussed above), rebuild and open it one more time.

**Comment by ickata** [comment]
Yes, I already have read this, and XCode is closed during rebuilt.

**Comment by ickata** [comment]
FYI, I even tried restarting my Mac as a very last resort :) no change, still having same problem...

**Comment by Daxito** [comment]
@ickata I have no idea either why this happens, but right **before** I build with xCode I execute this command:

tns build ios --release 

And then XCode builds, I also started to get this error after a Mac/Xcode Upgrade

**Comment by ickata** [comment]
Hey @Daxito , 

Many thanks! After building with cli `tns build ios --release` the XCode build is successful.
