### ISSUE TITLE
Run should not watch hidden files

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2512]
Steps to reproduce:

Start `tns run android` on hello-world JS project.
`vim app/app.css` 

Result:

```
Transferring project files...
Successfully transferred .app.css.swp.
Refreshing application...
```
And watcher start restarting app even before I edit something.

Moreover, when this hidden file disappeared I started receiving this on the console:
```
Unable to sync files. Error is: Multiple errors were thrown:
ENOENT: no such file or directory, stat '/Users/topuzov/Git/nativescript-cli-tests/TNS_App/platforms/android/src/main/assets/app/.app.css.swp'
```

**Comment by Plamen5kov** [comment]
should be fixed by: https://github.com/NativeScript/nativescript-cli/pull/2508

**Comment by sis0k0** [comment]
NativeScript CLI 3.1.1 still watches *.swp files...
