### ISSUE TITLE
CLI captures logs from Chrome and Cordova apps

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#2515]
In case, there is working `Chrome` or  `Cordova app` on the device or emulator and build a `NativeScript `app with `tns run android`, the following message will be print in the console.

Message
```
"chromium: [INFO:CONSOLE(25)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (25)"
```

**Comment by Pip3r4o** [comment]
This seems to be a problem with the way we filter out log messages from the device Logcat. For whatever reason (a substring that matched the filter regex) unrelated messages are shown.

This will be addressed with changes to the logging service to only output logs of the running process.

**Comment by pkoleva** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/2818
