### ISSUE TITLE
Fetch-package-versions

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#252]
Add a verb that when used in the context of a project will list the versions and the git commits of the runtimes, the modules and any other information applicable for a bug report

How about "EXTRACT BUG REPORT INFO" verb, or even "REPORT BUG" verb that will prepare a package with all the needed information and send it to the team (how?)

**Comment by ligaz** [comment]
Thanks, this feedback has been merged here https://github.com/NativeScript/nativescript-cli/issues/252
