### ISSUE TITLE
Android debugger does not work

### ISSUE THREAD

**Issue by mannouman** [NativeScript/nativescript-cli#2520]
Hi,

When i launch the debugger (Android launch or Android attach on my device) in Visual Studio Code, the debugger seems to connect but quit immediately, see the trace below : 

```
# NativeScript Debugger started #
[NSDebugAdapter] Ready to attach to application on 40000
[NSDebugAdapter] Connection to target application established on 40000
Error: Unknown signal: SIGQUIT
```

Any idea ?
Thanks

**Comment by halaharr** [comment]
This worked after I did this.
"you could try to delete launch.json file from .vscode folder in your project and to generate it again while following the instructions [here](https://docs.nativescript.org/tooling/visual-studio-code-extension#generate-launch-configurations)."

**Comment by mannouman** [comment]
Thanks Halaharr, the debugger is well connected now. 

But i don't understand it does not stop on my breakpoints...

if it helps, see my launch.json configuration (android part) : 

```
{
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true,
            "stopOnEntry": false
        },
        {
            "name": "Attach on Android",
            "type": "nativescript",
            "request": "attach",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        }
```

**Comment by halaharr** [comment]
I have seen that happen before. It takes some time sometime for the breakpoints to be enabled.  Here is my launch.json settings
 {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        },

**Comment by ivanbuhov** [comment]
@halaharr From v2.5 only inline source maps are supported on Android. If you are debugging TypeScript project, make sure the generated `.js` files have source maps inlined. To achieve it you can add set `inlineSourceMap` to `true` in your `tsconfig.json`.

**Comment by mannouman** [comment]
@halaharr i tried with the same conf as yours but same problem.

I will retry with another device but with this one (Oneplus 3) i can debug Android native in android studio so i don't think the problem comes from my device.

@ivanbuhov i am not using TypeScript

Thanks for your help guys ! any ather idea ?

**Comment by fbeaulieu** [comment]
Nativescript (vanilla javascript)
VSCode 191
nativescript extension 061

Same problem here, from VSCODE 191, variable section is foreever empty. Breakpoints works but after application is launched. Nativescript pre-launch events do not hit at all now. Watch section works well though. Tried all possible combination of launch.json (destroyed it, recreate vanilla, said a prayer...)

Just wondering if it's an extension bug or a vscode bug (which I think it is...)

any help is welcomed !

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/nativescript-vscode-extension#119
