### ISSUE TITLE
tns create error ENOTCONN

### ISSUE THREAD

**Issue by Mepk** [NativeScript/nativescript-cli#2522]
NativeScript 2.4.2
After call "tns create pHello" I received an error: Failed to retrieve data from npm. Error: connect ENOTCONN 151.101.84.162:443.
What it means?

**Comment by rosen-vladimirov** [comment]
Hey @Mepk ,
It looks like there are some connection issues on your side. During creation of project, NativeScript CLI tries to download several packages from npm. It looks like it is unable to connect to `npm`.
Are you still reproducing the issue?
Can you try installing any package, for example `npm i -g rimraf`?
Have you set npm proxy, it might have issues connecting to npm. You can check if you have set proxy by executing:
```
$ npm config get proxy
$ npm config get https-proxy
```

**Comment by Mepk** [comment]
npm packages via npm install loading correct.
Proxy config is set.
Problems is only with tns

**Comment by rosen-vladimirov** [comment]
Hey @Mepk , 
Can you send us the output of the following commands:
```
$ tns doctor --log trace
$ tns create pHello --log trace
```

**Comment by etabakov** [comment]
Closing this, due to inactivity.
