### ISSUE TITLE
`tns run android --device <emulator-avd-image>` does not start existing emulator images

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2525]
`tns --version` output:
```3.0.0-2017.2.9.3```

`tns run android --path TestApp --device Emulator-Api19-Default` output:
```
Skipping prepare.
Searching for devices...
Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.
```

Note that `android list avds` list all my emulator images correctly.

**Comment by Plamen5kov** [comment]
We've never worked like this as is described in the docs for [run android](https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/project/testing/run-android.md). What you are looking for is `--emulator`.
