### ISSUE TITLE
`tns run android --device <emulator-image-avd>` fails with ECONREFUSED on Windows

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2526]
`tns emulate android --path TestApp --device Emulator-Api19-Default` output is:
```
Starting Android emulator with image Emulator-Api19-Default
Error: connect ECONNREFUSED 127.0.0.1:5554
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

tns version: 3.0.0-2017.2.9.3

**Comment by Plamen5kov** [comment]
@dtopuzov  can't reproduce with latest master.

**Comment by dtopuzov** [comment]
It works properly with `tns run android --path TestApp --device <avd-image-name>`.
Closing since `emulate` i deprecated and `run` works properly with {N} 3.0.0
