### ISSUE TITLE
Templates support

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#254]
Currently only hello-world-template is supported. But actually we have 4 templates - Blank, Hello World, Master Detail, Tabbed App. It should be nice if we support all of them.

**Comment by shrimpywu** [comment]
will be nice to have a typescript project template as well.

**Comment by ch-weiss** [comment]
I  would appreciate TypeScript templates as well.

**Comment by rosen-vladimirov** [comment]
Closing this one as duplicate of https://github.com/NativeScript/nativescript-cli/issues/374
Check the other thread for more details.
