### ISSUE TITLE
iOS: tns livesync gets stuck at Applying changes...

### ISSUE THREAD

**Issue by zsf3** [NativeScript/nativescript-cli#2544]
When I run `tns live sync ios --watch` command. It syncs application on my iPhone first time, but then when I change anything in any `html` or `ts` file. the tns compiler gets stuck and does not sync application to iPhone.

Following are the logs I got from trace command:

Transferring project files...
Transferring all files.
Creating zip file: /var/folders/h2/xgxkpy9567x7kty4fk__t9hw0000gn/T/sync117115-60794-5dbwc0.rksw09t3xr.zip
spawn: zip "-r" "-0" "/var/folders/h2/xgxkpy9567x7kty4fk__t9hw0000gn/T/sync117115-60794-5dbwc0.rksw09t3xr.zip" "app" "-x" "app/tns_modules/*"
PlistService sending: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>VendContainer</string>
	<key>Identifier</key>
	<string>com.folio3.atlona</string>
</dict>
</plist>

An error has occured: TypeError: Cannot read property 'nodeName' of null
Removing device file 'Library/Application Support/LiveSync/sync.zip', result: 0
transfer-> localFilePath: '/var/folders/h2/xgxkpy9567x7kty4fk__t9hw0000gn/T/sync117115-60794-5dbwc0.rksw09t3xr.zip', devicePath: 'Library/Application Support/LiveSync/sync.zip', localFilePathSize: '10460313', transferred bytes: '10460313'
Successfully transferred all files.
Applying changes...
GDB: send packet $QStartNoAckMode#b0
GDB: read packet: +
GDB: send packet +
GDB: send packet $QEnvironmentHexEncoded:#f7
GDB: read packet: $OK#9a
GDB: send packet $QSetDisableASLR:1#ce
GDB: read packet: $OK#00
GDB: send packet $A186,0,2f707269766174652f7661722f636f6e7461696e6572732f42756e646c652f4170706c69636174696f6e2f38433841323137302d334237432d343944312d424143462d4234314346443339343630412f41746c6f6e616769742e617070#bd
GDB: read packet: $OK#00
GDB: send packet 
GDB: send packet 
GDB: send packet $k#6b
GDB: read packet: $X09#00$X00;description:5465726d696e617465642064756520746f207369676e616c2039;#00
GDB: send packet $QStartNoAckMode#b0
GDB socket get closed. HadError false
GDB: read packet: +
GDB: send packet +
GDB: send packet $QEnvironmentHexEncoded:#f7
GDB: read packet: $OK#9a
GDB: send packet $QSetDisableASLR:1#ce
GDB: read packet: $OK#00
GDB: send packet $A186,0,2f707269766174652f7661722f636f6e7461696e6572732f42756e646c652f4170706c69636174696f6e2f38433841323137302d334237432d343944312d424143462d4234314346443339343630412f41746c6f6e616769742e617070#bd
GDB: read packet: $OK#00
GDB: send packet $qLaunchSuccess#a5
GDB: read packet: $OK#00
GDB: send packet $vCont;c#a8
Successfully synced application com.folio3.atlona on device e266460221859aebc1ed5c03c56fcf8d7cf9b7eb.
BeforeHookName for command watch is before-watch
Executing before-watch hook from /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/before-watch/nativescript-dev-typescript.js
Executing before-watch hook at location /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/before-watch/nativescript-dev-typescript.js in-process
Validating before-watch arguments.
Found peer TypeScript 2.0.10
/usr/local/Cellar/node@6/6.9.4/bin/node --max_old_space_size=2048 /Users/it/Documents/AtlonaRepo/Atlona_git/node_modules/typescript/lib/tsc.js --project /Users/it/Documents/AtlonaRepo/Atlona_git --watch --inlineSourceMap --inlineSources
Hook promises to signal completion
6:13:42 PM - Compilation complete. Watching for file changes.

Hook completed
 Shasum of file /Users/it/Documents/AtlonaRepo/Atlona_git/app/pages/opportunity/opportunity.detail.component.html is a9a1fe52fe999b2b0d9001153dc7bc2ab0947e42
Adding /Users/it/Documents/AtlonaRepo/Atlona_git/app/pages/opportunity/opportunity.detail.component.html file with a9a1fe52fe999b2b0d9001153dc7bc2ab0947e42 hash.
Syncing filePath /Users/it/Documents/AtlonaRepo/Atlona_git/app/pages/opportunity/opportunity.detail.component.html, mappedFilePath is /Users/it/Documents/AtlonaRepo/Atlona_git/platforms/ios/Atlonagit/app/pages/opportunity/opportunity.detail.component.html
Syncing /Users/it/Documents/AtlonaRepo/Atlona_git/platforms/ios/Atlonagit/app/pages/opportunity/opportunity.detail.component.html
Removed files from syncQueue:  []
Removed files from syncQueue:  []
BeforeHookName for command prepare is before-prepare
Executing before-prepare hook from /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook at location /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/before-prepare/nativescript-dev-android-snapshot.js in-process
Validating before-prepare arguments.
Hook completed
Executing before-prepare hook from /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/before-prepare/nativescript-dev-typescript.js
Executing before-prepare hook at location /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/before-prepare/nativescript-dev-typescript.js in-process
Validating before-prepare arguments.
Hook completed
Project successfully prepared (ios)
AfterHookName for command prepare is after-prepare
Executing after-prepare hook from /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/after-prepare/nativescript-dev-android-snapshot.js
Executing after-prepare hook at location /Users/it/Documents/AtlonaRepo/Atlona_git/hooks/after-prepare/nativescript-dev-android-snapshot.js in-process
Validating after-prepare arguments.
Hook completed
Transferring project files...
Transferring all files.
PlistService sending: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>VendContainer</string>
	<key>Identifier</key>
	<string>com.folio3.atlona</string>
</dict>
</plist>

An error has occured: TypeError: Cannot read property 'nodeName' of null
Removing device file 'Library/Application Support/LiveSync/app/pages/opportunity/opportunity.detail.component.html', result: 0
transfer-> localFilePath: '/Users/it/Documents/AtlonaRepo/Atlona_git/platforms/ios/Atlonagit/app/pages/opportunity/opportunity.detail.component.html', devicePath: 'Library/Application Support/LiveSync/app/pages/opportunity/opportunity.detail.component.html', localFilePathSize: '8646', transferred bytes: '8646'
Successfully transferred all files.
Applying changes...
PlistService sending: 
0hlist00�WCommandTName_ObserveNotification_5com.folio3.atlona:NativeScript.Debug.AlreadyConnected
PlistService sending: 
0flist00�WCommandTName_ObserveNotification_3com.folio3.atlona:NativeScript.Debug.ReadyForAttach
PlistService sending: 
0glist00�WCommandTName_ObserveNotification_4com.folio3.atlona:NativeScript.Debug.AttachAvailable
PlistService sending: 
bplist00�WCommandTName]ClientOptions_PostNotification_<com.folio3.atlona:NativeScript.Debug.AttachAvailabilityQuery*=|}
The application com.folio3.atlona does not appear to be running on Shagird or is not built with debugging enabled.

**Comment by tsonevn** [comment]
Hi @zsf3,

Since NativeScript 2.5, `tns run ios` command will start live sync automatically. Could you verify, whether you will have the same behavior with run command?

**Comment by dtopuzov** [comment]
Can't reproduce with {N} 3.0.0 RC and `tns run ios` on angular projects.
Close due to inactivity.
