### ISSUE TITLE
No livesync with Android, because "No such file or directory" error

### ISSUE THREAD

**Issue by Humberd** [NativeScript/nativescript-cli#2546]
I'm doing [this tutorial](http://docs.nativescript.org/tutorial/chapter-1) and the only commands I used were:
 * `tns create HelloWorld --template nativescript-template-tutorial`
 * `tns run android`

The app starts ok, but whan I edit any file the emulator doesn't show changes. Here is what shows the console:
```
Executing before-prepare hook from F:\Repositories\WebStorm\HelloWorld\hooks\before-prepare\nativescript-dev-android-snapshot.js
Preparing project...
Project successfully prepared (android)
Executing after-prepare hook from F:\Repositories\WebStorm\HelloWorld\hooks\after-prepare\nativescript-dev-android-snapshot.js
Transferring project files...
Unable to sync files. Error is: ENOENT: no such file or directory, stat 'F:\Repositories\WebStorm\HelloWorld\platforms\android\src\main\assets\app\main-page.js___jb_tmp___'

```

**Comment by rosen-vladimirov** [comment]
Hey @Humberd ,
This is a reported issue in our 2.5.0 release. You can find more information [here](https://github.com/NativeScript/nativescript-cli/issues/2476).
We are preparing 2.5.1 release, that should fix this problem. Meanwhile you can try installing our `next` version, which is published from CLI's master branch:
```
npm i -g nativescript@next
```

Please note that `@next` is a development release and you may face other issues, but we'll be glad if you can give it a try and see if it fixes your issue.

I'm closing this issue as it's a duplicate. We can continue the communication in the other thread.
