### ISSUE TITLE
Own option

### ISSUE THREAD

**Issue by vincentpalita** [NativeScript/nativescript-cli#2548]
Hello,

I searched issues but didn't find anything about it.
I would like to be able to pass options that are not included in the nativescript-cli list.
Is it possible?

For example:
tns run ios --emulator --watch --environment=integration

As of now I get the following error:
The option 'environment' is not supported. To see command's options, use '$ tns help run'. To see all commands use '$ tns help'.

Thank you for your help,
Vincent

**Comment by rosen-vladimirov** [comment]
Hey @vincentpalita ,
Thanks for your idea. At the moment it is not possible to pass such options as CLI validates all data passed. It's a kind of a strict validation 😺 
We'll consider your idea, but can you share some more details regarding your requirements. What's the purpose of the `environment` argument? Do you have different environments, like `test`, `pre-live`, `live` or you need something like project configurations (`debug`, `release`)?

**Comment by vincentpalita** [comment]
Hey @rosen-vladimirov ,
Thanks for getting back to me!
Well we have in our case multiple environments like development, test, demo, live.
Each environment has its own settings for API or tier products keys (Google, etc...).
As of now we are manually switching the configuration ourselves. But this is subject to errors and of course harder to include the project in a CI platform.
Hope I gave you the details you needed.

**Comment by dtopuzov** [comment]
Hi @vincentpalita we have similar situation and here is hot we solve it:

We use hooks, inside those hooks we read values from environment variables and replace placeholder some file which act the role of configuration.

I don't believe passing options to CLI commands is good way to modify your app.

**Comment by vincentpalita** [comment]
Hi @dtopuzov thanks for your message. Well I don't really agree with you about the fact that it's not a good way to "modify your app" while passing options to CLI commands.

It is currently a method used by numerous systems such as angular-cli with the argument --environment.

We are not looking to "modify the app" but to change the configuration at startup.
We will look into hooks method since there are no ways to configure that part of with the current nativescript cli.

Thanks

**Comment by Guatom** [comment]
This would be a very nice feature.

**Comment by rosen-vladimirov** [comment]
At the moment you can use `--env` to pass any kind of variables and respect them in webpack.config.js for example. 
```
tns build android --env.myVariable valueOfMyVariable
```
I'm closing this thread, feel free to reopen it in case you think the suggested solution is not applicable for your use case.

**Comment by jitendraashutec** [comment]
@rosen-vladimirov 

Can I pass custom variable in `tns test` command?
I want to do like: `tns test ios --emulator --env.project=my_project` and use project variable into webpack and in my custom hook.
