### ISSUE TITLE
Bug while building for release iOS application with Xcode, which has plugin with CocoaPods 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#2552]
The below-given error will be displayed when you try to build an app for release while using Xcode
```
didiff: /../Podfile.lock: No such file or directory
didiff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
``` 
Workaround
To workaround this behavior you could follow the below-described steps.
1. remove platforms folder from the project -> `rm -rf platforms` 
2. run `tns prepare ios` command
3. `cd platforms/ios`
4. run `pod install`
5. open with Xcode `<project_folder>/platforms/ios/<project_name>.xcworkspace` file
6. open the project `Build Settings`
7. scroll down to the end of the file and look for `PODS_ROOT`
8. the final steps is to copy the path from `Debug` flag and to set the set the same path for `Release`.

**Comment by imtodor** [comment]
In addition to the above changes, it might be necessary to change the Preprocessor Macros of the Debug and Release under Build Settings to become:

![screen shot 2017-02-21 at 16 21 06](https://cloud.githubusercontent.com/assets/1559936/23168831/41c8d7cc-f852-11e6-9f27-38d00ce1f0c2.png)

The initial issue is that the Release is empty and the Debug has the two valies "COCOAPODS=1 DEBUG=1".

**Comment by Natalia-Hristova** [comment]
I can confirm that the same errors still appear with `CLI 3.4.2` `Xcode 9.2` `cocoapods 1.4.0`. Used [nativescript-iqkeyboardmanager](https://github.com/tjvantoll/nativescript-IQKeyboardManager) plugin to test it.

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

**Comment by lambourn** [comment]
@Natalia-Hristova does this help https://github.com/NativeScript/NativeScript/issues/5150

**Comment by rosen-vladimirov** [comment]
This issue should be fixed by https://github.com/NativeScript/nativescript-cli/pull/4559
You can try it with latest official CLI and reopen it in case you still reproduce it.
