### ISSUE TITLE
--clean option ignored

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/nativescript-cli#2556]
Using CLI 2.5.1 and iOS

When running emulator commands with the `--clean` option, the CLI will still skip the prepare, build and install steps if an app has been previously installed. Testing with the iOS simulator.

This occurs with both the `tns run ios --emulator --clean` and `tns emulate ios --clean` commands.

**EXPECTED RESULT:**
Using the `--clean` flag would force a complete prepare, build, install of the app in the simulator, regardless of previous installs.

I did not try to use this command flag prior to 2.5.1, so not sure if this is new behavior or behavior that existed before 2.5.1.

**Comment by jacargentina** [comment]
I can confirm the behaviour: i was having a hard time changing the iOS app icons (the only way to make a complete rebuild i've found is:  `tns platform remove ios; tns platform add ios; tns build ios`

**Comment by toddanglin** [comment]
Interesting. Usually just doing a `tns prepare` and `tns build` or even a `tns deploy` is enough to get new assets deployed to a native app package. Did you try using those commands before removing/re-adding the platform folder? Curious if they were not working for you, too.

**Comment by yyosifov** [comment]
We've updated the `--clean` option to work like this:

- On initial start Rebuilds the application
- On changes in the App code, it doesn't rebuild - it leaves the livesync do it's job.

The problem with iOS app icons is unrelated to this issue. There was a problem with Livesyncing the App_Resources folder, where the resources are located. This is fixed, too.
