### ISSUE TITLE
Ctrl + C shortcut does not stop the livesync 

### ISSUE THREAD

**Issue by OscarLopezArnaiz** [NativeScript/nativescript-cli#2558]
Hi guys!

Really enjoying NS 2.5.0 but one of the thing I get confused is that Ctrl + C does not stop livesync session anymore. I need to close terminal session in order to make a build from scratch. Its great to have a robust livesync session but you should be able to eventually stop it. 

Any chance we can get back Ctrl + C shorcut to end up livesync session. 

Thanks

**Comment by Plamen5kov** [comment]
@OscarLopezArnaiz I can't reproduce the problem with latest cli `npm install -g nativescript@next`. Other than that, can you provide more information about the specific versions you're using: CLI and component versions?

**Comment by dtopuzov** [comment]
`tns livesync` is deprecated in flavor of `tns run` and Ctrl + C work for me with {N} 3.0.0 RC and `tns run`.
