### ISSUE TITLE
Confusing messages when upgrading 

### ISSUE THREAD

**Issue by PetyaSotirova** [NativeScript/nativescript-cli#2570]
I'm trying to upgrade to 2.5 and I ran `tns doctor`. I'm receiving somewhat confusing logs to the point that I'm really not sure whether or not I have an issue in the environment and if I should file it. I suggest we make those more consistent.
Here's what I'm seeing:

npm WARN nativescript-check-cocoapods@0.0.1 No description
npm WARN nativescript-check-cocoapods@0.0.1 No repository field.
npm WARN nativescript-check-cocoapods@0.0.1 No license field.

  ◝ Verifying CocoaPods. This may take some time, please be patient..
You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=25.0.2'.
Run android from your command-line to install required Android Build Tools.

There seem to be issues with your configuration.
? Do you want to visit the official documentation? No
? Do you want to run the setup script? No
Your components are up-to-date.

When you file an issue, these warnings will help the NativeScript team to investigate, identify, and resolve the report.
Please, ignore them if you are not experiencing any issues with NativeScript.

**Comment by DannyFeliz** [comment]
Im getting the message "You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=25.0.2'."

**Comment by kwong93** [comment]
I am also getting "You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=25.0.2'." I ran "android" from command line in my NS project, and I have Android SDK Build-tools 25.0.2 installed

**Comment by TheOriginalJosh** [comment]
I getting the same error `You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=25.0.2'.` I tried fixing it by running `android` from the command line. uninstalling all of my existing Android SDK Build-tools and then re-install just version `25.0.2`  however if I run `tns doctor` I'm still getting the same error.  I

**Comment by kwong93** [comment]
Solved my problem above. The ANDROID_HOME path in my bash_profile file was not pointing to sdk path listed in the SDK manager when 'android' is entered in the command line. Modified it to point to the correct path, and installed 25.0.2 build tools.

**Comment by Plamen5kov** [comment]
@PetyaSotirova 
> You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=25.0.2'. Run android from your command-line to install required Android Build Tools.

This means you need to update the build-tools version to >= 25.0.2, with a suggestion of how that might happen.

---
> There seem to be issues with your configuration. 

This message is shown when there's a problem with the build tools or java version, as is in this example.

---
> Your components are up-to-date.

This means CLI tns-modules and tns-android(ios) are the latest, and are all up-to-date.
(I can see how this message might confuse users, so we can discuss a more precise message, explaining better what "components" means.

Please give your comments and suggestions about improving this.

**Comment by PetyaSotirova** [comment]
If my NS components are up to date but I have other config issues, here's the order in which I suggest we notify the user:
 1.  Your NativeScript components are up to date.
  2. There are issues with your configuration that might prevent you from working with NativeScript. Please resolve the following:
  3. [Whatever warnings there are, in this case, I need Android SDK Built tools >=25.0.2]
  4. Prompt to resolve the warnings if possible (Do you want to visit the docs?, Do you want to run the script?)
  5. If I still have issues, tell me so - "There are still issues with your configuration. Please resolve the following:
  [The warnings again]
"If you are unable to resolve the warnings, please file an issue and send these warnings to the NativeScript team to investigate, identify, and resolve the report."

**Comment by rosen-vladimirov** [comment]
As we are no longer checking the environment on post-install, this issue is no longer valid, so I'm closing this thread.
