### ISSUE TITLE
Error: sed: invalid replacement string

### ISSUE THREAD

**Issue by shivapersad** [NativeScript/nativescript-cli#2584]
Good day,

I ran "tns platform remove android" and then ran "tns platform add android" but the add command does not complete. I am presently receiving the following error message when attempting to add the android platform:

sed: invalid replacement string

Your assistance is appreciated.

**Comment by shivapersad** [comment]
node -v
v7.7.1

npm -v
4.3.0

tns --version
2.5.2

**Comment by shivapersad** [comment]
I resolved the issue. I changed "nativescript" -> "id" to another value and this caused the issue apparently.

**Comment by rcsoares** [comment]
Your "nativescript" -> "id" need to have 3 words like "br.com.myapp". This works for me.
If you change this, don't forget to change applicationId on app/App_Resources/Android/app.gradle
