### ISSUE TITLE
No longer see Angular template parsing errors on Android

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#2603]
If you create template parsing errors in your NativeScript + Angular apps those errors no longer appear on Android.

To recreate the problem, start a simple NativeScript + Angular app and use the following code for the app’s main component.

``` TypeScript
import { Component } from "@angular/core";

@Component({
  selector: "my-app",
  template: `
    <ActionBar class="action-bar"
    <Label text="Test"></Label>
  `
})
export class AppComponent {}
```

If you run this app on iOS you’ll see a template parsing error as expected.

```
file:///app/tns_modules/@angular/compiler/bundles/compiler.umd.js:13601:78: JS ERROR Error: Template parse errors:
	Unexpected closing tag "Label" ("
	    <ActionBar class="action-bar"
	    <Label text="Test">[ERROR ->]</Label>
	  "): AppComponent@2:23
```

On Android, however, the developer-friendly error seems to have been swallowed, and instead you’ll see the following.

![screen shot 2017-03-10 at 2 04 51 pm](https://cloud.githubusercontent.com/assets/544280/23809189/ace21ba4-059a-11e7-82e9-0ba0888711f2.png)

The error mentions the same file (`compiler.umd.js`), but the helpful message is nowhere to be found.

Note that this problem is affecting chapter 1 of the Angular Getting Started Guide, and was reported by a user in https://discourse.nativescript.org/t/ns-tutorial-chapter-1-3-syntax-error-handling-not-working/744.

**Comment by tjvantoll** [comment]
I’m using the version 2.5.2 of the CLI, version 2.5.1 of tns-core-modules, version 1.4.1 of nativescript-angular, and version 2.5.0 of the Android runtime. I tried using the “next” builds but ran into a few issues, so unfortunately I was not able to test with those.

**Comment by luciansr** [comment]
This is not a https://github.com/NativeScript/android-runtime issue?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#721
