### ISSUE TITLE
Issue with development in Windows AND Mac

### ISSUE THREAD

**Issue by irman** [NativeScript/nativescript-cli#2613]
My main development machine is on Windows, to develop for Android of course, but when it's time to release/test, I'll push my stuffs to gitlab and pull it on my Mac. And whenever I ran `tns update` on either of this machine, the cli will always switch up the `tns-android` & `tns-ios` on `package.json` which in turn triggered the changes on the git, which I personally think it is unnecessary. Refer below:

![image](https://cloud.githubusercontent.com/assets/6107943/23984185/22b46122-0a53-11e7-9698-836745402737.png)

I understand why this is happening, but can we just pick one order? `tns-ios` first or `tns-android` first it doesn't matter as long as it stays that way.

Hopefully this won't involve a lot of work. Thanks!

**Comment by NickIliev** [comment]
@irman at my side executing `tns update` produces the same order (ios is first) on both Windows and Mac.
If yu can reproduce this with a new project please share the exact steps needed to recreate this case.

**Comment by dtopuzov** [comment]
`tns update` always use the same order:
- platform update android
- platform update ios
If you once set the order in your package.json like this you will have no reorder issues in future.
