### ISSUE TITLE
No validation for invalid folder specified in --copy-from

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#262]
Execute:
tns create TestApp --copy-from <not existing folder>

Result:
cp: no such file or directory: <current_path>\<not existing folder>\*
Project TestApp was successfully created

app and tns_modules folders are empty and only .tnsproject is created

May be it will better if tns reports and error because TestApp is not created successfully.

**Comment by Fatme** [comment]
`tns create myApp --copy-from` reports the following message `The option 'copy-from' requires a value.`
