### ISSUE TITLE
"spawn EACCES" when trying to build app, or install plugins via tns

### ISSUE THREAD

**Issue by travs** [NativeScript/nativescript-cli#2626]
My inputs/outputs:
```
$ tns run android
Skipping prepare.
Searching for devices...
Building project...
spawn EACCES
```
and
```
$ tns plugin remove nativescript-mapbox
spawn EACCES
```

It appears there is something wrong with permissions somewhere in my stack, but I am not sure where. 

I reinstalled nativescript after this error started to occur, using `npm install -g --unsafe-perm nativescript`, as per [this issue](https://github.com/NativeScript/nativescript-cli/issues/477#issuecomment-101610923), and the problem persisted.

Happens on node v6.9.1 and v6.10.0, using tns version 2.5.3.
I am on OS X 10.12.3 (Sierra).

## Update
I tried using the more verbose `tns plugin remove nativescript-mapbox --log trace`, and the output is [here](https://gist.github.com/travs/6d5b20928da44f03e20836cdf1bb0702).

**Comment by travs** [comment]
## Fix
I just did `tns platform remove android; tns platform add android` and the problem seems to have fixed itself.
Logging my fix here for anyone else that encounters a similar issue, but I can't explain why this worked.

Cheers!

**Comment by alereisan** [comment]
This error appears really often, at least on my mac.
Cleaning the folders and re-building is time-consuming is there no quicker way to solve this issue?
