### ISSUE TITLE
Incorrect platform-tools/adb permissions on Linux

### ISSUE THREAD

**Issue by stevelacy** [NativeScript/nativescript-cli#263]
#113 brought up an issue where the `platform-tools/adb` command has the wrong permissions. The commits added to close that issue did Nothing to solve the actual issue.

`nativescript/resources/platform-tools/android/linux/adb` Still has incorrect permissions and should be set to +x

**Comment by rosen-vladimirov** [comment]
Hi @stevelacy 

I've just tried installing latest nativescript-cli release and "adb" has correct permissions: -rwxrwxr-x
Please note that we've moved it to be under ```nativescript/lib/common/resources/platform-tools/android/linux```
Could you try latest nativescript-cli release and see if it adb has correct permissions on your side?

**Comment by stevelacy** [comment]
The latest release does have correct permissions `rwxr-xr-x`.

Thanks
