### ISSUE TITLE
Guidance for new CLI users

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#2632]
# Problem description

New users may feel lost after installing the CLI for first time. It would be great to guide them through the "happy path". This should be unobtrusive to allow the experienced users to ignore the additional messages.

# Proposed work flow

I propose key CLI commands to have additional messages which guide the user to the next most likely command. The actual messages must be reviewed and agreed on.

## On installation
Add message: 

> To create a new NativeScript project, use `tns create name-of-project`. To get started with NativeScript CLI, use `tns help`.

## On `tns create`
Add message: 

> To continue with your project, `cd ${project-dir}`. Use `tns run ios` or `tns run android` to build and start your project on connected devices or emulators. To get started with NativeScript CLI, use `tns help`.

We can expand the work flow in the future but I think these steps are a good start.

**Comment by teobugslayer** [comment]
Ping @snikr

**Comment by rosen-vladimirov** [comment]
You can check the messages on post install of CLI and also after `$ tns create`.

**Comment by Natalia-Hristova** [comment]
Can confirm that the guidance is added. 
After installation user can see:

```
In order to create a new project, you can use:
tns create <app name>

To build your project locally you can use:
tns build <platform>

NOTE: Local builds require additional setup of your environment. You can find more information here: https://docs.nativescript.org/start/quick-setup


To build your project in the cloud you can use:
tns cloud build <platform>

NOTE: Cloud builds require Telerik account. You can find more information here: https://docs.nativescript.org/sidekick/intro/requirements


In case you want to experiment quickly with NativeScript, you can try the Playground: https://play.nativescript.org


In case you have any questions, you can check our forum: https://forum.nativescript.org and our public Slack channel: https://nativescriptcommunity.slack.com/

```

and after `tns create`:
```
Now you can navigate to your project with $ cd SomeApp
After that you can run it on device/emulator by executing $ tns run <platform>
```
