### ISSUE TITLE
`tns run android --no-watch` does not work as described in help.

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2635]
According to CLI command line help:
```
* --no-watch - If set, changes in your code will not be reflected during the execution of this command.
```

Actual behavior with master branch:
All changes are synced.

Steps to reproduce:
`tns run android --emulator --no-watch` and start making changes on the project.

Ideas:
`--no-watch` is almost the same as `--justlaunch`.
We can remove `--no-watch` or at least hide it from help.

**Comment by NathanaelA** [comment]
No, NO please do NOT remove **--no-watch.**  

We need this in some cases:
1. I'm demo'ing (don't want the app reseting under me, when I show/edit code).   
2. I'm doing debugging; in some cases when I am stepping through code; I don't actually want my changes to be applied until I'm totally done with the session and restart the debugging.

**Comment by yyosifov** [comment]
We won't remove it, we just fixed it to work as it did before.
