### ISSUE TITLE
Removed files are not sync correctly on android with `@next` version

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#2641]
### Tell us about the problem
During `tns run android` in case a file is removed from the application, it's not propagated to the device.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: `@next`
- Cross-platform modules: 2.5.0
- Runtime(s): tns-android 2.5.0
- Plugin(s): 

### Please tell us how to recreate the issue in as much detail as possible.
On any project run `tns run android` and after that delete a file from `app` dir (for example the entry point of app). You'll notice that application is working fine on device, so the file is not removed.

**Comment by newgerstas** [comment]
Did someone solve the problem? I get this problem for  tns 2.5.4 also.

**Comment by dtopuzov** [comment]
It is solved in master branch, so it will be delivered officially with {N} CLI 3.0.0.

If you want to test it now, please use:
`npm i -g nativescript@next` or `npm i -g nativescript@rc`
