### ISSUE TITLE
Please guys i need help

### ISSUE THREAD

**Issue by anassfiqhi** [NativeScript/nativescript-cli#2652]
I can't use my phone for run my native script application because the phone is not detected 
 android device has the Developer Options enabled and that the "USB Debugging" option is checked

/*****************************/
this is what i see in cmd
/****************************/

```
C:\Users\Anass\Documents\nativescript\Groceries
λ tns run android
Skipping prepare.
Searching for devices...
Could not find an emulator image to run your project.
# run android
...
```

**Comment by Daxito** [comment]
Make sure your android device has the Developer Options enabled and that the "USB Debugging" option is checked, you did not mention you already have those enabled so... try.

**Comment by anassfiqhi** [comment]
Developer Options enabled and that the "USB Debugging" option is checked

**Comment by Daxito** [comment]
I have seen issues like this with cables, try with a different cable and / or device or install a simulator in the meantime.

**Comment by anassfiqhi** [comment]
@Daxito 
i try it with another device and this what they give me .








C:\Users\Anass\Documents\nativescript\learning                                        
λ tns run android                                                                     
Skipping prepare.                                                                     
Searching for devices...                                                              
Could not find an emulator image to run your project.                                 
# run android                                                                         
                                                                                      
┌─────────────────┬───────────────────────────────────────────────────────────────┐   
│ Usage           │ Synopsis                                                      │   
│ Run on all      │ $ tns run android [--key-store-path <File Path> --key-store   │   
│ connected       │ -password <Password> --key-store-alias <Name> --key-store     │   
│ devices and     │ -alias-password <Password>] [--release] [--justlaunch]        │   
│ running         │                                                               │   
│ emulators       │                                                               │   
│ Run on a        │ $ tns run android --device <Device ID> [--key-store-path      │   
│ selected        │ <File Path> --key-store-password <Password> --key-store-alias │   
│ connected       │ <Name> --key-store-alias-password <Password>] [--release] [-  │   
│ device or       │ -justlaunch]                                                  │   
│ running         │                                                               │   
│ emulator        │                                                               │   
│ Start an        │ $ tns run android --emulator [<Emulator Options>] [--key      │   
│ emulator and    │ -store-path <File Path> --key-store-password <Password> --key │   
│ run the app     │ -store-alias <Name> --key-store-alias-password <Password>] [- │   
│ inside it       │ -release] [--justlaunch]                                      │   
└─────────────────┴───────────────────────────────────────────────────────────────┘   
                                                                                      
Runs your project on a connected Android device or in a native Android emulator, if co
nfigured. This is shorthand for prepare, build and deploy. While your app is running, 
prints the output from the application in the console and watches for changes in your 
code. Once a change is detected, it synchronizes the change with all selected devices 
and restarts/refreshes the application.                                               
                                                                                      
### Options                                                                           
                                                                                      
    * --no-watch - If set, changes in your code will not be reflected during the execu
tion of this command.                                                                 
    * --device - Specifies a connected device/emulator on which to run the app.       
    * --emulator - If set, runs the app in a native emulator for the target platform, 
if configured. When set, you can also set any other valid combination of emulator opti
ons as listed by $ tns help emulate android.                                          
    * --release - If set, produces a release build. Otherwise, produces a debug build.
 When set, you must also specify the --key-store-* options.                           
    * --key-store-path - Specifies the file path to the keystore file (P12) which you 
want to use to code sign your APK. You can use the --key-store-* options along with --
release to produce a signed release build. You need to specify all --key-store-* optio
ns.                                                                                   
    * --key-store-password - Provides the password for the keystore file specified wit
h --key-store-path. You can use the --key-store-* options along with --release to prod
uce a signed release build. You need to specify all --key-store-* options.            
    * --key-store-alias - Provides the alias for the keystore file specified with --ke
y-store-path. You can use the --key-store-* options along with --release to produce a 
signed release build. You need to specify all --key-store-* options.                  
    * --key-store-alias-password - Provides the password for the alias specified with 
--key-store-alias-password. You can use the --key-store-* options along with --release
 to produce a signed release build. You need to specify all --key-store-* options.    
    * --justlaunch - If set, does not print the application output in the console.    
    * --clean - If set, forces rebuilding the native application.                     
                                                                                      
### Attributes                                                                        
                                                                                      
    * <Device ID> is the index or name of the target device as listed by $ tns device 
android                                                                               
    * <Emulator Options> is any valid combination of options as listed by $ tns help e
mulate android

**Comment by Daxito** [comment]
The I would think a problem with your cable.... try with a emulator.

**Comment by anassfiqhi** [comment]
@Daxito 
i can't try with emulator my computer is super slow so that's why i'm using physical device (samsung s5 and  one plus 3)

**Comment by Daxito** [comment]
oh man, well, then maybe the cable is the issue, maybe.

**Comment by anassfiqhi** [comment]
@Daxito 
i have tried with other cable with oneplus 3

**Comment by dtopuzov** [comment]
Please run following and post the result:
`%ANDROID_HOME%\platform-tools\adb devices`

If `adb` cannot find your devices it is something that is related to Android tooling itself.
May be you need to install drivers for those devices.

**Comment by dtopuzov** [comment]
Close due to inactivity, please re-open if still encounter problems with devices.
