### ISSUE TITLE
`tns run android/ios` does not remove folders correctly

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2657]
### Which platform(s) does your issue occur on?
Android and iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0-2017.3.24.5

### Please tell us how to recreate the issue in as much detail as possible.
```
tns create MyApp
code MyApp (open the app in VSCode)
tns run android --path MyApp
Create new folder, add some js file -> File is there.
Delete the folder -> file is removed, but folder is available on still on device
```

Notes:

How to files on device: `adb shell run-as org.nativescript.MyApp ls /data/data/org.nativescript.MyApp/files/app/`

I'm not able to break livesync or crash the app.
It is just some garbage that we do not clean.

**Comment by Plamen5kov** [comment]
related: https://github.com/NativeScript/nativescript-cli/issues/2890#issuecomment-311017175

**Comment by dtopuzov** [comment]
Sill valid.
Tested with Api23 default emulator on macOS -> no issue.
Tested with the same Api23 default emulator on Linux and Windows -> The issue still exists.

**Comment by miroslavaivanova** [comment]
This issue is fixed.
