### ISSUE TITLE
build commands failed CompileAssetCatalog....Assets.xcassets

### ISSUE THREAD

**Issue by nassimus26** [NativeScript/nativescript-cli#2664]
Hi, i already try to find the solution in stackoverflow, i already try tns doctors : got no issues 

I am trying to build a HelloWorld tutorial with the last Xcode 8.3 and the 2.5.2 tns

The android builds and run fine on windows, but on MacOsx Sierra the build faileds with  : 

```
2017-03-28 09:14:28.860 xcodebuild[1015:18817]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11758/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
Details:  unexpected successful exit code from cancelled command <C0013:'CpResource app':P12>
Object:   <PBXTargetBuildContext: 0x7fca5d40d650>
Method:   -createCommandInvocationRecordFromInvocation:
Thread:   <NSThread: 0x7fca62232b00>{number = 6, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

** BUILD FAILED **


The following build commands failed:
	CompileAssetCatalog build/emulator/HelloWorld.app HelloWorld/Resources/Assets.xcassets
(1 failure)
Command xcodebuild failed with exit code 65
```
Then i try the Groceries Sample i got this Build Errors :
```
** BUILD FAILED **

The following build commands failed:
	CompileStoryboard g/Resources/LaunchScreen.storyboard
	CompileAssetCatalog build/emulator/g.app g/Resources/Assets.xcassets
(2 failures)
Command xcodebuild failed with exit code 65

```

**Comment by dtopuzov** [comment]
Hi @nassimus26 

I can not reproduce the issue, here is how I test:

```
npm un -g nativescript
npm cache clean
npm i -g nativescript
tns create TestApp
tns run ios --emulator --path TestApp
```

Output of `xcodebuild -version`:
```
Xcode 8.3
Build version 8E162
```

**Comment by nassimus26** [comment]
It related to the fact that i build on a Shared Virtual Machine Folder (its not considered as real folder), so it cause many issues, its not related to NativeScript , Sorry and Thanks

**Comment by devMls** [comment]
Hi, I have the same issue, 

The problem is that i can't build in a virtualbox virtual macox???

Is not posible without a real mac?

**Comment by yalva** [comment]
@nickmeehan which files names? all of my resource files have '@' in their name, not sure which files I need to rename?

**Comment by delanick** [comment]
Also experiencing this issue aftger upgrading to NS6.

**Comment by delanick** [comment]
@nickmeehan did you manage to sort this out?
