### ISSUE TITLE
Command line `tns run android --clean` rebuilds

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2670]
### Tell us about the problem
If you use `tns run android --clean` it does a full rebuild on EVERY single file change.  --clean should do an initial rebuild for the first run, but then all other changes should be simple livesyncs.

### Which platform(s) does your issue occur on?
Android for sure, probably on iOS also.

### Please provide the following version numbers that your issue occurs with:
2.5.1 CLI

### Please tell us how to recreate the issue in as much detail as possible.
1. tns run android --clean
2. Change an xml file, watch it rebuild the app again.

**Comment by yyosifov** [comment]
@NathanaelA We've fixed the issue. It was working backwards - "clean" wasn't forcing the first run to rebuild but every change afterwards resulted in rebuild. Now we've fixed the behavior - clean starts with rebuild and from this time on the livesync handles the changes.

Thanks for reporting it!

**Comment by webleaf** [comment]
Same issue in `tns --version 4.2.4`

**Comment by DimitarTachev** [comment]
@webleaf, thanks for reporting that.
