### ISSUE TITLE
How can I add suggestions to the documentation for Linux?

### ISSUE THREAD

**Issue by ToJen** [NativeScript/nativescript-cli#2681]
I run Ubuntu 16.04.

While setting up NativeScript, I spent a lot of time on stuff that wasn't covered in the [documentation](http://docs.nativescript.org/start/ns-setup-linux). 

Is there a way I can edit that page?

**Comment by dtopuzov** [comment]
Hi @ToJen 

We really appreciate your willingness to help us.
If you want to contribute to documentation  you can make pull requests in (this)[https://github.com/NativeScript/docs] repository.
