### ISSUE TITLE
[3.0@rc] App_Resources being copied into app RAW

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2697]
### Did you verify this is a real problem by searching 
Yes - this might be related to the https://github.com/NativeScript/nativescript-cli/issues/2586 but that was specifically talking about .android and .ios files being duplicated into the final app on the second build.  There is a possibility that this is also being duplicated at the same  time.    

### Tell us about the problem
I noticed my test app was huge; so I opened up the APK and found that all my resources were being copied into the \platforms\android\src\main\assets\app which then meant they were being build into the APK.  I not only had the android resources duplicated; but all the iOS resources where in the app/App_Resources folder inside the APK also.  So I ended up with another 10megs of resources that were duplicated into the app.

### Which platform(s) does your issue occur on?
Android (No idea if anything like this is happening on iOS)

### Please provide the following version numbers that your issue occurs with:
TNS 3.0.0-RC1

### Please tell us how to recreate the issue in as much detail as possible.
I believe build the app a couple times; you might need something to trigger a prepare; as I reset the platform folder earlier today; but I have built the app with new plugins since that point.

I can tell you for sure a fresh reset of the platform, and the app is built properly the first time.  (15megs instead of 25megs -- easy difference to see).

**Comment by dtopuzov** [comment]
Confirmed, this is a bug.

Steps to reproduce:
```
tns create TestApp
tns build android --path TestApp
cp TestApp/app/app.js TestApp/app/new.android.js (create new platform specific file)
tns build android --path TestApp
```

Result: `TestApp\platforms\android\src\main\assets\app\App_Resources` exists
