### ISSUE TITLE
Unable to run with webpack and CLI from master for android

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2707]
Details:
User is unable to run the application with webpack and CLI from master for android, as it doesn't manage to clean properly the platforms folder.

Steps to reproduce:
```
npm install -g nativescript@next # 3.0.0-2017-04-11-8607
tns create appJS && cd appJS
tns run android
npm install --save-dev nativescript-dev-webpack
npm run start-android-bundle
```

Log:
```
:asbg:runAstParser
Running incremental build
finished with reading lines with js files
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
/Users/vchimev/Work/tmp/appJS/platforms/android/src/main/java/com/tns/NativeScriptActivity.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vchimev/Work/tmp/appJS/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.98 secs
Multiple errors were thrown:
Command ./gradlew failed with exit code 1
```

Workaround:
```
rm -rf appJS/platforms/android
```

Suspected commit:
https://github.com/NativeScript/nativescript-cli/commit/8dedbcdefef39b70822caad42b84dbc22c51551b

**Comment by vchimev** [comment]
This issue has been handled in the *nativescript-dev-webpack* plugin to use `platform remove/add` instead of clean-app command: https://github.com/NativeScript/nativescript-dev-webpack/pull/116

@dtopuzov, @rosen-vladimirov, @yyosifov, @sis0k0

What do you think to delete the *magic* `clean-app` command, If we are going to stick to this behavior?

**Comment by sis0k0** [comment]
@vchimev,

Let's just deprecate it instead of removing it.

**Comment by pkoleva** [comment]
Let's decide what to do with the option and the close the issue.

**Comment by sis0k0** [comment]
Let's keep it. I hope we can use it in the future instead of `platform-remove`, `platform-add` before bundling. There are some issues now with the android runtime which requires a bit more cleanup.

**Comment by dtopuzov** [comment]
Closing this issue, since the original issue is fixed: 
`Unable to run with webpack and CLI from master for android` 
If we want to do something with *magic* `clean-app` command let's log separate issue.
