### ISSUE TITLE
[Android] nativescript.id requires app name subdomain

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-cli#2709]
I have the following package.json:
```
{
  .......
  "nativescript": {
    "id": "com.tangrainc",
   }
   .......
}
```

If you you do:
```
tns platform add ios
```
This works and adds fine the iOS platform and the you an compile the app w/o any problems. 

But if you do:
```
tns platform add android
```
The process fails with the following error:
```
sed: invalid replacement string
```
If I change the `id` to `com.tangrainc.app` the android process also completes fine. 

**Expected:**
The android workflow should allow for creating apps with "top-level" IDs w/o requiring an app "subdomain" similar to how it works for iOS.

**Comment by Pip3r4o** [comment]
Hey @PeterStaev 

Thank you for reporting this issue.

The problem has already been addressed with PR https://github.com/NativeScript/nativescript-cli/pull/2595 and is immediately available in `nativescript@3.0.0-rc`. The fix will also be available in our upcoming public `3.0.0` release.
