### ISSUE TITLE
No validation for invalid options in create command

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#271]
Steps to reproduce:
tns create TestApp --copyFrom ..\sample-Tasks

Result:
"Project TestApp was successfully created" is dispalyed, but content of TestApp  is the default one (--copy-from is not respected)

Expected:
When some of the create command options is wrong I should see appropriate error message.

**Comment by rosen-vladimirov** [comment]
this seems related to https://github.com/NativeScript/nativescript-cli/issues/262
