### ISSUE TITLE
[TNS 3.0 rc] - xcrun: error: unable to find utility "PackageApplication"

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-cli#2725]
_From @NathanWalker on April 19, 2017 23:41_

XCode 8.3 deprecated this tool however even when installing 3.0 rc and creating new project it appears it's still trying to use this. Steps to repo:

* `tns create MyApp --template tns-template-hello-world-ts@rc`
* `cd MyApp`
* Plug it an actual iPhone, `tns devices` to get it's id
* `tns run ios --device <device id>`

> xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH

_Copied from original issue: NativeScript/ios-runtime#751_

**Comment by dtopuzov** [comment]
Hi @NathanWalker 

This is an issue that we fixes after we published nativescript@rc.
Can you try with `npm i -g nativescript@next`, it should be fixed there.

Regards,
Dimitar
