### ISSUE TITLE
how can i use nativescript plugin written with typescript inside nativescript with vanilla javascript project

### ISSUE THREAD

**Issue by webenformasyon** [NativeScript/nativescript-cli#2726]

**Comment by NickIliev** [comment]
Hey @webenformasyon 

All the *.ts files in a plugin written in TypeScript will be transpiled to JavaScript so you don;t have to worry if the plugin is written in TS or in JS. - just follow the normal workfolw
```
tns plugin add <name-of-the-plugin>
```
and then in your application
```
var myPluginModule = require("<name-of-the-plugin>");
```
