### ISSUE TITLE
Can't install Nativescript

### ISSUE THREAD

**Issue by Billmike** [NativeScript/nativescript-cli#2733]
I keep getting this error. What do i do?

C:\Users\GRACE SANDA>npm i -g nativescript
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/
highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Versions\Current -> A
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@
^4.0.0.
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead
C:\Users\GRACE SANDA\AppData\Roaming\npm\nativescript -> C:\Users\GRACE SANDA\Ap
pData\Roaming\npm\node_modules\nativescript\bin\tns
C:\Users\GRACE SANDA\AppData\Roaming\npm\tns -> C:\Users\GRACE SANDA\AppData\Roa
ming\npm\node_modules\nativescript\bin\tns

> nativescript@2.5.4 postinstall C:\Users\GRACE SANDA\AppData\Roaming\npm\node_m
odules\nativescript
> node postinstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.verifyNodeVersion (C:\Users\GRACE SANDA\AppData\Roaming\npm\node_m
odules\nativescript\lib\common\verify-node-version.js:6:5)
    at Object.<anonymous> (C:\Users\GRACE SANDA\AppData\Roaming\npm\node_modules
\nativescript\bin\tns:9:57)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
C:\Users\GRACE SANDA\AppData\Roaming\npm
`-- nativescript@2.5.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\na
tivescript\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

**Comment by NickIliev** [comment]
This error might be caused by **npm** caching issues. Try to resolve it with
```
npm cache clean
```

**Comment by dtopuzov** [comment]
@Billmike any update on this, do you still experience the issue?

**Comment by dtopuzov** [comment]
Close due to inactivity.

**Comment by kangkang07** [comment]
I still have this issue

PS C:\WINDOWS\system32> npm i -g nativescript
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
D:\Program Files\nodejs
`-- (empty)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
"-g" "nativescript"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
