### ISSUE TITLE
Webpack bundling of iOS failing?

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/nativescript-cli#2755]
I have cloned the release repo of Groceries app but the webpack bundle is failing -      

    Validate build/device/sampleGroceriesrelease5.app
    cd "/Users/Dlucidone/Downloads/sample-Groceries-release 5/platforms/ios"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Dlucidone/Downloads/sample-Groceries-release 5/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Dlucidone/Downloads/sample-Groceries-release 5/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/Dlucidone/Downloads/sample-Groceries-release\ 5/platforms/ios/build/device/sampleGroceriesrelease5.app -validate-for-store

    ** BUILD SUCCEEDED **

     xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
    Command xcrun failed with exit code 72

Any Help Thanks!

**Comment by dtopuzov** [comment]
Hi @dlucidone 

It is an issue with Xcode 8.3 that should be solved in {N} 2.5.4 and {N} 3.0.0 RC.
What is the output of `tns --version`?

**Comment by dlucidone** [comment]
@dtopuzov It is 2.5.1. I tried updating my tns version to 2.5.4 but its not available i guess and its also not listed in release tab in git repo. Will I be able to build using lower version of xcode. Since I'm afraid if any of the plugin i'm using will brake if i update my tns

**Comment by dtopuzov** [comment]
```
npm un -g nativescript
npm cache clean
npm i -g nativescript@2.5.4
```

I think update from `2.5.1` to `2.5.4` is safe and will not cause issues with plugins.

Alternative is to downgrade your Xcode to 8.2.1 (or latest before 8.3), it will work with {N} 2.5.1.

**Comment by dlucidone** [comment]
Okay Lemme check if it works, to make a release build i'm using this command but it is failing and the documentation over webpacking ios app need updation.

    npm run build-ios-bundle -- --release --for-device --copy-to 
    /yourpath/toyourapp/folder/yourappname_1-0-2.ipa --teamId 123YUT876Y --provision 
    80449b3b-312a-1290-78f6-64hh43kgh4439c8 

Can you tell me what is the issue? with this command

**Comment by dtopuzov** [comment]
Can you please post log with error message.
