### ISSUE TITLE
Build Error: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2756]
_From @mawoole on May 1, 2017 14:18_

Hi,

Please, can somebody help me generate .js files of all .ts files of https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app.

I did : 
tns build android
then:
Tsc

But it can't generate .js files.

Can you tell me the exact steps to get these .js files.

Thanks

_Copied from original issue: telerik/nativescript-ui-feedback#163_

**Comment by NickIliev** [comment]
@mawoole please notice that this repository is for log issues, bugs, and feature requests. Post similar question in one of the community channels like forum.nativescript.org

Regarding your issue - you should run `tns build android` from the root application folder (not in app but [one level above](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk)) 

Also, one of the steps in `tns build android` is tranpiling your *.ts files (calling **tsc**) so your JavaScript files should be generated already. Still calling `tsc` from your root folder (where we have **tsconfig.json**) will work as well.

**Comment by NickIliev** [comment]
_From @mawoole on May 1, 2017 15:6_

Thanks @NickIliev for your answer.

I ran _**tns build android**_  command from the root application folder H:\Dev\projects\nativescript-ui-samples-release\sdk\
but .JS files are not generated, and I got the following error :

**Found peer TypeScript 2.1.5
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

---------------------------------------
H:\Dev\projects\nativescript-ui-samples-release\sdk>tns build android
Executing before-prepare hook from H:\Dev\projects\nativescript-ui-samples-release\sdk\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from H:\Dev\projects\nativescript-ui-samples-release\sdk\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.1.5
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Project successfully prepared (android)
Executing after-prepare hook from H:\Dev\projects\nativescript-ui-samples-release\sdk\hooks\after-prepare\nativescript-dev-android-snapshot.js

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-fresco
        +found plugins: nativescript-telerik-ui-pro
        +found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\configurations\include.gradle
        +applying configuration from: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\configurations\nativescript-fresco\include.gradle
        +applying configuration from: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\configurations\nativescript-telerik-ui-pro\include.gradle

        +applying configuration from: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\configurations\tns-core-modules-widgets\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Chart-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Common-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Data-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Feedback-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Gauges-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Input-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\List-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\Primitives-2017.1.222-nstrial-release.aar
        +adding dependency: H:\Dev\projects\nativescript-ui-samples-release\sdk\platforms\android\libs\aar\widgets-release.aar
Observed package id 'system-images;android-15;default;armeabi-v7a' in inconsistent location 'C:\Users\A514038\AppData\Local\Android\android-sdk\system-images\android-15
\armeabi-v7a' (Expected 'C:\Users\A514038\AppData\Local\Android\android-sdk\system-images\android-15\default\armeabi-v7a')
Observed package id 'system-images;android-19;default;armeabi-v7a' in inconsistent location 'C:\Users\A514038\AppData\Local\Android\android-sdk\system-images\android-19
\armeabi-v7a' (Expected 'C:\Users\A514038\AppData\Local\Android\android-sdk\system-images\android-19\default\armeabi-v7a')
Observed package id 'system-images;android-23;default;armeabi-v7a' in inconsistent location 'C:\Users\A514038\AppData\Local\Android\android-sdk\system-images\android-23
\armeabi-v7a' (Expected 'C:\Users\A514038\AppData\Local\Android\android-sdk\system-images\android-23\default\armeabi-v7a')
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0F1F2DebugBuild UP-TO-DATE
:checkF0F1F2DebugManifest
:preF0F1F2ReleaseBuild UP-TO-DATE
:prepareChart20171222NstrialReleaseLibrary UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:prepareComAndroidSupportDesign2340Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72340Library UP-TO-DATE
:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:prepareComFacebookFrescoDrawee090Library UP-TO-DATE
:prepareComFacebookFrescoFbcore090Library UP-TO-DATE
:prepareComFacebookFrescoFresco090Library UP-TO-DATE
:prepareComFacebookFrescoImagepipeline090Library UP-TO-DATE
:prepareComFacebookFrescoImagepipelineBase090Library UP-TO-DATE
:prepareCommon20171222NstrialReleaseLibrary UP-TO-DATE
:prepareData20171222NstrialReleaseLibrary UP-TO-DATE
:prepareFeedback20171222NstrialReleaseLibrary UP-TO-DATE
:prepareGauges20171222NstrialReleaseLibrary UP-TO-DATE
:prepareInput20171222NstrialReleaseLibrary UP-TO-DATE
:prepareList20171222NstrialReleaseLibrary UP-TO-DATE
:preparePrimitives20171222NstrialReleaseLibrary UP-TO-DATE
:prepareSdkRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0F1F2DebugDependencies
:compileF0F1F2DebugAidl UP-TO-DATE
:compileF0F1F2DebugRenderscript UP-TO-DATE
:generateF0F1F2DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:mergeF0F1F2DebugShaders UP-TO-DATE
:compileF0F1F2DebugShaders UP-TO-DATE
:generateF0F1F2DebugAssets UP-TO-DATE
:mergeF0F1F2DebugAssets UP-TO-DATE
:generateF0F1F2DebugResValues UP-TO-DATE
:generateF0F1F2DebugResources UP-TO-DATE
:mergeF0F1F2DebugResources UP-TO-DATE
:processF0F1F2DebugManifest UP-TO-DATE
:processF0F1F2DebugResources UP-TO-DATE
:generateF0F1F2DebugSources UP-TO-DATE
:incrementalF0F1F2DebugJavaCompilationSafeguard UP-TO-DATE
:compileF0F1F2DebugJavaWithJavac UP-TO-DATE
:compileF0F1F2DebugNdk UP-TO-DATE
:compileF0F1F2DebugSources UP-TO-DATE
:prePackageMarkerForF0F1F2Debug
:transformClassesWithDexForF0F1F2Debug
To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 884 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
:myMergeDex
Result compacted from 6465,6KiB to 5114,4KiB to save 1351,2KiB
Merged dex #1 (1 defs/1,6KiB)
Merged dex #2 (1 defs/1,4KiB)
Merged dex #3 (1 defs/1,9KiB)
Merged dex #4 (1 defs/1,7KiB)
Merged dex #5 (1 defs/1,4KiB)
Merged dex #6 (1 defs/1,6KiB)
Merged dex #7 (1 defs/1,4KiB)
Merged dex #8 (1 defs/1,3KiB)
Merged dex #9 (1 defs/1,5KiB)
Merged dex #10 (1 defs/1,7KiB)
Merged dex #11 (1 defs/2,7KiB)
Merged dex #12 (1 defs/1,5KiB)
Merged dex #13 (1 defs/1,4KiB)
Merged dex #14 (1 defs/1,6KiB)
Merged dex #15 (1 defs/1,6KiB)
Merged dex #16 (1 defs/1,7KiB)
Merged dex #17 (1 defs/1,3KiB)
Merged dex #18 (1 defs/1,4KiB)
Merged dex #19 (1 defs/1,7KiB)
Merged dex #20 (1 defs/1,8KiB)
Merged dex #21 (1 defs/1,7KiB)
Merged dex #22 (1 defs/2,0KiB)
Merged dex #23 (1 defs/1,3KiB)
Merged dex #24 (1 defs/1,4KiB)
Merged dex #25 (1 defs/1,3KiB)
Merged dex #26 (1 defs/1,4KiB)
Merged dex #27 (1 defs/1,4KiB)
Merged dex #28 (1 defs/2,2KiB)
Merged dex #29 (1 defs/1,5KiB)
Merged dex #30 (1 defs/2,3KiB)
Merged dex #31 (1 defs/1,4KiB)
Merged dex #32 (1 defs/1,5KiB)
Merged dex #33 (1 defs/1,3KiB)
Merged dex #34 (1 defs/1,4KiB)
Merged dex #35 (1 defs/1,3KiB)
Merged dex #36 (1 defs/1,4KiB)
Merged dex #37 (1 defs/1,7KiB)
Merged dex #38 (1 defs/1,6KiB)
Merged dex #39 (1 defs/1,3KiB)
Merged dex #40 (1 defs/1,3KiB)
Merged dex #41 (1 defs/1,5KiB)
Merged dex #42 (1 defs/1,4KiB)
Merged dex #43 (1 defs/1,9KiB)
Merged dex #44 (1 defs/1,9KiB)
Merged dex #45 (1 defs/2,5KiB)
Merged dex #46 (1 defs/2,6KiB)
Merged dex #47 (1 defs/1,2KiB)
Merged dex #48 (1 defs/1,3KiB)
Merged dex #49 (1 defs/1,4KiB)
Merged dex #50 (4102 defs/5088,4KiB)
Result is 4151 defs/5114,4KiB. Took 1,2s
:buildMetadata UP-TO-DATE
:mergeF0F1F2DebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForF0F1F2Debug UP-TO-DATE
:processF0F1F2DebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForF0F1F2Debug UP-TO-DATE
:validateDebugSigning
:packageF0F1F2Debug UP-TO-DATE
:zipalignF0F1F2Debug UP-TO-DATE
:assembleF0F1F2Debug UP-TO-DATE
:assembleDebug UP-TO-DATE
:buildapk UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2 mins 35.749 secs
Project successfully built.

H:\Dev\projects\nativescript-ui-samples-release\sdk>

**Comment by Pip3r4o** [comment]
https://github.com/NativeScript/nativescript-cli/issues/2168#issuecomment-290101965 might help.

**Comment by mawoole** [comment]
Hi @Pip3r4o,

I can see that in your referenced comment (#2168) :

"_**I saw that my problem was, of course, my 32bits environment, so I change 'native-dev-typescript\lib\compiler.js' to set '--max_old_space_size=4096' to '--max_old_space_size=2048'
and set JAVA_OPTS = -Xms1024m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=356m -XX:PermSize=256m -XX:MaxPermSize=356m.**_"

it is about to change 'native-dev-typescript\lib\compiler.js' to set '--max_old_space_size=4096' to '--max_old_space_size=2048',

Please, can you tell me where exactly to change these parameters?

Thanks

**Comment by JulienFr** [comment]
Using nativescript-dev-typescript 0.3.5,
go to your project node_modules directory, then nativescript-dev-typescript/lib/compiler.js,
line 26 with the nodeArgs, replace 4096 by 1024 worked for me

**Comment by mawoole** [comment]
Thanks @JulienFr, 
your solution also worked fine for me.

**Comment by trivediri2312** [comment]
set JAVA_OPTS = -Xms1024m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=356m -XX:PermSize=256m -XX:MaxPermSize=356m." where to set these parameter
