### ISSUE TITLE
--watch parameter does not work

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2768]
_From @ignaciolarranaga on September 28, 2016 20:16_

You change the code and nothing happens, the tests are not executed again.

_Copied from original issue: NativeScript/nativescript-unit-test-runner#20_

**Comment by dtopuzov** [comment]
_From @nakedcity on December 9, 2016 8:23_

Try reopening the app in the emulator, I have seen the test cases are loaded but once app closes you can not see them

**Comment by pkoleva** [comment]
Closed in favour of https://github.com/NativeScript/nativescript-cli/issues/2119
