### ISSUE TITLE
Add ability to ignore files from final package when build in release

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2776]
We have a lot of use cases when we need some files in debug mode, but we don't need them in release builds.

I've seen following in final packages:
- *.d.ts
- *.md
- *.html (it was HTML help of some angular packages)
- tests 
- unit test runner (https://github.com/NativeScript/nativescript-cli/issues/2773)

Adding such feature will help users to optimize app size of final package.

**Comment by paxperscientiam** [comment]
Any progress?

**Comment by rosen-vladimirov** [comment]
As a workaround you can use weback to build your application. When you use webpack (i.e. `--bundle`) for building the application, only the files actually used by it will be included in the bundle. This way you'll never receive `.d.ts`, `.tgz`, `tests`, etc. in case you are not importing them in your application's code.

**Comment by rosen-vladimirov** [comment]
I'm closing this issue as in NativeScript 6.0 we'll support only bundle workflow in which the mentioned files are not included anymore. Webpack will include only the required files, so we consider this issue as resolved.
