### ISSUE TITLE
NativeScript Version

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [NativeScript/nativescript-cli#2784]
NativeScript should maintain the same version as angular so as not to cause confusion. It should be NativeScript 4

**Comment by dtopuzov** [comment]
Reasons why this can't happen:
- {N} framework do not target only Angular, you can also develop apps with pure JavaScript (or TypeScript).
- We bump major version when we have significant breaking changes and those changes are not always related with Angular.
- We may think about releasing `nativescript-angular` with same versioning as Angular, but we can't do it for the framework in general.
