### ISSUE TITLE
Add the ability to generate pages and components

### ISSUE THREAD

**Issue by Abderrahmane-H** [NativeScript/nativescript-cli#2787]
At the moment the cli cannot generate pages and components ... we have to create them manualy. It woul be great if you could add the ability for the cli to generate componenets.

Example :
Tns generate component "component name" --ng

Tns generate provider "provider name"....

**Comment by dtopuzov** [comment]
Closed in favor of https://github.com/NativeScript/nativescript-cli/issues/2606
