### ISSUE TITLE
Cannot read property 'match' of null error when installing tns cli

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#2810]
### Tell us about the problem
I am installing tns on clean Mac Sierra, without any dependencies installed.
in this case, the following issue appears:

> Warning: CocoaPods is not installed or is not configured properly
> ....
> Cannot read property 'match' of null
> Do you want to help us improve NativeScript by automatically ....

### Which platform(s) does your issue occur on?
macOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0

### Please tell us how to recreate the issue in as much detail as possible.
On a freshly install macOS Sierra, install homebrew, node and then attempt to install NativeScript CLI

**Comment by vchimev** [comment]
Perhaps, java has not been installed. Related to: https://github.com/NativeScript/nativescript-cli/issues/1922.

**Comment by dtopuzov** [comment]
It looks more like https://github.com/NativeScript/nativescript-cli/issues/1245#issuecomment-159562131

**Comment by dtopuzov** [comment]
Actually those are two separate issues:
1. Setup script do not install cocoa pods properly
2. Tns doctor do not show appropriate error message

**Comment by Plamen5kov** [comment]
Can't reproduce the problem.

**Comment by Plamen5kov** [comment]
@teobugslayer can you provide the output from the command:
`tns doctor --log trace` so we can have a more detailed look at the computer configuration, because there's a possibility xCode is not installed or `xcodebuild` tool is not in the PATH.

**Comment by Plamen5kov** [comment]
@teobugslayer if your xcode is not installed at all or not configured properly, you should see something like:
```
mcsofplpetkov:nativescript-cli plpetkov$ tns doctor
WARNING: Xcode is not installed or is not configured properly.
You will not be able to build your projects for iOS or run them in the iOS Simulator.
To be able to build for iOS and run apps in the native emulator, verify that you have installed Xcode.

WARNING: CocoaPods is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPods.
Cannot read property 'match' of null
# doctor
```
If that's the case, we'll work on a better error message.
