### ISSUE TITLE
Groceries chapter 6 crashes on iOS

### ISSUE THREAD

**Issue by RCoverC** [NativeScript/nativescript-cli#2826]
### Which platform(s) does your issue occur on?
iOS but I have not tried Android. 

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 1.0.0
- Runtime(s): 2.5.0 (for both)
- Plugin(s): 2.5.0

### Please tell us how to recreate the issue in as much detail as possible.
I was following the instructions on Nativescript.org up to chapter 6. Whenever I try to sign in to test the project (on the iOS simulator on my mac), the app crashes. Every single time. Nothing is written in the debug console or terminal or problems or output. Ever. 
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

All the code in the steps up to chapter 6 on the site. For JavaScript. App "Groceries."

**Comment by dtopuzov** [comment]
Hi @RCoverC,

Can you reproduce the issue with {N} 3.0.0?
There are some breaking changes and may be tutorial is now modified for 3.0.0.

If you don;t see console logs you can try to get them in this way:
https://i.stack.imgur.com/PWZI3.png

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/sample-Groceries#251
