### ISSUE TITLE
`tns debug android --emulator --timeout <ms>` does not respect set timeout

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2829]
When a timeout in miliseconds is set to `tns debug android --emulator` it is not respected

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Select an emulator that starts slowly and run
`tns android --emulator <EmulatorName> --timeout <TimeoutInMs>`

Expected behavior: The command should stop after the timeout passes

**Comment by rosen-vladimirov** [comment]
Closing as the issue is no longer reproducible with latest version.
