### ISSUE TITLE
"tns library add android" does not handle references to "appcompat"

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-cli#283]
When using "library add" for an Eclipse project that has a reference to "appcompat" (for example `android.library.reference.1=../appcompat ` in the project.properties file) - the command succeeds, but build after that fails.

Suggestions:
 - Display a warning or error when a reference cannot be resolved in the "library add" command
 - Try to resolve/remove references to appcompat lib

**Comment by Fatme** [comment]
This should be fixed after implementing this - https://github.com/NativeScript/nativescript-cli/issues/687
