### ISSUE TITLE
Disable privacy policy prompt during install for unattended installations (ie: CI/CD)

### ISSUE THREAD

**Issue by briandilley** [NativeScript/nativescript-cli#2842]
How do i disable the following prompt during installation of NativeScript:

> Do you want to help us improve NativeScript by automatically sending anonymous usage statistics? We will not use this information to identify or contact you. You can read our official Privacy Policy at
> ? http://www.telerik.com/company/privacy-policy (Y/n) 

I'm using the following command to install it globally as part of a continuous integration build:
`npm install -g nativescript@2.5.4 --unsafe-perm`

That prompt comes up at the end and just sits there forever, is there not a flag or something to disable it?

**Comment by rosen-vladimirov** [comment]
Hey @briandilley ,
You can pass `--ignore-scripts` to the installation, this way the post-install script will not be executed and it will not ask anything.
Can you try it and confirm it works on your side?

P.S. There's nativescript 2.5.5 version :)

**Comment by briandilley** [comment]
will that not cause problems?  that postinstall script seems to do a lot of stuff :)

**Comment by briandilley** [comment]
Well, it helped get past that part - but then `tns build ios` prompted the same thing immediately :(

**Comment by briandilley** [comment]
doing `tns usage-reporting disable` and `tns error-reporting disable` after the npm install seems to have fixed it :)

**Comment by briandilley** [comment]
So as long as `--ignore-scripts` doesn't miss some important thing - the resolution is:
`npm install -g nativescript --ignore-scripts && tns usage-reporting disable && tns error-reporting disable`
followed by whatever build commands you may have.

**Comment by rosen-vladimirov** [comment]
@briandilley yeah, for CI builds you can safely skip the postinstall scripts.
