### ISSUE TITLE
Cannot run or modify after first time (device)

### ISSUE THREAD

**Issue by jrz** [NativeScript/nativescript-cli#2846]
From the ng-groceries example. 3.0.1

```
$ tns run ios
Skipping prepare.
Searching for devices...
Skipping package build. No changes detected on the native side. This will be fast!
Installing...
Multiple errors were thrown:
Could not create device path for file: /PATH_TO_PROJECT/platforms/ios/build/device/.nsbuildinfo

# run ios
```

Works on simulator

**Comment by tsonevn** [comment]
Hi @jrz,
I tested this case on my side while using the latest Official NativeScript CLI 3.0 and `sample-Groceries` project from  [this](https://github.com/NativeScript/sample-Groceries/) repository, however, was unable to reproduce this behavior on my side. 

Regarding that could you provide some more info about the problem and the exact steps, which you are using. It would also help if you could provide info about the device and to send us the full log from the console.

In the meantime, you could try to remove `platforms`, `node_modules` and to clear npm cache with `npm cache clear` and to build the project again.

**Comment by jrz** [comment]
Doing just the npm cache clear did the trick.
