### ISSUE TITLE
CLI autocompletion

### ISSUE THREAD

**Issue by dianjuar** [NativeScript/nativescript-cli#2847]
## Feature request

I'm a very big fan of auto completion, I feel that I can discover more easily the benefits of a tool or framework by myself.

Angular CLI has [autocompletion](https://github.com/angular/angular-cli/wiki/stories-autocompletion) for some consoles, and [nobody](https://github.com/robbyrussell/oh-my-zsh/issues?utf8=%E2%9C%93&q=is%3Aissue%20nativescript) is working for a plugin on the oh-my-zsh project.

Have you ever thought on implement something like the autocompletion of angular-cli?

**Comment by tsonevn** [comment]
Hi @dianjuar,
Such a functionality is already included in the NativeScript CLI. To verify the current status of the completion settings you could run `tns autocomplete status` command. If this setting is disabled you could activate it via `tns autocomplete enable`. More info about this feature could be found [here](https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/general/autocomplete.md).

**Comment by dianjuar** [comment]
OH! very nice... Before I submit this issue, I made a little research to be sure that my request hasn't been implemented, but I didn't found this...

**Comment by 5te1n** [comment]
Unfortunately, as it is written in the [documetation](https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/general/autocomplete-enable.md), autocomplete is only supported for bash and zsh shells. It is a little disappointing for a windows user like me, who is using Visual Studio Code with the integrated PowerShell console. Are there future plans to support autocompletion for PowerShell?
