### ISSUE TITLE
 Cannot change a debugging port

### ISSUE THREAD

**Issue by Humberd** [NativeScript/nativescript-cli#2865]
## Please, provide the details below:

Cannot change a debugging port: `--debug-port` property is being ignored.

### Tell us about the problem

I've created a brand new project using `tns create HelloWorldNativeScript--template nativescript-template-ng-tutorial`. 

As the device I am using Android Emulator.

I am specifying a port `7878`, but eventually it watches a port `40000`

It is **not** a fault of a Node.js 8.0.0, because I had the same problem with version 7.8.0

```
PS F:\Repositories\WebStorm\HelloWorldNativeScript> tns debug android --debug-port 7878

Support for Node.js 8.0.0 is not verified. This CLI might not install or run properly.

Searching for devices...
Executing before-prepare hook from F:\Repositories\WebStorm\HelloWorldNativeScript\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from F:\Repositories\WebStorm\HelloWorldNativeScript\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (Android)
Executing after-prepare hook from F:\Repositories\WebStorm\HelloWorldNativeScript\hooks\after-prepare\nativescript-dev-android-snapshot.js
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
Executing before-livesync hook from F:\Repositories\WebStorm\HelloWorldNativeScript\hooks\before-livesync\nativescript-angular-sync.js
Transferring project files...
Successfully transferred all files.
Successfully synced application org.nativescript.HelloWorldNativeScript on device emulator-5554.

Using  F:\Repositories\WebStorm\HelloWorldNativeScript\platforms\android\build\outputs\apk\HelloWorldNativeScript-debug.apk
device: emulator-5554 debug port: 40000

# NativeScript Debugger started #
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000

Executing before-watch hook from F:\Repositories\WebStorm\HelloWorldNativeScript\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
01:30:34 - Compilation complete. Watching for file changes.
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: **3.0.2**
- Cross-platform modules: **3.0.1**
- Runtime(s): **3.0.0**
- Plugin(s): default

### Please tell us how to recreate the issue in as much detail as possible.

I'm following [this tutorial](http://docs.nativescript.org/angular/tutorial/ng-chapter-1)

**Comment by pkoleva** [comment]
Hey @Humberd, 

Indeed this property is not respected, but with the latest changes we decided to disable this flag. This option is not relevant since our 2.5.0 release but we obviously didn't remove it from the documentation. In our @next documentation this is fixed. The idea of removing this option is that we now check which is the next available port from 40000 on for android and use it to attach the debugger.

I hope this is helpful!

**Comment by dtopuzov** [comment]
`--debug-port` removed from help.
