### ISSUE TITLE
Allow Node 8

### ISSUE THREAD

**Issue by ishitatsuyuki** [NativeScript/nativescript-cli#2873]
Currently Node 8+ is marked [unsupported](https://github.com/NativeScript/nativescript-cli/blob/master/package.json#L109). This makes CI builds with unpinned Node version start to fail.

As a part of adopting NPM 5, Node 8 compatibility should be ensured as well (although there should be no breaking changes affecting us).

**Comment by rosen-vladimirov** [comment]
Hey @ishitatsuyuki ,
We are in the process of verifying this Node.js version and once we are ready, we'll add it to NativeScript CLI's package.json. Meanwhile you should be able to use it on your side, the only issue will be that you'll see on each CLI's command execution that the version is not verified. Or maybe you've set the `engine-strict` npm config flag to true, which will break the installation of the CLI. In this case you can temporary set it to false by executing `npm config set engine-strict false`.
