### ISSUE TITLE
Unable to build and deploy app to iTunes: Unable to connect to iTunes Connect

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2874]
_From @briandilley on June 3, 2017 22:53_

`    /usr/bin/touch -c /Users/distiller/Library/Developer/Xcode/DerivedData/quickridensmobile-bnzhogcsicpkjudhwfepmetihxvs/Build/Intermediates/ArchiveIntermediates/quickridensmobile/BuildProductsPath/Release-iphoneos/quickridensmobile.app.dSYM

** ARCHIVE SUCCEEDED **

Archive at: /Users/distiller/quickride-ns-mobile/platforms/ios/build/archive/quickridensmobile.xcarchive
2017-06-03 15:36:48.606 xcodebuild[17633:31256] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/quickridensmobile_2017-06-03_15-36-48.605.xcdistributionlogs'.
Exported quickridensmobile.xcarchive to: /Users/distiller/quickride-ns-mobile/platforms/ios/build/archive
** EXPORT SUCCEEDED **

Export at: /Users/distiller/quickride-ns-mobile/platforms/ios/build/archive/quickridensmobile.ipa
Unable to connect to iTunes Connect
An error occurred while processing the json request. (1268)`

_Copied from original issue: NativeScript/NativeScript#4310_

**Comment by OscarLopezArnaiz** [comment]
+1 Having this issue since Friday, thought it was iTunes having some issues but today got same error message when trying to publish a build.

**Comment by dtopuzov** [comment]
@OscarLopezArnaiz @briandilley we can confirm this is valid issue and we will try to provide fix soon.

**Comment by OscarLopezArnaiz** [comment]
Cheers @dtopuzov  

As a temporal workout [application loader worked for me](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/UploadingBinariesforanApp.html).

To publish a build with Application Loader

1. Launch Xcode.
2. Choose Xcode > Open Developer Tool > Application Loader.
3. [Upload your application binary files](http://help.apple.com/itc/apploader/e3#/apdATD1E12-D1E1A1303-D1E12A1126)

**Comment by vchimev** [comment]
https://github.com/NativeScript/nativescript-cli/pull/2882

**Comment by dtopuzov** [comment]
@OscarLopezArnaiz @briandilley issue is fixed and it will be officially released with 3.1.0 (later this month).

Until then you can publish with @next builds (they are produced on each commit in master branch):
```
npm un -g nativescript
npm cache clean
npm i -g nativescript@next
```

**Comment by b02505048** [comment]
I had the same problem with nativescript@4.2.4, any idea?
```
> tns --version
4.2.4
```

**Comment by dtopuzov** [comment]
Hi @b02505048,

Can you post logs and add more info for your system and project you are working on?

Can you reproduce the issue in hello world app?

**Comment by b02505048** [comment]
Hi @dtopuzov, thanks for replying. 
The logs are simply like this
```
Unable to connect to iTunes Connect
Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
``` 
I don't even know that I have an `app-specific pwd` with me 😂
Anyway, my team and I end up with archiving it in Xcode and it just works fine.

**Comment by canelacho** [comment]
Well, well, well... I was in the same situation but finally I found how works the app-specific pwd. Is because the security of apple, when you have the two factor auth, you need a pwd for this situation. Thanks to telerik that have documented this problem.

Cause
These errors mean that you have enabled two-step verification or two-factor authentication for your Apple ID. With these feaures enabled, iTunes Connect requires an app-specific password when you use services that do not support entering a verification code, such as AppBuilder.

Solved:
https://docs.telerik.com/platform/knowledge-base/troubleshooting/password-not-working-on-itunes-connect
