### ISSUE TITLE
[npm5] Error handling issues

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2875]
In some cases `npm5` cause unpleasant results when we try to install something that is not available in npm.

- `tns plugin add fakePlugin --path TestApp`
With `npm4` we say `no such package available`
With `npm5` we show npm ERR messages (without own error message explaining the problem)

- `tns platform add android --path TestApp --frameworkPath invalidFile.tgz`
Same as above.

**Comment by TomaNikolov** [comment]
The error messages with npm5 seem OK to me. We show the errors from the `npm install` command, which are almost the same for both npm4 and apm5.
