### ISSUE TITLE
Build successful but nothing happened

### ISSUE THREAD

**Issue by JesusIslam** [NativeScript/nativescript-cli#288]
```
BUILD SUCCESSFUL
Total time: 12 seconds
Project successfully built
Using  /home/dida/project/testapp/testing/platforms/android/bin/testing-debug.apk
Successfully deployed on device with identifier 'MITOA355'
```

But then nothing happened on my phone, what should I do?

**Comment by rosen-vladimirov** [comment]
Hi @JesusIslam , may I ask you for more details. Could you send us which command are you executing, which android are you using on your device, etc. Also it will be great if you can send the output of your call with --log trace added. For example in case you execute ```tns run android``` we'll need the output of  ```tns run android --log trace```

**Comment by rosen-vladimirov** [comment]
Also, have you modified your AndroidManifest? In case you've changed your activity name (default value is com.tns.NativeScriptActivity) the CLI will not be able to run the app.

**Comment by JesusIslam** [comment]
```
 stderr: 
Found device with identifier 'MITOA355'
Exec "adb" -s MITOA355 shell pm uninstall "org.nativescript.testing" 
 stdout: Failure
 
 stderr: 
Exec "adb" -s MITOA355 install -r "/home/dida/project/nativescript/testing/platforms/android/bin/testing-debug.apk" 
 stdout: 	pkg: /data/local/tmp/testing-debug.apk
Failure [INSTALL_FAILED_OLDER_SDK]
 
 stderr: 4288 KB/s (8413298 bytes in 1.915s)

Exec "adb" -s MITOA355 shell am start -a android.intent.action.MAIN -n org.nativescript.testing/com.tns.NativeScriptActivity 
 stdout: Starting: Intent { act=android.intent.action.MAIN cmp=org.nativescript.testing/com.tns.NativeScriptActivity }
Error type 3
Error: Activity class {org.nativescript.testing/com.tns.NativeScriptActivity} does not exist.
 
 stderr: 
Successfully deployed on device with identifier 'MITOA355'
```

That's the last outputs, and no, I simply `tns create testing` and then `tns run android`, nothing else

**Comment by rosen-vladimirov** [comment]
Hi @JesusIslam 
It looks like there's some kind of a problem with the adb. Could you try executing ```adb version``` and see the output - it should be something like ```Android Debug Bridge version 1.0.32```.
It looks like you have added "adb" in your path, but from which version of android sdk? We'll have to improve our logging in such cases, as it clearly has some errors in adb, but we show ```Successfully deployed on device with identifier... ```. Anyway, please make sure you are have added adb from latest SDK in your path. Please note that min supported sdk version is 17. Also what is the android version on your device?

**Comment by JesusIslam** [comment]
`Android Debug Bridge version 1.0.31`

This is the result. I've installed it via `apt-get`

> Minimum supported SDK version is 17

So, this is one of the reason then. My Android version is SDK 16 (4.1.2).

Looks like I'll have to stay on the emulator.

**Comment by rosen-vladimirov** [comment]
Hi @JesusIslam, yes, you cannot use nativescript projects on 4.1.2 devices. May we close this issue?

**Comment by JesusIslam** [comment]
Yes, you we could close this issue. Thank you for the assistance.

**Comment by vanbumi** [comment]
what is minimum android version can work for nativiescript? even for view or deploy? so only new android can install the app from this platform?

**Comment by teobugslayer** [comment]
@vanbumi, API level 17 is the minimum supported one. See our [docs](http://docs.nativescript.org/faq.html#what-android-api-level-does-nativescript-target).

**Comment by Anilinfo2015** [comment]
Same problem me facing.

:config phase:  createDefaultIncludeFiles

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: C:\1Projects\NS Web\workstation\ns-mobile\platforms\
android\libs\aar\widgets-release.aar
:deleteMetadata
:deleteFlavors
:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 23.072 secs
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)

**Comment by yashwp** [comment]
@rosen-vladimirov I have created a new app using CLI and now I'm running it using `tns run android` command. The command runs successfully and AVD device is launched but, in the terminal, it stopped at 
```
Project successfully built.
Installing...
```
It's been showing this message for like 15 mins already and I tried re-running the commands, but still, the same problem. Can you tell me what's the problem here?
![screenshot 54](https://user-images.githubusercontent.com/13454790/46064005-d1d7dd00-c18b-11e8-8358-731ceacc71fa.png)
