### ISSUE TITLE
Error installing the docs while cli-install on MacOSX (Maybe Linux too)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2885]
_From @sittingbool on June 13, 2017 8:51_

Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

MacOSX 10.12.5

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

sudo npm install -g nativescript

### Please tell us how to recreate the issue in as much detail as possible.

1. Install nativescript cli on MacOSX
2. wait

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Output is:

EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nativescript/docs/html'

I guess its because the directory docs in /usr/local/lib/node_modules/nativescript/ is under my personal user but the installer ties as root (which is confusing but Apple changed some permission features in OSX 10.12).

The install process seams to run until the end though. But its confusing for some people.

_Copied from original issue: NativeScript/NativeScript#4367_

**Comment by NickIliev** [comment]
_From @sittingbool on June 13, 2017 8:52_

Btw: if i create the directory myself I will still get the error and its gone again afterwards.

**Comment by pkoleva** [comment]
Hey, @sittingbool

Is there a specific reason you need to install nativescript with `sudo`?

**Comment by sittingbool** [comment]
On Mac you have install all global modules as super-user because the directory it gets installed to is a Unix system directory. Same on Linux based operating systems btw.

**Comment by pkoleva** [comment]
When running `sudo npm install -g nativescript` npm executes postinstall scripts with a specific user -> _nobody_, who has no rights to your user's folders, so it is expected to behave like that. However, postinstall failure is not a problem and you do have nativescript installed after all. If you want to be sure that the postinstall succeeds you can execute `sudo npm install -g nativescript --unsafe-perm`. Hope this helps.

**Comment by sittingbool** [comment]
perfect, thank you

**Comment by elalienx** [comment]
@pkoleva can you please submit your answer in the official NativeScript documentation. Because the standard security level of the Mac OS Mojave require your method.

**Comment by gediminasiv** [comment]
I also runned `mkdir /usr/local/lib/node_modules/nativescript/docs/html`, and it just went through, so I guess the problem is with the `docs` folder.
