### ISSUE TITLE
Running build overrides DEVELOPMENT_TEAM set in build.xconfig

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-cli#2887]
Seems there is some bug when you run the `build` command it wipes the `DEVELOPMENT_TEAM` that is set in the `build.xconfig` file. In my `build.xconfig` file I have the following:
```
DEVELOPMENT_TEAM = 98********;

CODE_SIGN_IDENTITY[config=Debug] = iPhone Developer;
CODE_SIGN_IDENTITY[config=Release] = iPhone Distribution;

PROVISIONING_PROFILE[config=Debug] = a5ec2d86-9bfb-48e4-b8c0-a75c39a0a5bd;
PROVISIONING_PROFILE[config=Release] = 7ee2b2f5-8e07-4529-aeb4-fb560dafb3db;

ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;
```

I'm starting with a clean iOS platform folder. Then after I run `tns prepare ios` and open the project file in Xcode the settings look correct:
![screen shot 2017-06-13 at 7 21 43 pm](https://user-images.githubusercontent.com/9464097/27093152-4ee61d88-506e-11e7-8287-9862f1c3f161.png)

After that I close Xcode and run `tns build ios --for-device` which fails with the following error:
```
Check dependencies
Signing for "******" requires a development team. Select a development team in the build settings editor that matches
the selected profile "a5ec2d86-9bfb-48e4-b8c0-a75c39a0a5bd".
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

** BUILD FAILED **
```
At this point if I open the project in Xcode the settings are messed up as seems in the project file somehow the `DEVELOPMENT_TEAM` is set to an empty value which takes precedence over the one in the `xconfig` file:
![screen shot 2017-06-13 at 7 23 35 pm](https://user-images.githubusercontent.com/9464097/27093266-baae2560-506e-11e7-8771-cf909db83ab7.png)

**Comment by PanayotCankov** [comment]
Here: https://github.com/NativeScript/nativescript-cli/blob/ab08c918d52e8077d79e38804052c31b0b31478f/lib/services/ios-project-service.ts#L1242
The CLI reads the .xcconfig and sets manual signing style or automatic signing style based on the flags in the .xcconfig, but currently it uses manual signing style only if it finds `PROVISIONING_PROFILE` or `PROVISIONING_PROFILE[sdk=iphoneos*]`.

**Comment by PeterStaev** [comment]
@PanayotCankov , I do not think this is the problem. From what I see manual signing is correctly enabled for the project (below is a screenshot of the general project properties after running the `build` command):
![screen shot 2017-06-14 at 10 36 05 am](https://user-images.githubusercontent.com/9464097/27120763-86e0da14-50ed-11e7-98e8-2ed371abc76a.png)

**Comment by PeterStaev** [comment]
This seems to be fixed with the `@next` version 👍
