### ISSUE TITLE
No validation when emulate in invalid avd and device

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#289]
Run:
tns emulate android --avd invalidDevice --path TNSApp

Result:
Starting Android emulator with image invalidDevice

Expected:
Check if "invalidDevice" avd is available and if not then show some appropriate error message.

**Comment by vchimev** [comment]
From https://github.com/NativeScript/nativescript-cli/issues/1167:

If you execute `tns emulate android --device xxxxx` it starts the default emulator.
If you execute `tns emulate ios --device xxxxx` it prepares, builds and finally reports that *Unable to find device xxxxx*.

**Comment by enchev** [comment]
I suggest to obsolete `--avd` and use `--device` which should work for both android and ios.
