### ISSUE TITLE
Discussion: tns run android/ios target options

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-cli#2908]
### Tell us about the problem
I would like to get some insight or ideas on improving this process. Not the first time I've ran into the issue or heard about it. I tried `tns run ios` for an hour, reset the simulator, restarted macbook and it never would work with livesync. The app would install on sim and exit with signal 9. Talked with Nathan Walker and he asked if I was using `tns run ios --emulator` (he mentioned that's all he ever does). So I tried it and it has worked every time when I declare the run target option. So basically, is this reproducible by the CLI team? If so, maybe add the `--emulator` flag as a default on the `run` cmd or should the CLI always expect a target option to be specified. I enjoy the flexibility of the CLI with options but don't want others starting out in the NS community to have these types of issues and headaches 😄  so curious on the team's thoughts. 
This is not an issue when doing `tns run android` in my experience. That works without issue everytime.

### Which platform(s) does your issue occur on?
iOS mainly

### Please provide the following version numbers that your issue occurs with:
latest stable versions.

### Please tell us how to recreate the issue in as much detail as possible.

`tns run ios` will sync the app and exit on mac. `tns run ios --emulator` will sync and run livesync as expected. On a PC I never have to be explicit with the run target options. I cannot get `tns run ios` to work unless I'm explicit.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No

**Comment by pkoleva** [comment]
Hi, @bradmartin 

I always use `tns run ios` and have no such issue. The simulator is started and my app is deployed, launched and livesyncs ok. Since this happens to you every time could you send more details? What is your OSX, what's the simulator you're trying to use, the versions of the CLI and the runtime, sample app you consistently have this problem or anything that can help locate the problem.

Thank you!

**Comment by bradmartin** [comment]
I think it's more an issue with the macbook itself. Slow 5400 HDD and it just chokes a lot 😄 - I've now had the `--emulator` option fail for me. It typically happens when I don't have the simulator running and I am just starting out with `tns run ios` and of course with a slow mac it takes several minutes, the sim starts, app installs and then exits. So I'm assuming the reason it is exiting is because of the mac just choking out at times. I don't think it's anything wrong with the CLI, the app, but after another day it seems to be a crummy mac is all 😄 so no issue.

**Comment by bradmartin** [comment]
Since reporting this, I upgraded to a 2015 macbook pro with 128gb flash drive and 2.7 i5 and not once have I had an issue with any CLI command when launching the iOS simulator. So it was definitely the machine just choking.
