### ISSUE TITLE
Deploy and Run commands has the same behavior and different code implementations

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#293]
It looks Deploy and Run both do the same:
1. Prepare
2. Build
3. Deploy
4. Run 

Both commands have different implementations.
We should make them aliases and go with one single code implementation 
Personally,  I think deploy implementation is better (at least it handles invalid input better)

**Comment by dtopuzov** [comment]
Found a difference in iOS:
Run can run the app in simulator, Deploy can't deploy in simulator.

**Comment by emiloberg** [comment]
To make things easier, wouldn't it be a good idea to remove one of the choices; run or deploy.

My vote is on removing the `run` as that would give us `deploy` for running on actual devices and 'emulate' for virtual devices. Clear separation.

**Comment by rosen-vladimirov** [comment]
Hi @emiloberg ,
I'm wondering if we should duplicate the behavior or remove one of the commands. What do you think about making the deploy command just deploying to connected devices, without starting the application, while run will make deploy + starting of application. Emulate will make deploy on emulator + starting on emulator?

**Comment by emiloberg** [comment]
You're proposal works - if you can see a use case for _just_ deploying an app without starting it. Personally I can't see why I want to do that, but there might be one.

Doing it this way still separates the commands for emulating and deploying (and running) which is I see as the most important part.

**Comment by rosen-vladimirov** [comment]
As you've said - trying to find a use case for just deploying is really difficult. The only case I could think about is when you want to deploy several applications on different devices and check them after that.
In fact we have widely discussed command's behavior in [this issue](https://github.com/NativeScript/nativescript-cli/issues/475), so I'll close this one and we can continue our communication there. Thank you for the valuable feedback!
