### ISSUE TITLE
Getting debug error

### ISSUE THREAD

**Issue by hkirat** [NativeScript/nativescript-cli#2933]
Getting "Cannot find a compatible Android SDK for compilation. To be able to build for Android, install Android SDK 22 or later." error.

Has beed discussed before in #2583.
Have reverted to a previous version of android sdk.
Installed latest version of nativescript as well.

**Comment by hkirat** [comment]
Nvm.. is working fine now... downgraded to version 2.5.3 for nativescript
Another issue I'm facing though
nativescript run android shows the following exception
Exception: The plugin tns-android@3.1.1 is already installed
and stops to function.

**Comment by dtopuzov** [comment]
Hi @hkirat 

In case you have Android SDK Tools 25.2.3 or higher, can you please run `$ANDROID_HOME/tools/bin/sdkmanager --list` and post the result?

In case of older Android SDK Tools please run `android list sdk` and `android list target` and post the output.

**Comment by hkirat** [comment]
Here's the output @dtopuzov 
https://gist.github.com/hkirat/08375dd138eb483fc029bae4344cf3b9

**Comment by hkirat** [comment]
<img width="1270" alt="screen shot 2017-06-28 at 1 11 28 pm" src="https://user-images.githubusercontent.com/8079861/27658043-7e2431c0-5c03-11e7-8b8d-25cc72a61600.png">
Something similar happening for ios

**Comment by hkirat** [comment]
Fix this using https://github.com/nodejs/node-gyp/issues/569#issuecomment-255589932
Now I see this error
"cwd" must be a string
on running 
tns run ios

**Comment by Nahasean94** [comment]
This is my output
`sean@Sean:~$ $ANDROID_HOME/tools/bin/sdkmanager --list
Installed packages:
  Path                              | Version | Description                       | Location                         
  -------                           | ------- | -------                           | -------                          
  build-tools;25.0.2                | 25.0.2  | Android SDK Build-Tools 25.0.2    | build-tools/25.0.2/              
  build-tools;25.0.3                | 25.0.3  | Android SDK Build-Tools 25.0.3    | build-tools/25.0.3/              
  build-tools;26.0.0                | 26.0.0  | Android SDK Build-Tools 26        | build-tools/26.0.0/              
  emulator                          | 26.1.2  | Android Emulator                  | emulator/                        
  extras;android;m2repository       | 47.0.0  | Android Support Repository        | extras/android/m2repository/     
  extras;google;g...e_play_services | 42      | Google Play services              | extras/google/g..._play_services/
  extras;google;m2repository        | 55      | Google Repository                 | extras/google/m2repository/      
  extras;google;webdriver           | 2       | Google Web Driver                 | extras/google/webdriver/         
  extras;m2reposi...ver;1.0.0-beta4 | 1       | Solver for ConstraintLayout 1.... | extras/m2reposi...er/1.0.0-beta4/
  extras;m2reposi...ut-solver;1.0.2 | 1       | Solver for ConstraintLayout 1.0.2 | extras/m2reposi...t-solver/1.0.2/
  extras;m2reposi...out;1.0.0-beta4 | 1       | ConstraintLayout for Android 1... | extras/m2reposi...ut/1.0.0-beta4/
  extras;m2reposi...nt-layout;1.0.2 | 1       | ConstraintLayout for Android 1... | extras/m2reposi...t-layout/1.0.2/
  patcher;v4                        | 1       | SDK Patch Applier v4              | patcher/v4/                      
  platform-tools                    | 26.0.0  | Android SDK Platform-Tools        | platform-tools/                  
  platforms;android-14              | 4       | Android SDK Platform 14           | platforms/android-14/            
  platforms;android-19              | 4       | Android SDK Platform 19           | platforms/android-19/            
  platforms;android-25              | 3       | Android SDK Platform 25           | platforms/android-25/            
  platforms;android-26              | 1       | Android SDK Platform 26           | platforms/android-26/            
  sources;android-25                | 1       | Sources for Android 25            | sources/android-25/              
  system-images;a...s_playstore;x86 | 4       | Google Play Intel x86 Atom Sys... | system-images/a..._playstore/x86/
  tools                             | 26.0.2  | Android SDK Tools                 | tools/                           

Available Packages:
  Path                              | Version      | Description                      
  -------                           | -------      | -------                          
  add-ons;addon-g..._apis-google-15 | 3            | Google APIs                      
  add-ons;addon-g..._apis-google-16 | 4            | Google APIs                      
  add-ons;addon-g..._apis-google-17 | 4            | Google APIs                      
  add-ons;addon-g..._apis-google-18 | 4            | Google APIs                      
  add-ons;addon-g..._apis-google-19 | 20           | Google APIs                      
  add-ons;addon-g..._apis-google-21 | 1            | Google APIs                      
  add-ons;addon-g..._apis-google-22 | 1            | Google APIs                      
  add-ons;addon-g..._apis-google-23 | 1            | Google APIs                      
  add-ons;addon-g..._apis-google-24 | 1            | Google APIs                      
  add-ons;addon-g...e_gdk-google-19 | 11           | Glass Development Kit Preview    
  build-tools;19.1.0                | 19.1.0       | Android SDK Build-Tools 19.1     
  build-tools;20.0.0                | 20.0.0       | Android SDK Build-Tools 20       
  build-tools;21.1.2                | 21.1.2       | Android SDK Build-Tools 21.1.2   
  build-tools;22.0.1                | 22.0.1       | Android SDK Build-Tools 22.0.1   
  build-tools;23.0.1                | 23.0.1       | Android SDK Build-Tools 23.0.1   
  build-tools;23.0.2                | 23.0.2       | Android SDK Build-Tools 23.0.2   
  build-tools;23.0.3                | 23.0.3       | Android SDK Build-Tools 23.0.3   
  build-tools;24.0.0                | 24.0.0       | Android SDK Build-Tools 24       
  build-tools;24.0.1                | 24.0.1       | Android SDK Build-Tools 24.0.1   
  build-tools;24.0.2                | 24.0.2       | Android SDK Build-Tools 24.0.2   
  build-tools;24.0.3                | 24.0.3       | Android SDK Build-Tools 24.0.3   
  build-tools;25.0.0                | 25.0.0       | Android SDK Build-Tools 25       
  build-tools;25.0.1                | 25.0.1       | Android SDK Build-Tools 25.0.1   
  build-tools;25.0.2                | 25.0.2       | Android SDK Build-Tools 25.0.2   
  build-tools;25.0.3                | 25.0.3       | Android SDK Build-Tools 25.0.3   
  build-tools;26.0.0                | 26.0.0       | Android SDK Build-Tools 26       
  cmake;3.6.4111459                 | 3.6.4111459  | CMake 3.6.4111459                
  docs                              | 1            | Documentation for Android SDK    
  emulator                          | 26.0.3       | Android Emulator                 
  extras;android;gapid;1            | 1.0.3        | GPU Debugging tools              
  extras;android;gapid;3            | 3.1.0        | GPU Debugging tools              
  extras;android;m2repository       | 47.0.0       | Android Support Repository       
  extras;google;auto                | 1.1          | Android Auto Desktop Head Unit...
  extras;google;g...e_play_services | 42           | Google Play services             
  extras;google;instantapps         | 1.0.0        | Instant Apps Development SDK     
  extras;google;m2repository        | 55           | Google Repository                
  extras;google;m...t_apk_expansion | 1            | Google Play APK Expansion library
  extras;google;market_licensing    | 1            | Google Play Licensing Library    
  extras;google;play_billing        | 5            | Google Play Billing Library      
  extras;google;simulators          | 1            | Android Auto API Simulators      
  extras;google;webdriver           | 2            | Google Web Driver                
  extras;m2reposi...ut-solver;1.0.0 | 1            | Solver for ConstraintLayout 1.0.0
  extras;m2reposi...er;1.0.0-alpha2 | 1            | com.android.support.constraint...
  extras;m2reposi...er;1.0.0-alpha3 | 1            | com.android.support.constraint...
  extras;m2reposi...er;1.0.0-alpha4 | 1            | com.android.support.constraint...
  extras;m2reposi...er;1.0.0-alpha5 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...er;1.0.0-alpha6 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...er;1.0.0-alpha7 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...er;1.0.0-alpha8 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...er;1.0.0-alpha9 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...ver;1.0.0-beta1 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...ver;1.0.0-beta2 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...ver;1.0.0-beta3 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...ver;1.0.0-beta4 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...ver;1.0.0-beta5 | 1            | Solver for ConstraintLayout 1....
  extras;m2reposi...ut-solver;1.0.1 | 1            | Solver for ConstraintLayout 1.0.1
  extras;m2reposi...ut-solver;1.0.2 | 1            | Solver for ConstraintLayout 1.0.2
  extras;m2reposi...nt-layout;1.0.0 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...ut;1.0.0-alpha2 | 1            | com.android.support.constraint...
  extras;m2reposi...ut;1.0.0-alpha3 | 1            | com.android.support.constraint...
  extras;m2reposi...ut;1.0.0-alpha4 | 1            | com.android.support.constraint...
  extras;m2reposi...ut;1.0.0-alpha5 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...ut;1.0.0-alpha6 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...ut;1.0.0-alpha7 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...ut;1.0.0-alpha8 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...ut;1.0.0-alpha9 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...out;1.0.0-beta1 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...out;1.0.0-beta2 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...out;1.0.0-beta3 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...out;1.0.0-beta4 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...out;1.0.0-beta5 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...nt-layout;1.0.1 | 1            | ConstraintLayout for Android 1...
  extras;m2reposi...nt-layout;1.0.2 | 1            | ConstraintLayout for Android 1...
  lldb;2.0                          | 2.0.2558144  | LLDB 2.0                         
  lldb;2.1                          | 2.1.2852477  | LLDB 2.1                         
  lldb;2.2                          | 2.2.3271982  | LLDB 2.2                         
  lldb;2.3                          | 2.3.3614996  | LLDB 2.3                         
  ndk-bundle                        | 15.1.4119039 | NDK                              
  patcher;v4                        | 1            | SDK Patch Applier v4             
  platform-tools                    | 26.0.0       | Android SDK Platform-Tools       
  platforms;android-10              | 2            | Android SDK Platform 10          
  platforms;android-11              | 2            | Android SDK Platform 11          
  platforms;android-12              | 3            | Android SDK Platform 12          
  platforms;android-13              | 1            | Android SDK Platform 13          
  platforms;android-14              | 4            | Android SDK Platform 14          
  platforms;android-15              | 5            | Android SDK Platform 15          
  platforms;android-16              | 5            | Android SDK Platform 16          
  platforms;android-17              | 3            | Android SDK Platform 17          
  platforms;android-18              | 3            | Android SDK Platform 18          
  platforms;android-19              | 4            | Android SDK Platform 19          
  platforms;android-20              | 2            | Android SDK Platform 20          
  platforms;android-21              | 2            | Android SDK Platform 21          
  platforms;android-22              | 2            | Android SDK Platform 22          
  platforms;android-23              | 3            | Android SDK Platform 23          
  platforms;android-24              | 2            | Android SDK Platform 24          
  platforms;android-25              | 3            | Android SDK Platform 25          
  platforms;android-26              | 1            | Android SDK Platform 26          
  platforms;android-7               | 3            | Android SDK Platform 7           
  platforms;android-8               | 3            | Android SDK Platform 8           
  platforms;android-9               | 2            | Android SDK Platform 9           
  sources;android-15                | 2            | Sources for Android 15           
  sources;android-16                | 2            | Sources for Android 16           
  sources;android-17                | 1            | Sources for Android 17           
  sources;android-18                | 1            | Sources for Android 18           
  sources;android-19                | 2            | Sources for Android 19           
  sources;android-20                | 1            | Sources for Android 20           
  sources;android-21                | 1            | Sources for Android 21           
  sources;android-22                | 1            | Sources for Android 22           
  sources;android-23                | 1            | Sources for Android 23           
  sources;android-24                | 1            | Sources for Android 24           
  sources;android-25                | 1            | Sources for Android 25           
  system-images;a...ult;armeabi-v7a | 4            | ARM EABI v7a System Image        
  system-images;a...-10;default;x86 | 4            | Intel x86 Atom System Image      
  system-images;a...pis;armeabi-v7a | 5            | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 5            | Google APIs Intel x86 Atom Sys...
  system-images;a...ult;armeabi-v7a | 2            | ARM EABI v7a System Image        
  system-images;a...ult;armeabi-v7a | 4            | ARM EABI v7a System Image        
  system-images;a...15;default;mips | 1            | MIPS System Image                
  system-images;a...-15;default;x86 | 4            | Intel x86 Atom System Image      
  system-images;a...pis;armeabi-v7a | 5            | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 5            | Google APIs Intel x86 Atom Sys...
  system-images;a...ult;armeabi-v7a | 4            | ARM EABI v7a System Image        
  system-images;a...16;default;mips | 1            | MIPS System Image                
  system-images;a...-16;default;x86 | 5            | Intel x86 Atom System Image      
  system-images;a...pis;armeabi-v7a | 5            | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 5            | Google APIs Intel x86 Atom Sys...
  system-images;a...ult;armeabi-v7a | 5            | ARM EABI v7a System Image        
  system-images;a...17;default;mips | 1            | MIPS System Image                
  system-images;a...-17;default;x86 | 3            | Intel x86 Atom System Image      
  system-images;a...pis;armeabi-v7a | 5            | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 5            | Google APIs Intel x86 Atom Sys...
  system-images;a...ult;armeabi-v7a | 4            | ARM EABI v7a System Image        
  system-images;a...-18;default;x86 | 3            | Intel x86 Atom System Image      
  system-images;a...pis;armeabi-v7a | 5            | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 5            | Google APIs Intel x86 Atom Sys...
  system-images;a...ult;armeabi-v7a | 5            | ARM EABI v7a System Image        
  system-images;a...-19;default;x86 | 5            | Intel x86 Atom System Image      
  system-images;a...pis;armeabi-v7a | 28           | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 28           | Google APIs Intel x86 Atom Sys...
  system-images;a...-tv;armeabi-v7a | 3            | Android TV ARM EABI v7a System...
  system-images;a...;android-tv;x86 | 3            | Android TV Intel x86 Atom Syst...
  system-images;a...ult;armeabi-v7a | 4            | ARM EABI v7a System Image        
  system-images;a...-21;default;x86 | 4            | Intel x86 Atom System Image      
  system-images;a...;default;x86_64 | 4            | Intel x86 Atom_64 System Image   
  system-images;a...pis;armeabi-v7a | 20           | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 20           | Google APIs Intel x86 Atom Sys...
  system-images;a...gle_apis;x86_64 | 20           | Google APIs Intel x86 Atom_64 ...
  system-images;a...-tv;armeabi-v7a | 1            | Android TV ARM EABI v7a System...
  system-images;a...;android-tv;x86 | 3            | Android TV Intel x86 Atom Syst...
  system-images;a...ult;armeabi-v7a | 2            | ARM EABI v7a System Image        
  system-images;a...-22;default;x86 | 5            | Intel x86 Atom System Image      
  system-images;a...;default;x86_64 | 5            | Intel x86 Atom_64 System Image   
  system-images;a...pis;armeabi-v7a | 14           | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 14           | Google APIs Intel x86 Atom Sys...
  system-images;a...gle_apis;x86_64 | 14           | Google APIs Intel x86 Atom_64 ...
  system-images;a...-tv;armeabi-v7a | 10           | Android TV ARM EABI v7a System...
  system-images;a...;android-tv;x86 | 10           | Android TV Intel x86 Atom Syst...
  system-images;a...ear;armeabi-v7a | 6            | Android Wear ARM EABI v7a Syst...
  system-images;a...ndroid-wear;x86 | 6            | Android Wear Intel x86 Atom Sy...
  system-images;a...-23;default;x86 | 9            | Intel x86 Atom System Image      
  system-images;a...;default;x86_64 | 9            | Intel x86 Atom_64 System Image   
  system-images;a...pis;armeabi-v7a | 21           | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 21           | Google APIs Intel x86 Atom Sys...
  system-images;a...gle_apis;x86_64 | 21           | Google APIs Intel x86 Atom_64 ...
  system-images;a...;android-tv;x86 | 11           | Android TV Intel x86 Atom Syst...
  system-images;a...fault;arm64-v8a | 7            | ARM 64 v8a System Image          
  system-images;a...ult;armeabi-v7a | 7            | ARM EABI v7a System Image        
  system-images;a...-24;default;x86 | 7            | Intel x86 Atom System Image      
  system-images;a...;default;x86_64 | 7            | Intel x86 Atom_64 System Image   
  system-images;a..._apis;arm64-v8a | 14           | Google APIs ARM 64 v8a System ...
  system-images;a...pis;armeabi-v7a | 14           | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 14           | Google APIs Intel x86 Atom Sys...
  system-images;a...gle_apis;x86_64 | 14           | Google APIs Intel x86 Atom_64 ...
  system-images;a...s_playstore;x86 | 13           | Google Play Intel x86 Atom Sys...
  system-images;a...;android-tv;x86 | 4            | Android TV Intel x86 Atom Syst...
  system-images;a...ear;armeabi-v7a | 3            | Android Wear ARM EABI v7a Syst...
  system-images;a...ndroid-wear;x86 | 3            | Android Wear Intel x86 Atom Sy...
  system-images;a...pis;armeabi-v7a | 5            | Google APIs ARM EABI v7a Syste...
  system-images;a...google_apis;x86 | 5            | Google APIs Intel x86 Atom Sys...
  system-images;a...gle_apis;x86_64 | 5            | Google APIs Intel x86 Atom_64 ...
  system-images;a...;android-tv;x86 | 3            | Android TV Intel x86 Atom Syst...
  system-images;a...ndroid-wear;x86 | 1            | Android Wear Intel x86 Atom Sy...
  system-images;a...google_apis;x86 | 4            | Google APIs Intel x86 Atom Sys...
  system-images;a...s_playstore;x86 | 4            | Google Play Intel x86 Atom Sys...
  tools                             | 26.0.2       | Android SDK Tools                
done
`

**Comment by thabungm** [comment]
Exception: The plugin tns-android@3.1.1 is already installed
I am facing the same issue
@hkirat Please provide the solution if you've fixed it

**Comment by NickIliev** [comment]
@thabungm for your case you probably have `tns-android` as a dependency in your `package.json`.
If that is true do the following:
- open `package.json`
- delete from your **dependencies** list `tns-android`
- remove `platforms` and `node_module`s folders
- rebuild the application

**Comment by hkirat** [comment]
Removed that. 
Android still doesn't compile
Same error. Version 22 or more required for SDK.
Works fine for ios though

**Comment by dtopuzov** [comment]
Hi @hkirat 

What I see in [this](https://gist.github.com/hkirat/08375dd138eb483fc029bae4344cf3b9) log is that you have only build-tools 26.

Can you run those commands:
```
$ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
$ANDROID_HOME/tools/bin/sdkmanager "tools"
$ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.3"
$ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.2"
$ANDROID_HOME/tools/bin/sdkmanager "build-tools;23.0.1"
$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25"
$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-23"
$ANDROID_HOME/tools/bin/sdkmanager "emulator"
$ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository"
$ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository"
```
and try `tns build android` again?

**Comment by hkirat** [comment]
Followed the steps
Getting this now
<img width="1220" alt="screen shot 2017-07-11 at 4 43 23 am" src="https://user-images.githubusercontent.com/8079861/28066869-9bf0df60-65f3-11e7-86ba-c8e50fcd1be3.png">

**Comment by dtopuzov** [comment]
@hkirat This happens because you have typo.
Please use `tns run android` instead of `tns run anroid`.

**Comment by hkirat** [comment]
Ya sorry bout that.
Thanks a ton. Works now
