### ISSUE TITLE
No emulator.log for Genymotion

### ISSUE THREAD

**Issue by scbenjamin** [NativeScript/nativescript-cli#294]
As the title states there is no `emulator.log` generated when running the `--geny` flag. I would imagine that for parity with standard `avd` emulators (and the `--emulator` flag) this should be generated and logged to.

**Affected Versions:** all
**System Config**: OSX 10.10, node 0.12

**Comment by rosen-vladimirov** [comment]
Hi @scbenjamin 
nativescript-cli does not generate any logs for the emulators. They are created by the emulators themselves. As far as I know, in Genymotion you can extract the required logs, by opening settings menu, go to MISC. tab and use the "Save all logs" files. You can check [Genymotion's user guide](https://www.genymotion.com/#!/developers/user-guide) for more information (just search for logs in it)  
If I've misunderstood your idea, could you share some more details on the specific case.

**Comment by alex-rokabilis** [comment]
i had the same problem with genymotion and i found that all the logs are been kept here:
`/home/{{USERNAME}}/.Genymobile/Genymotion/deployed/{{DEVICE_NAME}}/logcat.txt`

if you want something like a live log in the terminal you can use in ubuntu:
`watch tail -n 50 /home/{{USERNAME}}/.Genymobile/Genymotion/deployed/{{DEVICE_NAME}}/logcat.txt`

**Comment by rosen-vladimirov** [comment]
As this issue is not related to nativescript-cli, but to Genymotion, I'm closing this thread.
