### ISSUE TITLE
Duplicate console logs with LiveSync in 3.1

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/nativescript-cli#2941]
Since upgrading to TNS 3.1, I'm noticing that console log messages start to duplicate with every LiveSync. Each LiveSync seems to add another console log writer, so after 4 LiveSyncs, there are 4 duplicates for every log (see image below for example). (This is all testing on a Mac building and deploying to iOS.)

I'm also seeing that LiveSync is sending both the .JS and .TS files now. Not sure if it's related, but I  *think* the TypeScript files should be ignored by LiveSync, right?

Are others seeing this same behavior? Or is something gone awry in my local setup?

![image](https://user-images.githubusercontent.com/647319/27765776-71233870-5e80-11e7-9fdf-c3c1a29cb8ea.png)

**Comment by Gribanov** [comment]
Same problem. 
MacOs 10.12.5
tns --version 3.1.2

**Comment by rosen-vladimirov** [comment]
Hey @toddanglin , @Gribanov 
Thank you for reporting this. We've identified the root cause of this and we'll provide a fix for our next release.
