### ISSUE TITLE
can't uninstall using npm uninstall nativescript -g after install unsuccessful

### ISSUE THREAD

**Issue by blankhang** [NativeScript/nativescript-cli#2942]
Hey
i was trying to install nativescript before many times but got no lucky about
same error 
You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.

All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.1.1           │ 3.1.1          │ Up to date    │
│ tns-core-modules │                 │ 3.1.0          │ Not installed │
│ tns-android      │                 │ 3.1.1          │ Not installed │
│ tns-ios          │                 │ 3.1.0          │ Not installed │

run tns doctor 

Support for Node.js 8.1.3 is not verified. This CLI might not install or run properly.
npm WARN
 nativescript-check-cocoapods@0.0.1 No description
npm WARN nativescript-check-cocoapods@0.0.1 No repository field.
npm
 WARN nativescript-check-cocoapods@0.0.1 No license field.
+ tns-ios@3.1.0
added 1 package in 3.467s
  ◠ Verifying CocoaPods. This may take some time, please be patient..
You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
Run $ $ANDROID_HOME/tools/bin/sdkmanager to manage the Android Support Repository.

seems like miss the ANDROID's stuff
but when i check the dir
/usr/local/Caskroom/android-sdk 
i can see there have a folder with named 3859397 
and the size of the folder is 6.5G 
so i think the android sdk should install well?

after fail serval times i give it up
so i trying to uninstall this 

when i run this npm uninstall nativescript -g
and get error = = OMG
why is this have to be so hard

here is the debug log of npm

plz help me to uninstall this completely thank you very much!

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   'nativescript',
1 verbose cli   '-g' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session c41bf4309b3c1c08
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 verbose stack RangeError: Maximum call stack size exceeded
7 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:31:40)
7 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
7 verbose stack     at Array.forEach (native)
7 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
7 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
7 verbose stack     at Array.forEach (native)
7 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
7 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:377:5)
7 verbose stack     at Array.forEach (native)
7 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
7 verbose stack     at Array.forEach (native)
7 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
7 verbose stack     at Array.forEach (native)
7 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
7 verbose stack     at Array.forEach (native)
7 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
8 verbose cwd /Users/blank/HelloWorld
9 verbose Darwin 16.6.0
10 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "uninstall" "nativescript" "-g"
11 verbose node v8.1.3
12 verbose npm  v5.0.3
13 error Maximum call stack size exceeded
14 verbose exit [ 1, true ]

**Comment by blankhang** [comment]
i am using  Mac 10.12.5 version

**Comment by blankhang** [comment]
/usr/local/bin/xcodeproj
Successfully installed xcodeproj-1.5.0
Parsing documentation for xcodeproj-1.5.0
Parsing sources...
100% [55/55]  lib/xcodeproj/xcodebuild_helper.rb                                
1 gem installed

Configuring your system for Android development... This might take some time, please, be patient.
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
Do you want to install Android emulator? (y/n)
n
The ANDROID_HOME and JAVA_HOME environment variables have been added to your .bash_profile/.zprofile
Restart the terminal or run `source ~/.bash_profile` to use them.
Your components are up-to-date.


when i trying to reinstall android-sdk via brew cask reinstall android-sdk

Installing Cask android-sdk
==> Warning: File /Users/blank/.android/repositories.cfg could not be loaded.

**Comment by blankhang** [comment]
when i trying to uninstall the node 8 and then reinstall the node version 6 
it seems now tns info 
All NativeScript components versions information
┌──────────────────┬────────────────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version            │ Latest version │ Information      │
│ nativescript     │ 3.1.1                      │ 3.1.1          │ Up to date       │
│ tns-core-modules │ 3.0.1                      │ 3.1.0          │ Update available │
│ tns-android      │ 3.2.0-next-2017-06-28-1901 │ 3.1.1          │ Up to date       │
│ tns-ios          │ 3.2.0-2017-6-30-2          │ 3.1.0          │ Up to date      

so now finnally worked?
the NativeScript DONT SUPPORT THE VERSION 8 OF NODE BUT VERSION6 ?

**Comment by dtopuzov** [comment]
Hi @blankhang can you run those lines:
```
$ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
$ANDROID_HOME/tools/bin/sdkmanager "tools"
$ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.3"
$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25"
$ANDROID_HOME/tools/bin/sdkmanager "emulator"
$ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository"
$ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository"
```
and run `tns doctor` again?

**Comment by blankhang** [comment]
thanks for response
Last login: Mon Jul  3 14:49:57 on ttys001
blankdeMBP:~ blank$ ls $ANDROID_HOME/tools/bin/sdkmanager
/usr/local/Caskroom/android-sdk/3859397/tools/bin/sdkmanager
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "tools"
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.3"
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository"
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
Warning: An error occurred while preparing SDK package Android Support Repository: SSL peer shut down incorrectly.
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository"
Warning: File /Users/blank/.android/repositories.cfg could not be loaded.
done
blankdeMBP:~ blank$ tns doctor
Verifying CocoaPods. This may take more than a minute, please be patient.
  ◞ Installing iOS runtime.npm
  ◡ Installing iOS runtime. notice created a lockfile as package-lock.json. You should commit this file.

npm WARN nativescript-check-cocoapods@0.0.1 No description

npm WARN nativescript-check-cocoapods@0.0.1 No repository field.
npm WARN
 nativescript-check-cocoapods@0.0.1 No license field.



+ tns-ios@3.1.0
added 1 package in 2.749s
  ◝ Verifying CocoaPods. This may take some time, please be patient..
You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
Run $ $ANDROID_HOME/tools/bin/sdkmanager to manage the Android Support Repository.

There seem to be issues with your configuration.
? Do you want to visit the official documentation? (Y/n)

**Comment by dtopuzov** [comment]
Can you run:
`/Users/blank/.android/repositories.cfg`
..and then all the steps from the [commend ](https://github.com/NativeScript/nativescript-cli/issues/2942#issuecomment-312641450) above

**Comment by blankhang** [comment]
Last login: Mon Jul  3 21:55:22 on ttys000
blankdeMBP:~ blank$ ls $ANDROID_HOME/tools/bin/sdkmanager
/usr/local/Caskroom/android-sdk/3859397/tools/bin/sdkmanager
blankdeMBP:~ blank$ touch /Users/blank/.android/repositories.cfg
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "tools"
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.3"
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25"
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository"
done
blankdeMBP:~ blank$ $ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository"
done
blankdeMBP:~ blank$ tns doctor
Verifying CocoaPods. This may take more than a minute, please be patient.
  ◟ Installing iOS runtime.npm 
  ◜ Installing iOS runtime.notice created a lockfile as package-lock.json. You should commit this file.

npm WARN
 nativescript-check-cocoapods@0.0.1 No description
npm WARN nativescript-check-cocoapods@0.0.1 No repository field.
npm WARN
 nativescript-check-cocoapods@0.0.1 No license field.



+ tns-ios@3.1.0
added 1 package in 3.306s
  ◠ Verifying CocoaPods. This may take some time, please be patient..
Your components are up-to-date.

No issues were detected.
blankdeMBP:~ blank$ 
it worked ?

**Comment by dtopuzov** [comment]
Yeah, it looks everything is fine :)

**Comment by blankhang** [comment]
thank you very much !!!
