### ISSUE TITLE
Debugging elements in Android chrome debug tools is not possible

### ISSUE THREAD

**Issue by tscislo** [NativeScript/nativescript-cli#2956]
I have a project that I created using tns 3.0.1 and now I updated my cli to 3.1.1 and also the version of tns-android is 3.1.1 in my package.json. I removed the Android platform and added it again after this change.

However when running in debug mode tns debug android in chrome dev tools:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000 i still have nothing in my Elements tab.

Am I doing something wrong?

**Comment by Pip3r4o** [comment]
Hey @tscislo!

Please make sure that your application has android runtime of version 3.1, and the cross-platform tns-core-modules package version 3.1. In your particular case any CLI 3.0+ will work, but we do recommend using the latest stable version.

**Comment by tscislo** [comment]
@Pip3r4o thanks! Problem was that I didn't have tns-core-modules version 3.1.0.
