### ISSUE TITLE
(Android) CLI not refreshing app

### ISSUE THREAD

**Issue by lukeramsden** [NativeScript/nativescript-cli#2970]
Running `tns run android --emulator` builds the app fine, opens the emulator, installs, but then doesn't open the app. Plus, when I make a change, it says it refreshes, kills the app, but when I open the app through the menu on the emulator it hasn't changed

Node version 6.11.1
NativeScript version 3.1.2

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.2           │ 3.1.2          │ Up to date  │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by lukeramsden** [comment]
I have to run `tns run android --emulator --clean --no-watch`

**Comment by dtopuzov** [comment]
May be you changed application bundle identifier in your package.json?

**Comment by Plamen5kov** [comment]
Hi @lukeramsden,
in addition of @dtopuzov`s suggestion, you can try running the same application using cli from next. You can install the latest version of cli like so:
`npm install -g nativescript@next`
Please tell us if the problem still persists after you've tried both suggestions.

**Comment by lukeramsden** [comment]
@dtopuzov @Plamen5kov Turns out, the change to app.gradle when I first made the app wasn't committed due to me switching PCs. Thanks for the help.
