### ISSUE TITLE
Image replacement is not respected during tns run android

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2981]
If an existing image in the `app` folder (outside App_Resources) is replaced during `tns run android`, the application on the device does not get updated with the new image. However, if the application is restarted, the new image is shown. The same scenario works for iOS.

Version of CLI, runtimes and *tns-core-modules* packages: `3.1.0`.

Steps:
- tns create appJS && appJS
- mkdir app/img/ - make a `img` directory in the `app` folder
- add an image to the `app/img` folder
- refer the image in the `main-page.xml`, for example: `<Image src="~/img/icon.png" />`
- tne run android
- replace the image

Expected: the application page refreshes and the new image shows.
Actual: the application page refreshes, but the new image does not show. The old one is still on the page.

**Comment by Plamen5kov** [comment]
On the cli and runtime side everything looks ok. Runtime has livesynced the new image into the application, and calls the livesync hook as it should. That leads me to believe the nativescript modules can't recognize that the `icon.png` has changed. ping: @PanayotCankov @vakrilov

**Comment by hshristov** [comment]
@vchimev, @Plamen5kov We are using memory and disk cache on the Image component. That is why changing the file won't change the currently shown image.

There are several options:
- [ ] Invalidate the whole cache on a livesync operation
- [ ] Disable cache for specific Image instance

**Comment by Plamen5kov** [comment]
My vote goes toward `Disable cache for specific Image instance`.

**Comment by vchimev** [comment]
@hshristov, what do you think would be the best?
*Disable cache for specific Image instance* sounds better to me.

**Comment by Plamen5kov** [comment]
I'm opening a new issue in the modules because this is no longer a CLI problem.
