### ISSUE TITLE
Doesn't show time taken to build for ios

### ISSUE THREAD

**Issue by ishandutta2007** [NativeScript/nativescript-cli#2998]
`tns build android` shows time time taken to complete build but `tns build ios` doesn't

**Comment by rosen-vladimirov** [comment]
Hey @ishandutta2007 ,
Thank you for sharing this idea.
Currently the build time for Android is shown on the terminal from the Gradle itself. For iOS, `xcodebuild` does not print such information by default. I like the idea and it should be pretty straightforward to implement this in CLI's code itself.
In fact, you can try implementing it and send us a pull request, we'll be happy to review it.

**Comment by preethamvishy** [comment]
I would like to try this. Is this still up for grabs?

**Comment by amaaniqbal** [comment]
@rosen-vladimirov @pkoleva Should I give this a shot as a part of `hacktoberfest`?
