### ISSUE TITLE
multiple errors when building for android and ios

### ISSUE THREAD

**Issue by RyanSMurphy** [NativeScript/nativescript-cli#3012]
Hi, I raised this issue on nativescript-angular but am also looking here for help as I feel it applies strongly. Any help?

https://github.com/NativeScript/nativescript-angular/issues/916

Thanks in advance

**Comment by Pip3r4o** [comment]
Hey @RyanSMurphy I replied in the SO topic too, but FWIW - Please install typescript version 2.3, I believe the new TypeScript which was just released may be causing all the build errors.

**Comment by dtopuzov** [comment]
Closing since issue is resolved in angular repo.
