### ISSUE TITLE
JavaScript iteration Function

### ISSUE THREAD

**Issue by MMAANNSS** [NativeScript/nativescript-cli#3015]
Hello Every one i want to solve this problem with javascript and es6 the problem is 👍 
if i have an array like that [1,2,3,4]  so i want to check every probability like the following and return the greatest number
1--> (1x2) + (3x4) = 14
2--> (1x3) + (2x4) = 11
3--> (1x4) + (2x3) = 10
then the greatest number is 14 as a return result ---> how can i do that using function and keep in mind if the array have 100 number how can i do the 99 probabilities dynamically

**Comment by dtopuzov** [comment]
Hi @MMAANNSS 

How this is related to Nativescript CLI?

It looks like a question for [stackoverflow](http://stackoverflow.com/questions/tagged/nativescript).
