### ISSUE TITLE
[Xcode9/iOS11] Tns run ios doesn't recognize ios 11 simulators

### ISSUE THREAD

**Issue by kristyanYochev** [NativeScript/nativescript-cli#3018]
After installation of XCode 9 beta 4 and the ios11 simulators that come with it and trying to run an app in the simulator tns just fires up the ios10 simulator and doesn't install the app on ios11.
This is tns version 3.0.3

**Comment by dtopuzov** [comment]
Hi @kristyanYochev 

Can you please run `xcode-select -print-path` on your machine and paste the output?

I can confirm that current behavior with `Xcode9` and `nativescript@3.1.3` is:
- `tns run ios --emulator` will start iOS Simulator with iOS 10 even if iOS 11 is available.
- If iOS 11 Simulator is manually started then `tns run ios` will deploy on it and app will run

How to list all running simulators:
```
xcrun simctl list 
```
To start iOS Simulator: 
```
xcrun simctl boot <ID>
```
To stop iOS Simulator: 
```
xcrun simctl shutdown <ID>
```

**Comment by dtopuzov** [comment]
Hi @kristyanYochev 

It is OK with Xcode9-beta5.

Closing the issue for now and will have in mind to check it with official release of Xcode9.
