### ISSUE TITLE
Nativescript installer fails on vanilla windows 10 - 'Unsupported platform for fsevents@1.1.2'

### ISSUE THREAD

**Issue by sjworkuid** [NativeScript/nativescript-cli#3019]
Tried to install Nativescript on a brand new Windows 10 machine using the WIndows Installer.
Install fails with the following error:

[3ABC:3314][2017-07-30T21:33:56]i000: Executing operation: InstallNativeScript.
[3ABC:3314][2017-07-30T21:34:34]e000: Executing operation InstallNativeScript failed. 
Error: npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

See attached full setup log. Let me know if I can help with any more information. 

Hopefully someone can provide a clue on how to move ahead. Really looking forward to getting started with dev - but stuck at Step 0 for now :)

[NativeScript_CLI_Setup_20170730212711.txt](https://github.com/NativeScript/nativescript-cli/files/1186580/NativeScript_CLI_Setup_20170730212711.txt)

**Comment by pkoleva** [comment]
Hi @sjworkuid,

Would you try upgrading to npm 3.10.10 and retry the installation. If the installator fails again could you try installing nativescript trough npm `npm i -g nativescript` and then run `tns doctor` to verify the installation was successful.

Hope one of these works for you!

**Comment by tigrenok00** [comment]
This happens to me too. Wanted to upgrade cli from 3.1.1 to 3.1.3.
Tried both suggestions here, but it did not help :(

**Comment by pkoleva** [comment]
Hi @tigrenok00,

Could you send us more details on your setup - npm and node version, OS, and the log when executing `npm i - g nativescript `.

Thanks!

**Comment by tigrenok00** [comment]
Windows 10
Node.js 6.9.1 (x64)

![image](https://user-images.githubusercontent.com/23075641/28818009-93f726a0-76b2-11e7-9873-32169c79553e.png)


[npm-debug.zip](https://github.com/NativeScript/nativescript-cli/files/1190069/npm-debug.zip)

**Comment by dtopuzov** [comment]
Hi @tigrenok00 

This screens says you have `npm@3.10.8`, which is the problematic one. 
Please upgrade to `npm@3.10.10` or newer.

Related to https://github.com/NativeScript/nativescript-cli/issues/2980

**Comment by sjworkuid** [comment]
That did the trick - thx.
Steps below:

Completely uninstalled Node and npm:

   - Uninstall Node.js (select Uninstall, not the Repair option).
   - Go into %programfiles%\nodejs and delete the entire folder.
   - Delete %appdata%\npm and %appdata%\npm-cache.
   - Edit your PATH and remove everything that references npm (to do so,
   hit "Start" and search for "Environment Variables").

Reinstall latest node and npm from:
https://nodejs.org/en/download/

After install:
node v6.11.2
npm 3.10.10

Restarted the nativescript win installer - finished successfully!

Thanks.

**Comment by dtopuzov** [comment]
We will provide updated version of Windows installer next week that should resolve the issue.

**Comment by tigrenok00** [comment]
Thanks for the steps, I will try them in this sequence. What I did before was just updating the npm to 3.10.10 but it still used the previous version for the installation somehow.

**Comment by dtopuzov** [comment]
@tigrenok00 @sjworkuid
We released new version of Windows Installer that should fix the issue (now we install newer version of `node` and `npm`).

**Comment by mesterum** [comment]
`npm i -g npm` just helped me upgrade my npm.

**Comment by KristiyanFxy** [comment]
> Hi @tigrenok00

This screens says you have npm@3.10.8, which is the problematic one.
We should check the installer and if it install npm@3.10.8 on brand new machines we should fix it.

Workaround:
Please upgrade to npm@3.10.10 or newer.

Related to #2980

Thanks, `npm install npm@latest -g` solved the problem 👍
