### ISSUE TITLE
Does not work behind proxy

### ISSUE THREAD

**Issue by briangabriel** [NativeScript/nativescript-cli#302]
I can install NativeScript via npm with no issues, but there is no way to configure the http-client with the proper proxy settings.

E:\LocalDev\nativescript>tns create hello-world --log trace
Starting watch on killswitch C:\Users\gabrielb\AppData\Local\Temp\gabrielb\KillSwitches\cli
Creating a new NativeScript project with name hello-world and id org.nativescript.helloworld at location E:\LocalDev\nativescript\hello-world
Using NativeScript hello world application
User-Agent: AppBuilderCLI/0.9.1 (Node.js 0.10.28; win32; x64)
httpRequest: { method: 'GET',
  host: 'registry.npmjs.org',
  port: null,
  path: '/tns-template-hello-world',
  headers:
   { Accept: 'application/json; charset=UTF-8, */*;q=0.8',
     'User-Agent': 'AppBuilderCLI/0.9.1 (Node.js 0.10.28; win32; x64)',
     'Accept-Encoding': 'gzip,deflate' } }
httpRequest: Sending:
[nothing]
{ [Error: connect ETIMEDOUT] stack: [Getter] }
Error: connect ETIMEDOUT

**Comment by rosen-vladimirov** [comment]
Hi @briangabriel 
It looks like there's a problem with the http-proxy. Could you try the suggestion from [this blog post](http://wil.boayue.com/blog/2013/06/14/using-npm-behind-a-proxy/): 
```npm config set proxy http://proxy.company.com:8080``` for example
Hopefully this will solve the issue.

**Comment by briangabriel** [comment]
I have no problems with npm, the issue is that the `NodePackageManager.getAvailableVersions` method calls the npm registry via a straight up HTTP request:

    var url = NodePackageManager.NPM_REGISTRY_URL + packageName;
    var response = this.$httpClient.httpRequest(url).wait().body;

**Comment by rosen-vladimirov** [comment]
Hi @briangabriel ,

You are absolutely correct. We are working on adding support for proxy, but meanwhile, can you try one more thing:
Can you try installing [this custom package](https://www.dropbox.com/s/wrn77fgmmdvxg6c/nativescript-0.9.1.tgz?dl=0) of nativescript-cli. Just download the file and execute:
```$ npm i nativescript-0.9.1.tgz -g```
After the installation finishes, find the place where nativescript is installed, open ```<nativescript-cli-dir>\lib\config.js``` and modify FIDDLER_HOSTNAME to match your proxy.
After that can you try creating new project and adding platforms, so we'll see if this works. Your help is appreciated. 
One more thing, the package I've shared is created from [this branch](https://github.com/NativeScript/nativescript-cli/tree/vladimirov/proxy-test), so you can compare it with our latest release branch to see my changes - they are only in the config file.

**Comment by rosen-vladimirov** [comment]
Hi @briangabriel 
In case you have problems with above link (its from dropbox), you can try [this one](https://github.com/rosen-vladimirov/nativescript-cli/releases/download/v0.9.1-proxy-test/nativescript-0.9.1.tgz) - this time I've uploaded the package directly in github.

**Comment by Klors** [comment]
I've tried the version and it doesn't work for me, probably because the port is hard-coded to 8888 (the xxx.xxx.xxx.xxx is really the right IP address, just blanked). I've tried it with just the host IP address and with the IP address and port, the result for both is the same.

    httpRequest: { method: 'GET',
     host: 'xxx.xxx.xxx.xxx',
     port: 8888,
     path: 'http://registry.npmjs.org/tns-template-hello-world',
     headers:
      { Host: 'registry.npmjs.org',
        Accept: 'application/json; charset=UTF-8, */*;q=0.8',
        'User-Agent': 'AppBuilderCLI/0.9.1 (Node.js 0.10.33; win32; x64)',
        'Accept-Encoding': 'gzip,deflate' } }
    httpRequest: Sending:
    [nothing]
    { [Error: connect ECONNREFUSED] stack: [Getter] }
    Error: connect ECONNREFUSED

**Comment by rosen-vladimirov** [comment]
Hi @Klors 
You are correct, in the package I've prepared, the port is hardcoded. We've prepared a fix for this and it will be included in our next release. You can try it now by downloading [this package](https://github.com/rosen-vladimirov/nativescript-cli/releases/download/v0.9.1-proxy-test/new-nativescript-0.9.1.tgz) and modifying ```<installation dir>\config\config.json``` file - just set USE_PROXY to be true and set your PROXY_HOSTNAME and PROXY_PORT. You can take a look at [this issue](https://github.com/NativeScript/nativescript-cli/issues/297) where the problem had been widely discussed, but finally the solution was found.

**Comment by Klors** [comment]
That's great, I'll try it on Monday thanks.

**Comment by Klors** [comment]
That worked perfectly thanks

**Comment by rosen-vladimirov** [comment]
Thank you for testing it. As I've said - the same fix will be included in our next release. I'm closing this thread now, but feel free to contact us in case you have any other problems with the configuration.

**Comment by vogatsiko** [comment]
I am having the same issue.  
Tried the suggested solutions: added proxy to native script/config/config.json, set proxy on the command line....

**Comment by datatribe** [comment]
I'm having the same trouble as @vogatsiko - >tns run android gets to 'Preparing project... , Executing before-prepareJSApp hook.... Gradle clean... and as it attempts to download gradle-4.10.2-all.zip the connection times out.  I've placed my proxy config in my gradle.properties file in my <userhome>/.gradle folder like:

systemProp.http.proxyHost=<our.proxy.ip>
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=<our.proxy.ip>
systemProp.https.proxyPort=8080

but even after restarting the CMD window still have this issue (Windows 10). I've searched a bit, but haven't found where gradlew would use a separate properties file though I see people refer to it.  Just copying my gradle.properties didn't help, I guess because gradlew is supposed to run standalone apart from an existing install.  It seems like poking proxy settings into project specific files is a bad solution though apparently the only way to do this presently?

**Comment by rosen-vladimirov** [comment]
Hey @datatribe ,
When setting the proxy in http.proxyHost and https.proxyHost, have you excluded the protocol, i.e. if the proxy is at 192.168.1.102, you'll have to put:
```
systemProp.http.proxyHost=192.168.1.102
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=192.168.1.102
systemProp.https.proxyPort=8080
```

I remember I've seen gradle failing in case you've added `http://` in front of the IP, but probably it is not the case here. 
What you can try is navigating to `<project dir>/platforms/android` and execute `gradlew --stacktrace --debug` and see if it will give you more information what's happening.

**Comment by datatribe** [comment]
Thanks @rosen-vladimirov, 

I was sure not to include http://.  I tried your suggestion to debug and got some interesting results.  The build failed the first two times with a lot of stack trace output, so I piped the output to a file and I noticed the behavior changed.  It no longer said "build failed in 43 seconds".

I also have this line in my properties file, added by me as I was troubleshooting:
org.gradle.daemon=true

The build now concludes with the following:

**Comment by datatribe** [comment]
Apparently piping to an output file isn't a good idea.  I notice most of the visible output is missing.

**Comment by datatribe** [comment]
I traced the problem to the ip address provided for our proxy server.  Thanks for your help @rosen-vladimirov  - you helped me pinpoint the issue.

**Comment by rosen-vladimirov** [comment]
I'm so glad you were able to trace the issue. Happy coding!
