### ISSUE TITLE
Utilize ios-sim-portable and remove redundant code from cli

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#3022]
### Tell us about the problem
There is redundant/dublicated code inside emulator-image-service and emulator-service which can be replaced with logic from ios-sim-portable.

As a part of this effort it will be great to generate d.ts files for the  ios-sim-portable library and provide a strict public api.

**Comment by dtopuzov** [comment]
Related: https://github.com/NativeScript/nativescript-cli/issues/1584

**Comment by rosen-vladimirov** [comment]
The mentioned services do not exist anymore in CLI's repository, so I'm closing this issue.
