### ISSUE TITLE
Improve the gathered analytics for the installers success rate

### ISSUE THREAD

**Issue by etabakov** [NativeScript/nativescript-cli#3025]
**The Problem:** In order to be able to create a good installers scripts for NativeScripts, we need insights about what are the current problems and what part of the users are experiencing them.

**Current State:** Currently, we are gathering some data about the success of the local setup, but the data is polluted by all kind of cases that are not related to the success rate itself like upgrades, multiple runs of tns doctor, etc.

**Expected Behavior:** We should track the state of the environment before and after executing the setup scripts. This will give us information in what percent of the usage the scripts actually provide a working environment.

**Comment by Natalia-Hristova** [comment]
Now the state of the environment is checked before and after running the setup script.
