### ISSUE TITLE
How to set Livesync on Android Studio Emulator 

### ISSUE THREAD

**Issue by AntiraLoachote** [NativeScript/nativescript-cli#3031]
I created project Angular2 nativescript cli on version 3.1.1 
my creating steps as following >> http://docs.nativescript.org/angular/tutorial/ng-chapter-1#appendix-a-choosing-an-editor
using Android Studio Emulator 

when I edited .html and .css code then emulator did not display in real-time, the app closed itself before opened the app again with new codes.

Is there a way to change setting to set the app display result in real-time without app closing?

**Comment by dtopuzov** [comment]
Hi @AntiraLoachote 

Do you start the livesync process with `tns run android` or with some other CLI command or you start if via some IDE extension?

Is it a hello-world project or it includes some plugins like `nativescript-dev-sass` or `nativescript-dev-less`?

Current behavior is:
- `css` and `html` changes will cause restart of angular app itself, you will not see the splash screen of nativescript application (but application state will be restarted, so if you navigated somewhere you will be back on home page after file change)
- `ts` changes will cause restart of nativescript application and you will see the splash screen of the app.

We have an issue for improvements in this area, so you can add more suggestions there: https://github.com/NativeScript/NativeScript/issues/4554
https://github.com/NativeScript/nativescript-cli/issues/2153
