### ISSUE TITLE
how to write objective c  code in to nativescript?

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/nativescript-cli#3037]
var citruspayment;
citruspayment=citruspayment.new();
var payparam = payparam.new();

Objective c :
[citruspayment RequestQuery:payparam successBlock:^(NSString* SuccessData) { 

} failedBlock:^(NSString*errorCode,NSString *errorData) { 
}];

I tried in this example code in nativescript(please check below one  i wrote correctly or not?)

 citruspayment.RequestQuery, payparam(successBlock, function (ParamData) {
        console.log(ParamData.TransactionType, ParamData.PaymentMethod);
    });

**Comment by dtopuzov** [comment]
Hi @priyangamani 

I hope those articles might help:
https://docs.nativescript.org/core-concepts/accessing-native-apis-with-javascript
https://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing.html
