### ISSUE TITLE
No option to have different app identifiers for iOS and Android and livesync working

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#3040]
### Tell us about the problem
Currently livesync woks with the application identifier specified inside "package.json". In order to have different application identifiers for iOS and Android currently, the user has to edit the "applicationId" key inside "app.gradle" file. This change will cause the livesync functionality to not work properly. 

A solution could be to add the option for "id" key inside "package.json" to have values for iOS and Andoid. Something like:
```JavaScript
"nativescript": {
    "id": {
        "ios": "{{appID1}}" ,
        "android": "{{appID2}}"
    }
  }
```
### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.1
- Runtime(s): 3.0.0
- Plugin(s): 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Change the application Id in `/App_Resources/android/app.gradle`

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "{{appID1}}" 

Change the application Id in `package.json` to something different.

  "nativescript": {
    "id": "{{appID2}}",

### Solution
1. Set in `package.json`
```JavaScript
"nativescript": {
    "id": {
        "ios": "{{appID1}}" ,
        "android": "{{appID2}}"
    }
  }
```
2. If you are using old project, remove the `applicationId` key from `{AppResources}/Android/app.gradle`
3. If you have opened the the project in NS Sidekick remove the `{AppResources}/Android/settings.json` file
4. Run the build

**Comment by KristianDD** [comment]
Related to #2825

**Comment by frapaa** [comment]
Is it possible to also make this available during a build step? I have a case where the same app will be built and deployed for multiple customers on their Apple and Google accounts, so they all need a unique app id. If we change this in the files (package.json for iOS and app.gradle + shortcuts.xml for Android) as part of the build process, the release build will have uncommitted changes and be "dirty".

**Comment by Gamadril** [comment]
```
"nativescript": {
    "id": {
        "ios": "{{appID1}}" ,
        "android": "{{appID2}}"
    }
  }
```
This really useful feature should be documented in https://docs.nativescript.org/core-concepts/project-structure
It really helps if you must have "-" in your iOS app ID, but are not allowed to use it in android app ID...
