### ISSUE TITLE
I'm with this problem of the image, the installation don't exit of this screen.

### ISSUE THREAD

**Issue by TecladistaProd** [NativeScript/nativescript-cli#3057]
the application wrote for don't shut down when it installing, what do i ?
![image](https://user-images.githubusercontent.com/26743405/29250880-c61fd77c-8020-11e7-8b71-74bc09ccc5a4.png)

**Comment by dtopuzov** [comment]
Hi @TecladistaProd 

How much you waited this to compete?
This steps of the installation may download several GB, so it might take long on low bandwidth connection.

**Comment by TecladistaProd** [comment]
Thanks My dear, i use the comand line form to install,
