### ISSUE TITLE
Error Domain=IDEProvisioningErrorDomain Code=9

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3059]
_From @b4rtt on August 11, 2017 20:0_

Hi, I am kinda desperated. Everytime when I try to `tns publish ios` I see this error. 

```
Archive at: /Users/roman/Desktop/eSports/PiratiGo/platforms/ios/build/archive/PiratiGo.xcarchive
2017-08-11 21:56:12.694 xcodebuild[44465:1369169] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/c8/kcxg82ln2mn7qy9v0rtppm8w0000gn/T/PiratiGo_2017-08-11_21-56-12.693.xcdistributionlogs'.
2017-08-11 21:56:16.141 xcodebuild[44465:1369169] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fc68767cee0>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
    "Error Domain=IDEProvisioningErrorDomain Code=9 \"\"PiratiGo.app\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"PiratiGo.app\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the \"Default\" build configuration in the project editor.}"
)}
error: exportArchive: "PiratiGo.app" requires a provisioning profile.

Error Domain=IDEProvisioningErrorDomain Code=9 ""PiratiGo.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="PiratiGo.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the "Default" build configuration in the project editor.}
```

I really don't know what to do. I tried almost everything. Provision profile I have. Bud I dunno know why it doesn't see it. 

Thanks for any help

_Copied from original issue: NativeScript/nativescript-angular#938_

**Comment by Mitko-Kerezov** [comment]
@b4rtt
Let us continue the discussion from https://github.com/NativeScript/sidekick-feedback/issues/25 here.
As discussed in https://github.com/NativeScript/sidekick-feedback/issues/25 could you try re-creating your provisioning profile and certificate and see if it does the trick.

Let me know if it helps.

**Comment by dtopuzov** [comment]
Hi @b4rtt,

We had an issue with Xcode 8.3 and Distribution/AdHoc profiles and it should be fixed in `nativescript@next` 3 days ago.

Can you please try:
```
npm un -g nativescript
npm cache clean
npm i -g nativescript@next
``` 

If it still fails please specify Xcode, npm and node versions.

Possible workaround you can try:
```
tns build ios --provision <id>
tns publish ios <AppleID> <Password> --ipa <path-to-ipa-from-build-above>
```

**Comment by b4rtt** [comment]
@dtopuzov it's working! Thanks

**Comment by dtopuzov** [comment]
Thanks @b4rtt !

The fix will be included in next official version of nativescript (it will be available at the end of the month), until then you can go with `nativescript@next`.
