### ISSUE TITLE
Cant find material theme

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [NativeScript/nativescript-cli#306]
[aapt] Generating resource IDs...
     [aapt] /home/siddhartha/MyApp/platforms/android/res/values-v21/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'.

BUILD FAILED
/home/siddhartha/Downloads/android-sdk-linux/tools/ant/build.xml:653: The following error occurred while executing this line:
/home/siddhartha/Downloads/android-sdk-linux/tools/ant/build.xml:698: null returned: 1

Total time: 1 second
Command ant failed with exit code 1

**Comment by Fatme** [comment]
https://github.com/NativeScript/nativescript-cli/issues/299
