### ISSUE TITLE
Not able to install by npm i -g nativescript

### ISSUE THREAD

**Issue by shinokada** [NativeScript/nativescript-cli#3062]
OS: macOS sierra v 10.12.6
I tried `npm i -g nativescript`. But it gives me the following error.

> ➜  ~ npm i -g nativescript
> 
> 
>  nativescript@3.1.3 preuninstall /usr/local/lib/node_modules/nativescript
>  node preuninstall.js
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.0 (node_modules/nativescript/node_modules/fsevents/node_modules/abbrev):
> npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/abbrev' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.abbrev.DELETE'
> 
> npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sokada/.npm/_logs/2017-08-15T04_50_54_036Z-debug.log

**Comment by dtopuzov** [comment]
Hi @shinokada

Can you please specify `node` and `npm` versions on your machine?

**Comment by shinokada** [comment]
> ➜  ~ npm -v
> 5.3.0
> ➜  ~ node -v
> v8.3.0

> ➜  ~ npm un -g nativescript
> npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules
> npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall access
> npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules'
> npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules'
> npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules\'',
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'access',
> npm ERR!   path: '/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sokada/.npm/_logs/2017-08-15T06_22_53_742Z-debug.log

**Comment by dtopuzov** [comment]
May be this can help:
http://docs.nativescript.org/start/quick-setup#step-2-install-the-nativescript-cli

```
If you’re on macOS and receive an EACCES error, you either need to rerun the previous command with sudo—that is, sudo npm install -g nativescript—or take a moment to [fix your npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) so that you don’t need admin rights to globally install npm packages.
```

**Comment by shinokada** [comment]
Still I get the error.

> ➜  ~ sudo npm install -g nativescript
> Password:
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.0 (node_modules/nativescript/node_modules/fsevents/node_modules/abbrev):
> npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/abbrev' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.abbrev.DELETE'
> 
> npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sokada/.npm/_logs/2017-08-15T07_08_02_695Z-debug.log

**Comment by dtopuzov** [comment]
What about:
```
npm un -g nativescript --ignore-scripts
npm cache clean
npm i -g nativescript
```

**Comment by shinokada** [comment]
Same error when I run, 

    ~ npm un -g nativescript --ignore-scripts

**Comment by dtopuzov** [comment]
To be honest I'm out of ideas at the moment, but I will leave the issue open hoping someone else can help.

The only think that I can suggest is reinstall node.
You can use [this ](https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x)article to completely remove current node and npm and then install it with those lines:
```
brew install node@6
echo 'export PATH="/usr/local/opt/node@6/bin:$PATH"' >> ~/.bash_profile
npm i -g -f npm@4
```

**Comment by shinokada** [comment]
Does this work with node 8?

**Comment by dtopuzov** [comment]
`nativescript@3.1.3` is ok with node8, older version do not support it.

**Comment by rosen-vladimirov** [comment]
Hey @shinokada ,
It looks like there's some problem with the old installation of nativescript on your machine. During uninstall, npm executes `preuninstall` script of the previously installed version. However, with some `npm` versions, the preuninstall step is executed **after** some of the dependencies of the package are removed. So the preuninstall script requires some package, but it is already uninstalled and the preuninstall fails.
In order to skip the preuninstall script (and all scripts) you can use:
```
$ npm install -g nativescript --ignore-scripts
```

In case this does not help, I suggest you to manually remove the nativescript dir: 
```
$ rm -rf /usr/local/lib/node_modules/nativescript/
$ npm install -g nativescript --ignore-scripts
```

Can you give it a try and see if it works for you?

**Comment by shinokada** [comment]
It still give the same error.

> ➜  ~ rm -rf /usr/local/lib/node_modules/nativescript/
> rm: /usr/local/lib/node_modules/nativescript//node_modules/cli-table/node_modules/colors: Permission denied
> rm: /usr/local/lib/node_modules/nativescript//node_modules/cli-table/node_modules/lodash: Permission denied
> rm: /usr/local/lib/node_modules/nativescript//node_modules/cli-table/node_modules: Directory not empty
> rm: /usr/local/lib/node_modules/nativescript//node_modules/cli-table: Directory not empty
> rm: /usr/local/lib/node_modules/nativescript//node_modules: Directory not empty
> rm: /usr/local/lib/node_modules/nativescript/: Directory not empty
> ➜  ~ npm install -g nativescript --ignore-scripts
> npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules
> npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall access
> npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules'
> npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules'
> npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules\'',
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'access',
> npm ERR!   path: '/usr/local/lib/node_modules/nativescript/node_modules/cli-table/node_modules' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sokada/.npm/_logs/2017-08-15T08_28_06_014Z-debug.log

**Comment by rosen-vladimirov** [comment]
@shinokada , the `rm -rf` did not work, it looks like `nativescript` has been installed with root user previous time.
You can try:
```
$ sudo rm -rf /usr/local/lib/node_modules/nativescript/
$ sudo npm install -g nativescript --ignore-scripts
```

**Comment by shinokada** [comment]
Finally it was successful. Thank you for your help.

> ➜  ~ sudo rm -rf /usr/local/lib/node_modules/nativescript/
> Password:
> ➜  ~ sudo npm install -g nativescript --ignore-scripts
> /usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/tns
> /usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/tns
> + nativescript@3.1.3
> added 687 packages in 12.873s
> ➜  ~

**Comment by rosen-vladimirov** [comment]
@shinokada 
I'm glad it worked. I'm closing this issue, feel free to open a new one in case you have other problems or concerns.
Happy coding with NativeScript!

**Comment by shinokada** [comment]
Now when I run `npm list -g --depth=0` I found that I get errors relating to nativescript.

> ➜  ~ npm list -g --depth=0
> /usr/local/lib
> ├── nativescript@3.1.3
> ├── nodemon@1.11.0
> └── npm@5.3.0
> 
> npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/cli-table: Invalid version: "https://github.com/telerik/cli-table/tarball/v0.3.1.2"
> npm ERR! invalid: cli-table /usr/local/lib/node_modules/nativescript/node_modules/cli-table
> npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/tabtab: Invalid version: "https://github.com/Icenium/node-tabtab/tarball/master"
> npm ERR! invalid: tabtab /usr/local/lib/node_modules/nativescript/node_modules/tabtab
> npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/xcode: Invalid version: "https://github.com/NativeScript/node-xcode/archive/1.4.0.tar.gz"
> npm ERR! invalid: xcode /usr/local/lib/node_modules/nativescript/node_modules/xcode
> npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/xmlhttprequest: Invalid version: "https://github.com/telerik/node-XMLHttpRequest/tarball/master"
> npm ERR! invalid: xmlhttprequest /usr/local/lib/node_modules/nativescript/node_modules/xmlhttprequest
> npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/zipstream: Invalid version: "https://github.com/Icenium/node-zipstream/tarball/master"
> npm ERR! invalid: zipstream /usr/local/lib/node_modules/nativescript/node_modules/zipstream
> npm ERR! missing: node-uuid@1.4.7, required by ios-device-lib@0.4.8
> npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/bplist-parser: Invalid version: "https://github.com/telerik/node-bplist-parser/tarball/master"
> npm ERR! invalid: bplist-parser /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/bplist-parser
> npm ERR! missing: cli-table@^0.3.1, required by marked-terminal@2.0.0
