### ISSUE TITLE
`tns debug android` doesn't attach debugger

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#3066]
### Tell us about the problem
`tns debug android` shows warning and doesn't continue on some devices.
`Unable to apply changes on device: 6PQ7N17302003436. Error is: The application org.nativescript.app2728 does not appear to be running on 6PQ7N17302003436 or is not built with debugging enabled..
`
Tested on Huawei P10

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.0-2017-8-15-2

### Please tell us how to recreate the issue in as much detail as possible.
Execute `tns debug android` on a faster device

**Comment by mhmo91** [comment]
I ran into this issue with the same cli version, how i fixed it is basically by resetting the developers options from phone, revoke USB debugging authorizations.

**Comment by rosen-vladimirov** [comment]
Closing as it cannot be reproduced with latest releases.
