### ISSUE TITLE
turn on trace logging in a file by default

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#308]

**Comment by valentinstoychev** [comment]
If we hav ethis by default, can we have a command that will send the report to us directly? Something like "tns sendLog". Or what is the scenario here?

**Comment by ligaz** [comment]
This looks like we do not need anymore due to the fact that we have streamlined the installation and dependencies. Closing for now and we can reopen it in the future in case we need it badly.
