### ISSUE TITLE
NativeScript Windows installer does not ask for install location

### ISSUE THREAD

**Issue by pedjas** [NativeScript/nativescript-cli#3098]
NativeScript Windows installer installs automatically without even asking where to install. It should ask as it requires lot of storage space and users could prefer not to install it all on system disk.

**Comment by dtopuzov** [comment]
Hi @pedjas 

I think this is mostly valid for Android SDK since this is the biggest thing we install.
Is there something else from the installation that you prefer to install on different location?

**Comment by rosen-vladimirov** [comment]
Hey @pedjas ,
The NativeScript Windows Installer is deprecated. Now we recommend using our setup scripts. You can find them [here](https://github.com/NativeScript/setup-scripts).
I've logged a new feature request there: https://github.com/NativeScript/setup-scripts/issues/8 , so you can follow it. I'm closing this one.
