### ISSUE TITLE
# NativeScript Debugger did not start in time # he application xxx.xxx.xxx does not appear to be running on emulator-xxx or is not built with debugging enabled..

### ISSUE THREAD

**Issue by marco-gagliardi** [NativeScript/nativescript-cli#3100]
One day I started to get the following error when trying to run/debug the application, apparently without any valid reason. At the beginning I could run the application both on my device and on the emulator without any problem, then I sometimes got this message (some other times the app started correctly), now it seems there is no way to get rid of it. I tried to update all NS components, but this didn't help. I guess it might be a memory size problem (and maybe a timeout problem) but can't figure out how to solve it (I already checked previous issues and posts but din't find a proper answer)

```
MacBook-Pro:MyAppName marcogagliardi$ tns debug android
Searching for devices...
Starting Android emulator with image Nexus_5X_API_26
Waiting for emulator device initialization...
Executing before-liveSync hook from /Users/marcogagliardi/Projects/Test/MyAppName/hooks/before-liveSync/nativescript-angular-sync.js
Skipping prepare.
Installing...
Successfully installed on device with identifier 'emulator-5554'.
Successfully transferred all files.
Using  /Users/marcogagliardi/Projects/Test/MyAppName/platforms/android/build/outputs/apk/it-debug.apk
device: emulator-5554 debug port: 40000

# NativeScript Debugger did not start in time #
Unable to apply changes on device: emulator-5554. Error is: The application myappname.test.it does not appear to be running on emulator-5554 or is not built with debugging enabled..
^CMacBook-Pro:MyAppName marcogagliardi$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.3           │ 3.1.3          │ Up to date  │
│ tns-core-modules │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘


```

**Comment by pkoleva** [comment]
Hi @marco-gagliardi ,

Could you try running the same command with --log trace and send us the output. Also it will be useful to see `adb logcat` output.

Thanks!

**Comment by marco-gagliardi** [comment]
Hi @pkoleva , I attach the relevant log trace and logcat output parts.
(might it be related to a package name change?)
[logcat.txt](https://github.com/NativeScript/nativescript-cli/files/1269875/logcat.txt)
[log.txt](https://github.com/NativeScript/nativescript-cli/files/1269876/log.txt)

Thank you

**Comment by rosen-vladimirov** [comment]
Hey @marco-gagliardi , 
Thanks for sending the logs. May I ask you to check the id in your `package.json` and the one in `<project dir>/app/App_Resources/Android/app.grade`? They should be the same for the debugger to work.
In case they are not, please set them to the same value and try again.
In case they are already the same, can you try starting the application manually and executing `tns debug android --start` and see if it works?

**Comment by surdu** [comment]
@rosen-vladimirov I have the same issue. In my case I've checked and the id's match.

It works if I use your second command to manually start the debugging.

I would also like to add some other symptom: on iOs, I get the following warning error: `Unable to apply changes on device: xxxxxxxxxxxx
. Error is: Error while waiting for response from NativeScript runtime.`. Also, the application takes a long time to start (stays a lot on the splash screen).

[ios.logtrace.txt](https://github.com/NativeScript/nativescript-cli/files/1394698/ios.logtrace.txt)

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.1           │ 3.2.1          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by surdu** [comment]
In my case the problem went away as soon as I uninstalled NativeScript Sidekick (at least on Android, I don't have an iOS device to test at the moment)

**Comment by surdu** [comment]
Unfortunately, that was just a coincidence. It worked for 3 - 4 more times, and now I have again the problem.

**Comment by bozhidarc** [comment]
I have a similar problem but with iOS. I think I tried everything, removing platform, node_modules, hooks, updating xCode to 9.2. 
I'm out of options. Is there any solution to the problem?

```
Searching for devices...
Your application will be deployed only on the device specified by the provided index or identifier.
Executing before-liveSync hook from [...]/hooks/before-liveSync/nativescript-angular-sync.js
Skipping prepare.
Installing...
Successfully installed on device with identifier '0b6...'.
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Starting...
Successfully run application org.test.myapp on device with ID 0b6....
Successfully started on device with identifier '0b6...'.
Starting...
Successfully run application org.test.myapp on device with ID 0b6....
Successfully started on device with identifier '0b6...'.
Unable to apply changes on device: 0b6.... Error is: Error while waiting for response from NativeScript runtime..
Executing after-watch hook from [...]/hooks/after-watch/nativescript-dev-sass.js
Executing after-watch hook from [...]/hooks/after-watch/nativescript-dev-typescript.js
```


```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-android      │                 │ 3.4.0          │ Not installed │
│ tns-ios          │ 3.4.0           │ 3.4.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

```

**Comment by nmongiya** [comment]
I am facing the same issue that app stays on splash screen forever. I have even tried with the sample-groceries and Hello world app as well.
`roject successfully built.
Installing...
Successfully installed on device with identifier 'a2616888534152302f549cc20b23e545d83676fb'.
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Starting...
Starting...
Unable to apply changes on device: XXX.XXX.XXX. Error is: Error while waiting for response from NativeScript runtime..`
Here is my package
```
Package                            Current  Wanted  Latest 
@angular/animations                  5.1.3   5.1.3   5.2.1
@angular/common                      5.1.3   5.1.3   5.2.1
@angular/compiler                    5.1.3   5.1.3   5.2.1
@angular/core                        5.1.3   5.1.3   5.2.1
@angular/forms                       5.1.3   5.1.3   5.2.1
@angular/http                        5.1.3   5.1.3   5.2.1
@angular/platform-browser            5.1.3   5.1.3   5.2.1
@angular/platform-browser-dynamic    5.1.3   5.1.3   5.2.1
@angular/router                      5.1.3   5.1.3   5.2.1
nativescript-angular                 5.1.0   5.1.0   5.2.0
typescript                           2.4.2   2.4.2   2.6.2
```
**ios version is 8.2**

**Comment by neil-119** [comment]
Did you guys figure out a solution to this? If I run it manually with a `-timeout` parameter, I can get it to work. I use VS Code, so I'll need to figure out a way to add this parameter to the launch config.

**Comment by surdu** [comment]
In our case the `--syncAllFiles`to stay a lot of time on the splash screen, which was causing the timeout.

@neil-119 's solution of setting the `--timeout` flag sounds like the fix for this issue (which the more I think about it, was not an issue but a feature, at least in our case)

**Comment by miroslavaivanova** [comment]
Closing the issue. It is not reproducible with CLI next. Fell free to reopen it and/or open an another issue in case you have some problems.
