### ISSUE TITLE
Command tns run android does not launch app on AVD

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#3111]
### Tell us about the problem

**This problem is only occurring on a specific app**, specifically this one: https://github.com/tjvantoll/nadidas. I do not have this problem with the default {N} template. I’m only flagging this now because this is the app we plan on using as part of the {N} DevDay keynote demo.

If I use `tns run android` the CLI is able to successfully build this app; it successfully installs the `.apk` file; but it no longer launches the app on my AVD. I have to manually go into the apps list and launch the app.

This same behavior occurs during LiveSync. The watcher detects my change, but the CLI is unable to relaunch my app to show that change.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.0
- Cross-platform modules: 3.1.0
- Runtime(s): I’ve hit the same problem with both 3.1.1 and 3.2.0
- Plugin(s): See https://github.com/tjvantoll/nadidas/blob/master/package.json

### Please tell us how to recreate the issue in as much detail as possible.

For me it’s as simple as cloning the repo and running `tns run android`. It’s quite possible that it’s something specific about my machine that’s causing the problem.

Here’s a full log of `tns run android --log trace`: https://gist.github.com/tjvantoll/b550885d0fc66edb30b4bed482309671

Any help would be greatly appreciated.

**Comment by tjvantoll** [comment]
Confirmed that the same behavior occurs for @jlooper. So at least it’s not just me 😄

**Comment by rosen-vladimirov** [comment]
Hey @tjvantoll ,
It looks like you've faced [this issue](https://github.com/NativeScript/nativescript-cli/issues/2825). In your `app.gradle` the application identifier is [com.ladeezfirstmedia.giftler](https://github.com/tjvantoll/nadidas/blob/master/app/App_Resources/Android/app.gradle#L11), while in `package.json` it is [org.nativescript.myKinveyApp](https://github.com/tjvantoll/nadidas/blob/master/package.json#L5).

CLI uses the id from package.json when trying to start the application, but the app is installed with the id defined in `app.gradle`. In order to fix this behavior you should set the id in package.json to be the same as the one in app.gradle.

**Comment by tjvantoll** [comment]
Thanks so much @rosen-vladimirov! That indeed solved our problem.

I suppose you could consider this issue a vote for us to implement something like https://github.com/NativeScript/nativescript-cli/issues/2367, or just to remove the app id from the root `package.json` entirely. This isn’t the first time I’ve mixed these app ids up.

Closing this issue. Thanks again!

**Comment by anandbaskaran** [comment]
I have the same issue. I don't have any special plugin/packages.  But I could not see anything on my emulator. The IDs are the same in both app.gradle and package.json. Am I missing something?

Note: `tns preview` works well.

Please find the attached log

`tns run android --log trace`:
[emulator.txt](https://github.com/NativeScript/nativescript-cli/files/3305332/emulator.txt)

**Comment by mauriciogracia** [comment]
Using the CLI command "ns create APP_NAME" created a project that does not run in a AVD emulator.

To solve that I set the id value in the package.json and app.graddle help me solve it 

In the **package.json** 
```
  "nativescript": {
    "id": "com.yournamespace.appname"
  }
```

And in **app.gradle**
```
  defaultConfig {
    minSdkVersion 17
    generatedDensities = []
    applicationId = "com.yournamespace.appname"
  }
```

For more details about application Ids for different platforms  - https://v6.docs.nativescript.org/tooling/changing-appid
