### ISSUE TITLE
Console.log has no output on terminal

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3118]
_From @bigradish on September 13, 2017 2:41_

When I follow the steps in the "Debugging apps" section of your tutorial https://docs.nativescript.org/tutorial/chapter-1 , both console.log and console.dir have no output on the terminal.

More info:
1. development machine: Windows 10 64bit
2. target platform: android
3. cli version: 3.2.0
4. Cross-platform modules: 3.1.1
5. Runtime: 3.2.0
6. Plugin: no plugin used, just the HelloWorld project in the tutorial.

Thank you.

_Copied from original issue: NativeScript/NativeScript#4835_

**Comment by christian-kolb** [comment]
I have the same issue on the same CLI and runtime version but on Mac and with iOS as target platform.

**Comment by christian-kolb** [comment]
If I run the app with `tns debug ios --watch` I get console output in the Nativescript Inspector. But only there and this seems to be the only way to get to the logging. The problem is for all logging information including errors.

**Comment by christian-kolb** [comment]
@bigradish and @NickIliev Did one of you try to use an older version of the CLI yet? I first thought it might be related to the XCode update and the new iOS 11, but as you're using Android on Windows those two things don't seem to be related.

**Comment by glen-stephens** [comment]
I just upgraded to XCode 9 and iOS 11 and my console.log quit outputting to the terminal.  Was working fine previous to updating XCode. Have not been able to get it working again. ` tns debug ios --watch` does output to the nativescript console, but not the terminal.  Any help or suggestions would be awesome!

**Comment by thegermin8er** [comment]
Same as glen-stephens

**Comment by etabakov** [comment]
Hey guys,
Regarding the problem with the missing logs with XCode9 / iOS 11, this is caused by changes in the latest iOS and how event logging is handled. We are working on resolution and it should be available in the next minor release.

Regarding the problem with Windows and Android - this is not related to the above issue. We will take a look and let you know.

**Comment by NathanaelA** [comment]
For those who need logging back; here is the way I'm doing it now... 
fluentreports.com/blog/?p=545

**Comment by glen-stephens** [comment]
@etabakov If it helps, console.log does work to the terminal when running on an actual device, just not from the simulator.

**Comment by KristianDD** [comment]
Here is a separate issue for iOS11 Simulator and Xcode9: https://github.com/NativeScript/nativescript-cli/issues/3141. Lets continue the discussion there.

**Comment by bigradish** [comment]
Why this issue has not received any process till now?

**Comment by Natalia-Hristova** [comment]
Can confirm that `console.log()` and `console.dir()` work on **mac** `Xcode 9.2` simulator and device and on **Windows** - emulator and device.
using current `rc` versions of nativescript and runtimes. All related fixes will be available in next official release.

You can test it out too in `rc`  --> `npm i -g nativescript@rc` `tns platform add ios@rc` and please share if you still encounter the same problems.

**Comment by dexter2019** [comment]
I am still facing the same issue? ios12 and xcode 9.4

**Comment by socalrunner** [comment]
Same issue here.  ios12 and xcode 9.4.  `tns run ios` stops at `refreshing application`, won't refresh the application and won't log to the console.
