### ISSUE TITLE
Fail to upgrade to nativescript@3.2.1

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#3126]
```
vchimev:git chimev$ node -v
v8.4.0
vchimev:git chimev$ npm -v
5.3.0
vchimev:git chimev$ npm i -g nativescript
...
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/safe-buffer' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
...
```

A complete log of this run can be found [here](https://gist.github.com/vchimev/921341a45d93b85244baaa40f954a44b).

**Comment by NathanaelA** [comment]
Try downgrading to 5.04 of NPM  (5.3.2 _might_ fix it too).    But NPM 5 > 5.04 is a bit buggy.

**Comment by dtopuzov** [comment]
@vchimev Can you reproduce the issue with latest releases of npm5?

**Comment by rosen-vladimirov** [comment]
Closing in favor of https://github.com/NativeScript/nativescript-cli/issues/3067
