### ISSUE TITLE
tns Issue

### ISSUE THREAD

**Issue by ZMW9** [NativeScript/nativescript-cli#3127]
after run npm i -g nativescript in MAC

I get EACCESS :permission denied,mkdir'/Users/dev/.local/share/.nativescript-cli'

After clean npm and install nativescript ,

I also get 
npm ERR! path /Users/dev/.npm-global/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/dev/.npm-global/lib//nativescript/node_modules/fsevents/node_modules/ansi-regex' -> '/Users/dev/.npm-global/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:s

**Comment by NickIliev** [comment]
@ZMW9 can you try to reinstall NativeScript with [this solution](https://discourse.nativescript.org/t/i-cant-install-nativescript-on-my-mac/2112/3?u=nickiliev)

**Comment by ZMW9** [comment]
Thank you Sir @NickIliev . After update npm , I can run nativescript tns.

**Comment by jsfgreen** [comment]
@NickIliev in my case, node/npm was broken.  I had to remove `rm -rf /usr/local/lib/node_modules` and uninstall/re-install node and then re-install all of my global npm packages including nativescript.
