### ISSUE TITLE
Emulator API 26 freezes when you try to run app

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#3137]
### Tell us about the problem
Close emulators and run 'tns run android'. The emulator freezes.

### Which platform(s) does your issue occur on?
Android - API 26

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0-2017-09-20

### Please tell us how to recreate the issue in as much detail as possible.
`Result when throw error is false:
{ stdout: '        android.intent.action.MAIN:\n          70f1c1f org.nativescript.MyApp1/com.tns.NativeScriptActivity filter b3fdbdf\n            Action: "android.intent.action.MAIN"\n            Category: "android.intent.category.LAUNCHER"\n--\n       Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity }\n       frontOfTask=true task=TaskRecord{c4ef760 #4 I=com.google.android.apps.nexuslauncher/.NexusLauncherActivity U=0 StackId=0 sz=1}\n--\n       Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity }\n       frontOfTask=true task=TaskRecord{c4ef760 #4 I=com.google.android.apps.nexuslauncher/.NexusLauncherActivity U=0 StackId=0 sz=1}\n--\n       Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity }\n       frontOfTask=true task=TaskRecord{c4ef760 #4 I=com.google.android.apps.nexuslauncher/.NexusLauncherActivity U=0 StackId=0 sz=1}\n--\n      mIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity }\n      mLaunchSingleTop=false mLaunchSingleInstance=false mLaunchSingleTask=true mLaunchFlags=0x10000100 mDoResume=true mAddingToTask=false\n--\n        intent={act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity}\n        realActivity=com.google.android.apps.nexuslauncher/.NexusLauncherActivity\n--\n            Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity }\n            frontOfTask=true task=TaskRecord{c4ef760 #4 I=com.google.android.apps.nexuslauncher/.NexusLauncherActivity U=0 StackId=0 sz=1}\n--\n     Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity }\n     frontOfTask=true task=TaskRecord{7527017 #5 I=com.google.android.apps.nexuslauncher/.NexusLauncherActivity U=0 StackId=0 sz=1}\n',
  stderr: '',
  exitCode: 0 }
`

![screen shot 2017-09-28 at 9 57 27 am](https://user-images.githubusercontent.com/4198315/30953198-7af1b36a-a433-11e7-95ea-e867777ab954.png)

**Comment by dtopuzov** [comment]
Not sure if it was fixed on Android side or on {N} side, but I can not reproduce the issue with latest version of Android SDK/Tools/Emulators/HAXM and {N}.
