### ISSUE TITLE
tns run ios shows "no reachable hosts" after running unit tests

### ISSUE THREAD

**Issue by jschwartz73** [NativeScript/nativescript-cli#3146]
After running unit tests via 
- tns test ios

a call to 

- tns run ios

displays an app with a big image of "N" and a label that says "no reachable hosts"

My expectation is that the app would run (not the unit tests)

tns info
nativescript     │ 3.2.1           │ 3.2.1          │ Up to date    │
tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date    │
tns-android      │                 │ 3.2.0          │ Not installed │
tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date    │

Steps to reproduce:

1. tns create test-app
2. cd test-app/
3. tns run ios
4. tns test init  # Choose Jasmine
5. tns test ios
6. tns run ios

Any help would be greatly appreciated.

**Comment by jschwartz73** [comment]
<img width="376" alt="screen shot 2017-10-04 at 6 53 36 pm" src="https://user-images.githubusercontent.com/935550/31203507-6b3735ba-a935-11e7-9c92-4d475e5b756d.png">

**Comment by jschwartz73** [comment]
I have now reproduced this on two computers.

**Comment by jschwartz73** [comment]
I tried the workaround and it does **not** solve the issue.

**Comment by wfwheele** [comment]
@jschwartz73 I was experiencing the same thing, it looks like running the tests might have changed `app/package.json` which I believe is how `tns run ios` figures out how to start the application.  For me I could see via `git status` that it was modified and just did a `git checkout -- app/package.json`

Basically you need to make that file looks something like this 

```
{
  "android": {
    "v8Flags": "--expose_gc"
  },
  "main": "main.js",
  "name": "tns-template-hello-world-ng",
  "version": "3.1.2"
}
```

In your case I bet main points to the unit test runner and not the app itself. 

Could anyone give some info on when that file gets changed and whether or not it should or shouldn't be in version control?

**Comment by rosen-vladimirov** [comment]
Hey all,
`tns test <platform>` command *must* update the package.json inside `<platforms>` dir only - that's how the tests are run. However, it looks like there is some issue with this and it updates the entry point in your `app/package.json`. This is definitely not intended. Can all of you, who hit the issue, share the following information:
* npm version (output of `npm -v`): 
* Node.js version (output of `node -v`):
* Xcode version (output of `xcodebuild -version`):
* Do you reproduce the issue with `iOS` or `Android`: 
* Do you have local plugins, do you use `npm link` in your development workflow?

Meanwhile, I've reproduced and confirmed that the following workflow does not work:
* tns run ios
* tns test ios
* tns run ios - at this point CLI prints `Skipping prepare` and does not update `package.json` in `platforms` dir, so the application running on device is the one with tests. CLI should not skip prepare here.
The workaround for this issue is to execute `touch app/package.json` and run `tns run ios` again. This will force CLI to prepare the application.

**Comment by jschwartz73** [comment]
npm -v: 5.4.2
node -v: v6.11.3
xcodebuild -version: Xcode 9.0, Build version 9A235

I can reproduce the problem every time using these steps:

1. tns create test-app
2. cd test-app/
3. tns run ios
4. tns test init # Choose Jasmine
5. tns test ios
6. tns run ios

I'll film a short screencast to demonstrate

**Comment by jschwartz73** [comment]
[https://s3.amazonaws.com/schwartech/nativescript-cli-3146.mov.zip](https://s3.amazonaws.com/schwartech/nativescript-cli-3146.mov.zip)

**Comment by khoroshulia** [comment]
@rosen-vladimirov Hi. I got the same issue reproduced on Android. Steps are the same as for iOS

npm -v: 5.3.0
node -v: v8.6.0
xcodebuild -version: Xcode 9.1, Build version 9B55

**Comment by henriqueadonai** [comment]
NPM -V = 5.5.1
Node -v = v8.9.1
Using Windows/Visual studio code
ANDROID

**Comment by jschwartz73** [comment]
I'm now running:
npm -v: 5.4.2
node -v: v6.11.3
xcodebuild -version: Xcode 9.1, Build version 9B55
iOS only for the time being

**Comment by Majed93** [comment]
I'm getting this too... Only after running tests i can't run the app again on emulator or device. After i do ``` tns update ``` however it seems to work. Is this expected??

**Comment by outsideMyBox** [comment]
Same thing with this configuration:
npm - v : 6.2.0
node -v : v6.10.2
xcodebuild -version : Xcode 9.4.1
iOS

**Comment by kamok** [comment]
npm: 5.6.0
node: v8.11.3
xcodebuild -version: Xcode 9.4.1; Build version 9F2000
iOS

It seems like the `tns run ios` is opening the app on the Emulator that runs the spec.

I just did `tns update` and it seemed to work because the entire `ios` folder got rebuilt. Perhaps `tns prepare ios` will work? 

Somehow it has to rebuild, I'm not too acquainted with the cli, but ideally `tns run ios --force-build` or something should work. Someone explore the docs?

**Comment by kamok** [comment]
This is still reproducible, and the `touch` on the package.json doesn't work for me. I need to manually make changes to it, then revert it back it how it was. Then `tns run ios` will work.

**Comment by 18clans** [comment]
Same thing with this configuration:
npm - v : 6.2.0
node -v : v8.11.3
xcodebuild -version : Xcode 9.4.1
iOS and Android

**Comment by kamok** [comment]
I simply run this now after `tns test ios` and if I'm gonna be working with `tns run ios` again:

`tns platform remove ios && tns platform add ios && tns run ios`

Added an alias to my bash and have been using it with 100% success rate. Quite annoying, but works.

**Comment by ajoslin103** [comment]
- xcodebuild -version
Xcode 10.1
Build version 10B61
 - node --version
v10.13.0
 - npm --version
6.4.1

IOS

**Comment by ajoslin103** [comment]
I execute this command after testing:

sed -i.bak 's|./tns_modules/nativescript-unit-test-runner/||' platforms/ios/Project1NativeScript/app/package.json

it resets the package.json file and is idempotent - I can't figure out where in the cli this would go...

**Comment by Yermo** [comment]
I am seeing this as well when building for Android using the sample Angular project however if after running 

```
tns test android
```
I modify any file in the project, then

```
tns run android
```
works correctly. 

If I run the two commands consecutively without making any edits, I get the "no reachable hosts" error.

**Comment by Fatme** [comment]
@Yermo ,

You need to add the following code to your `App_Resources/Android/AndroidManifest.xml`

```
<application
         android:usesCleartextTraffic=“true”
```

**Comment by Yermo** [comment]
@Fatme I am working with the sample app created using
```
tns create ns-test-app --ng
cd ns-test-app
npm install
tns test init
```
under Ubuntu.

There is no AndroidManifest.xml file under App_Resources/Android but there is one under App_Resources/Android/src/main/AndroidManifest.xml

I added the android:usesCleartextTraffic="true" line to that file but it has no effect. I still get "no reachable hosts" attempting to run the app after running tests.

**Comment by arimus** [comment]
Getting this same error first time using nativescript. Btw, some of the docs explicitly have you run `tns test ios` as your are setting up and testing that you are properly configured.

This seems like a terrible blocker for folks that are just getting started with NativeScript and a great annoyance to existing users. Seems like it should be somewhat high on the list of bug fixes to tackle and it's been open for over a year. I'd imagine that there are a number of folks that have given up before really ever getting started.

That said, thanks for all the tooling and nice job on most of the rest of the on-ramp process. This was just a minor hiccup, albeit a rather nasty one, along the way.

**Comment by rosen-vladimirov** [comment]
With current `rc` version, this should not happen anymore. Steps to reproduce the old behavior:
```
1. `tns create app1 --js`
2. `cd app1`
3. `tns test init`
4. `tns test android --no-bundle`
5. `tns run android --no-bundle` - this command should show the real application, but instead it will show the unit test page.
```
With new workflow you skip the `--no-bundle` flag and everything should work.
