### ISSUE TITLE
why java version is got from stderr?

### ISSUE THREAD

**Issue by intellild** [NativeScript/nativescript-cli#3148]
cli 3.2.1

I found this line of code
> this.javaCompilerVerCache = output ? /javac (.*)/i.exec(output.stderr)[1] : null;

while stderr is empty and stdout is "Java 9\r\n", I tried changing "stderr" to "stdout" and it works with correct java version. Then in function 'validateJavacVersion', the 'installedJavaVersion' is receives a correct number  '9'.

But this line of code return nothing

> const matchingVersion = (installedJavaVersion || "").match(AndroidToolsInfo.VERSION_REGEX);

and endup with

> Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.

**Comment by etabakov** [comment]
Hey @hzjzx. Regarding your first comment about using `stdout` instead of `stderr` - looks like a valid observation to me. Feel free to submit a PR and the team will review it.

Regarding the second problem - I will check and let you know, what might be the reason.

**Comment by dtopuzov** [comment]
Closing, explanation posted in related PR https://github.com/telerik/mobile-cli-lib/pull/1017
