### ISSUE TITLE
Can`t run projects: Execution failed for task ':mergeF0F1DebugResources'

### ISSUE THREAD

**Issue by Thenilko** [NativeScript/nativescript-cli#3157]
My tns version is : 3.2.1
Windows 10 Enterprise.

I am trying with this project -> https://github.com/shripalsoni04/nativescript-webview-interface-demo

I am always getting this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0F1DebugResources'.
> D:\Work\NativeScript Projects\nativescript-webview-interface-demo-master\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\26.0.0-alpha1\res\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: Error: File path too long on Windows, keep below 240 characters : D:\Work\NativeScript Projects\nativescript-webview-interface-demo-master\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\26.0.0-alpha1\res\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

**Comment by NickIliev** [comment]
@Thenilko this error might occur on Windows if your folder is deep in the file system and because Windows have a limitation of maximum file path of 254 symbols the build process might not be able to create longer paths.
As a workaround try moving your project in the root directory of your Windows partition and rebuild again. In your case try moving the project to `D:`  (instead of `D:\Work\NativeScript Projects\`) and perhaps renaming the project folder from `nativescript-webview-interface-demo-master` to something shorter like `demo`.

Let me know if this has resolved your issue.

**Comment by Thenilko** [comment]
Hey @NickIliev , thanks for the quick response.

Now I get this error in console and emulator as well: 


System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.webviewinterfacedemo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err: Error: Building UI from XML. @file:///app/main-page.xml:5:13
System.err:  > Module 'ui/web-view' not found for element 'WebView'.
System.err:    > java.lang.NoSuchFieldError: no "I" field "ERROR_UNSAFE_RESOURCE" in class "Landroid/webkit/WebViewClient;" or its superclasses
System.err:       com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:895)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:879)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:871)
System.err:     com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
System.err:     android.app.Activity.performCreate(Activity.java:6237)
System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
System.err:     android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:148)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: File: "/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 175, column: 20
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 175, column: 21
System.err:     Frame: function:'', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 147, column: 13
System.err:     Frame: function:'EasySAXParser.parse', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
System.err:     Frame: function:'XmlParser.parse', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 194, column: 22
System.err:     Frame: function:'XmlStringParser.parse', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 181, column: 27
System.err:     Frame: function:'parseInternal', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 48, column: 11
System.err:     Frame: function:'loadInternal', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 133, column: 27
System.err:     Frame: function:'load', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
System.err:     Frame: function:'pageFromBuilder', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 111, column: 27
System.err:     Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 89, column: 20
System.err:     Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 165, column: 20
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 690, column: 19
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 13, column: 25
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err: Error: Building UI from XML. @file:///app/main-page.xml:5:13
System.err:  > Module 'ui/web-view' not found for element 'WebView'.
System.err:    > java.lang.NoSuchFieldError: no "I" field "ERROR_UNSAFE_RESOURCE" in class "Landroid/webkit/WebViewClient;" or its superclasses
System.err:       com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:895)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:879)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:871)
System.err:     com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
System.err:     android.app.Activity.performCreate(Activity.java:6237)
System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
System.err:     android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:148)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: File: "/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 175, column: 20
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 175, column: 21
System.err:     Frame: function:'', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 147, column: 13
System.err:     Frame: function:'EasySAXParser.parse', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
System.err:     Frame: function:'XmlParser.parse', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 194, column: 22
System.err:     Frame: function:'XmlStringParser.parse', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 181, column: 27
System.err:     Frame: function:'parseInternal', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 48, column: 11
System.err:     Frame: function:'loadInternal', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 133, column: 27
System.err:     Frame: function:'load', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
System.err:     Frame: function:'pageFromBuilder', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 111, column: 27
System.err:     Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 89, column: 20
System.err:     Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 165, column: 20
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 690, column: 19
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.webviewinterfacedemo/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 13, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:895)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:879)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:871)
System.err:     at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
System.err:     at android.app.Activity.performCreate(Activity.java:6237)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
System.err:     ... 9 more
3:26:32 PM - Compilation complete. Watching for file changes.

ActivityManager: Process org.nativescript.webviewinterfacedemo (pid 4674) has died

**Comment by Pip3r4o** [comment]
@Thenilko `ERROR_UNSAFE_RESOURCE` is only available on API 26, so trying to access it on API's under that will cause the crash that you've experienced. Consider adding a check in your code if your device is of the proper version before accessing the constant.

**Comment by Thenilko** [comment]
After execution of this command  tns run/build android --compileSdk 25, I have the same error.

**Comment by Pip3r4o** [comment]
@Thenilko I think executing `tns run` without any changes to the `app/App_Resources` directory will not trigger a build where the lower android sdk will be used, so you should instead try `tns build android --compileSdk 25` which will force a build, with most build artifacts cached. Follow that by `tns run android --compileSdk 25`.

Thanks!

**Comment by Thenilko** [comment]
Yes man, that`s it. Thanks. I have the same issue with all my projects. So i am gonna test them now.

**Comment by Pip3r4o** [comment]
@Thenilko thanks for reporting back. I'll look into the original issue, and let you know when we've addressed it.

**Comment by Pip3r4o** [comment]
@Thenilko well, I was wondering why the problem appeared familiar, and I thought we had fixed it previously, only for it to pop up again. I peeked at the package.json, and it appears that the android runtime is a rather old version, almost a year old now.

If you remove the platform, and add the latest available (3.2), you should not have to manually pass `--compileSdk`, as the underlying problem was fixed in the platform. 

```
tns platform remove android
tns platform add android@3.2
```

Since the project is a bit old too, you will have to include an `app.gradle` in the `app/App_Resources/Android` directory too. Like this one - https://github.com/NativeScript/template-hello-world-ts/blob/master/App_Resources/Android/app.gradle . Better yet, create your own project and only copy the xml and .js files which you may use.

**Comment by Thenilko** [comment]
Could you please help me with this project: https://github.com/cfjedimaster/NativeScriptDemos/tree/master/rssTest2

When i try it to run it I`m getting this error: 

`D:\rssTest2>tns run android
Searching for devices...
Preparing project...
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Gradle build...

 :config phase:  createDefaultIncludeFiles

 :config phase:  addAarDependencies
        +adding dependency: D:\rssTest2\platforms\android\libs\aar\widgets-release.aar
Project successfully prepared (Android)
Building project...
Gradle build...

 :config phase:  createDefaultIncludeFiles
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for D:\rssTest2\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: D:\rssTest2\platforms\android\src\tns-core-modules-widgets -> D:\rssTest2\platforms\android\src\F0

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in D:\rssTest2\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: D:\rssTest2\platforms\android\configurations\include.gradle
        +applying configuration from: D:\rssTest2\platforms\android\configurations\tns-core-modules-widgets\include.gradle

:config phase:  addAarDependencies
        +adding dependency: D:\rssTest2\platforms\android\libs\aar\widgets-release.aar
Running full build
finished with reading lines with js files
Exception in thread "main" java.io.FileNotFoundException: D:\rssTest2\platforms\android\build-tools\android-static-binding-generator\bindings.txt (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.nativescript.staticbindinggenerator.Generator.getRows(Generator.java:132)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:75)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:54)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\rssTest2\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 277

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_131\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.`

**Comment by Pip3r4o** [comment]
@Thenilko The project appears to be outdated, but the problem seems to stem from the fact that your files have not been parsed properly. Your best bet is to create your own project using the tns cli:

`tns create rssFeed`

And copy-pasting the relevant pieces in the demo application. Mind you, some APIs might have changed, considering how outdated the project, and the plugin it uses are.

Please use the forums to get assistance on non-issue related questions. https://discourse.nativescript.org/
