### ISSUE TITLE
javac doesn't work

### ISSUE THREAD

**Issue by TecladistaProd** [NativeScript/nativescript-cli#3165]
i have a problem, i installed nativescript, jdk and android sdk, set java_home and android_home: _ANDROID_HOME = C:\Android\sdk, JAVA_HOME = C:\Program Files\Java\jdk1.8.0_144, and in PATH = C:\Program Files\Java\jdk1.8.0_144\bin; C:\Android\sdk\tools; C:\Android\sdk\platform-tools;_
But when i use the command **tns run build** and appear

>  Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.

**Comment by NickIliev** [comment]
@TecladistaProd  are you by chance using Java 9!? Keep in mind that at this very moment the support for Java is under development and [the required version is JDK 8](https://docs.nativescript.org/start/ns-setup-win#system-requirements)

**Comment by TecladistaProd** [comment]
yes, it's correct, but not worked javac. but I uninstalled and installed again, different of the first time, i this time i used choco and not the installer, and now it's working.
