### ISSUE TITLE
Many errors related to android when doing "tns run ios"

### ISSUE THREAD

**Issue by anaszgh** [NativeScript/nativescript-cli#3172]
Platform: MACOS Sierra
TNS Version 3.2.1

Package.json

{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.Sa7bah",
		"tns-ios": {
			"version": "3.2.0"
		},
		"tns-android": {
			"version": "3.2.0"
		}
	},
	"dependencies": {
		"@angular/animations": "~4.2.0",
		"@angular/common": "~4.2.0",
		"@angular/compiler": "~4.2.0",
		"@angular/core": "~4.2.0",
		"@angular/forms": "~4.2.0",
		"@angular/http": "~4.2.0",
		"@angular/platform-browser": "~4.2.0",
		"@angular/router": "~4.2.0",
		"angular2-jwt": "^0.2.3",
		"jssha": "^2.2.0",
		"nativescript-angular": "^4.4.1",
		"nativescript-facebook": "^2.0.1",
		"nativescript-ngx-slides": "^0.4.2",
		"nativescript-pro-ui": "^3.1.4",
		"nativescript-secure-storage": "^2.2.1",
		"nativescript-theme-core": "~1.0.2",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.4.2",
		"tns-core-modules": "~3.1.0",
		"zone.js": "~0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "6.4.5",
		"babel-types": "6.4.5",
		"babylon": "6.4.5",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.5.0",
		"typescript": "~2.4.2"
	}
}

i'm working on multiple PCs, one has windows 10 (Testing on Android) . the other MACOS (Testing IOS), suddenly on the MACOS when i run the tns run ios it results with many errors related to android, while it is still working fine on the windows machine.

Some of the errors returned

app/tns_modules/nativescript-pro-ui/android.d.ts(1449,104): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1450,100): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1451,100): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1452,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1453,106): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1453,126): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1454,96): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1455,96): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1456,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1457,92): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1458,99): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1459,103): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1460,105): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1461,106): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1462,98): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1463,94): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1464,99): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1465,97): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1466,100): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1467,103): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1468,105): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1469,94): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1470,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1471,92): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1472,105): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1475,94): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1476,92): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1477,101): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1478,106): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1478,133): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1479,108): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1480,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1481,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1482,104): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1483,97): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1484,103): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1485,97): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1486,104): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1487,99): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1488,104): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1489,100): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1490,100): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1491,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1492,106): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1492,126): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1493,96): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1494,96): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1495,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1496,92): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1497,99): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1498,103): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1499,105): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1500,106): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1501,98): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1502,94): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1503,99): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1504,97): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1505,100): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1506,103): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1507,105): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1508,94): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1509,102): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1510,92): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1511,105): error TS2694: Namespace 'android' has no exported member 'view'.
app/tns_modules/nativescript-pro-ui/android.d.ts(1518,96): error TS2694: Namespace 'android' has no exported member 'view'.

Unable to apply changes on device: 4C873811-2681-440A-882A-8D8AA7D2123C. Error is: TypeScript compiler failed with exit code 1.
Executing after-watch hook from /Users/anasal-zghoul/Dropbox/Work/jawa2ez_App_All/tnsVersion/Sa7bah/hooks/after-watch/nativescript-dev-typescript.js

**Comment by NickIliev** [comment]
@anaszgh your issue might be related to [this](https://github.com/NativeScript/nativescript-cli/issues/3016). Please check if in your 'app' folder there is a folder 'tns_modules' and delete it, then rebuild the application.

**Comment by cpvbruno** [comment]
@NickIliev Thank you very much
