### ISSUE TITLE
Webpack - where to register modules (in ng version)?

### ISSUE THREAD

**Issue by Joey33** [NativeScript/nativescript-cli#3175]
Hi, I’m a NS newbie moving from Ionic.

So far I’ve been doing well with transferring my Angular2 logic into NS ecosystem.
However now I’m stuck with Webpack. I’ve installed webpack and all dependencies and the next step in the docs is to register pages as dynamic modules with webpack eg:

> global.registerModule(“main-page”, () => require("./main-page"));

But it doesn’t say **where** to add these registrations.

Latar the docs say that for **non-ng** versions you should create bundle-config.js|ts file in app folder. But **my version is ng**, so I understand creating the file manually is not my case…

Any tip?

**Comment by NickIliev** [comment]
@Joey33 you do not need to register the HTML files in an Angular based project - the bundle-config file is needed for a non-Angular project to register the "combos" of XML and code-behind files. which is handled by design when using WebPack with an Angular project.

**Comment by Joey33** [comment]
thx Nick, I'll give it a try; 
ps. probably the docs could improve on clarity at this point since it talks about registering before the non-ng section. That's why I inferred you must register modules in ng apps too but in a different way. Thx again!
