### ISSUE TITLE
dismiss keyboard ios

### ISSUE THREAD

**Issue by behi1ty** [NativeScript/nativescript-cli#3185]
Hello
How can I get a keyboard and closure in the text field?
No keyboard buttons like Done and so on

**Comment by NickIliev** [comment]
@behi1ty this repository is for logging issues, bugs and feature requests related to NativeScript CLI.
For a how-to related question about the usage of NativeScript modules please use one of the community channels like [discourse.nativescript.org](https://discourse.nativescript.org/) or [SO](https://stackoverflow.com/questions/tagged/nativescript).
