### ISSUE TITLE
console.dir works the same as log 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3186]
_From @Andy-ZYA on October 28, 2017 8:48_

I am following the [official tutorial](https://docs.nativescript.org/angular/tutorial/ng-chapter-1) and after I change console.log to console.dir, the terminal shows the same thing.

`CONSOLE LOG file:///app/app.component.js:6:20: [object Object]
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:2957:20: Angu`

How should I fix this problem?

_Copied from original issue: NativeScript/NativeScript#4997_

**Comment by NickIliev** [comment]
Hey @Andy-ZYA thank you for reporting this issue - confirming this one as a bug.

Steps to reproduce - use [this test app](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-cli/issue_3186) and see how console.dir works[ at this line](https://github.com/NickIliev/NS-Issues/blob/master/nativescript-cli/issue_3186/app/item/items.component.ts#L21)

**Comment by blueberrynotblue** [comment]
@NickIliev btw,is tns 3.3.0 not available now?

**Comment by NickIliev** [comment]
@blueberrynotblue it is available on NPM.
```
npm i -g nativescript@latest
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#5064
