### ISSUE TITLE
NativeScript cli error when tns run ios or any command related to IOS platform

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#3189]
_From @fawzywassel on October 31, 2017 18:6_

cli error =>
NativeScript can only run in Xcode version 6.0 or greater

_Copied from original issue: NativeScript/NativeScript#5015_

**Comment by tsonevn** [comment]
_From @NathanaelA on October 31, 2017 19:17_

@fawzywassel -- Do you have XCode 8 or 9 installed?   
See: https://docs.nativescript.org/start/quick-setup

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 19:33_

yes i have XCode 9 , and i follow this steps and all is installed perfect

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 19:35_

![screen shot 2017-10-31 at 9 34 42 pm](https://user-images.githubusercontent.com/8037526/32245112-647676e2-be83-11e7-954b-f0bbd834bc3a.png)

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 19:37_

![screen shot 2017-10-31 at 9 36 47 pm](https://user-images.githubusercontent.com/8037526/32245189-a4544834-be83-11e7-979f-245a32027173.png)
this is my xcode version

**Comment by tsonevn** [comment]
_From @NathanaelA on October 31, 2017 20:11_

A couple things you can try:
1. what does `xcodebuild -version` say?
2. what does `c++ --version` say?
3. What does `tns doctor` say?

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 20:15_

`xcodebuild -version`
Xcode 9.0
Build version 9A235
`c++ --version`
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`tns doctor`
Your components are up-to-date: 
nativescript,tns-core-modules,tns-android,tns-ios

**Comment by tsonevn** [comment]
_From @NathanaelA on October 31, 2017 20:49_

@fawzywassel - Everything looks correct based on that.   So when you do a 
- `tns create name` 
- `cd name`
- `tns platform add ios`
- `tns build ios` 

You get that error, correct? , this is from a brand new project correct?

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 20:51_

yes

**Comment by tsonevn** [comment]
_From @NathanaelA on October 31, 2017 20:54_

Can you do a `tns info`?

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 20:55_

![screen shot 2017-10-31 at 10 55 20 pm](https://user-images.githubusercontent.com/8037526/32248528-a00e46fc-be8e-11e7-994e-abd0344d5607.png)

**Comment by tsonevn** [comment]
_From @fawzywassel on October 31, 2017 21:2_

this issue happen when i trying to add/remove/build/prepare ios

**Comment by tsonevn** [comment]
_From @NathanaelA on October 31, 2017 21:28_

@tsonevn - Any ideas?    This also probably needs to be moved to the CLI repo...

**Comment by tsonevn** [comment]
Hi @fawzywassel 
Could you try to open a Xcode, create a new native project and build it on iOS Simulator? This will help to verify, whether everything is properly configured. If everything works correctly, please try again to create a project and to build it, while following the above-given [instructions](https://github.com/NativeScript/nativescript-cli/issues/3189#issuecomment-341002607).

Also, could you run `xcode-select -v` and to provide, what does the command say?

**Comment by fawzywassel** [comment]
`xcode-select -v`
xcode-select version 2349.

**Comment by fawzywassel** [comment]
xcode new gererate native apps work normaly with no errors

**Comment by tsonevn** [comment]
@fawzywassel 

We are still unable to recreate this behavior on our side, which makes the research on the problem hard. Something that you could check on your side is if the correct path is set up for the Xcode while running `xcode-select -p`. The command should return a string similar to the below attached one:
```
/Applications/Xcode.app/Contents/Developer
```
Also, you could verify, the returned Xcode version in the terminal via `xcodebuild -version` and to check if it is the correct one.

**Comment by fawzywassel** [comment]
`xcode-select -p` Yes, it returned the same you suggest 
`xcodebuild -version`
Xcode 9.0
Build version 9A235

**Comment by fawzywassel** [comment]
@tsonevn can you send me your mail to send to you teamViewer credentials  or any private connection and you will can watch my pc from teamViewer, when you solve it we will post the solution

**Comment by tsonevn** [comment]
Hi @fawzywassel,
Thank you for your suggestion, however, at this point, a remote session is not applicable. After the research we made with our developers on our side this issue seems to be related to your local environment setting and in our further investigation we found that the issue should be related to the info parsing after executing ` xcodebuild -version | head -n 1 | sed -e 's/Xcode //'`.

Regarding that please run ` xcodebuild -version | head -n 1 | sed -e 's/Xcode //'` again, while using all arguments after the command and send us the output.

Thank you in advance for your cooperation.

**Comment by fawzywassel** [comment]
![screen shot 2017-11-04 at 12 23 02 am](https://user-images.githubusercontent.com/8037526/32398199-713d9e6c-c0f6-11e7-98ab-58e9b6a61f46.png)

**Comment by fawzywassel** [comment]
@tsonevn please help me .....

**Comment by tsonevn** [comment]
Hi @fawzywassel,
After reviewing the log from the error from the console, I found that the problem could be related to the overwriting the head command in the machine. The current command does not have `-n` option, which is needed to run the build. 

To confirm that this is the case you could run the following commands and verify if the log on your side will be the same.
`which head` ->result `/usr/bin/head`
`ls -la /usr/bin/he` ->result `No such file or directory`
`ls -la /usr/bin/head` ->result `-rwxr-xr-x  1 root  wheel  18864 23 Mar  2017 /usr/bin/head`

If there is a difference. you could run the following command in the terminal:
`export PATH=/usr/bin/head:$PATH`
The command will set up the path to the needed `head`, while merging it with the current one.

After that try to build an application in the same tab while using `tns run ios`

**Comment by fawzywassel** [comment]
after run all command only one is not the same 
`which head` result is  `/Applications/XAMPP/xamppfiles/bin/head`
and still the same after run `export PATH=/usr/bin/head:$PATH`

**Comment by tsonevn** [comment]
Hi @fawzywassel,
Could you execute one more time the following command `export PATH=/usr/bin/head`? This time close the terminal and open it again. Then run `echo $PATH` and validate that the same path(`/usr/bin/head`) is printed. 

If the path is correct, run `xcodebuild -version | head -n 1 | sed -e 's/Xcode //'` command, to verify if the correct version of the Xcode will be printed.

After that delete `node_modules` and `platforms` folders and rebuild the app with  `tns run ios`

**Comment by fawzywassel** [comment]
@tsonevn
Thanks for your support 
its working now

**Comment by narayananl23** [comment]
I had the same issue and this solved mine 

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

reference [https://github.com/nodejs/node-gyp/issues/569](url)

**Comment by hedza06** [comment]
@narayananl23 also working for me. Thank you!

**Comment by mrisek** [comment]
I faced the same scenario after fresh install of Xcode 9.2. Thanks @narayananl23 for a solution!

**Comment by aleangelico** [comment]
@narayananl23 this worked for me too, thanks!

**Comment by burkeholland** [comment]
@narayananl23 Worked for me as well! Thank you so much.

**Comment by biopowder** [comment]
But for me is still not working, i have tried all things what is mentioned here. Here is my stackoverflow ticket https://stackoverflow.com/questions/54873245/nativescript-can-only-run-in-xcode-version-6-0-or-greater.

**Comment by biopowder** [comment]
any news about this issue?
