### ISSUE TITLE
Cant install nativescript cli

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/nativescript-cli#319]
```
npm ERR! Failed at the ref@0.3.5 install script.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above
```

**Comment by rosen-vladimirov** [comment]
Hi @calebeaires ,
Can you send some more details:
 - Which OS are you using
 - Which node version are you using (output of ```node -v```)
 - Which npm version are you using (output of ```npm -v```)
 - In case you are running on MacOS or Linux, do you have gcc installed?
 - Can you send us the full log of the installation. For example ```npm i -g nativescript > output.txt``` and share the output.txt file

**Comment by calebeaires** [comment]
Mac OSx
Node: v0.10.33
npm: 1.4.28

````
> fibers@1.0.5 install /usr/local/lib/node_modules/nativescript/node_modules/fibers
> node ./build.js

`darwin-x64-v8-3.14` exists; testing
Binary is fine; exiting

> ref@0.3.5 install /usr/local/lib/node_modules/nativescript/node_modules/ref
> node ./build.js


> ffi@1.2.7 install /usr/local/lib/node_modules/nativescript/node_modules/ffi
> node ./build.js


> ws@0.4.32 install /usr/local/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

```

**Comment by rosen-vladimirov** [comment]
@calebeaires 

Thank you for this information. Unfortunately the short log that you've provided, does not give us more information. May I ask you to execute:
```npm i -g --verbose nativescript > output.txt``` and share the output.txt file?
Also can you check if you have gcc installed on your machine?

**Comment by calebeaires** [comment]
I have did it. Output still the same

**Comment by calebeaires** [comment]
Install got this:  https://www.dropbox.com/s/1p6q5q4juf5mjh3/output.txt?dl=0

**Comment by rosen-vladimirov** [comment]
@calebeaires , thank you for providing the log. The important messages I've found in it are:
```
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: EPERM, utime '/Users/mymacbook/.node-gyp/0.10.33'
gyp ERR! System Darwin 14.1.0
```
This indicates that the script is started with a user, that cannot access node-gyp (or at least it looks like this). Maybe you have installed node-gyp with sudo? You can try reinstalling node-gyp (npm i -g node-gyp) or installing nativescript-cli with sudo. 
The log you've provided suggests to reinstall node-gyp:
```
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
Build failed
```
Can you try this and inform us if it works for you?

**Comment by calebeaires** [comment]
Did it. Thanks!

**Comment by rosen-vladimirov** [comment]
I'm glad it helped. I'm closing this issue now, but feel free to contact us in case you have any problems or concerns.

**Comment by shinsenter** [comment]
Solve the problem after reinstall node-gyp
