### ISSUE TITLE
iOS console.info and console.warn is ignored

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#3191]
With `tns run ios` the logging:
```
console.log("Log: " + this.counter);
console.info("Info: " + this.counter);
console.warn("Warn: " + this.counter);
console.error("Err: " + this.counter);
```

Will output only log and error messages.
[We probably have to update the filter here](https://github.com/NativeScript/nativescript-cli/blob/0f861bb36ae2ecafe198b15c892c5fe082163732/lib/services/ios-log-filter.ts#L7).

We need to log a very small amount of logs in release builds, for now that would be only startup time, and will handle this in tns-core-modules-widgets through NSLog. It may be worth to consider outputting some of the info warn error etc. in release.

**Comment by rosen-vladimirov** [comment]
This is already implemented in iOS Runtime and CLI in one of our previous releases, so I'm closing this feature request.
