### ISSUE TITLE
Cannot run android on genymotion linux xubuntu

### ISSUE THREAD

**Issue by madsongr** [NativeScript/nativescript-cli#3199]
I configured genymotion to get android sdk from **Use custom Android SDK tools** in ADB tab and it says the path is correct.
So I try to run android in terminal but I get an error:
```  
Cannot find connected devices.
Emulator start failed with: spawn adb ENOENT
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.

```
Running tns device android --available-devices it finds Nexus 5 that was created by android studio.

``` 
Available emulators
┌─────────────┬──────────┬────────────┬─────────────────────┐
│ Device Name │ Platform │ Version    │ Device Identifier   │
│ Nexus 5X    │ Android  │ android-27 │ Nexus_5X_API_27_x86 │
└─────────────┴──────────┴────────────┴─────────────────────┘

Connected devices & emulators
Searching for devices...
spawn adb ENOENT
# device android

┌─────────┬─────────────────────────────────────────────────┐
│ Usage   │ Synopsis                                        │
│ General │ $ tns device android [--timeout <Milliseconds>] │
└─────────┴─────────────────────────────────────────────────┘

Lists all recognized connected Android physical and running virtual devices with serial number and index.  

### Options

    * --available-devices - Lists all available emulators for Android.
    * --timeout - Sets the time in milliseconds for the operation to search for connected devices before completing. If not set, the default value is 4000. 
```
Is there a fix to run in genymotion?

**Comment by NickIliev** [comment]
@madsongr  Try starting your GenyMotion in advance before executing the `tns` command.
Once the geny is started see if it is recognized by ABDB with
```
tns devices
```

and if it is listed as connected device you should be able to execute `tns run android`

**Comment by madsongr** [comment]
I've done that already. It's not being recognized.

**Comment by NickIliev** [comment]
There are multiple threads about GenyMotion not being recognized with ubunto - [see this query](https://www.google.bg/search?rlz=1C1CHBF_enBG741BG742&biw=1920&bih=1053&ei=rs8BWqiPMYeBaenIvYgP&q=genymotion+not+being+found+on+XUbuntu&oq=genymotion+not+being+found+on+XUbuntu&gs_l=psy-ab.3...2114.2114.0.2417.1.1.0.0.0.0.114.114.0j1.1.0....0...1.1.64.psy-ab..0.0.0....0.97GLRS4MGYM).

I would recommend either to try one of the solutions provided in the queries or simply to install AVD instaed of GenyMotion. The lastest AVDs are very fast with HAXm and are supporting Google Play.

**Comment by madsongr** [comment]
I added the Genymotion installation directory to the PATH environment variable las explained here: [http://docs.telerik.com/platform/appbuilder/nativescript/running-your-app/run-app-native-emulator](url)
 with `export PATH=$PATH:/home/user/.Genymobile/Genymotion/` so it worked.
Thanks for your response.
