### ISSUE TITLE
CLI to respect android and ios platforms as npm packages

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#3208]
Currently, the NativeScript CLI adds the Android and iOS platforms under the `nativescript` key of the **package.json** file.

```json
  "nativescript": {
    "id": "org.nativescript.nativescriptsdkexamplesng",
    "tns-ios": {
      "version": "3.2.0"
    },
    "tns-android": {
      "version": "3.2.0"
    }
  },
```

Ideally, the NativeScript CLI could install Android and iOS platforms as a project *dependency/devDependency*.

**Comment by DimitarTachev** [comment]
Closing in favor of https://github.com/NativeScript/nativescript-cli/issues/4511
