### ISSUE TITLE
node-package-manager assumes that platform package is always the first in the list of updated ones

### ISSUE THREAD

**Issue by Buuhuu** [NativeScript/nativescript-cli#3217]
In [node-package-manager.ts#L158](
https://github.com/NativeScript/nativescript-cli/blob/d4817bc24be8b2f08e1101d22a53b65e6d3e9d8c/lib/node-package-manager.ts#L158) the assumption is made that the installed platform package is always the first entry in the list of returned updated dependencies. In my setup I install a couple of `file:...` dependencies which are listed in the same place:

```
[
  {
    "action": "update",
    "name": "nativescript-adobe-marketing-cloud",
    "version": "file:nativescript-adobe-marketing-cloud-1.3.1.tgz",
    "path": "...",
    "previousVersion": ""
  },
  {
    "action": "update",
    "name": "nativescript-angular",
    "version": "file:nativescript-angular-3.1.3.tgz",
    "path": "...",
    "previousVersion": ""
  },
  {
    "action": "update",
    "name": "nativescript-google-maps-sdk",
    "version": "file:nativescript-google-maps-sdk-2.3.1.tgz",
    "path": "...",
    "previousVersion": ""
  },
  {
    "action": "update",
    "name": "nativescript-image-swipe",
    "version": "file:nativescript-image-swipe-2.0.3.tgz",
    "path": "...",
    "previousVersion": ""
  },
  {
    "action": "update",
    "name": "tns-android",
    "version": "3.1.1",
    "path": "...",
    "previousVersion": "3.1.1"
  }
]
```

And tns-android in that case it the last entry.

**Comment by rosen-vladimirov** [comment]
Hey @Buuhuu ,
Can you send us the output of the following commands:
```
$ node -v
$ npm -v 
```

**Comment by rosen-vladimirov** [comment]
Also which command fails on your side? Is it `tns build android` or something else?

**Comment by Buuhuu** [comment]
node 8.9.1, npm 5.5.1 and its `tns prepare android` and any other like that - working on a PR right now.
