### ISSUE TITLE
getting spawn EACCES.

### ISSUE THREAD

**Issue by chauhan-saurabh** [NativeScript/nativescript-cli#3223]
Getting: 
Unable to apply changes on device: emulator-5554. Error is: spawn EACCES.
 on making android build

**Comment by dtopuzov** [comment]
Hi @chauhan-saurabh,
Can you please provide more details for this error:
- Does it happen on HelloWorld project?
- What is your OS?
- Versions of npm and nodejs?

**Comment by chauhan-saurabh** [comment]
@dtopuzov issue resolved by recreating android, ios, node-modules and hooks folder and updating versions as well
