### ISSUE TITLE
nativescript-cli install on mac fails

### ISSUE THREAD

**Issue by murphy85** [NativeScript/nativescript-cli#3228]
I tried to execute the macOs setup script, but there are some ressources missing

```
xxx:~ admin$ ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"
This scripts needs sudo permissions
curl: (22) The requested URL returned error: 404 Not Found
```

The missing resource is:
https://raw.githubusercontent.com/NativeScript/nativescript-cli/production/setup/native-script.rb

There is no branch "production" in github.

A workaround is to start the ruby process with sudo:

```
xxx:~ admin$ sudo ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"
Password:
NativeScript requires Xcode.
If you do not have Xcode installed, download and install it from App Store and run it once to complete its setup.
Do you have Xcode installed? (y/n)
...
```

Please update the documentation!

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#967

**Comment by etabakov** [comment]
The script is updated to not use the missing branch. Should be working on your side now.
Thanks for letting us know about this problem!

**Comment by rosen-vladimirov** [comment]
Closing as we are no longer using the production branch and the issue should be resolved.
