### ISSUE TITLE
Unable to apply changes on device: emulator. Too many open files

### ISSUE THREAD

**Issue by rakeshgirase** [NativeScript/nativescript-cli#3236]
### Tell us about the problem
When tried to run the application got following error:
Unable to apply changes on device: emulator-5554. Error is: EMFILE: too many open files, open 'C:\Users\rakeshgirase\IdeaProjects\Angular\SasQuiz\platforms\android\src\main\assets\app\tns_modules\rxjs\operators\
expand.js.map'.
The project file undefined is corrupted. 
Consider restoring an earlier version from your source control or backup.
Additional technical info: Error: EMFILE: too many open files, open 'C:\Users\rakeshgirase\IdeaProjects\Angular\SasQuiz\package.json'
Failed to display command help { Error: EMFILE: too many open files, open 'C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\docs\man_pages\project\testing\run-android.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at FileSystem.readFile (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\file-system.js:156:19)
    at FileSystem.readText (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\file-system.js:166:21)
    at HelpService.<anonymous> (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\services\help-service.js:138:33)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\services\help-service.js:4:58)
    at <anonymous>
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: C:\\,......\\nvm\\v8.9.1\\node_modules\\nativescript\\docs\\man_pages\\project\\testing\\run-android.md' }

### Which platform(s) does your issue occur on?
Android. Not tried with ios

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
3.3.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
Execute following command
tns run android
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://github.com/rakeshgirase/SasQuizNewLaptop
###Detailed Error Message
-----------------
Unable to apply changes on device: emulator-5554. Error is: EMFILE: too many open files, open 'C:\Users\rakeshgirase\IdeaProjects\Angular\SasQuiz\platforms\android\src\main\assets\app\tns_modules\rxjs\operators\
expand.js.map'.
The project file undefined is corrupted. 
Consider restoring an earlier version from your source control or backup.
Additional technical info: Error: EMFILE: too many open files, open 'C:\Users\rakeshgirase\IdeaProjects\Angular\SasQuiz\package.json'
Failed to display command help { Error: EMFILE: too many open files, open 'C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\docs\man_pages\project\testing\run-android.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at FileSystem.readFile (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\file-system.js:156:19)
    at FileSystem.readText (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\file-system.js:166:21)
    at HelpService.<anonymous> (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\services\help-service.js:138:33)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Data\Rakesh\Workspace\Softwares\nvm\v8.9.1\node_modules\nativescript\lib\common\services\help-service.js:4:58)
    at <anonymous>
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Data\\Rakesh\\Workspace\\Softwares\\nvm\\v8.9.1\\node_modules\\nativescript\\docs\\man_pages\\project\\testing\\run-android.md' }

**Comment by dtopuzov** [comment]
Hi @rakeshgirase

Can you reproduce the issue with hello-world application?
If it happens only to specific app, please post content of package.json (all the dependencies).

**Comment by rakeshgirase** [comment]
Hi @dtopuzov  This sometimes run fine on my old laptop but gives me this error on new one. I wouldnt have raised it here but since the error message is not helpful and i thought of asking it here. Following is my package.json file.
-----------------------------
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.exuberant.exams.sas",
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/router": "4.4.6",
    "nativescript-angular": "4.4.1",
    "nativescript-pro-ui": "3.2.0",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "tns-core-modules": "3.3.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "3.2.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.1",
    "node-sass": "4.5.3",
    "tslint": "5.8.0",
    "typescript": "2.4.2"
  }
}
--------------------------------

**Comment by rakeshgirase** [comment]
I created another Sample Project using Nativescript Sidekick and it worked simply fine. Both the projects have same package.json file so I doubt if this is something to do with the package.json.

**Comment by rosen-vladimirov** [comment]
Hey @rakeshgirase ,
Can you try reproducing the issue with latest CLI - we have applied some fixes that should resolve it, but can you please verify it on your side?

**Comment by rakeshgirase** [comment]
Hi @rosen-vladimirov, thanks for your reply.  Creating a fresh project has resolved this issue so I dont think this can be reproduced now.
