### ISSUE TITLE
Run ios shows "Unable to find adb in PATH. Default one from %s resources will be used." warning then android SDK is not in path

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#324]

**Comment by Fatme** [comment]
1. Remove android sdk from PATH
2. Execute run ios

**Comment by demsking** [comment]
I have the same issue when I'm trying to run 'tns platform add android'.
How to resolve that please?

**Comment by rosen-vladimirov** [comment]
@demsking 
It looks like you have not configured your system. The message is just a warning, not an error. In case you do not want to see it, you have to add the following directories from android-sdk in your PATH: `platform-tools` and `tools`. You can check [this link](http://docs.nativescript.org/setup/quick-setup#the-nativescript-cli) for more information how to setup your system.

**Comment by teobugslayer** [comment]
I've changed the code so that this check is done only when installing the CLI.
