### ISSUE TITLE
About JDK_HOME & JAVA_HOME

### ISSUE THREAD

**Issue by bluelovers** [NativeScript/nativescript-cli#3248]
## Please, provide the details below:

some ppl use JRE and JDK at same time

and some JRE didn't have javac

i think maybe should use process.env.JDK_HOME > process.env.JAVA_HOME

https://github.com/telerik/mobile-cli-lib/pull/1031/files

**Comment by rosen-vladimirov** [comment]
Hey @bluelovers ,
Thanks for your efforts. I've marked this change as breaking, as it may cause unexpected behavior on some machines where JDK_HOME is already set. Current CLI version may work as expected, but the JDK_HOME may point to a JAVA version that is not supported, so after implementing this feature, Android builds may fail.
