### ISSUE TITLE
How to connect to genymotion emulator? 

### ISSUE THREAD

**Issue by webryan** [NativeScript/nativescript-cli#325]
I got the name of emulator by 'genyshell -c "device list"'.
```
F:\app\testApp>genyshell -c "devices list"
Logging activities to file: C:/Users/henryguo/AppData/Local/Genymobile/genymotio
n-shell.log
Connection mode: local host
Welcome to Genymotion Shell

Genymotion virtual device selected: galaxys4

Available devices:

 Id | Select |    Status     |   Type   |   IP Address    |      Name
----+--------+---------------+----------+-----------------+---------------
  0 |        |           Off |  virtual |         0.0.0.0 | Custom Phone - 4.4.4
 - API 19 - 768x1280
  1 |    *   |            On |  virtual |  192.168.56.102 | galaxys4
  2 |        |           Off |  virtual |         0.0.0.0 | Samsung Galaxy S4 -
4.4.4 - API 19 - 1080x1920
```

Then I try to connect the emulator by 'tns emulate android --geny "galaxys4"'. But I got a error message. Anything wrong ? 

```
BUILD SUCCESSFUL
Total time: 10 seconds
Project successfully built
Using  F:\app\testApp\platforms\android\bin\testApp-debug.apk
Command failed: ADB server didn't ACK
* failed to start daemon *
error:
```

**Comment by webryan** [comment]
I try to restart and kill the adb server by 'adb restart-server'/'adb kill-server', but it's not effect

**Comment by rosen-vladimirov** [comment]
Hi @webryan 
Can you try ```$ adb kill-server``` and after that execute ```$ tns emulate android --geny galaxys4``` 
Also, have you added tools and platform-tools from Android SDK in your PATH? If yes, may I ask you to give us the output of ```adb version```

**Comment by webryan** [comment]
@rosen-vladimirov 
still not work.
```
F:\app\testApp>adb version
Android Debug Bridge version 1.0.31
```

**Comment by rosen-vladimirov** [comment]
Hi @webryan ,
Can you try updating your adb to your latest version (it is 1.0.32) and try one more time?

**Comment by webryan** [comment]
@rosen-vladimirov 
It's work after updating the adb to 1.0.32. thank u very much.

**Comment by Nathanaela** [comment]
Just to echo this for any future users -- I had the exact same issue; 1.0.31 fails; 1.0.32 works.   Make sure of the version.

**Comment by teobugslayer** [comment]
Hi @Nathanaela,

The mismatch in adb version happens because Genymotion comes with their embedded adb and adb versions are incompatible. The fix is to install the latest Android SDK and use its adb first. I am sorry for the inconvenience caused!

**Comment by eliezer387** [comment]
you have to configure your Sdk path on the tab ADB of the Genymotion configuration
