### ISSUE TITLE
Typescript Copiler Failed Error

### ISSUE THREAD

**Issue by shaileshkadam25** [NativeScript/nativescript-cli#3272]
Error Message - Unable to apply changes on device: XXXX. Error is: TypeScript compiler failed with exit code 3221225477.

i have upgraded to latest version on NPM but still getting same error. please find below screenshot and attachd package.json, package-lock.json and tsconfig.json files

![33865914-e42188c4-dec1-11e7-8ac9-d05cd3773e5a](https://user-images.githubusercontent.com/34359368/34024871-9b29faa6-e11a-11e7-944c-f341ff63a05f.png)
[package.txt](https://github.com/NativeScript/nativescript-cli/files/1561436/package.txt)
[package-lock.txt](https://github.com/NativeScript/nativescript-cli/files/1561437/package-lock.txt)
[tsconfig.txt](https://github.com/NativeScript/nativescript-cli/files/1561438/tsconfig.txt)

**Comment by NickIliev** [comment]
@shaileshkadam25 try building with TypeScript 2.4.2 (remove `node_modules` folder before executng `npm i`)

**Comment by shaileshkadam25** [comment]
@NickIliev ; sorry for late response, was on vacation..
I tried to run with Typescript 2.4.2 but still getting same error.

![image](https://user-images.githubusercontent.com/34359368/34921318-5f02843e-f94e-11e7-9d64-f3430b831ba5.png)

**Comment by shaileshkadam25** [comment]
![image](https://user-images.githubusercontent.com/34359368/34921344-b593db54-f94e-11e7-928d-5623076a3940.png)

**Comment by shaileshkadam25** [comment]
Steps to reproduce the issue..
1. Install latest nodejs latest LTS from official website 
2. Follow the steps of installation provided as per link -https://docs.nativescript.org/angular/start/quick-setup 
3. My machine config is as follows 
    Windows 10 Pro 32 bit OS
    AMD Athlon(tm) Dual Core Processor 4450e 2.30 GHz
    3 GB Ram
4. create the hellowold app as per link - https://docs.nativescript.org/angular/tutorial/ng-chapter-1
    tns create HelloWorld --template nativescript-template-ng-tutorial
5. connected LG Android mobile phone to computer 
6. Run the following command to start the application
   tns run android

Please find attached config file for more info

[package.txt](https://github.com/NativeScript/nativescript-cli/files/1629877/package.txt)
[package-lock.txt](https://github.com/NativeScript/nativescript-cli/files/1629878/package-lock.txt)
[tsconfig.txt](https://github.com/NativeScript/nativescript-cli/files/1629879/tsconfig.txt)
