### ISSUE TITLE
Unable to install android platform

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/nativescript-cli#3289]
I'm using [this](https://github.com/NativeScript/template-drawer-navigation-ng) template starter for my nativescript project by running this command:

```
tns create my-app-name --template tns-template-drawer-navigation-ng
```
Then, when I want to install android platform by: `tns platform add android`, I get the following errors:

```
no such file or directory tns-android\framework\libs
```

### Platform
Android

### Project version numbers
- CLI: 3.1.3
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.0

**Comment by vahidvdn** [comment]
The same issue with nativescript default template.

**Comment by NickIliev** [comment]
@vahidvdn update your CLI to versions 3.4.0 and let me knopw if you are still experiencing this issue.
TO update NativeScript CLI:
```
npm uninstall -g nativescript
npm install -g nativescript
```

**Comment by vahidvdn** [comment]
@NickIliev Thanks. Now it works fine.

**Comment by Joelinbakumar** [comment]
hi @NickIliev 
After uninstalled and while installing i am getting this error.
![capture61](https://user-images.githubusercontent.com/29222845/37910321-dcc18bea-312a-11e8-8217-79744dc86647.PNG)

**Comment by Fatme** [comment]
Hi @Joelinbakumar,

This issue happens with some specific versions of `npm`. Can you please check your `npm version` - Just execute `npm --version`.

**Comment by Joelinbakumar** [comment]
hi @Fatme 
its 5.6.0

**Comment by Fatme** [comment]
Hi @Joelinbakumar,

I've just checked your error log again and see that your npm version is `3.10.9`.
```
npm ERR! node v6.9.2
npm ERR! npm v3.10.9
```

I'm suspecting that you have both `3.10.9` and `5.6.0` versions of npm.
Can your please ensure that you're using version `5.6.0` and try to execute command again.

**Comment by Joelinbakumar** [comment]
hi @Fatme 

Yes i checked it the version is 5.6.0 only and i updated my node and now its working fine thank you @Fatme .
