### ISSUE TITLE
Can't find android devices after moving Android directories

### ISSUE THREAD

**Issue by Nqsty** [NativeScript/nativescript-cli#3304]
### Tell us about the problem
I moved the `Android` (containing `android-sdk` and `AndroidStudio` directories) and `.android` directories to another hard drive because of space issues.
I changed all environment variables that were linked to the previous location. (`ANDROID_HOME`, `ANDROID_SDK_HOME` and 2 others in the PATH)
When I run `tns run android`, I have the following error `Cannot find connected devices.` and there indeed isnt any device found when running `tns devices`. Also, `tns doctor` finds no issues.
Note that everything was working as intended before moving the directories and changing the env variables.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.0
- Cross-platform modules: 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Install all the dependencies with `@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://www.nativescript.org/setup/win'))"` as told in the [Windows Quick Setup](https://docs.nativescript.org/start/quick-setup#windows)
2. Move the `Android` and `.android` directories to another hard drive
3. Run `tns run android` into any NS project you have

I imagine I must have missed something to change but I can't find what.

Regards.

**Comment by NickIliev** [comment]
@Nqsty update the Android SDK location in Android Studio

open **Android Studio** and go to

**Tools >> Android >> SDK Manager >> Android SDK**

set the path to **Android SDK Location** to be the same as for your `ANDROID_HOME`

**Comment by Nqsty** [comment]
@NickIliev it was already the same.

Here's my env variables:
* `ANDROID_HOME`: `E:\Android\android-sdk`
* `ANDROID_SDK_HOME`: `E:\`
* In path:
    * `E:\Android\android-sdk\tools`
    * `E:\Android\android-sdk\platform-tools`

**Comment by NickIliev** [comment]
Regarding `Cannot find connected devices.` - have you created an Android Virtual Device (downloaded system images and installed in your AVD Manager)

**Comment by Nqsty** [comment]
Yes, [see screenshot](https://i.imgur.com/tZAwHzL.png). :(

**Comment by NickIliev** [comment]
@Nqsty have you tried to completely uninstall and install NativeScript
```
npm uninstall -g nativescript
npm i -g nativescript
tns doctor
```

**Comment by Nqsty** [comment]
@NickIliev I did the uninstall and reinstall then:
`tns doctor`
```
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Your components are up-to-date:
nativescript,tns-core-modules,tns-android,tns-ios

No issues were detected.
```
`tns run android`
```
Searching for devices...
Skipping prepare.
Unable to apply changes on device: emulator-5554. Error is: The device is not authorized. Please use the --emulator flag to run the application on on an emulator.
```
`tns run android --emulator`
```
Searching for devices...
Cannot find connected devices.
Emulator start failed with: Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
```
With the emulator running: `tns device`
```
Connected devices & emulators
Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
┌───┬─────────────┬──────────┬───────────────────┬────────┬─────────────┐
│ # │ Device Name │ Platform │ Device Identifier │ Type   │ Status      │
│ 1 │             │ Android  │ emulator-5554     │ Device │ Unreachable │
└───┴─────────────┴──────────┴───────────────────┴────────┴─────────────┘
```

I deleted and recreated the same AVD and got the same outcome for the last 3 commands.

**Comment by NickIliev** [comment]
Hey @Nqsty can you check if your device is reachable and authorized via the ADB command (the native Android command tool).
[Here ](https://stackoverflow.com/a/25546300/4936697)you can find instruction s on how to run the ADB commands and how to kill/restart your ADB server.

**Comment by Nqsty** [comment]
@NickIliev It appears that the combination of Nexus 5X and the API 27 was the problem. I changed for a Nexus 6 and it's working. I can't find why the combination doesn't work anymore though.
Thank you a lot for your help through this issue! :)

**Comment by NickIliev** [comment]
@Nqsty FYI: sometimes the newly created emulators are popping up a dialog that requires user interaction to grant authorization (just like the first time authorization for USB Debbuging on a real device), so maybe that was the case. I had similar cases where the prompt on the emulator has blocked the execution of any `tns` (or `adb`) commands so I had to explicitly grant access (by tapping the option in the prompted dialog).
