### ISSUE TITLE
Support livesync with webpack

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#3317]
## Please, provide the details below:
We need to support LiveSync functionality with webpack builds. The idea is to use the webpack's watcher and rebuild the .js files when a change occur.

### Which platform(s) does your issue occur on?
Both

**Comment by rosen-vladimirov** [comment]
You can now use LiveSync + Webpack with the following command:
```
$ tns run <platform> --bundle
```

NOTE: This requires using the latest version of nativescript-dev-webpack

**Comment by IAMtheIAM** [comment]
`tns debug <platform> --bundle` can we do that? It doesn't seem to support livesync with webpack during Debug sessions

**Comment by IAMtheIAM** [comment]
@NickIliev Hi again. I cloned that app and did
`npm i`
`tns debug android --bundle`

the app then started.

I opened `main-page.xml` and changed the label text from "Tap the button" to "Tap the button!!"
Saved

The CLI then detected the changed, webpack incrementally compiled, then the app did all its hooks, reinstalled the app on the emulator, and opened the app.

The text unfortunately did not change, so my livesync is busted somehow.

Here is my environment:
tns 4.1.2
nativescript 4.1.2
webpack 4.16.1
typescript 2.7.2
nativescript-angular 6.1.0-rc.0
windows 10
android studio emulator latest, api 28

Is there something else that has to be done to get this working? Thanks for the help again!

**Comment by NickIliev** [comment]
@IAMtheIAM You are probably hitting [this known bug](https://github.com/NativeScript/nativescript-cli/issues/3602) related to API 27 and above. Can you try the same workflow by using a lower API level emulator (e.g API 25).

**Comment by IAMtheIAM** [comment]
That's great to know! I downgraded to API 25 and it fixed the issue! thanks once again. Incremental compile and reload takes about 30 seconds - better than 3 minutes for a full rebuild build, a clean build takes almost 15 minutes.

Are there any optimizations that could be done to speed up these incremental compilations, such as multi threaded webpack build or gradle builds?

**Comment by tomylee001001** [comment]
@NickIliev  is there going to be fix for this issue?
As you know with [this](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html) goole play do not accept API 25 or lower apps.

**Comment by dtopuzov** [comment]
Hi @tomylee001001,

Live sync should be ok on all android versions with latest official release.

If you still experience issues, please log an issue and provide as much details as possible.

**Comment by NickIliev** [comment]
@tomylee001001 Google Play will continue to accept applications that are working on lower API levels. What the blog says and what Google will require is that the **`targetSdkVersion`** should be set to API 26 from the 1st of November. This will not restrict the **minSdkVersion** or the **compileSdkVersion** and is not related to what device you will use for development (and respectivly for livesync).

The issue with `targetSdkVersion` is logged [here](https://github.com/NativeScript/nativescript-cli/issues/3921)
