### ISSUE TITLE
Releasing the app by signing doesn't work with *.jks file. 

### ISSUE THREAD

**Issue by Sharique-Hasan** [NativeScript/nativescript-cli#3320]
Hello, 

I had a native app already published in playstore.Now I have ported it on nativescript with angular. To release the app I have to sign it with the same key. When I tried to do that I got an error

`They keystore is tempered or the password is incorrect. `

However I am providing valid keystore and password. I tested this with **Sidekick**.
- Created a new app with it. 
- Built the release version of app with same keystore and password

Project builds successfully. Somehow it is rejecting the *.jks keystore on commandline. When I signed it with newly created keystore *.keystore it built the app successfully. What am I missing with *.jks keystore signing?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sidekick-feedback#119

**Comment by Sharique-Hasan** [comment]
@NickIliev but it is related to cli. As the supposed behavior is working with Sidekick but failing in CLI
