### ISSUE TITLE
Migrating between android runtimes does not update res directory

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#333]
In case you use $ tns platform update android@0.9.0 (when you are using 0.4.2 for example), platforms/android/res directory will not be updated accordingly and in some cases could make your project unbuildable.

**Comment by teobugslayer** [comment]
This potentially will be fixed when implementing https://github.com/NativeScript/nativescript-cli/issues/335

**Comment by vchimev** [comment]
Not relevant anymore.
