### ISSUE TITLE
`tns debug ios --chrome` can not stop on first line

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#3338]
There is no way to stop on first line with `tns debug ios` and ChromeDevTools.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2@rc
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1
- Plugin(s): No

### Please tell us how to recreate the issue in as much detail as possible.

Steps to reproduce:
```
tns create TestApp
tns debug ios --debug-brk --path TestApp
=> at this point app stops on launch screen
Open debug url in chrome browser
=> app continue and you can not hit the first line
```

**Comment by Natalia-Hristova** [comment]
This issue is fixed and will be available in the next ```CLI``` official release.
