### ISSUE TITLE
Enable LiveSync during bundling

### ISSUE THREAD

**Issue by Mitko-Kerezov** [NativeScript/nativescript-cli#3349]
### Enable LiveSync during bundling
Some bundler plugins (for example `nativescript-dev-webpack`) have the ability to be launched with a watcher and perform incremental bundling while watching for file changes. CLI should provide a way for such plugins to plug into the LiveSync pipeline.

Ultimately `tns run <platform> --bundle` should watch for file changes and LiveSync them correctly.

**Comment by Natalia-Hristova** [comment]
This is enabled in `nativescript 4.0.0` 
Checked in `Angular` (changed `.html, .ts, .css`) and `non-Angular` (changed `.js, .xml, .css`) apps, for `iOS` and `Android`, for both - `emulator/simulator` and device`.
