### ISSUE TITLE
Respect Android and iOS folders from App_Resources

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#335]
Example:
We should be able to respect App_Resources/Android folder and on prepare step we should copy its content into platforms/android/res

**Comment by rosen-vladimirov** [comment]
Same is valid for AndroidManifest.xml inside App_Resources/Android

**Comment by Fatme** [comment]
Yes, everything in Android folder should be respected. The description above is just a example with `res` folder.

**Comment by teobugslayer** [comment]
Additionally, we must change current templates, and move drawable-* dirs into res/

The "prepare" command should change to accomodate

**Comment by maknz** [comment]
:+1:

**Comment by Mitko-Kerezov** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/478
