### ISSUE TITLE
Debug fails to launch on MS Visual Code after updating to 1.20.0

### ISSUE THREAD

**Issue by BeMor81** [NativeScript/nativescript-cli#3358]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
No

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
Debug fails to launch on MS Visual Code after updating to 1.20.0

### Which platform(s) does your issue occur on?
iOS/Android/Both
Android only tested

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 3.4.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) Happening on all projects
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
Update to 1.20 of Visual Studio Code and setup standard debug JSON. Hit debug on either lauch and attach. Activity indicator will start but nothing else happens. Down grading to 1.19 resolves the issue.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by valera1401** [comment]
Also faced with this issue.

**Comment by NickIliev** [comment]
Reproducible with VSCode 1.2.0 and CLI 3.4.2

**Comment by Natalia-Hristova** [comment]
This is fixed in the latest version (0.7.3) of  [nativescript-vscode-extension](https://github.com/NativeScript/nativescript-vscode-extension).
