### ISSUE TITLE
tns debug android taking too long to attach

### ISSUE THREAD

**Issue by mikolino** [NativeScript/nativescript-cli#3363]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes, there are sporadic reports of the same problem without a solution

### Tell us about the problem
When I run `tns debug android` the debugger fails to attach because my phone takes too long to start the app. This is the output I get: 
https://gist.github.com/mikolino/d27a5c7822ca66742e0ca256b667a8af

However if I add a sleep in isAppRunning (nativescript/lib/services/android-debug.service.js) it works:
https://gist.github.com/mikolino/6e359903f447d6a675ecd3cabcef685d

Would it be possible to add a delay/retry when checking if the app is running similar to the one present in waitForDebugger() ?

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.0
- Runtime(s): tns-android 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.
`tns debug android`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No

**Comment by NickIliev** [comment]
@mikolino thank you for reporting this issue - I can confirm the behavior is [related to this](https://github.com/NativeScript/nativescript-cli/issues/3358).

Meanwhile, as a workaround try downgrading the version of your VSCode (e.g 1.19).

Closing as related to [https://github.com/NativeScript/nativescript-cli/issues/3358](https://github.com/NativeScript/nativescript-cli/issues/3358)
