### ISSUE TITLE
Visual Code (v1.20.0)'s Launch on Android not working (CLI v3.4.2)

### ISSUE THREAD

**Issue by danmontz** [NativeScript/nativescript-cli#3364]
### Did you verify this is a real problem by searching the [NativeScript Forum]
I have spent time on the forum but have not found a solution that works.

(http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

### Tell us about the problem
I am using Visual Code's Debug functionality to launch the application on my ASUS Android tablet.

### Which platform(s) does your issue occur on?
Just Android

### Please provide the following version numbers that your issue occurs with:
- CLI:  3.4.2
- Cross-platform modules:  3.4.0
- Runtime(s):  3.4.1
- Plugin(s):
  "dependencies": {
    "nativescript-color-picker": "^1.3.2",
    "nativescript-plugin-firebase": "^5.1.4",
    "nativescript-pro-ui": "3.3.0",
    "nativescript-theme-core": "~1.0.4",
    "tns-core-modules": "~3.4.0"
  },
  "devDependencies": {
    "awesome-typescript-loader": "~3.1.3",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }

### Please tell us how to recreate the issue in as much detail as possible.
I don't really know how to recreate the issue.  It was working at one point, and now it has stopped.  I typically debug on an ASUS Android tablet.  

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Sorry, I don't think there is any code involved.  I have tried creating a brand new hello world project and it has the same issue.

Thanks for your help!

**Comment by dtopuzov** [comment]
Hi @danmontz 

Looking at this [issue](https://github.com/NativeScript/nativescript-cli/issues/3358) it looks we have an issue with latest VSCode, can you try with older version?

**Comment by NickIliev** [comment]
@danmontz  thank you for reporting this issue - I can confirm the behavior is related to [this](https://github.com/NativeScript/nativescript-cli/issues/3358).

Meanwhile, as a workaround try downgrading the version of your VSCode (e.g 1.19).

Closing as related to [https://github.com/NativeScript/nativescript-cli/issues/3358](https://github.com/NativeScript/nativescript-cli/issues/3358)
