### ISSUE TITLE
tns run android fails at ':asbg:generateInterfaceNamesList'

### ISSUE THREAD

**Issue by acapozzoli** [NativeScript/nativescript-cli#3369]
## Please, provide the details below:
Whenever i try to build android app, the system fails
I was on another project, but doubted my instalation. So i created a new app using the sidekick and the failure happens as well.

### Did you verify this is a real problem by searching the [NativeScript Forum]
i checked the forum, only one other person reported something similar and it was closed (issue 3144). That person stated that it was a network problem, wich i never encountered before, and i dont think it is

### Tell us about the problem
tns run android fails at ':asbg:generateInterfaceNamesList'

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.0
- Runtime(s): android "3.4.1"

### Please tell us how to recreate the issue in as much detail as possible.
- create new app with sideckick
- run or build android

Logs from sidekick error tab
[18-02-14 10:56:22.525] (Error) Error detected during LiveSync on 4d005e39521c8013 for C:\Users\Ariel\Documents\Git\TODO1\producto-base-movil\todo1-mobile. Error: Command gradlew.bat failed with exit code 1 Error output: 
 
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Ariel\Documents\Git\TODO1\producto-base-movil\todo1-mobile\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 63

* What went wrong:
Execution failed for task ':asbg:generateInterfaceNamesList'.
> Could not get unknown property 'jarFiles' for project ':asbg' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#948
