### ISSUE TITLE
How to use 3rd party library API with nativeScript ?

### ISSUE THREAD

**Issue by ketansoni79** [NativeScript/nativescript-cli#3374]
Hello,
I want to use [Estimote](https://github.com/Estimote/iOS-SDK) sdk for ios and android with native script , I am trying to build plugin for Estimote sdk to use with nativescript. But I don't to  how to write js file to use Estimote SDK APIs. Any lights on this will be very helpful.

Thanks

**Comment by NickIliev** [comment]
Hello @ketansoni79 and thank you for your interest in NativeScript.
Please notice that this repository is for logging issues, bugs and feature request related to nativescript-cli.

For how-to related questions, i would recommend using the community channels like [NativeScript forum](https://discourse.nativescript.org/), SO or NativeScript community slack.

Regarding your question - check out the following documentation articles on how to use native libraries in NativeScript:
- [Android marshaling](https://docs.nativescript.org/runtimes/android/marshalling/overview) and [Android plugin structure](https://docs.nativescript.org/runtimes/android/plugins/plugins)

-[ iOS marshaling](https://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview) and using [native iOS libraries in NativeScript](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries)
