### ISSUE TITLE
Running app with locally installed plugin DOES NOT transpile the plugin TypeScript files

### ISSUE THREAD

**Issue by radeva** [NativeScript/nativescript-cli#3378]
### Did you verify this is a real problem by searching the [NativeScript Forum]
I'm still not sure if this is a problem or expected behavior. I'm sure the CLI didn't work like this before.
Have in mind this clarification is quite important for us since it affects the plugin development workflow which we explicitly recommend for building plugins.

### Tell us about the problem
Previously when I had to develop a plugin, I followed the guidelines of the [NativeScript Plugin Seed](https://github.com/NativeScript/nativescript-plugin-seed) stating that I need to run `tsc -watch` to watch for changes in the plugin and then run the plugin demo using the `npm run demo.android` or `npm run demo.ios`. This was enough to transpile the TypeScript when a do a change in the plugin and reload the demo app. 

What I noticed recently is that if I follow the workflow above, the app is restared twice. Stopping the command for watching for TypeScript changes "fixes" this. But what it means? 
 - Does this mean that running a demo with --syncAllFiles now is able to transpile the plugin .ts files also? - Or is it some side effect in recent versions? 
- Or is it a side effect from the way npm 5 works?

We need to know for certain what to recommend to our plugin authors.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 
  "tns-core-modules": "^3.1.0",
  "tns-platform-declarations": "^3.0.0",
- Runtime(s):
    "android": "3.0.0",
    "ios": "3.0.0"
- Plugin(s): (look for the version number in the `package.json` file of your
project)
- NPM: 5.6.0
### Please tell us how to recreate the issue in as much detail as possible.

1. git clone https://github.com/NativeScript/nativescript-plugin-seed.git
2. cd nativescript-plugin-seed/src
3. Open a command prompt / Terminal and write `npm run build`
4. In the same command prompt/Terminal write `npm run plugin.tscwatch`
5. In another command prompt / Terminal write `npm run demo.android` or `npm run demo.ios`
6. Make a change in the `yourplugin.common.ts` and watch how the change is applied to the app
7. You can now stop the command started in step 4 and repeat step 6.

The change will again be applied, but the app won't be restarted twice. Which means that only running the demo with `syncAllFiles` is now enough for the plugin TypeScript to be transpiled.

**Comment by radeva** [comment]
@Fatme Do we have an idea from which version of NativeScript we have such behavior? I need this in order to specify that for versions less then this specific one, the users need to watch for the typescript changes explicitly.

**Comment by Fatme** [comment]
I'm not sure about the exact version of {N} CLI, we've checked that this behaviour is since 1.8 version of `tsc`  compiler (which is released ~ 2 years ago)

**Comment by radeva** [comment]
Hi @Fatme @rosen-vladimirov 

It looks like the typescript version is not the only thing that affects this behaviour. Check below for details:

Versions:
tsc --version -> Version 2.7.2
tns --version -> 3.4.3
npm --version -> 5.6.0
package.json -> review the the [camera plugin](https://github.com/NativeScript/nativescript-camera) for package.json of the plugin and the demo.

Follow the steps:
- git clone https://github.com/NativeScript/nativescript-camera.git
- cd nativescript-camera/src
- npm run build
- cd ../demo
- tns run ios --syncAllFiles (The log says `Found peer TypeScript 2.2.2`, I'm not sure where this is coming from)
- Go to demo/node_modules/nativescript-camera/camera.ios.ts and make a change
Result: File is not transpiled.
Expected result: Based on the comments in the issue the file needs to be transpiled automatically.

**Comment by vchimev** [comment]
I experience the same problem with https://github.com/NativeScript/NativeScript/tree/master/e2e/modal-navigation.

Versions:
```
tsc --version: 2.4.2
tns --version: 4.0.0
npm --version: 5.8.0
nativescript-dev-typescript: next - 0.7.1-2018-04-13-04
```
