### ISSUE TITLE
Plugin development within app

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#3383]
I have started working with Nativescript and i intend to write/update some plugins.
Now i know of the way to do it within the plugin itself with a demo app.
But mostly i am always improving plugins from within an actual external app where i find myself with missing features.
I kind of already can do this by modifying the files from node_modules, but there are 2 issues with this:
- i am modifying compiled versions of the plugin
- there is no "watch" on the modules changes.

I think i can fix the first issue with ```npm link```, but i was mostly wondering about the second issue. Is there a way right no to make an app also watch the nativescript plugins for changes?
That would be awesome 

Thanks

**Comment by Fatme** [comment]
Use `--syncAllFiles` option. For example `tns run android| ios --syncAllFiles`. It looks for changes in node_modules folder.

**Comment by farfromrefug** [comment]
@Fatme You are awesome! Will try that right away. I'll close this issue once i report it working as expected.
Thanks

**Comment by farfromrefug** [comment]
I can confirm that it works great!

Thank you
