### ISSUE TITLE
Feature Request: Hot Reload

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3384]
_From @bnussey on February 20, 2018 23:55_

Currently styling and polishing NativeScript UI is incredibly inefficient due to the full app reload necessary for any change. This has added many hours, days, weeks to our NativeScript project and we consider this a significant deterrent in using NativeScript for any new projects.

Both React Native and Flutter have solved this through their hot reload capabilities which preserves state and sees a refresh within milliseconds. 

Is this feature coming to NativeScript soon? 

![Flutter Hot Reload](https://user-images.githubusercontent.com/7215297/36455982-848edbdc-1657-11e8-824f-cba86a520d0d.gif)

![React Native Hot Reload](https://user-images.githubusercontent.com/7215297/36456045-c689acb0-1657-11e8-95ce-dc7484c85ef4.gif)

_Copied from original issue: NativeScript/NativeScript#5447_

**Comment by NickIliev** [comment]
_From @NathanaelA on February 21, 2018 0:22_

I agree; this is a extremely important feature that should get some serious development effort.     As the  bar we should be shooting for is Flutter.    You should check out the instant reload with saved state in Flutter; it really makes a huge difference in programmer productivity.    

I created this sample for Jen's Cheese repo to learn a little bit about flutter (code is in Jen's repo); 

![stock_app](https://user-images.githubusercontent.com/850871/36455882-d14b9388-1667-11e8-8e76-9b5131190a15.gif)
---
What this image shows; I started the app -- THIS is a SINGLE take; I did NOT pause the recorder, edit, or do any tricks.   You see it in realtime, which is why their is delays while I switch over to the code editor and make any changes.   Just one small note: The GIF is recorded at like 10FPS, the app is actually buttery smooth 60fps so don't just the app by this GIF, I just didn't want a 100 meg GIF.    :grinning:

- This started as the stock standard flutter sample; click to add one to the counter.  You can see me click it a couple times. 
- Next, I changed the code from `counter++` to `counter+=5` and you then seem me click; and bam it starts incrementing by 5.    No restart needed, state remained...
- Next I pasted in the code I wrote for the list view.  Again, bam it instantly connected to Firebase; started downloaded the results as it displayed them.  Again, NO RESTART needed!   This is 100% live.
- Next I clicked the button to show the detail; and it showed up.  Again, still no restart.
- Hit back, still maintained the prior code state.

The entire time I recorded this GIF, I never had to restart the app ONCE.   The `counter` btw, was still 19 in the debugger, so even though I totally replaced the main screen with a whole new main screen, the existing state was always maintained.    

Now, there are things you can do in Flutter to cause it to have to restart the app; I've seen it in their code base (assuming it is still valid code)    But in my limited testing; I _never_ got it to recommend or do an app to restart.   That included completely rewriting the main screen, adding a new second screen, attaching to firebase, revamping the images layout, adding errors, and doing all sorts of other things (that I didn't record) as I was playing with the app and it was using hot reload.

---

This is the bar NativeScript needs to be shooting for; our current delay; build; reload is crazy crazy slow compared to this.   And in the event you change a .css/.xml file; the side effects when it reloads the .xml file are quite likely to crash your app on the next click.   ;-(

So :+1: on this request!

**Comment by NickIliev** [comment]
_From @cloudcover on February 21, 2018 0:35_

+1

**Comment by montella1507** [comment]
+1

**Comment by zuohuadong** [comment]
+1

**Comment by MickaelNeves** [comment]
+1

**Comment by DrSensor** [comment]
Hope the +1 thing does not become like http://bit.ly/silly-plus-1

**Comment by AdamSGit** [comment]
Was seriously looking into nativescript with VueJS to start a new project. Thing is, not having HR made me immediately abandon the idea... When you want your interface to be perfect, and spend a lot of time to polish it, it indeed adds like 4 time the time you would spend to do so in continually building your app. This is just a big no-go for me.

**Comment by radeva** [comment]
Hi @AdamSGit @montella1507 @DrSensor ,

I would like to assure you that the team is considering HMR a must-have feature for the framework and is working hard to deliver it. We're still exploring the best options for the implementation. 

In the meantime, recently we improved the [LiveSync for Android](https://www.nativescript.org/blog/nativescript-4.2-is-here) and it is now much faster and reliable. I would recommend to give it a try till the HMR becomes available.

**Comment by montella1507** [comment]
@radeva  will do. I  am happy you see the importance of HMR, thank you very much.

**Comment by sis0k0** [comment]
Closing in favor of https://github.com/NativeScript/NativeScript/issues/6398.
