### ISSUE TITLE
Android snapshot and split apk

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#3385]
I am testing split apk to decrease the size of the generated APK.
No i build my apk like this:
```
tns build  android --bundle --env.uglify --env.snapshot
```
I then look at the generated apks. 
each split apk contains snaphshots for all abis which is not necessary.

It does not represent a huge size, but still everything we can gain is good!

THanks

**Comment by Pip3r4o** [comment]
Hey @farfromrefug what is the output of the snapshot command? Is it blob files, or `.so`s? 

By design, only the binary (.so) snapshots can be split by CPU architecture, whereas the snapshot blob files need to be embedded in the application package as assets which are not subject to abi split.

**Comment by farfromrefug** [comment]
@Pip3r4o yes i am talking about blobs.
Whatever split apk i am in, all the arch blobs are there.

**Comment by RadouaneRoufid** [comment]
From [Nativescript documentation site](https://docs.nativescript.org/best-practices/bundling-with-webpack#v8-heap-snapshot) : 

> targetArchs - Since the serialization format of the V8 heap is architecture-specific, we need a different blob file for each V8 library target architecture. The Android Runtime library contains 3 architecture slices - ia32 (for emulators), arm and arm64 (for devices). However, if not explicitly specified, the arm slice will be used even on arm64 devices. **In other words, generating heap snapshot for all supported architectures (arm, arm64, ia32) will guarantee that the snapshotted heap will be available on every device/emulator.** However, when building for the release, you can leave only arm (and arm64 in case you have explicitly enabled arm64 support) in the targetArchs array which will decrease the size of the produced APK file.

**Comment by Fatme** [comment]
This issue was moved to NativeScript/android-runtime#997
