### ISSUE TITLE
Wont install on iPhone X when doing release builds.

### ISSUE THREAD

**Issue by devjosh-mudbath** [NativeScript/nativescript-cli#3402]
### Did you verify this is a real problem by searching the [NativeScript Forum]

I have searched for this issue everywhere, but have not been able to find other people with the same problem.

### Tell us about the problem
I am not able to perform release builds. It does however work on every other device that I try including:  iPhone 6, iPhone 6S Plus, iPhone 7, heaps of android devices). 
So to be clear the ```tns run --bundle --release```, ```tns build --bundle --release``` does not actually fail. It seems to work perfectly fine with the small caveat of not being able to install on iPhone X.

What gets interesting is that if I use the standard XCode GUI, and XCode CLI build/archive/export process, I can install and run on iPhone X with no problem. Just to reiterate the above, when building with the nativescript cli, the application runs as expected on every device except for iPhone X which it is unable to install on.

### Which platform does your issue occur on?
iOS - IPhone X

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Dependencies: 
```
┌───────────────────────────────────┬──────────┐
│ Plugin                            │ Version  │
│ @angular/animations               │ ~5.2.0   │
│ @angular/common                   │ ~5.2.0   │
│ @angular/compiler                 │ ~5.2.0   │
│ @angular/core                     │ ~5.2.0   │
│ @angular/forms                    │ ~5.2.0   │
│ @angular/http                     │ ~5.2.0   │
│ @angular/platform-browser         │ ~5.2.0   │
│ @angular/platform-browser-dynamic │ ~5.2.0   │
│ @angular/router                   │ ~5.2.0   │
│ @ngrx/core                        │ ^1.2.0   │
│ @ngrx/effects                     │ ~4.1.1   │
│ @ngrx/store                       │ ~4.1.1   │
│ @ngx-translate/core               │ ^8.0.0   │
│ @types/lodash                     │ ~4.14.88 │
│ lodash                            │ ~4.17.4  │
│ moment                            │ ~2.19.3  │
│ nativescript-angular              │ ^5.2.0   │
│ nativescript-barcodescanner       │ ^2.7.5   │
│ nativescript-dialog               │ ^0.1.0   │
│ nativescript-drop-down            │ ^3.2.2   │
│ nativescript-fresco               │ ^3.0.6   │
│ nativescript-geolocation          │ ^4.2.3   │
│ nativescript-loading-indicator    │ ^2.4.0   │
│ nativescript-platform-css         │ ^1.6.5   │
│ nativescript-secure-storage       │ ^2.2.2   │
│ nativescript-ui-sidedrawer        │ ^3.5.0   │
│ nativescript-version-number       │ ^1.1.0   │
│ node-sass                         │ ~4.7.2   │
│ reflect-metadata                  │ ~0.1.10  │
│ rxjs                              │ ~5.5.5   │
│ tns-core-modules                  │ ^3.4.1   │
│ zone.js                           │ ~0.8.18  │
└───────────────────────────────────┴──────────┘
Dev Dependencies:
┌─────────────────────────────┬─────────┐
│ Plugin                      │ Version │
│ typescript                  │ ~2.6.2  │
│ @angular/compiler-cli       │ ~5.2.0  │
│ @ngtools/webpack            │ ~1.9.1  │
│ @types/jasmine              │ ^2.8.4  │
│ babel-traverse              │ 6.4.5   │
│ babel-types                 │ 6.4.5   │
│ babylon                     │ 6.4.5   │
│ copy-webpack-plugin         │ ~4.3.0  │
│ css-loader                  │ ~0.28.7 │
│ extract-text-webpack-plugin │ ~3.0.2  │
│ jasmine-core                │ ^2.8.0  │
│ karma                       │ ^1.7.1  │
│ karma-jasmine               │ ^1.1.1  │
│ karma-nativescript-launcher │ ^0.4.0  │
│ lazy                        │ 1.0.11  │
│ nativescript                │ ~3.4.1  │
│ nativescript-css-loader     │ ~0.26.0 │
│ nativescript-dev-sass       │ ~1.3.5  │
│ nativescript-dev-typescript │ ~0.6.0  │
│ nativescript-dev-webpack    │ ~0.9.1  │
│ nativescript-worker-loader  │ ~0.8.1  │
│ raw-loader                  │ ~0.5.1  │
│ resolve-url-loader          │ ~2.2.1  │
│ sass-loader                 │ ~6.0.6  │
│ tns-platform-declarations   │ ~3.4.0  │
│ uglifyjs-webpack-plugin     │ ~1.1.6  │
│ webpack                     │ ^3.10.0 │
│ webpack-bundle-analyzer     │ ^2.9.1  │
│ webpack-sources             │ ~1.1.0  │
└─────────────────────────────┴─────────┘
```
- Runtime(s): tns-ios 3.4.1

**Comment by devjosh-mudbath** [comment]
I think this has something to do with which provisioning profile is being used to sign the application...

I have managed to replicate using xcodebuild export and setting the wrong export type (development vs enterprise).

Is it possible that using the team id for auto-signing is defaulting to the wrong provisioning profiles? Should I be using an explicit provisioning profile?

**Comment by Fatme** [comment]
Hi @devjosh-mudbath,

Can you please try @rc version of `nativescript`.
```
npm i -g nativescript@rc
```

I'm suspecting this is already fixed in @rc version.

**Comment by devjosh-mudbath** [comment]
Hey @Fatme things area a bit busy at the moment, but will try this again as soon as I can (I re-wrote the CI pipeline to *not* use the nativescript command line for the export). I'm happy for you to close this issue and ill open it again in the future if the issue comes up.
