### ISSUE TITLE
Not all frameworks are included in iOS project

### ISSUE THREAD

**Issue by lini** [NativeScript/nativescript-cli#3405]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript-cli/issues)?

Yes

### Tell us about the problem

When developing a plugin, which references other plugins, not all frameworks are added to the iOS project, which produces an app that will not run on a device.

### Which platform(s) does your issue occur on?

iOS

### Please provide the following version numbers that your issue occurs with:

- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.

Plugin A has Framework A in its `platforms/ios` directory and has a dependency on Plugin B.
Plugin B has Framework B in its `platforms/ios` directory.

When adding Plugin A as a dependency in an app, everything works fine.

However, if we have Plugin C, that has a dependency on Plugin A and we add Plugin C to an app, the app will not run. Opening the xcode project reveals that the native app only has reference to Framework A, but NOT to Framework B.

Adding Plugin B as a peerDepencency to Plugin A will fix this issue, but this workaround is not good for the users, because simply adding Plugin A to an app will cause an NPM warning for a missing peer dependency(Plugin B). We don't want to see these warnings each time `npm install` is run.

Adding Plugin B as a dependency to Plugin C will also fix the issue in the above scenario, but it is simply a hack to avoid the peerDependency warning problem. Each plugin that references Plugin A will also need have a dependence on Plugin B, even though only Plugin A needs it.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Create a plugin that references nativescript-ui-listview. Add the plugin to an app. The app will not run, because `nativescript-ui-listview` iOS framework depends on `nativescript-ui-core` and the latter will not be in the generated xcode project.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#890
