### ISSUE TITLE
How to suppress prompt for anonymous usage

### ISSUE THREAD

**Issue by creaux** [NativeScript/nativescript-cli#3414]
I set up tns to run under docker. Problem is that every time when I run command it is asking again and again for sharing of anonymous usage.

Is there option how to suppress this?

**Comment by Fatme** [comment]
Hey @creaux,

The prompt for sharing of anonymous usage is shown when it is not confirmed or the console is interactive. Once it is confirmed(enabled or disabled), it does not show again.

I suspect that in your case, you're running in isolated environment and that is the reason to see analytics prompt on every command execution. I can suggest you to try to use one of following commands `tns usage-reporting enable` or `tns usage-reporting disable` **before**  executing some command.

**Comment by creaux** [comment]
This is exactly what I was looking for, thanks!
