### ISSUE TITLE
Found peer TypeScript Error : CALL AND RETRY LAST ALLOCATION FAILED - JavaScript heap out of memory

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3421]
_From @jain1977 on March 6, 2018 5:43_

Need Help with following

a) 32 Bit System
b) Created fresh template using tns create --ng (angular)
c) android add as platform
d) tns run command --- Android Emulator Starts ---but it gives this error
e) It is default code only. Not a single word has been written

![image 2018-03-06 at 11 14 21 am](https://user-images.githubusercontent.com/37097515/37015887-ae871458-212f-11e8-826c-0fa3c94a04d9.png)

Executing before prepare hook from nativescript-dev-typescript.js

Found peer TypeScript Error : CALL AND RETRY LAST ALLOCATION FAILED - JavaScript heap out of memory

Unable to apply changes on device : emulator-5554. Error is: TypeScript Compiler failed with exit code 3

Tried to dig on here & stack but no sucess

_Copied from original issue: NativeScript/NativeScript#5494_

**Comment by jain1977** [comment]
Thanks @NickIliev for moving to right thread

**Comment by NickIliev** [comment]
@jain1977 can you try the solution provided [here](https://github.com/NativeScript/nativescript-cli/issues/2168#issuecomment-290101965)

**Comment by jain1977** [comment]
Hi @NickIliev , Based on link you provided I made changes & I set Java Opts based on this post ( https://stackoverflow.com/questions/17369522/set-default-heap-size-in-windows ) , parameters based on original article.

Issue still remains

**Comment by jain1977** [comment]
After trying all the re-installation as well. I tried to modify the "max_old_space_size=2000" to different figures in that the error moves out but another comes in. 

![image 2018-03-11 at 6 57 24 pm](https://user-images.githubusercontent.com/37097515/37253931-39e2288a-255e-11e8-98b6-322769b7264e.png)

**Comment by Plamen5kov** [comment]
Hi @jain1977,
as this problem is not related to the initial one, please open a new issue, following the issue template.
Thank you!

**Comment by RadouaneRoufid** [comment]
Same problem here.
