### ISSUE TITLE
Android: 'tns plugin build' failed when there is no platform/android folder in the plugin

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/nativescript-cli#3431]
Please, provide the details below:
Tell us about the problem:
'tns plugin build' failed for nativescript-dev-less plugin.
'tns run android' failed for an app with nativescript-dev-less plugin added.

Which platform(s) does your issue occur on?
Android

Please provide the following version numbers that your issue occurs with:
4.0.0-PR2018.3.7.8
Runtime(s): tns-android current next

Please tell us how to recreate the issue in as much detail as possible.
1. Clone the nativescript-dev-less repo
   git clone https://github.com/NativeScript/nativescript-dev-less
   tns plugin build
The output of the command is:
   No plugin found at the current directory, or the plugin does not need to have its platforms/android components built into an `.aar`.

2. Create sample app - tns create testApp
    Add nativescript-dev-less plugin in the app - tns plugin add nativescript-dev-less . 
    Run the app - tns run android

The output of the command is:
Unable to apply changes on device: ..... Error is: path must be a string or Buffer.

**Comment by Pip3r4o** [comment]
I'd like to add that the errors thrown are caused by the `nativescript-dev-less` plugin. A plugin with no `platforms/android` dir will be skipped, and should not throw any errors under any circumstances.
