### ISSUE TITLE
Unexpected token   in JSON at position 0

### ISSUE THREAD

**Issue by hussamsindhu** [NativeScript/nativescript-cli#3456]
i get this error while i run $tns doctor or $tns run android when i installed all this every things going fine but next day this issue occur  i uninstall nativescript and install it again but the issue remain the same

and the next thing is on android studio i got this error when i run emulator Emulator: Process finished with exit code -1073741819 (0xC0000005)

this all happen with both at the same time 
i try to run emulator on nativescript but this give me error then i thought first run it on android but this gives error too

**Comment by Fatme** [comment]
Hi @hussamsindhu,

You need to remove `userSettings` file.

On windows the file location is: `C:\Users\<username>\AppData\Roaming\.nativescript-cli\user-settings.json`
On mac OS the file location is `~/.local/share/.nativescript-cli/user-settings.json`

**Comment by hussamsindhu** [comment]
@Fatme thanks man i have solved my problem
