### ISSUE TITLE
IDEProvisioningErrorDomain Code=8

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/nativescript-cli#3461]
Hi, 
until today everything works great. But now I suddenly getting this error. I tried to reinstall certificates and provisioning profiles. It didn't help. Thats really weird. The same error I am getting when I set certificates and provisioning profiles in NativeScript Sidekick...

Error Domain=IDEProvisioningErrorDomain Code=8 "term-size has conflicting provisioning settings." UserInfo={NSLocalizedDescription=term-size has conflicting provisioning settings., NSLocalizedRecoverySuggestion=term-size is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified. Remove the "signingCertificate" entry from your Export Options property list, or switch to manual signing by setting "signingStyle" to "Manual.}

**Comment by NickIliev** [comment]
@b4rtt try opening the built project in XCode and to uncheck the Automatically manage signing box and then selecting the team manually (solution from [here](https://stackoverflow.com/a/42147217/4936697)).
.

**Comment by b4rtt** [comment]
@NickIliev 
When I uncheck automatically manage signing box I am getting this error

Code Signing Error: "skslovanbratislava" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

**Comment by b4rtt** [comment]
Now I am getting this. Thats weird, cuz I have both provisioning profiles with the push notifications feature :-O

Code Signing Error: "skslovanbratislava" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

**Comment by NickIliev** [comment]
@b4rtt make sure that the AppID in your [apple developer console](https://developer.apple.com)  has push notifications enabled. 

Good walkthrough on how to create APNS certificate for Push notification can be found [here](https://medium.com/@ankushaggarwal/generate-apns-certificate-for-ios-push-notifications-85e4a917d522) - the same can be achieved thought NativeScritp Sidekick but you would need to create APNS certificate (Change the certificate type on [step 6](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/create-development-provisioning#procedure)!) and not the standard one (so we could send/receive notifications)

**Comment by b4rtt** [comment]
@NickIliev Thank you for your help but I have this done right. I tried recreate all profiles too but without success.

When I import my provision profile to xcode and build app, it's working and install it to my phone. But when I run "tns run ios" it's still the same.


Error Domain=IDEProvisioningErrorDomain Code=8 "term-size has conflicting provisioning settings." UserInfo={NSLocalizedDescription=term-size has conflicting provisioning settings., NSLocalizedRecoverySuggestion=term-size is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified. Remove the "signingCertificate" entry from your Export Options property list, or switch to manual signing by setting "signingStyle" to "Manual.}

**Comment by b4rtt** [comment]
@NickIliev Oh, magic. Now I am getting this... :-O

`2018-03-16 10:51:00.670 xcodebuild[3907:1283327] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7fc2048b16a0>: Error Domain=IDEFoundationErrorDomain Code=1 "ipatool failed with an exception: #<NoMethodError: undefined method `toolsPath' for nil:NilClass>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:811:in `rawLoadCommands'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:827:in `rpaths'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:258:in `resolveLoadedDylibs'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1422:in `block (2 levels) in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `block in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `new'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2938:in `<main>'" UserInfo={NSLocalizedDescription=ipatool failed with an exception: #<NoMethodError: undefined method `toolsPath' for nil:NilClass>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:811:in `rawLoadCommands'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:827:in `rpaths'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:258:in `resolveLoadedDylibs'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1422:in `block (2 levels) in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `block in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `new'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2938:in `<main>'}
error: exportArchive: ipatool failed with an exception: #<NoMethodError: undefined method `toolsPath' for nil:NilClass>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:811:in `rawLoadCommands'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:827:in `rpaths'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:258:in `resolveLoadedDylibs'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1422:in `block (2 levels) in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `block in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `new'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2938:in `<main>'

Error Domain=IDEFoundationErrorDomain Code=1 "ipatool failed with an exception: #<NoMethodError: undefined method `toolsPath' for nil:NilClass>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:811:in `rawLoadCommands'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:827:in `rpaths'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:258:in `resolveLoadedDylibs'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1422:in `block (2 levels) in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `block in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `new'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2938:in `<main>'" UserInfo={NSLocalizedDescription=ipatool failed with an exception: #<NoMethodError: undefined method `toolsPath' for nil:NilClass>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:811:in `rawLoadCommands'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:827:in `rpaths'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:258:in `resolveLoadedDylibs'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1422:in `block (2 levels) in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1421:in `block in initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1420:in `initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `new'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2287:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2938:in `<main>'}

** EXPORT FAILED **

Unable to apply changes on device: 8daccffea029358d28e40e0d47ca3968cebe57f8. Error is: Command xcodebuild failed with exit code 70.`

**Comment by NickIliev** [comment]
@b4rtt have you managed to resolve the build issue?
Try resetting your projects `platform` folder and rebuilding from scratch.
```
tns platform remove ios
tns platform add ios
tns build ios --release --for-device
```

**Comment by chuckmitchell** [comment]
I have the same problem. Have re-set platforms and node_modules many times.

**Comment by Fatme** [comment]
@chuckmitchell have you managed to resolve your issue?

**Comment by chuckmitchell** [comment]
I did but I don't know how. I think I'm having a lot of problems with signing because I have multiple iOS developer accounts, profiles and certificates on my system. 

I resolved it by nuking everything.

Thanks for checking in.

**Comment by parliament718** [comment]
This error had me stuck for a while but here's what fixed it for me:

First, I created a new  iOS project in xcode with the same name and organization off my nativescript app. For example, if your {N} application identifier is org.nativescript.myapp, create an iOS project with name  ```myapp``` and organization ```org.nativescript```. This brand new project should build and deploy a blank app with the same name to your device without a problem. 

After deploying the blank app, my original app deployed without a problem as well, it simply overwrote the blank installation on the device. I deployed my app by going into platforms/ios and opening the xcodeproj file, selecting my device and hitting run.

**Comment by datanotion** [comment]
Good evening!  We are now seeing this error with NS5.  Was there ever an official fix/solution provided?  We've attempted all the solutions suggested.

**Comment by darkmantle** [comment]
I am also getting this error after attempting all suggestions. It is completely blocking the ability to upload to the app store - any idea of a time frame?

**Comment by KristianDD** [comment]
Hi @darkmantle ,
This issue is quite outdated and the information inside might be misleading and irrelevant. Please open a new issue following the the issue reporting template and might include a log produced by `tns run ios --log trace | tee log.txt`. This will provide us enough information for investigating what exactly happened.
Closing this issue.
