### ISSUE TITLE
[Modal Page][iOS] modalpage showing in fullscreen.

### ISSUE THREAD

**Issue by kamlekar** [NativeScript/nativescript-cli#3462]
Hi,

I am using the modal page to show a custom pop-up. In Android its working fine but in iOS, it's stretching (showing in fullscreen). As per the documentation, this is `by design in iPhone`. Is there any way to get rid of this behavior? or any alternative to show the pop-up?

Also, in iPad, this modal stretch abnormally. Please check the below screenshot.

![image](https://user-images.githubusercontent.com/2201186/37460315-e163d38c-2870-11e8-971b-82286de48ada.png)

Thanks.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#5542
