### ISSUE TITLE
ECONNRESET issue when run tns run android

### ISSUE THREAD

**Issue by fipolhuang** [NativeScript/nativescript-cli#3465]
PS C:\apps\NS_helloworld\helloworld0315> tns run android
Searching for devices...
Starting Android emulator with image Jason
Waiting for emulator device initialization.....
Executing before-liveSync hook from C:\apps\NS_helloworld\helloworld0315\hooks\before-liveSync\nativescript-angular-sync.js
Copying template files...
  - Installing tns-androidInstalling  tns-android
C:\apps\NS_helloworld\helloworld0315
`-- tns-android@3.4.1

  - Installing tns-androidError: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:581:26)

**Comment by NickIliev** [comment]
@fipolhuang try starting the emulator manually from Android AVD and then running the `tns` commands.

**Comment by fipolhuang** [comment]
can not work, the error message is still with the econnreset as blow, if need i install any package or do some configuration?
at exports._errnoException (util.js:1050:11)
at TCP.onread (net.js:581:26)

**Comment by fipolhuang** [comment]
![image](https://user-images.githubusercontent.com/34998022/37512505-51329cbc-293d-11e8-9954-6f6e38be872e.png)

**Comment by NickIliev** [comment]
@fipolhuang from the screenshot above it appears that the emulator was not started before running the command `tns run android`. Try starting the emulator manually before executing the run command.

Another thing you could do is to update your Node.js and NPM as suggested [here](https://discourse.nativescript.org/t/unable-to-create-helloworld-app-for-the-first-time-android/558/5)

**Comment by fipolhuang** [comment]
@NickIliev great thanks for you help,  according to your suggestion, it works fine now.
