### ISSUE TITLE
tsc: command not found

### ISSUE THREAD

**Issue by hussamsindhu** [NativeScript/nativescript-cli#3466]
i have installed native-script version 3.4.3 through npm  that works fine but tsc command did not works in vs code or in any command line interface to run and compile ts files  ?

**Comment by NickIliev** [comment]
@hussamsindhu The CLI command for NativeScript is  **`tns`**.
The command **`tsc`** is for running TypeScript and to be able to run it you need to have TypeScript installed locally or globally
For example:
```
npm i -g typescript
```
