### ISSUE TITLE
[4.0 - RC] tns doctor takes forever

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#3474]
### Tell us about the problem
Tns `tns doctor` command takes forever when CocoaPods is not installed.

Expected: the command reports that CocoaPods is not installed.
Actual: the command gets into an infinite loop and outputs nothing.

### Please provide the following version numbers that your issue occurs with:
```
vchimev@mcsofvchimev tmp  $ node --version
v9.8.0
vchimev@mcsofvchimev tmp  $ npm --version
5.7.1
vchimev@mcsofvchimev tmp  $ tns --version
4.0.0-2018-03-19-11189
```

### Please tell us how to recreate the issue in as much detail as possible.
Delete the CocoaPods' installation folder: `rm -frv ~/.cocoapods/` and execute `tns doctor`.

**Comment by dtopuzov** [comment]
Fixed in 4.0rc.

**Comment by jegesh** [comment]
I'm experiencing this as well, with tns-cli version 4.1.2.

Other specs:
macOS v10.11.6
node 8.9.4
npm 3.10.5

**Comment by dtopuzov** [comment]
@jegesh can you run 
tns doctor --log trace
and paste the output.

**Comment by jegesh** [comment]
I would have to uninstall cocoapods in order to reproduce the problem.  No
promises when I'll get to this
