### ISSUE TITLE
Generate assets for the mobile application

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#3496]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
When creating NativeScript project, it comes with predefined assets (icons and splash screens). At some point all assets should be changed with specific ones for the application. It would be great if CLI allows generation of these images based on a new image.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: Not applicable
- Cross-platform modules: Not applicable
- Runtime(s): Not applicable
- Plugin(s): Not applicable

### Please tell us how to recreate the issue in as much detail as possible.
No

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No

**Comment by rosen-vladimirov** [comment]
The feature is implemented in both `rc` and `next` versions of NativeScript CLI. We have introduced two new commands:
```
$ tns resources generate icons <path to image>
$ tns resources generate splashes <path to image> [--background <color>]
```

In order to get more information how to use both commands, you can use:
```
$ tns help resources generate icons
$ tns help resources generate splashes
```

NOTE: At the moment the generation will work based on the current images in App_Resources, i.e. it will generate the same number of images with the same size as the ones you have in your App_Resources.

**Comment by Natalia-Hristova** [comment]
`<background> is a valid path to an image that will be used as a background of the splashscreen. Defaults to white in case it is not specified. ` 

Is this the current behaviour?
Because I tried with path to image and the result was: `Unable to parse color from string: /.../images/some-bg.png`
And it works when set color as a string e.g. `yellow`

**Comment by Natalia-Hristova** [comment]
This feature is implemented and will be available in the next official release. Can be tested out with the `rc` and `next` versions of `nativescript-cli`

**Comment by tjvantoll** [comment]
@rosen-vladimirov Tried this out and it works great! Just as one quick fyi the new command does not appear in `tns help` at all.

**Comment by akoua** [comment]
@rosen-vladimirov, the new image which I generate have the same name <<icon>> so it's replace my original icon image
