### ISSUE TITLE
Mac access issues EACCES: permission denied

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3507]
_From @peppeg85 on March 29, 2018 10:46_

hello, I'm trying to install native script on high Sierra following the advanced guide I still can't install.
I'm new to the Mac world, I have the common issue eaccess with the command sudo npm i -g native script
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nativescript/docs/html'

I tried also following the guide with nvm, but I still can't make it work. is there a newbie detailed guide to fix this?

_Copied from original issue: NativeScript/NativeScript#5599_

**Comment by NickIliev** [comment]
@peppeg85 you are hitting [this issue](https://github.com/NativeScript/nativescript-cli/issues/1364#issuecomment-168655271).

If you need to install with sudo use the following
```
sudo npm install -g nativescript --unsafe-perm
```

**Comment by Yuzam** [comment]
Did you tried this?
https://discourse.nativescript.org/t/nativescript-create-new-project-failed-eacces-permission-denied-on-macos/7616
