### ISSUE TITLE
`tns resources update` with locked `App_Resources/Android` leaves `Android_Updated`

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#3510]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Running `tns resources update` when `App_Resources/Android` is locked results in a folder named `App_Resources/Android/Android-Updated` .

### Which platform(s) does your issue occur on?
Android

### Please tell us how to recreate the issue in as much detail as possible.
1 Execute `tns run android` in the app folder
2 Open separate command line.
3 Execute `tns resources update`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No

**Comment by Natalia-Hristova** [comment]
This is fixed and will be available in the next official release of nativescript `4.0.0`
