### ISSUE TITLE
Question: Nativescript app store question ??

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/nativescript-cli#3515]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
Hello guys I have  a quick question since I have nowhere to ask, posted already topic on discourse, and stackoverlow but no one is answering...
My question is 
 Im building my app with Nativescript, but When I upload my app to Apple for the review i always have to provide screenshot of this app running on an iPad. So i guess somewhere is some property file you can specify for what default device for App is.

How can I set this ?? In info.plist or some other file ??
### Which platform(s)
iOS

**Comment by NickIliev** [comment]
@markomiljkovic try setting `UIDeviceFamily` in the `info.plist` (info [here](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW11))

Something like:
```
<key>UIDeviceFamily</key>
  <array>
    <integer>2</integer>
  </array>
```

Still closing the issue as it is how-to related and not related to a CLI bug, feature or issue.
