### ISSUE TITLE
tns deploy iOS Error is: Could not install application

### ISSUE THREAD

**Issue by lumayara** [NativeScript/nativescript-cli#3525]
Hi everyone, I am trying to run this command: tns deploy ios --device (Identifier). However am getting always the message: 
```
Skipping prepare.
Searching for devices...
Your application will be deployed only on the device specified by the provided index or identifier.
Skipping package build. No changes detected on the native side. This will be fast!
Installing...
Failed to install /Users/luanafernandes/(path)/App.ipa on device with identifier b00000000000. Error is: Could not install application
```

The phone I have is a iPhone 7 plus and I already deployed this before in another iPhone 7 however is not working right now.
Anyone had this issue?

**Comment by lumayara** [comment]
HI @NickIliev.. No, that's not the real device. I changed it.. 
My Nativescript version:
```
"nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-android": {
      "version": "3.4.2"
    },
    "tns-ios": {
      "version": "3.4.1"
    }
  }
```
<img width="840" alt="screen shot 2018-04-11 at 9 26 36 am" src="https://user-images.githubusercontent.com/8031814/38619845-11dc8338-3d6b-11e8-97c7-c488fb7ed41c.png">

**Comment by Fatme** [comment]
Hi @lumayara,

I'm suspecting that your provision might not include your device. To check that please execute the followings:
1. Connect your  non working device
2. Execute `tns run ios --provision` and send us the output.

**Comment by lumayara** [comment]
Thanks @Fatme !
I ran the command and got the message below, however still no success with this device, still getting a message saying the app could not be installed..
<img width="578" alt="screen shot 2018-04-23 at 10 09 55 am" src="https://user-images.githubusercontent.com/8031814/39132194-45d9198a-46df-11e8-9c98-3c61fd3ca8b3.png">

**Comment by lumayara** [comment]
Hi @Fatme,
Yes. Thank you for this. My device has no provisioning profile. I will download one and see how it goes.
Thank you very much!

**Comment by lumayara** [comment]
It is working now. Thanks for the help.

**Comment by Mountingrest** [comment]
I managed to find the answer https://stackdev.space/questions/commands-for-nativescript-app-deployment-using-tns
