### ISSUE TITLE
iOS logging does not work on multiple simulators

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#3529]
### Tell us about the problem
iOS logging does not work when more than one iOS simulators are running.

### Which platform(s) does your issue occur on?
iOS

### Please tell us how to recreate the issue in as much detail as possible.
1. Execute  `tns create myApp`
2. Run more than one iOS simulators
3. Open your project and add some console.log - For example on click on tap button.
4. Execute `tns run ios`
5. Click the tap button (or execute an action that will trigger the logic with logging)
6. Repeat step 5. for all running simulators.

**Expected behaviour:**
The logs should be shown from all all running simulators.

**Current behaviour:**
The logs are shown only from one of the running simulators.

**Comment by Natalia-Hristova** [comment]
This is fixed and will be available in the next official release of `nativescript`.
