### ISSUE TITLE
Message for tracking in Google Analytics is visible when usage reporting is disabled

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#3536]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
When the usage reporting is disabled  (`tns usage-reporting disable`) the detailed log of CLI (passed `--log trace` to any command) prints messages that information will be send to Google Analytics.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: Not applicable
- Runtime(s): Not applicable
- Plugin(s): Not applicable

### Please tell us how to recreate the issue in as much detail as possible.
1. Disable usage reporting: `$ tns usage-reporting disable`.
2. Execute any command with verbose log, for example: `$ tns prepare android --log trace`.
3. Investigate the logs - you'll see messages that some data will be send to Google Analytics.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No.

NOTE: The problem is only with the logging information, no data is being set in the mentioned case.

**Comment by Natalia-Hristova** [comment]
The message is not seen anymore after reporting is disabled. This fix will be available in the next official release of `nativescript`.
