### ISSUE TITLE
Playground and local build - diffences + possible local usage

### ISSUE THREAD

**Issue by montella1507** [NativeScript/nativescript-cli#3539]
Hello,

i would like to ask how it is possible i can use your Nativescript playground and i will get updated aplication in < 4sec to my device + if i upgrade only style , application has not to be reloaded - HMR is working there.

However, when i build on my own PC (12thread cpu, 32gb ram, 1tera SSD) it takes 30sec to get updates on my device?

I found an issue where are you working on HMR i wonder if u use some kind of HMR in playground already? (alfa version, beta version)?

It is possible to host use the same process like there is in playground for real development process??

i think it is really important to get updates to app in several seconds (and not >30sec)

thanks for your answers

**Comment by dtopuzov** [comment]
Hi @montella1507 

Local livesync should be much faster and 30+ sec is not expected (except first run).
Can you please add more details how you reproduce the issue.

Does it happens on brand new project created with `tns create TestApp --ng`?
Can you also post package.json of your project (the issue might be caused by some plugin).

**Comment by jrz** [comment]
It also happens with a brand new app, mac/ios.  Has been like this for a long time, but it's now annoying the hell out of me.  Looking into reactnative and flutter seems very tempring purely because of the dev-cycle

**Comment by dtopuzov** [comment]
Hi @jrz 

Can you give us more detail on you project?
How fast is html, css or ts change at your side?

For hello-world NG app it should be less then 10 sec for ts changes when app is restarted.
For css or html changes it should even faster.

**Comment by montella1507** [comment]
@dtopuzov  i hvae to agree.. even 5secs is way tooo long time if another framework can do this in 250ms (like React Native, Flutter.io, Fuse tools,..)

**Comment by NickIliev** [comment]
@montella1507  @jrz indeed at this very moment the local builds are supporting livesync and not HMR> the HMR (Hot Reload) functionality is in our plans and is logged as a feature [here](https://github.com/NativeScript/nativescript-cli/issues/3384) - keep track on the issue for updates.
