### ISSUE TITLE
Failed to upgrade to TNS 4.0

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/nativescript-cli#3541]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes
### Tell us about the problem
I just wanted to upgrade my project today to TNS 4.0 but getting following error.
`Command npm install tns-ios@4.0.1 --silent --save-exact --save failed with exit code 254
`### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0

### Please tell us how to recreate the issue in as much detail as possible.
I install and re-install the nativescript. Then trying to create platform but i am unable todo so..

**Comment by Fatme** [comment]
Hi @dotnetdreamer,

Which command are you trying to execute?

**Comment by dotnetdreamer** [comment]
Tns platform add ios

**Comment by Fatme** [comment]
@dotnetdreamer,

Can you execute the command with `--log trace` option and send us the output?
```
tns platform add ios --log trace
```

**Comment by learwebit** [comment]
I also have this problem, and this my log. 

> Loading extensions.
> System information:
> { platform: 'darwin',
>   shell: '/bin/bash',
>   os: 'Darwin h-iMac-sl-myry.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64\n',
>   procArch: 'x64',
>   nodeVer: '8.11.1',
>   npmVer: '5.6.0',
>   nodeGypVer: null,
>   nativeScriptCliVersion: '4.0.0',
>   gitVer: '2.15.1 (Apple Git-101)',
>   dotNetVer: null,
>   javacVersion: '1.8.0_172',
>   adbVer: null,
>   androidInstalled: true,
>   monoVer: null,
>   gradleVer: null,
>   isAndroidSdkConfiguredCorrectly: true,
>   xcodeVer: '9.3.0',
>   xcodeprojLocation: '/usr/local/bin/xcodeproj',
>   itunesInstalled: true,
>   cocoaPodsVer: '1.5.0',
>   isCocoaPodsWorkingCorrectly: true,
>   isCocoaPodsUpdateRequired: false,
>   pythonInfo: { isInstalled: true, isSixPackageInstalled: true } }
> Looking for project in '/Users/miri/Desktop/GitHub/GoIsrael/GoIsrael'
> Project directory is '/Users/miri/Desktop/GitHub/GoIsrael/GoIsrael'.
> Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
>   action: 'Check Local Build Setup',
>   label: 'Starting',
>   customDimensions: {} }
> Initializing analytics statuses.
> Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
> spawn: node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
> Xcode is installed and is configured properly.
> xcodeproj is installed and is configured properly.
> CocoaPods are installed.
> CocoaPods update is not required.
> CocoaPods are configured properly.
> Your current CocoaPods version is newer than 1.0.0.
> Python installed and configured correctly.
> The Python 'six' package is found.
> Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
>   action: 'Check Local Build Setup',
>   label: 'Finished: Is setup correct: true',
>   customDimensions: {} }
> Exec xcodebuild -version | head -n 1 | sed -e 's/Xcode //'
>  stdout: 9.3
> 
>  stderr:
> Creating NativeScript project for the ios platform
> Path: /Users/miri/Desktop/GitHub/GoIsrael/GoIsrael/platforms/ios
> Package: com.webit.GoIsrael
> Name: GoIsrael
> Copying template files...
> ⠋ Installing tns-ios
> spawn: npm "install" "tns-ios@3.4.1" "--silent" "--save-exact" "--save"
> Error: Command npm install tns-ios@3.4.1 --silent --save-exact --save failed with exit code 243
>     at ChildProcess.childProcess.on (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:255:36)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:925:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> Error: Command npm install tns-ios@3.4.1 --silent --save-exact --save failed with exit code 243
>     at ChildProcess.childProcess.on (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:255:36)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:925:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|setup, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|build, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, resources, resources|generate|icons, resources|generate|splashes, resources|update, run, run|android, run|ios, setup, setup|cloud, test, test|android, test|init, test|ios, update, usage-reporting
> Reading help for command 'platform|add'. FileName is 'platform-add.md'.
> # tns platform add

**Comment by TinusJ** [comment]
Is this fixed? I also have the same issue with android

`Error: Command npm.cmd install tns-android@4.0.1 --silent --save-exact --save failed with exit code 1
    at ChildProcess.childProcess.on (C:\Users\Tinus\AppData\Roaming\npm\node_modules\nativescript\lib\node-package-manager.js:255:36)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
Error: Command npm.cmd install tns-android@4.0.1 --silent --save-exact --save failed with exit code 1
    at ChildProcess.childProcess.on (C:\Users\Tinus\AppData\Roaming\npm\node_modules\nativescript\lib\node-package-manager.js:255:36)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)`

**Comment by Fatme** [comment]
Hi @TinusJ,

Unfortunately I was not able to reproduce the problem. Any repro steps will be great appreciated.

**Comment by TinusJ** [comment]
Hi, the issue is not with nativescript cli or the tns command. 

The issue is with npm  [see](https://stackoverflow.com/a/50269601/4712391). This fixed the isse

**Comment by mudlabs** [comment]
I'm getting the same result _(i.e. exit code 243)_.

I've got more details here -> [NativeScript Forum: Can’t add platforms after updating to {N} 4.1.0](https://discourse.nativescript.org/t/cant-add-platforms-after-updating-to-n-4-1-0/6427).

Can successfully create and build `sampleProject`, so I'm thinking there's some conflict coming from my the existing application.

**Comment by dlcole** [comment]
I'm all of a sudden hitting the same error trying to add either ion or android: 

`Command npm install tns-android@4.1.3 --silent --save-exact --save failed with exit code 254`

I tried upgrading npm to the latest version (6.3.0) but the problem remains

**Comment by dlcole** [comment]
I tried removing/adding platforms to other projects, and that works OK.  So it seems this error is somehow related to my current project, but have no idea what the problem may be.

**Comment by dtopuzov** [comment]
Hi @dlcole 

Can you please post package.json of your project?

**Comment by dlcole** [comment]
And now it's working again...  Not sure what changed, but at least I'm up and running.

**Comment by gustavost26** [comment]
> I'm all of a sudden hitting the same error trying to add either ion or android:
> 
> `Command npm install tns-android@4.1.3 --silent --save-exact --save failed with exit code 254`
> 
> I tried upgrading npm to the latest version (6.3.0) but the problem remains

I'm having the same problem and I can not resolve it.

**Comment by rosen-vladimirov** [comment]
Hey @gustavost26 , can you please check which is your CLI version - just execute `tns --version`. In case it is not the latest one (4.2.4), can you please try upgrading it: `npm i -g nativescript` and see if this will resolve the issue on your side?

**Comment by rosen-vladimirov** [comment]
In the latest versions of nativescript-cli, we've changed the way tns-ios and tns-android packages are used - we do not install them via `npm install` anymore, so this issue is no longer reproducible.
