### ISSUE TITLE
Your project have installed babel-traverse version null but Android platform requires version ^6.4.5

### ISSUE THREAD

**Issue by sarvagayatri** [NativeScript/nativescript-cli#3546]
Done commands::
npm install nativescript -g
removed platform, hooks and nodemodules folders
tns platform add android
and i got error as--
**Copying template files...
- Installing tns-android
C:\ProjectFolder
`-- tns-android@4.0.1

Your project have installed babel-traverse version null but Android platform requires version ^6.4.5.**

**Comment by Fatme** [comment]
Hi @sarvagayatri,

Can you please execute the command with `--log trace` and send us the produced output?

**Comment by rosen-vladimirov** [comment]
Closing as the code that throws this error is no longer in CLI's repo. You can safely use any version of `babel-traverse` in your app.
