### ISSUE TITLE
Problem live syncing on iOS

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-cli#3548]
#Using NS 4.0 with iOS 4.0.1

Livesyncing doesn't seem to work.

This is on iOS 11.3 device.

Sometimes Safari opens and the url is set to 127.0.0.1 

Sometimes `tns run iOS` does a successful build and then goes to the command prompt - sometimes it works. Seems to be a timing issue.

`Searching for devices...
Skipping prepare.
Refreshing application...
Error while trying to start application dev.asrock.test on device 6c2738837caf832490dc687df75b326c20de142b. Error is: Could not start service com.apple.debugserver
Unable to start application dev.asrock.test on device 6c2738837caf832490dc687df75b336c20de142b. Try starting it manually.
Successfully synced application dev.asrock.test on device 6c2738837caf832490dc687df75b326c20de142b.
Executing before-watchPatterns hook from /Users/asrock/Documents/subs_test/hooks/before-watchPatterns/nativescript-dev-typescript.js
Executing before-watch hook from /Users/asrock/Documents/subs_test/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
6:17:03 PM - Starting compilation in watch mode...

6:17:05 PM - Compilation complete. Watching for file changes.

Unzipping LiveSync folder. This could take a while...
Unzipped 385 entries in 3030.322909ms.
Retrieving resting unlock: 0
Retrieving resting unlock: 0
`

**Comment by Fatme** [comment]
Hi @erjdriver,

Can you please try to restart your device and try to execute the command again?
>Error is: Could not start service com.apple.debugserver`

The one reason to see the error above can be in case when some sockets on your device are in unexpected state. The restart of device sometimes helps.

Another thing I can suggest you is to check if `Sync with this iPhone over Wi-Fi` option is selected in your `iTunes`. You need to do the followings:
1. Open your iTunes
2. Select your connected device
3. Go to options -> `Sync with this iPhone over Wi-Fi`
4. Uncheck the option if selected.

**Comment by erjdriver** [comment]
Did both...still getting

`Searching for devices...
Skipping prepare.
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Refreshing application...
Error while trying to start application dev.asrock.com on device 6c2738837caf832490dc687df75b336c20de142b. Error is: Could not start service com.apple.debugserver
Unable to start application dev.asrock.com on device 6c2738837caf832490dc687df75b336c20de142b. Try starting it manually.
Successfully synced application dev.asrock.com on device 6c2738837caf832490dc687df75b336c20de142b.
Executing before-watchPatterns hook from /Users/asrock/Documents/subs_test/hooks/before-watchPatterns/nativescript-dev-typescript.js
Executing before-watch hook from /Users/asrock/Documents/subs_test/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
11:39:32 AM - Starting compilation in watch mode...



11:39:33 AM - Compilation complete. Watching for file changes.
`


I have to start the app manually by tapping on the icon and then I get this

`Unzipping LiveSync folder. This could take a while...
Unzipped 13 entries in 74.215055ms.
tns_modules folder not livesynced. Using tns_modules from the already deployed bundle...
Retrieving resting unlock: 0
`

**Comment by Fatme** [comment]
Hi @erjdriver,

Sorry to hear that. Can you please execute the command with `--log trace` and send us the output?

**Comment by erjdriver** [comment]
I've attached the trace file.

I also got this on console

`Project successfully created.
mac:subs_test asrock$ tns run ios --log trace >temp.txt
2018-04-26 19:18:22.730 xcodebuild[4764:214405]  iPhoneConnect: ## Unable to mount developer disk image, (Error Domain=com.apple.dtdevicekit Code=601 "Could not locate device support files." UserInfo={NSLocalizedRecoverySuggestion=This iPhone 6 is running iOS 11.3.1 (15E302), which may not be supported by this version of Xcode., DeviceType=iPhone7,2, NSLocalizedDescription=Could not locate device support files.}) {
    DeviceType = "iPhone7,2";
    NSLocalizedDescription = "Could not locate device support files.";
    NSLocalizedRecoverySuggestion = "This iPhone 6 is running iOS 11.3.1 (15E302), which may not be supported by this version of Xcode.";
}
2018-04-26 19:18:36.305 xcodebuild[4881:215109] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/3k/l203s_9s60778q7jd3qj533w0000gn/T/substest_2018-04-26_19-18-36.304.xcdistributionlogs'.`


[temp.txt](https://github.com/NativeScript/nativescript-cli/files/1953339/temp.txt)

**Comment by Fatme** [comment]
Hi @erjdriver,

Thank you for sending the logs.

> Unable to mount developer disk image

In case when {N} CLI is not able to mount developer disk image on device, application cannot be started automatically on device. This is the reason to see this error:
```
Unable to start application dev.asrock.com on device 6c2738837caf832490dc687df75b336c20de142b. Try starting it manually.
```

From the provided log I noticed you're using `xcodeVer: '9.2.0'` but your device is iOS 11.3.1. You need to update your xcode version to 9.3.0 in order to fix the problem.
