### ISSUE TITLE
Ctrl+C doesn't stop 'tns run android'

### ISSUE THREAD

**Issue by vaindil** [NativeScript/nativescript-cli#3551]
### Which platform(s) does your issue occur on?
Windows 10 x64

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): `tns-android`: 4.0.1
- Nodejs: 8.11.1

### Please tell us how to recreate the issue in as much detail as possible.
I run projects using `tns run android`, which works fine. The problem is that I cannot stop the process once it's started. `Ctrl+C` causes the below output, but it stops there and never continues. I have to manually kill the node process via Task Manager to actually make it stop.

```
Executing after-watch hook from C:\fakepath\my-drawer-ng\hooks\after-watch\nativescript-dev-sass.js
Stopping nativescript-dev-sass watcher
Executing after-watch hook from C:\fakepath\my-drawer-ng\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from C:\fakepath\my-drawer-ng\hooks\after-watch\nativescript-dev-webpack.js
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

This happens with a fresh clone of [NativeScript/template-drawer-navigation-ng](https://github.com/NativeScript/template-drawer-navigation-ng). Specifically, I can reproduce it with these commands:

```
tns create my-drawer-ng --template https://github.com/NativeScript/template-drawer-navigation-ng
cd my-drawer-ng
tns build android
tns run android
```
Let the emulator start up, then hit `Ctrl+C`. The process won't stop.

**Comment by Fatme** [comment]
Hi @vaindil,

Thank you for reporting this issue.
Actually the problem occurs when `nativescript-dev-sass` plugin is added in the application. We investigated the problem and working on the fix.

I'm going to close this thread due to duplication. You can track the progress on the problem in the related issue.

Duplicated to:
https://github.com/NativeScript/nativescript-dev-sass/issues/76
