### ISSUE TITLE
Build error on Android with NS 4.0 (Android)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-cli#3552]
Getting the following build error:

NS 4.0, Core 4.0 and Android 4.0.1

I ran `tns run android`

I think the problem might have to do with the installed Android sdk. I've got 23 installed and would like to stick with it.

`/Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
    
/Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values/values.xml:252:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values/values.xml:252:5-69: AAPT: error: resource android:attr/font not found.
    
/Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values/values.xml:252:5-69: AAPT: error: resource android:attr/fontWeight not found.
`

Here's the full build output
[temp.txt](https://github.com/NativeScript/nativescript-cli/files/1957916/temp.txt)

**Comment by dtopuzov** [comment]
Hi @erjdriver 

Can you reproduce the same issue when you create brand new project:
```
tns create TestApp
tns run android
```

**Comment by erjdriver** [comment]
That works fine (pls see attached logs)
[temp.txt](https://github.com/NativeScript/nativescript-cli/files/1959126/temp.txt)

The original project I'm working with is a TS project.

I did a `tns platform clean android` and am still getting it in my main project.

Going back to the original temp.txt file submitted with my previous post - the first error seems to be 

`Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.`

and then

`Users/asrock/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/660efc19de91dbab5fb6f7640d14424a/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.`

Seems to be platform 26 reference - I don't have it installed (I can't remember but installing 24+ causes some problems).

**Comment by erjdriver** [comment]
I installed sdk 26 and that fixed the problem.

Thanks.
