### ISSUE TITLE
syncAllFiles should ignore ts files

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#3555]
I am using the the very last cli.

I am using npm ```file:``` to develop my plugins within my app.
I run my app with ```--syncAllFiles```
Now whenever i modify the ts file i get a ```Successfully transferred myfile.ts```
Obviously this is not useful plus it makes dev slow because i have to wait for it to finish for my actual js file to get transfered (after tsc has run).
So it would be nice for ts files to be ignored with ```--syncAllFiles```

BTW: is there a way to automatically ```tsc``` on plugin ts file change?

Thanks

**Comment by Fatme** [comment]
Hi @farfromrefug,

Are you using NativeScript version 4.0.0? To check it just execute `tns --version`.

**Comment by farfromrefug** [comment]
@Fatme i use 4.1.0-2018-04-18-11407

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug , 
You can try installing latest nativescript-dev-typescript, that should resolve this issue. Can you give it a try and inform us if it works?

**Comment by farfromrefug** [comment]
@rosen-vladimirov I can confirm that it is resolved in 0.7.4!!!!

Thanks!
