### ISSUE TITLE
Running npm uninstall runs postinstall.js

### ISSUE THREAD

**Issue by dolanmiu** [NativeScript/nativescript-cli#3559]
I ran `npm uninstall`, it runs `node postinstall.js` :

```
C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile>npm uninstall tns-android --save

> nativescript-dev-webpack@0.9.1 postinstall C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\node_modules\nativescript-dev-webpack
> node postinstall.js
```

From https://docs.npmjs.com/misc/scripts, I can see that:

```
install, postinstall: Run AFTER the package is installed.
```

**Comment by NickIliev** [comment]
@dolanmiu note that the runtime modules is not exactly NPM module and the NativeScript CLI has provided a specific commands to add and remove the runtimes (both iOS and Android)

adding Android runtime
```
tns platform add android
```

removing Android runtime
```
tns platform remove android
```

adding a specific version 
```
tns platform add android@next // or specific version e.g @4.1.1
```
