### ISSUE TITLE
Command xcodebuild failed with exit code 65.

### ISSUE THREAD

**Issue by ahtishamashraf** [NativeScript/nativescript-cli#3565]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes 
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
Command xcodebuild failed with exit code 65.
### Which platform(s) does your issue occur on?
iOS/Android/Both
iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)
tns-version 4.0.0
package.json 

{
  "description": "App Desc",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.app.appname",
    "tns-android": {
      "version": "3.3.1"
    },
    "tns-ios": {
      "version": "4.0.1"
    }
  },
  "dependencies": {
    "nativescript-drop-down": "^3.2.3",
    "nativescript-filter-select": "^1.2.6",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-screenshot": "0.0.2",
    "nativescript-theme-core": "^1.0.4",
    "tns-core-modules": "^3.4.1"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11"
  },
  "author": "ZOR"
}

### Please tell us how to recreate the issue in as much detail as possible.
tns run ios --provision <profile id>

ends with 
** BUILD FAILED **

Unable to apply changes on device: <device uuid> . Error is: Command xcodebuild failed with exit code 65.
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.
Code is working Okay with the Emulator , Issue arises when i try to deploy on the device, tried sidekick too but same error there.

**Comment by Fatme** [comment]
Hi @ahtishamashraf,

It seems like your device is not included in your provision. Can you execute the followings:
1. Connect your non working device
2. Execute `tns run ios --provision` command and send us the output.

**Comment by ahtishamashraf** [comment]
I have managed to run it on my device using the Same Provisioning Profile using Nativescript Sidekick

**Comment by Fatme** [comment]
@ahtishamashraf,

Sorry for the late reply.
It's strange the Sidekick works with the same provision but {N} CLI fails. Actually Sidekick calls {N} CLI logic to build the application.
I'll close this issue. Feel free to write here or open an another in case you have some problems.

**Comment by snq** [comment]
tns build ios --clean solved the issue for me

**Comment by xDmv** [comment]
2019-02-10 22:02:05.234 xcodebuild[75023:1277395]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x7ffe821e2ad0; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2019-02-10 22:02:05.235 xcodebuild[75023:1277395]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in." UserInfo={payload=<CFBasicHash 0x7ffe82256290 [0x7ffface1bb30]>{type = mutable dict, count = 9,
entries =>
	0 : responseId = <CFString 0x7ffe8224d4e0 [0x7ffface1bb30]>{contents = "f7d97feb-67c5-4e07-999b-71031ed03691"}
	2 : <CFString 0x7fffacd3eb98 [0x7ffface1bb30]>{contents = "protocolVersion"} = QH65B2
	3 : <CFString 0x7ffe822558f0 [0x7ffface1bb30]>{contents = "requestUrl"} = <CFString 0x7ffe8224f140 [0x7ffface1bb30]>{contents = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action"}
	6 : <CFString 0x7ffe822564c0 [0x7ffface1bb30]>{contents = "userLocale"} = en_US
	8 : resultCode = <CFNumber 0x44c37 [0x7ffface1bb30]>{value = +1100, type = kCFNumberSInt64Type}
	9 : userString = <CFString 0x7ffe82255c30 [0x7ffface1bb30]>{contents = "Your session has expired.  Please log in."}
	10 : <CFString 0x7ffe80404520 [0x7ffface1bb30]>{contents = "resultString"} = <CFString 0x7ffe82237fe0 [0x7ffface1bb30]>{contents = "authentication.failed"}
	11 : httpCode = <CFNumber 0xc837 [0x7ffface1bb30]>{value = +200, type = kCFNumberSInt64Type}
	12 : <CFString 0x7ffe82288660 [0x7ffface1bb30]>{contents = "creationTimestamp"} = <CFString 0x7ffe822558a0 [0x7ffface1bb30]>{contents = "2019-02-10T20:02:05Z"}
}
, NSLocalizedDescription=Your session has expired.  Please log in.}
2019-02-10 22:02:05.466 xcodebuild[75023:1277395]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x7ffe821e3d00; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2019-02-10 22:02:05.466 xcodebuild[75023:1277395]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in." UserInfo={payload=<CFBasicHash 0x7ffe82314730 [0x7ffface1bb30]>{type = mutable dict, count = 9,
entries =>
	0 : responseId = <CFString 0x7ffe821bb540 [0x7ffface1bb30]>{contents = "f3b31986-3f8c-4383-9c32-7d4f96e2ad2b"}
	2 : <CFString 0x7fffacd3eb98 [0x7ffface1bb30]>{contents = "protocolVersion"} = QH65B2
	3 : <CFString 0x7ffe821bc690 [0x7ffface1bb30]>{contents = "requestUrl"} = <CFString 0x7ffe821bc6d0 [0x7ffface1bb30]>{contents = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action"}
	6 : <CFString 0x7ffe821bb4a0 [0x7ffface1bb30]>{contents = "userLocale"} = en_US
	8 : resultCode = <CFNumber 0x44c37 [0x7ffface1bb30]>{value = +1100, type = kCFNumberSInt64Type}
	9 : userString = <CFString 0x7ffe821b8b40 [0x7ffface1bb30]>{contents = "Your session has expired.  Please log in."}
	10 : <CFString 0x7ffe821c3f00 [0x7ffface1bb30]>{contents = "resultString"} = <CFString 0x7ffe82317fc0 [0x7ffface1bb30]>{contents = "authentication.failed"}
	11 : httpCode = <CFNumber 0xc837 [0x7ffface1bb30]>{value = +200, type = kCFNumberSInt64Type}
	12 : <CFString 0x7ffe821c8170 [0x7ffface1bb30]>{contents = "creationTimestamp"} = <CFString 0x7ffe82317670 [0x7ffface1bb30]>{contents = "2019-02-10T20:02:05Z"}
}
, NSLocalizedDescription=Your session has expired.  Please log in.}
2019-02-10 22:02:05.703 xcodebuild[75023:1277395]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x7ffe82313610; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2019-02-10 22:02:05.703 xcodebuild[75023:1277395]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in." UserInfo={payload=<CFBasicHash 0x7ffe820ef080 [0x7ffface1bb30]>{type = mutable dict, count = 9,
entries =>
	0 : responseId = <CFString 0x7ffe82288660 [0x7ffface1bb30]>{contents = "74db59a4-8936-4c82-bfbc-e7a7a46d6072"}
	2 : <CFString 0x7fffacd3eb98 [0x7ffface1bb30]>{contents = "protocolVersion"} = QH65B2
	3 : <CFString 0x7ffe82238d40 [0x7ffface1bb30]>{contents = "requestUrl"} = <CFString 0x7ffe8223b070 [0x7ffface1bb30]>{contents = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action"}
	6 : <CFString 0x7ffe820ef810 [0x7ffface1bb30]>{contents = "userLocale"} = en_US
	8 : resultCode = <CFNumber 0x44c37 [0x7ffface1bb30]>{value = +1100, type = kCFNumberSInt64Type}
	9 : userString = <CFString 0x7ffe820f0200 [0x7ffface1bb30]>{contents = "Your session has expired.  Please log in."}
	10 : <CFString 0x7ffe820ed5a0 [0x7ffface1bb30]>{contents = "resultString"} = <CFString 0x7ffe820f7260 [0x7ffface1bb30]>{contents = "authentication.failed"}
	11 : httpCode = <CFNumber 0xc837 [0x7ffface1bb30]>{value = +200, type = kCFNumberSInt64Type}
	12 : <CFString 0x7ffe820ef7e0 [0x7ffface1bb30]>{contents = "creationTimestamp"} = <CFString 0x7ffe8223b120 [0x7ffface1bb30]>{contents = "2019-02-10T20:02:05Z"}
}
, NSLocalizedDescription=Your session has expired.  Please log in.}
2019-02-10 22:02:06.542 xcodebuild[75023:1277454]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x7ffe82240e60; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2019-02-10 22:02:06.542 xcodebuild[75023:1277454]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in." UserInfo={payload=<CFBasicHash 0x7ffe822aac70 [0x7ffface1bb30]>{type = mutable dict, count = 9,
entries =>
	0 : responseId = <CFString 0x7ffe822aa330 [0x7ffface1bb30]>{contents = "dcd3907e-ef92-4e00-ba13-fa19ac7cc347"}
	2 : <CFString 0x7fffacd3eb98 [0x7ffface1bb30]>{contents = "protocolVersion"} = QH65B2
	3 : <CFString 0x7ffe822aa210 [0x7ffface1bb30]>{contents = "requestUrl"} = <CFString 0x7ffe822aa250 [0x7ffface1bb30]>{contents = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action"}
	6 : <CFString 0x7ffe82041d50 [0x7ffface1bb30]>{contents = "userLocale"} = en_US
	8 : resultCode = <CFNumber 0x44c37 [0x7ffface1bb30]>{value = +1100, type = kCFNumberSInt64Type}
	9 : userString = <CFString 0x7ffe822aa720 [0x7ffface1bb30]>{contents = "Your session has expired.  Please log in."}
	10 : <CFString 0x7ffe8223af10 [0x7ffface1bb30]>{contents = "resultString"} = <CFString 0x7ffe82041b10 [0x7ffface1bb30]>{contents = "authentication.failed"}
	11 : httpCode = <CFNumber 0xc837 [0x7ffface1bb30]>{value = +200, type = kCFNumberSInt64Type}
	12 : <CFString 0x7ffe82041ba0 [0x7ffface1bb30]>{contents = "creationTimestamp"} = <CFString 0x7ffe82041b70 [0x7ffface1bb30]>{contents = "2019-02-10T20:02:06Z"}
}
, NSLocalizedDescription=Your session has expired.  Please log in.}
2019-02-10 22:02:06.788 xcodebuild[75023:1277454]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x7ffe8223ccd0; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2019-02-10 22:02:06.788 xcodebuild[75023:1277454]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in." UserInfo={payload=<CFBasicHash 0x7ffe82357090 [0x7ffface1bb30]>{type = mutable dict, count = 9,
entries =>
	0 : responseId = <CFString 0x7ffe8233a0d0 [0x7ffface1bb30]>{contents = "064a02fd-120c-492a-9a8e-2f87d73057fd"}
	2 : <CFString 0x7fffacd3eb98 [0x7ffface1bb30]>{contents = "protocolVersion"} = QH65B2
	3 : <CFString 0x7ffe82355930 [0x7ffface1bb30]>{contents = "requestUrl"} = <CFString 0x7ffe82355970 [0x7ffface1bb30]>{contents = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action"}
	6 : <CFString 0x7ffe82355d20 [0x7ffface1bb30]>{contents = "userLocale"} = en_US
	8 : resultCode = <CFNumber 0x44c37 [0x7ffface1bb30]>{value = +1100, type = kCFNumberSInt64Type}
	9 : userString = <CFString 0x7ffe82358360 [0x7ffface1bb30]>{contents = "Your session has expired.  Please log in."}
	10 : <CFString 0x7ffe82355680 [0x7ffface1bb30]>{contents = "resultString"} = <CFString 0x7ffe8234aa90 [0x7ffface1bb30]>{contents = "authentication.failed"}
	11 : httpCode = <CFNumber 0xc837 [0x7ffface1bb30]>{value = +200, type = kCFNumberSInt64Type}
	12 : <CFString 0x7ffe82358130 [0x7ffface1bb30]>{contents = "creationTimestamp"} = <CFString 0x7ffe82358100 [0x7ffface1bb30]>{contents = "2019-02-10T20:02:06Z"}
}
, NSLocalizedDescription=Your session has expired.  Please log in.}
2019-02-10 22:02:07.028 xcodebuild[75023:1277454]  DVTPortal: Service '<DVTPortalViewDeveloperService: 0x7ffe82358f70; action='viewDeveloper'>' encountered an unexpected result code from the portal ('1100')
2019-02-10 22:02:07.028 xcodebuild[75023:1277454]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in." UserInfo={payload=<CFBasicHash 0x7ffe82358020 [0x7ffface1bb30]>{type = mutable dict, count = 9,
entries =>
	0 : responseId = <CFString 0x7ffe82355ff0 [0x7ffface1bb30]>{contents = "63011692-03ec-422f-98fc-3d70e24a8491"}
	2 : <CFString 0x7fffacd3eb98 [0x7ffface1bb30]>{contents = "protocolVersion"} = QH65B2
	3 : <CFString 0x7ffe81ed6290 [0x7ffface1bb30]>{contents = "requestUrl"} = <CFString 0x7ffe8234a1d0 [0x7ffface1bb30]>{contents = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action"}
	6 : <CFString 0x7ffe821088a0 [0x7ffface1bb30]>{contents = "userLocale"} = en_US
	8 : resultCode = <CFNumber 0x44c37 [0x7ffface1bb30]>{value = +1100, type = kCFNumberSInt64Type}
	9 : userString = <CFString 0x7ffe8233bea0 [0x7ffface1bb30]>{contents = "Your session has expired.  Please log in."}
	10 : <CFString 0x7ffe82334170 [0x7ffface1bb30]>{contents = "resultString"} = <CFString 0x7ffe8210dd30 [0x7ffface1bb30]>{contents = "authentication.failed"}
	11 : httpCode = <CFNumber 0xc837 [0x7ffface1bb30]>{value = +200, type = kCFNumberSInt64Type}
	12 : <CFString 0x7ffe81a6d680 [0x7ffface1bb30]>{contents = "creationTimestamp"} = <CFString 0x7ffe821049e0 [0x7ffface1bb30]>{contents = "2019-02-10T20:02:06Z"}
}
, NSLocalizedDescription=Your session has expired.  Please log in.}
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
/Users/admin/Library/Developer/Xcode/DerivedData/Wellcome-chrbtfpoiwwmukhitqqmkkjekkxz/Build/Intermediates.noindex/ArchiveIntermediates/Wellcome/IntermediateBuildFilesPath/Wellcome.build/Debug-iphoneos/Wellcome.build/Script-C97FD7AC1ADE5369004DB2A4.sh: line 2: 75069 Abort trap: 6           "$SRCROOT/internal/nativescript-pre-build"
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build systemnote: Planning buildnote: Constructing build description
** ARCHIVE FAILED **

Unable to apply changes on device: 2234f1c5b7a14ecb76cb8978228bc2ca01bd60f4. Error is: Command xcodebuild failed with exit code 65.

Help me

**Comment by xDmv** [comment]
Xcode version 10.1
macOS Higth Sierra version 10.13.6

**Comment by kaige11** [comment]
run `tns build ios --clean --log trace` first ，if the log trace is related to some plugin, use whose latest version in the package.json file , run `npm install`, than run `tns build ios --clean --log trace` again.

if it not work, run `tns prepare ios --release` and open `{app-name}/platforms/ios/{app-name}.xcworkspace` file with xcode , try run it, xcode will tell you where is the problem.

**Comment by orl123124** [comment]
(1 failure)
Command xcodebuild failed with exit code 65
Error: Command xcodebuild failed with exit code 65
    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:147:28)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:120:21)
    at XcodebuildCommandService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:28:30)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by orl123124** [comment]
I can't solve this issue

tns build ios --clean --log trace
:(

(1 failure)
Command xcodebuild failed with exit code 65
Error: Command xcodebuild failed with exit code 65
    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:147:28)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:120:21)
    at XcodebuildCommandService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:28:30)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by JavierAcevedoC** [comment]
** BUILD FAILED **

Command xcodebuild failed with exit code 65
Error: Command xcodebuild failed with exit code 65
    at Errors.failWithOptions (/Users/macbook/Development/point/node_modules/nativescript/lib/common/errors.js:147:28)
    at Errors.fail (/Users/macbook/Development/point/node_modules/nativescript/lib/common/errors.js:120:21)
    at XcodebuildCommandService.<anonymous> (/Users/macbook/Development/point/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:28:30)
    at Generator.throw (<anonymous>)
    at rejected (/Users/macbook/Development/point/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE

**Comment by vidhyasgr** [comment]
> ** BUILD FAILED **
> 
> Command xcodebuild failed with exit code 65
> Error: Command xcodebuild failed with exit code 65
> at Errors.failWithOptions (/Users/macbook/Development/point/node_modules/nativescript/lib/common/errors.js:147:28)
> at Errors.fail (/Users/macbook/Development/point/node_modules/nativescript/lib/common/errors.js:120:21)
> at XcodebuildCommandService. (/Users/macbook/Development/point/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:28:30)
> at Generator.throw ()
> at rejected (/Users/macbook/Development/point/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:5:65)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> npm ERR! code ELIFECYCLE

I get the same error. Do you guys have any solution? "Applications" folder is already created.

**Comment by madmas** [comment]
Hi @vidhyasgr , that is a pretty generic error, the interesing part of the output is probably _above_ the ** BUILD FAILED **

Also, some information about the project would be handy: Versions of XCode and NativeScript, libraries, etc.

**Comment by NathanaelA** [comment]
HI, all!    Please read https://nativescript.org/blog/nativescript-6-7-xcode-compatibility/ and then after you verify XCode and NS CLI versions, let us know if you are still having issues and what versions of BOTH you are using?

**Comment by adideas** [comment]
HI !

Here is what helped me 
- XCODE 13.3.1
- NativeScript 8.0.2 cli
- Platform IOS "6.5.2"

STEP 1 (build.xcconfig)

```
// xcode 13
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited)
$(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))

IPHONEOS_DEPLOYMENT_TARGET = 12.0
```


STEP 2 (Podfile)

```
pod 'CocoaAsyncSocket'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] ='NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end

IPHONEOS_DEPLOYMENT_TARGET = 12.0
```
