### ISSUE TITLE
Login without browser

### ISSUE THREAD

**Issue by Jai-Krish** [NativeScript/nativescript-cli#3566]
`tns login` cannot be used in a CLI environment like in a Docker container which doesn't have a browser. Is there any other way for authentication ?

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): tns-android: 4.0.1
- Plugin(s): 4.0.0

**Comment by rosen-vladimirov** [comment]
Hey @Jai-Krish ,
You can use `tns dev-login <username> <password>` in such environments. This will allow you to use cloud builds. Can you give it a try and confirm if it works on your side?

**Comment by Jai-Krish** [comment]
Thank you @rosen-vladimirov, It works!!! :+1:
