### ISSUE TITLE
EXPORT FAILED  fse.node has conflicting provisioning settings

### ISSUE THREAD

**Issue by iosdeveloper1001** [NativeScript/nativescript-cli#3568]
I am using a latest version of Cli i.e **4.0.1**
I am not able to use `tns run ios` command for my project and getting below error.

error: exportArchive: fse.node has conflicting provisioning settings.

Error Domain=IDEProvisioningErrorDomain Code=8 "fse.node has conflicting provisioning settings." UserInfo={NSLocalizedDescription=fse.node has conflicting provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified.Remove the "signingCertificate" entry from your Export Options property list, or switch to manual signing by setting "signingStyle" to "Manual.}

**Comment by willzarem** [comment]
Same error here:

```
018-05-22 12:08:34.361 xcodebuild[30599:2756740] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7ff39660aea0>: Error Domain=IDEDistri
butionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSig
ningAssetStepUnderlyingErrors=(
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"ios-device-lib has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=ios-device-lib h
as conflicting provisioning settings., NSLocalizedRecoverySuggestion=ios-device-lib is automatically signed for distribution, but a conflicting code signing id
entity iPhone Distribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual sig
ning by setting \"signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"adb has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=adb has conflicting provisi
oning settings., NSLocalizedRecoverySuggestion=adb is automatically signed for distribution, but a conflicting code signing identity iPhone Distribution has be
en manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"signingStyle\"
to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fsevents.o has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fsevents.o has confl
icting provisioning settings., NSLocalizedRecoverySuggestion=fsevents.o is automatically signed for distribution, but a conflicting code signing identity iPhon
e Distribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by sett
ing \"signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicti
ng provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Dist
ribution has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"
signingStyle\" to \"Manual.}",
    "Error Domain=IDEProvisioningErrorDomain Code=8 \".node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=.node has conflicting pro
visioning settings., NSLocalizedRecoverySuggestion=.node is automatically signed for distribution, but a conflicting code signing identity iPhone Distribution
has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"signingSt
yle\" to \"Manual.}"
```

**Comment by mathias-mcb** [comment]
Hey there,

**Comment by NickIliev** [comment]
@mathias-mcb try the solution suggested in the error log 

```
or switch to manual signing by setting "signingStyle" to "Manual.}
```

Basically do [this](https://stackoverflow.com/a/42147217/4936697) - open the build project in XCode and set the signing to manual.

**Comment by surdu** [comment]
@NickIliev Tried your solutions but I have 2 problems:

1. for some reason, the .app is not generated anymore: 
```
Unable to apply changes on device: 5784c839f6bde322f71ed053979b3459900e92d5. Error is: ENOENT: no such file or directory, stat '/Us
ers/nicolae.surdu/work/capango-seeker/platforms/ios/build/device/capangoseeker.app'.
```
2. once you remove the platforms folder, you'll have to disable automatic signing again.

**Comment by pajohns** [comment]
I've been battling with this issue for the last 8 hours. I managed to work around it so that I can at least run the app on my phone, but it'd be great if there were a better solution. 

1. Build your app and run the `tns build ios` command
2. Open the `yourapp>platforms>ios>yourapp.xcworkspace` xcode workspace in xcode.
3. Choose your project on the left
4. Go to the "Signing" section in the project settings and check to ensure that "Automatically manage signing" is checked and that the team is selected.
5. Run the app on your connected iPhone.

It's not a fix rather a workaround and if anyone can shed any light on this issue, I'd be very appreciative!

**Comment by surdu** [comment]
@pajohns This doesn't solve the problem in my case 😞

**Comment by iosdeveloper1001** [comment]
I have one solution for this kind of issue, that is to search for the file `ios-project-service.js` at /usr/local/lib/node_modules/nativescript/lib/services this path.and search for the method name `exportDevelopmentArchive` and in this `plistTemplate` add a ```
<key>compileBitcode</key>
    <false/>
```.

Now execute your code with provisioning profile id i.e
tns run ios --provision provision-id.

**Comment by hettiger** [comment]
@NickIliev 

> ```
> or switch to manual signing by setting "signingStyle" to "Manual.}
> ```
> Basically, do [this](https://stackoverflow.com/a/42147217/4936697) - open the built project in XCode and set the signing to manual.

Is the team working on a solution that does not require manual repetitive steps? I don't want to keep touching generated code.

This issue should be labeled as a bug in my opinion.

**Comment by surdu** [comment]
In order to solve the problem we had to create a blank new project using the latest NativeScript  and copy all ot files to the new app. That was unpleasant but it worked.

**Comment by hettiger** [comment]
@surdu I've thought about that too but instead I tried to diff my project to a new clean 4.2 project. I couldn't find anything that would make a lot of sense to me causing this issue. We're using Sass, Webpack Builds, Firebase and whatnot. This will be a pain ... :-/

**Comment by surdu** [comment]
@hettiger I also made the diff in between a new and an old clean projects and arrived to the same conclusion as you.

**Comment by hettiger** [comment]
> @hettiger I also made the diff in between a new and an old clean projects and arrived to the same conclusion as you.

Your app name and id remained the same when you did copy over to a new project?

Maybe it's some Xcode cache ...?

**Comment by surdu** [comment]
Yes, they remained the same. In the [example I gave above](https://github.com/NativeScript/nativescript-cli/issues/3568#issuecomment-412868940), I didn't build the project, just created it, so I don't think it's the cache.

**Comment by hettiger** [comment]
Some further attempts of me:

- `npm i -g nativescript@latest`
- Adding `DEVELOPMENT_TEAM` and `CODE_SIGN_IDENTITY` to `app/App_Resources/iOS/build.xcconfig`
- `rm -rf node_modules && rm -rf platforms`
- Delete directories that are related to my app in `~/Library/Developer/Xcode/DerivedData`
- `rm -rf ~/Library/MobileDevice/Provisioning\ Profiles`
- Open up the Xcode project and deactivate + activate automatic code signing

Whatever I do:

- I'm not able to build for iOS using the CLI
- Building with Xcode works (but it's not a solution since i need the CLI for an effective workflow...)

**Comment by hettiger** [comment]
I finally gave up and recreated the entire project.
Fortunately it paid off and I can continue doing actual work.

I ran `tns create` and then copied over my `.git` directory.
This greatly simplified the process in my opinion.
(I just hat to revert and diff for a while ...)

**Comment by jrz** [comment]
No code change, ran tns run ios again, and all now I get this thing too.

**Comment by jrz** [comment]
Building with xcode works until you try to sign / upload.
After f'in arround with provisioning profiles etc, it turns out  fse.node is an executable that is not allowed in the package....

**Comment by jrz** [comment]
That also explains why it expects to be signed as Mac Developer

**Comment by jrz** [comment]
Alright.. I've removed the fsevent package. I'm not sure why it's in my node_modules, and therefore in my tns_modules.

**Comment by larssn** [comment]
@jrz 
It's used by the following modules:
```
├─┬ @angular/cli@6.2.5
│ └─┬ @angular-devkit/core@0.8.5
│   └─┬ chokidar@2.0.4
│     └── fsevents@1.2.4  deduped
├─┬ @angular/compiler-cli@6.1.10
│ └─┬ chokidar@1.7.0
│   └── fsevents@1.2.4 
├─┬ karma@3.0.0
│ └─┬ chokidar@2.0.4
│   └── fsevents@1.2.4  deduped
└─┬ nativescript-dev-sass@1.6.0
  └─┬ chokidar@2.0.2
    └── fsevents@1.2.4  deduped
```

**Comment by mathias-mcb** [comment]
I wrestled with the issue for quite some days. Eventually I came up with a little _build script_ that works in my case, at least. Maybe somebody finds it useful:
```sh
tns platform clean ios
tns install
tns build ios --bundle --env.uglify
tns prepare ios --release
``` 
I basically install from scratch. Afterwards - in xcode - I configure the signing team and I'm able to run the app on my phone and publish it to the app store.

**Comment by larssn** [comment]
We ended up making new provisioning profiles.

**Comment by hettiger** [comment]
@larssn That would have been my last resort too but I wanted to keep using automatic code signing.

**Comment by jrz** [comment]
Somehow
`"@angular/cli": "^6.0.8",`
Came back in my dependencies, where it should be in devDependencies (upgrading to the latest @next).
Moved to devDependencies, removed node_modules abomination and did `npm install`

**Comment by darkyelox** [comment]
You must pay attention to the `package.json` and their dependencies, if you have some plugin that use some package like `chockidar` that behinds use `fsevents` package (for example nativescript-dev-sass) and that plugin is listed in the `dependencies` instead of the `devDependencies` section then the `fse.node` error throws up, simple move that plugin package from `dependencies` to `devDependencies` and then run:

```
rm -rf node_modules
tns platform remove ios
```

Now you can generate an IPA or run over an emulator using the CLI.

**Comment by SephReed** [comment]
Has anyone found a solution for this problem yet?  None of the above have worked for me.

Alternatively, could anyone please at least explain roughly what's going on?  Why is there more than one Provisioning Profile if I only ever created one?  How is this other one being found?

This issue is really sucking up my time, and I don't yet even know what the core of the problem is

**Comment by SephReed** [comment]
Creating a new project and copying everything over did the trick for me in the end... :/
