### ISSUE TITLE
tns ios debug

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#358]
## Integrate the ios debugging with the CLI.
All the commands must be executed within the tns project folder, or with path to a project. They require the bundle id to setup the communication.

### Debug --debug-brk on Device
`tns debug ios --debug-brk`
Prepare, build, deploy, run the app. Start the inspector in Safari. Attach the inspector before any JavaScript is executed on iOS device. If you have a `debugger;` as first statement in the `bootstrap.js` the inspector should brake on it before any JS being executed. The terminal will block forwarding traffic over the USB cable.

### Debug --start on Device
`tns debug ios --start`
Start the inspector in Safari. Attach to an already running app. The terminal will block forwarding traffic over the USB cable.

### Debug --debug-brk on Emulator
`tns debug ios --debug-brk --emulator`
Prepare, build, debploy, run the app on an already running emulator or try to start one. Start the inspector in Safari. Attach the inspector before any JavaScript is executed on iOS device. If you have a `debugger;` as first statement in the `bootstrap.js` the inspector should brake on it before any JS being executed.

### Debug --start on Emulator
`tns debug ios --start --emulator`
Start the inspector in Safari. Attach to an already running app in emulator.

**Comment by PanayotCankov** [comment]
For testing purposes you may provide `--no-client` to suppress the Safari. Then the app will open 8080 for emulator or the CLI will forward the traffic from the device to the localhost on 8080.

Then you can connect to localhost 8080 using WebSocket client and simulate Inspector if you manage to reverse engineer the debugging protocol.

**Comment by jsgandalf** [comment]
This is some really great documentation! I don't mean to be a noob, but I'm running into an issue:

I run: tns ios debug --start

Unknown command 'ios'. Use 'NativeScript help' for help.

Any ideas? :/

tns version: 0.9.4

**Comment by teobugslayer** [comment]
Hi @jsgandalf ,
I think you have made a typo. The correct command should be **tns debug ios **
Also, for 0.9.4 we could not make it work in the emulator. The relevant code is already merged in the master branch and will be released in our next public build.

**Comment by jasssonpet** [comment]
`debug ios --start --emulator` - not working on Xcode 6.2+
`debug ios --debug-brk` - not working every time on device

**Comment by PanayotCankov** [comment]
@jsgandalf Fixed the 'ios debug' to 'debug ios' in the docs.

**Comment by jsgandalf** [comment]
Awesome!! Thanks!
