### ISSUE TITLE
Debug port -1 when run on android emulator

### ISSUE THREAD

**Issue by iamkarlson** [NativeScript/nativescript-cli#359]
Hello, I can't run debugger on android emulator because script stuck here
```
\lib\common\mobile\android\android-device.js:214
var dbgPort = this.startAndGetPort(packageName).wait();
```

After wait dbgPort geting -1

**Comment by iamkarlson** [comment]
I continued my investigation and I've found cause of port -1. 
File envDebug.out not exist in files directory. What am I doing wrong?

**Comment by rosen-vladimirov** [comment]
Hi @iamkarlson 
Please excuse us for the late reply. Can you try running the command with ```--log trace```, for example
```tns debug android --start --log trace```
If you can send us the output, we'll investigate it on our side. Also what is the android version of your device/emulator image?

**Comment by iamkarlson** [comment]
Yes, sure. You can find it here http://pastebin.com/tDf836qd

**Comment by slavchev** [comment]
It seems that the CLI cannot establish connection with your device/emulator. Currently, the CLI has hard-coded timeout set to 30 seconds which sometimes is not enough. I logged an issue here https://github.com/NativeScript/nativescript-cli/issues/375.

If you feel adventurous, you can change the timeout to, say, 60 seconds. From your logs I assume that you are running on Windows box, so you can edit `%localappdata%\..\Roaming\npm\node_modules\nativescript\lib\common\mobile\android\android-device.js` file (the exact location may be machine specific). You can search for `for (var i = 0; i < 30; i++)` and replace it with `for (var i = 0; i < 60; i++)` to increase the timeout to 60 seconds.

**Comment by iamkarlson** [comment]
Oh, no. My emulator doesn't have attached sdcard, but my phone does. And on my phone debugger  are working fine. Could please find out way to debug apps without mounted sdcard?

**Comment by slavchev** [comment]
We are already researching other options. I'll close our internal issue and make a public one so everybody can monitor its status.

**Comment by dtopuzov** [comment]
Closing this issue, see https://github.com/NativeScript/nativescript-cli/issues/661
