### ISSUE TITLE
xcrun: error: unable to find utility "simctl

### ISSUE THREAD

**Issue by moda20** [NativeScript/nativescript-cli#3590]
### Tell us about the problem

Can't launch The Sidekick successfully or the `tns devices`command, I get this error : 

```
Connected devices & emulators
Searching for devices...
Error: Error while executing command 'xcrun simctl list devices'. Please ensure your tools are configured correctly. More info: xcrun: error: unable to find utility "simctl", not a developer tool or in PATH

    at Simctl.simctlExec (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:116:19)
    at Simctl.getDevices (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:51:31)
    at XCodeSimctlSimulator.getBootedDevices (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/iphone-simulator-xcode-simctl.js:184:37)
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js:39:63)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```
same error also comes out in the sidekick main logs.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.1
- Cross-platform modules:  No project yet. just trying to run the sidekick to create a project using it.
- Runtime(s): No project yet. just trying to run the sidekick to create a project using it.
- Plugin(s): No project yet. just trying to run the sidekick to create a project using it.

### Please tell us how to recreate the issue in as much detail as possible.

Install  nativescript sidekick on macOS  10.13
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

No code.

**Comment by rosen-vladimirov** [comment]
Hey @moda20 ,
Can you try executing `xcodebuild -version`? I believe it will show an error that the Developer directory is not set correctly. If that's the case, you can try executing:
```
$ sudo xcode-select -s /Applications/Xcode.app
```
After that try executing `xcodebuild -version` again and if it works, you can try starting Sidekick again.

Can you try this and inform us if it works?

**Comment by moda20** [comment]
Just to be sure, is Xcode mandatory for sidekick to work on macOS ?

**Comment by Fatme** [comment]
Yes, xcode is mandatory.

**Comment by moda20** [comment]
@Fatme well I'll have to install it then I'll run the sidekick again and see if the problem persist.

**Comment by Fatme** [comment]
@moda20,
I'm closing this issue. Fell free to write here or open an another in case you have problems or questions.
