### ISSUE TITLE
My Android real Device is unreachable on ubuntu 18

### ISSUE THREAD

**Issue by toure28** [NativeScript/nativescript-cli#3591]
I have ubuntu 18.04 on my machine. The nativescript cli is set up and work properly. The tns doctor command show no issues. But the problem is that nativescript is unable to run for android real device because they are unreachable when i tap the following command: tns devices
Please I realy need help

**Comment by Fatme** [comment]
Hi @toure28,

 Could you check if the USB Debugging is enabled? Here is a [screencast](https://www.screencast.com/t/7P7vzSKP4OL) of where the setting is located.

If you cannot see the Developer menu, here are the steps to activate it:
* Go to the settings menu, and scroll down to "About phone." Tap it.
* Scroll down to the bottom again, where you see "Build number." (Your build number may vary from ours here.)
* Tap it seven (7) times.

**Comment by toure28** [comment]
Yes i confirm that the usb debugging mode is active. I compiled several times with this phone(samsung galaxy j7) but with a windows machine

**Comment by Fatme** [comment]
Hi @toure28,

Can you please confirm that you trusted your device? You should see a popup window on your device that asking you to trust the machine.

**Comment by toure28** [comment]
Hi @Fatme 
No, I didn't see a pop window on my android device when i connect it to the computer.

**Comment by toure28** [comment]
yes it is correct. My machine detect the device but it's status is unreachable when i run tns devices

**Comment by Fatme** [comment]
Can you please execute `adb devices` and send us the output?

**Comment by toure28** [comment]
this is the output when i execute adb devices:
List of devices attached
8SSKR4SC8DQCSOOR	    unauthorized

**Comment by Fatme** [comment]
As I can see from the output your device is `unauthorized` which means that you need to trust your device.
Can you please try the suggestions in this thread https://stackoverflow.com/a/25546300?
Let us know if it works on your side.

**Comment by toure28** [comment]
I tried all the steps but my device doesn't prompt for authorization.

**Comment by Fatme** [comment]
Have you tried to kill `adb server`?

**Comment by toure28** [comment]
Yes i kill first the adb server and after i restart it

**Comment by toure28** [comment]
when i connect the phone to the computer, it just ask me to allow access to phone data.

**Comment by priyangamani** [comment]
Have you tried this one.Follow this link
https://www.drivereasy.com/knowledge/solved-adb-device-not-found-error-on-windows/

**Comment by toure28** [comment]
thanks for the suggestion @priyangamani but i'm using ubuntu 18 LTS

**Comment by Fatme** [comment]
Hi @toure28,

> when i connect the phone to the computer, it just ask me to allow access to phone data.

What do you mean? Is a confirmation dialog shown on your device?
Also what happens in case you allow access to phone data?

**Comment by toure28** [comment]
Yes it is a confirmation dialog. when i allow access to phone data nothing happens and the device still be unreachable for the computer.

**Comment by NickIliev** [comment]
@toure28 the issue seems related to your local ADB setup - the command `tns devices` is just a wrapper around the `adb devices` command and if your ADB cannot reach the device it means that you have to provide access manually (by accepting the prompt on your mobile and then restarting the process).

Closing as not related to NativeScript CLI.
