### ISSUE TITLE
How to resolve RuntimeException error occured while run the application in mobile.

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/nativescript-cli#3596]
![image](https://user-images.githubusercontent.com/6038069/40171323-7e6070ba-59fd-11e8-8d58-ff22068ed300.png)

**Comment by NickIliev** [comment]
@priyangamani please consider posting as much as possible information on how to reproduce the issue and what are the environment settings used (versions of OS, CLI, and modules,  plugins and packages, etc.) Note that screenshots for error logs are not so user-friendly as their content can't be extracted easily - you could post your log in a generated file with  the following command
```
tns run android --log trace > log.txt
```

Below I am re-posting the guide to open a new issue with all the information needed

> ## Please, provide the details below:
> 
> ### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
> 
> ### Tell us about the problem
> Please, ensure your title is less than 63 characters long and starts with a capital
> letter.
> 
> ### Which platform(s) does your issue occur on?
> iOS/Android/Both
> 
> ### Please provide the following version numbers that your issue occurs with:
> - CLI: (run `tns --version` to fetch it)
> - Cross-platform modules: (check the 'version' attribute in the
> `node_modules/tns-core-modules/package.json` file in your project)
> - Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
> `package.json` file of your project)
> - Plugin(s): (look for the version number in the `package.json` file of your
> project)
> 
> ### Please tell us how to recreate the issue in as much detail as possible.
> 
> ### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
> Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.
