### ISSUE TITLE
Livesync does not work on Android P

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#3602]
### Tell us about the problem

Livesync does not work on Andorid P. In order to get latest changes applied it is need to remove and add the platform, then run the application again.

### Which platform(s) does your issue occur on?
Android P

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0-2018-05-17-11521
- Cross-platform modules: 4.0.0-2018-05-17-03
- Runtime: 4.1.0-2018.5.17.2
- node.js: 10.1.0

### Please tell us how to recreate the issue in as much detail as possible.
```
tns create appJS && cd appJS
tns run andoird (--bundle)
```
replace the "TAP" string in the `main-page.xml` file with "Test"

### Output:
```
Preparing project...
Project successfully prepared (Android)
Installing...
ActivityManager: Killing 7262:org.nativescript.appJS/u0a123 (adj 0): stop org.nativescript.appJS
ActivityManager: Killing 7262:org.nativescript.appJS/u0a123 (adj 0): stop org.nativescript.appJS
ActivityManager: setHasOverlayUi called on unknown pid: 7262
ActivityManager: setHasOverlayUi called on unknown pid: 7262
Successfully installed on device with identifier 'emulator-5554'.
Successfully transferred main-page.xml.
Refreshing application...
Successfully synced application org.nativescript.appJS on device emulator-5554.
ActivityManager: Start proc 7403:org.nativescript.appJS/u0a124 for activity org.nativescript.appJS/com.tns.NativeScriptActivity
```

**Comment by RadouaneRoufid** [comment]
+1

**Comment by BlindGarret** [comment]
+1

**Comment by BlindGarret** [comment]
For what it's worth, if you add the --clean flag to the "tns run android --emulator" command on cli 4.1.2, it will actually begin updating. However, the tradeoff is it appears to do a clean rebuild for every single file change, which isn't really better as it takes a huge amount of time to do a sync now. Still, it's a workaround.

**Comment by beginor** [comment]
+1
