### ISSUE TITLE
failed to remove and reinstall npm

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/nativescript-cli#3607]
## Please, provide the details below:
When I run command like tns plugin remove/ tns platform remove android ... EVEN npm uninstall nativescript. 
Process always stops at 

> nativescript-dev-android-snapshot@0.0.11 preuninstall C:\Users\ashleyca\Documents\we-deliver-food\We Deliver Food\We Deliver Food\node_modules\nativescript-dev-android-snapshot
> node preuninstall.js
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes
### Tell us about the problem
I cannot even delete folder "nativescript-dev-android-snapshot".

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.1
- Cross-platform modules:4.0.0
- Runtime(s): 4.0.1
- Plugin(s): 
"dependencies": {
    "@types/lodash": "4.14.104",
    "core-decorators": "0.20.0",
    "lodash": "4.17.5",
    "nativescript-appversion": "1.4.1",
    "nativescript-bitmap-factory": "1.1.0",
    "nativescript-bluetooth": "1.1.6",
    "nativescript-checkbox": "3.0.3",
    "nativescript-drawingpad": "3.0.0",
    "nativescript-drop-down": "3.2.0",
    "nativescript-fancyalert": "1.2.0",
    "nativescript-geolocation": "4.2.2",
    "nativescript-loading-indicator": "2.3.2",
    "nativescript-permissions": "1.2.3",
    "nativescript-portscanner": "file:nativescript-portscanner.tgz",
    "nativescript-print-zebra": "http://nativescript.rocks/RP/nativescript-print-zebra-1.2.0.tgz",
    "nativescript-sqlite": "1.1.7",
    "nativescript-toast": "1.4.6",
    "nativescript-ui-autocomplete": "3.7.0",
    "nativescript-ui-chart": "3.6.0",
    "nativescript-ui-listview": "3.5.5",
    "nativescript-ui-sidedrawer": "4.1.0",
    "tns-core-modules": "4.0.0"
  },
  "devDependencies": {
    "@types/core-decorators": "0.10.32",
    "awesome-typescript-loader": "~3.1.3",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "balanced-match": "1.0.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.5.1",
    "nativescript-dev-webpack": "0.11.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "^2.6.1",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  },

### Please tell us how to recreate the issue in as much detail as possible.
Please find log file [https://gist.github.com/AshleyCao/f74c6fc938ecde27ca8faeecd4bb8a56](https://gist.github.com/AshleyCao/f74c6fc938ecde27ca8faeecd4bb8a56)

**Comment by NickIliev** [comment]
@AshleyCao If you are using Windows try to log out and log in to unlock the folder and delete it manually. If that does not help in reinstalling your NativeScript, you could also force clean the NPM cache
```
npm cache clean -f
```

As a side note, I've noticed that your path folder is containing empty space in the path (`..\We Deliver Food\..`). The Gradle wrapper and Gradle plugin are not handling very well empty spaces in Windows paths. Please, try renaming the containing folders by removing all empty spaces.

**Comment by AshleyCao** [comment]
@NickIliev, Thanks a lot for your suggestion. 
By removing the space in the path solves the problem.
