### ISSUE TITLE
After v4 upgrade  : Error is: cp: copyFileSync: could not write to dest file (code=EPERM)

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-cli#3630]
This problem returned on TNS 4.

Look at this screen where my app is On : 

![image](https://user-images.githubusercontent.com/2842123/40643340-7db05e6c-6328-11e8-8a81-4788240b190a.png)

Now let's change something in the code

![image](https://user-images.githubusercontent.com/2842123/40643367-95513064-6328-11e8-91a6-17b4df9bf312.png)

See error : 

![image](https://user-images.githubusercontent.com/2842123/40643443-ddc11224-6328-11e8-8e1a-887e65a49176.png)

It didn't happen before in v 3
Files  ( origin files , )are read only due to TFS. **But it did work before v4.**

complete package.json : 

https://gist.github.com/RoyiNamir/c7adb7454b075369b0d325b88575f374

complete error : 
```
10:12:43 - File change detected. Starting incremental compilation...



10:12:44 - Compilation complete. Watching for file changes.



Executing before-prepare hook from C:\projects-web-storm\digital\dsapp1\hooks\before-prepare\nativescript-dev-sass.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from C:\projects-web-storm\digital\dsapp1\hooks\before-prepare\nativescript-dev-typescript.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from C:\projects-web-storm\digital\dsapp1\hooks\before-prepare\nativescript-plugin-firebase.js
Preparing project...
Executing before-prepareJSApp hook from C:\projects-web-storm\digital\dsapp1\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Unable to apply changes for device: 192.168.104.101:5555. Error is: cp: copyFileSync: could not write to dest file (code=EPERM):C:/projects-web-storm/digital/dsapp1/platforms/android/app/src/main/assets/app/app.module.ngfactory.d.ts.
Executing after-watch hook from C:\projects-web-storm\digital\dsapp1\hooks\after-watch\nativescript-dev-sass.js
Stopping nativescript-dev-sass watcher
Executing after-watch hook from C:\projects-web-storm\digital\dsapp1\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
```

Platform remove/add already been committed + full manual delete
Permission : everyone full control
Again - it didnt happen before
in v 4 we had to check out for edit (which remove read only flag)  only :` App_resources & Hooks & package.json`

But now , we have to check out the WHOLE project.

**Comment by dtopuzov** [comment]
Hi @RoyiNamir 

Can you please try with `nativescript@4.1.0` and `nativescript-dev-sass@1.6.0`?
We did some fixes for livesync issue on both places.

**Comment by RoyiNamir** [comment]
Hi @dtopuzov   - this is what I did : 

C:\Users\sff\Desktop\delme1\ddd\app>attrib +r /s
C:\Users\sff\Desktop\delme1\ddd\app>tns run android


And got this still : 


![image](https://user-images.githubusercontent.com/2842123/42017920-3d3998a0-7ab9-11e8-863c-83956c682be2.png)

I mention that I work with all most latest versions - with a simple clearn `tns create aaa --ng` proj : 

[Package.json ]( https://gist.github.com/RoyiNamir/f0a658265731abb06c12aad599149fa0)

If you need further details , please reply.
(windows 10).

**Comment by saintush** [comment]
I am getting same issue, any update on this.
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.something.topi",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "nativescript-cardview": "^2.0.2",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-dom": "^2.0.0",
    "nativescript-gif": "^2.0.0",
    "nativescript-google-plus": "file:C:\\Users\\citrix\\Downloads\\Takhat Server Files\\report 22-25\\nativescript-google-plus-master\\nativescript-google-plus-master",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-permissions": "^1.2.3",
    "nativescript-secure-storage": "^2.2.0",
    "nativescript-sms-inbox": "^1.0.7",
    "nativescript-social-share": "^1.5.0",
    "nativescript-sqlite": "^2.2.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-timedatepicker": "^1.2.0",
    "nativescript-toast": "^1.4.6",
    "nativescript-webview-interface": "^1.4.1",
    "tns-core-modules": "^4.1.0",
    "utf8": "^2.1.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11"
  }
}

**Comment by RoyiNamir** [comment]
@dtopuzov 
It's also happens in another variation when running `tns run android` ( after a checked-in )

```
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built aar for nativescript-calendar
Built aar for nativescript-fingerprint-auth
Built aar for nativescript-ng-shadow                                                                                          Built aar for nativescript-phone                                                                                              ShellJS: internal error                                                                                                       Error: EPERM: operation not permitted, open 'C:\projects-web-storm\digital\dsapp1\platforms\android\app\src\main\AndroidManifest.xml'                                                                                                                           at Object.fs.openSync (fs.js:646:18)                                                                                          at Object.fs.writeFileSync (fs.js:1299:33)                                                                                    at C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\sed.js:80:10                         at Array.forEach (<anonymous>)                                                                                                at Object._sed (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\sed.js:65:9)            at Object.sed (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\common.js:365:25)        at AndroidProjectService.interpolateConfigurationFile (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-project-service.js:233:15)                                                                                         at PreparePlatformNativeService.<anonymous> (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\lib\services\prepare-platform-native-service.js:57:56)                                                                                            at Generator.next (<anonymous>)                                                                                               at fulfilled (C:\Users\royin\AppData\Roaming\npm\node_modules\nativescript\lib\services\prepare-platform-native-service.js:4:58)                                                                                                                                                                                                                                                      C:\projects-web-storm\digital\dsapp1>    
```

**Comment by RoyiNamir** [comment]
@dtopuzov Any news on this one ? 
It causes us to checkout ALL our files project ( each "checking" and "get latest"). it's impossible to work with TFS with NS as TFS makes all files read only.
We don't have problem to remove read only from platforms. but every checking we checkout ALL files and checkin ALL files.
it's very frustrating to work like this.
Is there any future release that will fix this ?

**Comment by nukuuk** [comment]
Just installed Sidekick.  Trying to do my first "HelloWorld" build (for android).  Am getting this error.  Am not having any luck finding a fix/resolution

**Comment by rosen-vladimirov** [comment]
Related to: https://github.com/NativeScript/nativescript-cli/issues/3630
