### ISSUE TITLE
List View issue when trying to swipe from left and back with animation effect, on the ios

### ISSUE THREAD

**Issue by flowforever** [NativeScript/nativescript-cli#364]
I put a ListView on the page, then I add a itemTap event to open a detail page.
the pages like these:
ListPage:
![2015-03-22 7 28 41](https://cloud.githubusercontent.com/assets/1191872/6769139/0f07caca-d0ca-11e4-93ac-32f71a848a5d.png)

Detail Page:
![2015-03-22 7 35 23](https://cloud.githubusercontent.com/assets/1191872/6769193/a5d672d4-d0cb-11e4-91c4-e5b072b8281f.png)

Then I got this:

![2015-03-22 7 44 38](https://cloud.githubusercontent.com/assets/1191872/6769198/0c161f04-d0cc-11e4-8df0-422b530f3d1d.png)

and this (with swipe but not swipe back):

![2015-03-22 7 47 30](https://cloud.githubusercontent.com/assets/1191872/6769214/8d937e14-d0cc-11e4-91fe-2ad9c5e2e8bb.png)

The following are my code:
the ListView xml:
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
    <StackLayout>
        <ListView items="{{ listItems }}" itemTap="listViewItemTap">
            <ListView.itemTemplate>
                <Label text="{{ text }}" cssClass="listItem-text" />
            </ListView.itemTemplate>
        </ListView>
    </StackLayout>
</Page>
```
the ListView viewModel js:

```
var vmModule = require("./main-page.model");


// Event handler for Page "loaded" event attached in main-page.xml
function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = vmModule.mainViewModel;
}
function listViewItemTap(args){
    var frameModule = require("ui/frame");
    var topmost = frameModule.topmost();
    var navigationEntry = {
        moduleName: "app/detail-page",
        context: {info: "something you want to pass to your page"},
        animated: true
    };
    topmost.navigate(navigationEntry);
}

exports.pageLoaded = pageLoaded;
exports.listViewItemTap = listViewItemTap;
```

The Detail page js file is empty, and the xml file only has a <label/> inside

**Comment by teobugslayer** [comment]
Hello @flowforever , please open an issue in https://github.com/NativeScript/cross-platform-modules - this repo is for the CLI tool.
