### ISSUE TITLE
Feature Request: Android App Bundles

### ISSUE THREAD

**Issue by DickSmith** [NativeScript/nativescript-cli#3641]
Android now offers the ability to create "App Bundles" which replaces the need to do "ABI splits" and allows a developer to upload a single "universal" bundle that the store then splits into individual APKs according to ABI and screen density (much like iTunes has long allowed). This also makes the process of uploading these far easier, as only a single bundle with a single version needs to be uploaded, rather than uploading multiple APKs, which requires managing a different version number for each.

https://developer.android.com/guide/app-bundle/?utm_source=play-console

The feature still appears to be in Alpha as of now (requires Android Studio 3.2 Preview to initialize the alpha version of the Android Gradle Build plugin), but once stable would be a nice feature to allow for Android. (It does require signing via Google Play as well, but this seems to be the incentive to get developers to move to that setup.)

**Comment by dtopuzov** [comment]
Available in nativescript@5.1.

Docs:
https://docs.nativescript.org/angular/tooling/publishing/android-app-bundle
