### ISSUE TITLE
Allow using source code in iOS part of plugins

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#3650]
Currently we are able to use Cocoapods in iOS part of the plugins. This gives us a lot of power when creating plugin. However, for some cases, it will be great to be able to add just the source code in the `platforms/ios` directory of the plugin and to include it directly while building the project.

**Comment by Natalia-Hristova** [comment]
Implemented https://github.com/NativeScript/nativescript-cli/pull/3524_

**Comment by Natalia-Hristova** [comment]
Implemented and available from version `4.1.0`
