### ISSUE TITLE
TypeScript compiler failed with exit code 3221225477

### ISSUE THREAD

**Issue by rachid-aachich** [NativeScript/nativescript-cli#3652]
Hi, 

When i try to run the app on my android device it gives me the following error:

> Searching for devices...
Executing before-liveSync hook from C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-liveSync\nativescript-angular-s
ync.js
Executing before-prepare hook from C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-prepare\nativescript-dev-sass.js

Found peer node-sass
Executing before-prepare hook from C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-prepare\nativescript-dev-typescr
ipt.js
Found peer TypeScript 2.6.2
Unable to apply changes on device: 534af2fc. Error is: TypeScript compiler failed with exit code 3221225477.

the command "tns prepare android --log trace" gives the following output:

> `Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
System information:
{ platform: 'win32',
  shell: 'C:\\Windows\\system32\\cmd.exe',
  os: 'Windows Seven Black Edition 6.1.7601',
  procArch: 'ia32',
  nodeVer: '8.9.4',
  npmVer: '5.6.0',
  nodeGypVer: null,
  nativeScriptCliVersion: '4.0.2',
  gitVer: '2.15.1.windows.2',
  dotNetVer: '4.7.02558',
  javacVersion: '1.8.0_172',
  adbVer: '1.0.39',
  androidInstalled: true,
  monoVer: null,
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: undefined,
  xcodeprojLocation: null,
  itunesInstalled: false,
  cocoaPodsVer: undefined,
  isCocoaPodsWorkingCorrectly: false,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: null }
Starting watch on killswitch C:\Users\sony\AppData\Local\Temp\sony\KillSwitches\cli
Looking for project in 'C:\Users\sony\kan\kan-ngxp\nativescript'
Project directory is 'C:\Users\sony\kan\kan-ngxp\nativescript'.
Validate options for platform: Android
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: { cd5: 'CLI' } }
spawn: node "C:\Users\sony\AppData\Roaming\npm\node_modules\nativescript\lib\services\analytics\analytics-broker-process
.js" "C:\Users\sony\AppData\Roaming\npm\node_modules\nativescript\lib\bootstrap.js"
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can u
se the NativeScript cloud infrastructure.
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: true',
  customDimensions: { cd5: 'CLI' } }
Installed Android Targets are:  [ 'android-25' ]
Directories found in C:\Android\android-sdk\build-tools are 27.0.3
Versions found in C:\Android\android-sdk\build-tools are 27.0.3
Selected version is:  27.0.3
Selected targetSdk is: 25
Directories found in C:\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.
0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.
1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0-alpha1, 24.0.0-alpha2, 24.0.0-beta1, 24.1.0, 24.1.1, 24.2.0, 24.2.1,
 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0-alpha1, maven-metadata.xml, maven-metadata.xml.md5, mave
n-metadata.xml.sha1
Versions found in C:\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0
, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1
, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0, 24.0.0, 24.0.0, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0
, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0
Selected version is:  25.3.1
Selected AppCompat version is: 25.3.1
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'pageview',
  path: 'prepare',
  title: 'prepare',
  customDimensions: { cd5: 'CLI' } }
Changes info in prepare platform: ProjectChangesInfo {
  appFilesChanged: true,
  appResourcesChanged: true,
  modulesChanged: true,
  configChanged: true,
  nativePlatformStatus: '2' }
Project dir from hooksArgs is: C:\Users\sony\kan\kan-ngxp\nativescript.
Hooks directories: [ 'C:\\Users\\sony\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\hooks',
  'C:\\Users\\sony\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\hooks',
  'C:\\Users\\sony\\kan\\kan-ngxp\\nativescript\\hooks' ]
BeforeHookName for command shouldPrepare is before-shouldPrepare
Project dir from hooksArgs is: C:\Users\sony\kan\kan-ngxp\nativescript.
Hooks directories: [ 'C:\\Users\\sony\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\hooks',
  'C:\\Users\\sony\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\hooks',
  'C:\\Users\\sony\\kan\\kan-ngxp\\nativescript\\hooks' ]
AfterHookName for command shouldPrepare is after-shouldPrepare
Project dir from hooksArgs is: C:\Users\sony\kan\kan-ngxp\nativescript.
Hooks directories: [ 'C:\\Users\\sony\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\hooks',
  'C:\\Users\\sony\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\hooks',
  'C:\\Users\\sony\\kan\\kan-ngxp\\nativescript\\hooks' ]
BeforeHookName for command prepare is before-prepare
Executing before-prepare hook from C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-prepare\nativescript-dev-sass.js

Executing before-prepare hook at location C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-prepare\nativescript-dev-
sass.js in-process
Validating before-prepare arguments.
Found peer node-sass
C:\Program Files\nodejs\node.exe C:\Users\sony\kan\kan-ngxp\nativescript\node_modules\node-sass\bin\node-sass C:\Users\s
ony\kan\kan-ngxp\nativescript\app --output C:\Users\sony\kan\kan-ngxp\nativescript\app --output-style compressed -q --fo
llow --importer C:\Users\sony\kan\kan-ngxp\nativescript\node_modules\nativescript-dev-sass\lib\importer.js
Hook promises to signal completion
Hook completed
Executing before-prepare hook from C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-prepare\nativescript-dev-typescr
ipt.js
Executing before-prepare hook at location C:\Users\sony\kan\kan-ngxp\nativescript\hooks\before-prepare\nativescript-dev-
typescript.js in-process
Validating before-prepare arguments.
Found peer TypeScript 2.6.2
C:\Program Files\nodejs\node.exe --max_old_space_size=4096 C:\Users\sony\kan\kan-ngxp\nativescript\node_modules\typescri
pt\lib\tsc.js --project C:\Users\sony\kan\kan-ngxp\nativescript --inlineSourceMap --inlineSources
Hook promises to signal completion
Failed during hook execution.
TypeScript compiler failed with exit code 3221225477
Error: TypeScript compiler failed with exit code 3221225477
    at Errors.fail (C:\Users\sony\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
    at Errors.failWithoutHelp (C:\Users\sony\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:135:21)
    at HooksService.<anonymous> (C:\Users\sony\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-s
ervice.js:83:30)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\sony\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

Tns version is 4.0.2
TypeScript version is 2.6.2

tns devices shows that the device is connected.
 
I am running Windows 7.

Any help would be highly appreciated.
Thanks in advance.

**Comment by rachid-aachich** [comment]
The issue is resolved, atleast i got to know the origin of the problem.
The error occurs because nativescript cannot allocate enough heap memory for the JVM to build the application, NativeSript by default set the value in ``gradle.properties`` file to 16 GB of memory (a value that is relatively big for a good portion of computers).
Decreasing the value might help in some cases.

**Comment by alex-che** [comment]
Hi,
I have the same error (exit code 3221225477, at process._tickCallback (internal/process/next_tick.js:188:7) with very similar environment (Windows 7 32bit, nodeVer: '8.11.3', npmVer: '5.6.0', nativeScriptCliVersion: '4.1.0').
I've tried to manually change the `org.gradle.jvmargs` value in the gradle.properties of the generated project with no visible effect. Are there any more hints of how to solve the problem?
Here is my tns prepare android output:
[log.txt](https://github.com/NativeScript/nativescript-cli/files/2099463/log.txt)

**Comment by alex-che** [comment]
I managed to fix the error by removing the **--max_old_space_size=4096** argument to npm in the `node_modules/nativescript-dev-typescript/lib/compiler.js`. My environment is Windows 7 32bit virtual machine, so only 3 GB is available to applications. While max_old_space_size is in MB and is therefore greater than the available amount. I suspect that removing the max_old_space makes npm to select some default value based on currently available memory amount.

**Comment by rachid-aachich** [comment]
Hi Alex, 

I have Win 7 32bit as well, i will try out your solution and get back, btw i have found out that the problem is the amount of heap memory that NativeScript tries to allocate in order to build for Android is huge, something around 16 GB in the gladle properties file.

We ended up with a completly different solution which is to build in the cloud.
