### ISSUE TITLE
Changes in AndroidManifest are not updated after rebuild

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3655]
After making changes in [AndroidManifest.xm](https://github.com/NickIliev/nativescript-ng-cosmos/blob/next/app/App_Resources/Android/AndroidManifest.xml#L4-L5)l in already built application and running
```
tns run android --bundle --env.uglify --release --for-device <release-flags-follows-here>
```
the changes are not applied in the newly build app.

Steps to reproduce:
- build an application with Webpack in release
```
tns run android --bundle --env.uglify --release --for-device <release-flags-follows-here>
```

- stop the application and change the `versionCode` or other entry in `AndroidManifest.xml`

- rebuild the application with
```
tns run android --bundle --env.uglify --release --for-device <release-flags-follows-here>
```

Result: the `AndroidManifest.xml` is not changed and new values are not applied.
Reproduced with NativeScript 4.1.0 (OS: Windows)

Note: After build there are two AndroidManifest.xml files generated:
- one in **`platforms/android/app/src/main/AndroidManifext.xml`** (with the old content - not updated)
- one in **`platforms/android/app/src/main/res/AndroidManifest.xml`**  (with the updated content)
The Google Play store seems to respect the first manifest.

Workaround:  Delete `platforms` folder and rebuild
```
rm -rf platforms
tns build android --bundle --env.uglify --release <flags-folllows-here>
```

**Comment by DimitarTachev** [comment]
Not reproducible with nativescript@5.2.0.
