### ISSUE TITLE
Don't rebuild application for android when something is changed in App_Resources/iOS 

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#3658]
### Tell us about the problem
In case when some change occurs in `App_Resources/iOS` and `tns run android` command is executed, the application is fully rebuild.
In case when some change occurs in `App_Resources/Android` and `tns run ios` command is executed, the application is fully rebuild.

### Which platform(s) does your issue occur on?
Both

### Please tell us how to recreate the issue in as much detail as possible.
Steps to reproduce:
1. Create new project
2. Execute `tns run ios`
3. Execute again `tns run ios` - you should see `Skipping prepare...` message
4. Make some change inside `App_Resources/Android` folder - touch some file for example
5. Run again `tns run ios` command - You'll see the application is rebuild but actually no build is necessary.

**Comment by Natalia-Hristova** [comment]
Now only 
```
Skipping prepare.
Successfully synced application....
```
is shown.

This will be available in the next official version of `nativescript`.
