### ISSUE TITLE
Unable to apply changes on device: emulator-5554. Error is: No space left on device..

### ISSUE THREAD

**Issue by shimjudavid** [NativeScript/nativescript-cli#3667]
Iam a newbie in Nativescript.
Just created a new app using command-
 tns create GroceryApp --template nativescript-template-ng-tutorial

cd GroceryApp
tns run android

.....

Project successfully built.
Installing...
Unable to apply changes on device: emulator-5554. Error is: No space left on device..
Executing after-watch hook from /Users/EmaxSoftware/Apps/NSApps/GroceryApp/hooks/after-watch/nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from /Users/EmaxSoftware/Apps/NSApps/GroceryApp/hooks/after-watch/nativescript-dev-typescript.js

Android Emulator is launched, but this is what iam getting- 
<img width="350" alt="screen shot 2018-06-06 at 12 49 46 am" src="https://user-images.githubusercontent.com/16755297/40997831-9ec88952-6923-11e8-8b79-57edca76f48f.png">

**Comment by shimjudavid** [comment]
i found the solution

**Comment by thiagolimacg** [comment]
How?

**Comment by shimjudavid** [comment]
Find where the avd are stored, for (macOS) it’s in ~/.android/avd,
every avd has its own directory, with a config.ini file where you can change its config. The parameter you might need to look at is - 

disk.dataPartition.size=800M

**Comment by thiagolimacg** [comment]
on Windows path (C:\Android\android-sdk\tools\bin), worked with following command: 
emulator  @My-emulator-name -partition-size 1024

**Comment by MonsieurLeSuisse** [comment]
Check if the applicationId in App_Resources/Andropid/app.gradle and nativescript.id in package.json are identical. 
There might be differences when you pull the project from the templates (lower/uppercase issues on Windows, e.g org.nativescript.groceries vs org.nativescript.Groceries).

**Comment by daryllabar** [comment]
The path for Windows that @thiagolimacg  gives apparently has changed.

`C:\Android\android-sdk\emulator>emulator @My-emulator-name -partition-size 1024
`
also to get your emulator name:
`emulator -list-avds`

**Comment by hideman1975** [comment]
Not working. The same issue
Successfully installed on device with identifier 'emulator-5554'.
Unable to apply changes on device: emulator-5554. Error is: Socket connection timed out..
Stopping tsc watch
Stopping webpack watch

**Comment by DimitarTachev** [comment]
Hi @hideman1975,

This is a closed issue for `No space left on device` while you are getting `Socket connection timed out`. Please open a new issue following the issue template in order to allow us to investigate it further.
