### ISSUE TITLE
Validation for `tns update` before we execute it

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#3669]
### Tell us about the problem
Create project with 4.1.0
Run `tns update @rc`
This is invalid (it should be `tns update rc`).
It try to upgrade and roll back to original since `@rc` is invalid.
Can we validate before even try to update?

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.0
- Plugin(s): No

**Comment by janoshrubos** [comment]
This has been implemented since this issue was created.
The CLI checks the version before upload and throws error: `Could not update the project! Reason is: Unable to execute update as package @nativescript/core does not have version/tag @rc. Please enter valid version or npm tag.`

cc: @rigor789

**Comment by rigor789** [comment]
@janoshrubos I think the message is correct - however it's shown after the backup has been created/restored 
https://github.com/NativeScript/nativescript-cli/blob/6de0c3e513da0b91f4deef84748417a842c4bbf0/lib/controllers/update-controller.ts#L107-L116

We could perhaps do the checks earlier in the call - before the project is cleaned/backed up.
