### ISSUE TITLE
Difference between "tns plugin add" and "tns plugin install"

### ISSUE THREAD

**Issue by cvietor** [NativeScript/nativescript-cli#3677]
Hi,
is there any difference between these two commands ? As far as i can tell, the docs are the same and they seem to do the same thing.

**Edit:**
After looking into the code, i realised that they are "install" command actually runs the "add" command :)

[bootstrap.ts](https://github.com/NativeScript/nativescript-cli/blob/c18a8189ccb9ba33d04e3829edd322a0fbc1f6b5/lib/bootstrap.ts#L95):
`$injector.requireCommand("plugin|add", "./commands/plugin/add-plugin");
 $injector.requireCommand("plugin|install", "./commands/plugin/add-plugin");`

Should be mentioned in the docs that "install" is actually just an alias for "add" to avoid confusion.

**Comment by KristianDD** [comment]
Hi @cvietor ,
Thank you for reporting this and the effort you put into investigating it. We created and merged a PR to list the alias of the `tns plugin install/add` command.

If you find any other issues you are welcome to create a PR. We will be more than happy to review it and provide any help you need to contribute to the project. Again thank you for reporting this.
