### ISSUE TITLE
NativeScript 4 not working on CircleCI - setup script for macOS does not install python's six package

### ISSUE THREAD

**Issue by surdu** [NativeScript/nativescript-cli#3678]
I have a [simple CircleCI configuration](https://circleci.com/gh/surdu/TNSTravisTest/146#config/containers/0) which runs on MacOS that will checkout [some test code](https://github.com/surdu/TNSTravisTest), install NS dependencies [as described in the docs](https://docs.nativescript.org/start/quick-setup#macos) and then builds the project for iOS.

This [works perfectly](https://circleci.com/gh/surdu/TNSTravisTest/147) when I use `nativescript@3` but [always fails](https://circleci.com/gh/surdu/TNSTravisTest/146) when using `nativescript@4` with the following error:

```
You are missing the nativescript-cloud extension and you will not be able to execute cloud builds. 
Your environment is not configured properly and you will not be able to execute local builds.
[...]
Exited with code 127
```

Any ideas what NS4 needs extra from NS3 ?

**Versions:** 

```bash
$ node -v
v8.9.1

$ npm -v
5.5.1

$ xcodeproj --version
1.5.9

$ pod --version
1.5.3

# Command-line tools for Xcode
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
version: 9.1.0.0.1.1508540944
```

**Comment by rosen-vladimirov** [comment]
Hey @surdu ,
Thanks for the detailed report. I've checked the log files and here's what I think is happening:
1. The `tns prepare ios` command tries to check your environment
2. The validation fails and NativeScript CLI tries to resolve the issue
3. In case the terminal is not interactive, CLI should just print an error describing what is not setup correctly. In case the terminal is interactive, CLI gives you a choice how to resolve the faced issue - by preparing the environment for Cloud builds or by trying to setup the environment for local build. In the current situation it looks like CLI thinks the terminal is interactive (i.e. it thinks there's someone to answer the questions) and prompts to select a solution.

As I'm unable to see what is not setup in the logs, may I ask you to try executing `tns prepare ios --log trace` - this will print a lot more information in the output and we'll be able to see what is not setup correctly.

**Comment by surdu** [comment]
I did. [Here](https://circleci.com/gh/surdu/TNSTravisTest/150) are the results.

**Comment by rosen-vladimirov** [comment]
Hey @surdu ,
Thanks for providing the logs. Based on it I think the problem is that you do not have the python "six" package installed. Can you try installing it with `pip install six` and see if this will resolve the issue?

**Comment by surdu** [comment]
Thanks a million @rosen-vladimirov, this appears to have solved the problem.

What would be a good next step: edit documentation to list this dependency or update [setup-scripts](https://github.com/NativeScript/setup-scripts) to also install six ?

**Comment by rosen-vladimirov** [comment]
Hey @surdu , I'm glad it works now. We'll update both the documentation and the setup scripts. I'll keep this issue open, so you can track the progress of the task here.

**Comment by surdu** [comment]
I've created PRs to address this issue in both repos. Thanks again for the help!
