### ISSUE TITLE
Devices NotFoundDeviceByIndexErrorMessage on debug

### ISSUE THREAD

**Issue by domzinhuu** [NativeScript/nativescript-cli#3679]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

I can't debug in this new version 4.1 of CLI always show this error:
Unable to apply changes on device: 0039799762. Error is: Devices.NotFoundDeviceByIndexErrorMessage 39799761 tns

### Which platform(s) does your issue occur on?
iOS/Android/Both

Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

nativescript CLI: 4.1
node: v9.5.0

### Please tell us how to recreate the issue in as much detail as possible.

create a new project and run tns debug android or ios

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

I get this error in any project, inclusive in new project

**Comment by mintyweazel** [comment]
I am stuck at the same error on version 4.1.0, too.
As you say, the error shows up regardless of the projects.
In my case, downgrading to 4.0.2 fixed the problem.

I think this issue should be related to some of the changes on 4.1.0.
If I find any useful information, I will share it here.

**Comment by domzinhuu** [comment]
Hi #mintyweazel, thanks for the tips. i'll try make a downgrade tomorrow and post here If This work for me too

**Comment by Fatme** [comment]
Hi @domzinhuu,

Can you please execute the command with `tns debug ios --log trace` and send us the output?

**Comment by domzinhuu** [comment]
Hi @Fatme here the log solicited,
[output.log](https://github.com/NativeScript/nativescript-cli/files/2115825/output.log)

and @mintyweazel i'll now try your tips and post here..

**Comment by andresggarcia** [comment]
+1 I'm having the exact same problem too.

**Comment by Fatme** [comment]
Hi @domzinhuu, @mintyweazel, @andresggarcia,

I was able to reproduce the problem with old versions of `tns-ios`, but it works fine with latest version of `tns-ios`. So I'm suspecting your `tns-ios` version is not the latest one. You can check it inside `package.json` file. If this is the case I'm suggesting to update to latest `tns-ios` version. To do it execute the followings:
```
rm -rf platforms
tns platform add tns-ios@latest
```

**Comment by domzinhuu** [comment]
Hello @Fatme 
 i dont try use ios@latest but i try remove platform  exclude the platform folder and add platform again and nothing, but i'll try again when update nativescript, because i make a downgrade to try the tips of @mintyweazel and the tips resolve the problem for me.

i'll update again and try your tips and post here the result.

**Comment by mintyweazel** [comment]
Hi @Fatme,

I tried your solution with the command `tns-android` instead of `tns-ios`, but it did not work. In that case, the android runtime version is `4.1.3` and the cli version is `4.1.1`,  both of which are the latest version.

**Comment by Fatme** [comment]
Hi @mintyweazel,

I wasn't able to reproduce the problem for android. Can you please send us a log file (just execute the command with `--log trace`) or give us exact steps to reproduce the problem.

**Comment by domzinhuu** [comment]
Hi @Fatme  

I update again my nativescript CLI and try your tips with android add ios and android plat with @latest but not work i had the same problem. My solution for now was the tips of @mintyweazel 

> I am stuck at the same error on version 4.1.0, too.
As you say, the error shows up regardless of the projects.
In my case, downgrading to 4.0.2 fixed the problem.

I think this issue should be related to some of the changes on 4.1.0.
If I find any useful information, I will share it here.

**Comment by RafaelKr** [comment]
Hi, I got the same problem for `tns debug android` with `nativescript@4.1.0`
Here is my output of `tns debug android --log trace`. I removed some output, which is marked with `[...]`.
The downgrad to v4.0.2 by running `npm i -g nativescript@4.0.2` resolved the problem for me.

**Comment by miroslavaivanova** [comment]
Closing the issue. I wasn't able to reproduce it with the latest CLI. Please if anyone has a stable way to reproduce the issue - let me know and I will reopen this one immediately!
