### ISSUE TITLE
Many - "file change detected. Starting incremental compilation.... "

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-cli#3687]
Using the latest version ( 4.1 &  Angular 6    , on Windows 10 , webpack 0.13) - 

```
tns create aaa --ng
npm install --save-dev nativescript-dev-webpack
npm install
tns run android
```
Is causing many repeated messages : 

![image](https://user-images.githubusercontent.com/2842123/41508848-cc91826a-7253-11e8-9fa0-e553f1b4c7ac.png)

(finally succeeding).

**Comment by Fatme** [comment]
Hi @RoyiNamir,

Thank you for reporting this issue.

We've investigated the problem and fixed it. The fix will be released in next version of `nativescript-dev-typescript` plugin. I'll update you here in this thread when the fix is live.

**Comment by RoyiNamir** [comment]
@Fatme Thank you for your quick response.

**Comment by albertobastos** [comment]
Probably related with https://github.com/NativeScript/nativescript-cli/issues/3547, will confirm after the next release including the fix is launched.

**Comment by Fatme** [comment]
Hi @RoyiNamir,

Sorry for late reply. The change is inside `nativescript-dev-typescript` plugin. You can see it here https://github.com/NativeScript/nativescript-dev-typescript/pull/55/files.

**Comment by RoyiNamir** [comment]
@Fatme @miroslavaivanova  Hi.
Should this ^ be moved to `https://github.com/NativeScript/nativescript-dev-typescript` ?
(jsut asking)
