### ISSUE TITLE
Startup is extremely slow on Android

### ISSUE THREAD

**Issue by brianchirls** [NativeScript/nativescript-cli#371]
The Hello World application often takes a very, very long time to show any interface and run the `loaded` callback. The last time I ran it on the emulator (X86 emulator with HAX installed), it took 37 seconds from the time the app showed up with a blank white screen and menu bar. I've seen it take long enough to get a "not responding" warning. It's also slow running on my actual device (Nexus 4).

I don't have this problem with other Android apps I built in pure Java with Android Studio. Start-up of Hello World on the iOS emulator is instantaneous.

**Comment by rosen-vladimirov** [comment]
Hi @brianchirls 
Thank you for your feedback. In fact speeding up android apps is our top priority for version 1.0. Currently the apps are starting slow on Android 5.* 
One more thing - the speed up of emulator with HAX is possible when only a single emulator is running. In case you have running emulator and you start a second one, the performance will be as the default ARM images.

**Comment by cime** [comment]
I tried it today with the latest version of NativeScript on Nexus 4 (Android 5.1) and startup time is still slow (about 5-6 seconds untils TAP button is shown)

**Comment by bfattori** [comment]
Just tried this in 1.1.1 and my "app" (a XML page, no code beyond the basic app.js) takes _13 seconds_ to start. This is really pretty unacceptable. No one waits for a web page beyond 3 seconds, and they sure as hell don't want to wait 13 seconds for a "native" app to start. This needs to be improved.

**Comment by teobugslayer** [comment]
Hello @bfattori,

indeed, 13 seconds are abnormally high. Can you tell us what device are you using for your test and which OS version it runs?

**Comment by bfattori** [comment]
I'm sorry, I jumped the gun. That was on the emulator. On device it is a
very acceptable 3-4 seconds.

You can reclose the issue.

**Comment by CleverCoder** [comment]
I dunno... running the "Groceries" 'angular-start' code, with very, very basic code takes 5-6 seconds on my Nexus 6 device. This is pretty bad. I may re-open this or log a new issue if it continues this way. I don't even know where to begin profiling, since it's Nativescript.

**Comment by robertonic** [comment]
The app I'm currently writing takes at least 7 seconds before anything is shown on a Nexus 7.  This is too slow.  This isn't a release build.  

I'm using Nativescript 2 + Angular + Typescript.

**Comment by kazemihabib** [comment]
I have the same problem 
I'm using Nativescript 2 + Angular + Typescript.

**Comment by robertonic** [comment]
Is startup time for Android going to be improved in future releases?  Currently I think it's so slow that  NativeScript is close to unusable on Android.

**Comment by robertonic** [comment]
Just rebuilt my app using Nativescript but not using Angular 2. Startup is now much faster and acceptable. (~3 seconds).  The slow factor seems to have been Angular 2.

**Comment by dusanstamen** [comment]
Same issue here, without Angular app startup is much faster. Tested on Android 6.

**Comment by tomcatmwi** [comment]
How do you guys get a refresh in 5-6 seconds? It's 5-6 minutes for me, but a fresh build sometimes takes 20-25 minutes with a blank new app. It doesn't matter if it's Angular or not.

**Comment by dtopuzov** [comment]
Hi @matiasratcliffe 

Can you please try with NativeScript 4.1 and Angular 6, it contains a lot of performance improvements, specially in case you optimize your app with webpack.
