### ISSUE TITLE
node module date-fns won't work

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#3728]
the node module [date-fns](https://github.com/date-fns/date-fns) won't work with NativeScript. This module as ```_lib``` folder which seems to be ignored by NativeScript causing  a:
```
Failed to find module: "../_lib/toInteger/index.js", relative to: app/tns_modules/date-fns/addDays/
```

**Comment by NickIliev** [comment]
@farfromrefug it seems that the linked package is not an official NativeScript plugin so there are no guarantees that it will build/work as expected in a NativeScript application.

You could try to "nodeify" the package via [this plugin](https://github.com/EddyVerbruggen/nativescript-nodeify) or perhaps use an alternative like moment.js (which is working with NativeScript)

**Comment by farfromrefug** [comment]
@NickIliev well I agree it not a NativeScript plugin however it should work as it is and it does using webpack. It's like moment.
The issue is that for some reason "_lib" folders are ignored  in node_modules and not packaged with then app.
So consequently it seems like a Nativescript build issue which could be solved. Don't you think?

**Comment by NickIliev** [comment]
@farfromrefug I've created [this test project](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-cli/issue-3728) and in fact, I was able to use the library with no issues so far.

**Comment by farfromrefug** [comment]
@NickIliev thanks for creating this. I really don't understand why it does not work here. I can clearly see that the ```_lib``` folder is not packaged.

Also I saw something, I am not using```date-fns``` 1.29.0 but 2.0.0-alpha11. I will try to see if they changed the module directory structure. That could be why you can't reproduce it.

Thanks again for testing this. Will report here

**Comment by farfromrefug** [comment]
@NickIliev I can confirm that it happen with 1.29.0. That version does not have a ```_lib``` directory

**Comment by NickIliev** [comment]
@farfromrefug I've installed [the latest official version](https://date-fns.org/v1.29.0/docs/Change-Log). I haven't even noticed that there is a 2.00-alpha one. I guess it is still not production ready version so we could stick around 1.29.0 for now.

**Comment by farfromrefug** [comment]
@NickIliev can't stick with 1.29.0, they added too many functions that I need ;) Did you manage to reproduce the issue with 2.0.0 ?

**Comment by NickIliev** [comment]
@farfromrefug haven't tried with 2.0.0 as[ the officially released one on NPM is 1.2.9](https://www.npmjs.com/package/date-fns).

**Comment by farfromrefug** [comment]
@NickIliev so what does it mean? Do you want me to prepare a sample project with 2.0.0? You don't want to look at the issue behind because it happens with a package being noted as alpha?

**Comment by NickIliev** [comment]
@farfromrefug I've just [retested with the alpha version](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-cli/issue-3728) and it is working as expected on my side. I've used [v2.0.0.alpha1](https://github.com/NickIliev/NS-Issues-2018-II/blob/master/nativescript-cli/issue-3728/package.json#L13)

I am not fond of testing an alpha version of third-party projects as these are still in development and their implementation can be changed in the final stage. However, providing a sample project is always a good practice as noted in the "New Issue" template

> ### Please tell us how to recreate the issue in as much detail as possible.
> 
> ### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
> Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by farfromrefug** [comment]
@NickIliev Actually I think the sample you have is enough. Now I am seeing it randomly when running ```tns run android```. It seems like sometimes the ```_lib``` folder is ignored. All other folders are there.
Obviously as it is random you can't really look at this. I get that. Will try to fix it myself

Thanks

**Comment by vincentpalita** [comment]
@farfromrefug: did you find a way to fix that?
thank you for getting back to me about that!

**Comment by farfromrefug** [comment]
@vincentpalita i have no fix for that. well I have a workaround. with web pack there is no issue as web pack handles the import 😉
