### ISSUE TITLE
Support path to *.jar file when adding a library.

### ISSUE THREAD

**Issue by slavchev** [NativeScript/nativescript-cli#373]
On Android side `library add` command should support path to `*.jar` file.

**Comment by dtopuzov** [comment]
Library add support *.jar files. Closing...

**Comment by isapir** [comment]
Is there any information on this, or a commit ID?  I want to add a JAR file to a NativeScript app (Svelte Native) and I am not sure where or how to add the Jars.

**Comment by triniwiz** [comment]
@isapir drop them in `App_Resources/Android/libs`

**Comment by isapir** [comment]
Thanks @triniwiz - that works.

I was trying things like that but couldn't find the right path.  

I will try to open a PR to add that info to https://v7.docs.nativescript.org/core-concepts/project-structure-app#appapp_resources

**Comment by NathanWalker** [comment]
That’d be super helpful @isapir - if they could be added here instead would be great:
https://docs.nativescript.org/app-resources.html

Source here: https://github.com/NativeScript/docs-new/blob/develop/app-resources.md

Even though right now it states regarding styling - I think we could create a new page out of a section you add to that document. If pr’d it we could then add other things to a new page about things like this.

**Comment by isapir** [comment]
@NathanWalker please see https://github.com/NativeScript/docs-new/pull/77
