### ISSUE TITLE
I can't access my java third party library

### ISSUE THREAD

**Issue by meSmashsta** [NativeScript/nativescript-cli#3730]
I've been everywhere, articles, your documentation (even read how the metadata works), issues relavant to mine but to no avail!

I wanted to use my declared java libraries in app/App_Resources/Android/app.gradle but it's undefined even if I call the complete name i.e `console.dir(de.mannodermaus.rxbonjour.BonjourEvent)`. The libraries are declared in my app.gradle file and I did run the `nts build android` command. I can access the JDK and ADK though i.e `console.dir(android.view.View)`

I can't access the libraries I have in my app.gradle, it's undefined.

### Which platform(s) does your issue occur on?
Android--I don't use IOS

`tns --version` 4.1.2
node_modules/tns-core-modules/package.json: "version": "4.1.0"
		"tns-android": {
			"version": "4.1.3"
		}
No tns-ios--my target platform is Android
No plugins

### Please tell us how to recreate the issue in as much detail as possible.
All I did was generate a simple nativescript typescript project, changed the app.gradle e.g min Sdk version to 19, target Sdk to 26., compile sdk version to 26, you can see my app.gralde [here](https://pastebin.com/BLGAJWeZ) oh and I also changed the android manifest which can be seen [here](https://pastebin.com/aGLAq7hB).

**Comment by NickIliev** [comment]
@meSmashsta For your convenience, I have created [this test project](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-3730) that is accessing the very same library. You can use it as a reference to compare your codebase with the test one. Let me know if you need further assistance.

**Comment by meSmashsta** [comment]
Brooooooooo, thank you!!!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1108
