### ISSUE TITLE
possibility of using nativescript.version to define version name and code ? 

### ISSUE THREAD

**Issue by championswimmer** [NativeScript/nativescript-cli#3754]
In Android we have these - 

```xml
    android:versionCode="00110"
    android:versionName="0.1.1"
```

In IOS we have these
```xml
		<key>CFBundleShortVersionString</key>
		<string>0.1.1</string>
		<key>CFBundleSignature</key>
		<string>????</string>
		<key>CFBundleVersion</key>
		<string>0.1.1</string>
```

Is it possible we simple pick the values from here in package.json - 

```json
{ ...
  "nativescript": {
    "version": {
      "string": "0.1.0",
      "code": "00110"
    }
  }
}
```

We already have this for the package name / bundle id

**Comment by Fatme** [comment]
@championswimmer,

I'm closing this thread as duplicated to https://github.com/NativeScript/nativescript-cli/issues/1118. You can track the progress of feature in the thread above.
