### ISSUE TITLE
Could not start simulator session  <Buffer@0x0 >

### ISSUE THREAD

**Issue by neurotech** [NativeScript/nativescript-cli#376]
After going through the installation process on OSX Yosemite and going through the quick start process:

```
tns create MyApp
tns platform add ios
tns run ios --emulator
```

I get the following error and the end of the build process:

```
** BUILD SUCCEEDED **

Project successfully built
Using  /Users/neurotech/tmp/nativescript/MyApp/platforms/ios/build/emulator/MyApp.app
Cleaning up before starting the iOS Simulator
Starting iOS Simulator
Specify the timeout in number of seconds to wait. It should be greater than 0. Default value 90 seconds will be used.
Could not start simulator session  <Buffer@0x0 >
```

Does anyone know how to fix this?

**Comment by rosen-vladimirov** [comment]
Hi @neurotech 
Can you try executing the command with --log trace option and send us the output:
```Shell
tns run ios --emulator --log trace
```
Also which version of XCode are you using?
You can try increasing the timeout by specifying --timeout 300 for example

**Comment by neurotech** [comment]
I have XCode 6.1 (6A1046a). 6.2 is out but the App Store doesn't think XCode needs to be updated. I am going to reinstall just to be sure.

Regardless here's the trace output: https://gist.github.com/neurotech/efe0674dd9b820c903db

**Comment by neurotech** [comment]
I am still getting the error after removing XCode 6.1 and installing 6.2. Here's the trace:

https://gist.github.com/neurotech/57f09cafce6bf64537c8

**Comment by Fatme** [comment]
Hi @neurotech,

Does starting simulator standalone from XCode work?

**Comment by neurotech** [comment]
Hi @Fatme,

Yes it works when launched from within XCode - I can browse the web with Safari, etc.

**Comment by Fatme** [comment]
Hi @neurotech,

This is very strange.. Can you try to execute `node <path to tns>\node_modules\ios-sim-portable\lib\ios-sim.js launch <path to your .app>`

`<path to your .app> should be <your project root>/platforms/ios/build/emulator`

**Comment by teobugslayer** [comment]
Hi @neurotech , can you please try with the latest release of the CLI -1.0.1?
