### ISSUE TITLE
tns build ios error with @types/jasmine and @types/mocha

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-cli#3774]
### Tell us about the problem
I am using NativeScript-dev-appium package with mocha for my e2e tests. I'm using standard Jasmine/Karma for my unit tests.
In my tsconfig, I exclude `node_modules` from my typescript compiler as such:
```
    "exclude": [
        "node_modules",
        "platforms",
        "e2e"
    ]
```
Yet when I run `tns build ios`, it tells me there is a duplicate identifier between the type files for mocha and jasmine.

### Which platform(s) does your issue occur on?
iOS/Android/Both

iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 4.1.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
4.1.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
```
    "tns-ios": {
      "version": "4.1.0"
    },
    "tns-android": {
      "version": "4.1.3"
    }
```
- Plugin(s): (look for the version number in the `package.json` file of your
project)
none

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-dev-appium#138

**Comment by kamok** [comment]
Nick, can you please reopen this. From my perspective this isn't really an issue with nativescript-dev-appium.

It's the `tns build ios` command that, for some reason, is reading my node_modules and complaining. Why does the `tns build ios` command care what types I use for my testing?

**Comment by kamok** [comment]
This issue can be fixed for anyone that encounters this, by adding to your ts-config, an empty types array (or any types you use aside from testing)

Adding types:[] will force the compiler to NOT automatically read all the @types in your node_modules.
