### ISSUE TITLE
feature(iOS) support Podfile in App_Resources/iOS folder

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#3775]
It would be very helpful to be able to have a Podfile in App_Resources/iOS which would be merged exactly like the plugin ones. Right now we need to modify the Podfile in platforms which won't resist a clean, but also I tried to modify it but the build system won't see the change and won't reinstall the pods.

The similar behaviour already works on Android.

**Comment by NickIliev** [comment]
Closing as duplicate to [https://github.com/NativeScript/ios-runtime/issues/939](https://github.com/NativeScript/ios-runtime/issues/939)

**Comment by farfromrefug** [comment]
@NickIliev sorry my bad didn't know this was handled in the ios-runtime. Though it was here like the gradle things.

**Comment by kenny-evitt** [comment]
NativeScript/ios-runtime#939 ended-up being moved to #3807 (back in this project) and has, since around February, been implemented.

**Comment by Fatme** [comment]
@kenny-evitt,

You're right - it was moved back to this repo and yes - the feature is already implemented.
