### ISSUE TITLE
Emulator cannot find ADB location And Cloud Id Needed

### ISSUE THREAD

**Issue by YoungLinkar** [NativeScript/nativescript-cli#3779]
Hi?
I started studing Nativescript with angular few weeks ago on my own computer. I went through this tutorial https://docs.nativescript.org/start/ns-setup-win to install everything needed for Android platform. 

At the end of the installation when I tested if everything was ok using tns doctor, I was told:
-My Computer was not able to make local buildings and need to try cloud buildings.

Then, I selected cloud buildings when I ran my first app, I had to sign up for an account.
So, I had to use: tns cloud run android command

When I thought everything was ok, suddenly on my emulator appeared a message:
"The emulator could not find the adb location"
After a while, another message on cmd:
"Could not save the project to emulator. Reason: please informe your cloud id"

AND AT THIS POINT the emulator does not receive anything and on cmd the process of building the app stopped.

Well, that's it!
This is the problem I have and  hope someone helps me!

My CLI version: 4.1.2
Platfom: Android (On windows 8 pro, 64 bits);

**Comment by NickIliev** [comment]
@YoungLinkar make sure that you have your environment variables `ANDROID_HOME` and `JAVA_HOME` set properly to the actual paths where Android SDK and JAVA are residing. Also, check if you have emulator images downloaded and installed.
```
tns devices android --available-devices
```

You can also share with us the out output from `tns doctor`

**Comment by YoungLinkar** [comment]
Hi?

I am very glad for your answer.

This is the output from tns doctor


[image: image.png]


Em seg, 30 de jul de 2018 às 08:17, Nick Iliev <notifications@github.com>
escreveu:

**Comment by YoungLinkar** [comment]
OUT PUT FROM

tns devices android --available-devices


[image: image.png]


Em seg, 30 de jul de 2018 às 14:55, Adelino Safeca <safeetyy@gmail.com>
escreveu:
