### ISSUE TITLE
ProjectTypes

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#378]
It would be nice if a project type can be specified - TypeScript, CoffeeScript or JavaScript.

Thus, having a TypeScript/CoffeeScript project, CLI would transpile them to JavaScript as a first step.

**Comment by enchev** [comment]
:+1:

**Comment by teobugslayer** [comment]
May I suggest alternate approach? We have hooks which are executed pre- & post- actions. The users are free to hook the tools they like. This way we are not limited to a particular compiler we support. The users can use traceur, coffeecript, typescript, linters, and everything else they need.

**Comment by ErjanGavalji** [comment]
That's freaking cool!

We'd need to provide an example then :)

**Comment by ligaz** [comment]
We have provided support for TypeScript, Babel, CoffeeScript and [others](https://www.npmjs.com/search?q=nativescript-dev). 

Support for TypeScript is also built-in using the `create` command with `--template typescript` option: https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/project/creation/create.md
