### ISSUE TITLE
Faster builds

### ISSUE THREAD

**Issue by milannankov** [NativeScript/nativescript-cli#380]
Being able to quickly test changes on an app is crucial which means that builds should be as fast as possible. At the moment building a bare-bones app for android is done in about 20 seconds. That might be okay for the initial build but consecutive builds with minor changes should take considerably less time.  Having no designer at the moment makes this issue much more important since the only way to see any UI changes is to build and deploy. 

Telerik NativeScript version - 0.9.4
Steps to reproduce: Create new NativeScript project and build using 'tns build android'

**Comment by teobugslayer** [comment]
Hello @milannankov , we are aware of the issue and already working on a fix. You can follow https://github.com/NativeScript/android-runtime/issues/47 for details. Closing this one as a duplicate.
