### ISSUE TITLE
feature: Enable app Podfile

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3807]
_From @DickSmith on June 10, 2018 21:59_

Sometimes a project just needs to add a `Podfile` without any JS/TS, but a full plugin must be created:
1. https://github.com/tjvantoll/nativescript-IQKeyboardManager (Until recently was only a podfile)
0. https://github.com/Essent/nativescript-disable-bitcode (just a postinstall to strip all bitcode from a project).

Additionally, this is where a project should be able to set its platform version level, as well. (and plugin Podfiles should not).

In many ways this is similar to many of the settings and package management actions that can be taken in `app.gradle` (dependencies not requiring JS, package overrides, and min platform).

Would likely just come from `App_Resources` like similar files.

_Copied from original issue: NativeScript/ios-runtime#939_

**Comment by NickIliev** [comment]
+1 from a slack conversation with a client

**Comment by DickSmith** [comment]
@NickIliev 
I've documented my current workaround in this blog post if your would like to share it with any of your other clients currently awaiting this feature.

**Comment by NickIliev** [comment]
@DickSmith yeah for sure! I would like to share! :)

I am not seeing the blog post link thou...

**Comment by DickSmith** [comment]
@NickIliev https://nstudio.io/blog/nativescript-app-specific-podfile/
Link screwed up before, sorry.

**Comment by rosen-vladimirov** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/3604

**Comment by Fatme** [comment]
Acceptance criteria:

* Ensure the Podfile from `App_Resources` is correctly merged in platforms folder
* Ensure the application is successfully run on device when Podfile in `App_Resources`
* Ensure the content from project's podfile is removed when Podfile in `App_Resources` is removed
