### ISSUE TITLE
3rd party libraries without simulator architecture fail on run in sumulator

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#383]
Shared frameworks without simulator slice can be added, but when run in simulator the project builds and runs without problems, however the symbols they export result in 'undefined' at runtime.

This is quite tricky for development. We should consider adding warnings on `tns library add ios` when some slices are missing.

We should also try to warn for missing architectures in the libraries when we build or run the app.

**Comment by teobugslayer** [comment]
We have deprecated `library add` and will remove it in a future version of NativeScript.
