### ISSUE TITLE
The livesync check if a file has modifications doesn't work as expected

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-cli#3849]
### Tell us about the problem
Saving a file with no changes causes a sync of a running app.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.2
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1) `tns run` any app
2) save any of its files
3) the app the synced even though there are no changes that needs to be synced

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by aasci** [comment]
I have same problem.

**Comment by endarova** [comment]
I am reproducing this only when opening file directly from the file system on macOs. Find the file in Finder, open it in any editor and save without changes - livesync is triggered.
