### ISSUE TITLE
TextField data binding ignores last edit operation on ios

### ISSUE THREAD

**Issue by brianchirls** [NativeScript/nativescript-cli#385]
If you simply type some text, the last letter will be ignored. If you edit the text in the field, whatever the last operation is - whether adding a character or removing it - the result will always be one operation behind.

Seems fine in Android.

(version 0.9.4)

**Comment by brianchirls** [comment]
This might be the same as this other issue:
https://github.com/NativeScript/cross-platform-modules/issues/122

**Comment by teobugslayer** [comment]
Hi @brianchirls, this repository is dedicated to the nativescript cli tooling. Please follow https://github.com/NativeScript/cross-platform-modules/issues/122 for the resolution of the issue. I am closing this one.
