### ISSUE TITLE
How to include SDK (C++) and libraries (*.so) in {N} plugin

### ISSUE THREAD

**Issue by natatatata** [NativeScript/nativescript-cli#3855]
Hi,

I am new with `{N}`, and I am trying to create a plugin using [VisionLabs](https://visionlabs.ai/index.html) & [Face++](https://www.faceplusplus.com/)'s SDK . I am lost on how to start the plugin using the [Nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed).

Any tips and suggestions are very much delighted.
Thanks!

**Comment by NickIliev** [comment]
@natatatata  NativeScript framework works with the native Android Java aar or jar packages) and iOS  Objective-C static/shared libraries and Cocoa Pods. 

There is no official support for C++libraries (see this response [here](https://github.com/NativeScript/NativeScript/issues/2680#issuecomment-245296131))
