### ISSUE TITLE
Unable to debug at all on Android

### ISSUE THREAD

**Issue by brianchirls** [NativeScript/nativescript-cli#386]
When I run `tns debug android --debug-brk --log trace`, the build process runs and the app is launched on the device (or emulator if no device is plugged in), and then it immediately crashes (presumably because of a bug in my code somewhere). Chrome is not launched, and there is nothing listening on port 8080.

Output is here: https://gist.github.com/brianchirls/60b4fc05e225ace40f38

Possibly related to #359, but probably not the same thing, since that guy can get it working on his device and I can't.

Also, in all the commands in the [debugger documentation](http://docs.nativescript.org/runtimes/android/debug/debug-cli), "android" is misspelled as "andorid."

```
tns debug andorid --debug-brk
```

**Comment by teobugslayer** [comment]
Hi @brianchirls,
Indeed, looking at the supplied log it seems that the 30-second timeout is insufficient. Could you follow the advice from https://github.com/NativeScript/nativescript-cli/issues/359#issuecomment-85998150

**Comment by brianchirls** [comment]
Thanks @teobugslayer. That kind of works a little. It doesn't launch Chrome, but it does pause the application and set up the debugger But once the app stops (usually because it crashes), there doesn't seem to be any way to debug it again, unless I find the node process that's listening on 8080 and kill that first. It makes for a very slow debugging process.

The bigger problem is that if there is an uncaught exception in Javascript, the app dies, and the debugger disconnects. So there's no way to find out what the error was. For some code, I can just wrap everything in a try...catch, which is far from idea. But sometimes the app crashes right as it starts, and Io can't seem to catch it. Is there a way around this? Node Inspector doesn't seem to have an option to pause on uncaught exceptions.

Also, not sure if this is helpful, but I'm seeing this error in the debugger console:
```
Page.getResourceTree failed.
ReferenceError: process is not defined
```

**Comment by teobugslayer** [comment]
Hello @brianchirls ,

Thank you for feedback. 
We will significantly improve the debugging experience for the upcoming 1.0 release. We aim to resolve the underlying issue and allow debugging of startup crashes.

**Comment by getsetbro** [comment]
+1
`tns debug android --debug-brk`
results in:
"Page.getResourceTree failed. ReferenceError: process is not defined"

**Comment by dtopuzov** [comment]
Closing this issue, see https://github.com/NativeScript/nativescript-cli/issues/661

**Comment by mhh1422** [comment]
Any update on this issue? I am getting same error mentioned in by getsetbro and can not debug yet!

**Comment by gillestasse** [comment]
I got the same issue on a fresh install of NativeScript

**Comment by sushruth** [comment]
Please give more information about why an issue has been closed. I went looking through all the related issues about this and could not find any useful information. 

I still see this issue.

**Comment by WagnerSilveira** [comment]
@sushruth 

Close you application, and launch it again  in your phone and then refresh  your dbug page http://127.0.0.1:8080/debug?port=40000
It is not a solution, but someway you can test your aplication 

Regards
