### ISSUE TITLE
zlib: unexpected end of file

### ISSUE THREAD

**Issue by Josh10Martin** [NativeScript/nativescript-cli#3862]
I've installed nativesript and want to add the android platform using the "tns platform add android" command but I get this error afterwards:  zlib: unexpected end of file. There is another error some lines down: ENOTEMPTY: directory not empty, rmdir 'C:\Users\JOSHUA~1\AppData\Local\Temp\runtimeDir11883-12948-14y5jxw.sofj\framework\app\libs\runtime-lib. I do not know what it means exactly... This is the whole response:

$ tns platform add android
Copying template files...
**zlib: unexpected end of file**
# tns platform add

┌───────────────┬────────────────────────────────────────────────────────────┐
│ Usage         │ Synopsis                                                   │
│ Android       │ $ tns platform add android [--framework-path <File Path>]  │
│ latest        │ [--symlink] [--sdk <API Level>] [--platform-template       │
│ runtime       │ <Platform Template>]                                       │
│ Android       │ $ tns platform add android[@<Version>] [--framework-path   │
│ selected      │ <File Path>] [--symlink] [--sdk <API Level>] [--platform   │
│ runtime       │ -template <Platform Template>]                             │
└───────────────┴────────────────────────────────────────────────────────────┘

Configures the current project to target the selected platform.

### Options

    * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package.
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is
not specified, creates a symlink to platform runtime installed with your current
version of NativeScript.
    * --sdk - Sets the target Android SDK for the project.
    * --platform-template - Sets the platform template that will be used for the
native application.

### Attributes

    * <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.
    * <Version> is any available version of the respective platform runtime published in npm.

**ENOTEMPTY: directory not empty, rmdir 'C:\Users\JOSHUA~1\AppData\Local\Temp\runtimeDir11883-12948-14y5jxw.sofj\framework\app\libs\runtime-libs'**
# tns platform

┌─────────┬─────────────────────┐
│ Usage   │ Synopsis            │
│ General │ $ tns platform list │
└─────────┴─────────────────────┘

Lists all platforms that the project currently targets. You can build and deploy
your project only for these target platforms.

**Comment by pujiaolin** [comment]
me，too

windows 10  + nativescript 4.2.3

`tns create app001`
`cd app001`
`tns run android`

### then get error :
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Copying template files...
Unable to apply changes on device: A5RNW17A14072452. Error is: zlib: unexpected end of file.
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\admin\AppData\Local\Temp\runtimeDir118810-19280-1hkqgj2.jyd4g\framework\app\libs\runtime-libs'
    at Object.rmdirSync (fs.js:677:3)
    at rmkidsSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)

**Comment by rosen-vladimirov** [comment]
Hey @pujiaolin , @Josh10Martin ,
Can you please execute `tns platform add android --log trace` and send us the full output, so we can investigate it on our side?

**Comment by pujiaolin** [comment]
@rosen-vladimirov 
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
System information:
{ platform: 'win32',
  shell: 'C:\\WINDOWS\\system32\\cmd.exe',
  os: 'Windows 10 Pro 6.3.17134',
  procArch: 'x64',
  nodeVer: '10.10.0',
  npmVer: '6.4.1',
  nodeGypVer: null,
  nativeScriptCliVersion: '4.2.3',
  gitVer: '2.13.0.windows.1',
  dotNetVer: '4.7.03056',
  javacVersion: '1.8.0_181',
  adbVer: '1.0.40',
  androidInstalled: true,
  monoVer: null,
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: undefined,
  xcodeprojLocation: null,
  itunesInstalled: false,
  cocoaPodsVer: undefined,
  isCocoaPodsWorkingCorrectly: false,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: null }
Starting watch on killswitch C:\Users\admin\AppData\Local\Temp\admin\KillSwitches\cli
Looking for project in 'D:\workspace\app001'
Project directory is 'D:\workspace\app001'.
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: { cd5: 'CLI' } }
spawn: node "C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\lib\services\analytics\analytics-broker-process.js" "C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\lib\bootstrap.js"
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: true',
  customDimensions: { cd5: 'CLI' } }
Installed Android Targets are:  [ 'android-25', 'android-26', 'android-28' ]
Directories found in C:\Android\android-sdk\build-tools are 26.0.1, 26.0.3, 27.0.3, 28.0.2
Versions found in C:\Android\android-sdk\build-tools are 26.0.1, 26.0.3, 27.0.3, 28.0.2
Selected version is:  27.0.3
Selected targetSdk is: 26
Directories found in C:\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0-alpha1, 24.0.0-alpha2, 24.0.0-beta1, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0
-alpha1, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in C:\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0, 24.0.0, 24.0.0, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0
Selected version is:  26.0.0-alpha1
Selected AppCompat version is: 26.0.0-alpha1
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'pageview',
  path: 'platform add',
  title: 'platform add',
  customDimensions: { cd5: 'CLI' } }
Creating NativeScript project for the android platform
Path: D:\workspace\app001\platforms\android
Package: org.nativescript.app001
Name: app001
Copying template files...
- Calling pacoteService.extractPackage for packageName: 'tns-android@4.2.0', destinationDir: 'C:\Users\admin\AppData\Local\Temp\runtimeDir118811-3564-pqpesd.rb8i' and options: undefined
- Exec npm config get cache
 stdout: C:\Users\admin\AppData\Roaming\npm-cache

 stderr:
Calling pacoteService.extractPackage for packageName: 'tns-android@4.2.0', destinationDir: 'C:\Users\admin\AppData\Local\Temp\runtimeDir118811-3564-pqpesd.rb8i' and options: undefined
Creating extract tar stream with options: {
  "strip": 1,
  "C": "C:\\Users\\admin\\AppData\\Local\\Temp\\runtimeDir118811-3564-pqpesd.rb8i"
}
\ Error in destination while trying to extract stream from tns-android@4.2.0. Error is ZlibError: zlib: unexpected end of file
ZlibError: zlib: unexpected end of file
    at Zlib.(anonymous function).onerror (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:131:21)
    at Unzip.write (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:255:31)
    at Unzip.flush (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:222:10)
    at Unzip.end (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:229:10)
    at Unpack.end (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\tar\lib\parse.js:415:21)
    at PassThrough.onend (_stream_readable.js:628:10)
    at Object.onceWrapper (events.js:273:13)
    at PassThrough.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
List of registered commands: /?, accept, accept|eula, account, account|features, account|usage, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|cloud, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|build, cloud|clean|workspace, cloud|codesign, cloud|deploy, cloud|lib|version, cloud|publish|android, cloud|publish|io
s, cloud|run|*all, cloud|run|android, cloud|run|ios, cloud|setup, codesign, codesign|cloud, config, config|apply, config|reset, config|set, create, debug, debug|android, debug|ios, deploy, deploy|cloud, dev-generate-help, dev-generate-messages, dev-login, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|io
s, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, kill-server, login, logout, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|build, plugin|install, plugin|remove, plugin|update, po
licy, policy|accept, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, resources, resources|generate|icons, resources|generate|splashes, resources|update, run, run|android, run|cloud|*all, run|cloud|android, run|cloud|ios, run|ios, setup, setup|cloud, test, test|android, test|init, test|ios, update, usage-reporting, user
Reading help for command 'platform|add'. FileName is 'platform-add.md'.
# tns platform add

┌──────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                    │ Synopsis                                                                                                                                        │
│ Android latest runtime   │ $ tns platform add android [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>]             │
│ Android selected runtime │ $ tns platform add android[@<Version>] [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>] │
└──────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Configures the current project to target the selected platform.

### Options

    * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package.
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
    * --sdk - Sets the target Android SDK for the project.
    * --platform-template - Sets the platform template that will be used for the native application.

### Attributes

    * <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.
    * <Version> is any available version of the respective platform runtime published in npm.

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\admin\AppData\Local\Temp\runtimeDir118811-3564-pqpesd.rb8i\framework\app\libs\runtime-libs'
    at Object.rmdirSync (fs.js:677:3)
    at rmkidsSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\admin\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
List of registered commands: /?, accept, accept|eula, account, account|features, account|usage, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|cloud, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|build, cloud|clean|workspace, cloud|codesign, cloud|deploy, cloud|lib|version, cloud|publish|android, cloud|publish|io
s, cloud|run|*all, cloud|run|android, cloud|run|ios, cloud|setup, codesign, codesign|cloud, config, config|apply, config|reset, config|set, create, debug, debug|android, debug|ios, deploy, deploy|cloud, dev-generate-help, dev-generate-messages, dev-login, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|io
s, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, kill-server, login, logout, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|build, plugin|install, plugin|remove, plugin|update, po
licy, policy|accept, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, resources, resources|generate|icons, resources|generate|splashes, resources|update, run, run|android, run|cloud|*all, run|cloud|android, run|cloud|ios, run|ios, setup, setup|cloud, test, test|android, test|init, test|ios, update, usage-reporting, user
Reading help for command 'platform'. FileName is 'platform.md'.
# tns platform

┌─────────┬─────────────────────┐
│ Usage   │ Synopsis            │
│ General │ $ tns platform list │
└─────────┴─────────────────────┘

Lists all platforms that the project currently targets. You can build and deploy your project only for these target platforms.

**Comment by rosen-vladimirov** [comment]
Hey @pujiaolin ,
Thanks for the provided log. Can you please try cleaning your npm cache:
```
npm cache clean --force
```
After that, please manually delete the `C:\Users\admin\AppData\Roaming\npm-cache` directory (the npm cache clean command sometimes does not clear the whole cache) and try `tns platform add android` again.

Also can you try creating a dir in `C:\Users\admin\AppData\Local\Temp` manually, just to ensure your user have the correct privileges. Also do you run NativeScript CLI from an administrator's CMD? In case yes, can you please try from a normal non-admin CMD ?

**Comment by Josh10Martin** [comment]
tns platform add android --log trace
Loading extensions.
System information:
{ platform: 'win32',
  shell: 'C:\\WINDOWS\\system32\\cmd.exe',
  os: 'Windows 10 Pro 6.3.17134',
  procArch: 'x64',
  nodeVer: '9.1.0',
  npmVer: '6.4.1',
  nodeGypVer: null,
  nativeScriptCliVersion: '4.2.3',
  gitVer: '2.15.1.windows.2',
  dotNetVer: '4.7.03056',
  javacVersion: '1.8.0_181',
  adbVer: '1.0.40',
  androidInstalled: true,
  monoVer: null,
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: undefined,
  xcodeprojLocation: null,
  itunesInstalled: false,
  cocoaPodsVer: undefined,
  isCocoaPodsWorkingCorrectly: false,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: null }
Starting watch on killswitch C:\Users\JOSHUA~1\AppData\Local\Temp\JoshuaMMbewe\KillSwitches\cli
Looking for project in 'C:\Users\JoshuaMMbewe\movieRaterMobile'
Project directory is 'C:\Users\JoshuaMMbewe\movieRaterMobile'.
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
Installed Android Targets are:  [ 'android-23', 'android-28' ]
Directories found in C:\Users\JoshuaMMbewe\AppData\Local\Android\Sdk\build-tools are 27.0.3, 28.0.2
Versions found in C:\Users\JoshuaMMbewe\AppData\Local\Android\Sdk\build-tools are 27.0.3, 28.0.2
Selected version is:  27.0.3
Selected targetSdk is: 23
Directories found in C:\Users\JoshuaMMbewe\AppData\Local\Android\Sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0,
23.4.0, 24.0.0, 24.0.0-alpha1, 24.0.0-alpha2, 24.0.0-beta1, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0-alpha1, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in C:\Users\JoshuaMMbewe\AppData\Local\Android\Sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0, 24.0.0, 24.0.0, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0
Selected version is:  23.4.0
Selected AppCompat version is: 23.4.0
Creating NativeScript project for the android platform
Path: C:\Users\JoshuaMMbewe\movieRaterMobile\platforms\android
Package: org.nativescript.movieRaterMobile
Name: movieRaterMobile
Copying template files...
- Calling pacoteService.extractPackage for packageName: 'tns-android@4.2.0', destinationDir: 'C:\Users\JOSHUA~1\AppData\Local\Temp\runtimeDir118811-11360-iibq1i.6bze' and options: undefined
\ Exec npm config get cache
 stdout: C:\Users\JoshuaMMbewe\AppData\Roaming\npm-cache

 stderr:
Calling pacoteService.extractPackage for packageName: 'tns-android@4.2.0', destinationDir: 'C:\Users\JOSHUA~1\AppData\Local\Temp\runtimeDir118811-11360-iibq1i.6bze' and options: undefined
Creating extract tar stream with options: {
  "strip": 1,
  "C": "C:\\Users\\JOSHUA~1\\AppData\\Local\\Temp\\runtimeDir118811-11360-iibq1i.6bze"
}
\ Error in destination while trying to extract stream from tns-android@4.2.0. Error is ZlibError:
zlib: unexpected end of file
ZlibError: zlib: unexpected end of file
    at Zlib.(anonymous function).onerror (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:131:21)
    at Unzip.write (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:255:31)
    at Unzip.flush (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:222:10)
    at Unzip.end (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\minizlib\index.js:229:10)
    at Unpack.end (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\tar\lib\parse.js:415:21)
    at PassThrough.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:322:30)
    at emitNone (events.js:120:20)
    at PassThrough.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|setup, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|build, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, resources, resources|generate|icons, resources|generate|splashes, resources|update, run, run|android, run|ios,
setup, setup|cloud, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'platform|add'. FileName is 'platform-add.md'.
# tns platform add

┌───────────────┬─────────────────────────────────────────────────────────────────────────────┐
│ Usage         │ Synopsis                                                                    │
│ Android       │ $ tns platform add android [--framework-path <File Path>] [--symlink] [-    │
│ latest        │ -sdk <API Level>] [--platform-template <Platform Template>]                 │
│ runtime       │                                                                             │
│ Android       │ $ tns platform add android[@<Version>] [--framework-path <File Path>] [-    │
│ selected      │ -symlink] [--sdk <API Level>] [--platform-template <Platform Template>]     │
│ runtime       │                                                                             │
└───────────────┴─────────────────────────────────────────────────────────────────────────────┘

Configures the current project to target the selected platform.

### Options

    * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path>
must point to a valid npm package.
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you
want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to
the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
    * --sdk - Sets the target Android SDK for the project.
    * --platform-template - Sets the platform template that will be used for the native application.

### Attributes

    * <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.
    * <Version> is any available version of the respective platform runtime published in npm.

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\JOSHUA~1\AppData\Local\Temp\runtimeDir118811-11360-iibq1i.6bze\framework\app\libs\runtime-libs'
    at Object.fs.rmdirSync (fs.js:866:18)
    at rmkidsSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\JoshuaMMbewe\AppData\Roaming\npm\node_modules\nativescript\node_modules\rimraf\rimraf.js:150:5)
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|setup, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|build, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, resources, resources|generate|icons, resources|generate|splashes, resources|update, run, run|android, run|ios,
setup, setup|cloud, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'platform'. FileName is 'platform.md'.
# tns platform

┌─────────┬─────────────────────┐
│ Usage   │ Synopsis            │
│ General │ $ tns platform list │
└─────────┴─────────────────────┘

Lists all platforms that the project currently targets. You can build and deploy your project only for these target platforms.

**Comment by rosen-vladimirov** [comment]
Hey @Josh10Martin ,
Can you try cleaning your `npm cache` - just delete the `C:\Users\JoshuaMMbewe\AppData\Roaming\npm-cache` directory and try `tns platform add android` again.

**Comment by Josh10Martin** [comment]
It worked. Thank you very much

**Comment by mhmo91** [comment]
On Mac ```npm cache clean --force``` 
OR delete ~users/${username}/.npm/_cacache

**Comment by badrihippo** [comment]
Just a note: this error seems to arise when a file hasn't been downloaded properly. So make sure your Internet is working well before retrying the command, else you'll run into the error again. It took me several failed attempts before I realised.
