### ISSUE TITLE
[Question] Check if --syncAllFiles flag was passed when running app

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3865]
_From @aaayushsingh on September 3, 2018 18:47_

I have a hook that needs to check if `tns run <platform> --syncAllFiles` was used or just `tns run <platform>`. Basically I need to check for `--syncAllFiles` flag. I couldn't find a resource for this.

or is there another way to execute a hook on full build and ignore otherwise?

_Copied from original issue: NativeScript/NativeScript#6236_

**Comment by rosen-vladimirov** [comment]
`syncAllFiles` option will not exist in NativeScript 6.0.0. @aaayushsingh , is there a reason you needed syncAllFiles in hooks ?

**Comment by aaayushsingh** [comment]
@rosen-vladimirov it came in handy when trying to debug errors in a plugin I was using.

Why is this being removed? Incompatible with the new mandatory bundling when running?

**Comment by rosen-vladimirov** [comment]
Hey @aaayushsingh ,
The flag will be removed as in 6.0.0 release CLI will watch all required files in node_modules by default. We would like to streamline the development of plugins (which is the use-case for adding syncAllFiles option in the past), so we decided to make it as easier as possible, i.e. skip all custom options.
