### ISSUE TITLE
Read registry from npm config instead of hard-wiring to npmjs.org in node-package-manager

### ISSUE THREAD

**Issue by lambourn** [NativeScript/nativescript-cli#3866]
We use artifactory as a our internal npm repository. It mirrors npmjs.org and also allow us to push internal npm packages to it.

However, when we do a clean install/build using `tns build android` the nativescript-cli itself starts a http client to pull the tns-android package from npmjs.org:

https://github.com/NativeScript/nativescript-cli/blob/f0e150ca8b2988bb23caafa2e239ee91cc8cde14/lib/node-package-manager.ts#L123

this does not work for us. 

Ideally, inside the `getRegistryPackageData` the registry to use should be read from the npm config (.npmrc)

**Comment by lambourn** [comment]
just fixed it locally, happy to open a PR, just submitted my CLA

**Comment by rosen-vladimirov** [comment]
Hey @lambourn , thanks for reporting the issue and preparing a fix. We'll be glad to review it!

**Comment by lambourn** [comment]
@rosen-vladimirov no permission for me to push my branch

**Comment by rosen-vladimirov** [comment]
Hey @lambourn ,
You have to fork the repo and create a pull request from the fork. As you have already cloned the current repo, you can fork it and just change the `origin` remote in your local copy:
```
$ git remote -v # this will print the current origin, which probably points to CLI
$ git remote set-url origin <the url of your fork>
$ git remote -v # this will print the current origin, which must now point to your fork of CLI
$ git push origin <your branch>
```
After that you can open your GitHub repository and create a PR - GitHub will allow you to target CLI's original repository and this way you'll create a PR in this repo.

More information can be found [here](https://help.github.com/articles/changing-a-remote-s-url/) and [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by lambourn** [comment]
thanks @rosen-vladimirov - it looked as if I'd need to sign the CLA but if opening the PR from the fork works then that's also fine.
