### ISSUE TITLE
After update "tns run" always crashes vscode (Native Script Extension).

### ISSUE THREAD

**Issue by zzador** [NativeScript/nativescript-cli#3871]
I did an complete update:

   npm install -g nativescript

and within app folder:

   tns update

After the update the command "tns run andoid" always leads to a total crash of VSCODE and therefore makes it impossible to run "tns run" from within VSCODE.

After disabling the NativeScript extension within VSCODE however the app could be started again over the integrated terminal.

**Comment by NickIliev** [comment]
@zzador can you post the versions of your CLI and VSCode extension (try updating both to latest).
If there is an error message before the crash please post it here.

**Comment by zzador** [comment]
Component nativescript has 4.2.3 version and is up to date.
Component tns-core-modules has 4.2.0 version and is up to date.
Component tns-android has 4.2.0 version and is up to date.
Component tns-ios has 4.2.0 version and is up to date.


NativeScript VSCode-Extension 0.8.1

**Comment by NickIliev** [comment]
Using the latest VSCode extension 0.8.2 and the latest NativeScript I am not able to reproduce the issue. Please do let us know if the crash is outputting some errors so we could investigate further.
