### ISSUE TITLE
Feature Request: allow specifying default flags in package.json

### ISSUE THREAD

**Issue by rigor789** [NativeScript/nativescript-cli#3873]
It would be convenient to allow setting default flags for tns commands in `package.json`

For example
```json
{
  "nativescript": {
    "id": "com.nativescript.application",
    "defaults": {
      "bundle": true 
    },
    "tns-ios": {},
    "tns-android: {}
  }
}
```
would force the `--bundle` flag when running `tns run android/ios`

This would make it easier to work on projects that require bundling (nativescript-vue for example must be bundled to compile .vue files) without having to remember to use `--bundle`.

**Comment by rosen-vladimirov** [comment]
This is now possible by setting `"useLegacyWorkflow": false` in your `nsconfig.json file. More information is available here: https://docs.nativescript.org/core-concepts/project-structure#nsconfigjson-enabling-hmr-example
