### ISSUE TITLE
CLI installs the app on every change

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#3883]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
When a change is made the application gets installed every time. Previously sync changes are overwritten.

### Which platform(s) does your issue occur on?
Android Pie
Windows workstation

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.3(run `tns --version` to fetch it)
- Cross-platform modules: 4.2.0(check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): 4.2.0(look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
`tns run android` with Android P device on a Windows workstation.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by KristianDD** [comment]
Hi @Aceman18,
There might be a couple of reasons that cause that behavior and are out of our control. For example there is a size limit of the `(...)/data/local/tmp` folder in some Android devices and when this limit is reached on the device, the CLI can't work properly.

Try the solution described [here](https://github.com/NativeScript/sidekick-feedback/issues/256#issuecomment-419008025).

If cleaning up the `(...)/data/local/tmp` folder doesn't solve the issue please run the command with
`--log trace > clilog.txt` at the end and then modify something in the project in order to trigger a livesync operation. This will produce a `clilog.txt` file in the application directory. Please attach the log file to your response.

**Comment by Aceman18** [comment]
Over the last few days it seems to be working fine. Maybe it was that one day? But its fine now. Thank you for taking the time to write the response.

**Comment by cerireyhan** [comment]
@Aceman18  You have to delete and reinstall node modules/hooks/platforms after updating the cli.
