### ISSUE TITLE
Support tns_modules from npm

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/nativescript-cli#390]
A NativeScript application package must not contain the `tns_modules` it uses. These should be available through [npmjs.org](http://www.npmjs.org). Utilizing the dependencies in the package.json file (see #362), the CLI would retrieve the modules the application depends on.

**Comment by ErjanGavalji** [comment]
Package name is [tns-core-modules](https://github.com/NativeScript/NativeScript/blob/master/package.json)

**Comment by vchimev** [comment]
https://github.com/NativeScript/nativescript-cli/issues/854
