### ISSUE TITLE
data binding template selector in ListView fails

### ISSUE THREAD

**Issue by jokro** [NativeScript/nativescript-cli#3908]
In [Playground Nativescript](https://play.nativescript.org/?template=play-js&id=h0dxyU&v=23) I have adapted the ListView example with multiple templates. Two buttons show the age of two persons. The age of each person selects a template, hence one button appears red the other green.

A tap of the button changes its age. The new age is correctly displayed. Hence databinding is working for text. The color is not changing accordingly, meaning that the changed age is not propagated to the itemselector key.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#6280
