### ISSUE TITLE
App_Resources android files not copied to platforms

### ISSUE THREAD

**Issue by crkjl** [NativeScript/nativescript-cli#3915]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

I've not found this issue.

### Tell us about the problem

I’ve added a strings.xml and colors.xml to App_Resources/Android/values and values-v21 directory but when I run the project these files are not copied to platforms directory and no changes appear in my app.

### Which platform(s) does your issue occur on?

Android

### Please provide the following version numbers that your issue occurs with:

- CLI: **4.2.3**
- Cross-platform modules: **4.2.1**
- Runtime(s): **4.2.0**
- Plugin(s): 

```
{
  "nativescript": {
    "id": "com.visiblesoft.velamobile",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "description": "CCR Vela Mobile",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "^6.1.8",
    "@angular/common": "^6.1.8",
    "@angular/compiler": "^6.1.8",
    "@angular/core": "^6.1.8",
    "@angular/forms": "^6.1.8",
    "@angular/http": "^6.1.8",
    "@angular/platform-browser": "^6.1.8",
    "@angular/platform-browser-dynamic": "^6.1.8",
    "@angular/router": "^6.1.8",
    "nativescript-angular": "^6.1.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.3.2",
    "tns-core-modules": "^4.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.1.8",
    "@ngtools/webpack": "^6.2.3",
    "nativescript-dev-typescript": "^0.7.4",
    "nativescript-dev-webpack": "^0.16.1",
    "typescript": "^2.9.2"
  },
  "readme": "NativeScript Application"
}
```

### Please tell us how to recreate the issue in as much detail as possible.

I've created a colors.xml and strings.xml in App_Resources/Android/values and values-v21 directories with the app name and some colors changed from the default colors.

I will start with a clean of my project:
Delete node_modules
Install npm dependencies
Run "tns platform remove android"
Run "tns platform add android" or directly "tns run android"

colors.xml and strings.xml in platform directory are the default ones and not my customizations.

I've tested this issue in two different systems (Windows and Mac) with the same result.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

No

**Comment by NickIliev** [comment]
@crkjl with NativeScript 4.x.x the project structure was aligned with the native one and currently the new project template is as follows: **_app/App_Resources/Android/src/main/res/values_**

To avoid having to manually update your resources folders (including the drawable and the location of files like AndoirdManifes.xml or app.gradle) the NativeScript CLI has introduced a command to automatically migrate your resources to the new project structure. Full details about the resources update command can be found in [this documentation article](https://docs.nativescript.org/tooling/docs-cli/project/configuration/resources/resources-update).

To migrate to the new structure you need to run the follwing command
```
tns resources update
```

With the new structure applied the files should trigger an applicaiton rebuild (if **tns run android** command is executed prior  to their change

**Comment by crkjl** [comment]
@NickIliev you are right. It was a problem with the directory structure change.
Now is working fine.
Thank you very much!
