### ISSUE TITLE
targetSdkVersion min requrment API26 from 1st of November

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3921]
Consider making the default **targetSdkVersion** 26 when a new project is created via the CLI.

> 
> Hello Google Play Developer,
>
>This is a reminder that starting November 1, 2018, updates to apps and games on Google Play will  be required to target Android Oreo (API level 26) or higher. After this date, the Play Console will  prevent you from submitting new APKs with a targetSdkVersion less than 26.
> 
> Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion).
> 
> **Action required**
> Please ensure that your apps are configured to target at least Android 8.0 (API level 26) by November 1, 2018. For technical advice on how to change your app's target API level to meet these requirements, refer to the migration guide.
> 
> **Affected apps**
> The apps included below have one or more APKs—in production or testing tracks—that aren't currently targeting API level 26 or higher. Apps are listed with the maximum version code and corresponding targetSdkVersion. If you have more than 20 apps that could be affected in your account, please check the Play Console for a full list.

**Comment by dtopuzov** [comment]
As of {N} 5.0 we set `targetSdkVersion=28` by default.
