### ISSUE TITLE
Unable to build when app contains .gz file

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#393]
In case the app contains .gz file, build for android fails on package-resources step:
-package-resources:
     [aapt] Creating full resource package...
     [aapt]       Unable to add 'd:\Work\scratch\app1\platforms\android\assets\app\app\app.js.gz': file already in archive (try '-u'?)
     [aapt] ERROR: unable to process assets while packaging 'd:\Work\scratch\app1\platforms\android\bin\app1.ap_'
     [aapt] ERROR: packaging of 'd:\Work\scratch\app1\platforms\android\bin\app1.ap_' failed

BUILD FAILED
d:\Program Files\android_sdk\tools\ant\build.xml:932: The following error occurred while executing this line:
d:\Program Files\android_sdk\tools\ant\build.xml:950: null returned: 1

### Steps to reproduce:
* Create project: `tns create app1`
* `cd app1`
* `tns platform add android`
* `cd app/app/`
* create gzip in this directory or copy one from somewhere
* `tns build android`

**Comment by rosen-vladimirov** [comment]
Note, the issue has high impact, when your app contains node_modules, some of them, like semver, contain .gz files

**Comment by rosen-vladimirov** [comment]
This issue is no longer relevant, it is related to ant, but from CLI 1.3.0, we are using Gradle for Android builds.
So I'm going to close this issue :)

**Comment by gausie** [comment]
I'm still getting this even with Gradle.

**Comment by rosen-vladimirov** [comment]
Hi @gausie 
May I ask you for more information on this case, what is your CLI's version and which android runtime are you using? Can you give us steps to reproduce this case?

**Comment by rajuashok** [comment]
I'm getting "Zip add failed":

      Unable to add '/Users/****/src/******/*****/app/build/intermediates/assets/debug/native-config/asef439406aae92bbba6b.js.gz': Zip add failed (-2147483648)

This file was added to my assets folder. If I change the file to a .mp3 extension then it works, but I need the .gz file to be used in my app.

**Comment by josx** [comment]
Its an aapt problem.
Maybe you can delete .gz files before building.
