### ISSUE TITLE
Require Android SDK 28 for compilation

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#3991]
Currently applications can be build for Android with SDK 22 or above. However, with latest changes in tns-core-modules, applications cannot be build with SDK lower than 28. The problem is that the we've set min version of Android Support Library to be 28, which cannot be build with anything less than SDK 28. Trying to build such app with SDK 27 for example leads to error for missing resources.
So we need to set min required SDK for building to be 28.
Related issue: https://github.com/NativeScript/NativeScript/issues/6331

**Comment by endarova** [comment]
We need also to update the setup scripts and the documentation  in https://docs.nativescript.org/ to use and suggest Sdk 28 on setup.

**Comment by endarova** [comment]
#4052

**Comment by endarova** [comment]
Passing compile sdk lower than 28 fails build with tns-android@next #4052

**Comment by endarova** [comment]
Update Nativescript cli setup scripts to use android sdk 28  #4053

**Comment by RosilBelli** [comment]
My project is under the latest Nativescript version (5.3), but my app needs to run on android 5.1.
I'm trying to run tns run android --bundle --compileSdk 22 but I'm asked to install Android SDK 28. 

How can I generate a build for the version I need?
Couldn't find anything on the docs.
