### ISSUE TITLE
Your URL has expired. Please generate a new one

### ISSUE THREAD

**Issue by MurhafSousli** [NativeScript/nativescript-cli#3995]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: **5.0.0-2018-10-08-12421**
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

I just installed NativeScript CLI on my PC (Win 10), created new app with the blank angular template and then ran it for android platform.

**To Reproduce**

1. Run `tns run android`

![image](https://user-images.githubusercontent.com/8130692/46629413-64438d80-cb49-11e8-854d-a60eaf5c4d30.png)

2. Click on the generated link

The browsers shows an empty page with this text

 > "Your URL has expired. Please generate a new one."

**Expected behavior**

To open the playground editor

**Sample project**

**Additional context**

**Comment by Fatme** [comment]
Hi @MurhafSousli,

The message indicates that we are generating a QR code for the mentioned URL i.e. it is related to the QR code generation itself. The url is `play.nativescript.org`, as we are using a URL shortener hosted in the playground.

The idea of the message is to be show the URL and if for some reason the user is unable to scan the QR code, they can find another way to input the URL and open it in the preview app  (i.e. using another QR code generator, for example in the browser or directly writing the url in the browser on device).
Actually it is not possible to open the application in playground editor using this url.
