### ISSUE TITLE
LiveSync is not working in Preview app when Angular's lazy loading is used

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#4024]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: rc (5.0.0-2018-10-12-12482)
 - Cross-platform modules: Not applicable
 - Android Runtime: Not applicable
 - iOS Runtime: Not applicable
 - Plugin(s): nativescript-dev-webpack - next, nativescript-angular - next

**Describe the bug**
In case you have Angular application with Lazy loading and you try:
```
tns preview --bundle
```
or 
```
tns preview --hmr
```
You will not be able to use LiveSync - the changes are not applied.

**To Reproduce**
```
git clone https://github.com/NativeScript/nativescript-sdk-examples-ng.git
cd nativescript-sdk-examples-ng
// update all depenencies to next and update your webpack.config.js
tns preview --bundle
// Scan the QR code
// After app is synced, apply a change in any file, it should be synced, but it is not
```

**Expected behavior**
LiveSync to Preview app should work

**Comment by sis0k0** [comment]
Note: The navigation in the app is not working, not just the livesync.
