### ISSUE TITLE
Can't add plugins

### ISSUE THREAD

**Issue by Hasanhsk** [NativeScript/nativescript-cli#4027]
**Environment**
 - CLI:  4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime:
 - Plugin(s): kinveys-sdk or firebase-sdk

**Describe the bug**
Its a build time error. 
Whenever I add any plugin let it be kinvey or firebase the project starts building and ends up with the error.

Log:

D:\nativescript\test3>tns run android
Skipping node_modules folder! Use the syncAllFiles option to sync files from thi
s folder.
Searching for devices...
Executing before-checkForChanges hook from D:\nativescript\Internship\test3\hook
s\before-checkForChanges\firebase-copy-google-services.js
nativescript-plugin-firebase: building for same environment, not forcing prepare
.
Executing before-checkForChanges hook from D:\nativescript\Internship\test3\hook
s\before-checkForChanges\kinvey-nativescript-sdk.js
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from D:\nativescript\Internship\t
est3\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimize
d-with-inspector
         + adding aar plugin dependency: D:\nativescript\Internship\test3\node_m
odules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: D:\nativescript\Internship\test3\node_m
odules\tns-core-modules-widgets\platforms\android\widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCol
lection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCol
lection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot functi
on without it.
   Searched Location:
  D:\nativescript\Internship\test3\platforms\android\app\src\nullnull\debug\goog
le-services.json
  D:\nativescript\Internship\test3\platforms\android\app\src\debug\nullnull\goog
le-services.json
  D:\nativescript\Internship\test3\platforms\android\app\src\nullnull\google-ser
vices.json
  D:\nativescript\Internship\test3\platforms\android\app\src\debug\google-servic
es.json
  D:\nativescript\Internship\test3\platforms\android\app\src\nullnullDebug\googl
e-services.json
  D:\nativescript\Internship\test3\platforms\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Unable to apply changes on device: 31006dd927cab319. Error is: Command gradlew.b
at failed with exit code 1.

**Comment by edusperoni** [comment]
You haven't installed firebase correctly: https://github.com/EddyVerbruggen/nativescript-plugin-firebase#prerequisites

**Comment by rosen-vladimirov** [comment]
Closing this as the issue seems to be local configuration of the plugin.
