### ISSUE TITLE
Unable to run nativescript hello world project

### ISSUE THREAD

**Issue by gezn** [NativeScript/nativescript-cli#4028]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Component nativescript has 5.0.0-2018-09-26-12314 version and is up to date.
✔ Component tns-core-modules has 4.2.1 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✔ Component tns-ios has 4.2.0 version and is up to date.

**Describe the bug**
I've installed nativesctipt created a project using 
`tns create hellotns --ng `
tried to run it using
`tns run android`
but an error appears stating: 
`Unable to apply changes on device: 192.168.56.101:5555. Error is: cp: cannot create directory '/Users/pedroteran/Documents/tutator/nativescript/hellotns/platforms/android/app/src/main/assets/app/tns_modules/@angular': No such file or directory.`

**To Reproduce**
just create a  project with nativescript-cli
I've uploaded the generated project here: so it can be tested...
https://github.com/gezn/nativescript-cli-issue

**Expected behavior**
that the app compiles
**Sample project**
https://github.com/gezn/nativescript-cli-issue

**Additional context**
according to tns doctor everything is setup correctly:
No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Getting NativeScript components versions information...

my npm and node versions are: 
```
npm 5.0.3
node v8.1.3
operatying system: mac Os high sierra 10.13.2
```

**Comment by mpochron** [comment]
Resolved for me with the newest version released of date 2018-10-15

**Comment by Fatme** [comment]
Hi @gezn , @mpochron,

Can you please update to `rc` version of NativeScript?

```
npm un nativescript -g
npm i nativescript@rc -g
```

**Comment by mpochron** [comment]
@Fatme

I have created plugin and loaded from local directory.  

I found alternative ,  I need put plugin to NPM regsitry server to resolve this issue.

**Comment by gezn** [comment]
after trying to install  native script in this npm version I have the following error. that I believe is generated by nodeJs
`npm ERR! sha512-3pA0cXbkwu55+He71QO1oRE18wQyquk5t6vpM4laAFatI5w8n2dyHYSzM7pM6bN57zpcP2sk5u1q3YtYv0d2MQ== integrity checksum failed when using sha512: wanted sha512-3pA0cXbkwu55+He71QO1oRE18wQyquk5t6vpM4laAFatI5w8n2dyHYSzM7pM6bN57zpcP2sk5u1q3YtYv0d2MQ== but got sha512-NjXN4+ETuo852b7n2YdxCXttQGh53YR3cK0MCE0q+1HjAEHwLH33FfsFhQfiOphxbG8qyO6G0d2ix+bvhl9qDw==. (903632 bytes`

**Comment by gezn** [comment]
in fact with the latest node it works smoothly, and the error is gone, thanks @rosen-vladimirov. I would suggestto document that other versions of node may not work, or at least that some versions on npm doesn't generate correct results, and point to the versions that are officially supported and stable. or the stacks is tested. this will help a lot

**Comment by rosen-vladimirov** [comment]
Closing this as the issue cannot be reproduced with latest versions of Node.js and npm
