### ISSUE TITLE
IOS App not building since Xcode Update

### ISSUE THREAD

**Issue by divyachandana** [NativeScript/nativescript-cli#4035]
Xcode build...
error: unexpected duplicate task: CodeSign /Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework (in target 'client')
error: unexpected duplicate task: CodeSign /Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework (in target 'client')
error: Multiple commands produce '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework':
1) Target 'client' has copy command from '/Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework'
2) Target 'client' has copy command from '/Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework'
error: Multiple commands produce '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework/TNSCore':
1) Target 'client' has copy command from '/Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework'
2) Target 'client' has copy command from '/Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework'
warning: duplicate output file '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework' on task: PBXCp /Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework (in target 'client')
warning: duplicate output file '/Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework/TNSCore' on task: PBXCp /Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework (in target 'client')
warning: duplicate output file '' on task: PBXCp /Users/user/Desktop/sourcecode/srs/client/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/user/Desktop/sourcecode/srs/client/platforms/ios/build/emulator/client.app/Frameworks/TNSCore.framework (in target 'client')
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

Unable to apply changes on device: 70C7A1CB-1359-484C-9500-5352B4641CD8. Error is: Command xcodebuild failed with exit code 65.

**Comment by Fatme** [comment]
Hi @divyachandana, looking at this error I can see that there are multiple TNSCore.frameworks in your node_modules directory. 

You can find more info in [this thread](https://github.com/NativeScript/nativescript-cli/issues/3909).

I'm closing this issue as it is duplicated to https://github.com/NativeScript/nativescript-cli/issues/3909

**Comment by r58developer** [comment]
Just for those that are looking for an answer, I looked through that thread and many, many others that claimed to have a solution to this issue and did not. After hours I managed fix the problem myself. I hope this will save others the time!!

SOLUTION!!!
- Open Xcode 
- Select your project
- Find the 'General' tab (located within the same tab list as Build Phases, Build Settings etc)
- Scroll down to the 'Embedded Binaries' section.
- In the list you'll see that TNSCore.framework is in the list multiple times.
- Remove the duplicates using the '-' button until there is just one.
- Rebuild and hopefully if there are no other duplicates in that list you should have a successful build

**Comment by jonnuttingYCH** [comment]
Thank you r58developer. Your fix worked for me :)

**Comment by Stardock-AI** [comment]
Totally fixed the problem for me.  I simply deleted the libraries that were complaining of duplication and let tns rebuild them. Fixed!

**Comment by erkanarslan** [comment]
Not working for me. There are no multiple .framework files listed in the Xcode but I still get this error
