### ISSUE TITLE
Specifying iOS build only for iPad not working (app can be deployed on iPhone)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4038]
@NickIliev commented on [Fri Oct 05 2018](https://github.com/NativeScript/sidekick-feedback/issues/274)

In the [iOS properties](https://docs.nativescript.org/sidekick/user-guide/configure-app/ios-properties) we can specify the device family to build for. However, checking only **iPad** is actually creating a build for iPhone as well.

Possibly related to the way [UIDeviceFamily](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW11) is added in info.plist.

> Important: Do not insert this key manually into your Info.plist files. Xcode inserts it automatically based on the value in the Targeted Device Family build setting. You should use that build setting to change the value of the key

Reported via the feedback form.

**Comment by rosen-vladimirov** [comment]
To achieve the desired functionality with local iOS build, you can add:
TARGETED_DEVICE_FAMILY = 2
in `<project dir>/app/App_Resources/iOS/build.xcconfig`
Value 1 is for iPhone and iPod, 2 is for iPad, default is `1,2`.
For cloud builds please follow the related issue: https://github.com/NativeScript/sidekick-feedback/issues/274
