### ISSUE TITLE
tns preview fails when local plugin is referenced with tag in package.json

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-cli#4043]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0-2018-10-11-12463
 - Cross-platform modules: rc

**Describe the bug**
If the version of some plugin in the package.json is specified with tag (f.e. `rc`) instead of version (f.e. `5.0.0`), the `tns preview` command fails with:
```
TypeError: Cannot read property 'major' of null
    at PreviewAppPluginsService.getWarningForPluginCore (/home/sis0k0/nativescript-cli/lib/services/livesync/playground/preview-app-plugins-service.ts:82:30)
```

The `PreviewAppPluginsService` uses `semver` to check some stuff with the versions of the plugins in the package.json. However, `semver.coerce('rc')` returns `null` and breaks the following logic.
https://github.com/NativeScript/nativescript-cli/blob/b9bfc685c8ab3b1f03d78e820661aa0f472075b3/lib/services/livesync/playground/preview-app-plugins-service.ts#L74-L91

**To Reproduce**
1. Create a hello-world app.
2. Add this dependency to your package.json:
````
...
"dependencies": {
	"tns-core-modules": "rc",
	...
}
````
3. Run `tns preview` and scan the barcode.

**Expected behavior**
To ignore the above check if the tag is `beta`, `rc` or `next`.
I can submit a PR if you agree that's the correct behaviour.

**Comment by Fatme** [comment]
We discussed the problem personally and decided to skip the check if the version is not valid semver version. The same approach is used here: https://github.com/NativeScript/nativescript-cli/blob/master/lib/helpers/bundle-validator-helper.ts#L27
