### ISSUE TITLE
Make the warnings about the Beta features more visible 

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#4058]
**Is your feature request related to a problem? Please describe.**
The Beta features will be described only in the release notes.

**Describe the solution you'd like**
We should show warnings in the CLI output and the commands help.

**Additional context**
The Beta features for the 5.0 release are the Hot Module Replacement (HMR) option and the Webpack support for the `preview` commands. We should also make the HMR Angular limitations more visible.

**Comment by endarova** [comment]
- [ ] Verify warning is shown when command (debug, run) is run  with --hmr option
- [ ] Verify warning is shown when  preview command  is run with --hmr option
- [ ] Verify warning is shown when  preview command  is run with --bundle option
- [ ] Verify warning for angular limitations is shown when  preview command  is run with --hmr option in angular project
- [ ] Verify warnings in help for --hmr and preview --bundle option
