### ISSUE TITLE
Add option for setting the current platform

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/nativescript-cli#406]
Currently, most of the commands require the platform-specific parameter, e.g.

```
tns prepare android
tns build android
```
What I suggest is to enable some way of setting the current platform and then to call all the commands without this additional parameter. Something like:

```
tns platform setCurrent android
tns prepare //(uses Android)
tns build //(uses Android)
```

**Comment by ligaz** [comment]
What about just adding the capability to execute the commands without platform and it will execute the command for all added platforms.
```
$ tns platform add android
$ tns run
```
will run (prepare, build, deploy) for Android.
```
$ tns platform add android
$ tns platform add ios
$ tns run
```
will run for both platforms.

**Comment by teobugslayer** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/475

**Comment by ligaz** [comment]
Superseded by https://github.com/NativeScript/nativescript-cli/issues/475
