### ISSUE TITLE
Refresh on Android does not work

### ISSUE THREAD

**Issue by florianislitzer** [NativeScript/nativescript-cli#4062]
**Environment**
 - CLI:  4.2.3

**Describe the bug**
When running tns run android --bundle for the first time the application starts on my device. After doing changes the cli rebuilds the project but nothing happens on the device. 
I get following message: 

> Successfully transferred bundle.js.
> Refreshing application...
> Error while trying to start application com.b2c.posapp on device 20080411. Error is: Cannot read pro
> perty 'removeAllListeners' of null
> Unable to start application com.b2c.posapp on device 20080411. Try starting it manually.
> Successfully synced application com.b2c.posapp on device 20080411.

What is the reason for that?

**Comment by florianislitzer** [comment]
@Fatme 
Thanks! refreshing is working now but I get the following error when executing any tns command:

Error while loading nativescript-angular-cli is: Default commands should be required before child commands

**Comment by dtopuzov** [comment]
Hi @florianislitzer,

Since refresh work I think we can close the original issue.

I believe next issue you hit is different so if you still encounter it, please log separate issue.
