### ISSUE TITLE
NativeScript v4 is not using the v4 of the app templates during project creation

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#4096]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4

**To Reproduce**
1) `npm i -g nativescript@4`
2) `tns create newApp`
3) Check the `package.json` of the newly created app. The core modules and runtimes should be compatible with the CLI (v4) but both of them are installed with their latest versions (v5).

**Comment by endarova** [comment]
If you pass template version for template v2 it is not respected. Example: tns create testApp --template tns-template-hello-world@4.2   should create project with core modules and runtimes 4.2.x. The created template is with core modules and runtimes 5.0.0.
