### ISSUE TITLE
Cleanup `tns run ios --emulator` output

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#410]
_From @vjeux on April 5, 2015 15:39_

Since the entire project is written in JS, there isn't a big need for displaying all the xctools build logs. It is super spammy and doesn't add any value for the end user. Would be nice removing it.

Example: https://gist.github.com/vjeux/3a87e04b90f62f43501b (846 lines)

_Copied from original issue: NativeScript/NativeScript#31_

**Comment by PanayotCankov** [comment]
:+1:

For me the Xcode output is important if the build fails, and is not important if the build succeeds. I was wondering if we can somehow log that the xcodebuild started, cache the output and selectively trace or error it out.

In case of success only a "Project build started..." / "Project successfully built" will be displayed, (unless run in verbose mode).

In case of failure, we will dump the whole xcodebuild as error at the user and exit violently?

**Comment by enchev** [comment]
We've decided to keep the Xcode output since it is important.
