### ISSUE TITLE
Avoiding qemu-system-x86_64.exe console window

### ISSUE THREAD

**Issue by doffltmiw** [NativeScript/nativescript-cli#4102]
On windows, `tns run android` creates another console window with the title `C:\Users\username\AppData\Local\Android\sdk\emulator/qemu/windows-x86_64/qemu-system-x86_64.exe`, which is a little detracting.

Is this inevitable?

**Comment by KristianDD** [comment]
Hi @doffltmiw ,
There seem to be multiple issues logged inside Node.js repository about this(for example [this](https://github.com/nodejs/node/issues/21825). 

I investigated the issue and I found that the `emulator.exe`, which we spawn, always creates the console window. The spawn configuration I used was :
```JavaScript
child_process.spawn("<path-to-sdk>\emulator.exe -avd SomeImage", { stdio: 'ignore', detached: true, windowsHide: true, shell: false })`.
```
It works only if I don't spawn `emulator.exe` as a detached process, but that means that terminating the CLI command will close the emulator, which is inconvenient for most users. 

This behavior seems to be specific to this executable and out of our control, so I am closing the issue.
