### ISSUE TITLE
project doesn't work after fix error in xml file

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#4123]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Android Runtime: 5.0
 - iOS Runtime: 5.0

**Describe the bug**
after fix an error in xml files, the project doesn't work

**To Reproduce**
1. tns run ios --hmr
2. make error in main-page.xml 
3. stop process
4. fix error in maim.page.xml
5. tns run ios --hmr and you will see that the exception doesn't fix

**Expected behavior**
working project

**Comment by KristianDD** [comment]
Should be tested with nativescript-dev-webpack@rc.
