### ISSUE TITLE
Project id does not match directory name if it contains a dash

### ISSUE THREAD

**Issue by brianchirls** [NativeScript/nativescript-cli#413]
See https://github.com/NativeScript/ios-runtime/issues/77

To reproduce, run `tns create hello-world`.

The project is created in a folder called `hello-world`, but the project id inside .tnsproject is `org.nativescript.helloworld`. Project ids inside other files (e.g. AndroidManifest.xml, build.xml) are inconsistent - some have the dash, and some don't.

**Comment by teobugslayer** [comment]
Hello @brianchirls ,
we generate ids so that they are valid in all supported platforms (including windows, which we plan to support). Can you pinpoint where we generate incorrect ids?

**Comment by brianchirls** [comment]
Hi @teobugslayer. I don't know where in the code the name gets replaced, but I'm pretty sure it happens at project creation, not any time later. It appears it's validated [here](https://github.com/telerik/mobile-cli-lib/blob/1d3c5068f336b0555bc47814bd31c27f426a8d7d/validators/project-name-validator.ts#L7).

If some platforms can't handle a dash in the name, then names containing one should be rejected by the validator.

**Comment by Fatme** [comment]
Hello @brianchirls,

Sorry for the late response. 

You're right that the project id is inconsistent. As @teobugslayer said we generate cross platform identifier and sanitize the given or default (the default id is `org.nativescript.<app name>`) app identifier. But we doesn't sanitize the `app name`. And actually here we get the inconsistent. 
 In your case we're creating a folder named `hello-world`, `AndroidManifest.xml` is replaced with the sanitized application identifier e.g `org.nativescript.helloworld`. After that `android update project -p <project directory>` is called and creates build.xml with `org.nativescript.hello-world`. 

I'm going to fix the problem and will update you here in this thread.
