### ISSUE TITLE
[iOS] [!] Invalid `Podfile` file: The target `Pods-projectName` already has a platform set..

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#4134]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  whatever version
 - Cross-platform modules: depends
 - Android Runtime: not used
 - iOS Runtime: 5.0.0 (but happens with all)
 - Plugin(s): examples are ```nativescript-mapbox``` and ```nativescript-plugin-firebase```

**Describe the bug**
Some plugins define ```platform :ios, '9.0'``` or whatever other version in their PodFile.
As soon as you 2 plugins doing so your app wont build.  You will get the error ```Invalid `Podfile` file: The target `Pods-projectName` already has a platform set..```

I think this comes from ```nativescript-cli``` merging Podfiles. Consequently there will be multiple calls to ```platform :ios``` and pod will report an error.
This should be handled by the cli.

**Comment by Fatme** [comment]
@farfromrefug,

I'm closing this issue as duplicate to https://github.com/NativeScript/nativescript-cli/issues/3604. You can track the progress there.

**Comment by farfromrefug** [comment]
@Fatme  sorry my bad!
