### ISSUE TITLE
Cannot download app to simulator (iOS)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-cli#4140]
When I do `tns run ios` - it doesn't download the app to the simulator.

I've verified `tns devices` - it's running.

If I do `tns build ios` and `tns deploy ios` - that downloads the app.

Even after downloading the app - `tns run ios` does NOT launch the app.

I get

`Starting compilation in watch mode...

Found 0 errors. Watching for file changes.`

I'm using NS 5.0

**Comment by erjdriver** [comment]
I deleted the hooks folder and it started working again.

The `run` command the hooks folder - but nothing is in it.

But the downloaded the app - so solved for now.

**Comment by erjdriver** [comment]
The problem seems to be that when I edit a file - the watcher seems to detect it and re-downloads the app.

But the app on the device is not updated.

This is with the "hooks" folder blank.

A `tns platform clean ios` and `tns run ios` does not rebuild the hooks folder.

I'm using typescript and the message I see in the compiler is

`Successfully transferred main.ts on device ...`

Shouldn't it be the .js file.

Anyway looks like the hooks folder needs to be rebuilt.

**Comment by Fatme** [comment]
@erjdriver,

> Successfully transferred main.ts on device

Yes, it should be `Successfully transferred main.js on device`. Typescript compiler is started from `hooks` directory. But in your case it is an empty directory so no typescript compilation is executed. This is the reason to see the above message.

In order to receive correct `hooks` directory, you need to execute the steps below:
```
rm -rf node_modules
rm -rf hooks
npm i
```

**Comment by erjdriver** [comment]
I tried it - and the same.

`tns devices` shows the simulator.

`tns build ios` and `tns deploy ios` works. Latter downloads the app to the simulator.

But `tns run ios` doesn't build, deploy or even launch the already deployed app.

**Comment by Fatme** [comment]
@erjdriver,

Can you please execute `tns run ios --log trace` and send us the output?

**Comment by erjdriver** [comment]
Fixed.
