### ISSUE TITLE
Typing ng g component stops LiveSync

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4171]
@dolanmiu commented on [Thu Nov 22 2018](https://github.com/NativeScript/nativescript-angular/issues/1627)

Ttyping in `ng g component my-component` in the command line stops LiveSync, and I need to restart the app with `tns run ios` every time

**Comment by Fatme** [comment]
@dolanmiu,

Can you please give us the exact steps in order to reproduce the issue on our side?

**Comment by dolanmiu** [comment]
Run the emulator:

```
$ tns run ios
```

Wait until everything is loaded.

Inside the project directory:
```
$ ng g component my-component
```
