### ISSUE TITLE
[Installation] undefined local variable or method `avdmanager'

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4173]
@n1kk commented on [Sun Nov 25 2018](https://github.com/NativeScript/NativeScript/issues/6610)

Trying to install to macos 10.14 via `ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"` getting error in the end:
```
Do you want to create Android emulator? (y/n)
y
-e:174:in `<main>': undefined local variable or method `avdmanager' for main:Object (NameError)
Did you mean?  avd_manager
```
brew version
```
Homebrew 1.8.3
Homebrew/homebrew-core (git revision 39e5; last commit 2018-11-24)
Homebrew/homebrew-cask (git revision ff3b54; last commit 2018-11-24)
```

**Comment by jer0m** [comment]
I got the same error on MacOS High Sierra. I looked at the installation script (https://www.nativescript.org/setup/mac). It seems that a variable is not defined well at the end of the script:
```puts "Do you want to create Android emulator? (y/n)"
if $silentMode || gets.chomp.downcase == "y"
  error_msg = "Failed to create Android emulator."
  avd_manager = File.join(ENV["ANDROID_HOME"], "tools", "bin", "avdmanager")
  execute("echo y | #{avdmanager} create avd -n Emulator-Api28-Google -k  \"system-images;android-28;google_apis;x86\" -b google_apis/x86 -c 265M -f", error_msg)
end```
`File.join(ENV["ANDROID_HOME"], "tools", "bin", "avdmanager")` is set in `avd_manager` variable instead of `avdmanager`. I would have done a PR but I can't find the file

**Comment by NickIliev** [comment]
@jer0m PRs are welcomed! :) Th3e repository containing the setup scripts is located [here](https://github.com/NativeScript/setup-scripts)

**Comment by jer0m** [comment]
@NickIliev It seems there is one opened already for this bug: https://github.com/NativeScript/setup-scripts/pull/19
