### ISSUE TITLE
package.json indentation always switched to spaces

### ISSUE THREAD

**Issue by Fedelaus** [NativeScript/nativescript-cli#4190]
**Environment**
 - CLI: 5.1.0
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s): 

dependencies:
```
    "nativescript-angular": "~6.1.0",
    "nativescript-audio": "^5.0.1",
    "nativescript-geolocation": "^4.3.1",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-orientation": "^2.2.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.4.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^3.7.0",
```
dev: 
```
    "nativescript-dev-sass": "",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "0.15.0",
```

**Describe the bug**
When running an `npm install` with no `hooks` directory, the package.json file will be rewritten with spaces instead of tabs.

**To Reproduce**
1. Ensure `package.json` has tab indentation.
2. delete `hooks` + `node_modules`
3. run `npm install`
4. Check `package.json`.

**Expected behavior**
The indentation style currently used to be honored, as per npm5+ does currently and as suggested by this merge request: https://github.com/NativeScript/nativescript-cli/pull/1779

**Comment by rosen-vladimirov** [comment]
Hey @Fedelaus ,
Thanks for reporting this issue. We've reproduced it and it is caused by the postinstall script of nativescript-dev-webpack plugin. We have created a fix for it and we'll include it in one of the next releases.
