### ISSUE TITLE
Setting app version number from 1 central place

### ISSUE THREAD

**Issue by fransyozef** [NativeScript/nativescript-cli#4191]
**Is your feature request related to a problem? Please describe.**
With IONIC you have a config.xml file in the root map of the folder where you can set some configuration for both iOS and Android.
One of those settings is setting the build version. In NS I need to manually alter the build versions for both platforms in 2 difference files.

**Describe the solution you'd like**
In the package.json you can set the build versions (either for both or separate). 

**Describe alternatives you've considered**
I've considered writing my own webpack plugin to search and replace a string (for example __NS_APP_BUILD_VERSION__) to set the version.

**Comment by Fatme** [comment]
I'm closing this as a duplicate to https://github.com/NativeScript/nativescript-cli/issues/1118.
