### ISSUE TITLE
Nativescript not updating to latest version

### ISSUE THREAD

**Issue by vincentderidder** [NativeScript/nativescript-cli#4195]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4
 - Cross-platform modules: 
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - tns-core-modules: 5.0.5
 - Plugin(s):

on macOS version 10.14.1 (18B75)

**Describe the bug**
When running `sudo npm i -g nativescript@latest --unsafe-perm` to get the latest version of the CLI, the installation succeeds but tns info claims i'm still on 4.2.4. When looking into npm list -g, nativescript is on 5.0.2. This results in not being able to run the latest version of Sidekick. I tried removing nativescript and reinstalling it, but no result.

**To Reproduce**
run sudo npm i -g nativescript@latest --unsafe-perm when on version 4.2.4

**Expected behavior**
tns info shows latest version after updating. Sidekick starts without version errors

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@vincentderidder I think your issue is with the local access rights and permissions and not with the CLI. Try removing the `sudo` for npm install  (e.g. a blog post [here ](https://www.competa.com/blog/how-to-run-npm-without-sudo/)

**Comment by vincentderidder** [comment]
Thank you! Not only was I able to resolve my problem, but I learned something new about using npm. The blog post really helped!
