### ISSUE TITLE
Not able to change IPHONEOS_DEPLOYMENT_TARGET due to CLI overwriting ARCHS and VALID_ARCHS

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4197]
When trying to change the iOS deployment target version to 11.0 the build is failing due to the CLI overwriting the VALID_ARCHS and ARCHS [here (simulator logic)](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts#L563-L564) and [here (device logic)](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts#L388-L389)

```JS
"ARCHS=i386 x86_64",
"VALID_ARCHS=i386 x86_64",
```

Steps to reproduce the issue:

- `tns create testApp --ng`
- `cd testApp`

- Place the following `App_Resources/iOS/build.xcconfig`
```
 IPHONEOS_DEPLOYMENT_TARGET = 11.0; 
```

- Run 
```
tns build ios
```

As a result, the build will fail with 
```
Building project...
Xcode build...
warning: The i386 architecture is deprecated for your deployment target (iOS 11.0). You should update your ARCHS build setting to remove the i386 architecture. (in target 'targetios11')
clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

Command xcodebuild failed with exit code 65
```

**Comment by etabakov** [comment]
@DickSmith ☝️
