### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by rhg1968** [NativeScript/nativescript-cli#421]
This is a question about using typescript with Nativescript. I created the hello world example and it worked correctly, but I wanted to see how it would work with typescript. I decided to change the main-page.js to main-page.ts. This broke the application and the taps that were being counted on the screen now show with just the binding expression {{message}}. I even tried changing the the new ts file to use import and export typescript functions without any luck.

Does the CLI automatically compile the ts files into javascript ?

**Comment by george-jones** [comment]
I had the exact same experience.  Did you find a resolution to this?

**Comment by rhg1968** [comment]
I didn't find a solution unfortunately. I closed this because I posted it instead on the Native script forums.
https://groups.google.com/forum/#!topic/nativescript/r2jwG4fIXt4

**Comment by teobugslayer** [comment]
Hello @rhg1968,

You are right that at the moment we do not auto-compile ts files. I am preparing a fix for it. 

We have already started preparing for releasing version 0.10 of the CLI and my fix probably won't be in it. You'll need to wait a little longer or work against master ;)

**Comment by ctartamella** [comment]
His this available in 1.0.1?  I am not seeing any of my .ts files being compiled.

**Comment by teobugslayer** [comment]
Hello @ctartamella,

No, this is not available in {N} 1.0.1

We decided that the proposed implementation is not good enough and I closed my PRs. We will implement it in a better way, with ability to customize TypeScript compilation per-project in one of the future releases of {N} CLI.

In the mean time, you can use one of the node.js automation tools, like [grunt](http://gruntjs.com/) or [gulp](http://gulpjs.com/) to automate ts compilation.

**Comment by ligaz** [comment]
We have written down our current thinking in this issue: https://github.com/NativeScript/nativescript-cli/issues/493. I'm going to close this down and let's continue the discussion there.
