### ISSUE TITLE
 cannot install nativescript cli on ubuntu

### ISSUE THREAD

**Issue by calebdeji** [NativeScript/nativescript-cli#4217]
I am facing problems to install nativescript cli
**Linux- Ubuntu**
I typed in the following code in my terminal

> sudo npm install nativescript -g --unsafe-perm

and i got this 

npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/request/-/request-2.85.0.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/es6-promisify/-/es6-promisify-5.0.0.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/async/-/async-1.2.1.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/async/-/async-1.5.2.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/source-map/-/source-map-0.2.0.tgz
npm ERR! tar.unpack unzip error /tmp/npm-5761-fdb7c981/registry.npmjs.org/colors/-/colors-1.0.3.tgz
npm ERR! tar.unpack untar error /tmp/npm-5761-fdb7c981/registry.npmjs.org/colors/-/colors-1.0.3.tgz
npm ERR! fetch failed http://registry.npmjs.org/lodash/-/lodash-4.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
npm ERR! fetch failed http://registry.npmjs.org/commander/-/commander-2.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
 
**and then it hangs here**
loadRequestDeps -> netw  | ######-----------------------------------|
![nativescript](https://user-images.githubusercontent.com/33372799/49801294-1534f700-fd4a-11e8-9b8f-aeaeba6f1583.png)

**Comment by dtopuzov** [comment]
Hi @calebdeji,

Can you install successfully any other npm package, for example:
npm i -g appium

Can you confirm your system is ok for other npm package and only nativescript fails to install?

**Comment by dtopuzov** [comment]
ECONNRESET usually happens when there is a networking configuration issue.
For example wrong proxy settings or issue in registry configuration.

Reference:
https://stackoverflow.com/questions/1841
9144/npm-not-working-read-econnreset

I am closing the issue since it looks like general system configuration issue.

Please reopen if you can confirm that you can install other npm packages and the issue happens only with nativescript.
