### ISSUE TITLE
Android debugging is leaking the debug session

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#4219]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0

**To Reproduce**
1) `tns create testApp --js && cd testApp`
2) `tns debug android`
3) Open the Chrome URL and set a breakpoint.
4) Run `ctrl + c` in order to terminate the debug command.
5) Try to hit your breakpoint.
6) The breakpoint will be successfully hit.

**Expected behavior**
The debug session should be terminated along with the CLI debug command.

**Comment by rosen-vladimirov** [comment]
Once the session is established and CLI command exits, CLI will remove the port forwarding. But the connection between Chrome DevTools and device is already setup, so it will continue to live. If you refresh DevTools or restart app on device, the connection will not be established anymore.
So I'm closing this issue as CLI no longer leaks forwarded ports.
