### ISSUE TITLE
Debugging with HMR

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#4230]
@DimitarTachev commented on [Mon Dec 03 2018](https://github.com/NativeScript/ios-runtime/issues/1026)

**Environment**
 - CLI: next (v)
 - Cross-platform modules: 5.0.0
 - iOS Runtime: 5.0.0

**Describe the bug**
When a file is updated with HMR, the dev tools are not updated and the breakpoints are not working anymore.

**To Reproduce**
1) tns create newApp --js
2) cd newApp
3) tns debug ios --hmr
4) open chrome dev tools and set a breakpoint
5) change a js file
6) the change will not be applied in the dev tools and the breakpoint will not be hit anymore

**Expected behavior**
The dev tools code should be updated and the breakpoint should be refreshed and hit after livesync. (try the `tns debug android --hmr` behavior)

**Comment by sis0k0** [comment]
related to https://github.com/NativeScript/NativeScript/issues/6398
