### ISSUE TITLE
Fresh project build error on ios

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4238]
@hamdiwanis commented on [Sun Dec 16 2018](https://github.com/NativeScript/NativeScript/issues/6715)

**Environment**
 - CLI: 5.1.0
 - Cross-platform modules:  5.1.0
 - Android Runtime:  5.1.0
 - iOS Runtime:  5.1.0
 - Plugin(s): none

**Describe the bug**

i get this error with ios build

```
linking ObjC for iOS Simulator, but dylib (/Volumes/project/platforms/ios/internal/NativeScript.framework/NativeScript) was compiled for MacOSX

ld: framework not found CoreServices for architecture i386
```

**To Reproduce**
```
tns create test
cd test
npm i
tns run ios
```

---

@NickIliev commented on [Mon Dec 17 2018](https://github.com/NativeScript/NativeScript/issues/6715#issuecomment-447735889)

@hamdiwanis what is the simulator/device you are running on?

**Comment by hamdiwanis** [comment]
Thanks @Nicklliev for thr response. I use the ios simulator that comes with xcode version 9 specifically i phone 6 with ios 12. It used yo work until i upgraded from 4.2 to 5.1

**Comment by NickIliev** [comment]
@hamdiwanis can you try adding these two lines in your build.xcconfig

```
ARCHS=i386 x86_64
VALID_ARCHS=i386 x86_64
```

The thing is that XCode 9 supports 32-bit architecture while with XCode 10 only 64-bit architecture is now officially supported (meaning that all simulators created with XCode 10 are not 64-bit)
```
The macOS 10.14 SDK no longer contains support for compiling 32-bit applications. If developers need to compile for i386, Xcode 9.4 or earlier is required. (39858111)
```

However, we removed the explicit i386 builds [here](https://github.com/NativeScript/nativescript-cli/pull/4206/files) so we could support setting [deployment target](https://github.com/NativeScript/nativescript-cli/issues/4197)

If the solution with `build.xcconfig` is not working please do let me know and also try the following solution but in reverse (adding ARCHS and VALID_ARCHS instead of removing them)

**Comment by hamdiwanis** [comment]
thanks but with both solutions still get the same error
`ld: framework not found CoreServices for architecture i386`

**Comment by NickIliev** [comment]
@hamdiwanis ok on second thought it seems that the issue you are hitting seems related to [this one](https://github.com/NativeScript/nativescript-cli/issues/4163#issuecomment-441147416). We are not able to reproduce the issue but it might be related to a messed up XCode environment- if possible please try reinstalling the XCode
