### ISSUE TITLE
Copy App_Resources directly to platforms/.../res (Android) or platforms/.../Resources (iOS)

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-cli#4239]
**Current behaviour**
Currently, the `App_Resources` directory is copied from the root of the project (usually `my-project/App_Resources` or `my-project/app/App_Resources`) to the native assets (`my-project/platforms/.../assets/app`).
After that, the resources from the native assets are copied to their regular locations in the native project (e.g. `my-project/platforms/../main/res`).

**Describe the solution you'd like**
The first step can be skipped and the resources can be copied from the root of the project (e.g. `my-project/App_Resources`) to the native project (`my-project/platforms/.../main/res`) directly.

**Additional context**
When building with the `--bundle` flag, the initial copying is performed by the `CopyWebpackPlugin`.

**Comment by rosen-vladimirov** [comment]
Already implemented in CLI's rc version.
