### ISSUE TITLE
iOS build breaks with multiple plugins with podfiles 

### ISSUE THREAD

**Issue by GeorgeKyriakou** [NativeScript/nativescript-cli#4245]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 5.1.0
 - Plugin(s): nativescript-plugin-firebase (with ML_kit), nativescript-zxing

**Describe the bug**
Build breaks with the following error
`[!] Invalid 'Podfile' file: The target 'Pods-projectapp' already has a platform set..`

**To Reproduce**
Run a fresh application with those two plugins, with ml-kit enabled for the firebase plugin, and run `tns run ios --bundle`

**Expected behavior**
Build successfuly

**Additional context**
This is opened only to raise attention to #3604
It is a huge issue for our current development phase

**Comment by endarova** [comment]
Hi @GeorgeKyriakou, 
Thanks for reporting this. Since it is related to #3604  I am closing it as duplicate, so we can keep the conversation in the original issue.
