### ISSUE TITLE
LiveSync stop working in Preview app when make change in scss file 

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#4253]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0 
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s):nativescript-dev-webpack - rc(0.18.5-rc-2019-01-03-145308-01), 
                    nativescript-angular - next

**Describe the bug**
If you use Angular app with Lazy loading and make a change in scss file, you will see that the livesync stop to work.

**To Reproduce**
1. `tns create app --template tns-template-tab-navigation-ng`
2. `cd app`
3. `npm i nativescript-dev-webpack@rc --save-dev`
4. run `update-ns-webpack --configs` from /node_modules/.bin
5. `npm i nativescript-angular@next --save`
6. run `update-app-ng-deps` from /node_modules/.bin
7. `tns preview --hmr`
8. make a change in `ts` file - livesync works
9. make a change in `html` file - livesync works
10. make a change in scss and you will see in console: `HMR: Cannot apply update. A previous update aborted. Application needs to be restarted in order to apply the changes.`
11. after step 10, livesync stop to work for all files.

**Expected behavior**
after step 10 livesync must to continue to work

**Comment by KristianDD** [comment]
This should work with:
"tns-core-modules@next"
"nativescript-angular@next"
"nativescript-dev-webpack@next"
