### ISSUE TITLE
nativescript helloworld

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4269]
_From @Gurucharan on January 7, 2019 11:52_

Hello,

I was new to nativescript and trying to run android app in my local emulator followed steps from the nativescipt website. got following error. please tell me a solution to solve this error.

C:\Windows\System32\HelloWorld>tns run android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watchPatterns hook from C:\Windows\System32\HelloWorld\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from C:\Windows\System32\HelloWorld\hooks\before-watch\nativescript-dev-webpack.js
Executing before-shouldPrepare hook from C:\Windows\System32\HelloWorld\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\Windows\System32\HelloWorld\app\App_Resources\Android\app.gradle
Using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\Windows\System32\HelloWorld\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  C:\Windows\System32\HelloWorld\platforms\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  Command: C:\Users\BESPL-COMP1\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\833daae6ab7426f29bf50f02404424e1\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\Windows\System32\HelloWorld\platforms\android\app\build\intermediates\res\merged\debug \
          C:\Windows\System32\HelloWorld\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
Executing after-watch hook from C:\Windows\System32\HelloWorld\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from C:\Windows\System32\HelloWorld\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch

_Copied from original issue: NativeScript/NativeScript#6764_

**Comment by NickIliev** [comment]
@@Gurucharan are you using the latest version of NativeScript CLI? Please post the needed information as requested in the "report a bug/issue" template.

```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```

**Comment by Gurucharan** [comment]
@NickIliev 

yes,

√ Getting NativeScript components versions information...
√ Component nativescript has 5.1.0 version and is up to date.
√ Component tns-core-modules has 5.1.1 version and is up to date.
√ Component tns-android has 5.1.0 version and is up to date.
√ Component tns-ios has 5.1.0 version and is up to date.

**Comment by darind** [comment]
This seems to be an issue with android gradle plugin. Moving the project outside the `Windows\System32` folder should resolve the problem.

**Comment by Gurucharan** [comment]
@darind Thank you! it works now.

**Comment by DimitarTachev** [comment]
I'm closing this one as it's a known limitation of NativeScript.
