### ISSUE TITLE
HMR - Debug - HMR Sync logs are shown in dev tools console

### ISSUE THREAD

**Issue by vhristov5555** [NativeScript/nativescript-cli#4278]
1. Create project
2. Debug project with hmr `tns debug ios --hmr`
3. Change some code and save
Actual: HMR sync logs will be shown in dev tools console
Expected: HMR Sync logs to be shown only in terminal

**Comment by rosen-vladimirov** [comment]
This is by design - currently all logs are visible in both the Chrome Debug Console and in CLI. I'm closing this issue as there are no plans to implement it.
