### ISSUE TITLE
`tns run` fails if user specify both project path and iOS Simulator id.

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#4284]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: next (after https://github.com/NativeScript/nativescript-cli/pull/4254)
 - Cross-platform modules: latest
 - Android Runtime: latest
 - iOS Runtime: latest
 - Plugin(s): No

**Describe the bug**
`tns run` fails if user specify both project path and iOS Simulator id.

**To Reproduce**
```
manually boot at least one iOS Simulator
xcrun simctl list devices | grep Boot
-> get id of some booted device
tns create TestApp
tns run ios --path TestApp --device 8EB023D3-BAF1-4E89-A5D6-E93A1203757C
```

**Expected behavior**
`tns run` to work properly.

**Sample project**
No

**Additional context**
Issue is caused by https://github.com/NativeScript/nativescript-cli/pull/4254
Workarounds:
- `tns run ios --device <ID>` inside project (do not specify --path)
- `tns run ios --path TestApp --emulator` (do not specify iOS Simulator id).

**Comment by rosen-vladimirov** [comment]
Also CLI is unable to livesync changes on iOS Simulator in case app has `grep` in the name, for example `appgreptest`.
