### ISSUE TITLE
[MacOS 10.14] WARNING: CocoaPods is not installed or is not configured properly.

### ISSUE THREAD

**Issue by ebellumat** [NativeScript/nativescript-cli#4302]
- CLI: 5.1.1
 - Cross-platform modules: 5.1.2 
 - Android Runtime: 5.0.0 
 - iOS Runtime: 5.0.0 
- Pod version: 1.6.0.beta.2

**Describe the bug**
When i Run `tns run ios --bundle` Nativescript cli says "WARNING: CocoaPods is not installed or is not configured properly.", but the Cocoapods is installed.

![image](https://user-images.githubusercontent.com/26942680/51434188-f75c8b00-1c41-11e9-85c6-8a9c7e9e6403.png)

**To Reproduce**
`tns run ios --bundle `

**Expected behavior**
Run on ios device.

**Comment by Fatme** [comment]
@ebellumat,

What is the output of `pod --version` command? Also can you execute `tns run ios --bundle --log trace` and send us the output?

**Comment by ebellumat** [comment]
Hello! I fixed the error by myself, I Fixed NPM permissions to run without sudo, runs fine now. Thanks!

**Comment by bhavincb** [comment]
@ebellumat  how did you fixed npm permissions? i'm having similar issue can you please share all the steps.

**Comment by ebellumat** [comment]
It's is very complicated. I already forgot how i fixed that. But, last week i migrated to a new laptop, and i use a new method to prevent this permission errors. I'm now using the NVM (Node Version Manager), now i can have multiple versions of Node JS on Mac and i never more need to fight with the permissions. Uninstall your Node JS and Install using this.

https://nodesource.com/blog/installing-node-js-tutorial-using-nvm-on-mac-os-x-and-ubuntu/

**Comment by dasarijit88** [comment]
Hi Guys, I face the same issue. can anyone help here.I am attaching the log trace below


Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 11.0 (20A2411)
      Kernel Version: Darwin 20.1.0
      Time since boot: 21:20

 
 stderr: 
macOS version based on system_profiler is 11.0.
Looking for project in '/Users/arijitdas/Autility/Repository/test'
Project directory is '/Users/arijitdas/Autility/Repository/test'.
Initializing project identifiers. Config:  {
  id: 'org.nativescript.test',
  appResourcesPath: 'App_Resources',
  android: { v8Flags: '--expose_gc', markingMode: 'none' }
}
Loading extensions.
System information:
{
  "platform": "darwin",
  "shell": "/bin/zsh",
  "os": "Darwin Arijits-Mac-mini.local 20.1.0 Darwin Kernel Version 20.1.0: Sun Oct 18 15:32:00 PDT 2020; root:xnu-7195.41.8~9/RELEASE_ARM64_T8101 x86_64\n",
  "procArch": "x64",
  "nodeVer": "14.15.1",
  "npmVer": "6.14.8",
  "nodeGypVer": null,
  "nativeScriptCliVersion": "7.0.11",
  "gitVer": "2.24.3 (Apple Git-128)",
  "dotNetVer": null,
  "javacVersion": "15.0.1",
  "javaVersion": "15.0.1",
  "javaPath": "java",
  "adbVer": null,
  "androidInstalled": false,
  "monoVer": null,
  "gradleVer": null,
  "isAndroidSdkConfiguredCorrectly": false,
  "xcodeVer": "12.2.0",
  "xcodeprojLocation": "/usr/local/bin/xcodeproj",
  "itunesInstalled": false,
  "cocoaPodsVer": "1.10.0",
  "isCocoaPodsWorkingCorrectly": null,
  "isCocoaPodsUpdateRequired": false,
  "pythonInfo": {
    "isInstalled": true,
    "isSixPackageInstalled": true
  }
}
Current CLI version:  7.0.11
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command resolveCommand is before-resolveCommand
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command resolveCommand is after-resolveCommand
Could not find an installed runtime, falling back to default runtimes
Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal.
The stackTrace of the location trying to handle SIGINT is:
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:26:28)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:128:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:126:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:36:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:331:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/detached-processes/cleanup-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Shasum of file /Users/arijitdas/Autility/Repository/test/package.json is 93ed2b1c40849bdc0ef284a2b7fe088e26e9f8c7
Got cached result for shouldMigrate for platform: iOS
Could not find an installed runtime, falling back to default runtimes
Could not find an installed runtime, falling back to default runtimes
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command checkEnvironment is before-checkEnvironment
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Error while trying to parseJson  data from /Users/arijitdas/.local/share/.nativescript-cli/doctor-cache.json file. Err is: SyntaxError: Unexpected end of JSON input
getInfos cacheConfig options: { forceCheck: undefined }  current info from cache:  null
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Warnings:WARNING: There was a problem with CocoaPods',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 12.2.0 satisfies minimum required version 10.
✖ WARNING: There was a problem with CocoaPods 
 Verify that CocoaPods are configured properly. 

Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: false',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Your environment is not configured properly and you will not be able to execute local builds.
Select "Sync to Playground" to enjoy NativeScript without any local setup. All you need is a couple of companion apps installed on your devices.
Select "Configure for Local Builds" to run the setup script and automatically configure your environment for local builds.
Select "Skip Step and Configure Manually" to disregard this option and install any required components manually.
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Environment Requirements',
  label: 'User should select: Your environment is not configured properly and you will not be able to execute local builds.\n' +
    'Select "Sync to Playground" to enjoy NativeScript without any local setup. All you need is a couple of companion apps installed on your devices.\n' +
    'Select "Configure for Local Builds" to run the setup script and automatically configure your environment for local builds.\n' +
    'Select "Skip Step and Configure Manually" to disregard this option and install any required components manually.',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}

**Comment by samiul-gtmi** [comment]
I am facing the same issue, after Xcode upgrade from 11.3.1 to 12.5.1. How did you fixed it? I installed and uninstalled cocoapods everyway possible, but no luck.
