### ISSUE TITLE
Unable to install NativeScript CLI - Cannot find module 'hawk'

### ISSUE THREAD

**Issue by kayveedw** [NativeScript/nativescript-cli#4315]
Environment
Provide version numbers for the following components (information can be retrieved by running tns info in your project folder or by inspecting the package.json of the project):

CLI: 5.1.1
npm: 6.7.0
node: v10.15.0
Describe the bug
Unable to install NativeScript CLI via npm. It gives an error:

Cannot find module 'hawk'

I've also tried npm i -g nativescript@5.0 which installs nativescript@5.0.4. This has the same error.

To Reproduce
```
npm i -g nativescript
```
Expected behavior

Additional context
```
C:\Users\micro>npm i -g nativescript
C:\Users\micro\AppData\Roaming\npm\tns -> C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\bin\tns
C:\Users\micro\AppData\Roaming\npm\nativescript -> C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\bin\tns

nativescript@5.1.1 postinstall C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript
node postinstall.js

Cannot find module 'hawk'
Failed to display command help { Error: Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.
at Errors.fail (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
at Errors.failWithoutHelp (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:135:21)
at HelpService. (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\help-service.js:178:26)
at Generator.next ()
at fulfilled (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\help-service.js:4:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
name: 'Exception',
message:
'Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.',
stack:
'Error: Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.\n at Errors.fail (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)\n at Errors.failWithoutHelp (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:135:21)\n at HelpService. (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\help-service.js:178:26)\n at Generator.next ()\n at fulfilled (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\help-service.js:4:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)',
errorCode: 127,
suppressCommandHelp: true,
proxyAuthenticationRequired: false,
printOnStdout: undefined }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\nativescript\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

nativescript@5.1.1
added 912 packages from 1345 contributors in 36.94s
```

**Comment by kayveedw** [comment]
Originally posted to the main NS project repro at https://github.com/NativeScript/NativeScript/issues/6836. Moved here as it seems to be a CLI issue.

**Comment by kayveedw** [comment]
Hi @Fatme,

I ran npm cache clean --force and then npm i -g nativescript and it is still the same. Same error message.

**Comment by kayveedw** [comment]
Similar problems with NS 4
```
C:\Users\micro>npm cache clear --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\micro>npm i -g nativescript@4
C:\Users\micro\AppData\Roaming\npm\nativescript -> C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\bin\tns
C:\Users\micro\AppData\Roaming\npm\tns -> C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\bin\tns

> nativescript@4.2.4 postinstall C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript
> node postinstall.js

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:137:5)
    at require (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:110:12)
    at util.js:25:21
    at req_ (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:137:5)
    at require (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:110:12)
    at fs.js:42:21
    at req_ (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\micro\AppData\Roaming\npm\node_modules\nativescript\node_modules\fstream\node_modules\graceful-fs\fs.js:1:99)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\nativescript\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ nativescript@4.2.4
added 743 packages from 1211 contributors in 26.255s
```

**Comment by rosen-vladimirov** [comment]
Hey @kayveedw ,
It looks like there are two different errors in this case and I would like to try to understand what's causing each of them. Maybe they are caused by the same reason, I'm not sure about it.

In both cases, NativeScript CLI is successfully installed, but the postinstall script is failing. Note, that this does not prevent the installation, so you should be able to run `tns --version` for example.
For the first case - the missing `hawk` plugin, it seems CLI reached to the point where it tries to generate the html help for the commands (CLI does this at postinstall), but it fails. I'm not sure what can cause the issue here, but it seems we are trying to execute some http request, but the module we are using (`request`) is not installed correctly (`hawk` plugin is dependency of `request`).

In order to try fixing the issue with `hawk` plugin, can you try the following steps:
1. Navigate to `%APPDATA%\.nativescript-cli` and check if you have `extensions` dir there - in case you have it, please delete it.
2. Uninstall the CLI - `npm un -g nativescript`
3. Manually clean your cache dir - check the output of `npm config get cache` command and manually delete the directory
4. Install CLI - `npm install -g nativescript`

Regarding the second issue - it looks like you are installing CLI 4.2.4, which does not support Node.js 10.15.0.

**Comment by kayveedw** [comment]
Hi @rosen-vladimirov,

That fixed it, I did have an ```extensions``` folder. After I removed it, it installed without a problem. I guess it was left over from an older version of CLI that was installed. It has been a good few months since I was working on NS on this PC. Not sure which version of CLI was the last one before I updated yesterday.

Thanks,

David

**Comment by narayananl23** [comment]
I see the same, I also installed hawk manually. no use

here is my tns doctor

✔ Getting environment information

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 9.1.0 satisfies minimum required version 9.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.1 version and is up to date.
✔ Component tns-core-modules has 5.1.2 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.1 version and is up to date.
Cannot find module 'hawk'
# tns doctor

**Comment by rosen-vladimirov** [comment]
Hey @narayananl23 ,
Can you try the following steps:
1. Navigate to `~/.local/share/.nativescript-cli` and check if you have `extensions` dir there - in case you have it, please delete it.
2. Try `tns doctor` again.
