### ISSUE TITLE
Angular Nativescript Code sharing project, multiple in workspace

### ISSUE THREAD

**Issue by Lightk3ira** [NativeScript/nativescript-cli#4318]
**Environment**

'tns info'
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.1.0 and the latest available version is 5.1.1.
‼ Update available for component tns-core-modules. Your current version is 5.1.1 and the latest available version is 5.1.2.
√ Component tns-android has 5.1.0 version and is up to date.
× Component tns-ios is not installed.

 - CLI:  @angular/cli@7.1.4
 - Cross-platform modules: N/A
 - Android Runtime: latest
 - iOS Runtime: N/A
 - Plugin(s): N/A

**Describe the bug**
Hello The nativescript + Angular Code sharing project works as expected however I believe it is expected that many developers will want to utiliize angular workspaces with multiple applications.

In my workspace I have two nativescript + angular code sharing projects. In my actual projects in a workspace I have an nsconfig.file that points to the files as well as overridden in webpack.config.js for testing as I am not fully sure if the nsconfig is working as expected

When generating a new platform it can never find the Android Manifest in a project, (which is expected) I assume on build It will override these values anyways. However Near the end of running 'tns run android --bundle' it seems to try to direct to a default folder of 'app/' which I cannot see even in a new code sharing project by itself so I am led to believe this is some sort of default path.

Error as as follows:
```
...
[./package.json] 129 bytes {bundle} [optional] [built]
    + 382 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Could not find folder: C:\Users\userNameHere\Desktop\projects\myProjects\AngularWorkSpace**\app**
Unable to apply changes on device: emulator-5554. Error is: ENOENT: no such file or directory, stat 'C:\Users\userNameHere\Desktop\projects\myProjects\AngularWorkSpace**\app**\App_Resources\Android'.

```

**Showing Angular workspace with 2 projects and a feature library:**
![image](https://user-images.githubusercontent.com/8987009/51859494-415e0480-2305-11e9-85f5-9420342b1070.png)

![image](https://user-images.githubusercontent.com/8987009/51860033-9ea68580-2306-11e9-9cb3-4b5e3fb18598.png)

**To Reproduce**
Create a new empty workspace
Add 2 nativescript Angular code sharing projects
Add a library (possibly not neccessary)
Set up similar structure for reusable platform and webpack.

Update nsconfig inside project 1 and 2
{
  "appResourcesPath": "projects/applicationOne/App_Resources",
  "appPath": "projects/applicationOne/src",
  "nsext": ".tns",
  "webext": "",
  "shared": true
}

**Expected behavior**
Should be able to have an Angular workspace with multiple applications projects added.
1 webpack.config.js for handling building. An nsconfig.js per application in the projects folder for paths.
To build per application.

**Additional context**
I believe I have everything set up correctly. I think the only issue is 
`Could not find folder: C:\Users\userNameHere\Desktop\projects\myProjects\AngularWorkSpace**\app**`
The \app i think is the default when a path iis not specific or  found. it should be pointing to 
..AngularWorkspace/projects/applicationOne

**Comment by sis0k0** [comment]
Hi @Lightk3ira,

Thank you for the suggestion!
Developing multiple projects in a single Angular workspace is indeed something we need to support. We're currently tracking the progress of the feature here - https://github.com/NativeScript/nativescript-schematics/issues/25.
