### ISSUE TITLE
Cocoapod and Framework in Plugin creates invalid podfile

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#4319]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - iOS Runtime:5.1.0
 - Plugin(s): Creating one

**Describe the bug**
I have a plugin I'm creating that has a custom Framework and a podfile in the /platforms/ios folder.
When the CLI creates the app `Podfile` it screws up the configuration of the podfile.

The error reported; please note; app is named: `demo2`, custom framework is named `awsyncwrapper`
```
Analyzing dependencies
[!] Unable to find a target named `awsyncwrapper`, did find `demo2`.

[!] Automatically assigning platform `ios` with version `9.0` on target `demo2` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
'pod install' command failed.
```
Pod file created:
```
use_frameworks!

target "demo2" do
# Begin Podfile - /path/to/node_modules/pod_file
target 'awsyncwrapper' do
  use_frameworks!
  
  pod 'AWSAppSync', '~> 2.6.24'
end

# End Podfile
end
```

**To Reproduce**
Create a plugin the "src/platforms/ios" directory with both a framework and a simple Podfile linking to any cocoapod.
`tns create demo`
`tns plugin add ../src`
`tns build ios`  

**Expected behavior**
Everything works properly.  :grinning:

**Sample project**
If need be I can give you access to it; however I will be converting the framework file into its own podfile to eliminate this issue myself in the future as this is for a client.  

**Additional context**
To temporarily fix; manually update the generated `Podfile` and remove three lines: the `target`, `use frameworks!` and one of the `end` statements.

**Comment by Fatme** [comment]
Hey NathanaelA,

I'm not sure I understand correctly your case. 

Meanwhile, I'll try to explain the current workflow. {N} CLI iterates over the all {N} plugins from your project. For each of them {N} CLI checks if there are frameworks, native source code files, static libs or cocoaPods in `platforms/ios` folder of the plugin. If {N} CLI find some of the above mentioned files, it prepares them in a specific way. Let's take a look what is the exact algorithm:
*  frameworks - {N} CLI adds a reference to the `.framework` file in all required sections and phases of your Xcode project using [xcode](https://www.npmjs.com/package/xcode) package. On this step we have only one target in our Xcode project and all modifications are applied **only** in this target.
* podfiles - {N} CLI merges the content of the podfile in project's podfile (the one placed in platforms/ios folder of your project).

After all plugins are processed, {N} CLI executes `pod install`. On this step the project's podfile will be respected and this is the step where you receive the error `Unable to find a target named awsyncwrapper, did find demo2`. The error is correct as no target named `awsyncwrapper` is added to your Xcode project.

> NOTE: `pod install` produces an additional target named 'Pods' to your Xcode project. {N} CLI does not modify this target.

So the question here is why do you need to specify a `awsyncwrapper` target in your podfile. If no target is specified, it should work. I'm not sure what are the exact expectations.
Can you please share some additional details and describe what is exactly the purpose of this target?

**Comment by NathanaelA** [comment]
My apologies the original podfile I created in the project had the extra target in it.   This was pure user error.  :grinning:        

I went back in my commit history to double check the validity (as I've switched my it all to pod's and no longer have a framework) and noticed that the original `podfile` had the target in it.
