### ISSUE TITLE
Question: Any way to build on iOS and put a file in the ROOT directory (not /app) directory

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#4320]
**Environment**
 - CLI: 5.1.1

**Describe the Question**
I have a data file that I really need to put in the absolute root of the application project in an iOS application.   I can build; then manually drag it out of the "app/" folder into the root folder in xcode so that it is now linked to its proper location.   

 But is their some way I could have TNS by default put it into the root folder of the app?

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA ,
You can achieve this with `after-prepare` hook, where you can get the path to the actual file (I assume it is part of your app folder) and move it to the correct place. The only problem with this approach is that in case you need to rebuild your application every time when it is changed, the CLI will not detect this. You can workaround this behavior as well by placing the file in your App_Resources directory and in the after-prepare hook move it to correct place.
Do you think the suggested solution will work for you?

**Comment by NathanaelA** [comment]
Yes, this can work for me.   Thank you!

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA ,
I'm not quite sure I understand what's the requirement. Can you confirm my understanding is correct:
- you have a file, that must be at the root in `<project dir>/platforms/ios`
- you need this file to be included in the Xcode project, for example as a framework or a resource
Is this correct?

Meanwhile, I'll try to explain the way CLI creates the Xcode project:
1. When you have a NativeScript application, you do not have `platforms/ios` directory.
2. On any `ios` related command (like `tns platform add ios`, `tns prepare ios`, etc., NativeScript CLI gets the `tns-ios` version from package.json of the project (or calculates which version to add) and downloads it from npm. After it is downloaded, it is extracted in `<project dir>/platforms/ios` directory.
3. At this point the `<project dir>/platforms/ios` directory already contains .xcodeproj file (it is included in the `tns-ios` package. CLI renames it based on your project dir and applies some additional string replacements. 
4. After that CLI starts preparing your project files (including `node_modules`). 

So there's no way to plug in before creating the Xcode project as it is not actually created based on your files - it is static at the beginning and CLI just modifies it based on your project files.

In case my assumption what you need to do is correct, you can still use the `after-prepare` hook to move the file, but you'll have to reference your file in the Xcode project. Usually this is done with the `https://www.npmjs.com/package/xcode` package, so you can add it as a devDependency of your project and require it in the hook.

If I've not understood what is your use-case, can you please share some additional details?

P.S. Here's a link with more information about hooks and how they are executed in CLI, I think the schemes may be useful for this case: https://www.dropbox.com/sh/yri0q3ubf38kezk/AAAtUER2rg9piqm0_MlvQa6Ia?dl=0

**Comment by NathanaelA** [comment]
Hi @rosen-vladimirov,

I have a plugin that requires a JSON file to be included in the actual app at the very root level.  Unfortunately Amazon does not give me a way to configure where this file lives.     If I use a after-prepare step to copy the file to the parent directory from the `app`; Xcode doesn't seem to pick it up when TNS/xcode is building the app.  I need tns/xcode to pick it up so it is considered part of the app.

![image](https://user-images.githubusercontent.com/850871/52046687-f57dac00-250c-11e9-94e1-73ff1edaa66a.png)

So right now; I have to build once with TNS.   Open xcode; navigate to the xcworkspace; Then drag the awsconfiguration.json file from the "app/" folder to the parent "demo" folder.  Then you get the "awsconfiguration.json" showing right under "demo" and right above the "app/"  folder.   I then have to click on it; and then click the target membership box.  With those steps I'm good to go.

What I want is that this is all automatically done, the version I put in the "app" folder is automatically told that it belongs in the root app directory.

Does that make sense?

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA ,
Thank you for the detailed description. I've created a sample application with custom hook, which should implement what you've described. You can find it here:
https://github.com/rosen-vladimirov/appAwsConfig

You can find more information for the implementation in the README.md file. Can you give it a try and see if it resolves your issue?

**Comment by NathanaelA** [comment]
I didn't realize the hook could actually update the project file, which was the missing piece.  Looking at your sample; looks like it should work at first glance.    ;-)   Will test shortly!

**Comment by NathanaelA** [comment]
Awesome I was able to make a couple changes to your hook script and make it all work properly the way I needed it to.    

1. Out of curiosity is their a way during hook install we can request npm to install "xcode" or do I have to just make sure to note this needs to be added "npm i --save-dev xcode" in the readme?   Adding it as a dev requirement to the plugin, won't get it installed.  Peer requires manual install; and of course full dependency means it would then try to package up the xcode into the app; which isn't needed.

2. Does TNS use that "xcode" library in any of its modules, if so -- any chance the hook can get the global directory and require the global copy of xcode?

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA ,
I'm glad it worked on your side. In fact there's a way to achieve the desired solution without installing `xcode` - CLI uses it and exposes it through `$xcode` module. However, CLI is using a fork for the package and we've not updated this fork for a while. So I had to adjust the code a little bit to make it work - https://github.com/rosen-vladimirov/appAwsConfig/commit/c965bd74eb1ded0f1391402131807a3e54c7472c 
With this approach there's no need to install xcode anywhere.

As for the second question - there's one package that I've written some time age - [global-modules-path](https://www.npmjs.com/package/global-modules-path) - you can use it to determine the path to the globally installed CLI:
```JavaScript
const pathToCLIDir = require("global-modules-path").getPath("nativescript", "tns");
const pathToXcodeInCLI = path.join(pathToCLIDir, "node_modules", "xcode");
```

However, I believe the first solution is more appropriate in this case.

**Comment by NathanaelA** [comment]
First solution is definitely better!   Thank you Rosen.
