### ISSUE TITLE
Angular apps do not work with HMR out of the box

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#4325]
**Environment**
 - CLI: 5.1.1
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s): nativescript-dev-webpack: 0.19.1

**To Reproduce**
1) `tns create ngApp --ng && cd ngApp`
2) `tns run android --hmr` or `tns run ios --hmr`
3) Apply some change in order to trigger the LiveSync process.
4) The app will not get the change applied.

**Expected behavior**
The app should get the change applied.

**Additional context**
In order to get the HMR working in Angular apps, I have to follow the steps in this wiki: https://github.com/NativeScript/nativescript-angular/wiki/HMR.

**Comment by endarova** [comment]
With CLI 5.2.0  and nativescript-dev-webpack@0.20.0

- [ ]  --env flag should leave your project with its current setup
- [ ]  --hmr should  automatically setup your project for hmr and apply changes on device without additional snippets 
- [ ]   no warning for --hmr + Angular are shown on tns run and tns debug
- [ ]  tns run --hmr should work as expected in angular projects
- [ ]  tns debug --hmr should work as expected in angular projects
