### ISSUE TITLE
Objective-C code in App Resources not included in iOS application

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#4343]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: next
 - Cross-platform modules: 5.1.2
 - iOS Runtime: 5.1.1

**Describe the bug**

After build the native classes in the Objective-C files inside App Resources are not available for use in the application.

**To Reproduce**

Download sample project and then use `tns run ios`.

**Expected behaviour**
To be able to use the native classes defined in the Objective-C files inside App Resources.

**Sample project**
[testSrc.zip](https://github.com/NativeScript/nativescript-cli/files/2836504/testSrc.zip)
When you run the project, click the "Tap" button and `CONSOLE LOG file:///app/main-view-model.js:18:20: Hey!` log should appear.

**Additional context**

Additionally, please verify that after removing `...app/App_Resources/iOS/src` the project will rebuild and deploy successfully (it is expected that the application will crash if the button is clicked).

**Comment by rosen-vladimirov** [comment]
NOTE: You can place your Objective-C code in `<path to App_Resources/iOS/src` directory.
