### ISSUE TITLE
feature: preview <module> (page)

### ISSUE THREAD

**Issue by flddr** [NativeScript/nativescript-cli#4366]
While i am very very happy today with `tns preview` (which qr-code works for android and ios in parallel :+1: :1st_place_medal: ), i would like to only watch all designed (updated) pages quickly, like the following commands:

`tns preview home-page`
`tns preview second-page`
...

Meanly, without tapping through the app. Just for design, not functionallity.

Do you mean this could be interesting and possible / help in workflow?

**Comment by endarova** [comment]
Hi @flddr , 
For now I can suggest a workaround  to ease your work. You can set the page you are designing temporary as a home page, that way even if  the app restarts you will be still on the desired view. Also if you  are using webpack you can benefit from our HMR(Hot Module Replacement) feature. It is currently in beta, but when  you run ‘tns preview  --hmr’  even if you change js and ts files the changes will be updated without restarting your application.

**Comment by flddr** [comment]
Hi @endarova 

Oh, ok, yes, first way: i know,

second way: `--hmr` sounds interesting, too :+1: 

Because of HMR, i am not sure about this feature request. You can close if you don't like, but, the idea behind is different to HMR at least (just a _design-preview_). So, it's a question about having a _design-preview_ without completed _business-logic_; is it worth to implement that if possible - i don't know :relaxed: Using `playground` and `preview` gives already great experience - could be a next step to have a very quick layout-preview while coding :blush: As far as i know this isn't available on any framework out there ...
