### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by bradrice** [NativeScript/nativescript-cli#4369]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
NativeScript CLI version: 5.2.0
CLI extension nativescript-cloud version: 1.16.0
CLI extension nativescript-starter-kits version: 0.3.5

**Describe the bug**
Just trying to run tns run ios to a device

**To Reproduce**
tns run ios

**Expected behavior**
build and runs my app

**Additional context**
This is what I get when I try to build

Whenever I try to build to a device I'm getting this error:

Error Domain=IDEProvisioningErrorDomain Code=8 "binding.node has conflicting provisioning settings." UserInfo={NSLocalizedDescription=binding.node has conflicting provisioning settings., NSLocalizedRecoverySuggestion=binding.node is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified. Remove the "signingCertificate" entry from your Export Options property list, or switch to manual signing by setting "signingStyle" to "Manual.}

I can build to a simulator just fine. What would this be?

**Comment by DimitarTachev** [comment]
Hi @bradrice,

Reviewing the above-mentioned logs, we suppose that you might have a dev dependency in your dependencies list.

Please take a look at [this StackOverflow thread](https://stackoverflow.com/questions/54512390/nativescript-5-1-and-tns-modules-folder-in-ios-build/54512538#54512538) for more details and if you are not able to find any dev dependencies there, please share your dependencies list (the one from your package.json) in order to allow us investigate this further.

**Comment by bradrice** [comment]
`{
  "description": "Tooling U Class Player",
  "license": "private",
  "readme": "NativeScript Application",
  "repository": "https://github.com/toolingudev/classappnativescript.git",
  "name": "class2tns",
  "version": "0.1.0",
  "scripts": {
    "test": "ng test"
  },
  "nativescript": {
    "id": "com.toolingu.class2tns",
    "tns-android": {
      "version": "5.2.0"
    },
    "tns-ios": {
      "version": "5.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "async-await": "^0.1.40",
    "lodash": "^4.17.11",
    "moment": "^2.22.0",
    "nativescript-angular": "^7.2.1",
    "nativescript-audio": "5.0.1",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-orientation": "^2.2.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "^5.1.0",
    "nativescript-ui-sidedrawer": "^5.1.0",
    "nativescript-videoplayer": "^4.1.0",
    "nativescript-webview-interface": "^1.4.2",
    "nativescript-xmlobjects": "^1.1.4",
    "node-sass": "^4.11.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.2.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.13.1",
    "@angular/cli": "7.3.1",
    "@angular/compiler-cli": "~7.1.0",
    "@ngtools/webpack": "^6.2.7",
    "@types/lodash": "4.14.68",
    "@types/node": "~6.0.60",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "jasmine-core": "^3.1.0",
    "karma": "^3.1.1",
    "karma-jasmine": "^1.1.1",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "^0.8.0",
    "nativescript-dev-webpack": "^0.20.0",
    "nativescript-unit-test-runner": "0.4.1",
    "tns-platform-declarations": "5.2.0",
    "ts-node": "~3.3.0",
    "tslint": "^5.8.0",
    "typescript": "~3.1.1"
  },
  "author": "bradrice"
}
`

**Comment by DimitarTachev** [comment]
@bradrice  As far as I see `node-sass` should be the problematic dependency. Try moving it to the `devDependencies` list, remove the `platforms` and `node_modules` folders and run your app.

**Comment by bradrice** [comment]
i've corrected that. Now, I've discovered that an issue is cropping up when I try to run to a ios device that has 9.3.5 installed. How do I work through issues with lower ios? What happens is the app installs but crashes when it launches. I created a simulator with that version of software and I see it generate this error in the console:

BUG in libdispatch: 18D109 - 715 - 0x16

My app does run fine in iOS 12.

**Comment by NickIliev** [comment]
@bradrice closing the issue as the original issue is resolved. 

Please post any new issues is separate threads and in the related repositories. In your last case, the issue seems suitable for logging  [a new one in ios-runtime repository](https://github.com/NativeScript/ios-runtime/issues/new?template=bug_report.md) - make sure to provide all the details requested in the issue template.
