### ISSUE TITLE
Create app with --template default@version and webpack.config.js missing

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#4371]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.0

**Describe the bug**
When create app with template default@version, you will see that you don't have all dependencies in node_modules and package.json

**To Reproduce**
1. `tns create app --template default@5.0.0`
2. open `node_modules` and you will see only : `nativescript-theme-core`, `tns-core-modules`, `tns-core-modules-widgets`, `tslib`

**Expected behavior**
you must have `webpack.config.js`

**Comment by Fatme** [comment]
It seems `@5.0.0` version is released without `webpack.config.js` for some reasons. `5.0.1` version is released 3 hours after `5.0.0` and has `webpack.config.js`
```
npm view tns-template-hello-world time
'5.0.0': '2018-11-02T12:48:25.813Z',
'5.0.1': '2018-11-02T15:15:02.935Z',
```
