### ISSUE TITLE
Show warning for deprecated short imports/require used in application

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#4375]
**Is your feature request related to a problem? Please describe.**
In NativeScript 5.2.0 short imports like `import * as application from "application";` are deprecated, i.e. support for them will be removed in a future version. It would be great in case CLI can analyze the application and report for such imports used in the app.
NOTE: Same is applicable for `const application = require("application");`

**Describe the solution you'd like**
During project build/run, CLI should analyze application's code and inform for used short imports. Same is applicable when running `tns doctor` inside project directory.

**Describe alternatives you've considered**
TSLint rule can do the same for TypeScript projects, but it will not work for JS ones. Also the IDE should have integration with TSLint to see the warning.

**Comment by rosen-vladimirov** [comment]
NOTE: Until now, we were able to use short imports/requires for all packages coming from `tns-core-modules`, i.e. all directories from here: https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules

This means, that we were able to write:
```TypeScript
const fileSystem = require("file-system"); // In JS Project
import * as fileSystem from "file-system"; // In TS Project
```

From now on, in case you have such short imports/require, during `tns doctor`, `tns prepare <platform>`, `tns run <platform>`, `tns build <platform>` , `tns debug <platform>` and `tns test <platform>`, CLI will notify you that these short imports are deprecated and you should replace them in your code.

CLI will not notify you for short imports inside `node_modules` directory.

**Comment by tdhman** [comment]
Hello, 
After upgrading to NS 5.2.0, I got a lot of warning because of `short import` in my project's assets. Since my application will need to execute some static javascript resources in webview, I have added these js as static assets under the folder `app/assets`, but when build the app, the cli show warning reports for also my js files. Is there any way to turn off the verification for resource files ? 
Thanks.

**Comment by rosen-vladimirov** [comment]
Hey @tdhman ,
Can you please post an example of some warnings generated for your application, so we can investigate them?

**Comment by tdhman** [comment]
Hello, 
This is one of the import warning I got, actually I got this for every js file in my assets folder.

`In file /../app/assets/www/IM.js line <This is content of my minified js>: is short import. Add tns-core-modules/ in front of the required/imported module.`

**Comment by rosen-vladimirov** [comment]
Hey @tdhman ,
Is it possible to send us the minified js file, so we can investigate the issue further. We have an idea what's going wrong, but it will be great in case you can send us the real world scenario for this case.
In case you do not want to send it here, you can find me in the [NativeScript Community Slack](https://nativescriptcommunity.slack.com/) - search for `vladimirov`

**Comment by miroslavaivanova** [comment]
@tdhman You can try the fix with the ```rc``` version. Just install CLI like this ```npm i -g nativescript@rc```.

**Comment by tdhman** [comment]
@miroslavaivanova I install the `rc` version as you suggested (`+ nativescript@5.2.4-2019-03-19-13041`) but it does not resolve the issue.

**Comment by rosen-vladimirov** [comment]
Hey @tdhman ,
Can you please send us at least one of the minified files that triggers the issue you've faced. Without it we are unable to provide additional fix, as currently we are not sure what causes the incorrect behavior.
I'm looking forward to hearing from you.

**Comment by tdhman** [comment]
Hello @rosen-vladimirov, one of the minified js that cause the tns warning of import is [UWA_Standalone_Alone.js](http://uwa.netvibes.com/lib/c/UWA/js/UWA_Standalone_Alone.js).

**Comment by rosen-vladimirov** [comment]
Hey @tdhman , thanks a lot, we've identified the issue and we've provided a fix in our `next` version.
Can you please use `npm install -g nativescript@next` and after that try `tns run <platform>` again, the warnings should be gone.

**Comment by tdhman** [comment]
Hello @rosen-vladimirov,

I tried the version `nativescript@next` and yes, it does not show any wrong short import warnings.
However, I cannot build & run my app with `tns run <platform>` command. It always shows me the error below. I have to rollback to `nativescript@5.1.1` & everything works fine. I'm using XCode 10.1.

```
** ARCHIVE FAILED **

Unable to apply changes on device: <deviceId>. Error is: Command xcodebuild failed with exit code 65.
```

**Comment by rosen-vladimirov** [comment]
Hey @tdhman 
We are working on a fix for the xcodebuild error in our `next` version. Thanks for testing it!

**Comment by rosen-vladimirov** [comment]
Hey @tdhman , 
We've fixed the issue, can you please try with latest `next` or `rc` version of CLI?

**Comment by tdhman** [comment]
@rosen-vladimirov I install the latest `next` version & the CLI works as expected.
Thanks a lot for your support.

**Comment by thungapallyharish** [comment]
In file /Users/sreevalli/Project/master/app/addattachments/addattachments.component.ts line import * as app from 'application' is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/addattachments.component.ts line import * as fs from "file-system" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/addattachments.component.ts line import { android as androidApp, ios as iosApp } from "application" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/documentpicker.android.ts line import * as fs from "file-system" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/documentpicker.android.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/documentpicker.ios.ts line import * as utils from "utils/utils" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/documentpicker.ios.ts line import { ios as iosApp } from "application" is short import. Add tns-core-modules/ in front of the required/a module.
In file /Users/sreevalli/Project/master/app/addattachments/documentpicker.ios.ts line import * as fs from "file-system" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/addattachments/documentpicker.ios.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/app.component.ts line let applicationSettings = require("application-settings") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/completeprofile/completeprofile.component.ts line import * as fs from "file-system" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/completeprofile/completeprofile.component.ts line import { Image } from "ui/image" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/completeprofile/completeprofile.component.ts line import view = require("ui/core/view") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/completeprofile/completeprofile.component.ts line import * as app from 'application' is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/completeprofile/completeprofile.component.ts line var applicationSettings = require("application-settings") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/createcontext/createcontext.service.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/createcontext/createcontext.service.ts line import * as fs from "file-system" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/folders/myfolders.component.ts line import { AnimationCurve } from "ui/enums" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/home/home.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-attachements.component.ts line import { Page } from "ui/page" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-attachements.component.ts line import { ActionItem } from "ui/action-bar" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-attachements.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-attachements.component.ts line import { android as androidApp, ios as iosApp } from "application" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-attachments-preview.component.ts line import { Page } from "ui/page" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-attachments-preview.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-detail.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item-detail.component.ts line import {Page} from "ui/page" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/item/item.service.ts line import * as fs from "file-system" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/login/login.component.ts line var view = require("ui/core/view") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/login/login.component.ts line var applicationSettings = require("application-settings") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/login/splash.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/login/splash.component.ts line var view = require("ui/core/view") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/login/splash.component.ts line var applicationSettings = require("application-settings") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/notes/mynotes.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/notes/notes.component.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/notifications/notification.ts line var applicationSettings = require("application-settings") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/pricing/pricing.service.ts line import * as dialogs from "ui/dialogs" is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/settings/settings.component.ts line var applicationSettings = require("application-settings") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/vendor-platform.android.ts line require("application") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/vendor-platform.android.ts line require("ui/frame") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/vendor-platform.android.ts line require("ui/frame/activity") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/vendor.ts line const application = require("application") is short import. Add tns-core-modules/ in front of the required/imported module.
In file /Users/sreevalli/Project/master/app/vendor.ts line require("ui/styling/style-scope") is short import. Add tns-core-modules/ in front of the required/imported module.

**Comment by thungapallyharish** [comment]
how to fix it
