### ISSUE TITLE
tns build android --aab --env.snapshot  app crashes with tns-android@next

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4384]
- CLI: next
 - Android Runtime: tns-android@next
 

Steps:
1. tns create TestApp --js
2. in app.gradle add: 
    defaultConfig {  
    generatedDensities = []
	ndk {
      abiFilters.clear()
    }
  }  
sourceSets {
    main {
        jniLibs.srcDirs = ["$projectDir/libs/jni", "$projectDir/snapshot-build/build/ndk-build/libs"]
	}
3. In webpack.config.js add:
    if (snapshot) {
        config.plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
            chunk: "vendor",
            requireModules: [
                "tns-core-modules/bundle-entry-points",
            ],
            projectRoot,
            webpackConfig: config,
			targetArchs: ["arm", "arm64", "ia32"],
            useLibs: true,
			androidNdkPath: "$ANDROID_NDK_HOME"
        }));
    }
4. Execute: tns build android --release --aab --env.uglify --env.snapshot --bundle
5. Use bundletool to deploy on device

Expected: App should run on device
Actual: App is crashing

**Comment by darind** [comment]
Which version of the `nativescript-dev-webpack` plugin are you using?

**Comment by endarova** [comment]
The version was "nativescript-dev-webpack": "~0.19.0" (the default in the template projects)  . I can confirm that updating to nativescript-dev-webpack@next fixes the issue. Thanks.

**Comment by darind** [comment]
Thanks for confirming. The @next android runtime is only compatible with nativescript-dev-webpack@latest. We have discussed with the CLI team to add a warning if such incompatibility is detected in the project.
