### ISSUE TITLE
execution failed for task ':app:runsbg' android after tns plugin add

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-cli#4409]
_From @dreweird on February 28, 2019 1:39_

**Environment**
package.json
{
    "nativescript": {
        "id": "org.nativescript.HelloWorld",
        "tns-ios": {
            "version": "5.1.1"
        },
        "tns-android": {
            "version": "5.1.0"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "@angular/animations": "~7.1.0",
        "@angular/common": "~7.1.0",
        "@angular/compiler": "~7.1.0",
        "@angular/core": "~7.1.0",
        "@angular/forms": "~7.1.0",
        "@angular/http": "~7.1.0",
        "@angular/platform-browser": "~7.1.0",
        "@angular/platform-browser-dynamic": "~7.1.0",
        "@angular/router": "~7.1.0",
        "nativescript-angular": "~7.1.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-dataform": "^3.10.0",
        "nativescript-ui-sidedrawer": "^5.1.0",
        "reflect-metadata": "~0.1.12",
        "rxjs": "~6.3.0",
        "tns-core-modules": "~5.1.0",
        "zone.js": "~0.8.26"
    },
    "devDependencies": {
        "@angular/cli": "^7.3.3",
        "@angular/compiler-cli": "~7.1.0",
        "@nativescript/schematics": "~0.5.0",
        "@ngtools/webpack": "~7.1.0",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "~0.19.0"
    },
    "gitHead": "9b6565a4513375a33a59c44262dfc1d818a8205e",
    "readme": "NativeScript Application"
}

 
**Describe the bug**
BUILD FAILED i
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat
failed with exit code 1.

**To Reproduce**

When i add plugin, tns plugin add nativescript-ui-dataform
I fix the error by typing the command again everytime I add plugins

-tns platform remove android
-tns platform add android
-tns run android

**Expected behavior**

**Sample project**

**Additional context**

_Copied from original issue: NativeScript/nativescript-angular#1751_

**Comment by tsonevn** [comment]
Hi @dreweird,
I was able to recreate the issue and it seems to be related to nativescript-cli. I will mark it as a bug and we will investigate it further. 
As a workaround, you can delete the `platforms` folder after `tns plugin add <plugin name>` command and rebuild the project.

**Comment by Fatme** [comment]
Related to: https://github.com/NativeScript/android-runtime/issues/1257
