### ISSUE TITLE
Generate resources from a single image for use in res:// URLs

### ISSUE THREAD

**Issue by bundyo** [NativeScript/nativescript-cli#4416]
**Is your feature request related to a problem? Please describe.**
In order to to use res:// URLs in the app, a developer has to start an image editing program and create all the different images for the different resource folders in all platforms. It will be good if CLI/Sidekick provide a way to generate all these images and place them in their designated folders with just one image with sufficiently high resolution.

**Describe the solution you'd like**
Do something like
```
tns resources add menu.png
```
This should generate menu.pngs with different resolutions for Android and place them in drawable-hdpi, drawable-xhdpi, etc. folders and menu.png, menu@2x.png, menu@3x.png and place them in the iOS folder.

**Comment by lee-devopa** [comment]
This would be a really nice addition! +1

**Comment by Kweku7k** [comment]
<img width="1440" alt="Screenshot 2020-07-24 at 1 46 52 PM" src="https://user-images.githubusercontent.com/51480704/88397943-2d894680-cdb4-11ea-8204-955607e7df4c.png">
Hi guys, brosteins is down, is there another image builder I can use?

**Comment by NathanaelA** [comment]
You can use both the TNS cli, or https://images.nativescript.rocks
