### ISSUE TITLE
increased app size when building for ios with --bundle --env.uglify

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4425]
- CLI: next (5.3.0)
 - tns-ios@next
 -nativescript-dev-webpack@next

The app size of angular project built with bundle and env. aot and  env. uglify flag has increased lately. 'Actual app size:16167835. Expected size:  15386993'

Steps:
1. tns create TestApp --ng
2. Install tns-ios@ next and nativescript-dev-webpack@next
3. tns build ios --bundle --release --for-device
4. tns build ios --bundle  --release  --for-device  --env.aot  --env.uglify

**Comment by rosen-vladimirov** [comment]
Closing as the regression is not caused by CLI. Seems it is caused by Angular release.
