### ISSUE TITLE
ability to use `--bundle` as the default

### ISSUE THREAD

**Issue by cowboyd** [NativeScript/nativescript-cli#4439]
**Is your feature request related to a problem? Please describe.**
It seems to me that you're either using webpack to build your javascript, or you're not, and if you are, then it's really rare that you don't want to use the `--bundle` option. It's annoying to have to never forget to add this to every single command.

**Describe the solution you'd like**
Some way to set in `nsconfig.json` settings that `--bundle` is the default and to provide a `--no-bundle` option in the event that you _don't_ want to bundle with webpack.

**Describe alternatives you've considered**

Right now, we work around this by having:

```json
{
  "scripts": {
    "build:ios": "tns build ios --bundle",
    "build:android": "tns build android --bundle"
}
```
To wrap every native script command that you might want to use in order to ensure that the `--bundle` flag is set.

**Comment by Fatme** [comment]
Hey @cowboyd,

We've already implemented such functionality in the NativeScript CLI. All you need is to install the next version of NativeScript CLI - `npm i -g nativescript@next` and add the following in your `.nsconfig` file
```
{
    "useLegacyWorkflow": false
}
```

This will enable `hmr` by default for your project for all commands.

**Comment by cowboyd** [comment]
Awesome! That's good to know. It would be great to update the documentation to indicate that the old way is deprecated.

**Comment by Fatme** [comment]
@cowboyd,

Here it the PR to the docs repo - https://github.com/NativeScript/docs/pull/1593.

I'm closing this as a duplicate to https://github.com/NativeScript/nativescript-cli/issues/4389.
