### ISSUE TITLE
Changes of splash screen are not updated on iOS

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4443]
- CLI: 5.2.3

When you change splash screen images and deploy project again on iOS device, the changes are not applied, you still see the old splash screen.
Steps:
1. tns create MyApp --js
2. tns deploy ios
3. tns resources generate splashes new.png
4. tns deploy ios
Expected: The new splash screen is shown on app run.
Actual: The old splash screen is shown on app run. 
The same steps work for android.

**Comment by hettiger** [comment]
If I remember correctly there's some system caching going on. I think the only way to reset these reliably is to reboot the device.

**Comment by Lelelo1** [comment]
> If I remember correctly there's some system caching going on. I think the only way to reset these reliably is to reboot the device.

uninstall -> reboot -> install, to to be exact.

**Comment by JimLynchCodes** [comment]
This imo is a pretty bad bug related to nativescript... doesn't seem to have with native swift apps.

**Comment by vitalyt** [comment]
Solution
Again, thanks to the thread I have referenced above I found a way to solve this issue - name your new image differently from the one there was before in case your new one has the same name as the old one and put it out of the *.xcassets folder to the project directory and reference it in your UIImageView. And that's it.
