### ISSUE TITLE
tns test android --watch false does not exit 

### ISSUE THREAD

**Issue by asgerjensen** [NativeScript/nativescript-cli#4467]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Component nativescript has 5.2.4 version and is up to date.
✔ Component tns-core-modules has 5.2.2 version and is up to date.
✔ Component tns-android has 5.2.1 version and is up to date.
✔ Component tns-ios has 5.2.0 version and is up to date.

**Describe the bug**
`tns test android --watch false` does not exit after a single run

This is the last bit of the output
```
tiveScript / 28 (9; Android SDK built for x86): Executed 8 of 11 SUCCESS (0 secs / 0.23 secs)
NativeScript / 28 (9; Android SDK built for x86): Executed 10 of 11 (skipped 1) SUCCESS (0.614 secs / 0.233 secs)
TOTAL: 10 SUCCESS
JS: NSUTR: completeAck
JS: NSUTR-socket.io: io server disconnect

```

After it writes `disconnect`, the i still have to break it with ctrl-c to get back to the shell

**To Reproduce**
`tns test android --watch false`
or
`tns test android --watch=false`

**Expected behavior**
Tests would run through once, and the cli would exit with exit code 0.

**Additional context**

Required to run tests in CI environments.

`tns test ios --watch=false` gives the following
```
CONSOLE LOG file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:266:24: NSUTR: completeAck
CONSOLE LOG file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:89:28: NSUTR-socket.io: io server disconnect
Child process terminated with signal 15: Terminated
```
and exists as expected

**Comment by Fatme** [comment]
Can you try with `tns test ios --justlaunch`?

**Comment by asgerjensen** [comment]
`tns test android --justlaunch` actually worked.

Thanks

**Comment by cowboyd** [comment]
I was just about to file this ticket when I saw this. IMHO, `--just-launch` should be the default, especially given that there is already a `--watch` flag.

**Comment by Fatme** [comment]
@cowboyd, @asgerjensen,

Sorry for the late reply.

Let me first explain the difference between `—watch` and `—justlaunch` options.

Currently the default value of `—watch` option is true. This means the NativeScript CLI is started in watch mode out of the box. The watch mode means NativeScript CLI watches your source code for changes and automatically transfers the changed files on all connected devices. In other words the watch mode is applicable for all commands that are transferring files on devices - `tns run`, `tns debug`, `tns test`.

The `—justlaunch` option starts the NativeScript CLI in “non-watch” mode.

Based on the above, theoretically it should not have difference between the two options. Practically the behavior is different. The difference is that `—justlaunch` option doesn’t start the application’s log process. An opposite of this, the `—watch false` starts the application’s log process. And that is the reason why NativeScript CLI doesn’t exit when `tns test android —watch false` command is executed.

**Comment by cowboyd** [comment]
I see now how this is the correct behavior, but the fact that the difference is this subtle and requires such a careful explanation indicates that there is something "off" about the API.

Command line options should be intuitive to developers, not confusing. Is there a separate issue to track this?
