### ISSUE TITLE
Executing "$ tns platform add ios" throws exception

### ISSUE THREAD

**Issue by tytodorov** [NativeScript/nativescript-cli#45]
Xcode: Version 5.0.2 (5A3005)

TYTODOROVMAC:kolcho tytodorov$ tns platform add ios --log trace
Starting watch on killswitch /Users/tytodorov/.nativescript-cli/KillSwitches/cli
Looking for project in '/Users/tytodorov/nativeclitest/kolcho'
Project directory is '/Users/tytodorov/nativeclitest/kolcho'.
exec: which xcodebuild
exec: xcodebuild -version | head -n 1 | sed -e 's/Xcode //'
**Version strings are not in the same format**
Usage:
    $ tns platform add <platform>

Platform-specific usage:
    $ tns platform add android
    $ tns platform add ios

Creates a new platform specific project. In this version of Telerik NativeScript you can create only ios and android projects.
You can create Android projects on windows and Mac machine. You can create ios projects only on Mac machine.

**Comment by leebailey88** [comment]
I'm getting this error today when following the getting started guide after `tns platform add ios`

**Comment by ifyio** [comment]
I'm also getting this error today.

**Comment by teobugslayer** [comment]
Hello @leebailey88,

Please give us more details about your configuration - what are the versions of NativeScript, Xcode, Mac OS you are using?

It would be very helpful to us, if you try the following command:

```bash
$ tns platform add --log trace > log.txt
```

and send us the contents of log.txt. Note, it may contain sensitive information, so check it before posting it publicly or open a support ticket with Telerik support mentioning this issue.
