### ISSUE TITLE
Add swift files to Xcode project 

### ISSUE THREAD

**Issue by tdermendjiev** [NativeScript/nativescript-cli#4503]
**Is your feature request related to a problem? Please describe.**
Users should be able to add swift files to App_Resources as well as Objective-C files. The CLI will add them to compile sources the same way.

**Describe the solution you'd like**
The CLI should add *.swift* files to the .xcodeproj. Also the proper settings should be set in the project so they are compiled and the symbols are accessible.

**Comment by hettiger** [comment]
This is a must have. We can expose public functions using @objc in plugins already. I think this should be possible. It’s a burden having to translate platform specific solutions to TypeScript if it brings no value to the table.

**Comment by AhmedAzzabi** [comment]
+1 for this. Swift is used more and more than obj-c.

**Comment by tirsomartinezreyes** [comment]
+1  Most new code comes in swift flavor

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/ios-runtime #1131](https://github.com/NativeScript/ios-runtime/issues/1131) via [**ZenHub**](https://www.zenhub.com/)
