### ISSUE TITLE
Tagged versions of android runtime are not supported

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-cli#4504]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.0
 - Cross-platform modules: 5.3.0
 - Android Runtime:5.3.0
 - iOS Runtime:5.3.0
 - Plugin(s):

**Describe the bug**
The version of `tns-android` can not be a custom tag. Currently there is a version tagged `androidx`, but if I use that version in an application's `package.json`, I get a `Invalid Version: androidx` error.

**To Reproduce**
For any NS Application use:
```
  "nativescript": {
    "id": "org.nativescript.demoangular",
    "tns-android": {
      "version": "androidx"
    },
    "tns-ios": {
      "version": "5.3.0"
    }
  },
```

**Expected behavior**
The version currently tagged with `androidx` to be used.

**Sample project**

**Additional context**

**Comment by Fatme** [comment]
As we reverted the old fix and fixed the issue using another approach, I'll reopen this issue.
