### ISSUE TITLE
App does not restart after crash on simulator with `tns run ios` and hangs on the crashed screen

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-cli#4506]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.0
 - Cross-platform modules: 5.3.1
 - iOS Runtime: 5.3.1

**Describe the bug**
After starting a normal session with `tns run ios` with an iOS simulator, if the app crashes (possible in a native code not JS, not sure if this is important) it is stuck on the screen where it crashed (app does not close due to the crash). After that if you cause a new livesync of the app it cannot be refreshed for around 1 min. Stopping the `tns run ios` with Ctrl + C causes the next start of this process to hang on the splash screen of the app.

**To Reproduce**
Using [this](https://github.com/telerik/nativescript-ui-samples/tree/master/listview) project make the app crash by calling a method that does not exist on the RadListView `nativeviewProtected`.

**Expected behavior**
The app is restarted after it has crashed after you cause a livesync.

**Sample project**
[This](https://github.com/telerik/nativescript-ui-samples/tree/master/listview) project

**Comment by modermo** [comment]
I'm experiencing frequent crashes with no auto-recovery, the simulator just freezes which means you have to kill the process and start again with `tns run ios`

**Comment by DimitarTachev** [comment]
The issue is not reproducible in NativeScript 6.1 with both Xcode 10 and 11. We've tried the above-mentioned steps on iOS 9 and 12 simulators and it's working as expected. If you reproduce this freeze again, please open a new issue and describe the exact steps to reproduce and the versions of your NativeScript CLI, iOS Runtime, Xcode and Simulator.
