### ISSUE TITLE
Build should report malformed XML

### ISSUE THREAD

**Issue by bundyo** [NativeScript/nativescript-cli#452]
XML errors are easy to miss and without an easy way to spot the error can be a big problem (losing development time). A preprocessing XML parser during/before the build step can be a big help here.

**Comment by RangerMauve** [comment]
Knowing which XML files are going to be used as views is probably non-trivial. Have you considered running your code through something like [xmllint](http://linux.die.net/man/1/xmllint) yourself?

**Comment by bundyo** [comment]
Linting will help, but not all users will have this in mind when starting app building with NativeScript.

**Comment by RangerMauve** [comment]
I guess it'd be useful if someone added information on using linters in the docs somewhere?

**Comment by bundyo** [comment]
It will, but it should be somewhere very visible.

**Comment by vchimev** [comment]
Implemented here: https://github.com/NativeScript/nativescript-cli/issues/1272.
