### ISSUE TITLE
TNS 5.x CLI doesn't support TNS 2 running

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#4530]
**Environment**
 - CLI: 5.3.1
 - Cross-platform modules: 2.5.1
 - Android Runtime: 3.01
 - Plugin(s): (lots)

**Describe the bug**
Doing a `tns run android` actually does start the emulator, builds the apk; but never installs the apk nor does the watching/syncing work.  
It displays:
```
  - Starting compilation in watch mode...
  - Found 0 errors. Watching for file changes.
```
So at this point the only way to update the APK with new code; is to manually kill the platforms/android folder; rebuild and then manually install it.

**To Reproduce**
1. Create a TNS 2.x app.
2. Run it with a modern CLI.

**Expected behavior**
Everything continues to work

**Additional context**
This might be something that could be considered a corner case; not sure how many people have to rebuild any older apps; so this might be a bug left just so people can find it.

**Comment by Fatme** [comment]
@NathanaelA,

Thank you for reporting this issue!

We've deleted the support for android runtime version lower than `3.4.0` by mistake in our `rc`. The commit is reverted, so with the latest `rc` version of the CLI it should work as expected.

As of NativeScript 6.0.0 release, we'll drop officially the support for android runtime version lower than `4.2.0`. It seems like the perfect time to migrate to newer android runtime version 😄.

**Comment by Fatme** [comment]
Rel to: https://github.com/NativeScript/nativescript-cli/pull/4531

**Comment by NathanaelA** [comment]
Just a FYI; I tried `5.3.2-2019-04-12-13150` and it still did the exact same thing.    I'll try the RC tomorrow to see if it shows up and maybe missed the window today...
