### ISSUE TITLE
https://nativescript.org/setup/win-avd RETURN 404

### ISSUE THREAD

**Issue by averied** [NativeScript/nativescript-cli#4535]
When trying to follow guide at https://docs.nativescript.org/start/ns-setup-win

step 7.a is returnig 404 error. 

`@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://nativescript.org/setup/win-avd'))"`

The link seems to not be avilable any more. Any alternative URL so we can avoid installing android studio just for the emulator?

**Comment by NickIliev** [comment]
@averied thanks for bringing this to our attention. We will update the documentation with the proper step.

Meanwhile, use this article [as a reference](https://docs.nativescript.org/tooling/android-virtual-devices#creating-android-virtual-device-via-command-line-tool)

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/docs/pull/1625](https://github.com/NativeScript/docs/pull/1625)

@averied note that you will still need the Android studio is you want to use the Android Studio's simulators.
