### ISSUE TITLE
Research and implement embedding Apple Watch App inside NativeScript App.

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#4541]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to include an Apple Watch App in your NativeScript application.

**Describe the solution you'd like**
I'd like to add the watch app and watch app extension code inside `App_Resources/iOS` and the tooling to integrate them build time inside the iOS app.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
None.

Workflow:
1. Create Single Page App from Xcode.
2. Add watch app target - File>New>Target>WatchKit App
3. Add a name to your watch app, for example `MyFirstWatchApp`
4. Copy the generated "MyFirstWatchApp" and `MyFirstWatchApp Extension` to `.../apps/MyApp/app/App_Resources/iOS/watchapp/MyFirstWatchApp` and `.../apps/MyApp/app/App_Resources/iOS/watchextension/MyFirstWatchApp Extension` respectively.
5. Inside the `Info.plist` of the Watch App and Watch Extension replace the value of `WKCompanionAppBundleIdentifier` with `$(WK_APP_BUNDLE_IDENTIFIER)`.
6. You can populate the `Assets.xcassets` of the Watch App and the Watch Extension and add the name of the `appiconset` to the `.../apps/MyApp/app/App_Resources/iOS/watchapp/MyFirstWatchApp/watchapp.json` and `.../apps/MyApp/app/App_Resources/iOS/watchextension/MyFirstWatchApp Extension/extension.json` respectively:
```json
{
    "assetcatalogCompilerAppiconName": "AppIcon"
}
```
7. You can modify the `WATCHOS_DEPLOYMENT_TARGET` of the Watch App by adding the value inside the `watchapp.json` like this:
```json
{
    "assetcatalogCompilerAppiconName": "AppIcon",
    "targetBuildConfigurationProperties": {
        "WATCHOS_DEPLOYMENT_TARGET": 4.1
    }
}
```
8. Run the NativeScript application

**Comment by endarova** [comment]
known limitation is that Swift projects are not supported in the current version

**Comment by MickL** [comment]
This issue is 4 years old, is Swift now supported?
