### ISSUE TITLE
tns build ios freezes at xcodebuild in xcode 10.2

### ISSUE THREAD

**Issue by dhoffens** [NativeScript/nativescript-cli#4543]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.2
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.4.0-xxx 
 - iOS Runtime: 5.3.1
 - Plugin(s):
Plugin                            │ Version │
│ @angular/animations               │ ~7.2.0  │
│ @angular/common                   │ ~7.2.0  │
│ @angular/compiler                 │ ~7.2.0  │
│ @angular/core                     │ ~7.2.0  │
│ @angular/forms                    │ ~7.2.0  │
│ @angular/http                     │ ~7.2.0  │
│ @angular/platform-browser         │ ~7.2.0  │
│ @angular/platform-browser-dynamic │ ~7.2.0  │
│ @angular/router                   │ ~7.2.0  │
│ nativescript-angular              │ ^7.2.3  │
│ nativescript-checkbox             │ ^3.0.3  │
│ nativescript-gradient             │ ^2.0.1  │
│ nativescript-ngx-fonticon         │ ^4.2.0  │
│ nativescript-svg                  │ ^1.3.7  │
│ nativescript-theme-core           │ ^1.0.4  │
│ nativescript-ui-chart             │ ^4.0.0  │
│ nativescript-ui-dataform          │ ^4.0.0  │
│ nativescript-ui-listview          │ ^6.1.0  │
│ nativescript-ui-sidedrawer        │ ^6.0.0  │
│ reflect-metadata                  │ ~0.1.8  │
│ rxjs                              │ ^6.3.3  │
│ tns-core-modules                  │ ^5.3.1  │
│ typescript                        │ ~3.1.1  │
│ zone.js                           │ ^0.8.4  │

Dev Dependencies:
│ Plugin                       │ Version                           │
│ @angular/cli                 │ ^7.1.1                            │
│ @angular/compiler-cli        │ ~7.2.0                            │
│ @fortawesome/fontawesome-pro │ ^5.7.2                            │
│ @nativescript/schematics     │ ~0.4.0                            │
│ @ngtools/webpack             │ ~7.2.0                            │
│ nativescript-dev-sass        │ ^1.7.0                            │
│ nativescript-dev-typescript  │ ^0.9.0                            │
│ nativescript-dev-webpack     │ ^0.22.0-next-2019-04-12-181144-02

**Describe the bug**
On tns build, after successfully installing all pods, the build freezes and spits out:

Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/me/Desktop/camob/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/me/Desktop/camob/platforms/ios/Pods/Target Support Files/Pods-camob/Pods-camob.debug.xcconfig')).save_as(Pathname.new('/Users/me/Desktop/camob/platforms/ios/plugins-debug.xcconfig'))"
 stdout:
 stderr:
Project successfully prepared (ios)
Project dir from hooksArgs is: /Users/me/Desktop/camob.
Hooks directories: [ '/Users/me/Desktop/camob/hooks' ]
AfterHookName for command prepare is after-prepare
Building project...
spawn: xcodebuild "SHARED_PRECOMPS_DIR=/Users/me/Desktop/camob/platforms/ios/build/sharedpch" "build" "-configuration" "Debug" "-sdk" "iphonesimulator" "ONLY_ACTIVE_ARCH=NO" "BUILD_DIR=/Users/me/Desktop/camob/platforms/ios/build" "CODE_SIGN_IDENTITY=" "-workspace" "/Users/me/Desktop/camob/platforms/ios/camob.xcworkspace" "-scheme" "camob" "-allowProvisioningUpdates"
Build settings from command line:
    BUILD_DIR = /Users/me/Desktop/camob/platforms/ios/build
    CODE_SIGN_IDENTITY =
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator12.2
    SHARED_PRECOMPS_DIR = /Users/me/Desktop/camob/platforms/ios/build/sharedpch

**To Reproduce**

tns build ios --clean 

**Expected behavior**
Expect it to build me everything in platforms/ios so I can then continue in Xcode and archive.

**Additional context**
I see that the CODE_SIGN_IDENTITY is blank there in 'build settings from command line', but in my build.xcconfig, I do have my CODE_SIGN_IDENTITY set to the right one.

I have tried rm -rf-ing and tns run/debug/prepare, I've also reinstalled xcode cli stuff just in case, and tried manually passing the --provision just in case ... but still no luck

Thanks for your help.

**Comment by badulescub** [comment]
what is the solution ?

**Comment by vforv** [comment]
Any solution?

**Comment by ninahorne** [comment]
I am having this issue.
