### ISSUE TITLE
 Command git failed with exit code 1

### ISSUE THREAD

**Issue by sandoche** [NativeScript/nativescript-cli#4552]
- CLI: 5.3.2

When I build with Sidekick for iOS, release, I get this error after a few minutes in both Windows and Linux
```
[19-04-21 16:37:05.227] Prepare step completed.
[19-04-21 16:37:06.715] Upload step started.
[19-04-21 16:37:07.470] (CLI) Unable to use git, reason is:
[19-04-21 16:37:07.470] (CLI) Command /usr/bin/git failed with exit code 1
```

**Comment by rosen-vladimirov** [comment]
Hey @sandoche , is this an error or just a message ? Does your build continue after this message?
In case not, can you please send us the log files from Sidekick.
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

**Comment by sandoche** [comment]
It shows the error and the build doesn't stop but nothing is displayed in the console it looks stuck.
After doing `tns platform remove ios` it worked but when I delete the folder manually it doesn't.
