### ISSUE TITLE
XCode project: framework not found CocoaLumberjack

### ISSUE THREAD

**Issue by SephReed** [NativeScript/nativescript-cli#4560]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 5.3.1 and the latest available version is 5.3.2.
✔ Component tns-core-modules has 5.4.0-next-2019-04-03-175957-02 version and is up to date.
✔ Component tns-android has 5.4.0-2019-04-03-095324-01 version and is up to date.
✔ Component tns-ios has 5.4.0-2019-04-03-180044-02 version and is up to date.

**Describe the bug**

For [whatever reason](https://github.com/NativeScript/nativescript-cli/issues/3568), I'm unable to build an ipa using command line.  I am attempting to build the ipa using the xcode project, but the project file appears to be broken.

```
ld: warning: directory not found for option '-F/Users/seph/Library/Developer/Xcode/DerivedData/ChooseHealth-anmnaswytduzyghejefmipsqfpdo/Build/Intermediates.noindex/ArchiveIntermediates/ChooseHealth/BuildProductsPath/Release-iphoneos/CocoaLumberjack'
ld: warning: directory not found for option '-F/Users/seph/Library/Developer/Xcode/DerivedData/ChooseHealth-anmnaswytduzyghejefmipsqfpdo/Build/Intermediates.noindex/ArchiveIntermediates/ChooseHealth/BuildProductsPath/Release-iphoneos/HockeySDK-Source'
ld: warning: directory not found for option '-F/Users/seph/Library/Developer/Xcode/DerivedData/ChooseHealth-anmnaswytduzyghejefmipsqfpdo/Build/Intermediates.noindex/ArchiveIntermediates/ChooseHealth/BuildProductsPath/Release-iphoneos/SVGKit'
ld: framework not found CocoaLumberjack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**

Open the xcode project, set target to Generic iOS Device, run Product -> Build

**Expected behavior**
The project should build

**Sample project**

Default sample project

**Additional context**

The extra tns modules I have are 
```
    "nativescript-cardview": "^3.1.1",
    "nativescript-dom": "2.0.2",
    "nativescript-hockey-sdk": "1.2.0",
    "nativescript-plugin-firebase": "^8.2.0",
```

If CocoaLumberjack is not a dependency of nativescript core, perhaps it is one of the above.

**Comment by SephReed** [comment]
Found it.  You have to open the xcode workspace, not the project.

**Comment by PetroSuch** [comment]
i run command tns run ios and get same error, how can i solve the error ?
my app worked well before, and now i have this error,
i tried to upgrade macos, nativescript and xcode, but it is not help me, and error still here

**Comment by madmas** [comment]
@PetroSuch What are the exact version you are currently using? I had the same after XCode 12 was installed but the project was still on TNS 6. Downgrading to XCode 11.7 worked, but I got confirmed that building the APp with NS 7.0 CLI while the app itself would still remaint 6.5 is also possible.

**Comment by ray007** [comment]
I'm now on NS7 with latest XCode on latest MacOS and also have this error.
Could somebody please explain to me how to get the build working again?

**Comment by PetroSuch** [comment]
i removed plugin lnativescript-ocalization, and it is helped me

**Comment by ray007** [comment]
Ah, so the fix is not to make building `CocoaLumberjack` work but to remove the plugin which uses it?
Unfortunate.

**Comment by PetroSuch** [comment]
i dont know how, but my friend successfully built the same project on his  computer,
try to uninstall platforms folder, and rebuild it

**Comment by email-nkishor** [comment]
![Screenshot 2023-02-15 at 4 44 54 PM](https://user-images.githubusercontent.com/22617369/219013979-f46f79d7-c13f-4ad8-9984-2b02475887c9.png)
I am getting error like 'ld: framework not found IQKeyboardManager' when archive or build.
