### ISSUE TITLE
tns test android launches the app instead of running the tests

### ISSUE THREAD

**Issue by yringler** [NativeScript/nativescript-cli#4571]
**Environment**
Using angular.

 - CLI: 5.3.4
 - Cross-platform modules (tns-core-modules):  5.3.1
 - Android Runtime: 5.3.1
 - Plugin(s): nativescript-audio, nativescript-download-progress

**Describe the bug**
Unit tests aren't run.
Using angular.
tns test android --bundle runs the app. It does not run unit tests.

**To Reproduce**
git clone https://github.com/yringler/rabbi-gordon-audio
git checkout 15-unit-test
tns test android --bundle

**Expected behavior**
Unit tests are run

**Sample project**
https://github.com/yringler/rabbi-gordon-audio/tree/15-unit-test

**Comment by Fatme** [comment]
@yringler,

You need to update your [nativescript-dev-webpack plugin](https://github.com/yringler/rabbi-gordon-audio/blob/master/package.json#L43) and [webpack.config.js file](https://github.com/yringler/rabbi-gordon-audio/blob/master/webpack.config.js).
```
rm -rf webpack.config.js
npm i nativescript-dev-webpack@latest --save-dev
```
After that you can initialize the tests and run them.

```
tns test init
tns test android --bundle
```

**Comment by yringler** [comment]
Thank you.
That gets me up to #3146.
Closing this, as that issue is already there.

**Comment by Fatme** [comment]
@yringler,

The workaround for https://github.com/NativeScript/nativescript-cli/issues/3146 is `rm -rf platforms` before `tns test` command.

**Comment by yringler** [comment]
No luck.
I had already tried git clean -xdf.
Tried rm -rf platforms then test, but same error: first "disconnected", then "no reachable hosts"

**Comment by Fatme** [comment]
@yringler,

Can you please ensure that you passed `--bundle` option to the command?

If this is not the case, you need to ensure that the device and your computer are in the same network. This is a requirement in order to run tests on a connected device.

**Comment by yringler** [comment]
They were indeed on a different network; PC on wifi, and phone on data.
I'll take a look.

**Comment by yringler** [comment]
Although as per #4574, it seems that the new webpack (which is needed for unit tests) breaks uglify, so I don't know if I'd want it on my main branch yet.
However, I'll try again (using the same network) on my unit test branch when I have a chance, and I'll keep you posted.
Ty.

**Comment by Nileshdcool** [comment]
I am also facing some issues while running the test cases. They get executed and suddenly mobile application on which test results are being displayed gets shut down. 
Error What I get is disconnectedClient disconnected from CONNECTED state (transport error)

I neither able to see my test cases on mobile neither on browser.
