### ISSUE TITLE
nodeJS processes not killed after 'tns create' on Mac OS with latest "next"

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-cli#4593]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0-2019-05-08-13226
- Mac OS version: 10.14.4 (18E226)

**Describe the bug**
When creating a project using `tns create testapp --js`, after the creation is finished if you open Activity Monitor and search for "node" you can find at least 2 processes left.

**To Reproduce**

- Install the `5.4.0-2019-05-08-13226` version of the CLI `npm i nativescript@5.4.0-2019-05-08-13226`
- Open Activity Monitor
- Do `tns create my-app --js`
- Search for "node" in the Activity Monitor

**Expected behavior**
After creation of the project there are no nodeJS processes left alive.

**Comment by rosen-vladimirov** [comment]
Another way to check if there are leaked processes is by using the following command (after CLI has died):
```
ps -ef | grep nativescript | grep -v grep
```
