### ISSUE TITLE
"Missing required icon file..." when trying to publish an iOS app to App Store

### ISSUE THREAD

**Issue by tbozhikov** [NativeScript/nativescript-cli#4595]
**Environment**
 - CLI: 5.3.4

**Describe the bug**
Hi guys, recently I have been struggling publishing an iOS app for TestFlight. The reason why the store rejects is:
>Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format for iOS versions supporting iPad Pro.

... and some similar icon/assets related complaints. In the same time all these icons are there in the project and when testing the app everything is fine with them.

Fortunately, yesterday I managed to resolve this with the help of [this thread](https://stackoverflow.com/a/46233725). The steps to success were:
1. tns build ios --release
2. Open the workspace in Xcode
3. In the project properties’ General tab, click `Use Asset Catalog...` and choose the Asset catalog already existing in the project.

**Expected behavior**
So without step 3, the publish fails with complaints related to icons. I was wondering, can this step be done with the generation of the project? This could spare a lot of time of devs trying to publish apps to store since the error messages are somewhat useless.

**Comment by KristianDD** [comment]
After investigation we discovered that a line was missing from `app/App_Resources/iOS/build.xcconfig`. The line is `ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;`. This line is present in all templates and the CLI should't handle this additionally.

Closing this issue.

**Comment by FatimahSanni** [comment]
Thanks @KristianDD, you are a life saver!
