### ISSUE TITLE
"tns build ios" fails with spaces in the path

### ISSUE THREAD

**Issue by dbbk** [NativeScript/nativescript-cli#461]
Apps cannot be built from the CLI if any directory in the path has a space. Build process gets stuck at:

`Generating metadata for i386:
./metadata-generation-build-step.sh: line 4: $BUILT_PRODUCTS_DIR/metadata-generation-stderr-$1.txt: ambiguous redirect`

Removing any spaces from your directories fixes the issue.

**Comment by jasssonpet** [comment]
Thank you for reporting this. We have logged the issue in the iOS runtime repo: https://github.com/NativeScript/ios-runtime/issues/106

**Comment by teobugslayer** [comment]
This is related to https://github.com/NativeScript/nativescript-cli/issues/459

**Comment by Fatme** [comment]
The fix has already been released. You can update NativeScript CLI to version 1.0.1
