### ISSUE TITLE
Provide an easy way to disable logcat printing

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#463]
In case you run `$ tns run android` we print the logcat in the terminal and it is not released. You can turn it off for this command by executing `$ tns run android --juslaunch`. We should provide an easy way to set this as default behavior, so in case you do not need the logcat output, you will not have to write `--justlaunch` every single time.

**Comment by Fatme** [comment]
We can use config file.

**Comment by enchev** [comment]
Closed due to low community interest.
