### ISSUE TITLE
Could not get unknown property 'VersionNumber' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4630]
@SuperAssassinNinja commented on [Fri May 17 2019](https://github.com/NativeScript/NativeScript/issues/7257)

After updating my nativescript to 5.4.0 and trying to run android with webpack this is happening

app.gradle
```
android {
  compileSdkVersion 28
  buildToolsVersion '28.0.3'

  defaultConfig {
    generatedDensities = []
    applicationId = "APP-KEY"
    versionCode 1
    versionName "1.0"
    VersionNumber 2

    ndk {
        abiFilters.clear()
        abiFilters "armeabi-v7a"
 	}

  }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }

    project.ext {
       googlePlayServicesVersion = "15.8.0"
    }
}

project.ext {
       firebaseMessagingVersion = "15.0.1" // OR the version you wish
}

def settingsGradlePath = "$rootDir/../../app/App_Resources/Android/settings.gradle";
def settingsGradleFile = new File(settingsGradlePath);

if(settingsGradleFile.exists())
{
    apply from: settingsGradleFile;
}
```

```
Time: 10577ms
         + setting applicationId

FAILURE: Build failed with an exception.

* Where:
Script '/Users/alexandre.melo/projetos/connect/node_modules/nativescript-plugin-firebase/platforms/android/include.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'VersionNumber' for project ':app' of type org.gradle.api.Project.

```

**Comment by NickIliev** [comment]
@SuperAssassinNinjawhat is the version of your `nativescript-plugin-firebase`?
Try updating the plugin to the latest version and making a clean rebuild for the project - that resolved the issue on my side

**Comment by SuperAssassinNinja** [comment]
@NickIliev just updated to 8.3.2 seems like this error is gone,But the application does not with NS 6.0
Trying to make changes to see what happens

**Comment by konradkluzniak** [comment]
HI,
Can you confirm that it's nativescript.firebase issue ?
I cannot do build for android beacuse of this. I have Nativescript 5.3 and firebase ver 7.7. Thanks.

**Comment by konradkluzniak** [comment]
Hi Guys,
This situation is not ideal. Do you have any updates on this ?

**Comment by NickIliev** [comment]
@konradkluzniak you need t use a newer version of `nativescript-plugin-firebase`, delete the hooks before installing the newer version.

Overall I would recommend migrating to NativeScript 6 and using the latest version of the Firebase plugin.

**Comment by konradkluzniak** [comment]
Thanks, but my problem is - i have lots of community plugins like for example toast etc... If i will update project another plugins may not work (toast will not def work).App is huge and i can't imagine how to do tests again...I will resolve one issue and will face 10 another... But thanks for answer.
