### ISSUE TITLE
App crashes after deploy on ios device

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4637]
- CLI: 5.4

Steps:
First scenario:
1. tns create NewApp --js
2. tns deploy ios (deploy on device, not simulator)
Expected: app is deployed and can be started
Actual: app crashes when you try to start in. Log: 
[log_deploy.txt](https://github.com/NativeScript/nativescript-cli/files/3207616/log_deploy.txt)

Second scenario:
1. tns create NewApp --js
2. tns prepare ios 
3. run the project from xcode
Expected: app is deployed and can be started
Actual: app crashes when you try to start in. Log: 
[log_run_xcode.txt](https://github.com/NativeScript/nativescript-cli/files/3207623/log_run_xcode.txt)

**Comment by SuperAssassinNinja** [comment]
same
