### ISSUE TITLE
IOS simulator launched but hello-world app not in it

### ISSUE THREAD

**Issue by ifyio** [NativeScript/nativescript-cli#464]
`tns run ios --emulator` launches the hello-world app but the hello-world app is not launched within it, and there is no `hello-world` app in the simulator itself.

**Comment by teobugslayer** [comment]
Hello @ifyio,

We have just released version 1.0.1 of {N} CLI. Please update to it and give it a try. If the issue persists, please gather and give us more details. Run
```
tns run ios --emulator --log --trace > log.txt
```
and send us the generated log.txt. Please check and anonymize all security-conscious data in it (like your user name, paths, etc), or better - open a Telerik [support ticket](http://www.telerik.com/account/support-tickets.aspx) mentioning this issue.
