### ISSUE TITLE
[Tracking] Build NativeScript applications using only webpack workflow

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#4640]
## Overview

Webpack is a static module bundler tool and as such is usually the most important part when building the application.

At the moment NativeScript CLI uses two different ways to build the applications
* Using default LiveSync workflow (the legacy workflow)
* Using webpack workflow

The legacy and webpack workflows specify very different behaviors for their implementations. Here is a table of the differences:

|   |      Legacy workflow      |      Webpack workflow      |
|----------|:-------------:|:------:|
| Transferring files on device |  All application's files are transferred on device regardless if they are used at runtime | Only the modules that are used runtime are transferred on device as webpack traverses the source code and collects only them. |
| Restarting application on device | The application is restarted from scratch when a JavaScript or TypeScript file is changed | Is has the ability to exchanges, adds or removes modules while an application is running without having to do a restart on device. |
| Preserving application's state on device | As the application is restarted from scratch, its state is not preserved. | As the application is not restarted from scratch, its state is preserved. |

More info can be found [here](https://www.nativescript.org/blog/the-future-of-building-nativescript-apps).

## Discussion
Please, don't report problems here. Instead, open a new issue and link it to this one.
Let's use this discussion for suggestions and improvement ideas. We would love to hear from you!

**Comment by vakrilov** [comment]
This issue has moved here: https://github.com/NativeScript/NativeScript/issues/7320
