### ISSUE TITLE
Introduce command (`tns migrate`) to migrate old project to 6.0.0 requirements

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#4646]
**Is your feature request related to a problem? Please describe.**
In 6.0.0 release, we'll have new requirements for applications build process, i.e. all apps must have webpack as dependencies, several development plugins should be replaced with others, etc.
All of these changes could take a lot of time to the users and several issues might occur during the process. So it will be great in case `tns update` command can handle all these changes.

**Describe the solution you'd like**
The `tns update` command should update the following components of the application:
* runtime versions
* `tns-core-modules` and `tns-core-modules-widgets` versions
* `nativescript-dev-webpack` version
* `webpack.config.js` file according to latest changes - create a backup of the old one
* `hooks` directory - create backup of it and allow `npm` to recreate it on its own
* remove all dev plugins that will not be supported anymore and add required development dependencies instead of them:
  * `nativescript-dev-sass` should be replaced with `node-sass`
  * `nativescript-dev-typescript` should be replaced with `typescript` (possibly `typescript` is already a devDependency of the project)
  * `nativescript-dev-less` should be replaced with `less`
* it will be great if the command can update all dependencies to their latest versions - due to changes around AndroidX most of the plugins will need a new version to be published. Their old versions will not work with Android runtime that supports only AndroidX.

After updating the package.json and backing up the directories, CLI should execute `npm rebuild`, so all new dependencies and devDependencies will be installed and all required hooks will be generated in the project.

Also it will be great to check the project files and notify the users if there are `.xml`/`.css` files that do not follow the convention requirements of our webpack logic (i.e. they do not have `page` or `root` in the name) and show warnings for them.

**Describe alternatives you've considered**
CLI might show interactive prompts which of the mentioned components to be updated.

**Comment by SuperAssassinNinja** [comment]
Also add the -page suffix to the files that need it.

**Comment by endarova** [comment]
Acceptance criteria `tns update`:
- [ ]  `tns update` should take versions of dependencies  from  the latest compatible hello world template based on your app flavor and your cli version
 - [ ]  `tns update {version}/{tag}` should take versions of dependencies  from  the latest compatible hello world template based on your app flavor and the specified cli version or tag
 - [ ]  `tns update {version}/{tag}` should exit with error when invalid tag or version are specified 
- [ ]  `tns update` should only update dependencies (not add or remove any)
- [ ] `tns update` should exit with info for migrate command when your app in not 6.0 compatible
     - [ ] when dependencies do not match  https://github.com/NativeScript/nativescript-cli/blob/3cabd7e66efe583722301a6f3b0bd7386a0af0b0/lib/controllers/migrate-controller.ts#L39

Acceptance criteria `tns migrate`:
- [ ] All templates created with `nativescript@5.4` should be able to run, preview, test and debug after `tns migrate`
- [ ]  `tns migrate` should  exit with info about `tns update` if the project is already compatible with 6.0
- [ ]  `tns migrate` and  `tns update` should  exit with already updated/migrated info for newly created apps
- [ ]  `tns migrate` should remove all  *.js,  *.js.map,  *.css  files in app folder  when they have the corresponding *.ts, *sccs, *.sass, *.less files
- [ ]  `tns migrate` should backup all files affected by migration in `{projectDir}/.migration_backup` folder
- [ ]  `tns migrate` should migrate project dependencies only if versions are lower than:  https://github.com/NativeScript/nativescript-cli/blob/3cabd7e66efe583722301a6f3b0bd7386a0af0b0/lib/controllers/migrate-controller.ts#L39
