### ISSUE TITLE
CLI's checkForChanges method should not check all `node_modules`

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#4647]
**Is your feature request related to a problem? Please describe.**
CLI's watcher for `node_modules` should watch only the plugin's native files. With changes for 6.0.0 release, webpack will automatically watch all required files, even when they are from `node_modules`. When a change in some of the native files is applied, CLI's watcher will be triggered. In this case, the logic of CLI will be triggered to check if the `node_modules` are modified. It will list all files in `node_modules` just to determine if there's a change in any of them. Instead of listing all `node_modules`, CLI should check only the nativescript plugins and their `platforms/<platform>` directories.

**Describe the solution you'd like**
Change this code to list only `<project dir>/node_modules/<nativescript plugin name>/platforms/<current platform>` directories.
https://github.com/NativeScript/nativescript-cli/blob/a4cb42ccc8a2f33dcc4fd893f65ffcba7255e6af/lib/services/project-changes-service.ts#L77-L81

**Describe alternatives you've considered**
Refactor the whole checkForChanges logic, but this requires more time.

**Additional context**

**Comment by adrian-niculescu** [comment]
This is only desirable during the development of 1 plugin and would cripple other development flows.
The current behaviour should be kept (and be configurable maybe) to allow:
- debugging of any node_modules file://... dependency.
- debugging of a plugin that is used inside of another plugin (recently  needed this with a a permissions management plugin used inside another one).
