### ISSUE TITLE
Please add support for pkg manager `pnpm`

### ISSUE THREAD

**Issue by paxperscientiam** [NativeScript/nativescript-cli#4654]
**Describe the solution you'd like**
Please add support for [pnpm](https://pnpm.js.org/)

> pnpm uses hard links and symlinks to save one version of a module only ever once on a disk. When using npm or Yarn for example, if you have 100 projects using the same version of lodash, you will have 100 copies of lodash on disk. With pnpm, lodash will be saved in a single place on the disk and a hard link will put it into the node_modules where it should be installed.

**Comment by farfromrefug** [comment]
@rosen-vladimirov did you make any progress on this? I use pnpm for all my N apps but I am facing issues when using some tns commands whic force the use of npm. Could we simply have a option or something to set the actual "npm" command to be run for install. For me for example it would be "pnpm i - - shamefully-hoist"

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
We've not worked on this feature request. One way to implement it is to add a new package manager support in NativeScript CLI, similar to the way yarn is supported. To achieve this you'll have to provide an implementation similar to these ones:
- [npm](https://github.com/NativeScript/nativescript-cli/blob/master/lib/node-package-manager.ts)
- [yarn](https://github.com/NativeScript/nativescript-cli/blob/master/lib/yarn-package-manager.ts)

And after that you can add the package manager in the selection used by CLI [here](https://github.com/NativeScript/nativescript-cli/blob/7c692eeff3c5743a4831db1c91a931b9ae9ba007/lib/package-manager.ts#L91-L104)
And in the [set command](https://github.com/NativeScript/nativescript-cli/blob/master/lib/common/commands/package-manager-set.ts) for selection of package manager:

**Comment by dtopuzov** [comment]
Available in `nativescript@next`, will be officially shipped with `nativescript@6.4.0`.
