### ISSUE TITLE
New Web bundle update file location when debugging

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/nativescript-cli#4695]
I have just upgraded to Nativescript 5.4.0 and been told about the web bundle options and how V6 will force this option on us. Given I already had a project and upgraded to 5.4.0 thought I would see how it goes.

Why is it necessary to move the files to the web pack folder.  This is confusing as code editing the files are in the App folder, but not when debugging.

**Comment by rosen-vladimirov** [comment]
Hey @mrwrighty ,
Sorry for the late reply. If I understand you correctly, you are confused by the files shown in Chrome DevTools when debugging, am I right?

Meanwhile, I'll try why you see `webpack` node in Chrome DevTools. When we bundle the application the original files that you have in your application and combined in just a few output files. These new files are uploaded on device and these are the ones reported to Chrome DevTools. However, to make debugging easier, we have added sourceMaps in these files. This allows Chrome DevTools to generate the original files from the bundled ones, so you can debug them. That's what you see in `webpack` node in the DevTools. We cannot place the files in the `files` node as these are generated files, they do not exist on the device, they are generated from source maps. 

Hope this helps.

**Comment by mrwrighty** [comment]
OK thanks for the reply. Obviously from previous apps developed under nativescript, when debugging all files are located in the the same place but with webpack they are not there, so found it somewhat confusing over previous methods to debug.

**Comment by rosen-vladimirov** [comment]
I'm glad the answered helped understanding the current behavior. I'm closing this thread, but feel free to reopen it in case you still have concerns.
