### ISSUE TITLE
tns create hello-world fail

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/nativescript-cli#473]
Hello,

Using your install process i tried to install NS.

When i execute "tns create hello-world", i got this error :
"EACCES, open '/home/XXX/.local/share/.nativescript-cli/.lock'"

For your information, I've just resolved it by using "sudo chown -R vagrant /home/XXX/.local/share/.nativescript-cli/"

**Comment by Fatme** [comment]
Hi @guillaume-roy,

It seems that your user doesn't have access to `/home/XXX/.local/share/.nativescript-cli/` directory. I suggest you to use `sudo npm install nativescript -g --unsafe-perm` command  when installing NativeScript CLI.

**Comment by guillaume-roy** [comment]
Thanks
