### ISSUE TITLE
tns create crash after installing visual studio 

### ISSUE THREAD

**Issue by Fabiyo-90** [NativeScript/nativescript-cli#4762]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.2
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

Every using "tns create" , I can't create a nativescript app after installing android studio 2017, even if I use NativescriptSideKick.

If I use tns create app, I have as bug 

gyp info spawn args   '-Dmodule_root_dir=D:\\project\\mobile\\kiosque\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\project\\mobile\\kiosque\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "D:\project\mobile\kiosque\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\project\mobile\kiosque\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\mobile\\kiosque\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\project\mobile\kiosque\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ts-loader@5.4.5 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fabrice IYONGO\AppData\Roaming\npm-cache\_logs\2019-06-24T15_57_30_092Z-debug.log
Command npm.cmd failed with exit code 1
# tns create

**Comment by Fabiyo-90** [comment]
I did uninstall node, delete npm folder and npm-cache folder. After I installed node, reinstall nativescript but I have the same bug, I can't  create a new project.
I use : 
* windows 10
* node-v10.16.0
* tns @5.2.4
* npm 6.9.0

**Comment by rosen-vladimirov** [comment]
Hey @Fabiyo-90 ,
It looks like you have troubles installing `node-sass` dependency which is included in some of our templates. `node-sass` has some native (C++) code that is built in a binary file and should be downloaded during postinstall of the package. In case the download fails or there's no binary available for your Node.js version, node-sass tries to build the binary on your machine. And that's where it fails.
Can you try installing node-sass anywhere on your machine and see if it works:
```
mkdir testapp
cd testapp
npm init -f
npm i --save node-sass
```

**Comment by Fabiyo-90** [comment]
I did it and I have the same error !
I do not use sass...

there is the bug

λ npm i --save node-sass

> node-sass@4.12.0 install D:\project\mobile\testApp\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxyserverpac proxyserverpac:80

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall D:\project\mobile\testApp\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\project\mobile\testApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\project\\mobile\\testApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2.7" in the PATH
gyp verb `which` failed Error: not found: python2.7
gyp verb `which` failed     at getNotFoundError (D:\project\mobile\testApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\project\mobile\testApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\project\mobile\testApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\project\mobile\testApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\project\mobile\testApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\project\mobile\testApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2.7 { Error: not found: python2.7
gyp verb `which` failed     at getNotFoundError (D:\project\mobile\testApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\project\mobile\testApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\project\mobile\testApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\project\mobile\testApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\project\mobile\testApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\project\mobile\testApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2.7\n    at getNotFoundError (D:\\project\\mobile\\testApp\\node_modules\\which\\which.js:13:12)\n    at F (D:\\project\\mobile\\testApp\\node_modules\\which\\which.js:68:19)\n    at E (D:\\project\\mobile\\testApp\\node_modules\\which\\which.js:80:29)\n    at D:\\project\\mobile\\testApp\\node_modules\\which\\which.js:89:16\n    at D:\\project\\mobile\\testApp\\node_modules\\isexe\\index.js:42:5\n    at D:\\project\\mobile\\testApp\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python2.7". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.0
gyp verb build dir attempting to create "build" dir: D:\project\mobile\testApp\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? D:\project\mobile\testApp\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb Not using VS2017: No usable installation of VS2017 found
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\project\mobile\testApp\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\project\mobile\testApp\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: D:\project\mobile\testApp\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'D:\\project\\mobile\\testApp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2017',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\project\\mobile\\testApp\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\project\\mobile\\testApp\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Fabrice IYONGO\\.node-gyp\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Fabrice IYONGO\\.node-gyp\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\project\\mobile\\testApp\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Fabrice IYONGO\\.node-gyp\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\project\\mobile\\testApp\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\project\\mobile\\testApp\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "D:\project\mobile\testApp\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\project\mobile\testApp\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\mobile\\testApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\project\mobile\testApp\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN testApp@1.0.0 No description
npm WARN testApp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fabrice IYONGO\AppData\Roaming\npm-cache\_logs\2019-06-24T16_21_22_206Z-debug.log

**Comment by Fabiyo-90** [comment]
Should I use a previous version of nodejs? And yet everything worked well before I installed visual studio 2017

**Comment by Fabiyo-90** [comment]
There is a way to create a app with --vue template without node-sass ? I don't use sass

**Comment by rosen-vladimirov** [comment]
Hey @Fabiyo-90 ,

I've checked your log and it seems for some reason you are unable to download the required binary from GitHub:
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxyserverpac proxyserverpac:80

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080
```

Are you working behind a proxy? It looks like you have set some incorrect proxy with `npm config set proxy...`, but this is just an assumption.

As the issue is not related to NativeScript CLI itself, but to `node-sass`, I suggest you to ask in StackOverflow or open new issue in [node-sass repository](https://github.com/sass/node-sass).

**Comment by Fabiyo-90** [comment]
May I change the version of node ? 
I want a way to create a new project without sass, I don't use sass

**Comment by rosen-vladimirov** [comment]
Hey @Fabiyo-90 ,
I'm not sure changing Node.js version will help - there's a problem with downloading the required binary file, that's what causes the issues on your side. 
Regarding creating Vue project, you can start with simple JavaScript Hello World application and install `nativescript-vue` in it:
```
tns create myApp --js
cd myApp
npm i --save nativescript-vue
```
After that you can start adding your Vue files and content in the `app` folder. You can get the Vue files from our Vue blank template from here: https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-blank-vue/app

**Comment by Fabiyo-90** [comment]
Thanks for the advice, I did not think about that, I'll see this now

**Comment by Fabiyo-90** [comment]
I did it but it does not take into account the .vue file

**Comment by rosen-vladimirov** [comment]
Hey @Fabiyo-90 ,
I forgot to mention, once you add `nativescript-vue` , you should delete your node_modules, hooks and webpack.config.js and after that execute `npm install`. This way the postinstall script of nativescript-dev-webpack will place correct (vue) webpack.config.js in your application.

**Comment by Fabiyo-90** [comment]
I will try again

**Comment by Fabiyo-90** [comment]
ERROR in ./components/Home.vue?vue&type=sty
ativescript-dev-webpack/apply-css-loader.js
ass-loader/lib/loader.js!../node_modules/vu
Module build failed (from ../node_modules/s
Error: Cannot find module 'node-sass'      
    at Function.Module._resolveFilename (in
    at Function.Module._load (internal/modu
    at Module.require (internal/modules/cjs
    at require (D:\project\mobile\template-
    at Object.sassLoader (D:\project\mobile
 @ ./components/Home.vue?vue&type=style&ind
 @ ./components/Home.vue                   
 @ ./app.js                                
Webpack compilation complete.              
Executing webpack failed with exit code 2. 

there is my bug

**Comment by Fabiyo-90** [comment]
Thank you it's working now !
