### ISSUE TITLE
Not able to add platform android in Ubuntu 14.04

### ISSUE THREAD

**Issue by haikyuu** [NativeScript/nativescript-cli#477]
Here is the output of  `npm install -g nativescript` : 

-
> nativescript@1.0.1 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

Trying to kill adb server. Some running Android related operations may fail.
npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> fibers@1.0.5 install /usr/local/lib/node_modules/nativescript/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.28` exists; testing
Binary is fine; exiting
 
> ref@0.3.5 install /usr/local/lib/node_modules/nativescript/node_modules/ref
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/lelouch/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nativescript/node_modules/ref/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/nativescript/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory `/usr/local/lib/node_modules/nativescript/node_modules/ref/build'
Installed in `/usr/local/lib/node_modules/nativescript/node_modules/ref/bin/linux-x64-v8-3.28/binding.node`
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css

> ws@0.4.32 install /usr/local/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws/build'

> ffi@1.2.7 install /usr/local/lib/node_modules/nativescript/node_modules/ffi
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/lelouch/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nativescript/node_modules/ffi/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/nativescript/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
../deps/libffi/src/closures.c:433:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node: Finished
  COPY Release/ffi_bindings.node
make: Leaving directory `/usr/local/lib/node_modules/nativescript/node_modules/ffi/build'
Installed in `/usr/local/lib/node_modules/nativescript/node_modules/ffi/bin/linux-x64-v8-3.28/ffi_bindings.node`
/usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/nativescript.js
/usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/nativescript.js

> nativescript@1.0.1 postinstall /usr/local/lib/node_modules/nativescript
> node postinstall.js

WARNING: adb from the Android SDK is not installed or is not configured properly.
For Android-related operations, the NativeScript CLI will use a built-in version of adb.
To avoid possible issues with the native Android emulator, Genymotion or connected
Android devices, verify that you have installed the latest Android SDK and
its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the native emulator.
To be able to build for Android and run apps in the native emulator, verify that you have
installed the latest Android SDK and its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

If you are using bash or zsh, you can enable command-line completion.
? Do you want to enable it now? No
Restart your shell to disable command auto-completion.
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-git@'~1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
nativescript@1.0.1 /usr/local/lib/node_modules/nativescript
├── filesize@2.0.3
├── bufferpack@0.0.6
├── osenv@0.1.0
├── winreg@0.0.12
├── mute-stream@0.0.4
├── rimraf@2.2.6
├── colors@0.6.2
├── open@0.0.4
├── properties-parser@0.2.3
├── lockfile@1.0.0
├── bplist-parser@0.0.6
├── node-uuid@1.4.1
├── mkdirp@0.3.5
├── temp@0.8.1
├── tabtab@0.0.3
├── xmlhttprequest@1.5.1
├── marked@0.3.3
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── semver@3.0.1
├── shelljs@0.3.0
├── minimatch@2.0.4 (brace-expansion@1.1.0)
├── yargs@1.2.2 (minimist@0.0.10)
├── iconv-lite@0.4.4
├── cli-table@0.3.1 (colors@1.0.3, wcwidth@1.0.0)
├── byline@4.1.1
├── progress-stream@0.5.0 (single-line-log@0.3.1, speedometer@0.1.4, through2@0.2.3)
├── gaze@0.5.1 (globule@0.1.0)
├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── xcode@0.6.7 (node-uuid@1.3.3, pegjs@0.6.2)
├── prompt@0.2.12 (read@1.0.5, pkginfo@0.3.0, revalidator@0.1.8, utile@0.2.1, winston@0.6.2)
├── fibers@1.0.5
├── marked-terminal@1.4.0 (node-emoji@0.1.0, lodash.assign@3.1.0, cardinal@0.5.0)
├── ref-struct@1.0.0 (debug@2.2.0)
├── lodash@3.6.0
├── plistlib@0.2.1 (xml@0.0.12, node-xml@1.0.2, underscore@1.5.2, async@0.2.10, moment@2.4.0)
├── plist@1.1.0 (base64-js@0.0.6, util-deprecate@1.0.0, xmldom@0.1.19, xmlbuilder@2.2.1)
├── inquirer@0.8.2 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.7, readline2@0.1.1, rx@2.5.2)
├── npm@2.6.1
├── ios-sim-portable@1.0.7 (lodash@3.2.0, NodObjC@1.0.0)
├── ref@0.3.5 (bindings@1.2.1, prebuilt@0.1.0, debug@2.2.0, nan@1.5.3)
├── node-inspector@0.7.4 (opener@1.3.0, debug@0.8.1, which@1.0.9, async@0.8.0, strong-data-uri@0.1.1, rc@0.3.5, glob@3.2.11, express@4.0.0, ws@0.4.32)
└── ffi@1.2.7 (bindings@1.2.1, prebuilt@0.1.0, debug@1.0.4, nan@1.8.4)

But after i do `tns platform add android`, i get ``/usr/local/lib/node_modules/nativescript/node_modules/ref/bin/linux-x64-v8-3.14/binding.node` is missing. Try reinstalling `prebuilt`?`

**Comment by rosen-vladimirov** [comment]
Hi @haikyuu 
During the installation process, you are using Nodejs 0.12.2. After that when you execute `tns platform add android` it looks like the process is started with Node 0.10.x This is causing the issue - nativescript cli is installed with one version of node and after that you are trying to use it with another one.
You can verify Node's version when using nativescript by running `tns platform add android --log trace` - can you send this output as well?
I'm not sure what has caused the difference, but I suggest you to try reinstalling nativescript cli with your current node versions:
`npm i -g nativescript --unsafe-perm`
I'm looking forward to hearing from you.

**Comment by haikyuu** [comment]
Thanks for the quick reply.  
Here is the output of `tns platform add android --log trace`

Exec uname -a 
 stdout: Linux hp 3.14.3-031403-generic #201405061153 SMP Tue May 6 15:54:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
 
 stderr: 
Exec npm -v 
 stdout: 2.1.9
 
 stderr: 
spawn: java -version
Exec ant -version 
 stdout: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
 
 stderr: 
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: 1: node-gyp: not found

Exec adb version 
 stdout: Android Debug Bridge version 1.0.32
 
 stderr: 
Exec android -h 
 stdout:  
 stderr: /bin/sh: 1: android: not found

System information:
{ procInfo: 'nativescript/1.0.1',
  platform: 'linux',
  os: 'Linux hp 3.14.3-031403-generic #201405061153 SMP Tue May 6 15:54:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.10.29',
  npmVer: '2.1.9',
  javaVer: 'Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)',
  antVer: 'Apache Ant(TM) version 1.9.3 compiled on April 8 2014',
  nodeGypVer: null,
  xcodeVer: null,
  itunesInstalled: true,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: false }
Starting watch on killswitch /tmp/lelouch/KillSwitches/cli
AnalyticsInstallationID: 15f8690c-a83f-4017-be22-b7fb8b234d8a
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
BeforeHookName for command platform-add is before-platform-add
AfterHookName for command platform-add is after-platform-add
Looking for project in '/home/lelouch/workspace/playspace/nativescript/hello'
Project directory is '/home/lelouch/workspace/playspace/nativescript/hello'.
`/usr/local/lib/node_modules/nativescript/node_modules/ref/bin/linux-x64-v8-3.14/binding.node` is missing. Try reinstalling `prebuilt`?
List of registered commands: /?, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|uninstall, emulate, emulate|android, emulate|ios, feature-usage-tracking, help, library, library|add, platform, platform|*list, platform|add, platform|remove, platform|update, prepare, run, run|android, run|ios
Reading help for command 'platform|add'. FileName is 'platform-add.md'.
# platform add
┌──────────────────────────┬──────────────────────────────────────────────────────────────────────────────────┐
│ Usage                    │ Synopsis                                                                         │
│ Android latest runtime   │ $ tns platform add android [--frameworkPath <File Path>] [--symlink]             │
│ Android selected runtime │ $ tns platform add android[@<Version>] [--frameworkPath <File Path>] [--symlink] │
└──────────────────────────┴──────────────────────────────────────────────────────────────────────────────────┘

Configures the current project to target the selected platform.  

### Options

    * --frameworkPath - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package. 
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.

### Attributes

    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Version> is any available version of the respective platform runtime published in npm. 

`npm i -g nativescript --unsafe-perm` worked like a charm. Thanks

**Comment by haikyuu** [comment]
For `stderr: /bin/sh: 1: android: not found`, i had to add android location to $PATH in .zshrc

**Comment by rosen-vladimirov** [comment]
Thank you for the output. I've noticed the following line in it:
`nodeVer: 'v0.10.29',`
So the fresh installation of the nativescript cli helped.

For the other question regarding android warning - yes, you have to add the path to your `Android SDK/tools` and `Andorid SDK/platform-tools` directories to your PATH environment variable. The process is explained [here](http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-linux#setup). As you are using zsh, `.zshrc` seems the correct place, so you'll not have to add the paths every single time :) 
Hope this helps.

**Comment by haikyuu** [comment]
A lot, thanks
