### ISSUE TITLE
Missing tab bar icons in newly created tab-view application when running for iOS

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-cli#4842]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0-2019-07-11-160948-13630
 - Cross-platform modules: 6.0.1
 - iOS Runtime: 6.0.0
 - nativescript-dev-webpack: 1.0.0

**Describe the bug**
The tab bar icons are not displayed when running an application, created from the tabs template, on iOS.
Error messages on the console:
```
CONSOLE ERROR file:///node_modules/tns-core-modules/trace/trace.js:178:0 Error: Could not load tab bar icon: res://tabIcons/home
CONSOLE ERROR file:///node_modules/tns-core-modules/trace/trace.js:178:0 Error: Could not load tab bar icon: res://tabIcons/browse
CONSOLE ERROR file:///node_modules/tns-core-modules/trace/trace.js:178:0 Error: Could not load tab bar icon: res://tabIcons/search
```

**To Reproduce**

```bash
tns create tabs-app # Select: 1) Plain JavaScript 2) Tabs
cd tabs-app
tns migrate
tns run ios
```

**Expected behavior**
The tabs icons should be displayed.

**Comment by davecoffin** [comment]
@rosen-vladimirov @Fatme is this fixed in the latest RC? I'll be happy to test if so...

**Comment by rosen-vladimirov** [comment]
Hey @davecoffin , 
Yes, it should be fixed there. Can you give it a try and inform us if it works on your side?

**Comment by davecoffin** [comment]
Yup its fixed! Great, fast work guys :)

@NathanWalker FYI 👆.
