### ISSUE TITLE
Platform specific prepare breaks source map paths

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#485]
Create file `test.ios.coffee`:

```coffeescript
class MyClass
```

Compile with `--map` and `tns prepare ios`:

File `platforms/ios/TestApp/app/test.js`:
```javascript
(function() {
  var MyClass;
  MyClass = (function() {
    function MyClass() {}
    return MyClass;
  })();
}).call(this);

//# sourceMappingURL=test.ios.js.map
```

File `platforms/ios/TestApp/app/test.js.map`:
```javascript
{
  "version": 3,
  "file": "test.ios.js",
  "sourceRoot": "",
  "sources": [
    "test.ios.coffee"
  ],
  "names": [],
  "mappings": ";AAAA;AAAA,MAAA,OAAA;;AAAA,EAAM;yBAAN;;mBAAA;;MAAA,CAAA;AAAA"
}
```

The source mapping is broken.

This should be also happening with Babel, TypeScript and others.

Are there any inline source maps, that can be used only in debugging?

**Comment by burkeholland** [comment]
I'm not able to debug typescript and I assume this is related to this issue? My issue is that the .ts files simply don't show up in Safari Web Inspector, but I'm not completely sure why.

**Comment by enchev** [comment]
Still valid with 2.0.1

**Comment by vchimev** [comment]
Tests added: https://github.com/NativeScript/nativescript-cli-tests/commit/172ac708df3bf9f5e5d624365d6336ad268e4142.
