### ISSUE TITLE
Delete --platformTemplate option

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#4867]
The idea of `--platformTemplate` was to have custom native project template. However, its implementation was not correct and it was almost impossible to create such custom template.
Delete it as it was not used and consider implementing different solution in the future.

**Comment by NathanaelA** [comment]
@rosen-vladimirov - 
`--platform-template` is still showing in the help...
![image](https://user-images.githubusercontent.com/850871/61394609-1eaab280-a889-11e9-82f5-c4fb654613ad.png)
