### ISSUE TITLE
How to enable/disable the sending usage stast fucntionality after installation?

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/nativescript-cli#4882]
When you install nativescript you get a prompt to send or not to send anonymous usage statistics.
I accidentally disabled it. Can I enable everything by running
```
tns usage-reporting enable
tns error-reporting enable
```
If I change my mind later, does setting these two to disabled disable every analytic feature also?

**Comment by rosen-vladimirov** [comment]
Hey @aranmohyeddin ,
Yes, you can use the mentioned commands to enable sending anonymous usage statistics. You can also pass `disable` to these commands to stop sending usage stats:
```
tns usage-reporting disable
tns error-reporting disable
```

In case you are interested what's being tracked, you can pass `--analyticsLogFile <path to file>` and if the usage-reporting is enabled, the file will be populated with all the information that CLI tracks. For example:
```
tns build android --analyticsLogFile analyticsLogs.txt
```

I'm closing this thread, but feel free to reopen it in case you have any other questions or concerns.
