### ISSUE TITLE
[Bug] Invalid TNS Migrate occurring

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#4889]
**Environment**
 - CLI: 6.0.1
 - Cross-platform modules: 6.0.0
 - iOS Runtime: 6.0.0

**Describe the bug**
If the CLI is now even out of step by one patch version as the runtime. The stupid `tns migrate` warning command shows up.   This command is useful when upgrading from < 6.0 project.  But it is not when I am a single patch/build difference.

I had a demo that I was testing on both ios/android.  I had both set to runtime 6.0.0 in the package json; ran fine on android.  iOS CLI threw the error that I needed to do a migrate, so that it could change the `package: {ios: "6.0.0"}` to package: {ios: "6.0.1"}` 

**To Reproduce**
- npm i nativescript@6.0.1 -g
- tns create test --js
- edit package.json file to point runtime to 6.0.0 (if it isn't already).
- tns run ios

**Expected behavior**
The past behavior, it should NOT fail on patch versions...

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA ,
The requirement for 6.0.1 version of iOS Runtime is included in the official version of NativeScript CLI (6.0.0). We have set it as we have found a major issue in 6.0.0 version of iOS Runtime (applications were not working correctly when there's a space in the path to application). As this was the first **official** version of NativeScript CLI that requires min version of the runtime, we've decided to force this requirement to the version we know is working. 
We do not have plans to bump the minimum required version of the iOS Runtime (or any other packages in fact) anymore, i.e. we'll keep it 6.0.1 (at least that's the plan).
We are sorry that this had caused issues on your side, but as I said, this was the first official version of CLI that has such requirement and we thought setting 6.0.1 of iOS Runtime will be more useful for the majority of the users. Most of them had not migrated their projects to 6.0.0, so we expect most of them will not hit the case you've faced.
Once again I want to assure you we do not have plans to bump the minimum required versions of the packages, no matter if this is for patch or minor versions.
