### ISSUE TITLE
`tns preview` crashes when scanning on devices with different platforms

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4893]
- CLI: 6.0.2

If you do preview of project for first time on both ios and android  devices, the command crashes with
 TypeError: Cannot read property 'hash' of null
 at PreviewAppController.<anonymous> (C:\Users\test\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\preview-app-controller.js:130:64)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\test\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\preview-app-controller.js:10:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**To Reproduce**
1. `tns create TestApp --js`
2. `tns preview`
3. Scan the QR code on android and then scan it on ios device. Preview command crashes. 
On next preview runs everything works as expected

**Comment by maximus1010101** [comment]
Hello, I have the same problem too after the update.

**Comment by ShastinaSandman** [comment]
I have the same problem as well.

**Comment by endarova** [comment]
Other way to reproduce the same error is: `tns preview`, scan the qr code on some device and then make change in project's package.json file.

**Comment by amitdhanaliya** [comment]
Replicated the same issue while previewing the application on an iOS device. Please rectify this asap and let us know the solution.
![error](https://user-images.githubusercontent.com/53511626/62941515-d7fe9880-bdf3-11e9-9fe3-6f6d98f1d41e.png)

**Comment by endarova** [comment]
Fixed in nativescript@rc (6.1.1)
