### ISSUE TITLE
Feature request: Directly integrate Babel

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#490]
I talked with @ligaz a bit about this in Boston, but I couldn't find an open issue so I thought I'd create one so this is documented.

I would like to see Babel directly integrated into the NativeScript CLI, much like TypeScript currently is. That is, if I opt into Babel (somehow), I would like NativeScript to automatically transpile my ES6 code during `prepare`.

You can implement this workflow today, but you have to implement your own build setup that moves files around in your project. @csell5 and I [implemented this sort of thing for JustMeme](https://github.com/NativeScript/sample-JustMeme), and @emiloberg actually [built an module to do this](https://www.npmjs.com/package/nativescript-emulator-reload). Each of us independently wrote a mechanism for moving files from `src` to `app`.

This could be tricky to implement as we'd want to make it possible for people to change their Babel version and config, but I still personally believe this is worth doing. As an alternative maybe we could somehow make `prepare` pluggable. What I'm really trying to avoid is the need to create a `src` folder and to move files around.

Thanks,
TJ

**Comment by emiloberg** [comment]
Calling it a module is a much, it's a simple gulpscript ;)

Anyways. As for the config goes, it's an important part (as some people want to use Stage 0/ES7 stuff where others are quite happy with Stage 4/ES6 things). But Babel is using a `.babelrc` which {N} should adhere to. Shouldn't be to much of a problem.

**Comment by Fatme** [comment]
It seems that we can use `https://www.npmjs.com/package/broccoli-babel-transpiler`. It supports babel options - http://babeljs.io/docs/usage/options/ so the user will be able to configure them.

**Comment by ligaz** [comment]
We have written down our current thinking in this issue: https://github.com/NativeScript/nativescript-cli/issues/493. I'm going to close this down and let's continue the discussion there.
