### ISSUE TITLE
Error executing nativescript/tns on Linux ubuntu 14.04.2 LTS 64-bit

### ISSUE THREAD

**Issue by kivS** [NativeScript/nativescript-cli#491]
Hello, I get the following error when trying to use  tns/navtivescript:

Error: EPERM, chmod '/tmp/dongato/KillSwitches'
    at Object.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at new CancellationService (/usr/local/lib/node_modules/nativescript/lib/common/services/cancellation.js:14:67)
    at Yok.resolveConstructor (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:289:18)
    at Yok.resolveByName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:315:44)
    at Yok.resolve (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:247:25)
    at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:280:30
    at Array.map (native)
    at Yok.resolveConstructor (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:275:46)
    at Yok.resolveByName (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:315:44)
    at Yok.resolve (/usr/local/lib/node_modules/nativescript/lib/common/yok.js:247:25)
    - - - - -
    at Error (native)

Any ideas how to solve?
Thanks

**Comment by rosen-vladimirov** [comment]
Hi @kivS ,
May I ask you to check who is owner of /tmp/dongato and /tmp/dongato/KillSwitches directories. If your user is not the owner, you can try changing the ownership of these directories, so you user should be able to access them.
In case this does not help and you are using node with sudo, can you try reinstalling nativescript-cli with ```$ sudo npm i -g nativescript --unsafe-perm```

If you still get the same error, may I ask you to send us the output of 
```tns -h --log trace```

I'm looking forward to hearing from you.

**Comment by kivS** [comment]
Hey @rosen-vladimirov,
I tried and re-installed.The owner is user dongato. It's working when using sudo, without it the trace log ouput is:
Exec uname -a 
 stdout: Linux dongato 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 
 stderr: 
Exec npm -v 
 stdout: 2.9.1
 
 stderr: 
spawn: java -version
Exec ant -version 
 stdout: Apache Ant(TM) version 1.9.4 compiled on January 27 2015
 
 stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: 1: node-gyp: not found

Exec adb version 
 stdout: Android Debug Bridge version 1.0.32
 
 stderr: 
Exec android -h 
 stdout: 
       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.
 
 stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

System information:
{ procInfo: 'nativescript/1.0.1',
  platform: 'linux',
  os: 'Linux dongato 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.3',
  npmVer: '2.9.1',
  javaVer: 'Java(TM) SE Runtime Environment (build 1.8.0_45-b14)',
  antVer: 'Apache Ant(TM) version 1.9.4 compiled on January 27 2015',
  nodeGypVer: null,
  xcodeVer: null,
  itunesInstalled: true,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true }
Starting watch on killswitch /tmp/dongato/KillSwitches/cli
Error: watch ENOSPC
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:16:45
    - - - - -
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /usr/local/lib/node_modules/nativescript/lib/common/dispatchers.js:36:46
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:16:45
    - - - - -
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/gaze.js:289:30)
    at /usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/usr/local/lib/node_modules/nativescript/node_modules/gaze/lib/gaze.js:74:10)

**Comment by rosen-vladimirov** [comment]
Hi @kivS 
Thank you for sharing the log. The error here is ENOSPC, which means there's no free space on the places where we are trying to create our "watch" file. Can you check the available space for your /tmp directory, it looks like it is full.

**Comment by kivS** [comment]
Hello @rosen-vladimirov, 
thank you for the feedback, increasing the maximum amount of system watches solved the issue.
