### ISSUE TITLE
livesync not working with command tns test android

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#4914]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.2.
 - Android Runtime: 6.0.0
 - karma-webpack: 3.0.5

**Describe the bug**
Run the app and make a change in tests/example.js. You will see: ```Unable to apply changes for device: emulator-5554. Error is: Socket connection timed out..``` and new change is missing. 

**To Reproduce**
1. ```tns create appJS --js```
2. ```tns test init```
3. add console.log() in tests/example.js
4. ```tns test android```
5. add new console.log() in tests/example.js
You will see: ```No captured browser, open http://localhost:9876/```
```Unable to apply changes for device: emulator-5554. Error is: Socket connection timed out..```
after that console.log will miss

**Expected behavior**
working properly

**Comment by jasonstcyr** [comment]
Thank you.
