### ISSUE TITLE
The parser did not find any certificates in the .apk.

### ISSUE THREAD

**Issue by wendt88** [NativeScript/nativescript-cli#4918]
**Environment**
```
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 6.0.2 version and is up to date.
√ Component tns-core-modules has 6.0.3 version and is up to date.
√ Component tns-android has 6.0.1 version and is up to date.
√ Component tns-ios has 6.0.1 version and is up to date.
```
**Describe the bug**
error comes after upgrade to ns 6, now I tried on a new project by running `tns create newproject --vue`, but with the same error:

`Unable to apply changes on device: XXXXX. Error is: The parser did not find any certificates in the .apk..`

**Comment by KristianDD** [comment]
Hi @wendt88 ,
This error is thrown by `adb` when we use it to install the application on a device/emulator. There are a few things you can try to isolate and resolve the issue.
1. Try on a different device/emulator. If this works, it is most probably an issue with the device configuration - check that `USB debugging` is enabled in `Developer options`.
2. Try killing the `adb` process. The CLI will start a fresh one on the next run.
3. Try to cleanup the configuration and artifacts directories - `rm -rf node_module hooks platforms`. Then run the application again.
4. Try installing Android SDK Tools version 28.0.3 and Android SDK 28

If the issue persists, you can run the project with `tns run android --log trace > out.txt` command and send us the `out.txt` file that will contain the full output log of the NativeScript CLI.

**Comment by wendt88** [comment]
Thank you, for your answer...
I tried all this thinds without success (SDK Tools was already on v 29+ and I didn't know how to downgrade), but a computed restart solved the problem

**Comment by rosen-vladimirov** [comment]
Closing the issue as it has been resolved on users's machine after restart.
