### ISSUE TITLE
ERROR trying install ios ipa

### ISSUE THREAD

**Issue by calleja23** [NativeScript/nativescript-cli#4930]
Hi guys!
Thanks for this framework!

**Environment**

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.2
 - tns-core-moules: 6.0.5

 - Cross-platform modules:
 - iOS Runtime:
 - Plugin(s): camera, firebase, bandscanner
 - xcode 10.3
 - tns-ios: 6.01
 - NativeScript-Angular: ^8.1.0
 - Angular: 8.0.0
 
**Describe the bug**

since I updated the macos, the xcode, the nativescript version, I can't install any application on ios. When I create one from 0 I can install it but not open it, after the launch screen appears crashed, and no errors appear.

**To Reproduce**

create 1001 new certificates, regenerating appIDs, profiles ...
remove platforms
remove hooks
remove node modules
update pods
update nativescript
update webpack
migrate
build ios
prepare ios
when I create an app from scratch (with the same appid) I get to install it but I can't open it it doesn't happen from the launchscreen
**Expected behavior**
I almost always get the error you can't install the app
other times I returned the error from xcode 65 0 70 ..
You cannot identify the type of development profile or you do not have permissions to access the Wi-Fi .. when you can.
![Captura de pantalla 2019-08-06 a las 13 28 01](https://user-images.githubusercontent.com/11317014/62545446-ff88ba80-b861-11e9-9b79-626d5310c201.png)
[log.txt](https://github.com/NativeScript/nativescript-angular/files/3472579/log.txt)

**Comment by miroslavaivanova** [comment]
Hey @calleja23 
It looks like the problem is related to the Code Signing of the application. Can you please try to download your developer and distribution certificates from [apple](https://developer.apple.com) and double click them to add in a keychain. Also, ensure you are logged with your appleID in Xcode.

**Comment by calleja23** [comment]
Hi @miroslavaivanova 

Thank you very much for answering, "I have solved it" by creating a new user (mac) by creating all the certificates, profiles ... etc ...
Thank you
I close the issue
