### ISSUE TITLE
tns is not defined.

### ISSUE THREAD

**Issue by Peayne** [NativeScript/nativescript-cli#4931]
**Environment**
I'm using a boilerplate which is running with Prepros. I'm not using NPM because I don't know how to initialize it with my existing boilerplate.

**Describe the bug**
I used the CDN to access to tiny-slider, but when I'm going on my project I have this :
"slider.js:1 Uncaught ReferenceError: tns is not defined
    at slider.js:1"

**To Reproduce**
I put the CSS CDN link and the JS CDN link in my HTML.

**Sample project**
https://github.com/Peayne/my-own-website

**Additional context**
I'm really new in Web development, so I'm almost sure that I did something wrong but I followed step by step the installation. Very sorry if the solution is simple but I'm desesperate now.

**Comment by rosen-vladimirov** [comment]
Hey @Peayne , 
NativeScript CLI is a Node.js package that should be used in a desktop environment. It is not intended for web development and usage in websites. If I understand you correctly, you've tried to use the package in your website, which is not the purpose of the package. You can find more information about NativeScript [here](https://www.nativescript.org/). 
I'm closing this issue, but feel free to reopen it in case I've misunderstood your question.
