### ISSUE TITLE
tns create command generates the old TabView component

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/nativescript-cli#4935]
When I create an app with command `tns create` and select tabs template, it generate with the old tab component. When will this be updated?

**Comment by miroslavaivanova** [comment]
@vahidvdn 
These new components are still in Beta. You can track the current status [here](https://github.com/NativeScript/NativeScript/issues/6967).

**Comment by vahidvdn** [comment]
@miroslavaivanova
When will this be a part of cli app creation? Will it be in 6.1?
