### ISSUE TITLE
Running Nativescript full setup has caused all globally installed packages to disappear

### ISSUE THREAD

**Issue by modermo** [NativeScript/nativescript-cli#4943]
**Environment**
Unforunately unavailable because none of my commands work after doing the full Nativescript local dev setup.

I'm running Mojave 10.14.4

**Describe the bug**

I just ran to the following completely install the Nativescript local development environment:

```ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"```

And now, none of my global commands work.

Running `npm`, `nvm`, `nativescript` etc all return:

```-bash: npm: command not found```

**To Reproduce**
I ran `ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"`

**Expected behavior**
A complete install of Nativescript local dev setup. 

**Additional context**
What for it's worth, opening a new terminal yields me:

```-bash: /Users/user/.nvm/nvm.shexport: No such file or directory```
Where have I gone wrong here?

**Comment by modermo** [comment]
Looks like:

```. ~/.bashrc```

...fixed it.

What actually happened during installation that caused this to happen in the first place?

**Comment by modermo** [comment]
Welp... looks like it was only a temporary fix. Seems that I'm now still getting the above error when I restart the terminal

**Comment by rosen-vladimirov** [comment]
Hey @modermo ,
Can you please check your `~/.bash_profile and see if you have a reference to `~/.bashrc` in it?
In case not, can you try adding the following lines in your `~/.bash_profile`:
```
if [ -f ~/.bashrc ]; then 
    source ~/.bashrc 
fi
```

**Comment by modermo** [comment]
What happened was that Nativifer concatenated lines in my `.bash_profile`. So what should have been this: 
```
source ~/.nvm/nvm.sh
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
```
Was this:
```
source ~/.nvm/nvm.shexport JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
```

**Comment by modermo** [comment]
You can close this btw.
