### ISSUE TITLE
[iOS] tns publish runs HMR - results Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by yassilah** [NativeScript/nativescript-cli#4944]
**Environment**
✔ Component nativescript has 6.0.3 version and is up to date.
✔ Component tns-core-modules has 6.0.6 version and is up to date.
✔ Component tns-android has 6.0.1 version and is up to date.
✔ Component tns-ios has 6.0.2 version and is up to date.

 - Plugin(s):
"nativescript-app-sync": "^1.0.4"
"nativescript-calendar": "^2.1.0"
"nativescript-directions": "^1.3.1"
"nativescript-fingerprint-auth": "^7.0.1"
"nativescript-gif": "^4.0.2"
"nativescript-image-cache-it": "^5.0.0-alpha.3"
"nativescript-image-swipe": "^5.0.0"
"nativescript-iqkeyboardmanager": "^1.5.1"
"nativescript-mapbox": "^4.4.1"
"nativescript-secure-storage": "^2.5.0"
"nativescript-social-login": "^4.0.1"
"nativescript-social-share": "^1.5.2"
"nativescript-stripe-sdk": "^1.1.4"
"nativescript-videoplayer": "^4.2.1"
"nativescript-vue": "^2.4.0"

**Describe the bug**
After migrating to Nativescript 6, I am unable to publish my iOS app. I have tested publishing it through XCode and everything works fine except I eventually get the following error: ITMS-90535: Unexpected CFBundleExecutable Key - The bundle at '/Payload/frontend.app/app/App_Resources/iOS/Info.plist' does not contain a bundle executable.

Using "tns publish ios", I get the following (very strange) error: {"data":null,"messages":{"warn":null,"error":["Unexpected Error"],"info":null},"statusCode":"ERROR"}

What I find strange is that I am perfectly able to run the app both on emulator and on my iPhone (btw great work on ns6, hmr works like a charm ❤️), I simply cannot publish it...

**Comment by tkrevh** [comment]
If anyone is using vue.config.js for webpack config, solution for us was to add:
`config.plugins.delete('copy-native-resources')` in the chainWebpack function.

**Comment by Lelelo1** [comment]
I having the same problem in [react-nativescript](https://github.com/shirakaba/react-nativescript), also when archiving in Xcode. `--hmr=false` nor `--release` helps. I suspect I might have to comment something out in the  `wepback.config.js` as well? @shirakaba

**Comment by Lelelo1** [comment]
I moved the info.plist out of the `app` folder: https://stackoverflow.com/questions/39512387/app-processing-error-unexpected-cfbundleexecutable-key
and my build passed.
Having made a fairly simple app - there seem to be no implication of having done that.

**Comment by shirakaba** [comment]
@Lelelo1 thanks for pointing me to this thread. The RNS starter template is forked from the NativeScript Core TS one. I’ll check whether it has the same issue that @rigor789 found (which should probably cover your issue), and address it in the same way if so.

This would mean that the NativeScript Core TS starter template is broken, too! @rosen-vladimirov we might then want to check that the Svelte template isn’t similarly broken.
