### ISSUE TITLE
Android warning messages when updating cli

### ISSUE THREAD

**Issue by lighta971** [NativeScript/nativescript-cli#495]
### Cli output

sudo npm install nativescript -g
> WARNING: adb from the Android SDK is not installed or is not configured properly.
For Android-related operations, the NativeScript CLI will use a built-in version of adb.
To avoid possible issues with the native Android emulator, Genymotion or connected
Android devices, verify that you have installed the latest Android SDK and
its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

> WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the native emulator.
To be able to build for Android and run apps in the native emulator, verify that you have
installed the latest Android SDK and its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

### System configurations
```
uname -a
Linux aurel-XPS13-9333 3.19.2-031902-generic #201503181436 SMP Wed Mar 18 14:37:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.1 Rebecca
Release:        17.1
Codename:       rebecca
```

```
 echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools:/home/aurel/genymotion:/home/aurel/gradle-2.3/bin
```

```
which adb
/opt/android-sdk-linux/platform-tools/adb
```

```
 echo $ANDROID_HOME
/opt/android-sdk-linux/
```

**Comment by teobugslayer** [comment]
Hello @lighta971,

Please, run

```
tns dev-post-install --log trace > trace.txt
```

and send us the trace.txt file.

**Comment by RusEu** [comment]
same problem here
