### ISSUE TITLE
cannot deploy app on iOS 10

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4956]
**Environment**
 - CLI: 6.1.0-2019-08-16-090517-13761(@next)

**To Reproduce**
1. `tns create MyApp --js`
2. `tns run ios` on device with ios10
Error in log and app is not deployed: 
Webpack build done!
Project successfully prepared (ios)
Installing on device 5a881702b27b58979ebdd24172821f22698d4a36...
Unable to apply changes on device: 5a881702b27b58979ebdd24172821f22698d4a36. Error is: Could not start house arrest for application org.nativescript.MyApp.

**Expected behavior**
App is deployed and started on device

**Comment by rosen-vladimirov** [comment]
This happens when invalid developer disk image is deployed on device. Ensure you have latest Xcode installed and restart the device. This way the new run operation will use the correct developer disk image.
