### ISSUE TITLE
No resource found that matches the given name (at 'icon' with value  '@drawable/icon') because App_resources is missing

### ISSUE THREAD

**Issue by lighta971** [NativeScript/nativescript-cli#496]
`tns create app_test` is not creating `app/App_resources` and it cause `tns build android` to fail.

> -code-gen:
[mergemanifest] No changes in the AndroidManifest files.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] /home/aurel/projects/tns-ui/tnsUI/platforms/android/bin/AndroidManifest.xml:21: error: Error: No resource found that matches the given name (at 'icon' with value 
'@drawable/icon').
     [aapt] 

> BUILD FAILED
/opt/android-sdk-linux/tools/ant/build.xml:653: The following error occurred while executing this line:
/opt/android-sdk-linux/tools/ant/build.xml:698: null returned: 1

> Total time: 0 seconds
Command ant failed with exit code 1

Is it a normal behavior that `tns create` does not create a default App_resources directory ?

And even when I create this directory to have a successfull build, I have another error on genymotion.
I do not know if it is related.
Debug log of `tns deploy android`:

```
Successfully deployed on device with identifier '192.168.57.101:5555'                                                                                               [355/1057]
--------- beginning of /dev/log/main
D/AndroidRuntime( 1574): 
D/AndroidRuntime( 1574): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 1574): CheckJNI is OFF
D/dalvikvm( 1574): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 1574): Added shared lib libjavacore.so 0x0
D/dalvikvm( 1574): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 1574): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 1574): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm( 1574): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 1574): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 1574): failed to load memtrack module: -2
D/AndroidRuntime( 1574): Calling main entry com.android.commands.am.Am
--------- beginning of /dev/log/system
I/ActivityManager(  500): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=ui.tns.com/com.tns.NativeScriptActivity} from pid
 1574
D/AndroidRuntime( 1574): Shutting down VM
D/dalvikvm( 1574): GC_CONCURRENT freed 94K, 15% free 576K/672K, paused 0ms+0ms, total 1ms
--------- beginning of /dev/log/main
E/TNS.Native( 1543): Error: Module "application" not found
E/TNS.Native( 1543): File: "/data/data/ui.tns.com/files/app/app.js, line: 0, column: 68
E/TNS.Native( 1543): StackTrace: 
E/TNS.Native( 1543):    Frame: function:'require', file:'/data/data/ui.tns.com/files/app/app.js', line: 2, column: 234
E/TNS.Native( 1543):    Frame: function:'', file:'/data/data/ui.tns.com/files/app/app.js', line: 1, column: 19
D/dalvikvm( 1543): GC_CONCURRENT freed 180K, 7% free 3251K/3480K, paused 0ms+1ms, total 3ms
D/AndroidRuntime( 1543): Shutting down VM
W/dalvikvm( 1543): threadid=1: thread exiting with uncaught exception (group=0xa4cbcb20)
E/TNS.Native( 1543): Error: Module "application" not found
E/TNS.Native( 1543): File: "/data/data/ui.tns.com/files/app/app.js, line: 0, column: 68
E/TNS.Native( 1543): StackTrace: 
E/TNS.Native( 1543):    Frame: function:'require', file:'/data/data/ui.tns.com/files/app/app.js', line: 2, column: 234
E/TNS.Native( 1543):    Frame: function:'', file:'/data/data/ui.tns.com/files/app/app.js', line: 1, column: 19
D/dalvikvm( 1543): GC_CONCURRENT freed 180K, 7% free 3251K/3480K, paused 0ms+1ms, total 3ms
D/AndroidRuntime( 1543): Shutting down VM
W/dalvikvm( 1543): threadid=1: thread exiting with uncaught exception (group=0xa4cbcb20)
F/libc    ( 1543): Fatal signal 11 (SIGSEGV) at 0x00004350 (code=1), thread 1543 (ui.tns.com)
F/libc    ( 1543): Fatal signal 11 (SIGSEGV) at 0x00004350 (code=1), thread 1543 (ui.tns.com)
I/DEBUG   (  141): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

Configuration:
Linux mint 17
Nativescript-cli 1.0.1

**Comment by lighta971** [comment]
Problem solved by re installing nativescript. App_resources are now generated and no error happen on build.
These problems appeared after an update, 0.9 to 1.0

**Comment by Fatme** [comment]
Hi @lighta971,

We've introduced breaking change in `0.10` version related to project structure. You can find more information here - https://github.com/NativeScript/nativescript-cli/blob/master/README.md#create-project. 
In older versions than `0.10` version `App_Resoucerces` folder ``is not included`` into `app` folder.
It seems that you're creating you project with older than `0.10` version of `NativeScript CLI` and trying to build it with runtime version greater than `0.10`. You can get runtime version from `.tnsproject` file.

**Comment by lighta971** [comment]
I knwew that, `App_Resources` just was not created even with last version. tns maybe broke when I updated it.
But like I said, it's fine know, after removing and installing the cli again.
You can close this issue I guess.
