### ISSUE TITLE
Difference in hookArgs.prepareData.platform

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-cli#4963]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0.6
 - Android Runtime: 6.0.1
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
There is a difference in the casing of the platform that is sent to an `after-prepare` hook. 

**To Reproduce**
Create a simple plugin with an `after-prepare` hook having the following:
```js
module.exports = function (hookArgs) {
  console.log("PLATFORM: ", hookArgs.prepareData.platform)
}
```
Execute:
```
tns prepare ios
```
Output:
```
PLATFORM: ios
```
Execute:
```
tns run ios
```
Output:
```
PLATFORM: iOS
```

**Expected behavior**
The `platform` should be made consistent no matter which CLI command you are executing. 

**Sample project**

**Additional context**

**Comment by rosen-vladimirov** [comment]
Hey @PeterStaev ,
Thanks for sharing this issue. We've successfully reproduced it on our side based on your descriptions and it is definitely not expected to have the platform with different casing based on the executed command.

**Comment by azozen** [comment]
اوك الأمور ما اعرفها
