### ISSUE TITLE
MIgrating issues to NS 6.x

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-cli#4969]
Migrating from latest 5.x to 6.x

When I run the app on the Android emulator (Mac) - I get the following runtime error

```
Restarting application on device emulator-5554...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: ReferenceError: observable is not defined
System.err: File: "file:///app/subscription.ts:10:34
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///app/subscription.ts:10:34
System.err: 	Frame: function:'./subscription.ts', file:'file:///data/data/dev.crewapps.test/files/app/bundle.js', line: 14464, column: 30
System.err: 	Frame: function:'__webpack_require__', file:'file:///app/webpack/bootstrap:750:0
```

The first few lines of the Subscription.ts file are:

```
import httpModule = require("tns-core-modules/http");
import observable = require("tns-core-modules/data/observable");
import { Transaction, TransactionState } from "nativescript-purchase/transaction";
import { Product } from "nativescript-purchase/product";
import platformModule = require("tns-core-modules/platform");
import fingerprintModule = require("nativescript-fingerprint-auth");

import utils = require("./utils");

export class Subscription extends observable.Observable  // line#10 
{
}
```

What could the problem be?

I do have other files in the project - that don't have the tns-core-modules/ prefix.

So there could be another file with

`import observable = require("data/observable");`

Also, in the bundle.js file - there are 8 other similar references to `observable` - the error one is the last one in the file and is the only one being error logged - of course it could be being used at runtime for the first time.

**Comment by NickIliev** [comment]
@erjdriver migrate all short imports (e.g. `import * as observable from "data/observable"`) to full-path imports (e.g., `import * as observable from "tns-core-modules/data/observable"`) - NativeScript 6 is working with Webpack by default and [is **not** supporting short imports](https://www.nativescript.org/blog/say-goodbye-to-short-imports-in-nativescript)

**Comment by erjdriver** [comment]
Ok after changing to the required format I was able to get past this error message - now have to deal with other migration issues.

If this is just a critical requirement, why let it get past the build process - just flag it as an error and force a change. I spent days trying to figure out the issue.

Or better yet, make it part of the migrate program and make this change automatically.

I've got a lot of files and each file has a lot of this lines  - I had to write a script program to automate it.

**Comment by erjdriver** [comment]
btw - how should the following be written for NS6

`var timer = require("tns-core-modules/timer");`

**Comment by Fatme** [comment]
@erjdriver,

You can see more info about `timer` module and how to use it [here](https://docs.nativescript.org/ns-framework-modules/timer).

**Comment by erjdriver** [comment]
Apologies for not being clear - my question was re the new syntax for imports

Can `var timer = require("tns-core-modules/timer");` be written as

`import * as timer from "tns-core-modules/timer";`

i.e. is it the same?

**Comment by Fatme** [comment]
@erjdriver,

NativeScript 6 doesn't force you to update `require` to `import` or vice versa. The only requirement is to update your short imports i.e:

### OLD
```
const timer = require("timer");
import * as timer from "timer";
```

#### NEW
```
const timer = require("tns-core-modules/timer");
import * as timer from "tns-core-modules/timer";
```

In other words, you need only `tns-core-modules` prefix before the name of the imported/required module.
