### ISSUE TITLE
Nativescript 6 - environment specific files not working

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/nativescript-cli#4977]
0

I just recently migrated my app to NS 6 and I noticed that the environment specific files are not processed properly.

E.g. I have settings.debug.json and settings.release.json. In code, I reference them as import * as settings from '/settings.json' . In NS < 6, this used to work, but now I get an error that that settings.json does not exist.

I have very limited experience with Webpack. Is there a setting I need to configure there for this to work?

Here is my package.json:

```{
  "name": "<app>",
  "nativescript": {
    "id": "<id>",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.1"
    }
  },
  "description": "",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "moment": "^2.24.0",
    "nativescript-appversion": "^1.4.2",
    "nativescript-geolocation": "5.1.0",
    "nativescript-iqkeyboardmanager": "1.3.0",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-local-notifications": "3.1.0",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-theme-core": "~1.0.4",
    "tns-core-modules": "6.0.1"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "1.0.2",
    "typescript": "3.4.5"
  },
  "readme": "",
  "author": ""
}```

Thank you.

**Comment by Fatme** [comment]
Hey @dpdragnev,

Thank you for reporting this issue and sorry for the late reply!

You're absolute correct that this is not supported as of NativeScript 6. We'll plan the fix for one of our next releases.
Meanwhile there is a workaround - you should modify the following in`webpack.config.js`:

### require the file in typescript apps

```
const buildConfiguration = production ? "release" : "debug"; 
resolve: {
    extensions: [".ts", ".js", ".scss", ".css", `.${buildConfiguration}.json`, ".json"]
}
``` 
After that you should require `settings.json` using the following syntax:
```
const settings = require("./settings");
```

> NOTE: The above workaround is valid only for typescript projects and will work only when the file is required. It will not work in the following cases:
> *  when the file is imported in typescript apps (`import * as settings from "./settings.json"`)
> *  in angular apps regardless if file is required or imported.

### import the file in typescript app

For this case you can check [this sample demo application](https://github.com/Fatme/configurationSpecificFilesTs) demonstrating the required changes.

### import/require the file in angular app

For this case you can check [this sample demo application](https://github.com/Fatme/configurationSpecificFilesNg) demonstrating the required changes.

**Comment by dpdragnev** [comment]
Thank you @Fatme 

I am trying to implement your solution, but I am having some issues.  The sample solution you provided is different than what your code snippet shows above.  Namely, the webpack.config.js is different and the way you import/require is different.  I tried both, to import and to require the settings file, but in both cases I get errors.  

When I require the file as: **const settings = require("./settings");** I get **Cannot find module ./settings** error.

When I import it, as shown in the sample solution, Visual Studio Code underlines it with the same error: **Cannot find module 'settings'**  The strange thing is that, I can actually build the app, but the error still remains.

Please advise.

**Comment by Fatme** [comment]
Hey @dpdragnev,

> The sample solution you provided is different than what your code snippet shows above.

Yes, it is different as the code snippet above is for the case when `settings.json` is required and the sample app is for the case when `settings.json` is imported.

> When I require the file as: const settings = require("./settings"); I get Cannot find module ./settings error.

You need  `{ "resolveJsonModule": true }` in your `tsconfig.json` as well.

> The strange thing is that, I can actually build the app, but the error still remains.

What do you exactly mean by "but the error still remains"? Do you mean that the error remains only in Visual Studio Code and it is not shown in your terminal? Keep in mind that you need here `{ "resolveJsonModule": true }` in `tsconfig.json` as well.

**Comment by dpdragnev** [comment]
Thank you very much @Fatme.  After revising my code to match your sample project everything worked as expected.
