### ISSUE TITLE
[AAB] No .aab found in bundle directory.

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#4987]
Towday i get this error wtih nativescript@next and tns-android@next
```
No .aab found in /Volumes/data/dev/nativescript/ActiveLook/platforms/android/app/build/outputs/bundle directory.
```
After looking at it, it is because Gradle generate a ```app-release.aab``` and not ```app.aab```

This can be fixed here:
https://github.com/NativeScript/nativescript-cli/blob/9320a1de8462e8451f08a4798d35912573f78ac3/lib/services/android-project-service.ts#L66
We need to add ```${constants.APP_FOLDER_NAME}-${buildMode}${constants.AAB_EXTENSION_NAME}```
like it is done with ```apk```

**Comment by KristianDD** [comment]
Hi @farfromrefug ,
Thanks for reporting this and for your effort to investigate it. Your suggestion for a solution is spot on.

We have already created a PR, addressing the issue - https://github.com/NativeScript/nativescript-cli/pull/4986.

**Comment by farfromrefug** [comment]
@KristianDD Sorry did not see you already had the PR :P

**Comment by kokosky93** [comment]
Version 6.3 throwing the same error. I am working with Angular app
