### ISSUE TITLE
Building plugin and running demo app fails if plugins has a surrounding gradle build

### ISSUE THREAD

**Issue by madmas** [NativeScript/nativescript-cli#4995]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0
 - Android Runtime: 6.0.2
 - iOS Runtime: 6.0.2
 - Plugin(s): 

**Describe the bug**

When building an Plugin which uses gradle to encapsulate the NPM setup, running the demo app fails due to the error message:

> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Project directory '[...]/plugin/demo/platforms/tempPlugin/nativescript_plugin' is not part of the build defined by settings file '[...]/settings.gradle'. If this is an unrelated build, it must have its own settings file.

**To Reproduce**

* Create a new plugin using the seed
* add a surroungind gradle multi-module build that includes /plugin in the settings.gradle file
* try to run the demo app in /plugin/demo 

**Expected behavior**

* Plugin can be built and demo runs flawlessly.

**Additional context**

I'll add a PR to solve this as it implies only adding a settings.gradle file to the gradle-plugin contained in nativescrip-cli .

**Comment by KristianDD** [comment]
Hi @madmas ,
Thanks for logging this issue and for the effort of creating a PR.

Could you please attach a sample project/archive that represents the setup you are using to reproduce the issue, so that we can verify the fix.

**Comment by madmas** [comment]
Hi @KristianDD , 

finally I could set it up: https://github.com/madmas/NativeScriptPluginSampleGradleBuild

please have a look at it and let me know if I can help

**Comment by rosen-vladimirov** [comment]
Hey @madmas ,
Thank you for the sample project. We've merged your PR and we'll use the project to test it on our side.
Meanwhile, you can take a look at this blog post for information how you can use your contribution to participate in the Hacktoberfest initiative.
