### ISSUE TITLE
tns run offline support is now broken.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#5026]
**Environment**
 - CLI: 6.1
- Runtimes: 6.1
- Core: 6.1

**Describe the bug**
Attempting to do a `tns run android` when the computer is offline will fail and return the following error:
```
Command failed: npm view tns-core-modules  versions --json
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nathanael/.npm/_logs/2019-09-18T20_47_48_944Z-debug.log
```

**To Reproduce**
1. Take computer offline.
2. tns run android

**Expected behavior**
`tns run android` to actually run the application, even though it can't access npm.  

**Additional context**
`tns deploy` appeared to still work.

**Comment by NathanaelA** [comment]
Is their someway we can get this fixed.   This has been driving me nuts since v6.0 --  This is crazy bad when the internet is very flaky and/or slow.   I just sat waiting for about 10 minutes several times and had to cancel it each of those times. then finally this last time it actually connected and got the data it was looking for, so it could continue and actually run and deploy the app..  

I'd be even happy to have to pass a `--offline` flag to disable all npm calls/checks, or set an environmental variable.

**Comment by NathanaelA** [comment]
If anyone needs to disable "online" mode; you can manually patch the nativescript/lib/node-package-manager.js file in your npm global directory.

The two highlighted lines; fixes my issue as it basically makes the `npm view` commands a noop command.   

![image](https://user-images.githubusercontent.com/850871/67316915-e8f01800-f4ce-11e9-8607-79843b8186a9.png)

I'd be very happy to have a '--offline` flag that I can pass that would eliminate the `npm view` commands.

**Comment by KristianDD** [comment]
Hi @NathanaelA ,
The `npm view` calls are triggered by the `shouldMigrate` method, which validates that the application is NativeScript v6.x.x compatible. Inspired by this issue we implemented caching for that check based on the `package.json` content - https://github.com/NativeScript/nativescript-cli/pull/5074. Now all check should be skipped after the first run, which also brings some performance improvement for all commands that validate the project. You can try it by using `nativescript@rc`.

Event without the `shouldMigrate` caching I was able to get the error described only for the very first run of the application. The first run of the application, always requires an internet connection(native build tools might need dependencies). After that every run worked even without an internet connection as all packages were cached. 

Offline support for running the application was never an official or documented feature. If it works it is more of a coincidence, than a specific effort.

**Comment by NathanaelA** [comment]
@KristianDD 

> Offline support for running the application was never an official or documented feature. If it works it is more of a coincidence, than a specific effort.

Well considering it has worked perfectly offline since I started using NativeScript at v0.9, I would have to say when it started failing to work offline -- I really consider that a serious regression.  :D      This has been a **major** feature of my work flow since my internet can frequently be out or I might be outside of coverage for large chunks of time...    

So thank you for getting it fixed or at least caching the value so that all future runs will continue to work, if the cache value doesn't exist...
