### ISSUE TITLE
Nativescript Nodeify Plugin not compatible with webpack

### ISSUE THREAD

**Issue by Falu-G** [NativeScript/nativescript-cli#5027]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - Nativescript Angular: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - nativescript-nodeify

*ERROR in ../node_modules/readable-stream/lib/_stream_readable.js
[19-09-19 10:24:19.581] (CLI) Module not found: Error: Recursion in resolving
[19-09-19 10:24:19.581] (CLI) Stack:
[19-09-19 10:24:19.581] (CLI)   resolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/readable-stream/lib) string_decoder/
[19-09-19 10:24:19.58
  newResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/readable-stream/lib) string_decoder/
[19-09-19 10:24:19
  parsedResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/readable-stream/lib) string_decoder directory module
  de
[19-09-19 10:24:19.607] (CLI) scribedResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/readable-stream/lib) string_decoder directory module

  resolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/readable-stream/lib) string_decoder/ directory module
[19-
  newResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/readable-stream/lib) string_decoder/ directory module
[
 @ ../node_modules/readable-stream/lib/_stream_readable.js 162:40-66 324:38-64
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/readable-stream/readable-browser.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/stream-browserify/index.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/hash-base/index.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/ripemd160/index.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/pbkdf2/lib/sync-browser.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/pbkdf2/browser.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/crypto-browserify/index.js
[19-09-19 10:24:19.607] (CLI)  @ ./app/login/login.component.ts
[19-09-19 10:24:19.607] (CLI)  @ ./app/app.module.ts
[19-09-19 10:24:19.607] (CLI)  @ ./main.ts
[19-09-19 10:24:19.607] (CLI) ERROR in ../node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_readable.js
[19-09-19 10:24:19.607] (CLI) Module not found: Error: Recursion in resolving
[19-09-19 10:24:19.607] (CLI) Stack:
[19-09-19 10:24:19.607] (CLI)   resolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/stream-browserify/node_modules/readable-stream/lib) string
  newResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/stream-browserify/node_modules/readable-stream/lib) str
  parsedResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/stream-browserify/node_modules/readable-stream/lib) 
  describedResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/stream-browserify/node_modules/readable-stream/li
  resolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/stream-browserify/node_modules/readable-stream/lib) string
  newResolve: (/private/tmp/builds/_/c3fc9ac6fd822d1e44ce13280d7ec38175a89262/5.4.2/5.4.2/AMmobile/node_modules/stream-browserify/node_modules/readable-stream/lib) str
 @ ../node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_readable.js 172:40-66 328:38-64
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/stream-browserify/node_modules/readable-stream/readable-browser.js
[19-09-19 10:24:19.607] (CLI)  @ ../node_modules/s
**Sample project**

webpack.config.js
const shims = require('nativescript-nodeify/shims.json');
const aliases = {};
for (const key of Object.keys(shims)) {
        const value = shims[key];
        aliases[key + '$'] = value;
}
aliases['inherits$'] = 'inherits/inherits_browser';

const { join, relative, resolve, sep, dirname } = require("path");
const webpack = require("webpack");
const nsWebpack = require("nativescript-dev-webpack");
const nativescriptTarget = require("nativescript-dev-webpack/nativescript-target");
const { nsReplaceBootstrap } = require("nativescript-dev-webpack/transformers/ns-replace-bootstrap");
const { nsReplaceLazyLoader } = require("nativescript-dev-webpack/transformers/ns-replace-lazy-loader");
const { nsSupportHmrNg } = require("nativescript-dev-webpack/transformers/ns-support-hmr-ng");
const { getMainModulePath } = require("nativescript-dev-webpack/utils/ast-utils");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");
const { NativeScriptWorkerPlugin } = require("nativescript-worker-loader/NativeScriptWorkerPlugin");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
const { AngularCompilerPlugin } = require("@ngtools/webpack");

module.exports = env => {
    // Add your custom Activities, Services and other Android app components here.
    const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
    ];

    const platform = env && (env.android && "android" || env.ios && "ios");
    if (!platform) {
        throw new Error("You need to provide a target platform!");
    }

    const projectRoot = __dirname;

    // Default destination inside platforms/<platform>/...
    const dist = resolve(projectRoot, nsWebpack.getAppPath(platform, projectRoot));
    const appResourcesPlatformDir = platform === "android" ? "Android" : "iOS";

    const {
        // The 'appPath' and 'appResourcesPath' values are fetched from
        // the nsconfig.json configuration file
        // when bundling with `tns run android|ios --bundle`.
        appPath = "src",
        appResourcesPath = "App_Resources",

        // You can provide the following flags when running 'tns run android|ios'
        aot, // --env.aot
        snapshot, // --env.snapshot
        uglify, // --env.uglify
        report, // --env.report
        sourceMap, // --env.sourceMap
        hmr, // --env.hmr,
    } = env;

    const externals = nsWebpack.getConvertedExternals(env.externals);
    const appFullPath = resolve(projectRoot, appPath);
    const appResourcesFullPath = resolve(projectRoot, appResourcesPath);
    const tsConfigName = "tsconfig.tns.json";
    const entryModule = `${nsWebpack.getEntryModule(appFullPath)}.ts`;
    const entryPath = `.${sep}${entryModule}`;
    const ngCompilerTransformers = [];
    const additionalLazyModuleResources = [];
    if (aot) {
        ngCompilerTransformers.push(nsReplaceBootstrap);
    }

    if (hmr) {
        ngCompilerTransformers.push(nsSupportHmrNg);
    }

    // when "@angular/core" is external, it's not included in the bundles. In this way, it will be used
    // directly from node_modules and the Angular modules loader won't be able to resolve the lazy routes
    // fixes https://github.com/NativeScript/nativescript-cli/issues/4024
    if (env.externals && env.externals.indexOf("@angular/core") > -1) {
        const appModuleRelativePath = getMainModulePath(resolve(appFullPath, entryModule), tsConfigName);
        if (appModuleRelativePath) {
            const appModuleFolderPath = dirname(resolve(appFullPath, appModuleRelativePath));
            // include the lazy loader inside app module
            ngCompilerTransformers.push(nsReplaceLazyLoader);
            // include the new lazy loader path in the allowed ones
            additionalLazyModuleResources.push(appModuleFolderPath);
        }
    }

    const ngCompilerPlugin = new AngularCompilerPlugin({
        hostReplacementPaths: nsWebpack.getResolver([platform, "tns"]),
        platformTransformers: ngCompilerTransformers.map(t => t(() => ngCompilerPlugin, resolve(appFullPath, entryModule))),
        mainPath: resolve(appPath, entryModule),
        tsConfigPath: join(__dirname, tsConfigName),
        skipCodeGeneration: !aot,
        sourceMap: !!sourceMap,
        additionalLazyModuleResources: additionalLazyModuleResources
    });

    const config = {
        mode: uglify ? "production" : "development",
        context: appFullPath,
        externals,
        watchOptions: {
            ignored: [
                appResourcesFullPath,
                // Don't watch hidden files
                "**/.*",
            ]
        },
        target: nativescriptTarget,
        entry: {
            bundle: entryPath,
        },
        output: {
            pathinfo: false,
            path: dist,
            libraryTarget: "commonjs2",
            filename: "[name].js",
            globalObject: "global",
        },
        resolve: {
            extensions: [".ts", ".js", ".scss", ".css"],
            // Resolve {N} system modules from tns-core-modules
            modules: [
                resolve(__dirname, "node_modules/tns-core-modules"),
                resolve(__dirname, "node_modules"),
                "node_modules/tns-core-modules",
                "node_modules",
            ],
            //alias: nodeify.geAlias(appFullPath), 
            alias: Object.assign({
                '~': resolve(appFullPath)
            }, aliases),// <-- Add this line
            aliasFields: ["browser"], // <-- And this line
            /*alias: {
                '~': appFullPath
            },*/
           // symlinks: true
        },
        resolveLoader: {
            symlinks: false
        },
        node: {
            // Disable node shims that conflict with NativeScript
            "http": false,
            "timers": false,
            "setImmediate": false,
            "fs": "empty",
            "__dirname": false,
        },
        devtool: sourceMap ? "inline-source-map" : "none",
        optimization: {
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        name: "vendor",
                        chunks: "all",
                        test: (module, chunks) => {
                            const moduleName = module.nameForCondition ? module.nameForCondition() : '';
                            return /[\\/]node_modules[\\/]/.test(moduleName) ||
                                appComponents.some(comp => comp === moduleName);
                        },
                        enforce: true,
                    },
                }
            },
            minimize: !!uglify,
            minimizer: [
                new UglifyJsPlugin({
                    parallel: true,
                    cache: true,
                    uglifyOptions: {
                        output: {
                            comments: false,
                        },
                        compress: {
                            // The Android SBG has problems parsing the output
                            // when these options are enabled
                            'collapse_vars': platform !== "android",
                            sequences: platform !== "android",
                        }
                    }
                })
            ],
        },
        module: {
            rules: [
                {
                    test: new RegExp(entryPath),
                    use: [
                        // Require all Android app components
                        platform === "android" && {
                            loader: "nativescript-dev-webpack/android-app-components-loader",
                            options: { modules: appComponents }
                        },

                        {
                            loader: "nativescript-dev-webpack/bundle-config-loader",
                            options: {
                                angular: true,
                                loadCss: !snapshot, // load the application css if in debug mode
                            }
                        },
                    ].filter(loader => !!loader)
                },

                { test: /\.html$|\.xml$/, use: "raw-loader" },

                // tns-core-modules reads the app.css and its imports using css-loader
                {
                    test: /[\/|\\]app\.css$/,
                    use: [
                        "nativescript-dev-webpack/style-hot-loader",
                        { loader: "css-loader", options: { minimize: false, url: false } }
                    ]
                },
                {
                    test: /[\/|\\]app\.scss$/,
                    use: [
                        "nativescript-dev-webpack/style-hot-loader",
                        { loader: "css-loader", options: { minimize: false, url: false } },
                        "sass-loader"
                    ]
                },

                // Angular components reference css files and their imports using raw-loader
                { test: /\.css$/, exclude: /[\/|\\]app\.css$/, use: "raw-loader" },
                { test: /\.scss$/, exclude: /[\/|\\]app\.scss$/, use: ["raw-loader", "resolve-url-loader", "sass-loader"] },

                {
                    test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
                    use: [
                        "nativescript-dev-webpack/moduleid-compat-loader",
                        "nativescript-dev-webpack/lazy-ngmodule-hot-loader",
                        "@ngtools/webpack",
                    ]
                },

                // Mark files inside `@angular/core` as using SystemJS style dynamic imports.
                // Removing this will cause deprecation warnings to appear.
                {
                    test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
                    parser: { system: true },
                },
            ],
        },
        plugins: [
            // Define useful constants like TNS_WEBPACK
            new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
                "process": undefined,
            }),
            // Remove all files from the out dir.
            new CleanWebpackPlugin([`${dist}/**/*`]),
            // Copy native app resources to out dir.
            new CopyWebpackPlugin([
                {
                    from: `${appResourcesFullPath}/${appResourcesPlatformDir}`,
                    to: `${dist}/App_Resources/${appResourcesPlatformDir}`,
                    context: projectRoot
                },
            ]),
            // Copy assets to out dir. Add your own globs as needed.
            new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
            // Generate a bundle starter script and activate it in package.json
            new nsWebpack.GenerateBundleStarterPlugin([
                "./vendor",
                "./bundle",
            ]),
            // For instructions on how to set up workers with webpack
            // check out https://github.com/nativescript/worker-loader
            new NativeScriptWorkerPlugin(),
            ngCompilerPlugin,
            // Does IPC communication with the {N} CLI to notify events when running in watch mode.
            new nsWebpack.WatchStateLoggerPlugin(),
        ],
    };

    if (report) {
        // Generate report files for bundles content
        config.plugins.push(new BundleAnalyzerPlugin({
            analyzerMode: "static",
            openAnalyzer: false,
            generateStatsFile: true,
            reportFilename: resolve(projectRoot, "report", `report.html`),
            statsFilename: resolve(projectRoot, "report", `stats.json`),
        }));
    }

    if (snapshot) {
        config.plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
            chunk: "vendor",
            angular: true,
            requireModules: [
                "reflect-metadata",
                "@angular/platform-browser",
                "@angular/core",
                "@angular/common",
                "@angular/router",
                "nativescript-angular/platform-static",
                "nativescript-angular/router",
            ],
            projectRoot,
            webpackConfig: config,
        }));
    }

    if (hmr) {
        config.plugins.push(new webpack.HotModuleReplacementPlugin());
    }

    return config;
};

**Comment by DimitarTachev** [comment]
Hi @Falu-G,

This support should be handled in the nodeify plugin itself, please follow the thread in the plugin's repository - https://github.com/EddyVerbruggen/nativescript-nodeify/issues/35
