### ISSUE TITLE
tns publish ios provisionin profile problem

### ISSUE THREAD

**Issue by oncul** [NativeScript/nativescript-cli#5029]
**Environment**
✔ Component nativescript has 6.2.0-2019-08-30-142210-13830 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
✔ Component tns-android has 6.1.1 version and is up to date.
✔ Component tns-ios has 6.1.1 version and is up to date.

XCode Version: 11.0 (11A420a)

**Describe the bug**

I am running this command

`tns publish ios [username] [password] --appleApplicationSpecificPassword [appspecpass]
`
I tried automatic and manuel signing. recrated provisonin profile but i got same error.

`Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.xxxx.xxxx' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'com.xxxxx.xxxxx' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.xxxxx.xxxxx'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}`

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by Fatme** [comment]
Hey @oncul,

Sorry for the late reply.

It seems you don't have `Distribution` certificates installed on your machine.  In order to check if this is the case, you can execute `security find-key | grep Distribution`. If this is not the case, try to provide the provision directly to publish command:
```
tns publish ios [username] [password] --provision <your provision id> --appleApplicationSpecificPassword
```

**Comment by madmas** [comment]
* after upgrading to the latest xcode, the problem persits.
* using the latest 6.2.0 does not help.

**Comment by madmas** [comment]
I just verified this with NativeScript 6.3.3, the problem still persists. 

The very same setup succeeds with TNS 6.1.0 .

Unfortunately, this is blocking any upgrades to newer versions of NativeScript.

As we are using a "Inhouse-Distribution certificate", I suspect this problem to be related to this. Unfortunately, I haven't found any point to dig deeper into this.

**Comment by madmas** [comment]
This problem still persisted with the release of TNS 6.4.

But we were finally able to sort it out: In addtion to 
`PROVISIONING_PROFILE = <UUID>`
we needed to add
`PROVISIONING_PROFILE_SPECIFIER = Profile Name as it is listed on Apple Developer Portal`
to the build.xcconfig file to get a project generate from `tns prepare` that builds our app again.

So from my perspective, it looks like this issue could be solved, finally. If you want, feel free to close this, @Fatme
