### ISSUE TITLE
ios build fails

### ISSUE THREAD

**Issue by terion-name** [NativeScript/nativescript-cli#503]
I try to build demo app and get the following:

** BUILD FAILED **
The following build commands failed:
        GenerateDSYMFile build/emulator/app.app.dSYM build/emulator/app.app/app
(1 failure)
Command xcodebuild failed with exit code 65

I have latest version of xcode, xcode clt and nativescript. Some time earlier (a month ago maybe) app was built successfully.

**Comment by Fatme** [comment]
Hi @terion-name,

Does building project from Xcode work? (You can open .xcodeproj file that is located at `platforms/ios/<your project name.xcodeproj`).

**Comment by terion-name** [comment]
Hi @Fatme. Also fails

**Comment by terion-name** [comment]
Xcode build:

enerateDSYMFile /Users/terion/Library/Developer/Xcode/DerivedData/app-cobjmbinqkvxgbextjraqvefarvh/Build/Products/Debug-iphonesimulator/app.app.dSYM /Users/terion/Library/Developer/Xcode/DerivedData/app-cobjmbinqkvxgbextjraqvefarvh/Build/Products/Debug-iphonesimulator/app.app/app
    cd /Volumes/HDD/work/botan/app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/terion/Library/Developer/Xcode/DerivedData/app-cobjmbinqkvxgbextjraqvefarvh/Build/Products/Debug-iphonesimulator/app.app/app -o /Users/terion/Library/Developer/Xcode/DerivedData/app-cobjmbinqkvxgbextjraqvefarvh/Build/Products/Debug-iphonesimulator/app.app.dSYM

error: unable to open executable '': Is a directory

**Comment by Fatme** [comment]
I suggest you to delete the content of `DerivedData folder - /Users/terion/Library/Developer/Xcode/DerivedData/`  and try again.

**Comment by terion-name** [comment]
@Fatme didn't help (

**Comment by toddanglin** [comment]
Problem happened for me, too, with latest NS v1.1.0.

Looking at the logs, it seems folders in the path to the project directory with spaces in the name caused the build to fail. Removing the spaces in the folder names/path fixed the build. Here was the error:

*PhaseScriptExecution Generate\ Metadata build/NSTest.build/Debug-iphonesimulator/NSTest.build/Script-C97FD7AC1ADE5369004DB2A4.sh
    cd "/Users/toddanglin/git/Scratch Projects/NativeScript 1_1_0 Test/NSTest/platforms/ios"
    /bin/sh -c \"/Users/toddanglin/git/Scratch\ Projects/NativeScript\ 1_1_0\ Test/NSTest/platforms/ios/build/NSTest.build/Debug-iphonesimulator/NSTest.build/Script-C97FD7AC1ADE5369004DB2A4.sh\"
Generating metadata for i386:
metadata-generation-build-step.sh: line 7: $errorLog: ambiguous redirect
cat: /Users/toddanglin/git/Scratch: No such file or directory
cat: Projects/NativeScript: No such file or directory
cat: 1_1_0: No such file or directory
cat: Test/NSTest/platforms/ios/build/emulator/metadata-generation-stderr-i386.txt: No such file or directory*

As you can see, the metadata script was failing by looking for bad directory names.

**Comment by terion-name** [comment]
@toddanglin great suggest, but I have no spaces in paths =(

**Comment by Fatme** [comment]
@terion-name Can you try to create a new project and build it?
@toddanglin It seems that this is a bug with latest runtime. I've logged the issue - https://github.com/NativeScript/ios-runtime/issues/192
