### ISSUE TITLE
tns devices lists appletv as iOS platform

### ISSUE THREAD

**Issue by manijak** [NativeScript/nativescript-cli#5030]
**Environment**
 - CLI: 6.1.2

**Describe the bug**
Running the command `tns devices` lists my wifi-connected AppleTv as a iOS platform device. 

**Expected behavior**
Should be marked as a `tvOS`device so that build & run commands ignore it.

**Additional context**
I usually use `tns run ios` when testing my apps on simulator as I know that's the only device. But recently I noticed errors in the log stating that it failed to upload and run the app on a additional device. Found out that was my living room AppleTV. 

![tns_cli_tvos](https://user-images.githubusercontent.com/3605066/65390893-f779d100-dd62-11e9-9941-1f6bccac5f63.png)

**Comment by DimitarTachev** [comment]
Hi @manijak,

Thanks for reporting it!

A fix should be available in the `next` version of the NativeScript CLI. Could you try the following steps and update us back:

1) `> npm i nativescript@next -g`
2) `> tns devices`

> The fix will be officially released in NativeScript@6.2.0.
