### ISSUE TITLE
Android App Bundle Improvements

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#5049]
**Is your feature request related to a problem? Please describe.**
The Android App Bundle (+ snapshot and libs) is not well-documented and it requires a few manual steps.

**Describe the solution you'd like**
The Android App Bundle should be fully automated and well-documented.

**Comment by DimitarTachev** [comment]
Acceptance Criteria (should be tested in a newly created JavaScript app):

- [ ] The old `useLibs` SnapshotPlugin setting should be exposed as  `--env.compileSnapshot`
- [ ] The Android NDK should not be required in the `webpack.config` when providing `--env.compileSnapshot`. We should support the following installations:
1) From the `webpack.config` (backwards compatibility)
2) When the ANDROID_NDK_HOME env variable is set
3) `ndk-build` available globally (ndk home dir is in PATH)
4) Downloaded through Android Studio.
- [ ] The used `ndk-build` should be logged to the console (one of the 4 locations mentioned in the above AC).
- [ ] If the locally available `ndk-build` revision is different than the one used in the Android Runtime, a warning should be shown without exiting the build.
- [ ] If the `ndk-build` is used globally from PATH, an `unknown version` info message should be shown without exiting the build.  
- [ ] Providing `--env.snapshot`, `--end.compileSnapshot` and `--aab` should be the minimum setup of running the app if the Android NDK is locally available and `tns-android` >= 6.2.0.
- [ ] Before `tns-android@6.2.0`, the  `sourceSets` section of `App_Resources/android/app.gradle` should still be required.
- [ ] Specifying architectures will be supported in the `App_Resources/android/app.gradle` by providing `android.defaultConfig.ndk.abiFilters` and it should be described in the docs.
- [ ] The `--aab` should be supported on `tns run` and `tns deploy` with `--release`.
- [ ] The `--aab` should be supported on `tns cloud run --release` with an additional JAVA requirement.

**Comment by endarova** [comment]
#https://github.com/NativeScript/nativescript-cli/issues/5089
