### ISSUE TITLE
Unable to compile Typescript to a single file

### ISSUE THREAD

**Issue by Alphapage** [NativeScript/nativescript-cli#505]
Hello,

I'm trying to compile my .ts files to a single .js file using --out command from tsc.
It generates a blank .js file without any error??? 
I use tsc 1.5.0.

Thanks in advance for your answer.

**Comment by Fatme** [comment]
Hi @Alphapage,

Can you send us the exact command that you try to execute?

**Comment by Alphapage** [comment]
Hello @Fatme,

dir *.ts /b /s > ts-files.txt 
tsc --module commonjs --target ES5 @ts-files.txt --out appSingle.js

It was giving me errors in android17.d.ts and ios.d.ts : invalid use of arguments, but replacing all "arguments" by "args" did the trick. I was able to run the app without using the --out parameter.

Maybe I'm doing something wrong to generate a single .js file.
