### ISSUE TITLE
Could not load CSS from app.css - SCSS app error on tns preview

### ISSUE THREAD

**Issue by agims7** [NativeScript/nativescript-cli#5051]
**Environment**
```JSON
{
  "name": "sass-project",
  "nativescript": {
    "id": "org.nativescript.sassproject",
    "tns-ios": {
      "version": "6.2.0"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android",
    "ios": "tns run ios",
    "mobile": "tns run",
    "preview": "tns preview"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "core-js": "^2.5.4",
    "nativescript-angular": "~8.0.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular-devkit/build-angular": "~0.800.0",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.0.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "node-sass": "^4.7.1"
  }
}
```
_**Updated package.json at 14.11.2019**_

**Describe the bug**
I have create new project with official documentation instruction -> `ng new -c=@nativescript/schematics sass-project --shared --style=scss` than once I run 'tns preview' there is an error in concole -> 

`CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:174:22: Error: Could not load CSS from app.css: TypeError: Expected module identifier to be a string.`

**Comment by endarova** [comment]
Hi @agims7 , 
I am not able to reproduce the described issue with the latest @nativescript/schematics and latest Preview application. Can you please try to update and if you still experience such problems provide additional steps to reproduce if possible.

**Comment by agims7** [comment]
Hi @endarova I updated NS to the latest 6.2 version and again run `ng new -c=@nativescript/schematics sass-project --shared --style=scss` than once again i run `tns preview` and I have got ->

`Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (ios)
Start sending initial files for platform ios.
Successfully sent initial files for platform ios.
LOG from device iPhone (Michał): CONSOLE INFO file:///app/vendor.js:130:36: HMR: Hot Module Replacement Enabled. Waiting for signal.
LOG from device iPhone (Michał): 
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:25777:18: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
LOG from device iPhone (Michał): 
CONSOLE ERROR file:///app/tns_modules/@nativescript/core/trace/trace.js:174:22: Error: Could not load CSS from app.css: TypeError: Expected module identifier to be a string.`

**Comment by endarova** [comment]
Hi @agims7 ,
Have you updated the @nativescript/schematics also. Please try executing `npm i -g @nativescript/schematics@latest` and then the steps you describe and let us know if the issue persists.

**Comment by agims7** [comment]
@endarova yeap that was helpfull. problem solved. Thank you

**Comment by Etchington** [comment]
@endarova i have a related issue.

After generating the template project (tns create test --js) i renamed the app.css into app-root.css and set the applications css file in app.js via `application.setCssFileName("./app-root.css");`

When running the project with `tns run android` the error (JS: Error: Could not load CSS from app.css: Error: require's first parameter should be string.)

If an empty app.css is included then the error will not show up at app start.

I attached the sample project to reproduce the error.
[test.zip](https://github.com/NativeScript/nativescript-cli/files/3853257/test.zip)

**Comment by endarova** [comment]
Hi @Etchington,
The issue you are describing is logged here: https://github.com/NativeScript/nativescript-dev-webpack/issues/1079 . You can track the progress there, but  it should have no impact on the livesync  functionality or the application. If you experience any problems please log another issue providing as much details as possible.
