### ISSUE TITLE
Bluetooth stops working in background while cli running

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#5062]
Crazy bug right!

I am using latest cli 6.1.2, {N} 6.1.1 and a few plugins.

Now here what my app do:
- connect to a bluetooth screen
- show a chrono on it

I discovered a crazy bug while running on device.
- start my app with ```tns run ios```
- connect to my ble device
- start the chrono

Now everything work fine 
- turn the screen off
- chrono stops updating 
- in the console i still see all my bluetooth commands but nothing arrives on the screen

Now if i do CTRL+C to stop the ```tns``` command, everything comes back to normal! even with the screen still off.

This bug des not happen if i start my app manually.

I would suppose it has something to do with the way the cli reads logs from the device. Maybe it stops the bluetooth stack someway?

It  is not a critical bug as it wont happen in production but it is pretty annoying while working on a app working in the background like mine. It might also have other side effects than the one i have on bluetooth.

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
Thanks for the detailed description. We are not sure what might cause such unexpected behavior and we would like to investigate this case further, but we'll need your help. Can you send us a sample project reproducing the issue as I'm not sure we'll be able to prepare the same project on our side.

Meanwhile, just to check if the problem is related to the device logs, you can open `<cli installation dir>/node_modules/ios-device-lib/ios-device-lib.js` and find the `startDeviceLog` method:
```JavaScript
startDeviceLog(deviceIdentifiers) {
	this._getPromise(MethodNames.log, deviceIdentifiers, { shouldEmit: true, disregardTimeout: true, doNotFailOnDeviceLost: true });
}
```
And replace it with:
```JavaScript
startDeviceLog(deviceIdentifiers) {
	return Promise.resolve();
}
```

After that start `tns run ios` and try to reproduce the issue again.

Thanks in advance for your help.

**Comment by farfromrefug** [comment]
@rosen-vladimirov thanks for looking at this!
Now we can try and recreate a sample app. What would be the best way for you to communicate with a bluetooth device?
Are you ok with using your computer (macos would be best) as a bluetooth device (using noble) and connect to it with your mobile?
Need to see if that could work first but most part is already in the ```nativescript-bluetooth``` repo

**Comment by farfromrefug** [comment]
@rosen-vladimirov actually the issue came the use of another plugin and especially when a map view was presented while turning off the screen.
https://github.com/CartoDB/mobile-sdk/commit/c38cc22fa96cec15572101f1b7b1609915b03e5a
It is not happening anymore (at least right now) using their updated SDK. They fixed some synchronization issues when app getting paused.
It does not explain the link with ```nativescript-cli```, i mean why wasn't it happening when not running through cli? why was it suddenly starting to work when killing the cli while the screen was off?

Anyway it is fixed now so i will close that issue. If at one point you still want to investigate it let me know i think i can reproduce it now.
