### ISSUE TITLE
iOS 13 - webveiw session is getting lost or inactive

### ISSUE THREAD

**Issue by lsowmya** [NativeScript/nativescript-cli#5064]
**Environment**
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Xcode version 11.1.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.1.2 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
✔ Component tns-android has 6.1.2 version and is up to date.
✔ Component tns-ios has 6.1.1 version and is up to date.

**Describe the bug**
Issue with iOS active and inactive state.
We are using XXX app where we have 2Factor Authentication(2FA), 
After entering credentials on login screen, then opens 2FA screen where we get a notification, on clicking the notification on iphone screen - 2FA app gets opened, here we accept the request and again coming back to XXX app page is getting frozen, 
next step was to make API call to get tokens but its getting frozen here.
If we manually open 2FA apps and accept the request and come back to XXX app we are not facing any issue.

We are facing issue only when 2FA is automatically called on clicking on notification and XXX goes to suspend and after authentication is completed session is getting lost. 

**Package.json**
{
  "name": "XXX",
  "version": "1.0.0",
  "description": "A NativeScript-built iOS and Android app",
  "nativescript": {
    "id": "***************",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.1"
    }
  },
  "scripts": {
    "tslint": "tslint -p tsconfig.json",
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "e2e": "tsc -p e2e && mocha --opts ./e2e/config/mocha.opts",
    "watch-tests": "tsc -p e2e --watch",
    "update-app-ng-deps": "update-app-ng-deps",
    "ns-verify-bundle": "ns-verify-bundle",
    "update-ns-webpack": "update-ns-webpack"
  },
  "dependencies": {
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-floatingactionbutton": "^1.0.1",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "email-validator": "^1.0.7",
    "leo-profanity": "^1.2.5",
    "nativescript-angular": "^8.2.1",
    "nativescript-appavailability": "^1.3.1",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-fingerprint-auth": "^7.0.1",
    "nativescript-gif": "^4.0.1",
    "nativescript-grid-view": "^5.1.0",
    "nativescript-iqkeyboardmanager": "~1.2.0",
    "nativescript-ngx-slides": "^6.1.0",
    "nativescript-oauth2": "./nativescript-oauth2",
    "nativescript-open-app": "^0.2.0",
    "nativescript-social-share": "1.5.2",
    "nativescript-speech-recognition": "1.5.0",
    "nativescript-texttospeech": "./nativescript-texttospeech",
    "nativescript-themes": "^1.9.9",
    "nativescript-ui-chart": "5.0.0",
    "nativescript-ui-listview": "7.0.4",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-unit-test-runner": "0.7.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.1.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "@types/chai": "~4.1.3",
    "@types/mocha": "~5.2.1",
    "@types/node": "^7.0.5",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "codelyzer": "^3.0.1",
    "filewalker": "^0.1.3",
    "jasmine-core": "^2.6.2",
    "karma": "4.1.0",
    "karma-jasmine": "2.0.1",
    "karma-nativescript-launcher": "^0.4.0",
    "karma-webpack": "3.0.5",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-appium": "~4.0.6",
    "nativescript-dev-webpack": "^1.2.0",
    "tns-platform-declarations": "6.0.1",
    "tslint": "^5.11.0",
    "typescript": "~3.5.3"
  }
}

Any suggestions would greatly help.
Thanks in advance.

**Comment by NickIliev** [comment]
@lsowmya posting the issue in the `nativescript-oatuh2` is enough, so I am going to close this one as a duplicate to [https://github.com/alexziskind1/nativescript-oauth2/issues/69](https://github.com/alexziskind1/nativescript-oauth2/issues/69).

Keep in mind that without providing a test application that demonstrates the issue it would be hard for anyone to investigate what is causing this one.  Feel free to create a sample that illustrates the issue or to send me a test app (you can find me in the NativeScript community Slack channels - username: **niliev**)

**Comment by NickIliev** [comment]
[Track the original issue ](https://github.com/alexziskind1/nativescript-oauth2/issues/69)for more info about 2FA, MFA support in nativescript-oath2 plugin
