### ISSUE TITLE
`tns update next` doesn't work with CLI 6+

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#5072]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.x
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
The `tns update next` command throws the following error with 6.x version:
```
Failed to get template information for the specified version. Original error: Failed to get information for package: tns-template-blank-vue@next
```

However, it works fine with NativeScript CLI below 6.0.

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by kdagithub** [comment]
A similar error message occurs for the tns-template-hello-world@next:

Failed to get template information for the specified version. Original error: Failed to get information for package: tns-template-hello-world@next

**Comment by kokosky93** [comment]
Same problem here. I am trying to update from 6.0.1
