### ISSUE TITLE
[sporadic] unable to determine the bundle identifier of the application

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#5073]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.x
 - Cross-platform modules: **below 6.0.4**
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

Sometimes the following error is thrown and the application cannot be ran on simulator.

```
Unable to apply changes on device: FEE9701C-B925-4AF9-BCEC-862BEE21B4BA. Error is: Command xcrun with arguments simctl install FEE9701C-B925-4AF9-BCEC-862BEE21B4BA /Users/havaluova/Work/nativescript-cli/scratch/app542/platforms/ios/build/Debug-iphonesimulator/app542.app failed with exit code 22. Error output:
 An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
```

The `CFBundleIdentifier` property inside `Info.plist` is relying on `PRODUCT_BUNDLE_IDENTIFIER` environment variable: https://github.com/NativeScript/nativescript-cli/blob/2e7112fa20271fb226b011b1c5d973f777987905/lib/services/ios-project-service.ts#L419
Sometimes `PRODUCT_BUNDLE_IDENTIFIER` is not exported inside `.build_env_vars.sh` [on pre-build step](
https://github.com/NativeScript/ios-runtime/blob/master/build/project-template/internal/nativescript-pre-build#L3). This way, there isn't `CFBundleIdentifier` inside the produced `.Info.plist` file and the application throws the above mentioned error when installing on simulator.

The issue is sporadic and is reproducible only with `tns-core-modules` with version below `6.0.4`. This is due to the fact that a `Podfile` is added to `tns-core-modules`@6.0.4. This way, `.xcworkspace` is created instead of `.pbxproject` and it seems the Xcode build mechanism is totally different when using `.xcworkspace` and `.pbxproject`.
Also, we tried to delay the exporting of environment variables on `pre-build step` using `sleep 5s`. That fixes the problem and `PRODUCT_BUNDLE_IDENTIFIER` was exported.

**To Reproduce**
1. `tns create --js`
2. `npm i tns-core-modules@6.0.x` where x = 1, 2 or 3
3. `tns run ios`

**Workaround**
`npm i tns-core-modules@6.0.4`

**Comment by rosen-vladimirov** [comment]
Closing as it cannot be reproduced anymore.
