### ISSUE TITLE
NativeScript Plugins support

### ISSUE THREAD

**Issue by ligaz** [NativeScript/nativescript-cli#510]
This issue outlines the work breakdown for supporting [NativeScript Plugins in the CLI](https://github.com/NativeScript/NativeScript/issues/25)

### Plugin commands
- [x] `add` - will support everything `npm install` supports. Will save the installed plugin in `package.json`. The plugin itself will be installed in `node_modules`.
- [x] `remove` - will remove the plugin. Basically `npm uninstall ... --save` with some other magic.
- [x] `prepare` - hidden command that will do all the required mumbo-jumbo to install a plugin. Actually adding a plugin will be decomposed to `npm install` followed by `tns plugin prepare`

### Supported functionality
- [x] NPM based workflow.
- [x] `require` of JavaScript files from the plugin. `prepare` will ensure the script files are in the native platform `tns_modules` folder, so that they can be required. The `package.json` of the plugin should also be there in case there is a `main` declared.
- [x] Merging of native configuration files (`AndroidManifest.xml` and `Info.plist`)

## v1.2
- Ability to package native libraries and frameworks in the plugin.
  - Android
    - [x] Respect Android libraries added to `platforms/android`
    - [x] Respect jars added to `platforms/android/libs`
    - [x] Remove the library when removing the plugin
  - iOS
    - [x] Support for dynamic libraries (*.framework)

## v1.3
- [x] Support for Cocoapods (#729)
- [x] Support for new Android Library format (AAR)

## v1.4
- [x] Support for static iOS libraries

## v1.5

- [ ] Ability to package resources (images, xml files declaring native UI, etc.) in the plugin.
- [x] Ability to define plugin variables (ex: API keys that should be defined per plugin installation)

**Comment by valentinstoychev** [comment]
related:
https://github.com/NativeScript/nativescript-cli/issues/592
https://github.com/NativeScript/nativescript-cli/issues/591

**Comment by Plamen5kov** [comment]
I don't believe it's a good idea to:
`Ability to package resources (images, xml files declaring native UI, etc.) in the plugin.`
At least not directly. The preferred way is to have only an `.aar` file that includes all of the elements described above.
