### ISSUE TITLE
App restarts when changing platform specific scss file from other platform

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#5105]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0-rc
 - Cross-platform modules: 6.2.0-rc
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

The application is restarted when changing platform specific scss file from other platform. It shouldn't transfer any files in such a situation.

**To Reproduce**
1. `tns create ts_proj`  - choose ts tabs project 
2. `npm i tns-core-modules@rc --save --save-exact`
3. `npm i nativescript-dev-webpack@rc --save-dev --save-exact`
4. `./node_modules/.bin/update-ns-webpack --deps –configs` 
5.  `tns run android`

Change something in app.android.scss - the change is applied, no restart 

Change something in app.ios.scss - application restarts 

**Expected behavior**
The application shouldn't be restarted.

**Comment by DimitarTachev** [comment]
The issue is also reproducible by saving any file without changes (e.g. just save the `main-view-model.js` in a Hello World js app and the CLI will send `bundle.js` and restart the application).
