### ISSUE TITLE
Consider *.AAR files as Android Plugins

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/nativescript-cli#511]
_From @valentinstoychev_

This is the [Android Studio specific library format](http://tools.android.com/tech-docs/new-build-system/aar-format).

_Copied from original issue: https://github.com/NativeScript/android-runtime/issues/84_

**Comment by dtopuzov** [comment]
Will be implemented as part of https://github.com/NativeScript/nativescript-cli/issues/687
