### ISSUE TITLE
release need Docker after update to 6.2

### ISSUE THREAD

**Issue by elena-p** [NativeScript/nativescript-cli#5116]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.2
 - Cross-platform modules: 6.2
 - Android Runtime: 6.2
 - Plugin(s):
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-snackbar": "^1.0.0",
    "base-64": "^0.1.0",
    "email-validator": "^2.0.4",
    "guid-typescript": "^1.0.9",
    "nativescript-angular": "~8.2.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-plugin-firebase": "^10.0.1",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-listview": "^7.0.5",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "sha1": "^1.1.1",
    "tns-core-modules": "^6.2.0",
    "underscore": "^1.9.1",
    "utf8": "^3.0.0",
 - NativeScript-Angular: ~8.2
 - Angular: ~8.2

**Describe the bug**

When building the release, a message appeared

```
ERROR in NativeScriptSnapshot. Snapshot generation failed!
Docker installation cannot be found. Install Docker and add it to your PATH in order to build snapshots.
Executing webpack failed with exit code 2.
```

I deleted the parameter `--env.snapshot` and managed to collect the release.

In previous versions, this was not.
------------------
Logged from @Cheas
Duplicated from issue - https://github.com/NativeScript/nativescript-angular/issues/2054

**Comment by rosen-vladimirov** [comment]
Hey @Cheas, 
NativeScript CLI requires Docker for building snapshot when you try to build on macOS Catalina or newer. Due to Catalina's requirement for having only 64bits processes, the snapshot for 32bits architectures cannot run on Catalina. That's why we require Docker.
In case you are not using macOS Catalina, can you please provide more information for your setup?

**Comment by Cheas** [comment]
*ANDROID. not IOS*

PS C:\ProgramDataMy\CS\projects\sample-ns> tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 6.2.0 version and is up to date.
√ Component tns-core-modules has 6.2.0 version and is up to date.
√ Component tns-android has 6.2.0 version and is up to date.
√ Component tns-ios has 6.2.0 version and is up to date.

package.json:
{
  "nativescript": {
    "id": "org.chernikov.sampleNS",
    "templateVersion": "v2",
    "tns-ios": {
      "version": "6.2.0"
    },
    "tns-android": {
      "version": "6.2.0"
    }
  },
  "name": "sample-ns",
  "displayName": "sample-ns",
  "version": "1.0.0",
  "description": "Nativescript examples",
  "author": "Chernikov",
  "license": "Apache-2.0",
  "keywords": [
    "mobile",
    "angular",
    "nativescript",
    "{N}",
    "tns"
  ],
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-snackbar": "^1.0.0",
    "base-64": "^0.1.0",
    "email-validator": "^2.0.4",
    "guid-typescript": "^1.0.9",
    "nativescript-angular": "~8.2.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-plugin-firebase": "^10.0.1",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-listview": "^8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "sha1": "^1.1.1",
    "tns-core-modules": "^6.2.0",
    "underscore": "^1.9.1",
    "utf8": "^3.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.2.0",
    "@ngtools/webpack": "8.2.0",
    "codelyzer": "~5.1.2",
    "nativescript-dev-webpack": "~1.3.0",
    "tns-platform-declarations": "^6.1.1",
    "node-sass": "^4.12.0",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "scripts": {
    "release-android":
"tns build android --bundle --env.aot --env.uglify --env.snapshot
--release --key-store-path sampleNS.jks --key-store-password
Million35! --key-store-alias sampleNS --key-store-alias-password
Million35!"
,
    "lint": "tslint \"src/**/*.ts\""
  }
}

npm run release-android:
........
[image: image.png]

........


чт, 7 нояб. 2019 г. в 11:29, Rosen Vladimirov <notifications@github.com>:

**Comment by rosen-vladimirov** [comment]
Hey @Cheas ,
In the previous releases, the `snapshot` flag on Windows was stripped as there was no way to build snapshots on Windows. With the latest release, instead of stripping it, we've included a feature to be able to use snapshot on Windows via Docker.

So, in your case, the previous builds were not really using snapshots, but after updating to latest CLI, the build is actually trying to use snapshot. You can either remove `--snapshot` flag or install Docker and get the full benefits of the snapshot.

**Comment by rosen-vladimirov** [comment]
Hey @Cheas ,
As this change is intentional, I'm closing this issue. Feel free to reopen it in case you have any troubles with the usage.

**Comment by Cheas** [comment]
Hey, @Rosen Vladimirov.  
I can do without '--env.snapshot', this option did not work, it was just unexpected that the assembly did not work.  
Thanks for your attention.

**Comment by Omi231** [comment]
Can someone tell me how to install docker and use it on windows?

**Comment by MartinJHItInstituttet** [comment]
If you can live without the snapshot, a possible solution is to outcomment the snapshot code in `webpack.config.js`

```
    // if (snapshot) {
    //     config.plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
    //         chunk: "vendor",
    //         angular: true,
    //         requireModules: [
    //             "reflect-metadata",
    //             "@angular/platform-browser",
    //             "@angular/core",
    //             "@angular/common",
    //             "@angular/router",
    //             "nativescript-angular/platform-static",
    //             "nativescript-angular/router",
    //         ],
    //         projectRoot,
    //         webpackConfig: config,
    //     }));
    // }
```

### More info about snapshots

**Snapshot configuration**: https://docs.nativescript.org/performance-optimizations/bundling-with-webpack#snapshot-per-architecture

**What does snapshots do for your application**: https://docs.nativescript.org/performance-optimizations/startup-times#step-2

**Comment by JohanBeumer** [comment]
> You can either remove --snapshot flag or install Docker and get the full benefits of the snapshot.

Would it be possible for the cli to detect that Docker is not available in an earlier stage and then still strips the --snapshot flag to be able to continue building?

My gitlab pipeline uses a docker image that doesn't have docker and will never make it till the end of the build unless I remove the --snapshot flag. Instead of ending with an error I would rather have it finish with at least a valid apk.

**Comment by VeeK727** [comment]
I'm using Catalina, can you tell me how to install this dependency?
