### ISSUE TITLE
Support for incremental ANT builds for Android

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#512]
# Issue

Android build are unnecessary long: 12s or more.

tns build works by always overwriting files in the app directory and then spawning ant to do the actual building. This way ant always sees new files and cannot trigger an incremental build.

# Improvement strategies

We can improve the situation in two ways:

 * tns prepare become "smarter" and only copies files newer than existing apk. This makes tns dangerously close to a  build system which we should avoid.
 * instead of copying files into app, symlink them. This may have issues on Windows (see https://github.com/NativeScript/nativescript-cli/issues/282 ). In this way, prepare will just create symlinks for new files.

This issue supersedes https://github.com/NativeScript/android-runtime/issues/60 .

**Comment by dtopuzov** [comment]
The issue with incremental builds will be solved once https://github.com/NativeScript/nativescript-cli/issues/687 is implemented.
