### ISSUE TITLE
Detect that java8 is configured in $ nativescript doctor

### ISSUE THREAD

**Issue by jmfayard** [NativeScript/nativescript-cli#5127]
**Is your feature request related to a problem? Please describe.**

The doctor tells me that my system is ready to compile
```bash
$ nativescript doctor
 Getting environment information

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 11.1.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.2.0 version and is up to date.
✔ Component tns-core-modules has 6.2.0 version and is up to date.
✔ Component tns-android has 6.2.0 version and is up to date.
✔ Component tns-ios has 6.2.0 version and is up to date.
```

but actually this is wrong: 

```bash
$ java -version 
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190717_289 (JIT enabled, AOT enabled)
```

Building an Android APK requires Java 8 and do not work with Java 11

**Describe the solution you'd like**

Warns java-version is not java8

**Describe alternatives you've considered**

Fixing the Android build tools so that they support Java 11+

**Additional context**

Android supports only a very old version of Java. 

As a backend developer, I have a much newer version of Java installed for my newer project. 

I can switch between java8 and java11-12-13 using https://get.sdkman.io/

But I often forget. 

And then Gradle crashes.

**Comment by KristianDD** [comment]
Hi jmfayard,
Can you please provide the exact error you are getting when executing `tns build android`. A full trace log will also be very helpful:
- on MacOS and Linux:
`tns build android --log trace | tee log.txt`
- on Windows:
`tns build android --log trace > log.txt 2>&1`

The log will help us investigate the issue and make sure we are reproducing the same problem.

**Comment by jmfayard** [comment]
@KristianDD it's nothing specific to NativeScript. 
I have opened an issue on Gradle issue tracker because Kotlin / Android projects do not work with Java 11 / Java 13. I'm not sure who the culprit is. Gradle? Kotlin? Android?

See https://github.com/gradle/gradle/issues/11084

What is specific to NativeScript is that it would useful to emit a warning when a not supported version of Java is used.

**Comment by rosen-vladimirov** [comment]
Hey @jmfayard ,
In the latest CLI versions we've improved the detection for Java 13 and `tns doctor` fails in case you are using it. I'm closing this thread, but feel free to reopen it in case you think additional checks are required.
