### ISSUE TITLE
applyPluginsCocoaPods fails on case sensitive volumes

### ISSUE THREAD

**Issue by leevigraham** [NativeScript/nativescript-cli#5159]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.2
 - Cross-platform modules: 6.2.1 
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - Plugin(s): 

```$ tns plugin list
Dependencies:
┌──────────────────┬─────────┐
│ Plugin           │ Version │
│ nativescript-vue │ ^2.4.0  │
│ tns-core-modules │ ^6.2.1  │
└──────────────────┴─────────┘
Dev Dependencies:
┌────────────────────────────────────┬─────────┐
│ Plugin                             │ Version │
│ @babel/core                        │ ^7.0.0  │
│ @babel/preset-env                  │ ^7.0.0  │
│ babel-loader                       │ ^8.0.2  │
│ nativescript-dev-webpack           │ ^1.0.0  │
│ nativescript-vue-template-compiler │ ^2.0.0  │
│ nativescript-worker-loader         │ ~0.9.0  │
│ node-sass                          │ ^4.9.2  │
│ vue-loader                         │ ^15.4.0 │
└────────────────────────────────────┴─────────┘
```

**Describe the bug**
File: NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts 
Method: applyPluginsCocoaPods
Line https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts#L833

This method checks for the pluginPlatformsFolderPath  using the `normalizedPlatformName` which is [`iOS`](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-project-service.ts#L72)

In reality the folder names are lowercase:

* https://github.com/NativeScript/NativeScript/tree/master/nativescript-core/platforms/ios
* https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules-widgets/ios
* https://github.com/NativeScript/NativeScript/tree/master/tns-platform-declarations/ios

Example of a plugin:

* https://github.com/tjvantoll/nativescript-IQKeyboardManager/tree/master/src/platforms/ios
* https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/master/src/platforms/ios

**To Reproduce**

1. Create a new project on a case sensitive drive
2. run `tns platform add ios`
3. run `tns prepare ios`

Plugin Podfiles are not added.

**Expected behavior**

Plugin `Podfile` should be included

**Comment by leevigraham** [comment]
Looks like @Fatme and @KristianDD worked on some of this code.

**Comment by leevigraham** [comment]
Related: 

* https://github.com/NativeScript/nativescript-cli/pull/3045 
* https://github.com/NativeScript/nativescript-cli/issues/3091

**Comment by rosen-vladimirov** [comment]
Hey @leevigraham ,
Thanks for reporting this issue. A fix is available in our `next` version and should be live when we release 6.3.0 release.
Meanwhile you can give it a try by installing the `next` version of CLI: `npm i -g nativescript@next`.
