### ISSUE TITLE
hmr stops reloading in second run

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/nativescript-cli#5162]
**Environment**
 - CLI: 6.1
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2

**Describe the bug**
When I run a tns app to my device, hmr works fine and refreshes the page after making some changes. But if I close the app, and close the cli as well, then run the app again, in that case, it doesn't refresh the app by making some changes.

**Expected behavior**

To refresh the app.

**Comment by rosen-vladimirov** [comment]
Hey @vahidvdn ,
Can you try installing the `next` version of nativescript-dev-webpack (`npm i --save-dev nativescript-dev-webpack@next`) and see if it resolves the issue on your side? I think you may have hit this issue: https://github.com/NativeScript/nativescript-dev-webpack/issues/1082

**Comment by sebj54** [comment]
Has this issue on first run, I updated Nativescript, platforms and nativescript-dev-webpack and it's working fine now. Thanks!

Here are the commands to execute:

```
npm i -g nativescript
npm i tns-core-modules@latest
nativescript update platform android
nativescript update platform ios
npm i nativescript-dev-webpack@latest
```
