### ISSUE TITLE
Cryptic message when no platform added

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#518]
If you don't add a platform first you get cryptic messages instead of one explaining you forgot to add any platforms. 

tns create MyApp
tns run MyApp

result:

shell.js: internal error
xxxxx

**Comment by teobugslayer** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/475

**Comment by vchimev** [comment]
This issue is no more relevant since we "add platform on each platform related command" - https://github.com/NativeScript/nativescript-cli/issues/785.
