### ISSUE TITLE
packageName should support dashes in names

### ISSUE THREAD

**Issue by nrevutsky** [NativeScript/nativescript-cli#5190]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.0
 - Plugin(s):

**Describe the bug**
Running 
`tns build android --env.production --env.uglify --env.snapshot --env.aot`
generate 

> Package name must look like: com.company.Name

error

**To Reproduce**
In package.json use provide application id with dashes, e.g.
{
  "nativescript": {
    "id": "com.company-name.application",
...
}

**Expected behavior**
Application should be build w/o errors

**Additional context**
Dashes are allowed in urls and for native android applications.

**Comment by NickIliev** [comment]
@nrevutsky  see [this documentation article](https://developer.android.com/studio/build/application-id). 

> And although the application ID looks like a traditional Java package name, the naming rules for the application ID are a bit more restrictive:
> 
> It must have at least two segments (one or more dots).
> Each segment must start with a letter.
> All characters must be alphanumeric or an underscore [a-zA-Z0-9_].

So that said, the dash is not supported for package name in Android.
