### ISSUE TITLE
`tns info` command does not work with @nativescript/core

### ISSUE THREAD

**Issue by shiv19** [NativeScript/nativescript-cli#5192]
**Environment**
 - CLI: 6.3.0
 - Cross-platform modules: 6.3.2
 - Android Runtime: 6.3.0
 - iOS Runtime: 6.3.0

**Describe the bug**
tns info command does not work in a project that uses `@nativescript/core` instead of `tns-core-modules`

**To Reproduce**
Try running `tns info` in a project that uses `@nativescript/core` instead of `tns-core-modules`

**Expected behavior**
Expect it to show version information.

**Comment by NickIliev** [comment]
@shiv19 thanks for reporting this one! Confirming that the issue appears with `tns info` and with `tns doctor` commands when using a project with CLI 6.3.0 and only the scoped core package (no `tns-core-modules`)
