### ISSUE TITLE
Regex issue - lookbehind assertions not supported

### ISSUE THREAD

**Issue by zcaudate** [NativeScript/nativescript-cli#5196]
**Environment**

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: XCode V11.3
 - Plugin(s):

**Describe the bug**

```
Entrypoint bundle = runtime.js bundle.js
Entrypoint tns_modules/tns-core-modules/inspector_modules = runtime.js vendor.js tns_modules/tns-core-modules/inspector_modules.js
[./app.js] 563 bytes {bundle} [built] [failed] [1 error]
[./package.json] 99 bytes {tns_modules/tns-core-modules/inspector_modules} [optional] [built]
    + 254 hidden modules

ERROR in ./app.js
Module build failed (from ../node_modules/nativescript-dev-webpack/bundle-config-loader.js):
SyntaxError: Unsupported regular expression /(?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$/: TRegex: body of lookbehind assertion too complex; Joni: quantifiers inside lookbehind assertions not supported
    at new RegExp (native)
    at Object.loader (/Users/chris/Development/caudata/statstrade/statstrade-mobile/node_modules/nativescript-dev-webpack/bundle-config-loader.js:15:27)
Executing webpack failed with exit code 2.
```

**To Reproduce**

```
tns create app
cd app
tns prepare ios
```

**Expected behavior**

Expected it to compile

**Comment by rosen-vladimirov** [comment]
Hey @zcaudate ,
It seems your Node.js version is very old and it does not support some of the regular expressions required for our webpack compilation.
Can you try installing latest Node.js LTS version and see if it resolves the issue?

**Comment by zcaudate** [comment]
@rosen-vladimirov. Thanks for that. The problem went away after installing node 13. I was on node 12 before but that error came up only on the newly created ones - but not the samples on the marketplace. Strange but it's solved.
