### ISSUE TITLE
Support build hooks

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#5205]
**Is your feature request related to a problem? Please describe.**
We are not able to implement something like a cloud builds solution based on CLI hooks.

**Describe the solution you'd like**
We could expose a "build" hook in order to allow overriding the CLI logic with a custom one.

**Comment by rosen-vladimirov** [comment]
A sample demonstrating the hooks usage can be found here: https://github.com/rosen-vladimirov/app-build-hooks
