### ISSUE TITLE
Can't Add A View For Fourth Tab

### ISSUE THREAD

**Issue by JimLynchCodes** [NativeScript/nativescript-cli#5228]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

tns info:
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.3.3 version and is up to date.
✔ Component tns-core-modules has 6.3.2 version and is up to date.
✔ Component tns-android has 6.3.1 version and is up to date.
✔ Component tns-ios has 6.3.0 version and is up to date.

**Describe the bug**

I scaffolded a new "Angular Tabs" NativeScript application, but I cannot add a page for a fourth tab. I added in the code for the new tab, added in all the routing code, and created the component for the page, but it always goes to just a blank page....

![Screen Shot 2020-01-25 at 11 51 40 PM](https://user-images.githubusercontent.com/5354163/73130843-65166200-3fce-11ea-8494-8830fc84d241.png)

**To Reproduce**

Scaffold a new project with `tns create` and try to add a fourth tab page.

**Expected behavior**
Fourth page should load.

**Sample project**

Having this issue in both of the projects here: https://github.com/JimLynchCodes/Fun-With-NativeScript-2020

**Additional context**

**Comment by Fatme** [comment]
Hey @JimLynchCodes,

1. You need to add your settings tab [here](https://github.com/JimLynchCodes/Fun-With-NativeScript-2020/blob/master/my-test-app/src/app/app-routing.module.ts#L9):
```
redirectTo: "/(homeTab:home/default//browseTab:browse/default//searchTab:search/default//settingsTab:settings/default)",
```

2. You need to change [this path](https://github.com/JimLynchCodes/Fun-With-NativeScript-2020/blob/master/my-test-app/src/app/settings/settings-routing.module.ts#L8) with the following:
```
const routes: Routes = [
    { path: "default", component: SettingsComponent }
];
```

**Comment by JimLynchCodes** [comment]
Thanks @Fatme !

I have made nyour edits, but it doesn't seem to help the issue at all. The settings view still looks like a completely blank page rather than what is defined for it in `settings.component.html` (please see the project in the `my-fun-2` folder).

**Comment by Fatme** [comment]
It seems that there are 2 problems:

1. `JS: ERROR Error: Uncaught (in promise): Error: Type SettingsComponent is part of the declarations of 2 modules: AppModule and SettingsModule! Please consider moving SettingsComponent to a higher module that imports AppModule and SettingsModule. You can also create a new NgModule that exports and includes SettingsComponent then import that NgModule in AppModule and SettingsModule.`

You need to delete the declaration of `SettingsComponent` from within `AppModule` e.g you need to delete [this line](https://github.com/JimLynchCodes/Fun-With-NativeScript-2020/blob/master/my-fun-2/src/app/app.module.ts#L18).

2. `ERROR in ./app/settings/settings.component.ts
Module not found: Error: Can't resolve './settings.component.css' in '/Users/fatme/Work/Fun-With-NativeScript-2020/my-fun-2/src/app/settings'
 @ ./app/settings/settings.component.ts 11:21-56
 @ ./app/app.module.ts
 @ ./main.ts`

It seems that `./settings.component.css` file doesn't exist so just delete its reference from `settings.component.ts` [here](https://github.com/JimLynchCodes/Fun-With-NativeScript-2020/blob/master/my-fun-2/src/app/settings/settings.component.ts#L6).

**Comment by JimLynchCodes** [comment]
THANK YOU! ❤️

How were you able to see those errors?

Thanks

**Comment by Fatme** [comment]
The errors are printed on the console when executing `tns run android` command. The first one is a runtime error while the second one is a compile time error.

**Comment by JimLynchCodes** [comment]
ah ok, thanks.  👍
