### ISSUE TITLE
Omit files when copying into app 

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#5231]
Right now when i build an app for testflight i want to generate source maps so that i can upload them to Sentry. However i dont need nor want (bigger ipa) those files to be part of the ipa.
I think it could be fairly easy to do by not copying them from `platforms/ios/AppName/app` to the build folder.
Could you guide where this is done in the CLI.
I could then create a pull request.

**Comment by Fatme** [comment]
By default source maps are inlined into produced files from webpack compilation(`bundle.js`, `vendor.js`). You can specify [`--env.hiddenSourceMap <path to folder>`](https://github.com/NativeScript/nativescript-dev-webpack/blob/c2e20118269da499fa125f05829e2f7d26a23504/templates/webpack.javascript.js#L135) option and this way the source maps will be outputted to the provided `<path to folder>`:
```
tns build ios --env.hiddenSourceMap ./source-maps
```

**Comment by farfromrefug** [comment]
@Fatme sorry forgot to mention i was not using inline!
I still thing this would be a great feature to have. CAn you guide me on where the copy happens?

Will test the hiddenSourceMap. Thanks!

**Comment by Fatme** [comment]
> CAn you guide me on where the copy happens?

Actually CLI doesn't copy any JavaScript files. The webpack compilation produces the needed files inside the [output directory](https://github.com/NativeScript/nativescript-dev-webpack/blob/c2e20118269da499fa125f05829e2f7d26a23504/templates/webpack.javascript.js#L103) (for example, inside [`platforms/ios/appName/app`](https://github.com/NativeScript/nativescript-dev-webpack/blob/81ac4aa30136a9145803d97a0adb8320cda4d18e/index.js#L103)). CLI takes care only to start the [webpack compilation](https://github.com/NativeScript/nativescript-cli/blob/732f1a0c3aa7fa293ef74d8957642077022f8482/lib/services/webpack/webpack-compiler-service.ts#L181).

There is a mechanism [to ignore particular files from being copied](https://github.com/NativeScript/nativescript-dev-webpack/blob/c2e20118269da499fa125f05829e2f7d26a23504/templates/webpack.javascript.js#L233) during webpack compilation. So webpack ignores the files inside `App_Resources` folder as CLI handles them in a slightly different way.

**Comment by farfromrefug** [comment]
@Fatme ok got it. Hidden sourcemap was not possible for me. However seeing how you do it with hidden sourcemap i translated it for it to work with normal source maps.

Thanks again for your explanations!
