### ISSUE TITLE
custom file prefix in error stack

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#5236]
When you "translate" an error stack line with source maps [here](https://github.com/NativeScript/nativescript-cli/blob/4fa7e65071bb527a3b3784b1be79dd3d019667e4/lib/services/log-source-map-service.ts#L86) you add a `file:///` prefix to the file path.
This makes it impossible to use "CTRL+Click" to open the file at line/column which would be incredibly useful.
I dont know why you do this but i suppose it is to get this to work on another IDE.

Can you make this customizable ?

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
Thanks for pointing this UX problem, I've created a PR to replace the `file:///` with `file: ` when CLI prints the logs. 
We've tried to persist the same output coming from the device itself, that's why we've kept the `file:///` until now. However, we've discussed your suggestion and we've decided to implement it as it will be really useful for everyone. Thanks for the idea.

**Comment by farfromrefug** [comment]
@rosen-vladimirov thanks! do you know if `file:` works with vscode? if not would be good for it to be "customizable"

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
I've used `file: ` (note the space at the end), just to keep the output as similar as possible to the current one.
I've also tested it in VSCode's terminal and I was able to click on the link and it navigated to the correct file and even the exact line.

**Comment by dtopuzov** [comment]
Available in `nativescript@rc`, will be shipped with `nativescript@64.1`.

**Comment by farfromrefug** [comment]
@rosen-vladimirov Seems to be good but not completely:
<img width="971" alt="Screen Shot 2020-02-24 at 14 32 54" src="https://user-images.githubusercontent.com/655344/75156574-b0797880-5712-11ea-9fe6-e0c69178e02e.png">
I don't know why the `Object.p ...` is still using `file:///`

**Comment by farfromrefug** [comment]
@rosen-vladimirov found another issue
<img width="1243" alt="Screen Shot 2020-02-25 at 14 16 17" src="https://user-images.githubusercontent.com/655344/75250846-98b8f780-57d9-11ea-96d4-a0c9076fbb5b.png">
the file in webpack is `../../src/opencv.android.ts`. Though the cli still adds `app/` in front so vscode cant pick up the link
