### ISSUE TITLE
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

### ISSUE THREAD

**Issue by Sh031224** [NativeScript/nativescript-cli#5246]
Searching for devices...
Preparing project...
Bundling application for entryPath .\main...
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 42a5f273ac6f6be8a3e5
Version: webpack 4.27.1
Time: 11983ms
Built at: 2020-02-09 6:55:59
```
                             Asset       Size   Chunks             Chunk Names
assets/images/NativeScript-Vue.png   8.22 KiB           [emitted]
                         bundle.js    355 KiB   bundle  [emitted]  bundle
                      package.json  166 bytes           [emitted]
                        runtime.js   71.4 KiB  runtime  [emitted]  runtime
               tns-java-classes.js    0 bytes           [emitted]
                         vendor.js   8.55 MiB   vendor  [emitted]  vendor
```
Entrypoint bundle = runtime.js vendor.js bundle.js
```
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 175 bytes {bundle} [built]
[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 189 bytes {bundle} [built]
[./app.scss] 120 KiB {bundle} [optional] [built]
[./main.js] 1.82 KiB {bundle} [built]
[./package.json] 147 bytes {bundle} [optional] [built]
    + 333 hidden modules
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Building project...
Gradle build...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Sh031224\Desktop\프로젝트\ns-vue-weather\platforms\android\app\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Your project path contains non-ASCII characters. This will most likely cause the build to fail on Windows. Please move your project to a different directory. See http://b.android.com/95744 for details. This warning can be disabled by adding the line 'android.overridePathCheck=true' to gradle.properties file in the project directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

Please help me!

**Comment by NickIliev** [comment]
@Sh031224 

The error speaks for itself:
```
Your project path contains non-ASCII characters. 
```

Seeing the path you should p[ropbably rename the `프로젝트` part in
`C:\Users\Sh031224\Desktop\프로젝트\ns-vue-weather\` - use ASCII characters only in your path.
