### ISSUE TITLE
External files are not livesynced

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#5251]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules: Not applicable
 - Android Runtime: Not applicable
 - iOS Runtime: Not applicable
 - Plugin(s): Not applicable

**Describe the bug**
In case you have defined externals in your webpack.config.js, changing the code in those externals is not livesynced, so the changes are not visible on device. You have to restart the command to apply the changes, which makes the process slow.

**To Reproduce**
Use the project here - https://github.com/rosen-vladimirov/appWebpackExternalsIssue - check the README for description.

**Expected behavior**
Changes in externals must be visible and should not require restart of CLI command.

**Sample project**
https://github.com/rosen-vladimirov/appWebpackExternalsIssue

**Additional context**
Fix may result in regression in https://github.com/NativeScript/nativescript-cli/issues/5105

**Comment by dtopuzov** [comment]
Fix available in `nativescript@rc`, will be shipped with `nativescript@6.4.1`
