### ISSUE TITLE
Warn if the CLI might print sensitive data to the output

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-cli#5255]
**Is your feature request related to a problem? Please describe.**
The users could leak some sensitive data like secrets when they share their logs with TRACE level.

**Describe the solution you'd like**
We could warn them when the log level is set to TRACE

**Describe alternatives you've considered**
We could try to detect the secrets and replace them with * but I don't believe its possible to cover everything with regexes.

**Additional context**
The easiest way to leak a secret is by using it in a request query param.

**Comment by dtopuzov** [comment]
Available in `nativescript@rc`, will be shipped with `nativescript@64.1`.
