### ISSUE TITLE
Update plugin command

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#526]
## Scenario
Plugin `A` is installed with version 1.0.0. After some time, a new version is released. We need an easy way to install the new version of the plugin. Using `tns plugin add A` is telling me that the plugin is already installed.

## Possible solutions
* `tns plugin add A` should update the version of the plugin to its latest one.
* `tns plugin update A` should update the plugin A to its latest version.
* `tns plugin update` could update all plugins to their latest versions.

## Workaround
By default adding plugin with `tns plugin add <plugin name>` adds it to package.json with "^\<version\>". This way, if you execute `npm install` in your project directory, the plugin in node_modules will be the latest one.
Also you can remove the plugin with `tns plugin remove A` and add it again with `tns plugin add A`. This way, plugin add command will use the latest version of the plugin.

**Comment by atanasovg** [comment]
+1 for this feature, without it it is a bit tedious to incrementally develop and test a plugin.
