### ISSUE TITLE
Better way of previewing app

### ISSUE THREAD

**Issue by xhostcom** [NativeScript/nativescript-cli#5268]
**Is your feature request related to a problem? Please describe.**
 
Yes the Playground app on Android does not work very well, it doeant go in to scan mode to scan the bar code? Had to stop project because I just cant see it. The emulator is very resource heavy and slow, so dont use that, use Sidekick,local and Circle CI with preferably viewer on Android device but cant get it to work. is there any other way? Thanks
**Describe the solution you'd like**

See above
**Describe alternatives you've considered**

Tried the emulator, a bit slow and resource heavy, nothing else works on computer when it is running so cant do anything.
**Additional context**

**Comment by NickIliev** [comment]
@xhostcom the Playground is working great but has its own limitation (you can use only the se of plugin that are provided in the preview app - for anything else you need to provide the whole plugin source code inside the Playground app directory).

We are currently **not** planning to provide any other options apart from the native ones (emulators, simulators, real devices) and the Playground
