### ISSUE TITLE
is it possible to create project offline?

### ISSUE THREAD

**Issue by ejamshidiasl** [NativeScript/nativescript-cli#5269]
hello
i cannot connect to internet with my laptop in sometimes so i need to create project when i am offline like android studio or react native. is there any way to create project offline?(load project template from local?)

**Comment by DimitarTachev** [comment]
Hi @ejamshidiasl,

This is not officially supported but it is possible if you have the template dependencies in your local npm cache.

I suggest you execute the following steps online and if your npm cache is working properly, you will be able to execute them offline afterward:

1) Clone the app templates repository - https://github.com/NativeScript/nativescript-app-templates
2) Execute `npm pack` in the desired app template directory (e.g. `packages/template-hello-world`).
3) Copy the path to the generated `tgz` file.
4) Execute `ns create offlineTest --template /the/path/to/the/generated/tgz/file`
