### ISSUE TITLE
Use build configurations for plugins

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#527]
## Scenario
During project development every developer use some plugins to simplify the debugging of the application. However most of them cannot be used in release configuration and when the app is uploaded to AppStore. Currently all plugins are added as dependencies in project's package.json. The only way to remove them from release build is to remove the plugin: `tns plugin remove <plugin name>`

### Project's package.json
Add "debug" and "release" keys inside nativescript key of project's package.json.
```JSON
"nativescript": {
          "id": "org.nativescript.app1",
          "tns-android": {
                  "version": "1.0.0"
          },
          "debug": [ "plugin1", "plugin2", "plugin3" ],
          "release": [ "plugin2", "plugin3", "plugin4" ]
  }
"dependencies": {
         "plugin1": "^1.0.0",
         "plugin2": "^1.0.0",
         "plugin3": "^1.0.0",
         "plugin4": "^1.0.0",
}
```
When plugin add command is used, you can specify `--debug` or `--release` and this should add the plugin to the respective configuration, for example:
`tns plugin add plugin1 --debug` - this should add the plugin in dependencies section and in `nativescript.debug` key.
When plugin remove command is used, you can specify `--debug` or `--release` and this should remove the plugin from the specified configuration, for example:
`tns plugin remove plugin1 --debug` - this should remove the plugin from `nativescript.debug` key, but it should not be removed from dependencies.

### Plugin's package.json
Add `configurations` key to plugin's package.json and specify for which configuration you would like your plugin to be available. In case configurations section is missing, plugin will be available for both debug and release configurations.
```JSON
{
  "name": "plugin1",
  "version": "1.0.0",
  "main": "index.js",
  "nativescript": {
    "platforms": {
      "ios": "0.1.1",
      "android": "0.1.0"
    },
    "configurations": [ "debug" ]
  }
}
```
When user tries to add plugin1, the following behavior is expected:
* `tns plugin add plugin1` - adds plugin1 to dependencies and nativescript.debug section
* `tns plugin add plugin1 --debug` - adds plugin1 to dependencies and nativescript.debug section
* `tns plugin add plugin1 --release` - throws error that this plugin cannot be added to release configuration
* `tns plugin add plugin1 --debug --release` - adds plugin1 to dependencies and nativescript.debug section and shows warning that it cannot be added to release configuration.

## Technical concerns
* Currently when the project is "prepared", we install everything from package.json's dependencies to node_modules and copy node_modules to tns_modules directory (with some magic of course). When plugin configurations are supported, we will have to "select" which of the plugins to move to tns_modules.
* What will happen when we have to add some other configuration specific information. The proposed solution has debug and release keys inside nativescript key, but they are arrays of strings. Maybe we should have more complex object there, so in the future, it will be easy to add additional configuration specific data. For example we may have plugins key inside debug and release:
```JSON
"nativescript": {
          "id": "org.nativescript.app1",
          "tns-android": {
                  "version": "1.0.0"
          },
          "debug": { 
                  "plugins": [ "plugin1", "plugin2", "plugin3" ] 
          },
          "release": { 
                  "plugins": [ "plugin2", "plugin3", "plugin4" ]
          } 
  }
"dependencies": {
         "plugin1": "^1.0.0",
         "plugin2": "^1.0.0",
         "plugin3": "^1.0.0",
         "plugin4": "^1.0.0",
}
```

## Possible improvements
Instead of adding each plugin in both debug and release inside package.json, we can add only the plugins specified for one of the configurations. This will shorten the package.json and will make it easier to add the plugins manually. The example above will look like this:
```JSON
"nativescript": {
          "id": "org.nativescript.app1",
          "tns-android": {
                  "version": "1.0.0"
          },
          "debug": [ "plugin1"],
          "release": [ "plugin4"]
  }
"dependencies": {
         "plugin1": "^1.0.0",
         "plugin2": "^1.0.0",
         "plugin3": "^1.0.0",
         "plugin4": "^1.0.0",
}
```

**Comment by ErjanGavalji** [comment]
I like the possible improvement (had just asked that as a question before reading the entire text :smile: )

How about having a "dev-dependencies" node inside the "nativescript" node? (this is applicable if there are `debug` and `release` configurations only...)

**Comment by RangerMauve** [comment]
I normally use git for these purposes. Just have a separate branch for releases which doesn't have dev dependencies added in. Then merge code from debug to release.

**Comment by ligaz** [comment]
Can't we use the regular `package.json`'s `devDependencies` element?

**Comment by teobugslayer** [comment]
@ligaz, what about possible release-only plugins, like a counterpart to the existing AppManager LiveSync one?

**Comment by teobugslayer** [comment]
I also believe that we can extend this proposal to include config variables. This will be useful for plugins which need API keys or API endpoints which differ between the two configurations.

**Comment by ligaz** [comment]
What is the preferred way to do this currently with NPM?

**Comment by rosen-vladimirov** [comment]
Closing this as we do not have concept for debug/release in NativeScript. When you need the plugin in debug builds only, add it to your package.json and when you want to produce release builds, remove it from there.
