### ISSUE TITLE
Version in package.json is set to 6.5.0 for version 6.4.1

### ISSUE THREAD

**Issue by NickSch1** [NativeScript/nativescript-cli#5273]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
The package.json for v6.4.1 has version set to 6.5.0
This causes some weird behaviour like the npm package page not loading: https://www.npmjs.com/package/nativescript/v/6.4.1

**Comment by NickIliev** [comment]
@NickSch1 [the package.json version is 6.4.1](https://github.com/NativeScript/nativescript-cli/blob/release/package.json#L4) (from the **release** branch). We are still investigating why the package is now displayed properly on NPM.

**Comment by NickSch1** [comment]
Ah, my mistake it seemed the case since the commit mentioned in the release page has 6.5.0 set.
