### ISSUE TITLE
Just updated to 6.5.0: tns run android  "stuck"

### ISSUE THREAD

**Issue by gbonline** [NativeScript/nativescript-cli#5284]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules:
 - Android Runtime: 6.5.0
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

With the run command in the terminal
`tns run android`
stuck up on
`Searching for devices...`
but if I start any emulator before, the run goes well.
Also the `tns device android --available-devices`  command stuck
 With the 6.3 version I could obtain all the devices

**To Reproduce**

update nativescript to the last 6.5.0
```
tns create newproject
cd newproject
tns run android
```

**Expected behavior**

**Sample project**

**Additional context**

I develop on a  mac

**Comment by NickIliev** [comment]
@gbonline tried to reproduce the issue but everything works es expected on my side. Could you execute the command with `--log trace` flag and provide us with the detailed log.

```
tns run android --log trace > log.txt
```

**Comment by gbonline** [comment]
hi, this is the log file taken during the stuck  on a new project just created
[log.txt](https://github.com/NativeScript/nativescript-cli/files/4359418/log.txt)

**Comment by gbonline** [comment]
Hi my new project was created with angular and sidedrawer template

**Comment by gbonline** [comment]
This afternoon I turned off the pc. Then now I turned it back on and tried the newproject and it worked properly, without getting stuck looking for the service
