### ISSUE TITLE
Which one to install when using NVM?

### ISSUE THREAD

**Issue by basickarl** [NativeScript/nativescript-cli#5305]
Hi! I've installed Node.js via NVM. Which should I use:
```
sudo npm install nativescript -g --unsafe-perm

npm install nativescript -g
```
It's not stated here: https://github.com/NativeScript/nativescript-cli#install-the-nativescript-cli

**Comment by NathanWalker** [comment]
Hi @basickarl you can just use `npm install nativescript -g` when using `nvm` 👍
