### ISSUE TITLE
Incorrect verification code on macos ios publish

### ISSUE THREAD

**Issue by michael-dots** [NativeScript/nativescript-cli#5308]
CLI 6.5.0

Getting incorrect verification code, but I know it's correct:

$ tns publish ios --bundle --appleApplicationSpecificPassword ...
? Apple ID ...
? Apple ID password [hidden]
? Please enter the 6 digit code 396136
{
  "service_errors" : [ {
    "code" : "-21669",
    "title" : "Incorrect Verification Code",
    "message" : "Incorrect verification code.",
    "suppressDismissal" : false
  } ],
  "hasError" : true
}

**Comment by michael-dots** [comment]
Some further information. I was able to get past 2FA. I had my 2fa set to sms to a phone not associated with my apple id. I added one to a phone that was, and after i did, i no longer got SMS. Through passwords and security settings i was able to click "request verification code" and get a working code. A hassle, but a workaround nevertheless.

**Comment by NathanaelA** [comment]
One other way to work around the 2FA is open up XCode; and then open up the xcode settings, navigate to the accounts and then re-log in.   Once XCode is logged back in, then TNS has no issues with it.

**Comment by jscti** [comment]
reopen it does not work ... 
AccountId + password + sms received = OK
but : 
{
  "service_errors" : [ {
    "code" : "-21669",
    "title" : "Incorrect Verification Code",
    "message" : "Incorrect verification code.",
    "suppressDismissal" : false
  } ],
  "hasError" : true
}

Tried logout in Xcode ... what a pain

**Comment by ghodum** [comment]
Agree with @jscti I am having the same issue. Pleas re-open this issue.

NS 7.0.8

**Comment by premanandgit** [comment]
I am also facing the same issue. Not able to publish the IOS app through tns publish

**Comment by chevallard** [comment]
Receiving this issue for the first time today. Removing and re-adding user account to XCode does not fix the issue.

**Comment by chunterb** [comment]
This worked for me: 

1. Go to https://appleid.apple.com/account/manage and `Change Password`.
2. Make sure `Sign out of devices and websites using my Apple ID` is checked.
![Screen Shot 2020-11-15 at 2 12 13 PM](https://user-images.githubusercontent.com/31895576/99195660-92462380-274c-11eb-802c-51aa4c50ab28.png)
3. Retry the upload in the CLI.


**NOTE: Make sure you re-generate the one time password after changing your account password, if you are using it.**

**Comment by IanNMarshall** [comment]
Sorry for commenting on old thread. I've tried everything listed and still get same error.

I get the same problem with:

```
ns apple-login
```

or

```
ns publish ios --ipa platforms/ios/build/Release-iphoneos/MyApp.ipa --appleApplicationSpecificPassword <my-app-specific-password>
```

After entering, AppleID, AppleID password, and 6 digit code from SMS

```
{
  "service_errors" : [ {
    "code" : "-21669",
    "title" : "Incorrect Verification Code",
    "message" : "Incorrect verification code.",
    "suppressDismissal" : false
  } ],
  "hasError" : true
}
```

My work around has been:

```
xcrun altool --upload-app --type ios --file platforms/ios/build/Release-iphoneos/MyApp.ipa --username <my-apple-username@mydomain.com> --password <my-app-specific-password>
```

I am not an xCode expert by any means, but I'm also curious: Why does `ns publish ios` need my Apple Password if I'm giving it an app specific password? Isn't that the point of an app specific password?
v

**Comment by ralyodio** [comment]
nothing works for me for SMS verification on `tns apple-login` I logged into my account on xcode, nothing different.
