### ISSUE TITLE
when Entering Flutter doctor --android-licenses getting PS C:\Users\Asus> flutter doctor --android-licenses Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli

### ISSUE THREAD

**Issue by raheena-raeen** [NativeScript/nativescript-cli#5317]
[**Environment**]([url]([url](url
![2](https://user-images.githubusercontent.com/42466721/83322097-ca42c400-a209-11ea-9c74-c46dcda2242d.PNG)
)))
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NathanaelA** [comment]
@raheena-raeen - I believe you entered this bug in the wrong repo; this is not the Flutter repo.   This is the NativeScript repo; which NativeScript is also for developing awesome mobile applications.   Good luck with Flutter!
