### ISSUE TITLE
Splash screen cut out with cli

### ISSUE THREAD

**Issue by vforv** [NativeScript/nativescript-cli#5322]
I was using this command:
`tns resources generate splashes ./Splash-1024.jpg`

the issue is cli cuts out image and add some background behind it. Is it possible to use whole image as splash screen without cutting it?

This way we cannot design splash screen which have multiple colors in background

**Comment by NathanaelA** [comment]
Hi @vforv - You can use the https://images.nativescript.rocks to create splash screens for Android and iOS and it allows you to have customized background and foreground images..      The CLI tool is fairly limited and is meant to get you bootstrapped quickly.
