### ISSUE TITLE
Default `tsconfig.json` has property name `includes` instead of `include`. And it's causing error while running the tests

### ISSUE THREAD

**Issue by recev** [NativeScript/nativescript-cli#5329]
**Environment**
`tns info`
√ Getting NativeScript components versions information...
√ Component nativescript has 6.7.4 version and is up to date.
√ Component tns-core-modules has 6.5.7 version and is up to date.
‼ Update available for component tns-android. Your current version is 6.5.0 and the latest available version is 6.5.1.
‼ Update available for component tns-ios. Your current version is 6.5.0 and the latest available version is 6.5.1.

`node -v`
v12.18.0

`npm -v`
6.14.4

`ng --version`

Angular CLI: 9.1.8
Node: 12.18.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.8 (cli-only)
@angular-devkit/core         9.1.9
@angular-devkit/schematics   9.1.8 (cli-only)
@ngtools/webpack             9.1.9
@schematics/angular          9.1.8 (cli-only)
@schematics/update           0.901.8 (cli-only)
rxjs                         6.5.5
typescript                   3.8.3
webpack                      4.27.1

 - Cross-platform modules:
 - Android Runtime:
GenyMotion Google Pixel 3a emulator
Android 9.0

 - Plugin(s):
no pluging

### **Describe the bug**
While running the tests with `tns test android --emulator`
I got the following error:
```
Entrypoint src\tests\example = runtime.js src\tests\example.bundle.js
[./tests/example.ts] ./src/tests/example.ts 774 bytes {src\tests\example} [built] [failed] [1 error]

ERROR in ./src/tests/example.ts

> Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
> Error: C:\Work\learn\fifthApp\src\tests\example.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
>     at NativeScriptAngularCompilerPlugin.getCompiledFile (C:\Work\learn\fifthApp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
>     at NativeScriptAngularCompilerPlugin.getCompiledFile (C:\Work\learn\fifthApp\node_modules\nativescript-dev-webpack\plugins\NativeScriptAngularCompilerPlugin.js:28:26)
>     at C:\Work\learn\fifthApp\node_modules\@ngtools\webpack\src\loader.js:41:31
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> i ｢wdm｣: Failed to compile.
```

**To Reproduce**
This is how I created the project:
`tns create`

`? First, what will be the name of your app? fifthApp`

`? Next, which style of NativeScript project would you like to use: Angular`

`? Finally, which template would you like to start from: Hello World
`
This is how I initialized the Unit Testing:
`tns test init`
`Jasmine`

this is how I installed the typings
`npm install @types/node --save-dev`

Later, I run the tests on the running emulator 
`tns test android --emulator`

**Expected behavior**

**Sample project**

### **Additional context**
**I found the default template is causing the problem.**
Here is the default value in the `tsconfig.json`
```
  "includes": [
    "references.d.ts"
  ],
```
I changed it into, this
```
  "include": [
    "references.d.ts",
    "src/tests/**/*.ts"
  ],
```
And the problem solved. 
**`includes` must be changed with `include`**
I hope that it will help the others and this bug will be fixed in the future releases :)
Have a good day.

**Comment by NathanWalker** [comment]
Thanks for this @recev

**Comment by NathanWalker** [comment]
This is fixed in latest template - `tns create appname --ng` should have the correction.
