### ISSUE TITLE
Bug SMS tns apple-login

### ISSUE THREAD

**Issue by srcarmi** [NativeScript/nativescript-cli#5343]
tns apple-login
 -entering correct parameters

```
{
  "service_errors" : [ {
    "code" : "-21669",
    "title" : "Incorrect Verification Code",
    "message" : "Incorrect verification code.",
    "suppressDismissal" : false
  } ],
  "hasError" : true
}
```

There is another way to get? --appleSessionBase64 - The session that will be used instead of triggering a new login each time NativeScript CLI communicates with Apple's APIs?

**Comment by ralyodio** [comment]
failing for me too. This is 3 years old ffs.

**Comment by DevZatokio** [comment]
@ralyodio I had to work on an updated version, which resulted in me generating an .ipa then making a file in xcode.
