### ISSUE TITLE
tns build ios gets buggy when trying to export .IPA

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/nativescript-cli#5345]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.8
 - Cross-platform modules: 6.5.10
 - Android Runtime: 6.5.1
 - iOS Runtime: 6.5.1
 - Plugin(s):

**Describe the bug**
In my case, I wanted to export a .IPA package using 'tns build ios --release --for-device --provision my-provision-uid-goes-here' command. However, when using --for-device (needed to export .IPA) the following error occurs:

`No .ipa found in ... directory.`

On the other hand, when checking that directory manually, .ipa seems to be there.
Let me also mention that build seems to be successful, but this issue causes problems in cloud builds due to its exit status.

**To Reproduce**
tns build ios --release --for-device --provision my-provision-uid-goes-here

**Expected behavior**
.IPA for devices should be exported without any issues.

**Comment by DimitrisRK** [comment]
Seems this occurs when 'BundleDisplayName' is set to a different value than project name. In short, when developer sets an app name for iOS, instead of using 'PRODUCT_NAME' placeholder.

**Comment by asharghi** [comment]
Hi @DimitrisRK. I am having the same issue after I upgraded to xcode 12. How do you set the display name then? Do you change the PRODUCT_NAME variable?

**Comment by DimitrisRK** [comment]
> Hi @DimitrisRK. I am having the same issue after I upgraded to xcode 12. How do you set the display name then? Do you change the PRODUCT_NAME variable?

@asharghi I think there is no need to change it. It's probably handled from Apple Store and Certificates.
