### ISSUE TITLE
The Copy URL option is not working for Android apps

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#535]
The "Copy URL" feature that gives you the URL to the app, seems to return the wrong URL for the Android platform, so you can't use it in the companion app there. Even if the URL seems to be the correct one and you enter it in Chrome/Firefox (Nexus6), it still does redirect you to the Companion app.

moved from here - https://github.com/NativeScript/android-runtime/issues/73

**Comment by Fatme** [comment]
moved to android-companion app
