### ISSUE TITLE
Wrong link to nativescript-cli install instructions

### ISSUE THREAD

**Issue by funder7** [NativeScript/nativescript-cli#5352]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.8.0

**Describe the bug**
launching `nsc build android` is printing a warning about incorrect java version, the link on nativescript.org containing the configuration instructions & system requirements returns 404: 

[Linux install instructions (wrong)](http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-linux.html#system-requirements)
[Linux install instructions (right)](https://docs.nativescript.org/start/ns-setup-linux#system-requirements)

I didn't check the other OS links, I think that they're broken too. 

**To Reproduce**
- unset the JAVA_HOME environment variable
- click the link in the warning

**Expected behavior**
seeing the right link in the warning

**Comment by NathanaelA** [comment]
1. Where are you seeing the link to the wrong instructions, we will get that fixed...
2. The web site's instructions haven't been updated yet; the best instructions (which I personally tested) is here:
https://github.com/NativeScript/docs/blob/master/docs//start/ns-setup-linux.md

**Comment by funder7** [comment]
Ok, thanks for the link....I hope that at least the install instructions will be published soon, it took me a while to figure out that cmdline-tools now must be installed in another path respect to the one reported in the official doc.

Cheers

**Comment by NathanaelA** [comment]
@funder7 - I'm a Linux user; so when I fixed the docs on the link I provided (which is what will be published to the official docs site soon), I tested all three Ubuntu versions...  Are you saying you still had issues; or did you have issues with the outdated docs currently on the docs site?

**Comment by funder7** [comment]
Hi @NathanaelA, sorry I didn't specify it: it's the outdated version that doesn't work as is, it would be great to see it updated on the website too!
