### ISSUE TITLE
tns preview not working

### ISSUE THREAD

**Issue by catherine-augustine** [NativeScript/nativescript-cli#5355]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8
 - Cross-platform modules:
 - Android Runtime: 6
 - iOS Runtime:
 - Plugin(s):
nativescript & angular
**Describe the bug**
When I run  `tns preview ` I get the QR code and when I scan it I see 

`Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Start sending initial files for device Catherine (965eecbf-0a40-4da1-85cb-434e34dede29).
Successfully sent initial files for device Catherine (965eecbf-0a40-4da1-85cb-434e34dede29).
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PreviewSdkService.<anonymous> (C:\Users\cathy\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\playground\preview-sdk-service.js:100:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\cathy\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\playground\preview-sdk-service.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by PaulWeinsberg** [comment]
same issue https://github.com/NativeScript/nativescript-cli/issues/5356#issue-678877537

**Comment by narender56** [comment]
Still has no support (7>)?

**Comment by NathanWalker** [comment]
@narender56 Preview 2.0 is in private beta which will replace playground by enabling through better options like StackBlitz:
https://twitter.com/nativescript/status/1534242245020422145?s=21&t=Cwnx0uUG2NlPSCfRJMtMIg
