### ISSUE TITLE
ns migrate still shows hint for 6.0 blogpost

### ISSUE THREAD

**Issue by madmas** [NativeScript/nativescript-cli#5362]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.0

**Describe the bug**
after running `ns migrate` I still get the link to the 6.0 migration guide: 
<img width="751" alt="grafik" src="https://user-images.githubusercontent.com/37251/91830686-646c3b00-ec43-11ea-9b6a-093c2e0f6ed3.png">

**To Reproduce**
run `ns migrate`

**Expected behavior**
show a hint with link to the 7.0 migration guide

**Comment by rigor789** [comment]
This should be fixed in https://github.com/NativeScript/nativescript-cli/releases/tag/v7.0.5
