### ISSUE TITLE
Unable to install NativeScript CLI version 7.x

### ISSUE THREAD

**Issue by nevardreik** [NativeScript/nativescript-cli#5363]
**Environment**
 - CLI: 7.x
 - Node Version: 12.18.3
 - NPM Version: 6.14.8
 - OS: macOS 11 Beta

**Describe the bug**
When running `npm install -g nativescript@latest` the following error is occuring. 

Occurs when attempting to install all 7.x versions.

Does not occur when installing any other global npm packages, and does not occur when installing 6.x versions of {N}.

```
nevardreik@dev.local 💀 > npm  install -g nativescript@7.0.1

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"12.18.3","npm":"6.14.8"})
npm ERR! notsup Not compatible with your version of node/npm: xmlbuilder@2.2.1
npm ERR! notsup Not compatible with your version of node/npm: xmlbuilder@2.2.1
npm ERR! notsup Required: {"node":"0.8.x || 0.10.x"}
npm ERR! notsup Actual:   {"npm":"6.14.8","node":"12.18.3"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nevardreik/.npm/_logs/2020-09-02T03_39_16_444Z-debug.log
```

**Comment by NathanaelA** [comment]
@nevardreik - Kier, can you try doing a `npm i -g nativescript@7.0.0` and see if it works.     I have 7.0.0 installed and am using Node 12, I wonder if something changes in the 7.0.1  release...

**Comment by nevardreik** [comment]
Hi @NathanaelA I have tried all 7.x releases and they all return the same error.

**Comment by NathanaelA** [comment]
@nevardreik - Can you try doing this: `npm config get engine-strict` if it returns `true` then you need to do 
`npm config set engine-strict false`
and then try re-installing NativeScript.

**Comment by nevardreik** [comment]
Thank you @NathanaelA! 💯
