### ISSUE TITLE
File names wrongly cut on deploy

### ISSUE THREAD

**Issue by karaahmed** [NativeScript/nativescript-cli#538]
1.Create a hello world {N} app with iOS platform 
2.Create a module file pair in form  <somename>ios.ts / <somename>ios.xml  (or just rename the main-page.js/xml to main-pageios.js/xml , note the missing . before iOS)
e.g.: abadabaios.js/abadabaios.xml 
3. Execute: tns prepare ios 
4. check the deployed files in prepared solution
Result: the example file are deployed with name: 
abadab.js/abadab.xml
This leads to error during execution: "JS ERROR Error: Failed to load Page from entry.moduleName: views/abadabaios" , since the file with name abadabaios.xml doesn't exist

**Comment by teobugslayer** [comment]
Is this related to https://github.com/NativeScript/nativescript-cli/pull/515 and https://github.com/NativeScript/nativescript-cli/pull/514 ?
