### ISSUE TITLE
tns resources generate won't work properly

### ISSUE THREAD

**Issue by szhatef** [NativeScript/nativescript-cli#5384]
I use this line of code to change app icon:

`tns resources generate icons file.png`

it works! the installed app icon changes. BUT when I go to the recent menu or for the app.apk file itself still that default {N} icon appears.

How can I replace that icon once and for all?

**Comment by brookesb91** [comment]
I've faced similar. Just `remove` or `clean` (`tns platform remove [platform]` or `tns clean`) your platforms and prepare them again and the assets should be correctly included.

**Comment by szhatef** [comment]
I tried all these sort of possible solutions:

`tns paltform remove android`
`tns run android --clean`

still I can change the icon that shows in luncher, but I can see the {N} icon in these situation:

A. when it asks the permission to install the app
B. in recent apps menu
C. for its .apk file in folder manager

**Comment by szhatef** [comment]
It turned out that the actual problem is related to the my smartphone!
somehow MIUI caches the icon and refuse to update it by new installations,
any way changing `id` in `nativescript.confi.ts` can solve the problem :|
