### ISSUE TITLE
Cannot run on iOS device from command line or from VSCode plugin

### ISSUE THREAD

**Issue by facetious** [NativeScript/nativescript-cli#5389]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.
✖ Component @nativescript/android is not installed.

XCode 12, iOS 14, iPhone XS.

**Describe the bug**
`ns create --ng example` project installs correctly on iOS device but doesn't run, faced with error:
```Error while trying to start application org.nativescript.example on device <redacted>. Error is: Could not start service com.apple.debugserver```

**To Reproduce**
```
ns create --ng example
cd example/
ns run ios
```

**Expected behavior**
It runs.

**Additional context**
The Xcode project runs without issue, but obviously doesn't offer the best workflow.

**Comment by facetious** [comment]
@NathanaelA This issue was already resolved in `ios-deploy`: https://github.com/ios-control/ios-deploy/pull/471

A similar fix could be applied to the `ios-device-lib` owned by telerik, or (since that may not be possible, and why bother duplicating effort ...) the `ios-deploy` package could be used in the NativeScript CLI (preferable).

**Comment by NathanWalker** [comment]
@facetious Really appreciate this! And all the excellent reporting/investigations you've been helping with ❤️ 

Agreed I think that's a great idea. We should definitely look at using that package as is.

**Comment by NathanaelA** [comment]
@facetious - Yep, I was aware of that already and was looking at the changes -- but thank you as if I wasn't aware of it you would have saved me a lot of time...  :grinning:

**Comment by facetious** [comment]
@NathanaelA Threw a patch together on `ios-device-lib`: https://github.com/NativeScript/ios-device-lib/pull/68

Totally untested (I didn't bother investigating how to build the package properly), but in theory it works.

**Comment by facetious** [comment]
This is resolved with the resolution of #8867.

**Comment by NathanWalker** [comment]
See closing details here: https://github.com/NativeScript/NativeScript/issues/8867#issuecomment-703171842
