### ISSUE TITLE
NS7+Ng10 iOS app unexpectedly quit on launch with exception: __metadata is not defined 

### ISSUE THREAD

**Issue by ngocnt1** [NativeScript/nativescript-cli#5390]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.
✖ Component @nativescript/android is not installed.
 - macOS 10.5.6
 - xcode 12.0 public release.
- iPhone iOS 14.0 public release
**Describe the bug**
i initiated a angular app from scratch, and just try to run it with --release mode, it causes below exception all the times for both simulator & physical device:
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: __metadata is not defined
 at 
	(file:///app/vendor.js:2:979951)
	at l(file:///app/runtime.js:1:579)
	at (file:///app/vendor.js:2:883273)
	at (file:///app/vendor.js:2:898325)
	at l(file:///app/runtime.js:1:579)
	at (file:///app/vendor.js:2:341618)
	at l(file:///app/runtime.js:1:579)
	at (file:///app/vendor.js:2:578638)
	at l(file:///app/runtime.js:1:579)
	at (file:///app/vendor.js:2:254187)
	at l(file:///app/runtime.js:1:579)
	at (file:///app/vendor.js:2:696690)
	at l(file:///app/runtime.js:1:579)
	at (file:///app/vendor.js:2:607012)
	at (file:///app/vendor.js:2:694415)
	at l(file:///app/runtime.js:1:579)
	at 326(file:///app/bundle.js:1:1971)
	at l(file:///app/runtime.js:1:579)
	at t(file:///app/runtime.js:1:448)
	at r(file:///app/runtime.js:1:311)
	at (file:///app/bundle.js:1:170)
	at require(:1:137)
', reason: '(null)'

**To Reproduce**
1. Initiate a angular app with cli: **ng create NS70Ng10 --ng**
2. **cd NS70Ng10**
3. prepare iOS xcode project: **ns prepare ios --env.aot --env.uglify --release**
4. open Xcode workspace with Xcode 12 : /NS70Ng10/platforms/ios/NS70Ng10.xcworkspace
5. Build and run to deploy app to simulator or physical device
6. Issue: app quit on launch with the exception on output panel.

**Expected behavior**
  App can launch without the exception

**Sample project**
[NS70Ng10.zip](https://github.com/NativeScript/nativescript-cli/files/5249110/NS70Ng10.zip)

**Additional context**
if do step 3 without **--release** parameter, you should work well, it only happen to release mode as i see

**Comment by NathanWalker** [comment]
@ngocnt1 could you drop the contents of src/main.ts here?

**Comment by ngocnt1** [comment]
@NathanWalker the contents of main.ts here:
`// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { platformNativeScriptDynamic } from "@nativescript/angular";

import { AppModule } from "./app/app.module";

// A traditional NativeScript application starts by initializing global objects,
// setting up global CSS rules, creating, and navigating to the main page.
// Angular applications need to take care of their own initialization:
// modules, components, directives, routes, DI providers.
// A NativeScript Angular app needs to make both paradigms work together,
// so we provide a wrapper platform object, platformNativeScriptDynamic,
// that sets up a NativeScript application and can bootstrap the Angular framework.
platformNativeScriptDynamic().bootstrapModule(AppModule);
`
please see more details the attached sample project,

**Comment by NathanWalker** [comment]
Thanks - instead of using prepare can you run it this way and lemme know if any different after you open project in Xcode and run it to confirm:
ns build ios --env.aot --env.uglify --release  --env.production

**Comment by ngocnt1** [comment]
it's still the same crashing issue on launch, 
1. i ran **ns build ios --env.aot --env.uglify --release --env.production** and drop NS70Ng10.app to the simulator to try => it crashed immediately on launch

2. Then i tried **ns prepare ios --env.aot --env.uglify --release --env.production**  , and open ios xproj with xcode 12, press run to deploy to the simulator => crashed on launch

3. I tried another case: **ns prepare ios --env.aot --env.uglify --env.production**,  and open ios xproj with xcode 12 and deploy & run app on the simulator => crashed on launch

4. If i tried **ns build ios --env.aot --env.uglify**, and you know the drop package is signical bigger. But it works well, and i think it's not optimized for a production release. 

Btw the exception details is same with the "Decribe of bug",

**Comment by ngocnt1** [comment]
Hi @NathanWalker,  I got it work on verion:
√ Getting NativeScript components versions information...
√ Component nativescript has 7.0.8 version and is up to date.
√ **Component @nativescript/core has 7.0.7 version and is up to date.**
√ Component @nativescript/ios has 7.0.0 version and is up to date.
√ Component @nativescript/android has 7.0.0 version and is up to date.
with below:
**ns build ios --env.aot --env.uglify --release --env.production**

i'm going to close this
