### ISSUE TITLE
Console Does Not Log All console.logs

### ISSUE THREAD

**Issue by szhatef** [NativeScript/nativescript-cli#5392]
When I run this code: ` ns debug android --no-hmr --device #####`
I noticed frequently that shell stops to show console.log() messages. (sometimes it reports one or two and then stops to report further messages)
that´s bizarre while the message will be logged on `devtools://devtools/bundled/inspector.html?ws=localhost:40000`
so the code runs successfully but shell neglects it somehow!

OS: Pop OS 20.04

**Comment by mdjamal** [comment]
@szhatef for me the file and line number prefix is missing in console log after updating to NS7. Making it hard to debug.

**Comment by szhatef** [comment]
It seems setting Interval prevent shell to report logs!

**Comment by mdjamal** [comment]
where do I change this interval settings?

**Comment by szhatef** [comment]
I mean defining recursive setTimeout() or setInreval(), may impacts on shell log reporting

**Comment by mdjamal** [comment]
ok understood, thanks.

**Comment by szhatef** [comment]
It seems that this bug will appears only when the project is build up on previous versions of {N} (<7).
creating a new project with {N} 7 and importing source codes of my project into it solves the issue!
