### ISSUE TITLE
App crashing on Android and iOS when running with --env.production: "Module 'Frame' not found for element 'Frame'."

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/nativescript-cli#5401]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules: @nativescript/core@7.0.7 (also tested 7.0.0)
 - Android Runtime: 7.0.0
 - iOS Runtime: 7.0.0
 - Plugin(s): @nativescript/webpack 3.0.5 (also tested 3.0.0)

**Describe the bug**
Not sure if this is the right place for this issue or if it is more related to @nativescript/webpack, but I try it here first.

When creating a new app with the Hello-World template and running it on Android or iOS using the **--env.production** option, the app will crash on startup.

Android Crashlog:

> System.err: An uncaught Exception occurred on "main" thread.
> System.err: Unable to start activity ComponentInfo{org.nativescript.HelloWorld/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
> System.err: Error: Building UI from XML. @app-root.xml:1:1
> System.err:  > Module 'Frame' not found for element 'Frame'.
> System.err:    > com.tns.NativeScriptException: Failed to find module: "@nativescript/core/ui", relative to: app/tns_modules/
> System.err: 
> System.err: StackTrace:
> System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.HelloWorld/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
> System.err: Error: Building UI from XML. @app-root.xml:1:1
> System.err:  > Module 'Frame' not found for element 'Frame'.
> System.err:    > com.tns.NativeScriptException: Failed to find module: "@nativescript/core/ui", relative to: app/tns_modules/
> System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
> System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
> System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
> System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
> System.err:     at android.os.Looper.loop(Looper.java:214)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
> System.err:     at java.lang.reflect.Method.invoke(Native Method)
> System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
> System.err: Error: Building UI from XML. @app-root.xml:1:1
> System.err:  > Module 'Frame' not found for element 'Frame'.
> System.err:    > com.tns.NativeScriptException: Failed to find module: "@nativescript/core/ui", relative to: app/tns_modules/
> System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
> System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
> System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
> System.err:     at android.app.Activity.performCreate(Activity.java:7802)
> System.err:     at android.app.Activity.performCreate(Activity.java:7791)
> System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
> System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
> System.err:     ... 11 more

iOS Crashlog:

> ***** Fatal JavaScript exception - application has been terminated. *****
> NativeScript encountered a fatal error: Uncaught Error: Building UI from XML. @app-root.xml:1:1
> > Module 'Frame' not found for element 'Frame'.
> > The specified module does not exist: ui
> at
> ScopeError(file: node_modules/@nativescript/core/utils/debug.js:51:0)
> at SourceError(file: node_modules/@nativescript/core/utils/debug.js:58:0)
> at (file: node_modules/@nativescript/core/ui/builder/index.js:228:0)
> at (file: node_modules/@nativescript/core/ui/builder/index.js:207:0)
> at (file: node_modules/@nativescript/core/xml/index.js:412:0)
> at push.EasySAXParser.parse(file: node_modules/@nativescript/core/js-libs/easysax/easysax.js:751:0)
> at parse(file: node_modules/@nativescript/core/xml/index.js:455:0)
> at parse(file: node_modules/@nativescript/core/ui/builder/index.js:213:0)
> at parseInternal(file: node_modules/@nativescript/core/ui/builder/index.js:181:0)
> at loadInternal(file: node_modules/@nativescript/core/ui/builder/index.js:94:0)
> at createViewFromEntry(file: node_modules/@nativescript/core/ui/builder/index.js:36:0)
> at createRootView(file: node_modules/@nativescript/core/application/index.ios.js:312:30)
> at setWindowContent(file: node_modules/@nativescript/core/application/index.ios.js:253:0)
> at notifyAppStarted(file: node_modules/@nativescript/core/application/index.ios.js:165:0)
> at didFinishLaunchingWithOptions(file: node_modules/@nativescript/core/application/index.ios.js:149:0)
> at push.NotificationObserver.onReceive(file: node_modules/@nativescript/core/application/index.ios.js:39:0)
> (CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: Building UI from XML. @app-root.xml:1:1
> > Module 'Frame' not found for element 'Frame'.
> > The specified module does not exist: ui
> at
> ScopeError(file: node_modules/@nativescript/core/utils/debug.js:51:0)
> at SourceError(file: node_modules/@nativescript/core/utils/debug.js:58:0)
> at (file: node_modules/@nativescript/core/ui/builder/index.js:228:0)
> at (file: node_modules/@nativescript/core/ui/builder/index.js:207:0)
> at (file: node_modules/@nativescript/core/xml/index.js:412:0)
> at push.EasySAXParser.parse(file: node_modules/@nativescript/core/js-libs/easysax/easysax.js:751:0)
> at parse(file: node_modules/@nativescript/core/xml/index.js:455:0)
> at parse(file: node_modules/@nativescript/core/ui/builder/index.js:213:0)
> at parseInternal(file: node_modules/@nativescript/core/ui/builder/index.js:181:0)
> at loadInternal(file: node_modules/@nativescript/core/ui/builder/index.js:94:0)
> at createViewFromEntry(file: node_modules/@nativescript/core/ui/builder/index.js:36:0)
> at createRootView(file: node_modules/@nativescript/core/application/index.ios.js:312:30)
> at setWindowContent(file: node_modules/@nativescript/core/application/index.ios.js:253:0)
> at notifyAppStarted(file: node_modules/@nativescript/core/application/index.ios.js:165:0)
> at didFinishLaunchingWithOptions(file: node_modules/@nativescript/core/application/index.ios.js:149:0)
> at push.NotificationObserver.onReceive(file:///a<…>

When running the app without the **--env.production** option, everything seems to work as expected.

**To Reproduce**
1.) create a new app running `tns create HelloWorld` or use the sample project provided below and run it with `tns run android|ios --env.production`

**Expected behavior**
The app should not crash.

**Sample project**
[HelloWorld.zip](https://github.com/NativeScript/nativescript-cli/files/5298029/HelloWorld.zip)

**Additional context**
It is not related to the Hello-World-template, the a newly created app using the SideDrawer template is also crashing on startup with a slightly different error message.

**Comment by SaifulZiko** [comment]
@felixkrautschuk  i have the similar problem... have you solved it?
