### ISSUE TITLE
ns resources generate icons: iOS 1024x1024 garbled

### ISSUE THREAD

**Issue by BlueHunter99** [NativeScript/nativescript-cli#5410]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.10
 - @nativescript/core: 7.0.9
 - iOS Runtime: 7.0.1

**Describe the bug**
`ns resources generate icons` works perfectly for all of the icons except for the 1024x1024 one. This results in a weird 'garbled' image, which is then used on the app store.

**To Reproduce**
1. Create new project from sample (in my case Angular + Hello World)
2. Use `ns resources generate icons` on an icon of your choosing.

**Expected behavior**
The CLI should generate (scale) the icon properly.

**Additional context**
I've attached the `icon.png` which I use while running the command as well as the resulting image.

<img src="https://user-images.githubusercontent.com/14956440/95221344-a3b81980-07f7-11eb-82d9-070ebf92bef1.png" alt="original icon" width="100" height="100">
<img src="https://user-images.githubusercontent.com/14956440/95221375-ab77be00-07f7-11eb-8731-4f90016c3c89.png" alt="generated icon" width="100" height="100">

**Comment by crowmagnumb** [comment]
This just bit me too. I had to pull my app back from review after I discovered this. As a workaround I guess I will just copy my icon over by hand before building but would nice to get this fixed.

**Comment by NathanWalker** [comment]
I had no idea this command even existed!
Golden standard has been this for long time:
http://images.nativescript.rocks/

**Comment by crowmagnumb** [comment]
Well, that may be fine for one-offs, but I recreate the icons for development, beta, and production versions so that they show up on my phone differently and I can tell them apart. The dev version is the usual version, when I am deploying a beta test version to TestFlight for example, I recreate the icons for that, and finally when I publish to the store I recreate the production version of the icons. This is all done in my build script which includes this command.

**Comment by crowmagnumb** [comment]
This is caused by line 161 of assets-generation-services.ts but is the fault of the dependency jimp.

```
			// This code disables the alpha chanel, as some images for the Apple App Store must not have transparency.
			if (assetItem.rgba === false) {
				image = image.rgba(false);
			}
```

`assets.rgba` is only set to false for 1024 size icon. So, will investigate a fix on jimp, but in the meantime, does anyone know if this line of code is necessary? Why only for the 1024 sized icon?

**Comment by NathanaelA** [comment]
@crowmagnumb - Because The apple store will reject the 1024x1024 store images with transparency.  So this forces the image to be non-transparent.

**Comment by crowmagnumb** [comment]
Weird that it is only that one though. But OK. :) Anyway, I couldn't figure out the jimp issue on my own so I submitted an issue that you can find here https://github.com/oliver-moran/jimp/issues/954

**Comment by crowmagnumb** [comment]
For anyone that this may help I'm running the following command after `ns resources generate icons <src>` and that is `convert <src> -background white -alpha remove -alpha off AppResources/iOS/Assets.xcassets/AppIcon.appiconset/icon-1024.png` where `convert` is an ImageMagick utility. My <src> icon is 1024, so if yours is not you will have to resize it by adding `-resize 1024x1024` to above command.

**Comment by NathanaelA** [comment]
@crowmagnumb - Ken, since your already in the code; can you try

replacing `.rgba(false)` with `.colorType(2)`;  
And see if that fixes the issue?

**Comment by crowmagnumb** [comment]
Oooooh, that did the trick! Nice job! I'l do a pull request since i have the change, though I'ld be stealing your thunder.

**Comment by NathanaelA** [comment]
Please do steal my thunder...  We :heart: PR's.      Thank YOU for actually tracing down where the issue was...
