### ISSUE TITLE
Linker command failing with 7.0.10 version

### ISSUE THREAD

**Issue by romandrahan** [NativeScript/nativescript-cli#5411]
**Environment**

 - CLI: 7.0.10
 - Cross-platform modules: 7.0.11
 - Android Runtime: 7.0.0
 - iOS Runtime: 7.0.2-rc1

**Describe the bug**

Running `ns run ios` using CLI 7.0.10 and iOS runtime 7.0.2-rc1 (same for 7.0.1) fails with error below 👇

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SDImageCache", referenced from:
      objc-class-ref in ABKSDWebImageProxy.o
  "_OBJC_CLASS_$_SDWebImageManager", referenced from:
      objc-class-ref in ABKSDWebImageProxy.o
  "_OBJC_CLASS_$_SDWebImageActivityIndicator", referenced from:
      objc-class-ref in ABKSDWebImageProxy.o
  "_OBJC_CLASS_$_SDWebImagePrefetcher", referenced from:
      objc-class-ref in ABKContentCardsTableViewController.o
      objc-class-ref in ABKNewsFeedTableViewController.o
      objc-class-ref in ABKSDWebImageProxy.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It **works fine** with CLI 7.0.9-rc.2 and iOS runtime 7.0.0 though.

**To Reproduce**

Execute `ns run ios` with CLI 7.0.10.

**Comment by alpha2k-io** [comment]
yes... same here ... just downgraded to CLI 7.0.9-rc.2 and iOS runtime 7.0.0 though. and it worked.

**Comment by romandragan** [comment]
@alpha2k-io, UPD. It works fine while building for real device, but **not** for simulator.

**Comment by NathanaelA** [comment]
@romandragan - My guess based on this error is you are using XCode 11

Please see: https://nativescript.org/blog/nativescript-6-7-xcode-compatibility/

**Comment by romandragan** [comment]
> @romandragan - My guess based on this error is you are using XCode 11
> 
> Please see: https://nativescript.org/blog/nativescript-6-7-xcode-compatibility/
> 
> 

@NathanaelA, no-no, it's 12.0.1, and it works pretty fine with CLI 7.0.9-rc.2 and iOS runtime 7.0.0. It just started to fail with latest CLI and/or runtime and only while building for simulator.

**Comment by romandragan** [comment]
@NathanaelA\, it's interesting though, that running the project from Xcode after `ns prepare ios` works fine, while it does not work while running via `ns run ios`.

**Comment by romandragan** [comment]
@NathanaelA, seems like 7.0.10 CLI adds these lines to `build.xcconfig` which breaks the build for simulators:

![telegram-cloud-photo-size-2-5215415767657459567-y](https://user-images.githubusercontent.com/3455696/96370269-ecf85980-1165-11eb-9c92-126c2c24f6e9.jpg)

7.0.9 doesn't have those lines added.

**Comment by NathanaelA** [comment]
@romandragan - 
1. Do you still have XCode 11 installed with XCode 12, or are you sure you just XCode 12 installed?   
2. Yes, those are required in XCode 12; they changed the logic around.    So for the sdk=iphonesimulator we exclude everything except x86_64.    For iphoneos (read device) = we exclude everything but arm64.

**Comment by romandragan** [comment]
@NathanaelA,

Yes, its 12.0.1 for sure.

I don't get why it's working fine on 7.0.9-rc.2 CLI **or** while running on simulator **but** with Xcode itself. It only fails while building with 7.0.10 CLI.

**Comment by NathanaelA** [comment]
Well, the reason I ask if you have XC 11 still installed along with XC 12, is that from the CLI, it could be calling your XC11 install, where when you startup XC 12, it would use the XC 12 tooling.   

Can you go to a terminal shell and do the following:
- xcrun --show-sdk-platform-path --sdk iphonesimulator
- xcrun --show-sdk-platform-version --sdk iphonesimulator
- xcrun --show-sdk-platform-path --sdk iphoneos
- xcrun --show-sdk-platform-version --sdk iphoneos
- xcode-select -p

**Comment by romandragan** [comment]
@NathanaelA, thank's here is the output:

```
xcrun --show-sdk-platform-path --sdk iphonesimulator: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform

xcrun --show-sdk-platform-version --sdk iphonesimulator: 14.0

xcrun --show-sdk-platform-path --sdk iphoneos: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform

xcrun --show-sdk-platform-version --sdk iphoneos: 14.0

xcode-select -p: /Applications/Xcode.app/Contents/Developer
```

/Applications/Xcode.app:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/3455696/96373199-97c34480-1173-11eb-925e-7fb89c525411.png">

---

Also noticed these lines being added to Podfile, which could be the cause of the issue:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3455696/96373087-e3c1b980-1172-11eb-94b1-66af60abb4b4.png">

The only way for us to use latest `@nativescript/ios@7.0.3` is to use CLI 7.0.9-rc.2 and add these lines to `app/App_Resources/iOS/build.xcconfig`:

```
VALID_ARCHS[sdk=iphoneos*] = arm64
VALID_ARCHS[sdk=iphonesimulator*] = x86_64
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64
```

**Comment by NathanaelA** [comment]
I have to admit, I'm not sure why your setup would be failing unless you had XC < 12 tools somehow still being called.   I do know that we had a similar issue with a machine that has XCode 12.01 and the 12.2 beta.   All the paths said Xcode 12.01, but when it built the app; it kept using XCode 12.2, that is why I was curious if you still have any other XCode beside 12.01 still installed on the computer.

**Comment by romandragan** [comment]
@NathanaelA, could I please share my project via some private repo here so you can try it on your machine as well?

**Comment by NathanaelA** [comment]
@romandragan - I've sent you to a newly created private repo.

**Comment by romandragan** [comment]
@NathanaelA, thanks, pushed to your repo, PR 1 is the one you need.

**Comment by romandragan** [comment]
@NathanaelA, FYI I just tried it on clean macOS install on http://macincloud.com with Xcode 12.0.1 and it gives just the same issue :(

**Comment by NathanaelA** [comment]
Can you tell me what version of Node you are using; I tried NPM i; and it is failing on the grpc dependency...

**Comment by romandragan** [comment]
@NathanaelA, it's 10.19.0 it fails on all others :(

**Comment by romandragan** [comment]
@NathanaelA, cheers, sorry for disturbing, but just checking maybe you had time to reproduce the issue on that test repo?

**Comment by NathanaelA** [comment]
Actually I did get a chance and was able to duplicate it.  However, I haven't had the time to dig into WHY it is failing as it shouldn't be.   My guess is a Podfile is doing something, but I haven't had time to narrow it down yet...

**Comment by romandragan** [comment]
@NathanaelA, thanks!

Braze guys wrote here about possible EXCLUDE_ARCHS conflict: https://github.com/Appboy/appboy-ios-sdk/issues/250

**Comment by romandragan** [comment]
@NathanaelA, also just read this from Braze docs:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/3455696/96975266-e893be00-1522-11eb-8d31-5fb685049802.png">

I do can update `build.xcconfig` but this will work only for CLI < 7.0.10, cause it adds post install hook to Podfile with new `EXCLUDED_ARCHS` which obviously breaks the Braze Pod:

```
installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete "VALID_ARCHS"
    config.build_settings["EXCLUDED_ARCHS_x86_64"] = "arm64 arm64e"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 armv6 armv7 armv7s armv8 $(EXCLUDED_ARCHS_$(NATIVE_ARCH_64_BIT))"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "i386 armv6 armv7 armv7s armv8 x86_64"
end
```

Makes any sense?

**Comment by felixkrautschuk** [comment]
Are there any updates?

I also have this issue using NativeScript CLI 7.0.11 and XCode 12.2.

**Comment by davorpeic** [comment]
Issue is still the same on NS8 with xcode 12.5, I will assume they are working on a fix
