### ISSUE TITLE
Page onLoaded event is not being called on Android when pages are within a Frame within a Tabview

### ISSUE THREAD

**Issue by BMwanza** [NativeScript/nativescript-cli#5415]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules:^6.4.1
 - Android Runtime: 6.3.1
 - Plugin(s): Not applicable (I'm guessing the plugins are irrelevant in this case)

**Describe the bug**
This Bug seems to be a runtime error. In my project, I have a separate `login-root.xml` file which contains a Frame with a default page for the users to log in/sign up.

After logging in, using the Frame.getFrameById method, I navigate to a `user-tabs.xml` file which has a `Tabview` wrapped within a `Page`. Each `TabViewItem` contains a `Frame` with a default page that represents the starting page of each tab.

The behaviour now is, for any `Page` that is navigated to within the Tabview, the `Page's` `onloaded` event is not being triggered. This was not the case when I was running the `5.2.1` version of the {N} CLI with the `5.3.1` Android runtime. So clearly it's a change in behaviour since the migration.

Prior to migrating, each `Page's` `onLoaded` event was being called whenever the page went from not being shown to being shown (for example switching for tab A to tab B), this is not the case now as it is not being called at all.

**Comment by NathanaelA** [comment]
@BMwanza - Can you create a simple sample app that shows this behavior?

**Comment by BMwanza** [comment]
@NathanaelA Yes I can do that, please give me about a week to complete the small sample app. Once complete I will make it into a github repo

**Comment by BMwanza** [comment]
I created a sample project, while running the `tns create demo  --template tns-template-tab-navigation` command using the `6.2.0` version of the CLI. I noticed that the structure of the tab view has changed since I last ran this command on NS 5. In the demo app, with the new template, the `loaded` event for the tab pages are being properly triggered.

I am going to refactor my `Tabview` code in my actual project to match the new template. I will give an update if that fixes everything 👍🏾

**Comment by BMwanza** [comment]
I am confirming that using the N6 `BottomNavigation`, `TabStrip`, and `TapStripItem` components the the page's `loaded` events are being triggered as expected. Thank you!

Here is a code snippet for future reference for those who migrate from a  {N} <  {N} 6 project that uses a `Tabview`

`<Page loaded="onLoaded" navigatedTo="onNavigatedTo">
    <BottomNavigation>
    <TabStrip>
        <TabStripItem class="navigation__item">
            
            <Label text="Home" />
        </TabStripItem>
        <TabStripItem class="navigation__item">
            <Label text="Browse" />
            <Image src="font://&#xf1ea;" class="far t-36" />
        </TabStripItem>
        <TabStripItem class="navigation__item">
            <Label text="Search" />
            <Image src="font://&#xf002;" class="fas t-36" />
        </TabStripItem>
    </TabStrip>

    <TabContentItem>
        <Frame defaultPage="home/home-items-page" />
    </TabContentItem>

    <TabContentItem>
        <Frame defaultPage="browse/browse-page" />
    </TabContentItem>

    <TabContentItem>
        <Frame defaultPage="search/search-page" />
    </TabContentItem>
</BottomNavigation>

</Page>`
