### ISSUE TITLE
Cannot run app on iOS: Unable to apply changes on device: 75E3E329-50CC-4958-8760-782AF99783CF. Error is: Command xcrun with arguments simctl install 

### ISSUE THREAD

**Issue by JamesPJ** [NativeScript/nativescript-cli#5416]
**Environment**

 - CLI: 6.5.3
 - iOS Runtime: 13.3
 - XCode Version: 11.3 (11C29)
 - Plugin(s):

**Describe the bug**
I'm unable to run the app on iOS simulators after upgrading the app from 5.4 to 6.x `tns run ios` throws following error. 

```
Installing on device 75E3E329-50CC-4958-8760-782AF99783CF...
Unable to apply changes on device: 75E3E329-50CC-4958-8760-782AF99783CF. Error is: Command xcrun with arguments simctl install 75E3E329-50CC-4958-8760-782AF99783CF /Users/james/HelloWorld/platforms/ios/build/Debug-iphonesimulator/HelloWorld.app failed with exit code 1. Error output:
 An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not install at this time.
Failed to chmod /Users/james/Library/Developer/CoreSimulator/Devices/75E3E329-50CC-4958-8760-782AF99783CF/data/Bundle/Application/358B3C8E-8140-4DF0-BDCB-2F42AB804868/HelloWorld.app/HelloWorld : No such file or directory
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/james/Library/Developer/CoreSimulator/Devices/75E3E329-50CC-4958-8760-782AF99783CF/data/Bundle/Application/358B3C8E-8140-4DF0-BDCB-2F42AB804868/HelloWorld.app/HelloWorld : No such file or directory
```

**To Reproduce**
With this package.json I'm able to reproduce the issue on new NS app as well
```
{
  "nativescript": {
    "id": "org.nativescript.HelloWorld",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.3"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "@nativescript/theme": "^3.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^3.0.4",
    "@nstudio/nativescript-pulltorefresh": "^2.0.0",
    "@proplugins/nativescript-drop-down": "^7.1.0",
    "@proplugins/nativescript-localstorage": "^2.3.2",
    "@proplugins/nativescript-orientation": "^2.4.2",
    "base-64": "^0.1.0",
    "crypto-js": "^3.1.9-1",
    "nativescript-advanced-webview": "^6.0.0",
    "nativescript-angular": "^8.0.2",
    "nativescript-badge-button": "^0.1.2",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-local-notifications": "^4.2.1",
    "nativescript-pdf-view": "^2.4.3",
    "nativescript-permissions": "^1.3.9",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "~6.1.0",
    "nativescript-ui-sidedrawer": "~8.0.1",
    "nativescript-webview-interface": "^1.4.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.6.3",
    "tns-core-modules": "^6.5.20",
    "uglifyjs-webpack-plugin": "^2.1.1",
    "utf8": "^3.0.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.0",
    "@ngtools/webpack": "8.0.0",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-webpack": "~1.5.1",
    "typescript": "3.4.5"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  },
  "gitHead": "20a65d338ae8f8911087ab6615b89363f864b07b",
  "readme": "NativeScript Application"
}

```
After `npm install` run `tns run ios`

**Expected behavior**
App should run on similator as well as device.

**Comment by jitendraP-ashutec** [comment]
I have also same problem but nativescript environment is different. Below are my nativescript environment.

Environment

CLI: 7.0.10
iOS Runtime: 13.5
XCode Version: 11.5 (11E608c)

Error:
`Unable to apply changes on device: 149FA8BE-F671-48F5-A9E4-68F52CA06044. Error is: Command xcrun with arguments simctl install 149FA8BE-F671-48F5-A9E4-68F52CA06044 /Users/apple/projects/ns-7/platforms/ios/build/Debug-iphonesimulator/ns7.app failed with exit code 1. Error output:
 An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not install at this time.
Failed to chmod /Users/apple/Library/Developer/CoreSimulator/Devices/149FA8BE-F671-48F5-A9E4-68F52CA06044/data/Bundle/Application/58567C7A-A429-478E-95AA-22CF5A1C9BD7/ns7.app/ns7 : No such file or directory
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/apple/Library/Developer/CoreSimulator/Devices/149FA8BE-F671-48F5-A9E4-68F52CA06044/data/Bundle/Application/58567C7A-A429-478E-95AA-22CF5A1C9BD7/ns7.app/ns7 : No such file or directory
`
package.json
`{
  "name": "@nativescript/template-hello-world-ng",
  "main": "main.js",
  "version": "7.0.2",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/ios": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "typescript": "~3.9.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}
`

@JamesPJ  have you found any solution?

@tjvantoll  @rosen-vladimirov 

Thanks

**Comment by JamesPJ** [comment]
@NathanaelA I've updated NS CLI to 6.8.0 as suggested in the compatibility page, I'm still facing the original issue. Here is the  out of `tns info`.

```
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.8.0 and the latest available version is 7.0.10.
✔ Component tns-core-modules has 6.5.20 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.
✔ Component tns-ios has 6.5.3 version and is up to date
```

Let me know whether I'm I still having the wrong versions.

**Comment by NathanaelA** [comment]
@JamesPJ  - Are you still using xCode 11?

**Comment by JamesPJ** [comment]
@NathanaelA Yes, I'm still on 11.3 (11C29)

**Comment by NathanaelA** [comment]
Ok, a couple things can you try:
- First, using tns-ios 6.5.2   and see if it makes any difference?   (`tns platform remove ios` & ~tns platform add ios@6.5.2`)
- Second, if that doesn't work can you try using `npm i -g nativescript@6.5.1`

**Comment by JamesPJ** [comment]
@NathanaelA Thank you for your support. After switching to `6.5.2` iOS is working now.

`tns platform remove ios` & `tns platform add ios@6.5.2`.
