### ISSUE TITLE
Preemptively add corresponding runtime dependency when adding a platform

### ISSUE THREAD

**Issue by pavi2410** [NativeScript/nativescript-cli#5425]
**Is your feature request related to a problem? Please describe.**
 
In order to add a platform, the runtime dependency has to be added first, or else npm continues to run indefinitely.

**Describe the solution you'd like**

When running `ns platform add {android,ios}`, check package.json for the dependency and run `npm i @nativescript/{android,ios}` if it is absent.

**Describe alternatives you've considered**

Run those command manually.

**Additional context**

**Comment by NathanaelA** [comment]
I'm not understanding what issue you are trying to say:
For example a brand new created JS app has no runtime dependancy; 
![image](https://user-images.githubusercontent.com/850871/96931132-6fdd2500-1482-11eb-8620-7490384bec00.png)
However, if I do `ns platform add android`
![image](https://user-images.githubusercontent.com/850871/96933309-d31c8680-1485-11eb-9be5-6da5b97acd85.png)
I now have the android dependancy...

Can you describe in steps what you are seeing?

**Comment by pavi2410** [comment]
I posted about this on Slack
https://nativescriptcommunity.slack.com/archives/C0L9EEURY/p1603379632012300?thread_ts=1603379632.012300&cid=C0L9EEURY

1. I have installed the latest version of Nativescript using `npm i -g nativescript`
2. Then, created a new React NS project using `ns create NSTest --react`
3. `cd NSTest`
4. `npm i`
5. All good until here
6. Run `ns doctor` and it reports the platforms are missing in the project. Suggests running `ns platform add`
7. Naively run `ns platform add android`
8. Get's something like what is shown in Slack (npm runs indefinitely)


To fix this,
9. Run `npm i @nativescript/android`
10. Then, run `ns platform add android`
11. Mission successful!

**Comment by NathanaelA** [comment]
This is interesting can confirm it fails for a `--react`, but works fine for `--js`;
Using `--log trace` shows these lines
```
⠹ Using Android SDK '30'.
Directories to clean:
[]
Platform android successfully added. v7.0.1
```
And then it freezes until you hit ctrl-c; package.json has updated dev dependancy and platforms and node_modules has the correct files.

**Comment by NathanaelA** [comment]
@pavi2410 - Can you please try the latest NS Cli; I updated my cli mid-tests because I needed the `--svelte` support; and now when I tried `--react` again it worked...   So maybe this is fixed in the latest version.   (npm i -g nativescript@latest)

**Comment by pavi2410** [comment]
Using `npm i -g nativescript@latest`, I am not able to create a new RNS project

```
C:\Users\Pavitra\Desktop\NS>ns create --react NSReact
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @nativescript/template-blank-react@7.0.4
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.13.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.13.1" from react-native@0.63.3
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-navigation/native@5.8.1
npm ERR!   node_modules/@react-navigation/native
npm ERR!     @react-navigation/native@"^5.4.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Pavitra\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pavitra\AppData\Local\npm-cache\_logs\2020-10-30T05_00_04_627Z-debug.log
Command npm.cmd failed with exit code 1
```

**Comment by rigor789** [comment]
> 
> 
> Using `npm i -g nativescript@latest`, I am not able to create a new RNS project
> 
> ```
> C:\Users\Pavitra\Desktop\NS>ns create --react NSReact
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: @nativescript/template-blank-react@7.0.4
> npm ERR! Found: react@16.14.0
> npm ERR! node_modules/react
> npm ERR!   react@"^16.13.1" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"16.13.1" from react-native@0.63.3
> npm ERR! node_modules/react-native
> npm ERR!   peer react-native@"*" from @react-navigation/native@5.8.1
> npm ERR!   node_modules/@react-navigation/native
> npm ERR!     @react-navigation/native@"^5.4.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\Pavitra\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Pavitra\AppData\Local\npm-cache\_logs\2020-10-30T05_00_04_627Z-debug.log
> Command npm.cmd failed with exit code 1
> ```

@shirakaba does this seem like something that needs to be fixed in the template, or one of the packages for rns?

**Comment by shirakaba** [comment]
@rigor789 I think that I mistakenly added @react-navigation/native instead of @react-navigation/core as a dependency.

**Comment by shirakaba** [comment]
@pavi2410 I’m aiming to fix this over the weekend. Looks like React Navigstion has a new version, so I need to refactor React NativeScript Navigation significantly to catch up with it. I’ve refactored two out of the three navigators now, and will make the fix to RNS Navigation after fixing the third one.

After that fix is released, I can patch the RNS template.

**Comment by shirakaba** [comment]
@pavi2410 I've updated React NativeScript Navigation to `react-nativescript-navigation@2.0.1`, which supports the latest version of React Navigation 👴

I've also opened a Pull Request to update the React NativeScript starter template to `@nativescript/template-blank-react@7.0.6`, in which it will use `react-nativescript-navigation@2.0.1` and `@react-navigation/core@5.13.2`: https://github.com/NativeScript/nativescript-app-templates/pull/174/files

To get the benefits in an existing project, just run:

```sh
npm uninstall --save @react-navigation/native
npm install --save @react-navigation/core@5.13.2 react-nativescript-navigation@2.0.1
```

**Comment by pavi2410** [comment]
Thank you so much @shirakaba @NathanaelA @rigor789 

Very much excited to try React NativeScript 🤗
