### ISSUE TITLE
✖ WARNING: There was a problem with CocoaPods   Verify that CocoaPods are configured properly.

### ISSUE THREAD

**Issue by dasarijit88** [NativeScript/nativescript-cli#5447]
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 11.0 (20A2411)
      Kernel Version: Darwin 20.1.0
      Time since boot: 21:20

 
 stderr: 
macOS version based on system_profiler is 11.0.
Looking for project in '/Users/arijitdas/Autility/Repository/test'
Project directory is '/Users/arijitdas/Autility/Repository/test'.
Initializing project identifiers. Config:  {
  id: 'org.nativescript.test',
  appResourcesPath: 'App_Resources',
  android: { v8Flags: '--expose_gc', markingMode: 'none' }
}
Loading extensions.
System information:
{
  "platform": "darwin",
  "shell": "/bin/zsh",
  "os": "Darwin Arijits-Mac-mini.local 20.1.0 Darwin Kernel Version 20.1.0: Sun Oct 18 15:32:00 PDT 2020; root:xnu-7195.41.8~9/RELEASE_ARM64_T8101 x86_64\n",
  "procArch": "x64",
  "nodeVer": "14.15.1",
  "npmVer": "6.14.8",
  "nodeGypVer": null,
  "nativeScriptCliVersion": "7.0.11",
  "gitVer": "2.24.3 (Apple Git-128)",
  "dotNetVer": null,
  "javacVersion": "15.0.1",
  "javaVersion": "15.0.1",
  "javaPath": "java",
  "adbVer": null,
  "androidInstalled": false,
  "monoVer": null,
  "gradleVer": null,
  "isAndroidSdkConfiguredCorrectly": false,
  "xcodeVer": "12.2.0",
  "xcodeprojLocation": "/usr/local/bin/xcodeproj",
  "itunesInstalled": false,
  "cocoaPodsVer": "1.10.0",
  "isCocoaPodsWorkingCorrectly": null,
  "isCocoaPodsUpdateRequired": false,
  "pythonInfo": {
    "isInstalled": true,
    "isSixPackageInstalled": true
  }
}
Current CLI version:  7.0.11
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command resolveCommand is before-resolveCommand
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command resolveCommand is after-resolveCommand
Could not find an installed runtime, falling back to default runtimes
Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal.
The stackTrace of the location trying to handle SIGINT is:
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:26:28)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:128:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:126:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:36:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:331:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/detached-processes/cleanup-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Shasum of file /Users/arijitdas/Autility/Repository/test/package.json is 93ed2b1c40849bdc0ef284a2b7fe088e26e9f8c7
Got cached result for shouldMigrate for platform: iOS
Could not find an installed runtime, falling back to default runtimes
Could not find an installed runtime, falling back to default runtimes
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command checkEnvironment is before-checkEnvironment
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Error while trying to parseJson  data from /Users/arijitdas/.local/share/.nativescript-cli/doctor-cache.json file. Err is: SyntaxError: Unexpected end of JSON input
getInfos cacheConfig options: { forceCheck: undefined }  current info from cache:  null
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Warnings:WARNING: There was a problem with CocoaPods',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 12.2.0 satisfies minimum required version 10.
✖ WARNING: There was a problem with CocoaPods 
 Verify that CocoaPods are configured properly. 

Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: false',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Your environment is not configured properly and you will not be able to execute local builds.
Select "Sync to Playground" to enjoy NativeScript without any local setup. All you need is a couple of companion apps installed on your devices.
Select "Configure for Local Builds" to run the setup script and automatically configure your environment for local builds.
Select "Skip Step and Configure Manually" to disregard this option and install any required components manually.
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Environment Requirements',
  label: 'User should select: Your environment is not configured properly and you will not be able to execute local builds.\n' +
    'Select "Sync to Playground" to enjoy NativeScript without any local setup. All you need is a couple of companion apps installed on your devices.\n' +
    'Select "Configure for Local Builds" to run the setup script and automatically configure your environment for local builds.\n' +
    'Select "Skip Step and Configure Manually" to disregard this option and install any required components manually.',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}

**Comment by dasarijit88** [comment]
Can someone please help me with the above error , I have tried following the instructions mentioned for the same issue but the error persists. I have attached the log trace , hope that helps to find the issue here

**Comment by sr3dna** [comment]
I encountered the same issue on a brand new m1 mac mini.   Trying to setup a NS7 environment from scratch before attempting to migrate my NS6 project.  

ns doctor:

✔ Getting environment information

There seem to be issues with your configuration.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.11 version and is up to date.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 12.3.0 satisfies minimum required version 10.
✖ WARNING: There was a problem with CocoaPods
 Verify that CocoaPods are configured properly.

Your environment is not configured properly and you will not be able to execute local builds.

I even tried:
arch -x86_64 brew cleanup -d -v
arch -x86_64 brew reinstall cocoapods

And there was no error reported:
==> Reinstalling cocoapods
==> Pouring cocoapods-1.10.0.big_sur.bottle.tar.gz
  /usr/local/Cellar/cocoapods/1.10.0: 13,120 files, 30.4MB

And if I run 'pod setup', it returns:
Setup completed

Is there any log I should check to see what problem ns doctor is complaining?  

Thanks,
Anders

p.s. My environment:   node:  v15.3.0,    ns: 7.0.11,  javac: 1.8.0_275,   npm: 7.0.14, xcode 12.3, homebrew: 2.6

**Comment by fossette** [comment]
I'm not familiar with the log so I don't know if this is an actual NativeScript bug or just a operating system library/package version compatibility issue.

However, I recognize the CocoaPods warning.  What help me is BernatC answer here:
https://stackoverflow.com/questions/64084111/sudo-gem-install-cocoapods-error-failed-to-build-gem-native-extension

**Comment by sr3dna** [comment]
Thanks!  But my mileage is different.  I followed those steps but the issue remains.  Is your machine using M1 chip?

**Comment by fossette** [comment]
> Is your machine using M1 chip?

No!  I rushed to buy the last Intel MacMini model because I value the possibility to boot Unix and Windows, as well as the possibility to run VirtualBox.

**Comment by sr3dna** [comment]
Good call.  I was hoping I could start coding using NS7 right away.  Looks like I will have to wait for awhile now.

**Comment by dasarijit88** [comment]
Does that mean there is no solution to this problem? I have tried reinstalling everything but the issue persists. is there any open issue regarding this?

**Comment by dasarijit88** [comment]
I have found the solution now .Hope it helps others facing the same issue 

- Close all open terminal
- Go to your applications folder and then utilities folder.
- Right click on terminal app and select "Get Info" 
- Check "Open Using Rosetta" option
- Open terminal
- sudo gem install cocoapods
- sudo gem install ffi
- Goto your project folder -->platforms-->iOS
- pod install

**Comment by denkan** [comment]
@dasarijit88 
Facing same issue with "WARNING: There was a problem with CocoaPods".

How can I complete your solution when there's no `platforms/ios` folder (due to NS won't build)?

**Comment by denkan** [comment]
Ok, after been messing around with this quite a bit, I just wanna share what I wish I'd found when researching this:

**My main problem:**
What's actually wrong with CocoaPods? 
How does `tns doctor` detect if anything's wrong?

Here's how i troubleshooted:

### Step 1: Make sure `pod` is runnable without issues:
Try:
```sh
$ pod --version
$ pod setup
```
If you get errors, research [how to get pod running on your machine](https://docs.nativescript.org/start/ns-setup-os-x).

### Step 2: Manually reproduce the steps `tns doctor` does to detect issues with CocoaPods.
By reading the tns script, I found out this is what actually happens:
1. NPM package `@nativescript/doctor` has a zipped example cocoapods folder (`/resources/cocoapods-verification/cocoapods.zip`).
2. Extracts its content into a temporary folder.
3. Tries to run `pod install` in this temporary folder.

Any issues along it's way = "WARNING: There was a problem with CocoaPods"

So, to manually do this:
1. Find where npm packages are globally installed:
```sh
$ npm list -g | head -1
# /Users/denkan/.nvm/versions/node/v12.18.2/lib
```
2. Find `@nativescript/doctor` folder.
```sh
$ cd /Users/denkan/.nvm/versions/node/v12.18.2/lib
$ cd node_modules/nativescript/node_modules/@nativescript/doctor
$ cd resources/cocoapods-verification/
```
3. Extract the `cocoapods.zip` and try install
```sh
$ unzip cocoapods.zip
$ cd cocoapods
$ pod install
```

### Step 3: Fix the real issue
When running `pod install` we can see any real issues with Cocoapods.

In my case, I got: 

> Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`

This lead me to [this issue](https://github.com/facebook/react-native/issues/30002), saying it's CocoaPods having problem with their CDN links/servers (😑)

#### My fix:
1. Append [the (temporary) fix](https://github.com/facebook/react-native/issues/30002#issuecomment-696594433) to the top of the `./cocoapods/Podfile`:
```
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
```
2.  Make sure it works: 
```sh
$ pod install
```
3. Zip the fixed cocoapods folder and replace `cocoapods.zip`
```sh
$ cd ..
$ mv cocoapods.zip cocoapods-old.zip
$ zip -r cocoapods.zip cocoapods
```
4. Re-run `tns doctor` without CocoaPods errors: 
```sh
tns doctor
```

Thank you, lord!

> ✔ CocoaPods are configured properly.
