### ISSUE TITLE
tns platform android is failing

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [NativeScript/nativescript-cli#5470]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.4
 - Cross-platform modules: No Such Modules
 - Android Runtime:
 - Plugin(s):No Plugin

**Describe the bug**
I ran `tns platform add android` and I get following error

    ubuntu@ubuntu-ck0xxx:~/Projects/nativescript/test$ tns platform add android
    Copying template files...
    Command failed: npm view @nativescript/android  dist-tags --json

**To Reproduce**
I setup the environment on ubuntu, created a fresh project and got error while adding android.

**Expected behavior**

It should add the platform

**Comment by rigor789** [comment]
Try running `npm view @nativescript/android  dist-tags --json` - this could fail for a few reasons unrelated to nativescript:
* connectivity issues to the npm registry
* npm registry temporary outage
* `npm` not installed (though unlikely, since you already installed the CLI using npm most likely).

**Comment by GAGANsinghmsitece** [comment]
I tried `npm view @nativescript/android dist-tags --json` and get

    {
       "rc": "7.0.1-rc1",
       "latest": "7.0.1",
       "next": "7.0.1"
     }
and the command is still failing, I also looked for node and my current version is `v12.19.0`

**Comment by rigor789** [comment]
How about `tns platform add android --log trace`?

**Comment by GAGANsinghmsitece** [comment]
i got following error in log:-

    Copying template files...
    Could not find an installed runtime, falling back to default runtimes
    Exec npm view @nativescript/android  dist-tags --json 
     stdout:  
     stderr: 
    Command failed: npm view @nativescript/android  dist-tags --json

    Error: Command failed: npm view @nativescript/android  dist-tags --json

    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:157:27)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:130:21)
    at NodePackageManager.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:104:30)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:12:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by NathanaelA** [comment]
Going to jump in here real quick as I run on linux also.   
1. Can you do a `whereis npm`
2. Are you running a standard bash shell or a different shell?
3. Can you close your terminal, open another terminal window (so it is fresh) then do the following command: `npm --version && tns platform add android`

**Comment by GAGANsinghmsitece** [comment]
I uninstalled npm which i installed from  apt and installed it again using nvm, and now it works fine
