### ISSUE TITLE
Resources Generate commands gone

### ISSUE THREAD

**Issue by hammelev** [NativeScript/nativescript-cli#5471]
- CLI: 7.1.2

Resources command is now longer available:

```
ns resources

The input is not valid sub-command for 'resources' command.
Run ns resources --help for more information.

ns resources --help

Unknown command 'resources'. Try '$ tns help' for a full list of supported commands.
```

This removes the ability to use the cli for generating icons and splashes i.e. resources generate splashes and resources generate icons.

**Comment by rigor789** [comment]
The commands should still work if you invoke them, why the help doesn't work for `ns resources --help` I don't know (did this even work before?)

```bash
ns resources generate icons --help
ns resources generate splashes --help
```
