### ISSUE TITLE
iOS on Windows?

### ISSUE THREAD

**Issue by NovaPikmin** [NativeScript/nativescript-cli#548]
Why can't I create iOS apps on Windows?

**Comment by RangerMauve** [comment]
Apple only let you compile iOS apps with XCode which is only available on Apple-made operating systems.

**Comment by Fatme** [comment]
Hi @NovaPikmin,

NativeScript CLI is able to create iOS apps only on OSX operating system. If you want to target `iOS` on Windows you can use AppBuilder - http://docs.telerik.com/platform/appbuilder/.

**Comment by NovaPikmin** [comment]
Then why was iOS on Windows hyped up on the original homepage?

**Comment by ligaz** [comment]
The original homepage was here: [http://www.telerik.com/nativescript](http://www.telerik.com/nativescript ) In the context of Telerik AppBuilder you can build iOS applications on Windows using browser and desktop based environments or our Visual Studio extension or AppBuilder CLI. 

Please give AppBuilder a try and share your feedback with us.
