### ISSUE TITLE
Problem with javac version

### ISSUE THREAD

**Issue by crowmagnumb** [NativeScript/nativescript-cli#5483]
**Environment**
Ubuntu 20.04 LTS
See below for NS versions.

**Describe the bug**

I have lately been getting this error that oddly just goes away for reasons I do not know, and then resurfaces (for instance, right now) and I can't get it to go away. I have both openjdk14 and openjdk 11 installed on my machine. I only installed 11 to try to get around this issue. So actually first off, is 14 really not supported? And secondly, how is it determining which version of javac? You can see below that my javac version in the same shell is reporting 11. I use the linux commands `sudo update-alternatives --config javac` and `sudo update-alternatives --config java` to configure this. Help I'm stuck. :) I've tried blowing away platforms and node_modules and even rebooting. Nothing is working.
```
$ ns doctor
✔ Getting environment information 

There seem to be issues with your configuration.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.1.2 version and is up to date.
✔ Component @nativescript/core has 7.1.4 version and is up to date.
⚠ Update available for component @nativescript/ios. Your current version is 7.0.4 and the latest available version is 7.1.1.
✔ Component @nativescript/android has 7.0.1 version and is up to date.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✖ Javac version 14.0.2 is not supported. You have to install at least 1.8.0 and below 13.0.0. 
 You will not be able to build your projects for Android.
To be able to build for Android, verify that you have installed The Java Development Kit (JDK) and configured it according to system requirements as
 described in http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-linux.html#system-requirements 
```
```
$ javac --version
javac 11.0.9.1
```

**Comment by crowmagnumb** [comment]
Ugh. Sorry, it was my JAVA_HOME env variable which is not changed with the above commands. :(
But still begs the question, is java 14 really not supported or is that an invalid check.  Cheers.

**Comment by NathanaelA** [comment]
@crowmagnumb - Ken, Java 14 probably works, but to my knowledge we haven't actually tested it "officially".

**Comment by crowmagnumb** [comment]
Well that same message appears `Javac version 14.0.2 is not supported. You have to install at least 1.8.0 and below 13.0.0` if you try to serve your app and it fails. So something is stopping it from even trying and I can't seem to find that in the source code.

**Comment by NathanWalker** [comment]
@crowmagnumb comes from here which is transient dep in the cli, you can post a PR to doctor to bump the max version - you can even modify locally in the compiled .js from your installed global cli... just search for the same ref constant.
https://github.com/NativeScript/nativescript-doctor/blob/f9a86ef934b90e8f96fbb413b03e9fc09079a0d6/lib/android-tools-info.ts#L44

We worked with someone else whom we bumped manually and Java 14 worked fine so a PR would be great.

**Comment by crowmagnumb** [comment]
Ah, well I wasn't looking in the right repo. :) I've made a PR for it.

**Comment by crowmagnumb** [comment]
[PR accepted](https://github.com/NativeScript/nativescript-doctor/pull/67).
