### ISSUE TITLE
Error that says, "WARNING: The Android SDK is not installed or is not configured properly"

### ISSUE THREAD

**Issue by JimLynchCodes** [NativeScript/nativescript-cli#5491]
I have been having issues for a very long time. I can't run ns with android. I don't know what to do.

When I run `ns run android` I get this vague warning (it should not be a warning if it prevents compilation btw...)

What exactly do I need to do in order to "install and configure the Android SDK properly"??? 😢

**Comment by JimLynchCodes** [comment]
ns info prints this:
```
Error while loading nativescript-cloud is: Default commands should be required before child commands
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.1.2 version and is up to date.
✔ Component @nativescript/core has 7.1.4 version and is up to date.
✖ Component @nativescript/ios is not installed.
✖ Component @nativescript/android is not installed.
```

Then I ran `npm i -g @nativescript/android`and `@nativescript/ios` since that's what the error is asking for.

It seems like nothing happened though. `tns info` still prints the same thing.

**Comment by rigor789** [comment]
This has been replied to here: https://github.com/NativeScript/nativescript-cli/issues/5487#issuecomment-772594433

Please don't open multiple issues about the same question, makes it much harder for us to keep track of them & respond.

**Comment by JimLynchCodes** [comment]
Thanks @rigor789 , but the guide you provided does not work. 

Can you please explain exactly what I should try in order to get back the error that calls itself a warning?

Please don't close my issues until they have been solved.

**Comment by JimLynchCodes** [comment]
Thanks for helping me through this @rigor789  👍

I wrote a [blog post on setting up a mac for NativeScript Android development](http://www.jimlynchcodes.com/blog/setting-up-a-mac-for-nativescript-android-development) so that I can do this again more easily in the future. Maybe it will help someone else who stumbles across this!

**Comment by JimLynchCodes** [comment]
bump 🙃
