### ISSUE TITLE
Getting started missing icon.png and icon@2x.png

### ISSUE THREAD

**Issue by Alber70g** [NativeScript/nativescript-cli#550]
I'm following this guide: http://docs.nativescript.org/hello-world/hello-world-ns-cli.html#3-you-can-quickly-check-how-your-blank-project-looks-like-in-the-emulator-or-on-device.

When running `tns run ios --emulator` there is a two times build failure:

```
The following build commands failed:
	CpResource helloworld/Resources/icons/icon.png build/emulator/helloworld.app/icon.png
```
The same is for `icon@2x.png`.

After copying and renaming `icon-40.png` and `icon-40@2x.png` it works.

**Comment by Fatme** [comment]
Hi @Alber70g,

Can you update your CLI to latest version - `npm update nativescript -g` and upgrade you project - here is the article that you can follow - https://github.com/NativeScript/NativeScript/issues/316 and try to execute `tns run ios --emulator` again?

**Comment by Alber70g** [comment]
@Fatme after updating it's still missing:

```
The following build commands failed:
	CpResource gemplanapp/Resources/icons/icon.png build/emulator/gemplanapp.app/icon.png
(1 failure)
Command xcodebuild failed with exit code 65
```

**Comment by Fatme** [comment]
@Alber70g I wasn't able to reproduce the issue. Can you send us the project for further investigation?

**Comment by Alber70g** [comment]
Everything is here https://github.com/Alber70g/tns-helloworld-error

**Comment by Fatme** [comment]
@Alber70g It seems that `hello world` template is not correctly downloaded.

Can you try to execute the following: 
1. `npm config get cache`
2. Open npm cache directory and delete `tns-template-hello-world` folder.
3. Create  new project and try run your application.

**Comment by Alber70g** [comment]
Great! It's working now. That is a bit strange that the directory is nog correct. But it's working. Thank you so much. 

Another question:
I've noticed that I cannot move or rename the directory of the project. Is there something I need to change inside the project?

**Comment by Fatme** [comment]
I'm glad that your issue was solved. 

If you want to rename your project directory you need to change the name in your package.json file. Also you need to remove and add again the installed platforms.
