### ISSUE TITLE
tns run android Invalid Version: ^6.5.3

### ISSUE THREAD

**Issue by donker** [NativeScript/nativescript-cli#5500]
**Environment**
 - CLI: 7.2.0
 - Cross-platform modules: 7.1.0
 - Android Runtime: 6.5.3
 - ns-Angular: 11.0.0

**Describe the bug**
When running tns prepare android or run android, the result is:

```
Error while loading nativescript-cloud is: Default commands should be required before child commands
Preparing project...
Invalid Version: ^6.5.3
```

I've tried 7.01 but the result is the same.

**To Reproduce**
Type "tns prepare ios" with the versions above.

**Expected behavior**
Builds project

**Additional context**
iOS builds without a problem.

**Comment by donker** [comment]
O wow. OK, that worked. I'm baffled as to how that is possible. But happy that it works! Thanks @rigor789

**Comment by rigor789** [comment]
I'll reopen this - as this is something that the CLI should handle.
