### ISSUE TITLE
Android build error - no matches found

### ISSUE THREAD

**Issue by Whip** [NativeScript/nativescript-cli#5506]
**Environment**
 - CLI: 7.2.1
 - Cross-platform modules: 7.2.1
 - Android Runtime: 7.0.1

**Describe the bug**
I'm trying to generate an aab file to upload to play store like I've done many times before but since a few weeks I run into this error. Earlier I got around it by wrapping my password in quotes but now even that is not working. Here's the command I'm using: (passwords are not real)

```
ns build android --release --key-store-path Resources/Keys/app-upload.jks --key-store-password qrCYaQTpKRaLPK3t --key-store-alias app-upload --key-store-alias-password o6@92QP5@wLjYM*h --aab --copy-to app-2.6.6.aab
```

I get error:
```
zsh: no matches found: o6@92QP5@wLjYM*h
```

I don't get it what's the matter here.

**Comment by rigor789** [comment]
Use `--key-store-alias-password "o6@92QP5@wLjYM*h"` - your terminal is trying to expand the `*` (zsh) and it can't, you need to wrap it in quotes to prevent zsh from expanding. This is not related to NativeScript.

**Comment by Whip** [comment]
I would like to share some of my learnings here in case someone else stumble into this problem. Like I said before the quotes used to work earlier but now they don't but @rigor789's comments gave me an idea to use `\` to escape the asterisk. This got my command to execute at least. 

Another option is to use
```
unsetopt nomatch
```
[Source](https://superuser.com/questions/584249/using-wildcards-in-commands-with-zsh)

Both of these later gave me an error: `cannot recover key`. This is happening because of a recent change in SDK tools or something causing special characters in passwords to cause headaches. So I changed my alias password using the `keytool`. This [tutorial](https://blog.blundellapps.co.uk/tut-change-alias-passwords-of-your-android-keystore/) helped me.

Everything works again.
