### ISSUE TITLE
Resolve

### ISSUE THREAD

**Issue by Butuhpakagsial** [NativeScript/nativescript-cli#5519]
**Environment**lib/services/webpack/webpack-compiler-service.ts
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:n
 - XCode Version:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by rigor789** [comment]
Please fill out the required details when opening an issue.
