### ISSUE TITLE
ns migrate not migrating to ns 8

### ISSUE THREAD

**Issue by ray007** [NativeScript/nativescript-cli#5529]
**Environment**
Project still on ns 7, gobal cli installation already updated:
 - CLI: 8.0.2
 - Cross-platform modules: 7.3.0
 - Android Runtime: 7.0.1
 - iOS Runtime: 7.2.0

**Describe the bug**
Following the blog post I installed nativescript 8 and tried the migration.
But `ns migrate` only tells me I could migrate, but does not do anything:
```
$ ns --version
8.0.2         
√ Up to date. 

$ tns migrate
Project is compatible with NativeScript v8.0.2

$ ns info
√ Getting NativeScript components versions information...
√ Component nativescript has 8.0.2 version and is up to date.
‼ Update available for component @nativescript/core. Your current version is 7.3.0 and the latest available version is 8.0.5.
‼ Update available for component @nativescript/ios. Your current version is 7.2.0 and the latest available version is 8.0.0.
‼ Update available for component @nativescript/android. Your current version is 7.0.1 and the latest available version is 8.0.0.
```
Not sure what's going wrong here and how to get more information on the problem.

**Comment by rigor789** [comment]
@ray007 please run `ns migrate --log trace` and look for migration related hints (should print why a migration may/may not be required), could give us a hint why it won't migrate (there's room for improvement with `migrate` in general, been refactoring it recently to be less strict when it comes to running older projects, and that may be in play here).

**Comment by ray007** [comment]
@rigor789 Thank you, I got a hint on discord to remove the `should-migrate-cache-8.0.2.json` file in the `...\AppData\Roaming\.nativescript-cli` directory, and the next try did start the migration.
Now working to make everything work again...
