### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/nativescript-cli#5540]
NS 8.0.7
Xcode 12.4
Node 14.11.0

Migrate an app to NS 8 and none of my app images are displayed.

Code is

`
<Page loaded="pageLoaded" class="page" xmlns="http://www.nativescript.org/tns.xsd">
	<ActionBar title="Home" class="action-bar"></ActionBar>
	<ScrollView>
		<StackLayout class="home-panel" verticalAlignment="top">
			<Image src="~/images/wfsl-logo.jpg" width="100" />
				<GridLayout rows="70, 70, 70, 70, 70,70" width="100%" horizontalAlignment="center">
			<Button text="Monday" tap="onMondayTap" class="button" row="0" />
			<Button text="Wednesday" tap="onWednesdayTap" class="button" row="1"/>
			<Button text="Settings" tap="onSettingsTap"  class="button" row="2" />
			<Button text="Help" tap="onHelpTap" class="button" row="3"/>
			<Button text="About" tap="onAboutTap"  class="button" row="4"/>
			<Label id="appVersion" text="" horizontalAlignment="center" marginTop="20" fontSize="12px" row="5" />
		</GridLayout>
		</StackLayout>
	</ScrollView>
</Page>
`

Path to images
![Screenshot 2021-06-10 at 16 59 35](https://user-images.githubusercontent.com/6585298/121558136-4bcc5500-ca0d-11eb-9166-811ca7023c48.png)

I've tried ~/app/images/wfsl-logo.jpg and /app/images/wfsl-logo.jpg but cannot get them to display.

XML pages are in the views folder/page name

so the page above is ~/app/views/home/home-page.xml

**Comment by rigor789** [comment]
The `images` folder is not being copied - by default `assets` will be copied, but if you want to copy the `images` folder, you need to configure the copy rule: https://docs.nativescript.org/webpack.html#adding-a-copy-rule

For example, something like this:
```js
webpack.Utils.addCopyRule('images/*')
```

**Comment by mrwrighty** [comment]
Still not getting the images to display. In the original project webpack.config.js I had

new CopyWebpackPlugin([
                { from: { glob: 'assets/**', dot: false } },
                { from: { glob: 'fonts/**', dot: false } },
                { from: { glob: '**/*.jpg', dot: false } },
                { from: { glob: '**/*.png', dot: false } },
            ], copyIgnore),

I've tried the line you suggest but still cannot get images to display in my compiled app. How do I know if they are copied during the build process.

**Comment by nikoTM** [comment]
@mrwrighty with the above copy rule (`webpack.Utils.addCopyRule('images/*');`), your images should be accessible using `~/images/*` (like `~/images/gear.png`) path

**Comment by janoshrubos** [comment]
@mrwrighty did these answers help to solve your issue?

**Comment by mrwrighty** [comment]
Sorry yes they did. Problem solved.

**Comment by janoshrubos** [comment]
@mrwrighty glad to hear it!
