### ISSUE TITLE
[webpack5] --env.uglify no longer supported?

### ISSUE THREAD

**Issue by jessorlisa** [NativeScript/nativescript-cli#5549]
**Environment**
 - CLI: `├── nativescript@8.0.2`
 - Cross-platform modules: `@nativescript/core@8.0.8`
 - Android Runtime: `├── @nativescript/android@8.0.0`
 - iOS Runtime: `├── @nativescript/ios@6.5.4` (**JSC**)
 - Plugin(s):
   `├── @nativescript/core@8.0.8`
   `├── @nativescript/types@8.0.1`
   `├── @nativescript/webpack@5.0.0-beta.15`

**Describe the bug**
As it seems the recommended optimization using Uglify.is no longer supported since NativeScript 8 and Webpack 5 (however documented):
https://docs.nativescript.org/performance.html#uglify-js

**To Reproduce**
Run `ns build android|ios --env.uglify` vs `ns build android|ios` --> no difference in app size.

**Expected behavior**
Either working or if no longer necessary with Webpack5 a clarification of the documentation 😃. Thanks in advance!

**Comment by rigor789** [comment]
`--release` + `--env.production` should minify the bundle, `--env.uglify` no longer works (it's enabled with `--env.production` and it uses Terser now, and is very much a legacy flag). 

The docs contain all the valid flags here: https://docs.nativescript.org/webpack.html#env-flags
(has been updated a little while ago, just not linked to this issue, so I'm going to close it)

**Comment by fpaaske** [comment]
Sorry for adding to this issue, but the docs you linked to says

--env.production - enable production mode (will minify the code)

I'm not sure this is working either (minify). I will double check when I'm back home, but I don't think I saw any noticeable difference with this flag enabled. At least not compared to --release.

**Comment by rigor789** [comment]
@fpaaske just checked, `--env.production` is enabled with the `--release` flag (https://github.com/NativeScript/nativescript-cli/blob/be6706af99c89765f3773e7e324a70037b2ec7b8/lib/services/webpack/webpack-compiler-service.ts#L376) so leaving it off makes no difference, the only case where it would is if you wanted to disable minification in a release build (for debugging etc.) - where you'd pass `--env.production=false` to disable it...

**Comment by fpaaske** [comment]
Thanks for checking!
