### ISSUE TITLE
iTunesConnect API needs to be updated

### ISSUE THREAD

**Issue by qnguyen18** [NativeScript/nativescript-cli#5553]
**Environment**
 - CLI: 8.0.1
 - Cross-platform modules: N/A
 - Android Runtime: N/A
 - iOS Runtime: N/A
 - XCode Version: 12.5.1
 - Plugin(s): N/A

**Describe the bug**
cli commands that require connecting with iTunesConnect, such as publishing an iOS app, fails. The cli tries to call this URL:

https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/v1/session/webSession

which now throws a 404.

**To Reproduce**
Publish the app to the apple store, or execute any command that interacts with the AppStoreConnect API.
Example:
> ns publish ios
> ns appstore 

**Expected behavior**
Running "ns publish ios" should upload the ipa file successfully to TestFlight.

**Additional context**
This worked around early July, 2021, and broke recently. Apple may have deprecated the API.

**work around**
Run the Xcode upload command directly in Terminal after the ipa file is generated:

> xcrun altool --upload-app -f <PathToFile>.ipa -u <Username> -p <Password>

**Comment by mhchristensen** [comment]
I'm noticing the exact same thing starting at about the same time.  At first the account was having problems even accessing apps on appstoreconnect website.  This led me to think that maybe its a problem on Apple's side that may get resolved.    That url has been used for a long time and I couldn't find any note that the API was deprecated.

**Comment by p-smith1** [comment]
I'm having this exact same issue as reported by @qnguyen18.

**Comment by DevZatokio** [comment]
I have the same error, some solution?

**Comment by rigor789** [comment]
@DevZatokio see in the issue there's a workaround: 

> **work around**
> Run the Xcode upload command directly in Terminal after the ipa file is generated:
>
>   xcrun altool --upload-app -f .ipa -u -p

**Comment by DevZatokio** [comment]
I was generating .ipa after that, I left xcodeproj, I left the file and it worked for me to load it, I checked it with TestFlight

**Comment by michael-dots** [comment]
Any update? I'm using Transporter (Apple's upload app on appstore that replaced application loader) at the moment while waiting for a fix.

**Comment by shilik** [comment]
> Any update? I'm using Transporter (Apple's upload app on appstore that replaced application loader) at the moment while waiting for a fix.
> 
> Just to help others googling this, the error i get is an empty error like this following after build / export finishes:
> The server returned unexpected response:

Got the same error too!
