### ISSUE TITLE
`ns resources generate icons` - cli script update needed to support latest Android vector graphic launchers.

### ISSUE THREAD

**Issue by LaKing** [NativeScript/nativescript-cli#5571]
**Environment**
zsh on macOS Catalina 10.15.7

✔ Component nativescript has 8.0.1 version and is up to date.
✔ Component @nativescript/core has 8.0.3 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 8.0.0 version and is up to date.

**Describe the bug**
Created icon.png with 1024x1024 size.
```
tns resources generate icons ~/icon.png
Generating icons ...
Icons generation completed.
```
.. however, Android icons did not get created. Even when creating the mipmap icons, they don't get applied and the nativescript icon is associated with the app. No error messages.
Splashes are generated correctly.

**Expected behavior**
The launcher icon should be generated from the image.

**Comment by joshcomley** [comment]
Any update on this? Or is there an alternative way to generate icons?

**Comment by pierremacedo** [comment]
> Any update on this? Or is there an alternative way to generate icons?

I'd say the best alternative is to move to React Native cause bugs are fixed faster there, but if that's not possible, you can use this website https://apetools.webprofusion.com/#/tools/imagegorilla.
