### ISSUE TITLE
Support build.xcconfig in /app/App_Resource/iOS folder

### ISSUE THREAD

**Issue by ligaz** [NativeScript/nativescript-cli#558]
It would be good if we pick up custom `build.xcconfig` file from the `/app/App_Resource/iOS`. This will allow developers to keep this file under source control without the need to modify it in the `/platforms/ios`.

**Comment by Mitko-Kerezov** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/478

**Comment by PanayotCankov** [comment]
Then you can add to your project:

- `app/App_Resources/iOS/Images.xcassets`
- `app/App_Resources/iOS/build.xcconfig`

And use icons and launch images from the xccassets by setting the following flags in the `build.xcconfig`:
```
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = Brand Assets;
```
