### ISSUE TITLE
ipa file not found error during device builds

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-cli#5585]
My `tns info` results.

✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.7.8 and the latest available version is 8.1.3.
✔ Component tns-core-modules has 6.5.27 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.
✔ Component tns-ios has 6.5.4 version and is up to date.

Doing a build `tns build ios --for-device --env.uglify --release --provision "xxxx"` and getting the following error

```
** EXPORT SUCCEEDED **

Project successfully built.
No .ipa found in /Users/mini/Projects/xxx/platforms/ios/build/Release-iphoneos directory.
```

There's an .ipa file in the folder.

My xcode version is 12.5.1 and I would prefer not to update.

I'm using NS 6 and have added the fixes on [How to Fix NativeScript Issue with iOS14 and XCode 12](https://timleland.com/how-to-fix-nativescript-issue-with-ios14-and-xcode-12/)

**Comment by erjdriver** [comment]
I went back to the latest CLI and doing a simulator build 

`tns --force build ios`

and getting the following error in red

```
cp: no such file or directory: /Users/mini/Projects/xxx/App_Resources/iOS/*
```

That folder structure is different than what I have for NS 6.*  /Users/mini/Projects/xxx/app/App_Resources/iOS/*

My `tns info`

```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.1.3 version and is up to date.
✔ Component tns-core-modules has 6.5.27 version and is up to date.
✔ Component tns-ios has 6.5.4 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.
```

**Comment by rigor789** [comment]
You may need to explicitly set `appResourcesPath` to `app/App_Resources` in the nsconfig, I believe that should work

**Comment by erjdriver** [comment]
Curiously my nsconfig.json file is empty - should I delete it?

But I've got a tsconfig.json file

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "allowUnreachableCode": true,
        "esModuleInterop": true,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

Where do I need to put this `appResourcesPath`?

**Comment by erjdriver** [comment]
Thanks - that solved the problem.

Curiously - my nsconfig.json file was blank.

I added your suggestion and now even the iphone device build works.
