### ISSUE TITLE
[IOS]Unexpected duplicate tasks

### ISSUE THREAD

**Issue by kfathy-ys** [NativeScript/nativescript-cli#5586]
**Environment**

 - CLI: 8.1.3
 - Cross-platform modules: nativescript-angular-cli
 - Android Runtime: 
 - iOS Runtime: 
 - XCode Version: 13.0
 - Plugin(s):

**Describe the bug**
When run command tns build ios it finally give the following error:

error: Unexpected duplicate tasks:
1) Target 'IPA' (project 'IPA'): CodeSign /Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework
2) Target 'IPA' (project 'IPA'): CodeSign /Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework
error: Multiple commands produce '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework':
1) Target 'IPA' has copy command from '/Users/admin/IPA/node_modules/@nativescript/core/platforms/ios/TNSWidgets.xcframework/ios-arm64_x86_64-simulator/TNSWidgets.framework' to '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework'
2) Target 'IPA' has copy command from '/Users/admin/IPA/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework' to '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework'

error: Multiple commands produce '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework/TNSWidgets':
1) Target 'IPA' has copy command from '/Users/admin/IPA/node_modules/@nativescript/core/platforms/ios/TNSWidgets.xcframework/ios-arm64_x86_64-simulator/TNSWidgets.framework' to '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework'
2) Target 'IPA' has copy command from '/Users/admin/IPA/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework' to '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework'

warning: duplicate output file '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework' on task: PBXCp /Users/admin/IPA/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework /Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework (in target 'IPA' from project 'IPA')
warning: duplicate output file '/Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework/TNSWidgets' on task: PBXCp /Users/admin/IPA/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework /Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework (in target 'IPA' from project 'IPA')
warning: duplicate output file '' on task: PBXCp /Users/admin/IPA/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework /Users/admin/IPA/platforms/ios/build/Debug-iphonesimulator/IPA.app/Frameworks/TNSWidgets.framework (in target 'IPA' from project 'IPA')
/Users/admin/IPA/platforms/ios/IPA.xcodeproj: warning: Building for iOS Simulator, but the linked and embedded framework 'TNSWidgets.framework' was built for iOS + iOS Simulator. (in target 'IPA' from project 'IPA')

--------------------------------------------------------------------------------------------------------------------------
Package.json

{
  "name": "@nativescript/template-hello-world-ng",
  "main": "./src/main.ts",
  "version": "8.0.7",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "App_Resources",
    "hooks",
    "src",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "references.d.ts",
    "tsconfig.json"
  ],
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@nativescript/angular": "~12.0.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/core": "~8.0.0",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/localize": "^5.0.4",
    "@nativescript/schematics": "^11.2.0",
    "@nativescript/theme": "~3.0.1",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "nativescript-angular-cli": "^0.1.9",
    "nativescript-drop-down": "^6.0.0",
    "nativescript-splashscreen": "^2.3.0",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-ui-listview": "^10.0.0",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~12.0.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~12.0.0",
    "typescript": "~4.2.0"
  },
  "private": "true",
  "readme": "NativeScript Application",
  "discardUncaughtJsExceptions": false
}

**Comment by rigor789** [comment]
Please post your `package.json` - I suspect you have both `tns-core-modules` and `@nativescript/core` installed, and their versions are mismatched.

**Comment by kfathy-ys** [comment]
{
  "name": "@nativescript/template-hello-world-ng",
  "main": "./src/main.ts",
  "version": "8.0.7",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "App_Resources",
    "hooks",
    "src",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "references.d.ts",
    "tsconfig.json"
  ],
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@nativescript/angular": "~12.0.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/core": "~8.0.0",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/localize": "^5.0.4",
    "@nativescript/schematics": "^11.2.0",
    "@nativescript/theme": "~3.0.1",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "nativescript-angular-cli": "^0.1.9",
    "nativescript-drop-down": "^6.0.0",
    "nativescript-splashscreen": "^2.3.0",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-ui-listview": "^10.0.0",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~12.0.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~12.0.0",
    "typescript": "~4.2.0"
  },
  "private": "true",
  "readme": "NativeScript Application",
  "discardUncaughtJsExceptions": false
}

**Comment by rigor789** [comment]
`"nativescript-splashscreen": "^2.3.0",` is outdated, it pulls in `tns-core-modules` and is generally pretty outdated. You will need to remove it/replace it. Here's how you can achieve similar effects https://blog.nativescript.org/angular-launch-animations/index.html
