### ISSUE TITLE
tns debug ios command should download and open WebKit nightly 

### ISSUE THREAD

**Issue by KristinaKoeva** [NativeScript/nativescript-cli#561]
The update of JavaScriptCore requires new updated Web Inspector frontend which uses UI features that are not yet supported in the official Safari release, so we should open WebKit nightly instead

**Comment by ligaz** [comment]
Can you share more details about the features that are not yet supported?

**Comment by teobugslayer** [comment]
We talked to @KristinaKoeva in person and she informed me that they are implementing a different approach. Once they are ready, she'll close this PR and open a different one.

**Comment by teobugslayer** [comment]
Closing this one, as it will be reimplemented.
