### ISSUE TITLE
nativescript cli isnt identified after instalation.

### ISSUE THREAD

**Issue by Betryx** [NativeScript/nativescript-cli#5687]
### Issue Description

when i try running `ns <command>` as an example `ns create patron --js` or any other command of the nativescript cli, 
i get an error message that says ns isnt identified:

Output:
     `ns: The term 'ns' is not recognized as a name of a cmdlet, function, script file, or executable program.
      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

![outp](https://user-images.githubusercontent.com/79721643/182033642-3a4709f2-9bbc-46e2-adb4-551be2c6cbb2.png)

### Relevant log output (if applicable)

```shell
Output:
     `ns: The term 'ns' is not recognized as a name of a cmdlet, function, script file, or executable 
      program.
      Check the spelling of the name, or if a path was included, verify that the path is correct and try 
       again.`
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Make sure you have installed everything as noted in the setup guide 

https://docs.nativescript.org/environment-setup.html#windows-android

**Comment by Betryx** [comment]
everything is installed as it should be via the guide, but still doesnt work

**Comment by rigor789** [comment]
Is your npm set up correctly? The global install dir should be in your Environment Variables/Path - can't really give exact steps to fix as it depends on the way you installed nodejs.

**Comment by Betryx** [comment]
yes my npm is installed corectly.

**Comment by rigor789** [comment]
Ok, so npm is good, run `npm -g prefix` and make sure that path + `/bin` is in your PATH variable. 

For example:
```bash
$ npm -g prefix

/Users/rigor789/.nvm/versions/node/v18.3.0
```

So I have 
```
/Users/rigor789/.nvm/versions/node/v18.3.0/bin
```
in my PATH.

(my example is from a macos machine, but the only difference would be the actual path).

Once you are certain the path is in your system PATH (environment variable), then restart your terminal to pick up the environment changes, and see if `ns -v` works.

_And just to add, this has nothing to do with `ns` specifically, it's a standard globally installed node module which you are having trouble with - adding this just to help with your search._

**Comment by anterof5** [comment]
Worked for me: https://stackoverflow.com/questions/44958847/message-the-term-ng-is-not-recognized-as-the-name-of-a-cmdlet
