### ISSUE TITLE
The webpack configuration file does not exist

### ISSUE THREAD

**Issue by boutier** [NativeScript/nativescript-cli#5727]
### Issue Description

With `ns --version`: `8.5.2`
Angular projects created with `ns create test --ng` doesn't have webpack configuration file.

(Workaround is to copy/paste code from https://docs.nativescript.org/webpack.html)

### Reproduction

`ns create test --ng`

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Fixed in https://github.com/NativeScript/nativescript-cli/pull/5729

Available in 8.5.3
