### ISSUE TITLE
TARGETED_DEVICE_FAMILY not respected with NS7

### ISSUE THREAD

**Issue by maxorlovsky** [NativeScript/nativescript-cli#5733]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.2.1 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 7.1.4 and the latest available version is 7.3.0.
⚠ Update available for component @nativescript/ios. Your current version is 7.1.1 and the latest available version is 7.2.0.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

**Describe the bug**
TARGETED_DEVICE_FAMILY in build.xcconfig worked with NS6, with NS7 it seems to be ignored as in project files of iOS it is set to TARGETED_DEVICE_FAMILY = "1,2";

**To Reproduce**
Just build the app and open xproj files or project in xcode

**Expected behavior**
Project is targeting one device that specified.

**Comment by NathanWalker** [comment]
I moved this to CLI and put on 8.6 milestone to clear - possible we may be able to clear in a patch though.

**Comment by edusperoni** [comment]
maybe it's the same case as this: https://github.com/NativeScript/nativescript-cli/pull/5728

I think we might need to reconsider the build.xcconfig merge strategy @rigor789
