### ISSUE TITLE
Error message after upgrading to CLI 8.5.3

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-cli#5736]
### Issue Description

 just upgraded the cli to Nativescript 8.5.3 (I know old)

I'm starting to get errors on certain command tns commands. Error is

`Unexpected token '.'` in red.

Getting the error for command `tns platform remove ios` and other commands also.

Previous installed version was 8.3.2.

npm 6.14.5 node v12.18.1

### Reproduction

Fulls-Mac-mini:mobile mini$ tns info
You are using the deprecated nsconfig.json file. Just be aware that NativeScript now has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.5.3 version and is up to date.
✔ Component tns-core-modules has 6.5.27 version and is up to date.
⚠ Update available for component tns-ios. Your current version is 6.5.5 and the latest available version is 6.5.6.
✔ Component tns-android has 6.5.3 version and is up to date.
Fulls-Mac-mini:mobile mini$ tns platform remove ios
You are using the deprecated nsconfig.json file. Just be aware that NativeScript now has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Update your node to at least 14+, for example the latest LTS release (`18.16.0`)

**Comment by erjdriver** [comment]
Worked!
