### ISSUE TITLE
[Android] Log stop when app killed and relaunched

### ISSUE THREAD

**Issue by kefahB** [NativeScript/nativescript-cli#5739]
### Issue Description

Hi,

The CLI stop logging on android when we kill the app and relaunch it again, this happen on real device.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
This is a limitation with how it's currently filtering logs based on the spawned process id (pid). We could/should likely switch to filtering based on the package id instead, so we can keep showing logs even after the app is killed/restarted manually on the device.
