### ISSUE TITLE
Can't run the Hello World App

### ISSUE THREAD

**Issue by LeoLR** [NativeScript/nativescript-cli#576]
Hi guys! 

I start to use nativescript today and i've some problems... 
When i try to run my project on my device that doesn't work... 
When i try "tns run android":

![prtscr capture](https://cloud.githubusercontent.com/assets/10087588/8253388/88dc99d8-168f-11e5-952d-6d0055e14aa0.jpg)
![administrateur cwindowssystem32cmd exe_2](https://cloud.githubusercontent.com/assets/10087588/8253371/6030ba8c-168f-11e5-9ff3-085c611991f9.jpg)

If someone have a idea or need more informations! ;)

Thank's

**Comment by Fatme** [comment]
Hi @LeoLR,

You can check this thread - http://stackoverflow.com/questions/6676107/unable-to-locate-tools-jar

**Comment by rosen-vladimirov** [comment]
Hi @LeoLR ,
As @Fatme pointed, you have to install JDK, not JRE (you can check our [system requirements](https://github.com/NativeScript/nativescript-cli#windows) for more information. Please make sure to use at least JDK 8 and inform us if this works for you :)

**Comment by LeoLR** [comment]
Yeah my bad, i've write the wrong path for JAVA_HOME... Now i've this: 

![administrateur cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/10087588/8253757/fe8ae114-1692-11e5-9f08-9c3a9929fdfe.jpg)
![administrateur cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/10087588/8253763/0babd060-1693-11e5-8394-1101a41ff01d.jpg)

Thank's for your help! :)

**Comment by rosen-vladimirov** [comment]
Hi @LeoLR ,
It looks like there's a known issue in the latest Android SDK Build tools. You can find a workaround for it in [this SO thread](http://stackoverflow.com/questions/30812770/ant-jar-error-execute-failed-java-io-ioexception-cannot-run-program-aapt) It was also discussed [here](https://github.com/NativeScript/NativeScript/issues/328)

Could you try this approach and see if it works for you?

**Comment by LeoLR** [comment]
God! Would you marry me @rosen-vladimirov ?! :ring: :smile: 
The first thread was the good! :+1:  

Thank you so much!

**Comment by rosen-vladimirov** [comment]
I'm glad we were able to resolve the issue.

P.S. Sorry that I'll have to disappoint you, but my heart is whispering "NativeScript", "NativeScript", "NativeScript".

**Comment by LeoLR** [comment]
Maybe one day...!
