### ISSUE TITLE
Implement plugin init command

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#586]
# Implement plugin init command
## Background

Developing of NativeScript plugins may be a daunting task, especially for newcomers.
On the other hand, advanced users want to boost their productivity.
To satisty their needs, we need to provide an easy to use, interactive way to create NativeScript plugins.
To grasp the plugins infrastructure, read the [plugins docs](http://docs.nativescript.org/plugins/plugins).
## Tasks
- Create `plugin init` command in the CLI 
- {N} plugins are npm packages, therefore, interactively call out `npm init` to create the package.json and the plugin structure sceleton.
- Ask interactively for {N}-specific data to fill in the package.json. Make sure to have sane defaults for {N} modules and runtimes as dependencies, i.e. compatible version with the current CLI. 
- Ask for optional configuration for Android development
  - Ask to create or copy existing `.aar` file.
  - Ask to copy existing .jar files
  - Ask to copy existing or create a dummy include.gradle file
- Ask for optional configuration for iOS development
  - Ask to create a dummy or copy existing Info.plist
  - Ask to copy optional native iOS dynamic frameworks
  - Ask to create or copy an optional Podfile
- Ask for optional platform-specific .js files. See [UI Plugins](http://docs.nativescript.org/plugins/ui-plugin).
- Write accompanying documentation. Make sure both HTML and console help works and is integrated with other help topics.
- Write accompanying unit test.

**Comment by vchimev** [comment]
It would be beneficial if the command also asks to create optional sample/demo app and unit tests. CC: @dtopuzov

**Comment by Plamen5kov** [comment]
Because with the 2.0 release the android plugins will need to contain only `.aar` files, cli can help with the generation of those files as is already proposed.

**Comment by pkoleva** [comment]
Closed in favor of [1945](https://github.com/NativeScript/nativescript-cli/issues/1945)
