### ISSUE TITLE
Enable plugin user input for plugin configurations

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#591]
I'm creating a plugin which uses the Google APIs and I need to specify my API_KEY which should be used from the application.

I'm not sure where is the best place to specify this, but at the end it should be part of the ApplicationManifest.xml file for the Android runtime.

I see two options for this - to enable the tooling to "ask" for user input (in my case to ask for the proper API_KEY in the console) or the option would be allow some kind of a configuration file for the plugin which can be read by the CLI.

Do we know how this problem is solved in NPM?

**Comment by valentinstoychev** [comment]
I guess we can create an experience similar to how "npm init" works - e.g. asking predefined questions and then validating them and applying the values as configuration.

**Comment by ligaz** [comment]
We have introduced plugin variables support with version `1.4`: https://github.com/NativeScript/nativescript-cli/issues/882
