### ISSUE TITLE
Implement a hard dependency on the node.js version and exit if not satisfied

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#594]
We are currently logging a WARN when we run in an older version of Node.JS, but I think we need to stop the execution of the command if there is an older version of Node.js installed, otherwise some of the commands simply do not work. I hit an issues with the platform add command under Windows which prevented adding the Android platform at all. @rosen-vladimirov  is aware of this.

**Comment by dtopuzov** [comment]
With latest behavior we do WARN on each command if Node version is not in supported versions.
