### ISSUE TITLE
Documentation: Add and article that explains how to create a plugin with UI declaration

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#595]
We need an article that explains the steps of creating a plugin which contains UI components and how to use it in XML, how to add documentation for the plugin API, how to define multiple UI components, how to create TS definitions, how to write cross-platform and platform-specific code, etc.

**Comment by atanasovg** [comment]
I am working on this currently: NativeScript/NativeScript#461.

**Comment by ligaz** [comment]
@valentinstoychev Do you think it is a good idea to log those documentation issues in the docs repo?
