### ISSUE TITLE
`tmp` folder not created in root

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#599]
Hey all,

@jlooper and I discovered some strange behavior when working with the v1.1 CLI. `tns run` now creates a `tmp` folder in the folder you execute the command from.

The problem with this is: if you execute `run` from multiple folders, which I do with my [Sublime Text workflow](http://developer.telerik.com/featured/a-nativescript-development-workflow-for-sublime-text/), you end up with multiple copies of this `tmp` folder. This has a performance impact, as the CLI has to build `tmp` multiple times, and it's also just kind of strange.

Unless I'm missing something, it seems like `tmp` should always be created in the root of the project, regardless of the subfolder you execute `run` in.

Thanks.

**Comment by Fatme** [comment]
Hi @tjvantoll,

Here is the PR that fixes this issue - https://github.com/NativeScript/nativescript-cli/pull/593.  
We've improved our logic when preparing `node_modules` and don't need `tmp` directory anymore.
The fix will be included in our 1.1.2 release which is planned for the next week.
