### ISSUE TITLE
A script to set up Mac machine for developing with NativeScript

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#625]
Create a script which sets up a novice user's machine to be ready to work with NativeScript.

This should install all dependencies of Android SDK and node.js, asks the user to install Xcode, and finally, install the latest release of NativeScript CLI.

This feature targets only Macs with Yosemite or newer OS version.

**Comment by Alphapage** [comment]
Hello,
Those issues are under 1.5 milestone:
https://github.com/NativeScript/nativescript-cli/issues/955
https://github.com/NativeScript/nativescript-cli/issues/978

But I think those need to be solved before providing such a script, so I think previous issues should exist under 1.4 milestone.
I also think you can't wait milestone 1.5 release to fix nativescript-cli with xcode 7 problems.

**Comment by vchimev** [comment]
Related issue: https://github.com/NativeScript/nativescript-cli/issues/988.

**Comment by ligaz** [comment]
Happily closing this one :tada:
