### ISSUE TITLE
Unable to run emulate --geny <GenyName>

### ISSUE THREAD

**Issue by unlight** [NativeScript/nativescript-cli#627]
GenyMotion was installed by chocolatey.

`genyshell.exe -c "devices list"`
```
 Id | Select |    Status     |   Type   |   IP Address    |      Name
----+--------+---------------+----------+-----------------+---------------
  0 |    *   |            On |  virtual |  192.168.56.101 | CustomPhone
  1 |        |           Off |  virtual |         0.0.0.0 | Google Nexus 4 - 4.2.2 - API 17 - 768x1280
```
`tns emulate android --geny CustomPhone`
Error: spawn emulator ENOENT

Environment: 
```js
tns --version: 1.1.1
node --version: v0.12.6
genymotion: 2.4.0
Windows 8.1 
```

**Comment by teobugslayer** [comment]
Hello @unlight,

please run ```tns emulate android --geny CustomPhone --log trace > log.txt``` and send us the log.txt file. You may create a gist, for example.

**Comment by unlight** [comment]
Here it is.
https://gist.github.com/unlight/4f569b128846b3ea2d87

**Comment by Fatme** [comment]
Hi @unlight ,

It seems that Genymotion installation dir is not included to your PATH environment variable. You can find more information here - https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/project/testing/emulate-android.md#prerequisites

**Comment by unlight** [comment]
@Fatme, many thanks. It works now.
