### ISSUE TITLE
Prepare does not work correctly if you have npm module and tns plugin in same project

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#629]
Steps to reproduce:
tns create TestApp
cd TestApp
tns platform add android
tns plugin add nativescript-social-share 
tns prepare -> everything is fine at this point
npm install nativescript-appversion --save
tns prepare -> In platforms/android/assets/app/tns_modules/nativescript-social-share all js files are missing.

**Comment by rosen-vladimirov** [comment]
As a workaround you can delete node_modules directory before preparing the project (after `npm install <...> --save`. This way everything will be prepared correctly.
