### ISSUE TITLE
tns run/deploy does not check the target version of the device and continues with no error

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#630]
If you have an app that targets a newer SDK version the CLI should not try to deploy the app but fail with an error message that this app can't be installed on the device. 

Currently it silently tries to run the app and shows the logcat but no app is started on the device.

**Comment by dtopuzov** [comment]
Fixed in {N} 2.0.1. Warning message is:
The new package failed because the current SDK version is older than that required by the package.
