### ISSUE TITLE
Android debugger does not work on some OSX systems

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#632]
Moved https://github.com/NativeScript/android-runtime/issues/143 to CLI project

**Comment by nmladenov** [comment]
tns debug android --debug-brk not working with attached device. No debugger started, error is thrown. Commented with NS QA team repproducible on their side too. "Command ant failed with exit code 1"

**Comment by dtopuzov** [comment]
If name of Chrome Executable is not "Google Chrome" you should change ANDROID_DEBUG_UI_MAC entry in config/config.json in order to get debugger working.

**Comment by vchimev** [comment]
Android debugger does not work when "ANDROID_DEBUG_UI_MAC": "Google Chrome" specified in config/config.json and Chrome executable is "Google Chrome".

**Comment by teobugslayer** [comment]
The issue was that the fix was only in master branch. I ported it to release as well and the bug is ready for testing.
