### ISSUE TITLE
Customize developer tools --debug-brk port

### ISSUE THREAD

**Issue by punter82** [NativeScript/nativescript-cli#633]
Currently the dev tools debugger console opens by default with 8080 port. It would be great if we can customize that in the command line itself. 8080 is traditionally used by tomcat. We can change the tomcat port but would be nice if we have command line option in native script. Thanks

**Comment by Fatme** [comment]
Hi @punter82,

You can use `tns debug android --debug-brk --debug-port <your port>` command

**Comment by punter82** [comment]
Thanks for your help.
