### ISSUE TITLE
[iOS] Add options to build with different certificate/provisioning

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#635]
In order to build {N} app for app store users need an option to specify different certificate/provisioning

**Comment by vchimev** [comment]
:+1:

**Comment by ligaz** [comment]
This can be configured using `xcconfig` files. Also we will be implementing a publish https://github.com/NativeScript/nativescript-cli/issues/1172 command for such kind of scenarios.
