### ISSUE TITLE
tns plugin add not copying node_modules to tns_modules

### ISSUE THREAD

**Issue by anarchicknight** [NativeScript/nativescript-cli#637]
I have been trying to update my texttospeech module to work as a plugin.

I followed guides on the native script site and also looked at TJ's flashlight plugin as a guideline.

However, when I install my plugin in my demo app it gets added to the node_modules folder but nothing seems to go across to the tens_modules folder. When running the app I then get an error that the required file could not be found.

Has anyone else had this issue, or have I made a schoolboy error?

Repo is https://github.com/anarchicknight/nativescript-texttospeech

**Comment by Fatme** [comment]
Hi @anarchicknight,

Are you using the latest version of {N} CLI? If yes, I suggest you to delete `node_modules` folder and execute `tns prepare` command.

**Comment by anarchicknight** [comment]
Thanks for the response.

I'm on v1.1.2.

I deleted the node_modules folder and ran 'tns prepare ios'

All this did was add the node_modules folder back in and nothing new appeared in tns_modules.

Then running 'tns run ios --emulator' saw the app launch and then crash complaining that it could not find my plugin name I required. It was looking in the tns_modules folder

**Comment by tjvantoll** [comment]
Hey @anarchicknight,

Could you try `rm -rf platforms/ios` and `tns platform add ios` and see if NativeScript can resolve the path after that? I think there's currently a bug where new plugins don't get recognized until you add platforms but it'd be good to have someone verify that.

You'll know the install works when your plugin makes it into `platforms/ios/[project-name]/app/tns-modules/[plugin-name]`.

**Comment by anarchicknight** [comment]
thanks TJ - removing the platforms and adding them in again worked.

Looks like there is definitely a bug there then. Do you know if the issue is already raised or do you want me to put one in?

**Comment by anarchicknight** [comment]
Closing this and raised a new issue with specifics of the bug #669

**Comment by tjvantoll** [comment]
Thanks!

**Comment by mnesarco** [comment]
{N} 1.7.0 

I have the same issue, but removing and adding platform does not fix the problem.

I have a plugin inside the root folder, I have added it with tns plugin add [myplugin], the plugin is copied to node_modules and registered in package.json, but the App crashes with error:

Module /data/data/[package]/files/app/tns_modules/[myplugin] not found ...

**Comment by Mutantmannen** [comment]
Having this problem using Telerik AppBuilder in Visual Studio. Is there a way to work around it?

**Comment by Robophil** [comment]
this is for confirming if the plugin would work for ios`platforms/ios/[project-name]/app/tns-modules/[plugin-name].`, what of android? @tjvantoll

**Comment by YouYII** [comment]
I encountered this problem again

> $ ls platforms/android/src/main/assets/app/tns_modules/
> common                   core                     http                     platform-browser-dynamic
> compiler                 forms                    platform-browser         router

Get this error
> An uncaught Exception occurred on "main" thread.
> java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
> 
> Error calling module function 
> 
> Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/platform", relative to: app/tns_modules/
    > com.tns.Module.resolvePathHelper(Module.java:159)
    > com.tns.Module.resolvePath(Module.java:60)
    > com.tns.Runtime.runModule(Native Method)
    > com.tns.Runtime.runModule(Runtime.java:514)
    > com.tns.Runtime.run(Runtime.java:509)
    > com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    > android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
    > android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
    > android.app.ActivityThread.access$1500(ActivityThread.java:144)
    > android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
    > android.os.Handler.dispatchMessage(Handler.java:102)

> tns --version
> 2.4.1

I tried the following command
> $ rm -rf node_modules && rm -rf platform 
> $ tns prepare android
> Copying template files...
> Project successfully created.
> Executing before-prepare hook from /Users/zy/Workspaces/EasyReader/hooks/before-prepare/nativescript-dev-android-snapshot.js
> Executing before-prepare hook from /Users/zy/Workspaces/EasyReader/hooks/before-prepare/nativescript-dev-sass.js
> Executing before-prepare hook from /Users/zy/Workspaces/EasyReader/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.1.1
> Bus error: 10
> $ tns run android

But wrong again.This problem has been bothering me for two days...
