### ISSUE TITLE
Propagate {N} project version into the native projects

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#639]
Propagate {N} project version into the AndroidManifest.xml (for Android) and .lproj file (for iOS).

Client request:

Hello,
Is there somewhere in the {N} project that I can specify a version and build number which will be propagated into the AndroidManifest.xml (for Android) and .lproj file (for iOS), so that builds will get that version and build number?  And further to that, how can I retrieve the version and build number to display it in my app?
Thanks!

**Comment by mdgiles** [comment]
There should be a build number as well as a version number. AndroidManifest.xml and lproj file have both.

**Comment by sitefinitysteve** [comment]
I would really like this...it's endlessly irritating to set my project.json version for no apparent reason as the apps all nativly build to v1.0

**Comment by ligaz** [comment]
Merged into: https://github.com/NativeScript/nativescript-cli/issues/478. Regarding retrieving the app version you can use this plugin: https://www.npmjs.com/package/nativescript-appversion
