### ISSUE TITLE
emulate android command does not detect failed to start emulator

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#645]
Sometimes the emulator cannot start or exits unexpectedly. For example, there may be a configuration issue. In this case, the CLI waits until a timeout expires, which in some case may be infinite.

**Comment by teobugslayer** [comment]
The technical issue is that emulator.exe starts a sub-process which does the actual work and immediately stops with success exit code. We cannot simply check for exit code.

In Android Studio Beta 5 and accompanying SDK emulator.exe stays alive and we can check its exit code.

**Comment by dtopuzov** [comment]
{N} CLI in master with latest Android tooling, Intel HAXM not installed and x86 emulator:

C:\Users\topuzov>tns emulate android --path TestApp
Starting Android emulator with image Emulator-Api21-Default
....
and it hangs with out any logs.

When run with --log trace:

```
Looking for project in 'C:\Users\topuzov\TestApp'
Project directory is 'C:\Users\topuzov\TestApp'.
Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'emulate|android'.
Statistics was sent successfully (xhr).
startLookingForDevices; platform is Android
spawn: D:\adt-bundle\sdk\platform-tools\adb "start-server"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: D:\adt-bundle\sdk\platform-tools\adb "devices"
execFile: D:\adt-bundle\sdk\platform-tools\adb "devices"
Starting Android emulator with image Emulator-Api21-Default
spawn: D:\adt-bundle\sdk\tools\emulator "-avd" "Emulator-Api21-Default"
execFile: D:\adt-bundle\sdk\platform-tools\adb "devices"
execFile: D:\adt-bundle\sdk\platform-tools\adb "devices"

````

Not very good user experience.

**Comment by dtopuzov** [comment]
No infinite wait with {N} CLI 3.0.0. After timeout now we say:
```
Searching for devices...
Starting Android emulator with image Emulator-Api25-Google
Cannot run your app in the native emulator. Increase the timeout of the operation with the --timeout option or try to restart your adb server with 'adb kill-server' command. Alternatively, run the Android Virtual Device manager and increase the alloc
ated RAM for the virtual device.
```
