### ISSUE TITLE
tns plugin add must be run on project before tns platform add

### ISSUE THREAD

**Issue by anarchicknight** [NativeScript/nativescript-cli#669]
{N} v1.1.2

Whilst working on my TextToSpeech plugin I ran in to an issue where the plugin was not showing up correctly in a demo project.

With help from TJ it appears that the `tns plugin add` command needs to be run on the project before any platforms are added with the `tns platform add` command, which is not expected behaviour

**Comment by tjvantoll** [comment]
Thanks @anarchicknight for creating this. I can confirm that I've ran into this as well. If you install a plugin you need to recreate your platform in order for the plugin to make it into `tns_modules`, at least for iOS.

This also came up in the forums https://groups.google.com/forum/#!topic/nativescript/C0iu-RtozsI.

**Comment by anarchicknight** [comment]
I can confirm it is also affecting the Android side of things

**Comment by Fatme** [comment]
This issue is already fixed and the fix will be included in 1.2 release.

**Comment by Robophil** [comment]
whats the solution to this? @Fatme
