### ISSUE TITLE
Use the default sync command to sync only changes

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-cli#674]
Currently the sync command requires --watch to sync the changed files only. Can we switch this to not require --watch and the tns sync to do this by default.

**Comment by ligaz** [comment]
Usually those commands that do `watch` are triggered explicitly by using a switch.

**Comment by teobugslayer** [comment]
After personal meeting we decided to leave the current behavior. If people want --wait by default, we will implement it.
