### ISSUE TITLE
Enable "tns debug" default option

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#682]
Lets have the ```--debug-brk``` to be the default option of the ```debug``` command.

**Comment by tjvantoll** [comment]
+1

**Comment by vchimev** [comment]
```tns debug``` without ```--debug-brk``` option does not start the debugger

Possibly causes: https://github.com/NativeScript/nativescript-cli/issues/722

Tested with: ```tns debug android --emulator```

Console Log: https://gist.github.com/vchimev/2c97c3ec6da5c7feec77
