### ISSUE TITLE
Allow iOS asset catalogs

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#683]
Allow iOS asset catalogs to be added in the app and added to the Xcode project. Also see https://github.com/NativeScript/template-hello-world/issues/22

**Comment by e2l3n** [comment]
Per our discussion earlier we decided to postpone the implementation of image.xcassets catalogs which would enhance end users. 
The current PRs remove the hardcoding of icon fileset references and update the resources destination path.
