### ISSUE TITLE
"tns platform update android" does not work

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#699]
Precondition:
npm install -g nativescript@1.1.2
tns create MyApp
tns platform add android@1.1.0 --path MyApp

Steps to reproduce:
npm update -g nativescript
tns platform update android

Result:
ENOENT, scandir 'C:\Users\topuzov\AppData\Roaming\npm-cache\tns-android\1.2.0\package\framework'

**Comment by dtopuzov** [comment]
Workaround:
tns platform remove android
tns platform add android

**Comment by rosen-vladimirov** [comment]
Unable to reproduce

**Comment by rosen-vladimirov** [comment]
It looks like the issue is caused by npm cache. It can be reproduced when you manually delete the framework directory under `<npm_cache_folder>\tns-android\1.2.0\package`
