### ISSUE TITLE
Upgrading NativeScript app from 1.1 to 1.2

### ISSUE THREAD

**Issue by paranoid-android** [NativeScript/nativescript-cli#710]
I have an iOS and Android app built with NativeScript 1.1. I am interested in using the 1.2 version of NativeScript. The docs do not describe how to actually change the version. Is it as simple as 

1. Opening ./package.json
2. Changing `"nativescript": { "id":"org.nativeScript.Application", "tns-ios":{"version":"1.1.2"}, "tns-android":{"version":"1.1.0"}}` to `"nativescript": { "id":"org.nativeScript.Application", "tns-ios":{"version":"1.2.0"}, "tns-android":{"version":"1.2.0"}}`
3. Run `npm install` from the command-line.
4. Fix the breaking changes.

Thanks.

**Comment by vchimev** [comment]
Hi @paranoid-android,

we just pushed an article containing instructions how to upgrade a NativeScript application. Please find it here: http://docs.nativescript.org/upgrade-instructions.

**Comment by bfattori** [comment]
Running `tns create TempApp` does not generate a `tns_modules` folder. It also does not appear to create the `lib` folder which contains the Android runtimes. It seems a tad broken for creating new apps...

**Comment by vchimev** [comment]
Hi @bfattori,

please refer to https://github.com/NativeScript/nativescript-cli#create-project for a short summary of the `tns create <App Name>` command. For detailed information about all available commands run `tns help`.
