### ISSUE TITLE
Don't run "npm install" on "tns prepare"

### ISSUE THREAD

**Issue by moll** [NativeScript/nativescript-cli#728]
Hey,

I'm trying to go through why `tns prepare` takes forever on a fairly empty project —22 seconds to be exact. Part of that is `npm install`. There's no point in running that every time I make a change to the source code. I'll run that myself when I actually install something. ;)

**Comment by rosen-vladimirov** [comment]
Hi @moll ,
We are checking if there's a change in the npm modules and if you have changed only your code, npm install should not be executed.

**Comment by moll** [comment]
Well, removing node_modules entirely sped up `tns prepare`, I believe, around 2 times regardless if anything changed. If possible, it'd be nice to disable that beyond its performance impact. Some of us have special setups with special flags we pass `npm` on install. ;-)

Actually, I myself have stopped using `tns prepare` entirely as it never ran faster than 5s, even with no `node_modules`. That made for an awful development cycle. Outputting build artifacts straight to the platform folders ended up taking milliseconds vs 5–22s with `tns`. ;-)

**Comment by rosen-vladimirov** [comment]
Hi @moll 
With latest CLI's version `npm install` is not called anymore on each prepare. In fact in 1.5.0 we will check the dependencies from your project's package.json and we'll verify if each of them is already installed in `node_modules` dir. If everything is installed, we will not call `npm install`.

I hope this will resolve your issue. I'm closing it now, but feel free to contact us in case you still have problems or concerns.
