### ISSUE TITLE
set object and get them

### ISSUE THREAD

**Issue by iamajaymakwana** [NativeScript/nativescript-cli#734]
I am new into Nativescript development and try to learn it. I have query regarding the object set and get into another method.
I am trying to get the location with the getlocation method and set the location in observable object. But when try to get it and provide it to google map. it generates the error.
So I am not able to work with the object.
Can anybody help me that how can I set the value in object and get it back when required?

**Comment by teobugslayer** [comment]
Hello @iamajaymakwana consider checking the {N} [forum](https://groups.google.com/forum/#!forum/nativescript) for such kind of questions.
