### ISSUE TITLE
Stored data on Android physical device lost when app is re-run

### ISSUE THREAD

**Issue by maknz** [NativeScript/nativescript-cli#739]
If you have a physical Android device connected and you use `tns run android`, close the app once it's running, and `tns run android` again, any data stored in Android SharedPreferences will be lost. This behaviour is not present for Android emulators (when the `--emulator` flag is used), nor with iOS on either the simulator or physical device through Xcode.

This is probably due to the uninstall command being issued for physical devices, which is not done for emulators: `Exec "adb" -s 03b153cb13aa7aba shell pm uninstall "com.pocketsmith.mobile"`

**Comment by ligaz** [comment]
It looks like the same applies for SQLite databases.

**Comment by enchev** [comment]
I don't believe that we can do much here.
