### ISSUE TITLE
Platform update command to respect --frameworkPath.

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#743]
Add ability to specify android/iOS runtime to update to by --frameworkPath:
`tns platform update android --frameworkPath <Path>`
`tns platform update ios --frameworkPath <Path>`

**Comment by Plamen5kov** [comment]
This command is already working in CLI v.1.6.1

**Comment by ligaz** [comment]
@Plamen5kov Have you checked that the `--frameworkPath` option is respected? I'm not seeing it in the update code [here](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/platform-service.ts).

**Comment by Plamen5kov** [comment]
@ligaz yes, I downloaded a tgz and tried it out... it printed out version from the tgz's package.json.

**Comment by ligaz** [comment]
Indeed, closing this.
