### ISSUE TITLE
Hardcoded paths getting into project.pbxproj

### ISSUE THREAD

**Issue by karaahmed** [NativeScript/nativescript-cli#759]
For more information refer to the issue form nativescript-ui-samples repo: https://github.com/telerik/nativescript-ui-samples/issues/8

**Comment by maknz** [comment]
:+1:, please please please.

**Comment by Fatme** [comment]
Hi guys,

We've already fixed this issue - https://github.com/NativeScript/nativescript-cli/issues/679. The fix will be included in 1.2.2 version of {N}. We've planned to release today. You can give a try to a new version and let us know if the fix works for you.

**Comment by teobugslayer** [comment]
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/679
