### ISSUE TITLE
LiveSync does not show console logging statements

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#763]
Hi all,

When I use livesync for development, e.g. `tns livesync [platform] --watch`, I expect my console logging statements to get shown in the same terminal that remains open watching for changes, but currently that's not happening. Could this be supported?

Thanks,
TJ

**Comment by emiloberg** [comment]
+1

This is really crucial. Right now you can't do any log statements when using livesync, which kinda defeats the whole purpose of a streamlined development environment. I had to revert to doing full builds again.

**Comment by tjvantoll** [comment]
The other thing I'll add is the livesync also hides stack traces. So if you create a syntax error you have no way of knowing what went wrong.

**Comment by Fatme** [comment]
It is trivial to show device log output for `tns livesync <platform>` but it is a little bit challenging to support it for `tns livesync <platform> --watch`. We'll do our best to include it in `1.3 release` of {N}.

**Comment by emiloberg** [comment]
If it's trivial to add for `tns livesync`, may I suggest that that is done first (and separate) from the `tns livesync --watch`. We can solve the `--watch` functionality other ways in the meantime.

Example: Me, [I already have a gulpscript](https://github.com/emiloberg/oppna-program-reklistan-app/blob/master/gulpfile.js) watching all files (as I'm doing ES2015 to ES5 transpilation). That watch script can easily fire the `tns livesync` (no --watch) command.

**Comment by dmccuskey** [comment]
+1

in the meantime, i've been using another terminal to `tail` the log generated by the simulator (iOS). `~/Library/Logs/CoreSimulator/<sim-id>/system.log`

**Comment by manijak** [comment]
This is still not available?

**Comment by lelong37** [comment]
+10

**Comment by ligaz** [comment]
Hey all,

This feature has been finally implemented for all platforms and emulators/simulators in `1.6.0`. Please give it a try and share your feedback.

**Comment by manijak** [comment]
Doesn't seem to be working here... I still don't see any console.log items when using livesync on ios with the --watch flag

**Comment by tjvantoll** [comment]
> Doesn't seem to be working here... I still don't see any console.log items when using livesync on ios with the --watch flag

@manijak Same here. https://github.com/NativeScript/nativescript-cli/issues/1262 is the open issue to track that.

**Comment by philpalmieri** [comment]
you can run tns debug ios --watch, which shows the debugger with console logging
