### ISSUE TITLE
```tns run android``` throws an error if android platform is not added before that

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#774]
It give you an error message - ```c:\work\SideDrawerPlayGround\platforms\android\build.xml does not exist!```.

The thing is that after that you can't add the android platform because it seems like the ```tns run android ``` command is creating an ```android``` folder.

**Comment by vchimev** [comment]
This issue is resolved as we "add platform on each platform related command" - #785.
