### ISSUE TITLE
"tns library add ios" does not build correct relative paths to referenced frameworks for mdgenerator

### ISSUE THREAD

**Issue by ginev** [NativeScript/nativescript-cli#777]
When using `tns library add ios` the added library is not correctly resolved by the metadata generator because it receives a faulty path to the referenced framework.

**Comment by PanayotCankov** [comment]
For iOS you should be able to open the Xcode project in platforms/ios and edit the framework search paths by hand to use absolute paths instead of relative paths.

**Comment by Fatme** [comment]
This should be tested with latest ios-runtime from release branch.

**Comment by EddyVerbruggen** [comment]
Just a heads-up: even with PR #266 applied locally I it didn't resolve my framework. I had to add the full path instead, like [documented here](https://www.npmjs.com/package/nativescript-barcodescanner#ios-post-installation-step).

**Comment by maknz** [comment]
I haven't tried the actual release, but using `"\"$(PROJECT_DIR)/../../lib/iOS\""` in the pbxproj file manually doesn't solve the issue. In fact, now there's a build-time error of being unable to resolve the framework, instead of a runtime one where the constant is unavailable.

**Comment by Fatme** [comment]
Hi @maknz,

You're right. Using `"\"$(PROJECT_DIR)/../../lib/iOS\""` in the pbxproj file doesn't solve the issue. You need to fix the library output paths in {N} CLI as well. - https://github.com/NativeScript/nativescript-cli/pull/799/files

**Comment by EddyVerbruggen** [comment]
Awesome! With 1.2.3 the [barcodescanner](https://www.npmjs.com/package/nativescript-barcodescanner) no longer needs manual steps to install thanks to this fix. :+1:
