### ISSUE TITLE
Downgrade from latest android runtime to 1.1.0 is not working

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#784]
Downgrade form latest android runtime to 1.1.0 is not working

Note: Tested with latest CLI form master (1.3.0-2015.8.13.1)

Steps to reproduce:
tns create TNS_App
tns platform add android --frameworkPath tns-android.tgz --path TNS_App
node_modules\.bin\tns platform update android@1.1.0 --path TNS_App (and hit "y" key)

Result:
c:\Git\nativescript-cli-tests>node_modules\.bin\tns platform update android@1.1.0 --path TNS_App
? You are going to downgrade to android runtime v.1.1.0. Are you sure? Yes
Cannot read property 'dist.shasum' of undefined

**Comment by Fatme** [comment]
This happens only when the `--frameworkPath` option is used.

**Comment by ligaz** [comment]
This version is now obsolete. Closing the issue for now. If we can replicate it with newer versions we can reopen it.
