### ISSUE TITLE
Node modules with dependencies aren't copied over to tns_modules

### ISSUE THREAD

**Issue by maknz** [NativeScript/nativescript-cli#796]
I want to install the `request` npm module, but it installs a lot of dependencies to its own local `node_modules` folder. However, these aren't copied over to `tns_modules`. So when `request/index.js` is run by {N}, it fails when trying to `require("extend")`.

**Comment by Fatme** [comment]
Hi @maknz,

Can you give us the exact commands that you try to execute?

I just tried the following commands and it works as expected - I can see all dependencies of `request` module into `platforms/androd/assets/app/tns_modules`:

* tns create myApp
* cd myApp
* tns platform add android
* npm i request --save
* tns prepare android

**Comment by maknz** [comment]
Hmm, I tried the steps above and it worked. Not sure how I managed to get `request` into the platform without its own `node_modules`. All seems well, will open an issue if I see it again and can reproduce.

**Comment by ligaz** [comment]
Good to hear that everything is working fine on your end. I will close this issue for now but feel free to re-open it if this happens again.
