### ISSUE TITLE
Plugin add does not merge plugin's info.plist

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#797]
Consider following scenario: A developer wants to consume a {N} plugin which has custom info.plist using plugin add command.

In this scenario, {N} CLI looks for incorrectly named info.plist file in the plugin. Furthermore, the code does not correctly merge the contents of plugin info.plist file.

**Comment by vchimev** [comment]
The issue is reproducible with 1.3.0 release candidate.
