### ISSUE TITLE
Error executing command 'Java' on `OSX Yosemite 10.10.3`

### ISSUE THREAD

**Issue by heldrida** [NativeScript/nativescript-cli#803]
Hi,

I'd like to report that when running the command:
 tns platform add android

I get the error message:
 Error executing command 'java'. Make sure you have java installed and added to your PATH.

or, when running the `doctor`:

You will not be able to build your projects for Android.
To be able to build for Android, download and install Apache Ant and
its dependencies as described in http://ant.apache.org/manual/index.html

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

These warnings are just used to help the NativeScript maintainers with debugging if you file an issue.
Please ignore them if everything you use NativeScript for is working fine.

On bash_profile:
export JAVA_HOME="`/usr/libexec/java_home -v '1.8*'`"
export ANT_HOME=/usr/local/Cellar/ant/1.9.6/bin
export ANDROID_TOOLS=/usr/local/Cellar/android-sdk/24.3.3/tools
export ANDROID_PLATFORM_TOOLS=/usr/local/Cellar/android-sdk/24.3.3/platform-tools

export PATH="$PATH:$ANT_HOME:$JAVA_HOME/bin:$ANDROID_TOOLS:$ANDROID_PLATFORM_TOOLS"

When running `ant --execdebug`:

xec "/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java" -classpath "/Users/helder/Applications/apache-ant-1.9.6/bin/lib/ant-launcher.jar" -Dant.home="/Users/helder/Applications/apache-ant-1.9.6/bin" -Dant.library.dir="/Users/helder/Applications/apache-ant-1.9.6/bin/lib" -Djikes.class.path=":/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/alt-rt.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/alt-string.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/charsets.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/classes.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/dt.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jce.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jconsole.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jsse.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/management-agent.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/ui.jar" org.apache.tools.ant.launch.Launcher -cp ""
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/tools/ant/launch/Launcher
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by teobugslayer** [comment]
Hi @heldrida,

I guess your problem was that you were using Java 1.6, right? In our next major release of {N} we will detect and warn this.

**Comment by heldrida** [comment]
Yes, sorry I've reported, I had to change it manually and add that ln into my bash profile. I wasn't aware it was using the default version in osx.
