### ISSUE TITLE
LiveSync reports an error and stops when editing CSS on windows

### ISSUE THREAD

**Issue by EdCharbeneau** [NativeScript/nativescript-cli#811]
System Specs:
- Windows 8.1 pro
- {N} 1.2.3
- Device LG G4 (5.1)

When using LiveSync with `tns livesync android --watch` editing CSS files reports and error and stops LiveSync. LiveSync can be restarted again successfully until another edit is saved. **This only happens with platform specific CSS files ex: `platform.android.css`**

I tried this with both VS Code and notepad with the same result.

A video documenting the error can be seen here: http://1drv.ms/1Jp1M5s

**Comment by tjvantoll** [comment]
This issue appears to be with `*.android.css` and `*.ios.css` files, and I can also recreate the problem on OS X.

For me changing `*.android.css` files crashes the `livesync` process. Changing `.ios.css` files doesn't crash `livesync`, but I just don't see the changes I made in my `*.ios.css` file actually being applied to my app.

**Comment by teobugslayer** [comment]
@EdCharbeneau , @tjvantoll 

Thanks for reporting this issue. We reproduced it and created a fix which hopefully will be included in 1.3.
