### ISSUE TITLE
"tns platform add android" failing.

### ISSUE THREAD

**Issue by joshjensen** [NativeScript/nativescript-cli#816]
When I run "tns platform add android" I am getting "spawn android ENOENT" as an error. 

It seems to be related to line 145 in android-project-service.js

    _this.runAndroidUpdate(projectRoot, targetApi).wait();

If I comment out this line, I can then run the android update command manually and it works fine.

From what I can tell the folder "/platforms/android" is not being created before the spawn command is called.

    spawn: android update project --path PATH_TO_FOLDER/NativeScript/hello-world/platforms/android --target android-19 --name helloworld"

~~~~
// Here is part of the log just before it fails. I replaced the full path with "PATH_TO_FOLDER"
Package: org.nativescript.helloworld
Name: helloworld
Copying template files...
Using version 1.2.1. 
Using Android SDK 'android-19'.
Android target: android-19
spawn: android update project --path PATH_TO_FOLDER/NativeScript/hello-world/platforms/android --target android-19 --name helloworld
spawn android ENOENT
~~~~

CLI Version - 1.2.4
operating system: OSX 10.10.4
network connection: Wired
proxy usage: None
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by teobugslayer** [comment]
Hello @joshjensen,

I think you have not added correctly the tools and platform-tools directories from Android SDK. You may verify my assumption by running `tns doctor`. If this turns out to be correct guess, please check how to [set up the CLI](http://docs.nativescript.org/setup/quick-setup#the-nativescript-cli).

**Comment by joshjensen** [comment]
@teobugslayer,

Thank you for the reply. I went through the CLI docs to make sure I followed each step. I had run `tns doctor` on completing the setup docs. However on your recommendation I ran it again and I get `No issues were detected.`

**Comment by teobugslayer** [comment]
Hi @joshjensen,

I am sorry to hear that you still have problems. Can you verify that you have installed one of these Android Platforms: 17, 19, 21 or 22? Also, can you successfully run `android` from the command line and see the actual UI working?

**Comment by joshjensen** [comment]
@teobugslayer,

No worries, I just want to get it working. :) Just to be sure I was not missing anything I installed all the Platform API's So I have 8-23 installed. And yep, I can run android from the command line. The UI opens and I can add and remove sdks and what not. 

One thing to note, if I comment out line 145 in android-project-service.js the process completes and the android folder is created. I can then run the command that is causing the error without a problem. 

`android update project --path PATH_TO_FOLDER/NativeScript/hello-world/platforms/android --target android-19 --name helloworld`

I can run the above command from the command line and it updates the project successfully.

**Comment by Fatme** [comment]
Can you try to execute the command above from freshly opened command line?

**Comment by joshjensen** [comment]
Yep, here is the result from the new window. 

````
$ android update project --path PATH_TO_FOLDER/NativeScript/hello-world/platforms/android --target android-22 --name helloworld
Updated project.properties
Updated local.properties
Added file PATH_TO_FOLDER/NativeScript/hello-world/platforms/android/build.xml
Added file PATH_TO_FOLDER/NativeScript/hello-world/platforms/android/proguard-project.txt
````

**Comment by joshjensen** [comment]
@teobugslayer Any thoughts?

**Comment by teobugslayer** [comment]
Hello @joshjensen,

I am sorry for the late reply - we are through a major push for introducing gradle support.

Again, please run the command with added parameter `--log trace` and check the generated log or send it to us. Without the debug information in it we can only guess what's going on.

**Comment by joshjensen** [comment]
@teobugslayer - Can I get your email so I can send you the log dump?

**Comment by teobugslayer** [comment]
@joshjensen,

feel free to use my public e-mail - I've just shown it in my profile.

**Comment by joshjensen** [comment]
Thanks @teobugslayer, I sent you a message.

**Comment by joshjensen** [comment]
For future reference I had `~/LOCATION_OF_ANDROID_FOLDER` in my .bash_profile. The issue was that spawn does not seem to respect "~" as a reference to home on OS X. I changed "~" to "$HOME and it worked perfect.

**Comment by DeepakDonde** [comment]
Hello teobugslayer,
I am getting same issue while running "tns platform add android" command.
Can you please help me resolving this ?
I have attached log trace. 
Please help.
[log.txt](https://github.com/NativeScript/nativescript-cli/files/154179/log.txt)
