### ISSUE TITLE
Fail to build app with nativescript-telerik-ui plugin when it is added before the platform added

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#829]
Steps to reproduce:
```
tns create testApp
cd testApp
tns plugin add nativescript-telerik-ui
tns platform add android
tns build android
```
It fails to build with jar mismatch error (android-support-v4.jar).

The workflow below works as expected:
```
tns create testApp
cd testApp
tns platform add android
tns plugin add nativescript-telerik-ui
tns build android
```
It builds the app successfully.

**Comment by vchimev** [comment]
Related issue: https://github.com/NativeScript/nativescript-cli/issues/827.

**Comment by dtopuzov** [comment]
In iOS it is the opposite, this is working workflow:

node_modules/.bin/tns plugin add nativescript-telerik-ui --path RichUI
node_modules/.bin/tns platform add ios --frameworkPath tns-ios.tgz --path RichUI

This is not working workflow:
node_modules/.bin/tns platform add ios --frameworkPath tns-ios.tgz --path RichUI
node_modules/.bin/tns plugin add nativescript-telerik-ui --path RichUI

**Comment by vchimev** [comment]
I tried to build with version 1.3.0:

- android - as expected both workflows does not work due to the fact that nativescript-telerik-ui plugin is build as Eclipse projects for android.
Build failed. Output: https://gist.github.com/vchimev/c820d34923bc03a70bd2.

- ios - both workflows fail runtime because there are no {N} modules in the native project app/tns_modules, but nativescript-telerik-ui (and nativescript-plugin-appcompat) plugins.
Output: https://gist.github.com/vchimev/b67a08317d97430a0e3f.

**Comment by Fatme** [comment]
1.3 version of {N} CLI should be tested with .aar distribution of `nativescript-telerik-ui` plugin.
