### ISSUE TITLE
tns run android

### ISSUE THREAD

**Issue by vanbumi** [NativeScript/nativescript-cli#837]
When I run tns run android I have this error:

debug:

BUILD SUCCESSFUL
Total time: 16 seconds
Project successfully built

Using  /home/dyo/nativeScript/hello-world/platforms/android/bin/helloworld-debug.apk
Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.

I m using ubuntu 14.0 and device android from axioo picopad, anyone can help?

**Comment by dtopuzov** [comment]
Most likely native tools are not able to find your device.
Try to run "adb devices", if adb is not able to find the device, tns also will be not able to find the device.
In addition you can try to restart adb with following commands:
adb kill-server
adb start-server

**Comment by vanbumi** [comment]
Hi dtopuzov thanks for your reply,

When I do adb devices this is come up:
List of devices attached
LJNJZPNJWWQ8Q4AM	no permissions

is that correct setup to run tns run android?

**Comment by vanbumi** [comment]
update

I have done followed this instruction http://developer.android.com/tools/device.html and http://ptspts.blogspot.co.il/2011/10/how-to-fix-adb-no-permissions-error-on.html Now when do adb device came up:
LJNJZPNJWWQ8Q4AM devices 

But when I run tns run android after built successfully debug start running and never stop for ever 
![screenshot from 2015-09-01 09 14 33](https://cloud.githubusercontent.com/assets/9285653/9601607/f5c93e08-50cc-11e5-8ba1-c2edcce9ba54.png)
(I enclosed the page), what is went wrong??

**Comment by teobugslayer** [comment]
Hello @vanbumi,

This is the output of logcat. NativeScript CLI shows it to aid debugging of your app. If you do not need it, run CLI commands with `--justlaunch`, like:
`tns run android --justlaunch`

NativeScript CLI has extensive help for every command - you can access it using the `help` command, like: `tns help run android`.

**Comment by teobugslayer** [comment]
Please run `tns run android --justlaunch --log tarce > log.txt` and send us the log.txt file (you may create a gist with the contents).

**Comment by Plamen5kov** [comment]
If no app with the specified name comes up then you probably are testing on and old version of android. If you upgrade android or specify a lower target version, app should show up after install.

**Comment by teobugslayer** [comment]
I am closing this issue now. If you need further help with it, please re-open it.

**Comment by jdell64** [comment]
The Genymotion tutorial specifies to make an old version of Android (the one in http://developer.telerik.com/featured/using-android-emulator-hybrid-mobile-apps-telerik-appbuilder/#managing-avds) 
The NativeScript tutorial will not work with this version. 

Suggest updating that version if they have access.

**Comment by Mbatroukh** [comment]
This sounds silly, but you have to make sure that the "Developer Options" are activated on the device itself along with "USB Debugging".
