### ISSUE TITLE
Please support Android SDK 16

### ISSUE THREAD

**Issue by aMarCruz** [NativeScript/nativescript-cli#846]
Android 4.1.x Jelly Bean, SDK 16, still has a significant market share, 13% at august 2015, and I think even more in emerging markets.

https://developer.android.com/about/dashboards/
http://www.idc.com/getdoc.jsp?containerId=prUS25860315
This represents **more than 153 million**? phones with Android 4.1.x that can not use NativeScript :(
(1440 * .82 * .13)

**Comment by teobugslayer** [comment]
Related to https://github.com/NativeScript/android-runtime/issues/198
