### ISSUE TITLE
Possibility to create a new project from existing one along with its dependencies

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#847]
Currently `--copy-from` option of the `tns create <App Name>` command takes as argument the `app` directory of an existing NativeScript project. In this way the newly created project is not aware of the dependencies of the old one described in its package.json file.

It would be nice if there is a possibility to copy not only the `app` folder content, but also project's dependencies (and runtimes versions) information.

**Comment by Fatme** [comment]
You can get the dependencies and/or runtimes versions from old package.json file and use `tns init`.

**Comment by vchimev** [comment]
Yes, but still you have to get them manually.

My idea is for example `--copy-from` option to take as argument package.json file (or the directory of package.json and `app` folder) and include its list of dependencies in the package.json file of the new project. Then you would be able to proceed with `tns install`.

**Comment by PanayotCankov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
Maybe I'm missing something, but what's the business case here? In case you want the same project, can't you just copy the directory and change the `id` in the `package.json` ? Can you point existing IDE that allows copy project (maybe there's such option, but I really can't remember ever using it)?

**Comment by vchimev** [comment]
@rosen-vladimirov 
I see my idea behind this issue to be implemented as `--template` option (https://github.com/NativeScript/nativescript-cli/issues/374#issuecomment-157726025) in 1.6.0. Closing this one.
