### ISSUE TITLE
Certificates and provisions for ios build

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#86]

**Comment by Fatme** [comment]
We've already supported this. The build uses the certificate and provision that are setuped on the machine. Also the user can edit xcconfig file to use any provision/certificate.

**Comment by hvadotnarola** [comment]
@Fatme would you please provide steps to create build with provision and certificate ? I am getting `Certificate is not included in provision's certificates` error. Tried creating certificates as steps mentioned but still getting same error.

Thanks.
