### ISSUE TITLE
Provide option to create project with local tns-core-modules

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#872]
_From @dtopuzov on September 4, 2015 12:9_

Currently tns create does not provide an option to install tns-core-modules from local tgz. 
It will be nice it there is such option.

_Copied from original issue: NativeScript/NativeScript#677_

**Comment by vchimev** [comment]
_From @rosen-vladimirov on September 4, 2015 12:13_

As a workaround you can create the project and point the local tgz after that:
```
tns create app1;
cd app1;
npm i --save <path to .tgz>
```

**Comment by rosen-vladimirov** [comment]
You can use `tns plugin add <path-to-tgz>` - it should work fine.
