### ISSUE TITLE
Plugin variables

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#882]
## myPlugin's package.json: 
```json
"nativescript": {
    "platforms": {
      "android": "1.1.3",
      "ios": "1.2.3"
    },
    "variables": {
        "APP_ID": {
             "defaultValue": "myAppId"
        },
        "APP_NAME": {
        }
    }
  }
```

# Plugin add
{N} CLI will store all plugin variables and their values into project's package.json file:

```json
"nativescript": {
    "id": "org.nativescript.androidTest3",
        "tns-android": {
	    "version": "1.3.0"
	},
        "myPlugin-variables": {
            "APP_ID": "myAppId",
            "APP_NAME": "myAppName"
        }
}
```

## Valid plugin commands:

* `tns plugin add myPlugin --var.APP_ID myNewAppId  --var.APP_NAME myAppName
* `tns plugin add myPlugin --var.APP_NAME myAppName`

## Invalid plugin commands:
* `tns plugin add myPlugin`
* `tns plugin add myPlugin --var.APP_ID myNewAppId`

## Prepare
On prepare  {N} CLI will replace all references of plugin variable with the specified value by plugin add command. 
It seems that it will be enough to respect only `AndroidManifest.xml` and `Info.plist` file. But maybe in some cases {N} CLI should respect .java files as well.

**Comment by PanayotCankov** [comment]
We have a plugin that needs the app's id.

**Comment by Fatme** [comment]
@PanayotCankov I've logged your case as separate issue https://github.com/NativeScript/nativescript-cli/issues/1026 for next release.

**Comment by hdeshev** [comment]
This feature has so much potential :grin: I hope I'm not too late to the party!

What if:

1. We could either replace variable occurrences in the source code, or provide an API to get variable values at run time? This could be used by JS/TS code to read usernames, keys, all sorts of configuration data and modify behavior according to some flag. That makes [feature flags](https://code.flickr.net/2009/12/02/flipping-out/) easy too.
2. Why store the variables in the app package.json file? This limits us to having a single "environment". What if we design this similarly to [Rails environments](http://teotti.com/use-of-rails-environments/) and store variables in different files, possibly named according to some convention. This way we could allow for easy switching between a dev/qa build of an app and a real production one. Users could use that to hit different API endpoints, enable instrumentation, detect when running in a simulator. With some build time tricks, you can even use this to ship a different version of an app to different customers and implement a multi-tenant solution.
