### ISSUE TITLE
Missing App Icon 

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#888]
_From @emiloberg on September 4, 2015 15:10_

Hi,

When I'm trying to upload an app to iTunes Connect, it fails with the error message:
> ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0"

![skarmavbild 2015-09-04 kl 16 39 08](https://cloud.githubusercontent.com/assets/4673048/9686970/f4e874b6-5326-11e5-81ba-791346d86b05.png)

I've replaced all icons in App_Resources (gotten from the hello world project), and there's a 120x120 icon (named `icon-60@2x`)

![skarmavbild 2015-09-04 kl 17 00 24](https://cloud.githubusercontent.com/assets/4673048/9687034/540fa40a-5327-11e5-9e1b-3f0807f795ba.png)

And this is how it looks like in Xcode, all the icons under `Resources`
 
![skarmavbild 2015-09-04 kl 16 59 04](https://cloud.githubusercontent.com/assets/4673048/9687073/954f936c-5327-11e5-804d-0a642e0e9728.png)

That being said. Notice the blue {N} icon in the bottom of the Xcode window. How did that get there? All the blue default icons have been replaced. Could it be that {N} hasn't updated the images as it should?

_Copied from original issue: NativeScript/NativeScript#682_

**Comment by enchev** [comment]
_From @emiloberg on September 4, 2015 15:16_

Looking at Images.xcassets, it's all empty:

![skarmavbild 2015-09-04 kl 17 15 58](https://cloud.githubusercontent.com/assets/4673048/9687242/a2555a14-5328-11e5-8019-69d72d264888.png)

**Comment by enchev** [comment]
_From @emiloberg on September 7, 2015 11:35_

I manually solved this by drag 'n' dropping the icons to the placeholders in the screenshot above. However, this shouldn't really be the case, should it?

Anything I can do to debug this?

**Comment by rosen-vladimirov** [comment]
Hi @emiloberg,

I'm glad you were able to resolve the problem manually.
Support for `Images.xcassets` catalogs is still in our TODO list. NativeScript CLI uses the images from app/AppResources and copies them inside platforms/ios directory. However this should not be a problem and you should be able to upload the application in iTunes - as far as I know, there's no strict requirement to have Images.xcassets catalog. 
I'm not sure what could cause the problem with the images. Can you list the folders in your platforms/ios directory and see if there is some "strange" {N} blue icon? My suspicion is that for some reason, some of the files from app/AppResources were not moved correctly to platforms/ios directory.

Can you reproduce the issue in a newly created project? What are the steps that you are using?

I'm looking forward to hearing from you.

**Comment by mikebranstein** [comment]
I have a newly created project and have the same problem with iOS. Before I could upload my project to iTunes Connect, I had to change the "App Icons Source" from "Don't use asset catalogs" to an AppIcon asset catalog. After the AppIcon asset catalog was created I had to drag and drop, as described above.

**Comment by emiloberg** [comment]
Sorry for taking long time. Now experiencing the same thing as @mikebranstein 

This is  the app I'm trying to deploy: https://github.com/emiloberg/oppna-program-reklistan-app

**Comment by emiloberg** [comment]
However, after drag n dropping images, archiving and uploading to iTunes Connect, I get an error: ITMS-90096 about missing Launch Images.

<img width="509" alt="skarmavbild 2015-10-27 kl 11 21 27" src="https://cloud.githubusercontent.com/assets/4673048/10788687/6dc97f0c-7d79-11e5-8a2c-e96215822de2.png">

**Comment by teobugslayer** [comment]
@emiloberg,

what happens when you add the missing Launch-* images into app-root/app/App_Resources/iOS ? My expectation is that the CLI picks them up and adds them to the produced ipa.

**Comment by emiloberg** [comment]
Nope, no difference :/

When in the build process should {N} pick up the resources from /app/App_Resources/iOS and put them in the right place (and maybe modify some other files if needed)? When I run `tns prepare ios`?, when I run `tns build ios?`. Notice how I'm building from within XCode (as it helps me setting the correct certificates and profiles).

**Comment by ligaz** [comment]
With version `1.6.0` of the CLI we support putting the `Info.plist` file `app\App_Resources\iOS`. Using it you can declare `CFBundleIconFiles` that will be respected by the App Store.

I'm going to close this issue for now. Please use this new one https://github.com/NativeScript/nativescript-cli/issues/649 to share additional feedback.

*P.S. Support for Asset catalogs is logged as https://github.com/NativeScript/nativescript-cli/issues/683*

**Comment by sitefinitysteve** [comment]
Ive been dealing with this icon issue for like 3 days straight, felt like Im going crazy... surely the fix isnt to do what @emiloberg did by manually adding to the Images.xcassets?

Where are we as of 2.01 and why is nothing documented, so many hours burned :/

**Comment by ChrisFlannagan** [comment]
I have tried everything but this 120x120 is killing me, spent all day trying to get it to go up to the store

![image](https://cloud.githubusercontent.com/assets/14016454/16165275/097299fe-34b1-11e6-8535-f4d085fbd670.png)

I have all icons in place, I have migrated to the asset manager and they are all there, but I'm still getting this error.

![image](https://cloud.githubusercontent.com/assets/14016454/16165323/2f003eec-34b1-11e6-87bb-c3d0c80e825b.png)

I'm going crazy trying to get this working!

**Comment by sitefinitysteve** [comment]
@ChrisFlannagan Yeah, this isnt at all documented, and will hit every single person... I think the info.plist doesnt just have these by default.

Answer by @PeterStaev on slack fixed me
https://nativescriptcommunity.slack.com/files/peterstaev/F1E2YK6KS/Info_plist.txt

His GIST
https://gist.github.com/PeterStaev/95b116df2cc9d82868ad67cdac28ad0e#file-Info-plist

Basically just specify all the icons in the infoplist and it'll work (assuming you have all the icons...)  Case sensitive too btw.

**Comment by ChrisFlannagan** [comment]
Well, I finally figured it out.  If you are doing tweaks in xcode to the plist or anything else it can cause issues with the nativescript generated project so you gotta be carful.  I started a fresh nativescript project, copied my core files and icons over including the 120px, then I tns prepare ios it.  Also, nativescript seems to use lowercase i for a lot of icons in the plist when it needs to definitely be capital I based on how most icon generators spit out icons.

**Comment by sitefinitysteve** [comment]
Everything under /platforms should be considered volitile.. when you build the info.plist from App_Resources/iOS is copied down, thats the one you need to change manually... if you're doing this in xcode it's changing the platforms one and you're back in the same boat of it being potentially overwritten (on an upgrade or some other command)

**Comment by ChrisFlannagan** [comment]
yea man, it caused me a big struggle today.  I didn't change anything manually at first but I didn't have the 120px so then I tried to adjust it all manually in xcode to add the 120px icon and that screwed things up big time.

**Comment by PanayotCankov** [comment]
https://github.com/NativeScript/nativescript-cli/issues/1868#issuecomment-227485863
We will use asset catalogs from the next version on, there it should be much easier to setup icons and launch screens.

**Comment by ChrisFlannagan** [comment]
@PanayotCankov one of the biggest things for me which is my mistake but caused me hours of stress is that the default icon names in NativeScript use lower case "i" where almost every mass icon generator I found uses uppercase "I" in Icon filename.

**Comment by PanayotCankov** [comment]
Which icon generators do you use? It would be nice to list them here so we can have them in mind in future.

**Comment by PanayotCankov** [comment]
@ChrisFlannagan Which icon generators do you use? It would be nice to list them here so we can have them in mind in future.

**Comment by ChrisFlannagan** [comment]
@PanayotCankov I've used a few thinking they were generating wrong, but the entire time it was just they use I and not i lol

http://icon.angrymarmot.org/
https://makeappicon.com/
http://appicon.build/

**Comment by sitefinitysteve** [comment]
Exception I suppose being the @mikebranstein one http://nsimage.brosteins.com/Home/UploadIcon

**Comment by mikebranstein** [comment]
The correct URL for my icon generator is http://nsimage.brosteins.com. If you run into any problems, let me know. @ChrisFlannagan 

If you've got suggestions on improvements, please drop me a line.

**Comment by dxshindeo** [comment]
How is this still a thing? Got 120, 76, 152, 167 errors (same as in [this](https://github.com/NativeScript/nativescript-cli/issues/1490) issue, just without launchscreen).
Files exist, I tried adding the following in plist file:
```
    <key>CFBundleIconFiles</key>
    <array>
        <string>icon-76.png</string>
    </array>
    <key>UIPrerenderedIcon</key>
    <true/>
```

.. but now it gives additional error while trying to publish app to app store:
`No image found at the path referenced under key 'CFBundleIconFiles':'icon-76.png'`

**Comment by NickIliev** [comment]
@dxshindeo after renaming the icon I would recommend to remove the platform and rebuild your project to ensure that your renamed icon is delivered to the native project.

**Comment by dxshindeo** [comment]
Ah, I figured out what I was doing wrong. I did:
`tns prepare ios`
but I should have done:
`tns build ios --release`
