### ISSUE TITLE
Inaccurate error message when Android SDK Build tools are not installed

### ISSUE THREAD

**Issue by siyka-marinova** [NativeScript/nativescript-cli#900]
http://screencast.com/t/WaIK7DzQ

The error message in case Android SDK Build tools are not installed says: "You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=22 <=22'."
The "range" part of the message could be improved.

**Comment by rosen-vladimirov** [comment]
This is a valid range in fact, but as you are the second person that points this as error (I still think it is not :smile_cat:  ) I'll try to show another message :)

**Comment by siyka-marinova** [comment]
Agree it's a valid range, but the error message could be improved (maybe remove the range and pick one side of it) :)
