### ISSUE TITLE
Cannot find module 'xmlbuilder'

### ISSUE THREAD

**Issue by Oliver84** [NativeScript/nativescript-cli#908]
When I try to run "tns platform add android", I get an error, "Cannot find module 'xmlbuilder'". Running tns doctor gives me no errors (besides the mac OS warning since I'm no Linux). 

I've tried installing xmlbuilder with npm but I still get this error. What else could it be?

**Comment by Fatme** [comment]
Hi @Oliver84,

Can you give us the exact steps that you try to execute? I've tried this and it works as expected:
* tns create myApp
* cd myApp
* tns platform add android
* npm i xmlbuilder --save
* tns build android

**Comment by Fatme** [comment]
I'm going to close this issue for now. If you still have the error feel free to write here or open an another issue.
