### ISSUE TITLE
Configure livesync excludes

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#913]
`UsbLiveSyncService` has a private array of excluded patterns:

```
private excludedProjectDirsAndFiles = [
	"app_resources"
];
```

Some NPM modules (e.g. Angular2) are pretty huge and contain lots of unnecessary files (2432 files for Angular 2 at the time of this writing) which don't need to be synced to the device. We can speed initial syncs up by excluding files like *.ts, *.map, *.md, certain directories, etc.

It'd be great if we had some file, say `.livesyncignore` where we can list exclusion patterns.

**Comment by ligaz** [comment]
Ideally this should be part of a hook that gets installed somehow (ex. as an npm package). For example the TypeScript transpiling hook can omit the `*.ts` from the LiveSync process, the Angular 2 plugin can omit all Angular specific files, etc.

**Comment by hdeshev** [comment]
I like the hook idea. I still think we may need an ignore file to let developers easily ignore junk shipped with some module we've never heard of, but we can ship that later. (Implemented as a hook, of course! :tada:) .

I can imagine hooks being functions of the type `Array<Path> => Array<Path>`. How do we register those with the CLI?

**Comment by ligaz** [comment]
We are yet to figure this out in the upcoming weeks. We have done some previous [work for AppBuilder CLI](https://github.com/Icenium/icenium-cli/tree/master/lib/hooks) and we will try to leverage it.

**Comment by enchev** [comment]
Most probably related to https://github.com/NativeScript/nativescript-cli/issues/887

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/nativescript-cli/issues/887
