### ISSUE TITLE
TNS 1.3 (Master Issue)

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#924]
If you don't have ANDROID_HOME set; then it will throw a "path.join" error message while trying to install a platform.   To duplicate; just clear your Android_home and do a:
tns platform add android --frameworkPath=tns-android.tgz

And rather than installing it; it acts like it will install but then finally throws an error " Arguments to path.join must be strings" with nothing else to go on...   Took me a little bit of time to actually figure out which path.join was broken...    You might consider running the AndroidToolsInfo.validateInfo function before trying to use the path.join in either getBuildToolsVersion or getAndroidSupportLibVersion -- or throw and error up in the constructor saying the ANDROID_HOME is empty and needs to be set for **tns platform add android** to work...

**Comment by Fatme** [comment]
Hi @NathanaelA,

It seems that you're using an old master branch. I've tested the latest master branch and it shows the following error: `The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.`.

Pull the latest changes from master branch and let me know if it works fine for you.

**Comment by NathanaelA** [comment]
Interesting -- the CLI master should have been yesterdays master; but you are correct the "release" v1.30 does print that error properly.   Thanks for checking...
