### ISSUE TITLE
Updating App_Resources styles.xml kills livesync

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#942]
If I have livesync enabled and change any of the xml styles it crashes with

ENOENT, stat 'c:\Dropbox\Projects\Leap\OutbreakHelp\Mobile\Native\OutbreakHelp\platforms\android\src\main\assets\app\App_Resources\Android\values-v21\colors.xml'

**Comment by rosen-vladimirov** [comment]
Thanks for reporting this @sitefinitysteve 
It looks like changing anything inside `app/AppResources/<platformName>` is causing such ENOENT errors as we are searching for the files from AppResources on incorrect place.
Steps to reproduce:
1) Create new project (`tns create app1`)
2) Add platform, for example Android (`tns platform add android`)
3) Add testFile.xml inside app/AppResources/Android/
4) Deploy your application on the device (`tns run android`)
5) Start livesync: `tns livesync android --watch`
6) Modify testFile.xml created in step 3.
