### ISSUE TITLE
tns now seems to be caching things where it shouldn't

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#943]
I've been struggling all night with my 1.3 app (was fine on 1.2)

Seems that when I change things like adding\removing a style.xml file in App_Resources the only way to get NS to update is to platform remove\add android back in.

Worse was upgrading from 1.2 to 1.3 the entire app, all my custom scripts and views were all cached and loading old versions.  I could change style colors in styles.xml, they get reflected, but any of my views or scripts all ran\debugged as if I changed nothing.  However if I formed invalid xml, well then that would crash the thing, but any other changes wouldn't show up.  tns debug even showed me I was CLEARLY on the old scripts as well.

**CONFUSED**

**Comment by sitefinitysteve** [comment]
Example 
![image](https://cloud.githubusercontent.com/assets/1542376/9951043/be46aa22-5d8f-11e5-8ba4-2a5f36fd52f1.png)

Added the debugger line because there's clearly a bug in there
tns debug android starts up the debugger, but as you can see the debug script does not have any of my changes.

**Comment by rosen-vladimirov** [comment]
Hi @sitefinitysteve, 
May I ask you for the versions of the ios and android runtimes that you are using? In version 1.2.x of CLI and runtimes there are several issues with application's reloading after livesync. If you have used the livesync functionality and you have not updated the tns-ios and tns-android versions, you'll see the last livesynced application. 
Can you try using latest android and ios versions and see if it works for you?

**Comment by sitefinitysteve** [comment]
I'm on {N} 1.3, I have done tns remove\add android multiple times to try to fix it.

So I encountered this this morning as well, and this is what I noticed
1) Livesync always has the latest code (ctrl-c to cancel)
2) Added a debugger line in code
3) tns debug android
4) App fired back up, no debugger line in the code
5) Started livesync BACK up, wait for app to load, kill livesync
6) tns debug android, debugger line is now there and breaking fine

Now I also noticed that my segmentedbar selectedIndexChanged event is also not firing (one of the reasons I needed to debug)

tns doctor reports
C:\Dropbox\Projects\Leap\OutbreakHelp\Mobile\Native\OutbreakHelp>tns doctor
WARNING: You can work with iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Version strings are not in the same format
# doctor
┌─────────┬──────────────┐
│ Usage   │ Synopsis     │
│ General │ $ tns doctor │
└─────────┴──────────────┘

**Comment by rosen-vladimirov** [comment]
Hi @sitefinitysteve 
It looks like you are using older version of Gradle (The message `Version strings are not in same format` is caused by this when running `tns doctor`). Could you try installing gradle 2.3 or later?

**Comment by sitefinitysteve** [comment]
Okay, FYI gradle installs via chocolaty to 2.2.1 per the docs, 2.2.3 (or latest) hasn't been released yet...maybe update the docs to just install manually?

Updating now

**Comment by sitefinitysteve** [comment]
No issues with 2.2.7 all last night *figers crossed*

I will close as to not clog up the works

**Comment by sfeather** [comment]
Adding a note for those driving by, if installing gradle with homebrew, be sure to update your brew to get the latest formulas, then upgrade your gradle to 2.7.

Feel free to  reclose

**Comment by sitefinitysteve** [comment]
Okay, it's happening right now

I added this to my script (wanted to inspect the searchBar object)
        var searchBar = page.getViewById("searchResources");
        debugger;
        searchBar.dismissSoftInput();

tns debug android

...no "debugger" in the result

tns run android
tns debug android

...still no "debugger" in the result

**Comment by Fatme** [comment]
Hi @sitefinitysteve,

We've found the problem on our side and we're working on the fix. 

As a workaround I can suggest you to do the following:
1. Open the source code of {N} CLI - execute `which tns`
2. Open `lib/common/mobile/android/android-device.js` file and add this line `_this.adb.executeShellCommand(["rm", "-rf", "/data/local/tmp/"+packageName+"/fullsync"]).wait();` at the beginning of `deploy` function.

The another option is to execute `adb shell rm -rf /data/local/tmp/<applicationIdentifier>/fullsync && tns run android`.

Hope this will help you.

**Comment by sitefinitysteve** [comment]
I am so happy!  Thanks @Fatme ...will close, hope this makes 1.4
