### ISSUE TITLE
Improve tns build android --help text

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#946]
I did an Android release build for the first time today. And, not being an experienced Android developer, I had no idea what the various `--key-store` options meant.

If there something we can link to in the CLI's help text that explains how to create the key store that the CLI wants? I ended up using Android Studio (see https://developer.android.com/tools/publishing/app-signing.html#studio), but I'm not necessarily sure that's the process we want to recommend.

Also one trivial suggestion: currently all four `--key-store-*` options include the two sentences *“You can use the --key-store- options along with --release to produce a signed release build. You need to specify all --key-store- options.”* This repetition adds clutter and makes the options a bit hard to read. Could they only be included for the first option?

Let me know what you think. And thanks.

**Comment by lscown** [comment]
:+1: 

Also, there's no documentation on building a release APK.

**Comment by ligaz** [comment]
We are preparing a `publish` CLI command that should streamline this scenario. Let's contuniue the discussion there https://github.com/NativeScript/nativescript-cli/issues/1172.

Regarding the docs here is our current article on the subject: https://docs.nativescript.org/core-concepts/releasing-apps
