### ISSUE TITLE
Being able to specify the WebView client (specifically WebChromeClient)

### ISSUE THREAD

**Issue by svalchinov** [NativeScript/nativescript-cli#948]
I'm currently trying to get a WebView to work on a 4.2 HTC One.

The WebView is loading a MJPG stream that works perfectly in Chrome and Firefox but not the stock browser.

It'd great if we can force/specify the engine the WebView needs to use.

[WebChromeClient](http://developer.android.com/reference/android/webkit/WebChromeClient.html)

**Comment by ligaz** [comment]
This issue was moved to NativeScript/NativeScript#796
