### ISSUE TITLE
Add an error/warning for old CocoaPods versions

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#949]
@fealebenpae helped me through an issue with CocoaPods, where the problem ended up being that I was using an older version of CocoaPods.

Is it possible (and a good idea) to have `tns doctor` and/or `tns plugin add` show an error when the user is using an older version of CocoaPods? For now I think we'd want to require 0.38.x+.

Let me know what you think. And thanks.

**Comment by rosen-vladimirov** [comment]
Hi @tjvantoll 
I like the idea and it sounds reasonable. I'm wondering what is the best way to check the version of CocoaPods? If I try `gem which cocoapods` I receive something like:
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/rb` - is the 0.35.0 the version that we have to verify? Do you have any idea for another command that will give is the version of the cocoapods?

**Comment by ligaz** [comment]
What about `pod --version`?

**Comment by tjvantoll** [comment]
> What about pod --version?

:+1: That's what I've been using.

**Comment by rosen-vladimirov** [comment]
Ok, thanks, I've added it to 1.4.0 milestone.

**Comment by dtopuzov** [comment]
Error message if CocoaPods is old or missing:
WARNING: CocoaPod is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
