### ISSUE TITLE
Force emulator to run with specific iOS version?

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#952]
_From @emiloberg on September 21, 2015 12:58_

Hi,

All of a sudden (might be connected with me updating to 1.3.0), when I run `tns emulate ios --device iPhone-5`, my iOS simulator gives me: 

> The iOS 7.1 simulator runtime is not available.
> Unable to open liblaunch_sim.dylib. Try reinstalling Xcode or the simulator runtime. 

![skarmavbild 2015-09-21 kl 14 52 01](https://cloud.githubusercontent.com/assets/4673048/9992163/68b88358-6070-11e5-8a21-b5151dce3c27.png)

This is most probably because Xcode 7 (7A220 in my case)/Yosemite dropped support for simulating iOS 7.x. However, how can I make `tns emulate ios --device iPhone-5` use iOS 8.x instead of 7.x?

Running `tns emulate ios --device iPhone-6` (n.b iPhone __6__) works as it opens the emulator with iOS 8.1.

_Copied from original issue: NativeScript/NativeScript#794_

**Comment by enchev** [comment]
_From @emiloberg on September 22, 2015 7:11_

Looking at Xcode, there's no such thing as a 7.1 simulator (as Xcode 7 doesn't support it):

<img width="218" alt="skarmavbild 2015-09-22 kl 09 08 41" src="https://cloud.githubusercontent.com/assets/4673048/10012590/9f2a1534-6109-11e5-8361-60e48b3fd497.png">

**Comment by enchev** [comment]
_From @manijak on September 22, 2015 8:32_

I haven't installed Xcode7 yet. I've heard that {N} modules are not supported in iOS 9?

Does this mean that iOS7 apps are no more? And users of iPhone3 & 4 are out? We can focus on developing apps that are 8.x > ?

**Comment by enchev** [comment]
_From @emiloberg on September 22, 2015 8:55_

This doesn't mean that you can't build iOS7 apps (as far as I understand it), it just means that you can't use the emulator iOS 7 emulator.

**Comment by maknz** [comment]
+1 this would be good. We're just building in Xcode for now.

**Comment by protonmesh** [comment]
I encountered the same problem after recently upgrading to XCode 7.

``isim device-types`` showed that the older iOS 7 simulator runtime was still available was not deleted (The XCode upgrade correctly deleted the iOS 8 runtime, which was bundled in with XCode 6. I suspect the reason the 7 runtime was not automatically deleted is because it was installed manually from the Preferences -> Downloads -> Components section. 

Regardless, the way I forced using the latest iOS 9 simulator runtime is simply deleting `/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/` directory.

Now running `isim device-types` showed only the iOS 9 devices and simulator was starting properly.

**Comment by teobugslayer** [comment]
With the latest master you can select devices using `tns emulate ios --device "iPhone5"` - nothe the device name has changed. This will be released with 1.5.0.

**Comment by emiloberg** [comment]
How is this a change? Appart from the removal of the dash.

**Comment by dtopuzov** [comment]
Yes, --device now do not use the format with dashes. --device should specify the name of Simulator you see in the Xcode UI (name which is listed by "xcrun simctl list devices").

**Comment by dtopuzov** [comment]
{N} CLI 1.5.0 will support Xcode 7 and 7.1, we hope it will be live next week.

**Comment by emiloberg** [comment]
I still don't get it.

How  to choose iOS version? I have loads of a different, let's say iPhone 6, emulators. I've one for iOS 8.0, one for 8.1, 8.2, 8.3, 8.4, 9.0, 9.1 and so on. How do I start emulate a iPhone 6 with iOS 8.0 and another iPhone 6 with iOS 9.1 ?

**Comment by dtopuzov** [comment]
Ok I've got your idea and will reopen the issue. 

With {N} 1.5 you should create emulator with unique name and use it in --device option. 
Currently we don't have way to handle ambiguous simulators (with same name).

May be in future we can extend --device option, so user is able to specify both device name and version.

**Comment by emiloberg** [comment]
As this is the way XCode sets up the Emulators per default, I'd say you'd want to support doing `--device iPhone-6 --sdk 8.0`

**Comment by Fatme** [comment]
Hi @emiloberg,

With {N} 1.5 you'll be able to specify --sdk option to emulate command.

**Comment by rosen-vladimirov** [comment]
Hm, I'm not sure what happened here, but this feature is available in our 1.5.2 release. The option is --sdk, for example:
`tns emulate ios --sdk 9.2`
