### ISSUE TITLE
Install nativescript v1.3.0 on windows problem

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#953]
_From @weilitao on September 20, 2015 2:45_

When I follow the instruction to install nativescript v1.3.0 on windows,  There is an error during the instillation process: 

```
WARNING: You can work with iOS only on Mac OS X systems.                                                       
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.                        
                                                                                                               
Version strings are not in the same format                                                                     
Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.             
    at Errors.fail (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:85:28)   
    at Errors.failWithoutHelp (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.j
s:96:14)                                                                                                       
    at HtmlHelpService.convertCommandNameToFileName (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescri
pt\lib\common\services\html-help-service.js:100:30)                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\html-help-service.js:12
0:36                                                                                                           
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\html-help-service.js:13
2:68                                                                                                           
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\commands\help.js:26:87          
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\commands-service.js:55:
55                                                                                                             
    at Function.settle (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future
.js:249:26)                                                                                                    
    at FiberFuture.Future.wait (C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\node_modules\fiber
s\future.js:534:10)                                                                                            
    at C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:109:40                
nativescript@1.3.0 C:\Users\Litao\AppData\Roaming\npm\node_modules\nativescript        
```

This is what the command 'tns doctor' show:
```
λ tns doctor
WARNING: You can work with iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Version strings are not in the same format
# doctor
┌─────────┬──────────────┐
│ Usage   │ Synopsis     │
│ General │ $ tns doctor │
└─────────┴──────────────┘

Checks your system for configuration problems which might prevent the NativeScript CLI from working properly.
```

Does it mean my installation is OK or not? 

Thanks.

_Copied from original issue: NativeScript/NativeScript#784_

**Comment by enchev** [comment]
_From @NathanaelA on September 20, 2015 3:11_

Are you by any chance running Node v4.x?   If so, downgrade to v0.12.x then do the install of nativescript.

**Comment by enchev** [comment]
_From @weilitao on September 20, 2015 5:26_

No, I already use node v0.12.7. It only show `Error: Unknown command 'dev-post-install'`, other looks ok.

**Comment by enchev** [comment]
_From @dtopuzov on September 20, 2015 9:25_

Try to clean your npm cache with "npm cache clean"

**Comment by enchev** [comment]
_From @weilitao on September 20, 2015 15:20_

@dtopuzov  I have tried as you said, the error doesn't change.

**Comment by enchev** [comment]
_From @NathanaelA on September 21, 2015 7:46_

@weilitao, just to make sure the instructions from @dtopuzov are clear you need to do a

1. npm remove nativescript -g
2. npm cache clean
3. npm install nativescript -g

The cache cleaning won't have any affect until you re-install it.  And you should de-install it first, then clean, then install.

**Comment by enchev** [comment]
_From @weilitao on September 21, 2015 7:55_

I have tried these steps, but the error `Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.` is still here. And I try to execute `tns help`, it is true no command `dev-post-install` listed here.

BTW, I try to compile the tutorial on android, everything looks ok.

**Comment by enchev** [comment]
_From @emmanuelbuah on September 21, 2015 19:36_

I had the same problem and removing, cleaning cache and installed worked for me. I also installed the last version of node v0.12.x.

**Comment by enchev** [comment]
_From @weilitao on September 22, 2015 3:3_

@emmanuelbuah I don't know why it doesn't work for me. 
Does anyone know what the command 'dev-post-install' do? I have already compiled some sample projects and no problem during compilation and execution.

**Comment by rosen-vladimirov** [comment]
Hi,

The "dev-post-install" command is called when the installation process is finished in order to generate the html help pages used by nativescript-cli and to enable autocompletion of commands. All actions executed by this command can be executed manually, for example you can try executing
```
tns help
```
and this will generate the html pages in case they are missing. 
Also you can use 
```
tns autocomplete enable
```
in order to enable command autocompletion.

You should still be able to use nativescript-clit even when "dev-post-install" command fails.

However there seems to be a problem, this is the message that's worrying me:
```
Version strings are not in the same format
```

@weilitao, may I ask you to do the following:
1) Find the installation folder of `nativescript-cli` (command `which tns` or `where tns` should help you)
2) Locate the config directory inside the installation folder and open it - you will find config.json file there.
3) Open the config.json and set DEBUG to true.
4) Execute `tns doctor > out.txt` and send us the out.txt file in order to investigate the reason of the failure.

I'm looking forward to hearing from you.

**Comment by weilitao** [comment]
@rosen-vladimirov  Follow your instruction, I have executed: tns doctor > out.txt 2>&1.  The result is located here: https://www.dropbox.com/s/0q29p1uiopl9qjr/out.txt?dl=0

**Comment by rosen-vladimirov** [comment]
Thanks @weilitao . From the output it seems there's a difference between the version of Gradle that we expect and your currently installed. You are using `2.2.1`, but we need at least 2.3
May I ask you to try updating your version and try again?
I'm looking forward to hearing from you.

**Comment by weilitao** [comment]
@rosen-vladimirov I have used Chocolatey to install Gradle and Gradle in Chocolatey is 2.2.1. So I upgraded Gradle to latest official version(2.7) and everything works ok, the error messages disappear.  Much thanks.

**Comment by rosen-vladimirov** [comment]
Hi @weilitao ,
I'm glad you've solved the issue. Unfortunately the version 2.3 is not approved for Chocolatey, I expected this to happen earlier, that's why I've kept our documentation that describes how to install gradle with Chocolatey. Hopefully the version will be approved very soon.

I'm closing this thread, but feel free to contact us in case you have any other problems or concerns!
