### ISSUE TITLE
DVTAssertions error 

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#955]
_From @Alphapage on September 21, 2015 15:58_

Hello,

I get this error when I first "tns emulate ios" on fresh OS X 10.10.5 and Xcode 7 iPhone 6s emulator:

2015-09-21 08:47:11.115 node[2296:22124] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8201/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x101d924a0>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x100c13300>{number = 1, name = main}

Thanks in advance for your help.

_Copied from original issue: NativeScript/ios-runtime#324_

**Comment by Fatme** [comment]
Hi @Alphapage,

{N} CLI uses external library to deploy on emulator. It seems that this library does not work correctly with Xcode 7. I've added this issue to 1.5.0 milestone.

In the meantime you can use `xcrun` to deploy on emulator. You need to do the following:
1. Build your application for emulator - `tns build ios`.
2. Start iOS simulator
3. Execute `xcrun simctl install booted platforms/ios/build/emulator/<your project name>.app`

**Comment by dtopuzov** [comment]
{N} 1.5 should work fine with Xcode7 simulators.
