### ISSUE TITLE
Version 1.3 - Can't work behind the proxy

### ISSUE THREAD

**Issue by aaronluo** [NativeScript/nativescript-cli#959]
I am using NativeScript 1.3.0 behind my company's proxy. I edit the config.json under NativeScript npm  installed folder to enable the proxy, but it doesn't work.

**Comment by Fatme** [comment]
Hi @aaronluo,

Can you give us more information? What exactly have you changed in `config.json`? Does any error appear?

**Comment by aaronluo** [comment]
Hi Fatme,
I changed USE_PROYX, PROXY_PORT and PROXY_HOSTNAME which are addressed in NS user guide.

I can't remember error message, but in general it says connection timeout when I run 'tns platform add android' command

{
	"DEBUG": false,
	"USE_PROXY": true,
	"PROXY_PORT": 8080,
	"PROXY_HOSTNAME": "web-proxy.atl.hp.com",
	"TYPESCRIPT_COMPILER_OPTIONS": {},
	"CI_LOGGER": false,
	"ANDROID_DEBUG_UI_MAC": "Google Chrome"
}

**Comment by Fatme** [comment]
@aaronluo can you try to execute the following commands:
`npm config set proxy http://web-proxy.atl.hp.com` or `npm config set https-proxy web-proxy.atl.hp.com`
and
`npm install -g tns-android`?

**Comment by teobugslayer** [comment]
I am closing this issue as there is no further information. Do not hesitate to re-open it if you need further help.
