### ISSUE TITLE
Ver 1.3.0 installation error on Mac OS

### ISSUE THREAD

**Issue by aaronluo** [NativeScript/nativescript-cli#968]
I am installing NativeScript 1.3.0 on my Mac and following the setup instruction but failed at installing native script. 

Below is the error information

child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/aaronluo/.node-gyp/0.12.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nativescript/node_modules/ref/.node-gyp"
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/nativescript/node_modules/ref
gyp ERR! node -v v0.12.6
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok 
Build failed

**Comment by rosen-vladimirov** [comment]
Hi @aaronluo ,
It looks like one of the required libraries is missing on your machine:
```
ld: library not found for -lgcc_s.10.5
```
Maybe there's some problem with your XCode installation. Also I've noticed you are using pangyp, may I ask you to install latest version of node-gyp and try again.

**Comment by teobugslayer** [comment]
Can you try again with the just released NativeScript 1.4.3?

**Comment by rosen-vladimirov** [comment]
As a side note, I've faced a similar error in the last days and this helped me to resolve it:
```
cd /usr/local/lib
sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
```

**Comment by rosen-vladimirov** [comment]
Hi @aaronluo ,
As we have not heard back from you for a while, I'm closing this issue. Feel free to write back to us in case you still have this problem :)
