### ISSUE TITLE
LiveSync fails if .apk has a space in name

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-cli#969]
My App.apk fails to deploy with error: 'Unable to find .apk in path...'

If I config the CLI to build it with a hypen or removing the space entirely it will deploy the app to the device with livesync. I'll test some more situations later but wanted to get this out there asap for an explanation. I'm a web guy so sorry if this is something about Android specifically. :)

**Comment by teobugslayer** [comment]
Hello @bradmartin,

Which version of NativeScript are you using? I have just tried creating an application named `my app` and was able to successfully deploy and livesync it to my android phone using NativeScript 1.3.0.

Can you run the failing command with --log trace and send me the log of the failing operation? The command line should look like:

> tns livesync android --log trace > log.txt

**Comment by bradmartin** [comment]
Just emailed you the .txt file.

**Comment by bradmartin** [comment]
I tried a fresh {N} app with cloning the  sample-Groceries app and I can't reproduce the issue. I must have done something else to blow this up. Don't think there is any issue here. Thanks for testing that @teobugslayer
