### ISSUE TITLE
Installation problem OSX

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#970]
_From @PoluosmakAndrew on September 28, 2015 8:36_

There are a lot of errors during installation

Yosemite 10.10.5 (14F27)
Mac: 12-inch, Early 2015 (1.1 GHz Intel Core M)

Installation log file
https://drive.google.com/a/digicode.net/file/d/0B8PdNW5GOHwSdXhpRE9Zemt6M1k/view?usp=sharing

Can you help me?

_Copied from original issue: NativeScript/NativeScript#831_

**Comment by vchimev** [comment]
Hi @PoluosmakAndrew,

I don't have permission to access this file, could you please change its sharing options?

Thanks.

**Comment by PoluosmakAndrew** [comment]
@vchimev I did it

**Comment by Fatme** [comment]
Hi @PoluosmakAndrew,

I see that you're using node 4.0.0. Unfortunately {N} CLI doesn't support node 4.0.0. We have native dependencies that doesn't work with node 4.0.0. We're working closely with their owners to resolve the issues. In the meantime you need to downgrade your node version to 0.12.x.

**Comment by PoluosmakAndrew** [comment]
@Fatme  thanks

**Comment by Fatme** [comment]
I'm going to close this issue. You can check the progress for node 4.0 support here https://github.com/NativeScript/nativescript-cli/issues/958
