### ISSUE TITLE
Sequential Animation separating animations that should be played together

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-cli#973]
There is a problem with sequence animations, which should be bundled up together.
Where instructions that are meant to be played together are played one by one.

The below animation sequence is executed in 4 steps instead of 2.
1)Change width to: 0.8
2) Change height to: 0.8
3) Change width to: 1.2
4) Change height to: 1.2

Instead of:
1) Change width to: 0.8 and height to: 0.8
2) Change width to: 1.2 and height to: 1.2

```
var animationModule = require("ui/animation");
var animationChain = [
                        { target: view1, scale: { x: 0.8, y: 0.8 } },
                        { target: view1, scale: { x: 1.2, y: 1.2 } }
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
```

The same applies when the animation chain is based on translate.
First the component will move right and then after that it will move down.
Instead of moving across right-down.
```
animationChain = [
                        { target: view1, translate: { x: 100, y: 100 } }
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
````

And finally combining multiple animations in one step doesn't seem to work either.
The below animation executes in 3 steps instead of one.
```
animationChain = [
                        { target: view1, translate: { x: 100, y: 100 } , rotate: 270}
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
````

**Comment by Fatme** [comment]
This issue was moved to NativeScript/NativeScript#833
