### ISSUE TITLE
Android APK Deployment: Storage Errors Unreported

### ISSUE THREAD

**Issue by jbristowe** [NativeScript/nativescript-cli#979]
The NativeScript CLI fails to report a deployment failure via ADB if the Android emulator storage becomes full. This is non-optimal and creates a confusing situation where developers think the APK has been cached.

Request: Ensure that ADB deployment failures are reported through the CLI.

**Comment by Fatme** [comment]
Related: https://github.com/NativeScript/nativescript-cli/issues/1060

**Comment by Plamen5kov** [comment]
@teobugslayer, @rosen-vladimirov 
i think this can be closed.

**Comment by rosen-vladimirov** [comment]
Nope, we've not implemented parsing of adb failures. It's in my TO-DO list, I'll raise the priority of this feature.
