### ISSUE TITLE
tns uses configuration files isntead of assuming dependencies are pre-configured by the user

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#985]
Issue
=====

To work properly, tns requires complex set up by user. The customer needs not only to install various components, but also do unusual steps, like globally configuring PATH and other environment variables.

Feature
======

Introduce configuration file, say ~/.nativescript/config.json (exact location on file system is debatable and probably different on different host OSes). In it, we store all the paths to executables we need. This would be:
 * adb
 * android
 * geny executables
 * gradle
 * etc

Furthermore, we store values for environment variables like:
 * JAVA_HOME
 * ANDROID_HOME
 * etc

Tns should encapsulate all calls to external tools and make sure that the environment is prepared for their successful execution:

 - if an environment variable (say ANDROID_HOME) is already set in tns environment, use it
 - otherwise, read its value from the config file, and construct environment for the child process to include it
 - read the path to the executable from the config file. If present, use it.
 - otherwise, try executing it expecting it to be in the PATH (current behavior)

Implementation details
====

* When the user executes the first command which needs this configuration, we interactively prompt him to fill in the missing configuration details.
* If we decide to create GUI installers, they will create the config.json file and fill in the details
* Code which creates child processes, must be refactored to never plainly use executable names, instead use services to get them
* Code which creates child processes must expect interactive prompts and canceling by the user

**Comment by Plamen5kov** [comment]
I think that's a great idea and as our setting up the environment experience is still heavy on the user is getting better with time, this will boost it ever further.

**Comment by dtopuzov** [comment]
I don't think this is useful idea. 
Having config file will not solve you problem, you still need to install Java, Android SDK and otehr tools. This config will just make your live harder, because usually you need env. variables for other projects and config file will be one more step you should do. 
If it is up to me I'll close the issue.

**Comment by enchev** [comment]
@dtopuzov :+1: 
If you want to have additional settings we can use package.json file. I vote against introducing yet another config file. 

Hey @rosen-vladimirov @Plamen5kov @slavchev @atanasovg what do you think?

**Comment by atanasovg** [comment]
Before I can express an opinion I'd like @teobugslayer to share what problems this config file solves. One major benefit I can see in the proposal is having an entry point where users can manually add/edit variables instead of messing with their environment.

**Comment by slavchev** [comment]
>To work properly, tns requires complex set up by user.

That is correct. However I agree with @enchev that we don't need yet another place for configuration. Maybe it would be better to rethink `tns doctor` or maybe to have something like `tns config`.

**Comment by enchev** [comment]
I'm closing this for now. If you think that this is valuable please reopen the issue.
