### ISSUE TITLE
tns help opens a .txt file with the CLI commands

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-cli#991]
When I run 'tns help' it opens a txt file in notepad.

I figured out from this file that it's actually "TNS --HELP" or "TNS -H" and not "TNS HELP" however when I encounter errors during build or anything else the CLI tells me to run TNS HELP not '--help'

**Comment by Fatme** [comment]
Hi @bradmartin,

`tns help` opens  html help. It seems that your default application for .html files is `notepad`. If you change it to be for example chrome, you'll see the documentation in chrome.

`tns --help` opens console help so the help is shown in console.

**Comment by bradmartin** [comment]
Okay, thanks for the info. I hadn't seen that occur before from other CLI programs so I thought maybe something was off. It might be a good idea to change the informational message in the CLI to let users know of 'tns --help' so they can just view it in the CLI. I didn't know that was an option until digging through the docs and it would have saved me some time if it was in the console instead of 'tns help'.

I know that might be silly but when it opened up the html in notepad, default program I know, I had to then move it to notepad++ to view it and find the other HELP commands.
