### ISSUE TITLE
tns doctor says

### ISSUE THREAD

**Issue by 1amirjalai** [NativeScript/nativescript-cli#999]
You need to have the Android SDK Build-tools installed on your system. You have to install version 22.
it also says that You need to have the latest Android Support Repository installed on your system.

I have android sdk manager 24.4 and i have also install  SDK Build-tools version 22 and also android Android Support Repository is installed.

what's the problem and what is the workaround?

**Comment by sfeather** [comment]
Simply as a point of reference, saw similar during a couple of my installs yesterday. The installer complained about my build tools and android_home environment, despite both being correct.

But tns doctor doesn't find any problems and projects build ok.

**Comment by 1amirjalai** [comment]
also "tns platform add android" throws the above mentioned exception  which is 
You need to have the Android SDK Build-tools installed on your system. You have to install version 22.

**Comment by 1amirjalai** [comment]
ANDROID_HOME user variable refers to a android-sdk directory which has build tools as a sub directory

**Comment by 1amirjalai** [comment]
after reinstalling android everything works fine. but following the instruction https://docs.nativescript.org/getting-started  get me this error 
![error](https://cloud.githubusercontent.com/assets/2786675/10264481/9fcccda6-6a19-11e5-8280-875d0aaf86ec.jpg)

**Comment by 1amirjalai** [comment]
Installing 32 bits version of everything with required version number from the scratch nodeJs  + python 32 bit + itunes 32 bit and ..... made the situation worse now i can't even install nativescript with npm i -g nativescript im on windows machine with vs 2015 enterprise edition installed

**Comment by Fatme** [comment]
Hi @1amirjalai,

I've noticed you're using gradle 1.3. In order to work correctly {N} CLI needs gradle 2.3 or grater.

Can you give us more information about the installation error of {N} CLI?

**Comment by teobugslayer** [comment]
Closing this issue because there was no more information on it. If you need further help, please re-open it.
